/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking
-/
module

public import LeanPool.DavisKahan.ForTauCeti.Analysis.InnerProductSpace.UnitarilyInvariantSeminorm
public import LeanPool.DavisKahan.DavisKahan.Sources.DavisKahan1970.SineTheta.Norms.SingularValueTransport
public import LeanPool.DavisKahan.DavisKahan.OperatorIdeal.ApproximationNumbers.OperatorModulus
public import Mathlib.Data.ENNReal.Inv

/-!
# Unitarily invariant norms generated by a symmetric norming function

Davis and Kahan quantify over an arbitrary normalized unitarily invariant norm.
Section 1 of the paper fixes what that means -- the norm axioms, `‖VKW‖ = ‖K‖`
for unitary `V, W`, `‖uv*‖ = ‖u‖‖v‖` on rank one, no increase under
multiplication by a contraction -- and then fixes the criterion it will use:
"Fan dominance is used in the strong form: `‖K‖ ≤ ‖L‖` for every
unitary-invariant norm iff the inequality holds for every Ky Fan norm."

This module builds one model of that class: the **symmetrically normed ideals in
the Gohberg--Krein sense**, generated by a dimension-coherent normalized
symmetric norming function on finite singular-value lists, the same function in
every matrix size, extended to infinite dimensions as the supremum over finite
singular-value prefixes.

That model is not the whole printed class as a *type*.  A unitarily invariant
norm on `B(H)` such as `T ↦ ‖T‖ + ‖π(T)‖`, with `π` the Calkin quotient map,
satisfies every axiom Section 1 lists and agrees with the operator norm on
finite-rank operators, so no symmetric gauge generates it.  What makes the
source-facing endpoints cover the printed class anyway is that the *estimates*
do not distinguish the models: the Ky Fan gauges are themselves coherent
symmetric norming functions (`Ideals/KyFanNorm.lean`), so a bound proved over
this whole class yields Ky Fan majorization, and
`TauCeti.DavisKahan1970.kyFanDominant_of_symmetricNorming` carries it to every
Fan-dominant unitarily invariant ideal gauge, the Calkin-augmented norm
included.  `symmetricNorming_iff_kyFanDominant` states the equivalence of the
two quantifiers.

This module encodes that source definition directly.  A coherent sequence of
finite-dimensional unitarily invariant norms is equivalent to a normalized
symmetric norming function: finite Fan dominance is already proved for each
member of the sequence, while `zero_pad` identifies the same gauge across
matrix sizes.  No independently chosen operator-membership predicate occurs.
Membership in the completed ideal means exactly that the canonical prefix
supremum is finite.

The principal theorem is `scaled_gauge_le_of_all_kyFan_le`: simultaneous Ky Fan
bounds imply the corresponding inequality for every source-defined norm.  It
is the exact adapter from the compiler-accepted cutoff proof to the universal
norm quantifier in the 1970 paper.
-/

@[expose] public section

namespace TauCeti
namespace DavisKahan
namespace ExactSinTheta

open scoped InnerProductSpace BigOperators ENNReal

noncomputable section

universe u v

/-- Add one trailing zero to a finite singular-value vector. -/
def zeroPad {n : ℕ} (x : Fin n → ℝ) : Fin (n + 1) → ℝ :=
  Fin.lastCases 0 x

/-- A normalized symmetric norming function in the exact dimension-coherent
form used by Davis and Kahan.

The finite member is expressed as a square complex unitarily invariant norm
because the repository already proves the equivalence between such norms and
symmetric gauges.  Its gauge is real and therefore applies unchanged to real
and complex operators, and to rectangular operators through their singular
values. -/
structure SymmetricNormingFunction where
  /-- The normalized, compatible family of finite-dimensional unitarily invariant seminorms. -/
  finiteNorm : ∀ n : ℕ,
    TauCeti.UnitarilyInvariantSeminorm ℂ (EuclideanSpace ℂ (Fin n)) (EuclideanSpace ℂ (Fin n))
  normalized :
    (finiteNorm 1).gauge (EuclideanSpace.basisFun (Fin 1) ℂ)
      (fun _ => 1) = 1
  zero_pad : ∀ {n : ℕ} (x : Fin n → ℝ),
    (finiteNorm (n + 1)).gauge
        (EuclideanSpace.basisFun (Fin (n + 1)) ℂ) (zeroPad x) =
      (finiteNorm n).gauge (EuclideanSpace.basisFun (Fin n) ℂ) x

namespace SymmetricNormingFunction

/-- The finite symmetric gauge associated to the paper norm. -/
def finiteGauge (N : SymmetricNormingFunction) (n : ℕ)
    (x : Fin n → ℝ) : ℝ :=
  (N.finiteNorm n).gauge (EuclideanSpace.basisFun (Fin n) ℂ) x

/-- The first `n` approximation singular values of a rectangular bounded
operator. -/
def approximationPrefix
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (n : ℕ) (A : E →L[𝕜] F) : Fin n → ℝ :=
  fun i => approximationSingularValue (i : ℕ) A

/-- Evaluation of the source norm on the first `n` singular values. -/
def prefixGauge
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (N : SymmetricNormingFunction) (n : ℕ) (A : E →L[𝕜] F) : ℝ :=
  N.finiteGauge n (approximationPrefix n A)

/-- The extended value of the source norm.  It is finite precisely on the
canonical symmetrically normed ideal generated by the source gauge. -/
def extendedGauge
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (N : SymmetricNormingFunction) (A : E →L[𝕜] F) : ENNReal :=
  ⨆ n : ℕ, ENNReal.ofReal (N.prefixGauge n A)

/-- Membership in the source norm ideal is not independent data: it means the
canonical prefix supremum is finite. -/
def Mem
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (N : SymmetricNormingFunction) (A : E →L[𝕜] F) : Prop :=
  N.extendedGauge A ≠ ⊤

/-- The ordinary real-valued norm on its canonical ideal. -/
def gauge
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (N : SymmetricNormingFunction) (A : E →L[𝕜] F) : ℝ :=
  (N.extendedGauge A).toReal

/-- Rewrite form of the finite gauge as a sum over the first `k` singular values. -/
@[simp]
theorem finiteGauge_def (N : SymmetricNormingFunction) (n : ℕ)
    (x : Fin n → ℝ) :
    N.finiteGauge n x =
      (N.finiteNorm n).gauge (EuclideanSpace.basisFun (Fin n) ℂ) x :=
  rfl

/-- Source normalization in one dimension. -/
theorem finiteGauge_one (N : SymmetricNormingFunction) :
    N.finiteGauge 1 (fun _ => 1) = 1 :=
  N.normalized

/-- Coherence under trailing-zero padding. -/
theorem finiteGauge_zeroPad (N : SymmetricNormingFunction)
    {n : ℕ} (x : Fin n → ℝ) :
    N.finiteGauge (n + 1) (zeroPad x) = N.finiteGauge n x :=
  N.zero_pad x

/-- Finite gauges are nonnegative. -/
theorem finiteGauge_nonneg (N : SymmetricNormingFunction)
    {n : ℕ} (x : Fin n → ℝ) : 0 ≤ N.finiteGauge n x :=
  (N.finiteNorm n).nonneg _

/-- Finite gauges are absolutely homogeneous. -/
theorem finiteGauge_smul (N : SymmetricNormingFunction)
    {n : ℕ} (c : ℝ) (x : Fin n → ℝ) :
    N.finiteGauge n (c • x) = |c| * N.finiteGauge n x :=
  (N.finiteNorm n).gauge_real_smul
    (EuclideanSpace.basisFun (Fin n) ℂ) c x

/-- Finite gauges are subadditive. -/
theorem finiteGauge_add_le (N : SymmetricNormingFunction)
    {n : ℕ} (x y : Fin n → ℝ) :
    N.finiteGauge n (x + y) ≤
      N.finiteGauge n x + N.finiteGauge n y :=
  (N.finiteNorm n).gauge_add_le
    (EuclideanSpace.basisFun (Fin n) ℂ) x y

/-- The sum of a singular-value prefix is the corresponding approximation
Ky Fan gauge. -/
theorem sum_approximationPrefix
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (n : ℕ) (A : E →L[𝕜] F) :
    ∑ i : Fin n, approximationPrefix n A i =
      kyFanApproximationGauge n A := by
  rw [kyFanApproximationGauge]
  simp only [approximationPrefix]
  exact Fin.sum_univ_eq_sum_range (fun m => approximationSingularValue m A) n

/-- Finite Fan dominance for the paper gauge, obtained from the repository's
proved T-transform theorem rather than postulated as extra norm data. -/
theorem prefixGauge_le_of_all_kyFan_le
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (N : SymmetricNormingFunction) {A B : E →L[𝕜] F}
    (h : ∀ k : ℕ, kyFanApproximationGauge k A ≤
      kyFanApproximationGauge k B) (n : ℕ) :
    N.prefixGauge n A ≤ N.prefixGauge n B := by
  let NA := N.finiteNorm n
  let b := EuclideanSpace.basisFun (Fin n) ℂ
  change NA.gauge b (approximationPrefix n A) ≤
    NA.gauge b (approximationPrefix n B)
  apply NA.gauge_le_gauge_of_prefix_sums_le b
  · intro i j hij
    exact approximationSingularValue_antitone A (Fin.le_def.mp hij)
  · intro i
    exact approximationSingularValue_nonneg _ _
  · intro i
    exact approximationSingularValue_nonneg _ _
  · intro m
    rcases le_or_gt m n with hm | hm
    · simp only [approximationPrefix]
      rw [sum_filter_lt_eq_sum_fin hm
          (fun k => approximationSingularValue k A),
        sum_filter_lt_eq_sum_fin hm
          (fun k => approximationSingularValue k B),
        Fin.sum_univ_eq_sum_range
          (fun k => approximationSingularValue k A) m,
        Fin.sum_univ_eq_sum_range
          (fun k => approximationSingularValue k B) m]
      exact h m
    · have huniv :
          (Finset.univ.filter fun i : Fin n => (i : ℕ) < m) =
            Finset.univ :=
        Finset.filter_true_of_mem fun i _ => lt_trans i.isLt hm
      rw [huniv, sum_approximationPrefix n A,
        sum_approximationPrefix n B]
      exact h n

/-- Scaled finite Fan dominance.  This is the exact finite symmetric-gauge
step used in the paper's proof. -/
theorem mul_prefixGauge_le_of_all_mul_kyFan_le
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (N : SymmetricNormingFunction) {A B : E →L[𝕜] F}
    {c : ℝ} (hc : 0 ≤ c)
    (h : ∀ k : ℕ, c * kyFanApproximationGauge k A ≤
      kyFanApproximationGauge k B) (n : ℕ) :
    c * N.prefixGauge n A ≤ N.prefixGauge n B := by
  let NA := N.finiteNorm n
  let b := EuclideanSpace.basisFun (Fin n) ℂ
  have hdom : NA.gauge b (c • approximationPrefix n A) ≤
      NA.gauge b (approximationPrefix n B) := by
    apply NA.gauge_le_gauge_of_prefix_sums_le b
    · intro i j hij
      exact mul_le_mul_of_nonneg_left
        (approximationSingularValue_antitone A (Fin.le_def.mp hij)) hc
    · intro i
      exact mul_nonneg hc (approximationSingularValue_nonneg _ _)
    · intro i
      exact approximationSingularValue_nonneg _ _
    · intro m
      rcases le_or_gt m n with hm | hm
      · simp only [Pi.smul_apply, smul_eq_mul, approximationPrefix]
        rw [sum_filter_lt_eq_sum_fin hm
            (fun k => c * approximationSingularValue k A),
          sum_filter_lt_eq_sum_fin hm
            (fun k => approximationSingularValue k B),
          ← Finset.mul_sum,
          Fin.sum_univ_eq_sum_range
            (fun k => approximationSingularValue k A) m,
          Fin.sum_univ_eq_sum_range
            (fun k => approximationSingularValue k B) m]
        exact h m
      · have huniv :
            (Finset.univ.filter fun i : Fin n => (i : ℕ) < m) =
              Finset.univ :=
          Finset.filter_true_of_mem fun i _ => lt_trans i.isLt hm
        rw [huniv]
        simp only [Pi.smul_apply, smul_eq_mul]
        rw [← Finset.mul_sum,
          sum_approximationPrefix n A, sum_approximationPrefix n B]
        exact h n
  rw [NA.gauge_real_smul b c (approximationPrefix n A),
    abs_of_nonneg hc] at hdom
  exact hdom

/-- Universal Fan dominance for the extended source norm. -/
theorem extendedGauge_le_of_all_kyFan_le
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (N : SymmetricNormingFunction) {A B : E →L[𝕜] F}
    (h : ∀ k : ℕ, kyFanApproximationGauge k A ≤
      kyFanApproximationGauge k B) :
    N.extendedGauge A ≤ N.extendedGauge B := by
  apply iSup_le
  intro n
  exact le_trans
    (ENNReal.ofReal_le_ofReal (N.prefixGauge_le_of_all_kyFan_le h n))
    (le_iSup (fun m : ℕ => ENNReal.ofReal (N.prefixGauge m B)) n)

/-- Universal scaled Fan dominance for every normalized unitarily invariant
norm in the sense of Davis and Kahan. -/
theorem mul_extendedGauge_le_of_all_mul_kyFan_le
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (N : SymmetricNormingFunction) {A B : E →L[𝕜] F}
    {c : ℝ} (hc : 0 ≤ c)
    (h : ∀ k : ℕ, c * kyFanApproximationGauge k A ≤
      kyFanApproximationGauge k B) :
    ENNReal.ofReal c * N.extendedGauge A ≤ N.extendedGauge B := by
  rw [extendedGauge, ENNReal.mul_iSup]
  apply iSup_le
  intro n
  calc
    ENNReal.ofReal c * ENNReal.ofReal (N.prefixGauge n A) =
        ENNReal.ofReal (c * N.prefixGauge n A) := by
      rw [ENNReal.ofReal_mul hc]
    _ ≤ ENNReal.ofReal (N.prefixGauge n B) :=
      ENNReal.ofReal_le_ofReal
        (N.mul_prefixGauge_le_of_all_mul_kyFan_le hc h n)
    _ ≤ N.extendedGauge B :=
      le_iSup (fun m : ℕ => ENNReal.ofReal (N.prefixGauge m B)) n

/-- Finiteness descends through a positive scaled Fan bound. -/
theorem mem_of_all_mul_kyFan_le
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (N : SymmetricNormingFunction) {A B : E →L[𝕜] F}
    {c : ℝ} (hc : 0 < c) (hB : N.Mem B)
    (h : ∀ k : ℕ, c * kyFanApproximationGauge k A ≤
      kyFanApproximationGauge k B) : N.Mem A := by
  have hle := N.mul_extendedGauge_le_of_all_mul_kyFan_le hc.le h
  intro htop
  have hc0 : ENNReal.ofReal c ≠ 0 := ENNReal.ofReal_ne_zero_iff.mpr hc
  rw [htop, ENNReal.mul_top hc0] at hle
  exact hB (top_le_iff.mp hle)

/-- Real-valued universal norm inequality on the canonical ideal. -/
theorem mul_gauge_le_of_all_mul_kyFan_le
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (N : SymmetricNormingFunction) {A B : E →L[𝕜] F}
    {c : ℝ} (hc : 0 < c) (hB : N.Mem B)
    (h : ∀ k : ℕ, c * kyFanApproximationGauge k A ≤
      kyFanApproximationGauge k B) :
    N.Mem A ∧ c * N.gauge A ≤ N.gauge B := by
  have hA := N.mem_of_all_mul_kyFan_le hc hB h
  refine ⟨hA, ?_⟩
  have hle := N.mul_extendedGauge_le_of_all_mul_kyFan_le hc.le h
  have hto := (ENNReal.toReal_le_toReal
    (ENNReal.mul_ne_top ENNReal.ofReal_ne_top hA) hB).mpr hle
  rw [ENNReal.toReal_mul, ENNReal.toReal_ofReal hc.le] at hto
  exact hto

/-- Approximation singular-value prefixes are invariant under adjoint. -/
theorem approximationPrefix_adjoint
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (n : ℕ) (A : E →L[𝕜] F) :
    approximationPrefix n A.adjoint = approximationPrefix n A := by
  funext i
  exact approximationSingularValue_adjoint (i : ℕ) A

/-- Prefix source gauges are invariant under adjoint. -/
theorem prefixGauge_adjoint
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (N : SymmetricNormingFunction) (n : ℕ) (A : E →L[𝕜] F) :
    N.prefixGauge n A.adjoint = N.prefixGauge n A := by
  rw [prefixGauge, prefixGauge, approximationPrefix_adjoint]

/-- **Equal approximation numbers give equal gauges, between different pairs of
spaces.**

`gauge_eq_of_sameApproximationSingularValues` needs the two operators to have the
same domain and codomain.  A source norm sees only the singular-value sequence,
so no such restriction is needed, and the rectangular form is what relates an
ambient projection block `E → E` to its compression `Γ → Ω`. -/
theorem extendedGauge_eq_of_hasSameApproximationNumbers
    {𝕜 : Type u} [RCLike 𝕜]
    {E₁ F₁ E₂ F₂ : Type v}
    [NormedAddCommGroup E₁] [InnerProductSpace 𝕜 E₁]
    [NormedAddCommGroup F₁] [InnerProductSpace 𝕜 F₁]
    [NormedAddCommGroup E₂] [InnerProductSpace 𝕜 E₂]
    [NormedAddCommGroup F₂] [InnerProductSpace 𝕜 F₂]
    (N : SymmetricNormingFunction) {A : E₁ →L[𝕜] F₁} {B : E₂ →L[𝕜] F₂}
    (h : A.HasSameApproximationNumbers B) :
    N.extendedGauge A = N.extendedGauge B := by
  unfold SymmetricNormingFunction.extendedGauge
  refine iSup_congr fun n => ?_
  have hpre : approximationPrefix n A = approximationPrefix n B := by
    funext i
    exact h (i : ℕ)
  rw [prefixGauge, prefixGauge, hpre]

/-- Equality of complete approximation singular-value sequences gives equality
for every paper-defined norm, including simultaneous ideal membership. -/
theorem gauge_eq_of_sameApproximationSingularValues
    {𝕜 : Type u} [RCLike 𝕜]
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]
    (N : SymmetricNormingFunction) {A B : E →L[𝕜] F}
    (h : SameApproximationSingularValues A B) :
    N.extendedGauge A = N.extendedGauge B := by
  apply le_antisymm
  · exact N.extendedGauge_le_of_all_kyFan_le fun k =>
      le_of_eq (h.kyFanApproximationGauge_eq k)
  · exact N.extendedGauge_le_of_all_kyFan_le fun k =>
      le_of_eq (h.kyFanApproximationGauge_eq k).symm

end SymmetricNormingFunction

/-! ## The modulus and the paper norms

These two were in `DavisKahan/OperatorIdeal/ApproximationNumbers/OperatorModulus.lean` until
2026-07-28.  They are the only paper-facing statements that file had, and they were the
whole reason a *generic* module imported this source facade — the backwards dependency the
dependency-layer checker carries as `generic_imports_sources`.  Everything generic in that
file is now staged in
`ForTauCeti/Analysis/OperatorIdeal/ApproximationNumber/SameSequence.lean`, so the two
paper-facing ones move here, where the objects they talk about live. -/

section ModulusPaperNorms

variable {E : Type v} [NormedAddCommGroup E] [InnerProductSpace ℂ E] [CompleteSpace E]

/-- Every current ideal family assigns the same membership and gauge to `T`
and its positive modulus. -/
theorem modulus_mem_and_gauge_eq
    (N : KyFanDominantIdealFamily (𝕜 := ℂ))
    {T : E →L[ℂ] E}
    (hT : N.Mem T) :
    N.Mem (ContinuousLinearMap.modulus T) ∧
      N.gauge (ContinuousLinearMap.modulus T) =
        N.gauge T :=
  SameApproximationSingularValues.mem_and_gauge_eq N
    (modulus_hasSameApproximationNumbers T) hT

/-- Every literal paper norm assigns exactly the same extended value to an
operator and its positive modulus. -/
theorem normingFunction_modulus_eq
    (N : SymmetricNormingFunction) (T : E →L[ℂ] E) :
    N.extendedGauge (ContinuousLinearMap.modulus T) = N.extendedGauge T :=
  N.gauge_eq_of_sameApproximationSingularValues
    (modulus_hasSameApproximationNumbers T)


end ModulusPaperNorms

end

end ExactSinTheta
end DavisKahan
end TauCeti
