/-
Copyright (c) 2026 Arthur Freitas Ramos and coauthors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Arthur Freitas Ramos, David Barros Hulak, Ruy J. G. B. de Queiroz
-/

/-
Original copyright notice:
Copyright (c) 2026 Arthur Freitas Ramos, David Barros Hulak, Ruy J. G. B. de Queiroz. All rights
reserved.
-/

module

public import LeanPool.PoincareGeometry.PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.EuclideanZeroInitialOperator
public import LeanPool.PoincareGeometry.PoincareCurvature.Geometry.Manifold.RicciFlow.AnalyticPDE.TensorHeatFiniteBanach
public import Mathlib.LinearAlgebra.Matrix.Symmetric

/-!
# The matrix-valued zero-initial Euclidean heat solution operator

The scalar Duhamel inverse is applied to every matrix coefficient and the
resulting genuine second jets are assembled into one matrix-valued element of
the finite-cylinder `C^{2+α,1+α/2}` Banach space.  The construction is a
bounded linear map, satisfies the coefficientwise heat equation, has a strong
zero initial trace, and preserves symmetry.
-/

@[expose] public noncomputable section
open Real Set MeasureTheory Metric Filter
open scoped Real BigOperators Interval Topology

namespace RicciFlow
namespace AnalyticPDE

section MatrixZeroInitial

variable {n d : ℕ}

/-- Evaluation of a finite matrix at one coefficient, as a bounded linear
functional for the iterated sup norm. -/
def matrixEntryCLM (d : ℕ) (i j : Fin d) :
    (Fin d → Fin d → ℝ) →L[ℝ] ℝ :=
  (ContinuousLinearMap.proj j : (Fin d → ℝ) →L[ℝ] ℝ).comp
    (ContinuousLinearMap.proj i :
      (Fin d → Fin d → ℝ) →L[ℝ] (Fin d → ℝ))

@[simp] theorem matrixEntryCLM_apply (i j : Fin d)
    (A : Fin d → Fin d → ℝ) :
    matrixEntryCLM d i j A = A i j := rfl

theorem norm_matrixEntryCLM_le (i j : Fin d) :
    ‖matrixEntryCLM d i j‖ ≤ 1 := by
  apply ContinuousLinearMap.opNorm_le_bound _ zero_le_one
  intro A
  rw [matrixEntryCLM_apply]
  simpa only [one_mul] using
    (norm_le_pi_norm (A i) j).trans (norm_le_pi_norm A i)

/-- One scalar coefficient of a global matrix-valued parabolic source. -/
def globalMatrixEntrySourceL
    {α : ℝ} (i j : Fin d) :
    ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
        (Set.univ : Set (ℝ × (Fin n → ℝ))) →L[ℝ]
      ParabolicC0AlphaBanach (Fin n → ℝ) ℝ α
        (Set.univ : Set (ℝ × (Fin n → ℝ))) :=
  ParabolicC0AlphaBanach.compL (matrixEntryCLM d i j)

theorem norm_globalMatrixEntrySourceL_le
    {α : ℝ} (i j : Fin d) :
    ‖globalMatrixEntrySourceL (n := n) (α := α) i j‖ ≤ 1 := by
  exact (ParabolicC0AlphaBanach.norm_compL_le (matrixEntryCLM d i j)).trans
    (norm_matrixEntryCLM_le i j)

theorem norm_globalMatrixEntrySourceL_apply_le
    {α : ℝ} (i j : Fin d)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ)))) :
    ‖globalMatrixEntrySourceL (n := n) (α := α) i j q‖ ≤ ‖q‖ := by
  calc
    ‖globalMatrixEntrySourceL (n := n) (α := α) i j q‖ ≤
        ‖globalMatrixEntrySourceL (n := n) (α := α) i j‖ * ‖q‖ :=
      (globalMatrixEntrySourceL (n := n) (α := α) i j).le_opNorm q
    _ ≤ 1 * ‖q‖ := mul_le_mul_of_nonneg_right
      (norm_globalMatrixEntrySourceL_le i j) (norm_nonneg q)
    _ = ‖q‖ := one_mul _

@[simp] theorem evalCLM_globalMatrixEntrySourceL
    {α : ℝ} (i j : Fin d)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ))))
    (z : ℝ × (Fin n → ℝ)) :
    ParabolicC0AlphaBanach.evalCLM z (Set.mem_univ z)
        (globalMatrixEntrySourceL (n := n) (α := α) i j q) =
      ParabolicC0AlphaBanach.evalCLM z (Set.mem_univ z) q i j := by
  rw [globalMatrixEntrySourceL,
    ParabolicC0AlphaBanach.evalCLM_compL_apply]
  rfl

/-- The `MatrixHeatFiniteData` generated by a global matrix-valued source and
zero initial data.  Every coefficient is controlled by the norm of the single
matrix-valued source rather than by an independently supplied bound. -/
def zeroMatrixHeatFiniteData
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ)))) :
    MatrixHeatFiniteData n d t₀ T α where
  hT := hT.le
  hr0 := hα
  hr1 := hα1
  initial := fun _ _ => euclideanZeroC2Data n
  initialHessianHolderConstant := 0
  initialHessianHolderConstant_nonneg := by norm_num
  initialHessianHolder := by
    intro i j a b x y
    exact euclideanZeroC2Data_secondHolder α a b x y
  source := fun s i j =>
    globalScalarSourcePath hα
      (globalMatrixEntrySourceL (n := n) (α := α) i j q) s
  source_continuous := by
    intro i j
    exact continuous_globalScalarSourcePath hα
      (globalMatrixEntrySourceL (n := n) (α := α) i j q)
  sourceBound := ‖q‖
  sourceSpatialHolderConstant := ‖q‖
  sourceParabolicHolderConstant := ‖q‖
  sourceBound_nonneg := norm_nonneg q
  sourceSpatialHolderConstant_nonneg := norm_nonneg q
  sourceParabolicHolderConstant_nonneg := norm_nonneg q
  source_bounded := by
    intro s y i j
    exact (globalScalarSourcePath_bounded hα
      (globalMatrixEntrySourceL (n := n) (α := α) i j q) s y).trans
        (norm_globalMatrixEntrySourceL_apply_le i j q)
  source_spatialHolder := by
    intro s x y i j
    have hentry := globalScalarSourcePath_spatialHolder hα hα1
      (globalMatrixEntrySourceL (n := n) (α := α) i j q) s x y
    exact hentry.trans (mul_le_mul_of_nonneg_right
      (norm_globalMatrixEntrySourceL_apply_le i j q)
      (Finset.sum_nonneg fun ell _ => Real.rpow_nonneg (abs_nonneg _) _))
  source_parabolicHolder := by
    intro i j
    exact (globalScalarSourcePath_parabolicHolder hα
      (globalMatrixEntrySourceL (n := n) (α := α) i j q)).mono_const
        (norm_globalMatrixEntrySourceL_apply_le i j q)

/-- The matrix-valued zero-initial Duhamel solution. -/
def matrixZeroInitialSolution
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ)))) :
    FiniteParabolicC2AlphaBanach (Fin n → ℝ)
      (Fin d → Fin d → ℝ) t₀ T α :=
  (zeroMatrixHeatFiniteData hT hα hα1 q).solution

/-- Each coefficient of the matrix solution is exactly the scalar solution of
the corresponding projected source. -/
theorem matrixZeroInitialSolution_value_apply
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ))))
    {z : ℝ × (Fin n → ℝ)}
    (hz : z ∈ parabolicFiniteCylinder (Fin n → ℝ) t₀ T)
    (i j : Fin d) :
    FiniteParabolicC2AlphaBanach.value
        (matrixZeroInitialSolution hT hα hα1 q) z i j =
      FiniteParabolicC2AlphaBanach.value
        (euclideanZeroInitialSolution hT hα hα1
          (globalMatrixEntrySourceL (n := n) (α := α) i j q)) z := by
  rw [matrixZeroInitialSolution,
    MatrixHeatFiniteData.solution_value _ hz,
    euclideanZeroInitialSolution_value hT hα hα1 _ hz]
  rfl

/-- Insertion of one scalar into one coefficient of a finite matrix. -/
def matrixSingleCLM (d : ℕ) (i j : Fin d) :
    ℝ →L[ℝ] (Fin d → Fin d → ℝ) :=
  (ContinuousLinearMap.single ℝ (fun _ : Fin d => Fin d → ℝ) i).comp
    (ContinuousLinearMap.single ℝ (fun _ : Fin d => ℝ) j)

@[simp] theorem matrixSingleCLM_apply (i j : Fin d) (c : ℝ) :
    matrixSingleCLM d i j c = Matrix.single i j c := by
  ext a b
  change (Pi.single i (Pi.single j c) : Fin d → Fin d → ℝ) a b =
    Matrix.single i j c a b
  by_cases ha : a = i
  · subst a
    by_cases hb : b = j
    · subst b
      simp [Matrix.single]
    · simp [Matrix.single, hb, Ne.symm hb]
  · simp [Matrix.single, ha, Ne.symm ha]

/-- Reassembling all coefficients with the single-entry maps gives back the
original finite matrix. -/
theorem sum_matrixSingleCLM (A : Fin d → Fin d → ℝ) :
    (∑ i : Fin d, ∑ j : Fin d, matrixSingleCLM d i j (A i j)) = A := by
  classical
  have hrow : ∀ i : Fin d,
      (∑ j : Fin d,
        (ContinuousLinearMap.single ℝ (fun _ : Fin d => ℝ) j) (A i j)) = A i := by
    intro i
    simpa using
      (ContinuousLinearMap.sum_comp_single
        (R := ℝ) (φ := fun _ : Fin d => ℝ)
        (ContinuousLinearMap.id ℝ (Fin d → ℝ)) (A i))
  calc
    (∑ i : Fin d, ∑ j : Fin d, matrixSingleCLM d i j (A i j)) =
        ∑ i : Fin d,
          (ContinuousLinearMap.single ℝ (fun _ : Fin d => Fin d → ℝ) i) (A i) := by
      apply Finset.sum_congr rfl
      intro i hi
      change (∑ j : Fin d,
          (ContinuousLinearMap.single ℝ (fun _ : Fin d => Fin d → ℝ) i)
            ((ContinuousLinearMap.single ℝ (fun _ : Fin d => ℝ) j) (A i j))) =
        (ContinuousLinearMap.single ℝ (fun _ : Fin d => Fin d → ℝ) i) (A i)
      rw [← map_sum, hrow i]
    _ = A := by
      simpa using
        (ContinuousLinearMap.sum_comp_single
          (R := ℝ) (φ := fun _ : Fin d => Fin d → ℝ)
          (ContinuousLinearMap.id ℝ (Fin d → Fin d → ℝ)) A)

/-- Closed-time value trajectory for the matrix zero-initial solution.  It is
a bounded continuous path in the uniform spatial norm, not merely a
pointwise extension at the initial time. -/
def matrixZeroInitialValuePathIcc
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ)))) :
    BoundedContinuousFunction (↥(Set.Icc t₀ T))
      (BoundedContinuousFunction (Fin n → ℝ) (Fin d → Fin d → ℝ)) :=
  ∑ i : Fin d, ∑ j : Fin d,
    ((matrixSingleCLM d i j).compLeftContinuousBounded (Fin n → ℝ)).compLeftContinuousBounded
      (↥(Set.Icc t₀ T))
      (euclideanZeroInitialValuePathIcc hT hα
        (globalMatrixEntrySourceL (n := n) (α := α) i j q))

@[simp] theorem matrixZeroInitialValuePathIcc_initial
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ)))) :
    matrixZeroInitialValuePathIcc hT hα q ⟨t₀, le_rfl, hT.le⟩ = 0 := by
  ext x i j
  simp [matrixZeroInitialValuePathIcc,
    euclideanZeroInitialValuePathIcc_initial hT hα]

/-- At positive times, the closed-time matrix trajectory agrees with the
value component of the packaged higher parabolic solution. -/
theorem matrixZeroInitialValuePathIcc_eq_solution
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ))))
    (t : ↥(Set.Ioc t₀ T)) (x : Fin n → ℝ) :
    matrixZeroInitialValuePathIcc hT hα q
        ⟨t, (Set.mem_Ioc.mp t.2).1.le, (Set.mem_Ioc.mp t.2).2⟩ x =
      FiniteParabolicC2AlphaBanach.value
        (matrixZeroInitialSolution hT hα hα1 q) (t, x) := by
  classical
  ext i j
  rw [matrixZeroInitialSolution_value_apply hT hα hα1 q
    (by simpa [parabolicFiniteCylinder] using t.2) i j]
  calc
    matrixZeroInitialValuePathIcc hT hα q
          ⟨t, (Set.mem_Ioc.mp t.2).1.le, (Set.mem_Ioc.mp t.2).2⟩ x i j =
        (∑ a : Fin d, ∑ b : Fin d, matrixSingleCLM d a b
          (euclideanZeroInitialValuePathIcc hT hα
            (globalMatrixEntrySourceL (n := n) (α := α) a b q)
            ⟨t, (Set.mem_Ioc.mp t.2).1.le, (Set.mem_Ioc.mp t.2).2⟩ x)) i j := by
      simp [matrixZeroInitialValuePathIcc]
    _ = euclideanZeroInitialValuePathIcc hT hα
          (globalMatrixEntrySourceL (n := n) (α := α) i j q)
          ⟨t, (Set.mem_Ioc.mp t.2).1.le, (Set.mem_Ioc.mp t.2).2⟩ x := by
      rw [sum_matrixSingleCLM]
    _ = _ := euclideanZeroInitialValuePathIcc_eq_solution hT hα hα1
      (globalMatrixEntrySourceL (n := n) (α := α) i j q) t x

@[simp] theorem matrixZeroInitialSolution_add
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1)
    (q r : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ)))) :
    matrixZeroInitialSolution hT hα hα1 (q + r) =
      matrixZeroInitialSolution hT hα hα1 q +
        matrixZeroInitialSolution hT hα hα1 r := by
  apply FiniteParabolicC2AlphaBanach.ext_value hα hT
  intro z hz
  funext i j
  rw [matrixZeroInitialSolution_value_apply hT hα hα1 (q + r) hz i j]
  rw [show globalMatrixEntrySourceL (n := n) (α := α) i j (q + r) =
      globalMatrixEntrySourceL (n := n) (α := α) i j q +
        globalMatrixEntrySourceL (n := n) (α := α) i j r by
    exact map_add _ q r]
  rw [euclideanZeroInitialSolution_add hT hα hα1]
  rw [show FiniteParabolicC2AlphaBanach.value
      (matrixZeroInitialSolution hT hα hα1 q +
        matrixZeroInitialSolution hT hα hα1 r) z i j =
      FiniteParabolicC2AlphaBanach.value
          (matrixZeroInitialSolution hT hα hα1 q) z i j +
        FiniteParabolicC2AlphaBanach.value
          (matrixZeroInitialSolution hT hα hα1 r) z i j by
    rw [FiniteParabolicC2AlphaBanach.value_add]
    rfl]
  rw [matrixZeroInitialSolution_value_apply hT hα hα1 q hz i j,
    matrixZeroInitialSolution_value_apply hT hα hα1 r hz i j]
  rw [FiniteParabolicC2AlphaBanach.value_add]

@[simp] theorem matrixZeroInitialSolution_smul
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1)
    (c : ℝ)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ)))) :
    matrixZeroInitialSolution hT hα hα1 (c • q) =
      c • matrixZeroInitialSolution hT hα hα1 q := by
  apply FiniteParabolicC2AlphaBanach.ext_value hα hT
  intro z hz
  funext i j
  rw [matrixZeroInitialSolution_value_apply hT hα hα1 (c • q) hz i j]
  rw [show globalMatrixEntrySourceL (n := n) (α := α) i j (c • q) =
      c • globalMatrixEntrySourceL (n := n) (α := α) i j q by
    exact map_smul _ c q]
  rw [euclideanZeroInitialSolution_smul hT hα hα1]
  rw [show FiniteParabolicC2AlphaBanach.value
      (c • matrixZeroInitialSolution hT hα hα1 q) z i j =
      c • FiniteParabolicC2AlphaBanach.value
        (matrixZeroInitialSolution hT hα hα1 q) z i j by
    rw [FiniteParabolicC2AlphaBanach.value_smul]
    rfl]
  rw [matrixZeroInitialSolution_value_apply hT hα hα1 q hz i j]
  rw [FiniteParabolicC2AlphaBanach.value_smul]

/-- Explicit matrix assembly factor multiplying the scalar Schauder
constant. -/
def matrixAssemblyConstant (n d : ℕ) : ℝ :=
  ∑ i : Fin d,
    ParabolicC2AlphaNormLe.continuousLinearMapRadius
      (X := Fin n → ℝ) (E := Fin d → ℝ)
      (ContinuousLinearMap.single ℝ (fun _ : Fin d => Fin d → ℝ) i) *
      (∑ j : Fin d,
        ParabolicC2AlphaNormLe.continuousLinearMapRadius
          (X := Fin n → ℝ) (E := ℝ)
          (ContinuousLinearMap.single ℝ (fun _ : Fin d => ℝ) j))

/-- Explicit operator-norm coefficient for the matrix-valued zero-initial
Schauder inverse. -/
def matrixZeroInitialSchauderConstant
    (n d : ℕ) (t₀ T α : ℝ) : ℝ :=
  matrixAssemblyConstant n d * euclideanZeroInitialSchauderConstant n t₀ T α

theorem zeroMatrixHeatFiniteData_schauderRadius_eq
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ)))) :
    (zeroMatrixHeatFiniteData hT hα hα1 q).schauderRadius =
      matrixZeroInitialSchauderConstant n d t₀ T α * ‖q‖ := by
  classical
  simp only [MatrixHeatFiniteData.schauderRadius, zeroMatrixHeatFiniteData,
    heatMildC2AlphaNormConstantND_zero_eq_mul]
  unfold matrixZeroInitialSchauderConstant matrixAssemblyConstant
  simp_rw [← Finset.sum_mul]
  ring

theorem norm_matrixZeroInitialSolution_le
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ)))) :
    ‖matrixZeroInitialSolution hT hα hα1 q‖ ≤
      matrixZeroInitialSchauderConstant n d t₀ T α * ‖q‖ := by
  exact (zeroMatrixHeatFiniteData hT hα hα1 q).norm_solution_le.trans_eq
    (zeroMatrixHeatFiniteData_schauderRadius_eq hT hα hα1 q)

theorem matrixAssemblyConstant_nonneg : 0 ≤ matrixAssemblyConstant n d := by
  unfold matrixAssemblyConstant
  apply Finset.sum_nonneg
  intro i hi
  exact mul_nonneg
    (ParabolicC2AlphaNormLe.continuousLinearMapRadius_nonneg _)
    (Finset.sum_nonneg fun j hj =>
      ParabolicC2AlphaNormLe.continuousLinearMapRadius_nonneg _)

theorem matrixZeroInitialSchauderConstant_nonneg
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1) :
    0 ≤ matrixZeroInitialSchauderConstant n d t₀ T α := by
  exact mul_nonneg matrixAssemblyConstant_nonneg
    (euclideanZeroInitialSchauderConstant_nonneg hT hα hα1)

/-- Algebraic matrix-valued zero-initial solution map. -/
def matrixZeroInitialLinearMap
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1) :
    ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
        (Set.univ : Set (ℝ × (Fin n → ℝ))) →ₗ[ℝ]
      FiniteParabolicC2AlphaBanach (Fin n → ℝ)
        (Fin d → Fin d → ℝ) t₀ T α where
  toFun := matrixZeroInitialSolution hT hα hα1
  map_add' := matrixZeroInitialSolution_add hT hα hα1
  map_smul' := matrixZeroInitialSolution_smul hT hα hα1

/-- The bounded matrix-valued zero-initial Euclidean Schauder inverse. -/
def matrixZeroInitialOperator
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1) :
    ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
        (Set.univ : Set (ℝ × (Fin n → ℝ))) →L[ℝ]
      FiniteParabolicC2AlphaBanach (Fin n → ℝ)
        (Fin d → Fin d → ℝ) t₀ T α :=
  LinearMap.mkContinuous (matrixZeroInitialLinearMap hT hα hα1)
    (matrixZeroInitialSchauderConstant n d t₀ T α)
    (norm_matrixZeroInitialSolution_le hT hα hα1)

@[simp] theorem matrixZeroInitialOperator_apply
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ)))) :
    matrixZeroInitialOperator hT hα hα1 q =
      matrixZeroInitialSolution hT hα hα1 q := rfl

theorem norm_matrixZeroInitialOperator_le
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1) :
    ‖matrixZeroInitialOperator (n := n) (d := d) hT hα hα1‖ ≤
      matrixZeroInitialSchauderConstant n d t₀ T α := by
  exact LinearMap.mkContinuous_norm_le _
    (matrixZeroInitialSchauderConstant_nonneg hT hα hα1) _

/-- The assembled matrix solution satisfies `∂ₜ u - Δu = q`
coefficientwise at every positive time. -/
theorem matrixZeroInitialSolution_heatEquation
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ))))
    {t : ℝ} (ht : t ∈ Set.Ioc t₀ T) (x : Fin n → ℝ) :
    FiniteParabolicC2AlphaBanach.timeDeriv
        (matrixZeroInitialSolution hT hα hα1 q) (t, x) =
      (∑ k : Fin n, FiniteParabolicC2AlphaBanach.spaceSecondDeriv
        (matrixZeroInitialSolution hT hα hα1 q) (t, x)
          (Pi.single k 1) (Pi.single k 1)) +
        ParabolicC0AlphaBanach.evalCLM (t, x) (Set.mem_univ (t, x)) q := by
  have h := (zeroMatrixHeatFiniteData hT hα hα1 q).solution_heatEquation ht x
  simpa only [matrixZeroInitialSolution, zeroMatrixHeatFiniteData,
    globalScalarSourcePath_apply, evalCLM_globalMatrixEntrySourceL] using h

/-- Trace of an `E`-valued Euclidean bilinear map on the standard basis. -/
def euclideanVectorBilinearTraceCLM
    (n : ℕ) (E : Type*) [NormedAddCommGroup E] [NormedSpace ℝ E] :
    (((Fin n → ℝ) →L[ℝ] (Fin n → ℝ) →L[ℝ] E) →L[ℝ] E) :=
  ∑ k : Fin n,
    ((ContinuousLinearMap.apply ℝ E) (Pi.single k 1)).comp
      ((ContinuousLinearMap.apply ℝ ((Fin n → ℝ) →L[ℝ] E))
        (Pi.single k 1))

@[simp] theorem euclideanVectorBilinearTraceCLM_apply
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A : (Fin n → ℝ) →L[ℝ] (Fin n → ℝ) →L[ℝ] E) :
    euclideanVectorBilinearTraceCLM n E A =
      ∑ k : Fin n, A (Pi.single k 1) (Pi.single k 1) := by
  simp [euclideanVectorBilinearTraceCLM]

/-- The coefficientwise constant-principal-part matrix heat Cauchy operator
`u ↦ ∂ₜ u - Δu`. -/
def euclideanMatrixHeatCauchyL
    (n d : ℕ) (t₀ T α : ℝ) :
    FiniteParabolicC2AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ)
        t₀ T α →L[ℝ]
      ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
        (parabolicFiniteCylinder (Fin n → ℝ) t₀ T) :=
  FiniteParabolicC2AlphaBanach.timeDerivComponentL -
    (ParabolicC0AlphaBanach.compL
      (euclideanVectorBilinearTraceCLM n (Fin d → Fin d → ℝ))).comp
      FiniteParabolicC2AlphaBanach.spaceSecondDerivComponentL

theorem evalCLM_euclideanMatrixHeatCauchyL
    {t₀ T α : ℝ}
    (u : FiniteParabolicC2AlphaBanach (Fin n → ℝ)
      (Fin d → Fin d → ℝ) t₀ T α)
    (z : ℝ × (Fin n → ℝ))
    (hz : z ∈ parabolicFiniteCylinder (Fin n → ℝ) t₀ T) :
    ParabolicC0AlphaBanach.evalCLM z hz
        (euclideanMatrixHeatCauchyL n d t₀ T α u) =
      FiniteParabolicC2AlphaBanach.timeDeriv u z -
        ∑ k : Fin n, FiniteParabolicC2AlphaBanach.spaceSecondDeriv u z
          (Pi.single k 1) (Pi.single k 1) := by
  rw [euclideanMatrixHeatCauchyL, ContinuousLinearMap.sub_apply, map_sub,
    FiniteParabolicC2AlphaBanach.evalCLM_timeDerivComponentL,
    ContinuousLinearMap.comp_apply,
    ParabolicC0AlphaBanach.evalCLM_compL_apply,
    FiniteParabolicC2AlphaBanach.evalCLM_spaceSecondDerivComponentL,
    euclideanVectorBilinearTraceCLM_apply]

/-- Restriction of a global matrix source to the positive finite cylinder. -/
def restrictGlobalMatrixSourceToFiniteL
    (n d : ℕ) (t₀ T α : ℝ) :
    ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
        (Set.univ : Set (ℝ × (Fin n → ℝ))) →L[ℝ]
      ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
        (parabolicFiniteCylinder (Fin n → ℝ) t₀ T) :=
  ParabolicC0AlphaBanach.restrictL (fun _ _ => Set.mem_univ _)

/-- The matrix Duhamel operator is a bounded right inverse of the matrix heat
Cauchy operator, with its global source restricted to the finite cylinder. -/
theorem euclideanMatrixHeatCauchyL_comp_zeroInitialOperator
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1) :
    (euclideanMatrixHeatCauchyL n d t₀ T α).comp
        (matrixZeroInitialOperator (n := n) (d := d) hT hα hα1) =
      restrictGlobalMatrixSourceToFiniteL n d t₀ T α := by
  ext q
  apply (ParabolicC0AlphaBanach.eq_iff_forall_evalCLM _ _).2
  intro z hz
  rcases z with ⟨t, x⟩
  have ht : t ∈ Set.Ioc t₀ T := by
    simpa [parabolicFiniteCylinder] using hz
  rw [ContinuousLinearMap.comp_apply, matrixZeroInitialOperator_apply,
    evalCLM_euclideanMatrixHeatCauchyL]
  rw [matrixZeroInitialSolution_heatEquation hT hα hα1 q ht x]
  unfold restrictGlobalMatrixSourceToFiniteL
  rw [ParabolicC0AlphaBanach.evalCLM_restrictL_apply
    (Set.subset_univ _) (t, x) hz q]
  abel

/-- Pointwise symmetric forcing produces a pointwise symmetric solution. -/
theorem matrixZeroInitialSolution_isSymm
    {t₀ T α : ℝ} (hT : t₀ < T) (hα : 0 < α) (hα1 : α < 1)
    (q : ParabolicC0AlphaBanach (Fin n → ℝ) (Fin d → Fin d → ℝ) α
      (Set.univ : Set (ℝ × (Fin n → ℝ))))
    (hq : ∀ z i j,
      ParabolicC0AlphaBanach.evalCLM z (Set.mem_univ z) q i j =
        ParabolicC0AlphaBanach.evalCLM z (Set.mem_univ z) q j i)
    {z : ℝ × (Fin n → ℝ)}
    (hz : z ∈ parabolicFiniteCylinder (Fin n → ℝ) t₀ T) :
    ∀ i j, FiniteParabolicC2AlphaBanach.value
        (matrixZeroInitialSolution hT hα hα1 q) z i j =
      FiniteParabolicC2AlphaBanach.value
        (matrixZeroInitialSolution hT hα hα1 q) z j i := by
  intro i j
  exact (zeroMatrixHeatFiniteData hT hα hα1 q).solution_isSymm
    (by intro a b; rfl)
    (by
      intro s a b
      ext x
      simp only [zeroMatrixHeatFiniteData, globalScalarSourcePath_apply]
      rw [evalCLM_globalMatrixEntrySourceL, evalCLM_globalMatrixEntrySourceL]
      exact hq (s, x) a b)
    hz i j

end MatrixZeroInitial

end AnalyticPDE
end RicciFlow
