/-
Copyright (c) 2026 William Whistler. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Whistler
-/

import LeanPool.RegtsSevenster.RS.Classical.Deligne.AltPow
import LeanPool.RegtsSevenster.RS.Classical.Deligne.AltPowAct
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeAdjoint
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeBiprod
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeCoherence
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeDatum
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeFree
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeLinear
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeMonoidal
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeTensor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeTransport
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeZigzag
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BigTensor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BigTensorUnit
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BiprodPow
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BiprodTransfer
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BlockUnits
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BraidCoherence
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainAlgebra
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainB
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBGr
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBGraded
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBGradedLaws
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBInd
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBNonzero
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBofA
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBridge
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainDelta
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainIns
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainIns.Base
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainIns.FirstSlot
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainIns.SecondSlot
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainMul
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainMulHet
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainMulLaws
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainNonzero
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainShift
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainStage2
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainUnit
import LeanPool.RegtsSevenster.RS.Classical.Deligne.CharSplit
import LeanPool.RegtsSevenster.RS.Classical.Deligne.CommonAlgebra
import LeanPool.RegtsSevenster.RS.Classical.Deligne.CoprodPreserve
import LeanPool.RegtsSevenster.RS.Classical.Deligne.CountableDescent
import LeanPool.RegtsSevenster.RS.Classical.Deligne.CountableDescentClose
import LeanPool.RegtsSevenster.RS.Classical.Deligne.CountableNullstellensatz
import LeanPool.RegtsSevenster.RS.Classical.Deligne.CoverFactor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.CycleSplit
import LeanPool.RegtsSevenster.RS.Classical.Deligne.DayCalculus
import LeanPool.RegtsSevenster.RS.Classical.Deligne.DayType
import LeanPool.RegtsSevenster.RS.Classical.Deligne.DeligneAssembly
import LeanPool.RegtsSevenster.RS.Classical.Deligne.DescentClose
import LeanPool.RegtsSevenster.RS.Classical.Deligne.DevissageBound
import LeanPool.RegtsSevenster.RS.Classical.Deligne.DoubledAbelian
import LeanPool.RegtsSevenster.RS.Classical.Deligne.DoubledGrowth
import LeanPool.RegtsSevenster.RS.Classical.Deligne.DoubledLine
import LeanPool.RegtsSevenster.RS.Classical.Deligne.DoubledScalar
import LeanPool.RegtsSevenster.RS.Classical.Deligne.DoubledSmall
import LeanPool.RegtsSevenster.RS.Classical.Deligne.DoubledSplit
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Doubling
import LeanPool.RegtsSevenster.RS.Classical.Deligne.DualityMate
import LeanPool.RegtsSevenster.RS.Classical.Deligne.EvenEmbedMonoidal
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ExactFromShort
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FactorialBeats
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreAdditive
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreBridge
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreEps
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreExact
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreFaithful
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreFunctor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreMix
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreMonoidal
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreMu
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreLinear
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreMuNat
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreOverComplex
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreOverSplitting
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreRestrict
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreStrong
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FiltNil
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FlatLimit
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeCollapseAlg
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeMixRetract
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeModAdjoint
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeModBiprod
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeModFunctor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeModShuffle
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeModShuffleCoh
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeModTensor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeSummand
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeNormalise
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeNormaliseBase
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeNormaliseStep
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreePow
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreePowDesc
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreePowInsert
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeSlide
import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeTwistPi
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaAlgebra
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaBiprod
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaCountable
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaComplex
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaModule
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaModuleFunctor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPair
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairAdd
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairFreeFree
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairFreeMix
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairNat
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairRetract
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairRetractRight
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairUnit
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaShift
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaTwistLeft
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GeneratorAlgebra
import LeanPool.RegtsSevenster.RS.Classical.Deligne.GrowthDichotomy
import LeanPool.RegtsSevenster.RS.Classical.Deligne.HomFinite
import LeanPool.RegtsSevenster.RS.Classical.Deligne.HookMult
import LeanPool.RegtsSevenster.RS.Classical.Deligne.HookZero
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IdemCut
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IdempotentLength
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ImageSubalgebra
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndAllColim
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndBigTensorUnit
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndCoeq
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndCompact
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndDayClosure
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndImage
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndKill
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndLocallyMixed
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndMonoidal
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndOfLinear
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndOfMonoidal
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndPointTensor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndSchur
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndSchurKilled
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndSimple
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndSplit
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndSplitSection
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndTensorExact
import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndUnitNonzero
import LeanPool.RegtsSevenster.RS.Classical.Deligne.InitDatum
import LeanPool.RegtsSevenster.RS.Classical.Deligne.InitState
import LeanPool.RegtsSevenster.RS.Classical.Deligne.InterchangeAct
import LeanPool.RegtsSevenster.RS.Classical.Deligne.KernelPow
import LeanPool.RegtsSevenster.RS.Classical.Deligne.KeyLemma
import LeanPool.RegtsSevenster.RS.Classical.Deligne.KeyLemmaClose
import LeanPool.RegtsSevenster.RS.Classical.Deligne.KeyLemmaData
import LeanPool.RegtsSevenster.RS.Classical.Deligne.KillerNonempty
import LeanPool.RegtsSevenster.RS.Classical.Deligne.KronKill
import LeanPool.RegtsSevenster.RS.Classical.Deligne.LambdaCoend
import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixDegenerate
import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixShuffle
import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixShuffleLine
import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixSumPow
import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixWhisker
import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixWhiskerAll
import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixedConc
import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixedDiag
import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixedTransport
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModAssoc
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModBiprod
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModAbelian
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModContractL
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModCross
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModDual
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModIns
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModMulti
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModMultiTriple
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModPowCast
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModPowDescent
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModPowDescentClose
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModPowStage
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModSchur
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModSchurSummand
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModTensor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModZero
import LeanPool.RegtsSevenster.RS.Classical.Deligne.MulBy
import LeanPool.RegtsSevenster.RS.Classical.Deligne.MuInterchange
import LeanPool.RegtsSevenster.RS.Classical.Deligne.NatChain
import LeanPool.RegtsSevenster.RS.Classical.Deligne.NewtonConv
import LeanPool.RegtsSevenster.RS.Classical.Deligne.NullPoint
import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddLineMap
import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddLinePairing
import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddParity
import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddPermSign
import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddSquare
import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddSquareIso
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PairCarrier
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PairMul
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PairPerm
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PermNat
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PermRepChar
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PieriPos
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PlainShuffle
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointBaseChange
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointFibre
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointMonoidal
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointMonoidal.Calculus
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointMonoidal.Coherence
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointMonoidal.Comparison
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointMonoidal.Functor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointMonoidal.Residue
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointTensor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowAct
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowActMul
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowChain
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowCopairing
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowDatum
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowInduct
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowMerge
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowPairSucc
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowPairing
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowPoint
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowSucc
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowSuccMod
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowTriangle
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowZig
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowZigzag
import LeanPool.RegtsSevenster.RS.Classical.Deligne.PresentedQuotient
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Prop21
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Prop21Core
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Prop21General
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Prop29
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Prop29Close
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Prop29State
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Rappel210
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Rappel210Bridge
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Rappel210Chain
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Rappel210Close
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Rappel210Ind
import LeanPool.RegtsSevenster.RS.Classical.Deligne.Rappel210Reduce
import LeanPool.RegtsSevenster.RS.Classical.Deligne.RegularSum
import LeanPool.RegtsSevenster.RS.Classical.Deligne.RhoBiprod
import LeanPool.RegtsSevenster.RS.Classical.Deligne.RhoTwist
import LeanPool.RegtsSevenster.RS.Classical.Deligne.RowColIdem
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SandwichMerge
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SandwichRetract
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SandwichZig
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ScalarBraiding
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ScalarLinear
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ScalarUnitEquiv
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ScalarUnitInd
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SchurTransport
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SchurVanishing
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SeedIns
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ShapeAlgebra
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ShapeFintype
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SignConj
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SimpleGenerator
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SmallReduction
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SimpleQuotient
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SimpleSplit
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SimplePoint
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SimpleScalars
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitAdjoint
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitClosure
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitEverything
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitAssemble
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitComplement
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitExact
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitExtract
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitExtractDual
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitMonHom
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitPairDef
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitReduce
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitTransport
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplittingAlgebra
import LeanPool.RegtsSevenster.RS.Classical.Deligne.StateTransport
import LeanPool.RegtsSevenster.RS.Classical.Deligne.StepA
import LeanPool.RegtsSevenster.RS.Classical.Deligne.StepATransport
import LeanPool.RegtsSevenster.RS.Classical.Deligne.StepB
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperEmbed
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperEmbed.Letters
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperEmbed.Signs
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperEmbed.Standard
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperEvenRing
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperGamma
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperGammaInst
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModAbelian
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModBiprod
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModBiprodMap
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModHom
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModIso
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModMonoidal
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModShift
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModShiftUnit
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModTensor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperPointMod
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperRealize
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperSeries
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperSmall
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperValues
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperVectSchur
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SymAlg
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SymDatum
import LeanPool.RegtsSevenster.RS.Classical.Deligne.SymMul
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorDatum
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorExact
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorMuBraid
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorPowZero
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorTransfer
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorZigzag
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TrichotomyClose
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistBiprod
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistCoherence
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistDatum
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistFreeTensor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistMixLine
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistPow
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistShuffle
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistState
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistSymPow
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistUnitor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.UnitBase
import LeanPool.RegtsSevenster.RS.Classical.Deligne.UnitFreeMod
import LeanPool.RegtsSevenster.RS.Classical.Deligne.UnitMod
import LeanPool.RegtsSevenster.RS.Classical.Deligne.UnitSimple
import LeanPool.RegtsSevenster.RS.Classical.Deligne.UnitStage
import LeanPool.RegtsSevenster.RS.Classical.Deligne.UniversalAlgebra
import LeanPool.RegtsSevenster.RS.Classical.Deligne.WhiskerFaithful
import LeanPool.RegtsSevenster.RS.Classical.Deligne.WordMap
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZagAction
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZigzagCarrier
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZigzagNonzero
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZigzagSandwich
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZigzagTransfer
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZigzagTransferIso

/-!
# The Deligne development: aggregator

This module imports every file of the `RS.Classical.Deligne`
development, so that a single import brings the whole of the
Deligne-theorem work into scope.  It declares nothing of its own.
-/
