/-
Copyright (c) 2026 Christopher Albert. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christopher Albert
-/

import LeanPool.Stafford38.Stafford38.Characteristic.CanonicalTangentialPageOperators
import LeanPool.Stafford38.Stafford38.Characteristic.CommutingPolynomialAction

/-!
# Tangential symbol action on the canonical total pages

The commuting polynomial action is constructed from the actual right Weyl
generators. Their commutators have lower order and hence vanish on the pages.
-/

namespace Stafford38.Characteristic.CanonicalTangentialTotalAction

open Stafford38.Characteristic
open Stafford38.Characteristic.FilteredTwoTermPages
open Stafford38.Characteristic.CanonicalFilteredTwoTerm
open Stafford38.Characteristic.CanonicalTangentialPageOperators
open Stafford38.WeylIteratedEquivalence
open Stafford38.WeylPBWMonicBridge
open Stafford38.WeylQuotientTransport

noncomputable section

variable (k : Type*) [Field k] [Algebra ℚ k]
variable (n N : ℕ) (d : PresentedWeyl k (n + 1))

/-- The canonical filtered two-term complex associated with the Weyl element. -/
abbrev complex := canonicalFilteredTwoTerm k n N d

/-- The filtered page operator for a tangential position or momentum generator. -/
def generator (i : Fin n ⊕ Fin n) :
    (complex k n N d).PageOperator (tangentialDegree i : ℤ) :=
  match i with
  | .inl j => tangentialCoordinatePageOperator k n N d j
  | .inr j => tangentialMomentumPageOperator k n N d j

theorem generator_commutator_lowers (i j : Fin n ⊕ Fin n)
    (p : ℤ) (z : CanonicalQuotient k n N d)
    (hz : z ∈ (complex k n N d).G p) :
    (generator k n N d i).g ((generator k n N d j).g z) -
      (generator k n N d j).g ((generator k n N d i).g z) ∈
        (complex k n N d).G
          (p - (tangentialDegree i : ℤ) - (tangentialDegree j : ℤ) + 1) := by
  have h := tangential_commutator_lower k n N d i j p z hz
  cases i <;> cases j <;>
    simpa [generator, tangentialCoordinatePageOperator,
      tangentialMomentumPageOperator, tangentialPageOperator,
      tangentialDegree, show p - 1 - 1 + 1 = p - 2 + 1 by omega] using h

/-- The endomorphism induced by a tangential generator on a source total module. -/
def sourceGenerator (r : ℕ) (i : Fin n ⊕ Fin n) :
    Module.End k ((complex k n N d).SourceTotal r) :=
  (generator k n N d i).sourceTotalMap r

/-- The endomorphism induced by a tangential generator on a target total module. -/
def targetGenerator (r : ℕ) (i : Fin n ⊕ Fin n) :
    Module.End k ((complex k n N d).TargetTotal r) :=
  (generator k n N d i).targetTotalMap r

theorem sourceGenerator_commute (r : ℕ) (i j : Fin n ⊕ Fin n) :
    Commute (sourceGenerator k n N d r i) (sourceGenerator k n N d r j) :=
  (generator k n N d i).sourceTotalMap_commute_of_commutator_lowers
    (generator k n N d j) (generator_commutator_lowers k n N d i j) r

theorem targetGenerator_commute (r : ℕ) (i j : Fin n ⊕ Fin n) :
    Commute (targetGenerator k n N d r i) (targetGenerator k n N d r j) :=
  (generator k n N d i).targetTotalMap_commute_of_commutator_lowers
    (generator k n N d j) (generator_commutator_lowers k n N d i j) r

/-- The polynomial action generated by the commuting tangential source endomorphisms. -/
def sourceAction (r : ℕ) :
    MvPolynomial (Fin n ⊕ Fin n) k →ₐ[k]
      Module.End k ((complex k n N d).SourceTotal r) :=
  commutingPolynomialAction (sourceGenerator k n N d r)
    (sourceGenerator_commute k n N d r)

/-- The polynomial action generated by the commuting tangential target endomorphisms. -/
def targetAction (r : ℕ) :
    MvPolynomial (Fin n ⊕ Fin n) k →ₐ[k]
      Module.End k ((complex k n N d).TargetTotal r) :=
  commutingPolynomialAction (targetGenerator k n N d r)
    (targetGenerator_commute k n N d r)

theorem totalDrop_intertwines_polynomials (r : ℕ)
    (P : MvPolynomial (Fin n ⊕ Fin n) k) :
    (complex k n N d).totalDrop r ∘ₗ sourceAction k n N d r P =
      targetAction k n N d r P ∘ₗ (complex k n N d).totalDrop r :=
  commutingPolynomialAction_intertwines _ _ _ _ _
    (fun i => (generator k n N d i).totalDrop_intertwines r) P

/-- The module structure on a source total module induced by its tangential polynomial action. -/
@[instance_reducible]
def sourceModule (r : ℕ) :
    Module (MvPolynomial (Fin n ⊕ Fin n) k)
      ((complex k n N d).SourceTotal r) :=
  Module.compHom _ (sourceAction k n N d r).toRingHom

/-- The module structure on a target total module induced by its tangential polynomial action. -/
@[instance_reducible]
def targetModule (r : ℕ) :
    Module (MvPolynomial (Fin n ⊕ Fin n) k)
      ((complex k n N d).TargetTotal r) :=
  Module.compHom _ (targetAction k n N d r).toRingHom

attribute [local instance] sourceModule targetModule

/-- The concrete page differential is linear over the tangential symbol ring. -/
def tangentialDrop (r : ℕ) :
    (complex k n N d).SourceTotal r →ₗ[MvPolynomial (Fin n ⊕ Fin n) k]
      (complex k n N d).TargetTotal r where
  toFun := (complex k n N d).totalDrop r
  map_add' := map_add _
  map_smul' P z := by
    exact congrArg (fun f => f z)
      (totalDrop_intertwines_polynomials k n N d r P)

@[simp]
theorem tangentialDrop_apply (r : ℕ)
    (z : (complex k n N d).SourceTotal r) :
    tangentialDrop k n N d r z = (complex k n N d).totalDrop r z := rfl


end
end Stafford38.Characteristic.CanonicalTangentialTotalAction
