/-
Copyright (c) 2026 Christopher Birkbeck, Alex Torzewski. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christopher Birkbeck, Alex Torzewski
-/
module


/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
public import Mathlib.RingTheory.Ideal.Height
public import Mathlib.RingTheory.LocalRing.MaximalIdeal.Defs
public import Mathlib.RingTheory.FiniteType

/-!
# Excellent Rings

We define **catenary rings**, **regular local rings**, and **excellent rings**,
following EGA IV, §7.8.

## Main definitions

* `IsCatenaryRing R`: a commutative ring is catenary if for every pair of primes `p ≤ q`,
  the height satisfies `height(q) = height(p) + height(q/p)` in `R/p`.
* `IsRegularLocalRing R`: a local ring `(R, m)` is regular if `m` can be generated by at
  most `height(m)` elements.
* `IsExcellentRing R`: a commutative ring is excellent if it is noetherian, universally
  catenary, satisfies J-2, and has geometrically regular formal fibers.

## References

* [A. Grothendieck, *Éléments de géométrie algébrique IV*, §7.8][EGA4]
* [T. Wedhorn, *Adic Spaces*, Definition 6.9][Wedhorn]
-/

@[expose] public section

universe u

/-- A commutative ring is **catenary** if for every pair of prime ideals `p ≤ q`, the
height satisfies `height(q) = height(p) + height(q/p)` in `R/p`. -/
class IsCatenaryRing (R : Type u) [CommRing R] : Prop where
  height_add : ∀ (p q : Ideal R) [p.IsPrime] [q.IsPrime],
    p ≤ q → (q.map (Ideal.Quotient.mk p)).height + p.height = q.height

/-- A local ring `(R, m)` is **regular** if `m` can be generated by at most
`height(m)` elements. -/
class IsRegularLocalRing (R : Type u) [CommRing R] [IsLocalRing R] : Prop where
  regular : ∃ (s : Finset R),
    Ideal.span (s : Set R) = IsLocalRing.maximalIdeal R ∧
    (s.card : WithBot ℕ∞) ≤ (IsLocalRing.maximalIdeal R).height

/-- A commutative ring is **excellent** if it satisfies four conditions:
1. Noetherian
2. Universally catenary (every finitely generated algebra is catenary)
3. J-2 (regular locus of finitely generated algebras is open)
4. Geometrically regular formal fibers

This is the standard notion from EGA IV, §7.8.

We inline the conditions to avoid universe-level issues with quantified algebra types. -/
class IsExcellentRing (R : Type u) [CommRing R] : Prop where
  /-- R is noetherian. -/
  noetherian : IsNoetherianRing R
  /-- Every finitely generated R-algebra is catenary. -/
  universallyCatenary : ∀ (S : Type u) [CommRing S] [Algebra R S]
    [Algebra.FiniteType R S], IsCatenaryRing S
  /-- For every finitely generated R-algebra S, the regular locus in Spec S is open. -/
  j2 : ∀ (S : Type u) [CommRing S] [Algebra R S]
    [Algebra.FiniteType R S],
    IsOpen {p : PrimeSpectrum S | IsRegularLocalRing (Localization.AtPrime p.asIdeal)}
  /-- For every prime p, localizations of R_p at further primes are regular. -/
  geomRegularFormalFibers : ∀ (p : Ideal R) [p.IsPrime]
    (q : PrimeSpectrum (Localization.AtPrime p)),
      IsRegularLocalRing (Localization.AtPrime q.asIdeal)
