/-
Copyright (c) 2026 Christopher Birkbeck, Alex Torzewski. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christopher Birkbeck, Alex Torzewski
-/

/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import LeanPool.UniformSheafyTateDomains.AdicSpaces.ValuationSpectrum
import Mathlib.Topology.Compactness.Compact
import Mathlib.Topology.Constructions

/-!
# Compactness of the Valuation Spectrum (scaffolding)

This file begins the port of Huber's proof that `Spv A = ValuationSpectrum A` is a
**quasi-compact** topological space (Wedhorn, Theorem 4.9; Huber, *Continuous valuations*,
1993, Lemma 2.1 / Theorem 3.1).

## High-level strategy

The argument embeds `Spv A` into the function space `(A × A) → Prop`, equipped with the
product topology (each factor carrying the Sierpinski topology on `Prop`, under which
`{True}` is the only non-trivial open). Tychonoff gives `CompactSpace (A × A → Prop)`
(the Sierpinski space is compact, and an arbitrary product of compact spaces is compact).
To deduce compactness of `Spv A` one shows:

* `ιSpv` is a topological embedding (`ιSpv_isEmbedding`);
* the image of `ιSpv` inside `(A × A → Prop)` is a **closed subset** (Phase 2).

A closed subspace of a compact space is compact, giving `CompactSpace (Spv A)`.

## Choice of embedding: basic-open characteristic functions

The most natural-looking embedding would be `v ↦ (f, s) ↦ v.vle f s` (a direct
characteristic function of the valuative preorder). **However, that embedding does not
induce the right topology on `Spv A`.** The Sierpinski topology has only `{True}` open,
so the sub-basic pullback `{v | v.vle f s}` would be forced to be open in `Spv A` — but
this set is *not* open in `Spv A` in general (it fails to be closed under specialisations
that move `s` into the support). The topology on `Spv A` is generated by the strictly
stronger conditions `basicOpen f s = {v | v.vle f s ∧ ¬ v.vle s 0}`.

The fix is to take the coordinate to be the conjunction directly:

  `ιSpv v (f, s) := v.vle f s ∧ ¬ v.vle s 0`, i.e. `v ∈ basicOpen f s`.

With this choice, the Sierpinski sub-basic pullback at coordinate `(f, s)` is exactly
`basicOpen f s`, which is open in `Spv A` by definition of the topology; conversely every
generator of the topology on `Spv A` arises as such a pullback. Hence the product topology
restricts to the given topology on `Spv A` and `ιSpv` is a topological embedding.

Injectivity still holds: the support information carried by the coordinate `(s, s)`
(specifically, `v ∈ basicOpen s s ↔ ¬ v.vle s 0`) combined with the coordinates `(f, f)`
(telling us when `f ∈ supp v`, via `v ∈ basicOpen f f ↔ ¬ v.vle f 0`) is enough to recover
the raw valuative preorder `v.vle f s`.

## Contents of this file (Phase 1 — embedding only)

* `ValuationSpectrum.ιSpv` — the Huber embedding (basic-open characteristic form).
* `ValuationSpectrum.ιSpv_apply` — definitional unfolding.
* `ValuationSpectrum.vle_iff_of_ιSpv` — recovers `v.vle f s` from `ιSpv` values.
* `ValuationSpectrum.ιSpv_injective` — injectivity.
* `ValuationSpectrum.ιSpv_isInducing` — topology agreement.
* `ValuationSpectrum.ιSpv_isEmbedding` — the main embedding theorem.

## Future work (Phase 2 — not in this file yet)

* Prove the image of `ιSpv` is a closed subset of `(A × A → Prop)`. Concretely, express
  the fact that `r` arises from a valuation in terms of closed conditions in the product
  (each a finite boolean combination of coordinate sub-basics).
* Conclude `CompactSpace (Spv A)` from Tychonoff + closed-subspace compactness + the
  embedding proved here.

## References

* T. Wedhorn, *Adic Spaces*, Theorem 4.9.
* R. Huber, *Continuous valuations*, Math. Z. 212 (1993), 445–477.
-/

namespace ValuationSpectrum

variable {A : Type*} [CommRing A]

/-! ### The Huber embedding `ιSpv : Spv A → (A × A → Prop)` -/

/-- **Huber embedding.** Send a point `v ∈ Spv A` to the characteristic function of its
basic opens: `(f, s) ↦ v ∈ basicOpen f s`, unfolded as `v.vle f s ∧ ¬ v.vle s 0`.

With `Prop` carrying the Sierpinski topology and `A × A → Prop` the product topology, the
sub-basic open set `{r | r (f, s)}` pulls back to `basicOpen f s`, which is precisely one
of the generating opens of the topology on `Spv A`. Hence the induced topology agrees with
the given topology on `Spv A` (see `ιSpv_isInducing`). -/
def ιSpv (v : Spv A) : A × A → Prop := fun p ↦ v.vle p.1 p.2 ∧ ¬ v.vle p.2 0

@[simp]
lemma ιSpv_apply (v : Spv A) (f s : A) :
    ιSpv v (f, s) = (v.vle f s ∧ ¬ v.vle s 0) := rfl

/-- The coordinate `(f, s)` of `ιSpv v` exactly tests membership in `basicOpen f s`. -/
lemma ιSpv_iff_mem_basicOpen (v : Spv A) (f s : A) :
    ιSpv v (f, s) ↔ v ∈ basicOpen f s := Iff.rfl

/-- The coordinate `(s, s)` of `ιSpv v` tests whether `s` lies outside the support. -/
lemma ιSpv_diag (v : Spv A) (s : A) : ιSpv v (s, s) ↔ ¬ v.vle s 0 := by
  simp [ιSpv]

/-- The raw valuative preorder `v.vle f s` can be recovered from the `ιSpv` data.

If `¬ v.vle s 0` (i.e. `s ∉ supp v`) then `v.vle f s` is simply the `(f, s)` coordinate.
If `v.vle s 0` (i.e. `s ∈ supp v`) then `v.vle f s ↔ v.vle f 0`, which can be recovered
from the negations of the `(s, s)` and `(f, f)` coordinates (via `ιSpv_diag`). -/
lemma vle_iff_ιSpv (v : Spv A) (f s : A) :
    v.vle f s ↔ (ιSpv v (f, s) ∨ (¬ ιSpv v (s, s) ∧ ¬ ιSpv v (f, f))) := by
  rw [ιSpv_diag, ιSpv_diag]
  simp only [not_not, ιSpv_apply]
  constructor
  · intro h
    by_cases hs : v.vle s 0
    · exact Or.inr ⟨hs, v.vle_trans h hs⟩
    · exact Or.inl ⟨h, hs⟩
  · rintro (⟨h, _⟩ | ⟨_, hf⟩)
    · exact h
    · exact v.vle_trans hf (v.zero_vle s)

/-- The Huber embedding is injective: two points of `Spv A` with equal basic-open
characteristic functions are equal. -/
lemma ιSpv_injective : Function.Injective (ιSpv : Spv A → _) := by
  intro v₁ v₂ h
  apply ValuationSpectrum.ext
  funext f s
  have key : ∀ f s : A, ιSpv v₁ (f, s) ↔ ιSpv v₂ (f, s) := by
    intro f s; exact (congrArg (fun r ↦ r (f, s)) h).to_iff
  exact propext <| by
    rw [vle_iff_ιSpv, vle_iff_ιSpv]
    simp only [key]

/-! ### `ιSpv` is a topological embedding -/

/-- The topology on `Spv A` coincides with the topology induced from the product topology
on `(A × A → Prop)` (product of Sierpinski). -/
lemma ιSpv_isInducing : Topology.IsInducing (ιSpv : Spv A → (A × A → Prop)) := by
  refine ⟨?_⟩
  -- Unfold Pi topology to an iInf of single-coordinate induced topologies.
  rw [show (Pi.topologicalSpace :
      TopologicalSpace (A × A → Prop)) = ⨅ p, TopologicalSpace.induced
        (fun r : A × A → Prop ↦ r p) sierpinskiSpace from rfl]
  rw [induced_iInf]
  -- Each coordinate's pullback of the Sierpinski generator is a basic open.
  have hcoord : ∀ p : A × A,
      TopologicalSpace.induced ((fun r : A × A → Prop ↦ r p) ∘ ιSpv) sierpinskiSpace =
        TopologicalSpace.generateFrom {basicOpen p.1 p.2} := by
    intro p
    rw [show sierpinskiSpace = TopologicalSpace.generateFrom {{True}} from rfl,
        induced_generateFrom_eq]
    congr 1
    ext s
    refine ⟨?_, ?_⟩
    · rintro ⟨t, ht, rfl⟩
      rw [Set.mem_singleton_iff] at ht
      subst ht
      refine Set.mem_singleton_iff.mpr ?_
      ext v
      simp [Function.comp, ιSpv, basicOpen]
    · rintro hs
      rw [Set.mem_singleton_iff] at hs
      refine ⟨{True}, Set.mem_singleton _, ?_⟩
      subst hs
      ext v
      simp [Function.comp, ιSpv, basicOpen]
  simp_rw [induced_compose, hcoord]
  -- Match the iInf of single-generator topologies to the Spv topology.
  rw [show (⨅ p : A × A, TopologicalSpace.generateFrom {basicOpen p.1 p.2}) =
      TopologicalSpace.generateFrom (⋃ p : A × A, {basicOpen p.1 p.2}) from
      generateFrom_iUnion.symm]
  unfold ValuationSpectrum.instTopologicalSpace
  congr 1
  ext U
  simp only [Set.mem_iUnion, Set.mem_singleton_iff, Set.mem_ofPred_eq, Prod.exists]

/-- **Huber embedding — Phase 1 main result.** The map `ιSpv : Spv A → (A × A → Prop)`
is a topological embedding (injective + induced topology agrees).

This is the content of the topological half of Wedhorn's Theorem 4.9 / Huber 1993, Lemma
2.1. The compactness conclusion additionally requires closedness of the image, which is
deferred to Phase 2. -/
theorem ιSpv_isEmbedding : Topology.IsEmbedding (ιSpv : Spv A → (A × A → Prop)) where
  eq_induced := ιSpv_isInducing.eq_induced
  injective := ιSpv_injective

/-- **Sierpinski `Prop` is T0.** Two points `True` and `False` are
distinguished by the open set `{True}`. -/
instance : T0Space Prop := by
  refine ⟨fun p q hpq ↦ ?_⟩
  have hopen : IsOpen ({True} : Set Prop) :=
    TopologicalSpace.GenerateOpen.basic _ (Set.mem_singleton _)
  have hiff : p ∈ ({True} : Set Prop) ↔ q ∈ ({True} : Set Prop) := hpq.mem_open_iff hopen
  -- p ∈ {True} iff p = True iff p (since p : Prop).
  simp only [Set.mem_singleton_iff, eq_iff_iff, iff_true] at hiff
  exact propext hiff

/-- **`Spv A` is T0.** Inherited from the Huber embedding into the
T0 product `(A × A → Prop)`. -/
instance : T0Space (Spv A) := ιSpv_isEmbedding.t0Space

/-- **`{True}` is dense in Sierpinski `Prop`.** Equivalently `closure {True} = Set.univ`. -/
lemma dense_true : Dense ({True} : Set Prop) := by
  intro p
  rw [mem_closure_iff]
  intro U hU hpU
  refine ⟨True, ?_, Set.mem_singleton _⟩
  -- True ∈ U: induct on open structure.
  induction hU with
  | basic s hs =>
    rw [show s = {True} from (Set.mem_singleton_iff.mp hs)]
    exact Set.mem_singleton _
  | univ => trivial
  | inter U₁ U₂ _ _ ih₁ ih₂ =>
    exact ⟨ih₁ hpU.1, ih₂ hpU.2⟩
  | sUnion S _ ih =>
    obtain ⟨s, hsS, hps⟩ := hpU
    exact ⟨s, hsS, ih s hsS hps⟩

/-- **Sierpinski `Prop` is QuasiSober.** -/
instance : QuasiSober Prop where
  sober {S} hirr hclosed := by
    by_cases hT : (True : Prop) ∈ S
    · -- True ∈ S → S ⊇ closure({True}) = Set.univ.
      refine ⟨True, ?_⟩
      have hsub : closure ({True} : Set Prop) ⊆ S :=
        hclosed.closure_subset_iff.mpr (Set.singleton_subset_iff.mpr hT)
      have hSuniv : S = Set.univ :=
        Set.eq_univ_of_univ_subset (dense_true.closure_eq ▸ hsub)
      rw [hSuniv]
      exact dense_true.closure_eq
    · -- True ∉ S, S nonempty + closed → S ⊆ {False} (since p ∈ S → p ≠ True).
      refine ⟨False, ?_⟩
      have hSsub : S ⊆ {False} := by
        intro p hp
        rw [Set.mem_singleton_iff, eq_iff_iff, iff_false]
        intro hpT
        exact hT (eq_true hpT ▸ hp)
      obtain ⟨p, hp⟩ := hirr.nonempty
      have hFmem : False ∈ S := by
        have : p = False := Set.mem_singleton_iff.mp (hSsub hp)
        exact this ▸ hp
      have hSeq : S = {False} :=
        Set.eq_singleton_iff_unique_mem.mpr ⟨hFmem, fun q hq ↦ Set.mem_singleton_iff.mp (hSsub hq)⟩
      rw [hSeq]
      apply IsClosed.closure_eq
      -- {False} = {True}ᶜ in Prop, and {True} is open.
      have hcompl : ({False} : Set Prop) = ({True} : Set Prop)ᶜ := by
        ext q; simp [Set.mem_singleton_iff, eq_iff_iff]
      rw [hcompl, isClosed_compl_iff]
      exact TopologicalSpace.GenerateOpen.basic _ (Set.mem_singleton _)



/-! ### Characterising the image of `ιSpv`

We now capture the **set-theoretic** image of `ιSpv` via a predicate `IsValuationChar`.
An `r : A × A → Prop` lies in the range of `ιSpv` iff:

* a *recovered* preorder `vleOf r` (built from `vle_iff_ιSpv`) satisfies all six
  `ValuativeRel` axioms, and
* `r` itself is the basic-open indicator of that preorder:
  `r (f, s) ↔ vleOf r f s ∧ ¬ vleOf r s 0`.

The first family of conditions alone is not enough to force `r = ιSpv v` for the
associated `v`: we also need to know that `r` is the characteristic function of *that*
preorder's basic opens rather than some unrelated function. The extra `apply_iff`
field in `IsValuationChar` records that round-trip condition, and as we shall see it is
automatic for any `r = ιSpv v`.

The **topological** part — showing `{r | IsValuationChar r}` is closed in the product
Sierpinski topology — is still deferred to a later phase (see the TODO block at the end
of this file). -/

/-- The preorder on `A` recovered from a characteristic function `r : A × A → Prop`,
matching `vle_iff_ιSpv`: `v.vle f s ↔ r (f, s) ∨ (¬ r (s, s) ∧ ¬ r (f, f))`. -/
def vleOf (r : A × A → Prop) (f s : A) : Prop :=
  r (f, s) ∨ (¬ r (s, s) ∧ ¬ r (f, f))

lemma vleOf_ιSpv (v : Spv A) (f s : A) : vleOf (ιSpv v) f s ↔ v.vle f s :=
  (vle_iff_ιSpv v f s).symm

/-- A characteristic function `r : A × A → Prop` is a **valuation characteristic**
iff:

* the recovered preorder `vleOf r` satisfies the six `ValuativeRel` axioms
  (total, transitive, additive, left-multiplicative, cancellative, and `¬ 1 ≤ 0`);
* `r` is the basic-open indicator of that preorder — i.e.
  `r (f, s) ↔ vleOf r f s ∧ ¬ vleOf r s 0` for every `(f, s)`.

By `vle_iff_ιSpv` every `ιSpv v` is a valuation characteristic, and conversely every
valuation characteristic comes from a unique `v : Spv A` (see
`ιSpv_mem_isValuationChar` and `exists_spv_of_isValuationChar`). -/
structure IsValuationChar (r : A × A → Prop) : Prop where
  /-- Totality: `vleOf r f s ∨ vleOf r s f`. -/
  vle_total : ∀ f s : A, vleOf r f s ∨ vleOf r s f
  /-- Transitivity of the recovered preorder. -/
  vle_trans : ∀ {x y z : A}, vleOf r x y → vleOf r y z → vleOf r x z
  /-- Additivity: `vleOf r x z → vleOf r y z → vleOf r (x + y) z`. -/
  vle_add : ∀ {x y z : A}, vleOf r x z → vleOf r y z → vleOf r (x + y) z
  /-- Left multiplication by a constant preserves the preorder. -/
  mul_vle_mul_left : ∀ {x y : A} (_ : vleOf r x y) (z : A), vleOf r (x * z) (y * z)
  /-- Cancellation: a non-zero factor can be removed from both sides. -/
  vle_mul_cancel : ∀ {x y z : A}, ¬ vleOf r z 0 → vleOf r (x * z) (y * z) → vleOf r x y
  /-- Non-triviality: `1` is not `≤ 0`. -/
  not_vle_one_zero : ¬ vleOf r 1 0
  /-- Consistency: `r` is the basic-open indicator of the recovered preorder. -/
  apply_iff : ∀ f s : A, r (f, s) ↔ vleOf r f s ∧ ¬ vleOf r s 0

/-- Every point `v : Spv A` gives a valuation characteristic `ιSpv v`. -/
lemma ιSpv_mem_isValuationChar (v : Spv A) : IsValuationChar (ιSpv v) := by
  refine
    { vle_total := ?_, vle_trans := ?_, vle_add := ?_,
      mul_vle_mul_left := ?_, vle_mul_cancel := ?_, not_vle_one_zero := ?_,
      apply_iff := ?_ }
  · intro f s
    rcases v.vle_total f s with h | h
    · exact Or.inl ((vleOf_ιSpv v f s).mpr h)
    · exact Or.inr ((vleOf_ιSpv v s f).mpr h)
  · intro x y z hxy hyz
    exact (vleOf_ιSpv v x z).mpr
      (v.vle_trans ((vleOf_ιSpv v x y).mp hxy) ((vleOf_ιSpv v y z).mp hyz))
  · intro x y z hxz hyz
    exact (vleOf_ιSpv v _ _).mpr
      (v.vle_add ((vleOf_ιSpv v x z).mp hxz) ((vleOf_ιSpv v y z).mp hyz))
  · intro x y hxy z
    exact (vleOf_ιSpv v _ _).mpr
      (v.mul_vle_mul_left ((vleOf_ιSpv v x y).mp hxy) z)
  · intro x y z hz h
    refine (vleOf_ιSpv v x y).mpr (v.vle_mul_cancel ?_ ((vleOf_ιSpv v _ _).mp h))
    intro hz0
    exact hz ((vleOf_ιSpv v z 0).mpr hz0)
  · intro h
    exact v.not_vle_one_zero ((vleOf_ιSpv v 1 0).mp h)
  · intro f s
    constructor
    · intro h
      refine ⟨(vleOf_ιSpv v f s).mpr h.1, ?_⟩
      intro hs
      exact h.2 ((vleOf_ιSpv v s 0).mp hs)
    · rintro ⟨hfs, hs0⟩
      exact ⟨(vleOf_ιSpv v f s).mp hfs, fun hs ↦ hs0 ((vleOf_ιSpv v s 0).mpr hs)⟩

/-- A valuation characteristic `r` determines a `ValuativeRel` on `A` with `vle = vleOf r`.

This packages the six axioms carried by `IsValuationChar r` as a `ValuativeRel` record,
so that the `Spv A` whose underlying relation is `vleOf r` can be formed. -/
@[implicit_reducible]
def IsValuationChar.toValuativeRel {r : A × A → Prop} (hr : IsValuationChar r) :
    ValuativeRel A where
  vle f s := vleOf r f s
  vle_total := hr.vle_total
  vle_trans := hr.vle_trans
  vle_add := hr.vle_add
  mul_vle_mul_left := hr.mul_vle_mul_left
  vle_mul_comm := by intro x y; rw [mul_comm]; exact (hr.vle_total _ _).elim id id
  vle_mul_cancel := hr.vle_mul_cancel
  not_vle_one_zero := hr.not_vle_one_zero

/-- The `Spv A` point associated to a valuation characteristic `r`. -/
def IsValuationChar.toSpv {r : A × A → Prop} (hr : IsValuationChar r) : Spv A :=
  ⟨hr.toValuativeRel⟩

@[simp] lemma IsValuationChar.toSpv_vle {r : A × A → Prop} (hr : IsValuationChar r)
    (f s : A) : hr.toSpv.vle f s ↔ vleOf r f s := Iff.rfl

/-- **Valuation-characteristic inverse to `ιSpv`.** Every valuation characteristic is in
the image of `ιSpv`: from `hr : IsValuationChar r`, the point `hr.toSpv` satisfies
`ιSpv hr.toSpv = r`. -/
lemma ιSpv_toSpv {r : A × A → Prop} (hr : IsValuationChar r) :
    ιSpv hr.toSpv = r := by
  funext p
  obtain ⟨f, s⟩ := p
  change (hr.toSpv.vle f s ∧ ¬ hr.toSpv.vle s 0) = r (f, s)
  rw [hr.toSpv_vle, hr.toSpv_vle]
  exact propext (hr.apply_iff f s).symm

/-- Existence form of the inverse: every `r` with `IsValuationChar r` lies in the range
of `ιSpv`. -/
lemma exists_spv_of_isValuationChar {r : A × A → Prop} (hr : IsValuationChar r) :
    ∃ v : Spv A, ιSpv v = r :=
  ⟨hr.toSpv, ιSpv_toSpv hr⟩

/-- **Main characterisation of the range of `ιSpv`.** An `r : A × A → Prop` is in the
range of `ιSpv` iff it is a valuation characteristic. -/
theorem isValuationChar_iff_mem_range (r : A × A → Prop) :
    IsValuationChar r ↔ ∃ v : Spv A, ιSpv v = r :=
  ⟨exists_spv_of_isValuationChar, fun ⟨v, hv⟩ ↦ hv ▸ ιSpv_mem_isValuationChar v⟩

/-- The image of `ιSpv` as a set equals the set of valuation characteristics. -/
theorem range_ιSpv :
    Set.range (ιSpv : Spv A → (A × A → Prop)) = {r | IsValuationChar r} := by
  ext r
  simp only [Set.mem_range, Set.mem_ofPred_eq]
  exact (isValuationChar_iff_mem_range r).symm

/-! ### Sierpinski coordinate sub-basics

Each coordinate evaluation `r ↦ r p : (A × A → Prop) → Prop` is continuous (it is a
projection in a product topology). Combined with the Sierpinski facts that `{True}` is
open and `{False}` is closed, this yields two basic topological facts about the product:

* `{r | r p}` is **open** (sub-basis of the product Sierpinski topology),
* `{r | ¬ r p}` is **closed** (its complement is the open set above).

These are the only "building blocks" of the product topology (and its closed sets); see
the asymmetry note at the end of this file. -/

omit [CommRing A] in
/-- The coordinate-evaluation set `{r | r p}` is open in the Sierpinski product. -/
lemma isOpen_setOf_apply (p : A × A) :
    IsOpen {r : A × A → Prop | r p} :=
  continuous_Prop.mp (continuous_apply p)

omit [CommRing A] in
/-- The coordinate-negation set `{r | ¬ r p}` is closed in the Sierpinski product. -/
lemma isClosed_setOf_not_apply (p : A × A) :
    IsClosed {r : A × A → Prop | ¬ r p} :=
  (isOpen_setOf_apply p).isClosed_compl

/-! ### Compactness of the product space

`Prop` is finite and hence compact in every topology (in particular the Sierpinski
topology `sierpinskiSpace`). Tychonoff (`Pi.compactSpace`) then gives compactness of the
full function space. This is the target compact ambient space for the Huber embedding. -/

/-- `Prop` with its Sierpinski topology is compact (indeed, `Prop` is finite). -/
instance : CompactSpace Prop := Finite.compactSpace

/-- **Tychonoff for the Huber ambient space.** The product `A × A → Prop`, with each
factor in the Sierpinski topology, is compact. -/
instance : CompactSpace (A × A → Prop) := Pi.compactSpace

/-! ### Phase 2: Sierpinski closedness fails; pivot to Alexander sub-basis

The naive Phase 2 plan — "show `IsClosed {r | IsValuationChar r}` in the product
Sierpinski topology, then conclude `CompactSpace (Spv A)` via `range_ιSpv`,
`ιSpv_isEmbedding`, and closed-subspace-of-compact-is-compact" — **does not succeed in
this topology**. The obstruction is intrinsic to the Sierpinski choice and not a matter
of proof engineering; we record the counterexample briefly below, then turn to the
correct route (Alexander's sub-basis theorem, `compactSpace_generateFrom`).

#### Why the Sierpinski range is generally *not* closed

Sierpinski declares `{True}` open but not closed; the closed sub-basic sets in the
product are exactly of the form `{r | ¬ r p}`. A basic Sierpinski neighbourhood of a
point `r₀` is determined by the *True*-coordinates of `r₀` and can never forbid "True"
at further coordinates. Taking `s ∈ A` not nilpotent and `r₀ p := (p = (s, s))` one
checks `r₀` is not a valuation characteristic (e.g. `vle_total` fails at `(f, s)` for
most `f`), yet every Sierpinski neighbourhood of `r₀` meets `Set.range ιSpv` (via a
valuation `v` with `s ∉ supp v`). Hence the range is *not* closed in the Sierpinski
product. The same pathology means `vle_total` itself is not pointwise closed in this
topology.

#### The Alexander route

Mathlib's `compactSpace_generateFrom` (a.k.a. **Alexander's subbasis theorem**, in
`Mathlib.Topology.Compactness.Compact`) states that a topological space is compact
whenever every cover by elements of a chosen subbasis admits a finite subcover. The
`Spv A` topology is defined exactly as `generateFrom {U | ∃ f s, U = basicOpen f s}`
(see `ValuationSpectrum.instTopologicalSpace`), so Alexander applies directly, with
**no need for any embedding or closed-subspace argument**. This avoids the Sierpinski
obstruction outlined above and gives the cleanest path to `CompactSpace (Spv A)`.

We set up the Alexander API below: we expose a reusable reformulation
`compactSpace_iff_subbasic_subcover` that converts `CompactSpace (Spv A)` into the
concrete finite-subcover condition on families `(f_i, s_i)`. The **verification** of
that condition is the genuine Huber content (Wedhorn Thm 4.9 / Huber 1993) and is
still left open: the standard proof runs a Zorn / ultrafilter argument on pairs
`(valuation, prime)`, which is sizeable valuation-theoretic work. -/

/-! ### Alexander sub-basis reformulation of Spv compactness -/

/-- Membership in the Spv sub-basis: `U` is a sub-basic open iff `U = basicOpen f s`
for some `f s : A`. This is a restatement of the defining set of
`ValuationSpectrum.instTopologicalSpace`. -/
def IsSubbasicOpen (U : Set (Spv A)) : Prop := ∃ f s : A, U = basicOpen f s

/-- The Spv topology is `generateFrom` the set of sub-basic opens. Unfolds the
definition of `instTopologicalSpace`. -/
lemma instTopologicalSpace_eq_generateFrom :
    (instTopologicalSpace : TopologicalSpace (Spv A)) =
      TopologicalSpace.generateFrom {U | IsSubbasicOpen U} := rfl

/-- **Alexander sub-basis theorem, applied to `Spv A`.** If every cover of `Spv A`
by sub-basic opens (basic opens `basicOpen f s`) admits a finite subcover, then
`Spv A` is compact.

This is the direct content of Wedhorn Theorem 4.9 / Huber, *Continuous valuations*
(1993), reformulated purely as a statement about covers of the underlying type by
basic opens. -/
theorem compactSpace_of_subbasic_subcover
    (h : ∀ P ⊆ {U : Set (Spv A) | IsSubbasicOpen U}, ⋃₀ P = Set.univ →
      ∃ Q ⊆ P, Q.Finite ∧ ⋃₀ Q = Set.univ) :
    CompactSpace (Spv A) :=
  compactSpace_generateFrom instTopologicalSpace_eq_generateFrom h

/-- **Converse direction.** If `Spv A` is compact, then every cover of `Spv A` by
sub-basic opens admits a finite subcover. (Trivial direction: every sub-basic open is
open, so this is just `IsCompact.elim_finite_subcover_image`.) -/
theorem subbasic_subcover_of_compactSpace [CompactSpace (Spv A)]
    (P : Set (Set (Spv A))) (hP : P ⊆ {U : Set (Spv A) | IsSubbasicOpen U})
    (hcov : ⋃₀ P = Set.univ) :
    ∃ Q ⊆ P, Q.Finite ∧ ⋃₀ Q = Set.univ := by
  have hopen : ∀ U ∈ P, IsOpen U := by
    intro U hU
    obtain ⟨f, s, rfl⟩ := hP hU
    exact TopologicalSpace.isOpen_generateFrom_of_mem ⟨f, s, rfl⟩
  have hcompact : IsCompact (Set.univ : Set (Spv A)) := isCompact_univ
  obtain ⟨Q, hQP, hQfin, hQcov⟩ :=
    hcompact.elim_finite_subcover_image hopen (by simpa [Set.sUnion_eq_biUnion] using hcov.ge)
  refine ⟨Q, hQP, hQfin, ?_⟩
  apply Set.eq_univ_of_univ_subset
  simpa [Set.sUnion_eq_biUnion] using hQcov

/-- **Alexander reformulation.** `Spv A` is compact **iff** every cover by sub-basic
opens admits a finite subcover. This reduces the compactness question for the
valuation spectrum to a purely combinatorial statement about families of basic
opens. -/
theorem compactSpace_iff_subbasic_subcover :
    CompactSpace (Spv A) ↔ ∀ P ⊆ {U : Set (Spv A) | IsSubbasicOpen U},
      ⋃₀ P = Set.univ → ∃ Q ⊆ P, Q.Finite ∧ ⋃₀ Q = Set.univ :=
  ⟨fun _ ↦ subbasic_subcover_of_compactSpace,
    fun h ↦ compactSpace_of_subbasic_subcover h⟩


/-! ### Status of `CompactSpace (Spv A)`

`compactSpace_of_subbasic_subcover` (and the equivalent
`compactSpace_iff_subbasic_subcover`) reduces the compactness of `Spv A` to a
finite-subcover property for families of basic opens. Mathematically, the
statement we still need is:

  `∀ P ⊆ {basicOpen f s | f s : A}, ⋃₀ P = univ → ∃ Q ⊆ P finite, ⋃₀ Q = univ`.

Standard proofs (Huber 1993 Lemma 2.1; Wedhorn, *Adic Spaces*, proof of Thm 4.9) go
via an ultrafilter / Zorn argument on pairs `(valuation, prime)`: assuming no finite
subcover, one picks an ultrafilter on the failures, extracts a compatible
`(valuation ring, prime ideal)` configuration, and shows the resulting `v ∈ Spv A`
is not in any `basicOpen (f i) (s i)`, contradicting the hypothesised cover. This
requires substantial valuation-ring infrastructure (existence of valuation rings
dominating a local ring, Chevalley-style extension lemmas). It is out of scope for
the present file.

Alternative routes that do not depend on this extension theory:

* Realise `Spv A` as a spectral space via `PrimeSpectrum.compactSpace` of an auxiliary
  ring (Huber's 1993 construction via the valuation ring of the generic fibre). This
  is conceptually cleaner but needs the full `Γ`-valuation equivalence.

* Embed into a discrete power `(A × A → Bool)` (compact by Tychonoff + `Finite Bool`)
  with the image characterised as a closed subset by clopen cylinder conditions for
  each `ValuativeRel` axiom, then transfer compactness through `ιSpv_isEmbedding`.
  This route is scaffolded below (`ιSpvBool`, `boolToProp`, and the factorisation
  `ιSpv_eq_boolToProp_comp_ιSpv_bool`) so that the remaining obligation is exactly
  `IsClosed (Set.range ιSpvBool)` — an intersection of ≤ 7 closed cylinder
  families, one per `IsValuationChar` field. Completing this step would yield
  `CompactSpace (Spv A)` via `ιSpv_isEmbedding.isCompact_iff`.

The ambient compactness instances and the Sierpinski embedding
(`ιSpv_isEmbedding`, `range_ιSpv`) remain useful for either route, and the
Alexander reformulation provided here is the cleanest interface for the
ultrafilter-style proof. -/

/-! ### Scaffolding for the Bool / discrete-product route

We expose the Bool-valued version of the Huber embedding,

  `ιSpvBool : Spv A → (A × A → Bool)`, `v ↦ fun p => decide (v ∈ basicOpen p.1 p.2)`,

together with the coordinate-wise conversion `boolToProp : Bool → Prop`, so that
`ιSpv = boolToProp ∘ ιSpvBool`. The target space `(A × A → Bool)` carries the
product of the discrete topology on `Bool`; it is compact by Tychonoff and `Finite
Bool`. Finishing the compactness proof reduces to showing `IsClosed (Set.range
ιSpvBool)` in this discrete product — a closed-cylinder argument on the
`IsValuationChar` axioms. -/

/-- **Bool-valued Huber embedding.** Encodes `v ∈ basicOpen p.1 p.2` as a Bool. -/
noncomputable def ιSpvBool (v : Spv A) : A × A → Bool := fun p ↦
  @decide (v.vle p.1 p.2 ∧ ¬ v.vle p.2 0) (Classical.dec _)

-- (We state the decidability explicitly via `Classical.dec` rather than relying on
-- the `open Classical` diamond, since the underlying `ValuativeRel.vle` has no
-- automatic `Decidable` instance.)

@[simp]
lemma ιSpv_bool_apply (v : Spv A) (f s : A) :
    ιSpvBool v (f, s) = (@decide _ (Classical.dec (v.vle f s ∧ ¬ v.vle s 0))) := rfl

/-- Pointwise conversion `Bool → Prop`: `true ↦ True`, `false ↦ False` (via equality).
-/
def boolToProp (b : Bool) : Prop := b = true

omit [CommRing A] in
@[simp]
lemma boolToProp_decide {p : Prop} (hp : Decidable p) : boolToProp (decide p) ↔ p :=
  decide_eq_true_iff

/-- **Factorisation:** `ιSpv = (boolToProp ∘ ·) ∘ ιSpvBool`. In particular, the
Sierpinski-valued embedding is the continuous image of the Bool-valued one under
the coordinate-wise `boolToProp` map. -/
lemma ιSpv_eq_boolToProp_comp_ιSpv_bool (v : Spv A) :
    ιSpv v = fun p ↦ boolToProp (ιSpvBool v p) := by
  funext p
  simp only [ιSpv, ιSpvBool, boolToProp]
  exact propext (@decide_eq_true_iff _ (Classical.dec _)).symm

/-- `ιSpvBool` is injective. Follows from `ιSpv_injective` via the factorisation,
since `boolToProp` is injective on `Bool`. -/
lemma ιSpv_bool_injective : Function.Injective (ιSpvBool : Spv A → _) := by
  intro v₁ v₂ h
  apply ιSpv_injective
  rw [ιSpv_eq_boolToProp_comp_ιSpv_bool, ιSpv_eq_boolToProp_comp_ιSpv_bool, h]

/-- `Bool` is compact in its discrete topology (it is finite). -/
example : CompactSpace Bool := Finite.compactSpace

/-- **Tychonoff, Bool version.** The product `A × A → Bool` with discrete factors is
compact. Together with `Finite.compactSpace` and `DiscreteTopology Bool` this gives
a Cantor-style compactum as ambient space for the Bool Huber embedding. -/
instance : CompactSpace (A × A → Bool) := Pi.compactSpace

omit [CommRing A] in
/-- The coordinate-wise `boolToProp` map
`(A × A → Bool) → (A × A → Prop)` is continuous. Each coordinate reduces to the map
`b ↦ (b = true) : Bool → Prop` with Sierpinski codomain, which pulls back `{True}` to
`{true}` — open in discrete `Bool`. -/
lemma continuous_boolToProp_pi :
    Continuous (fun r : A × A → Bool ↦ (fun p ↦ boolToProp (r p)) : _ → (A × A → Prop)) := by
  refine continuous_pi fun p ↦ ?_
  -- `fun r => boolToProp (r p) = ((r p = true))` is the composition of `r ↦ r p`
  -- (continuous, `continuous_apply`) with `b ↦ b = true : Bool → Prop` (continuous
  -- since `Bool` is discrete).
  have h1 : Continuous (fun r : A × A → Bool ↦ r p) := continuous_apply p
  have h2 : Continuous (fun b : Bool ↦ boolToProp b) := by
    exact continuous_of_discreteTopology
  exact h2.comp h1

/-! ### Closedness of `range ιSpvBool` in the discrete Bool product

We now carry out the closed-cylinder argument: each `IsValuationChar` axiom,
evaluated at `fun p => r p = true` for `r : A × A → Bool`, is an intersection of
clopen cylinder sets in `(A × A → Bool)` (with the discrete product topology).
The arbitrary intersection of clopens is closed, so `range ιSpvBool` is closed.

Combined with the ambient `CompactSpace (A × A → Bool)` and the factorisation
`ιSpv = (boolToProp ∘ ·) ∘ ιSpvBool` plus continuity of the coordinate-wise
`boolToProp` map, this gives `IsCompact (range ιSpv)`, which via
`ιSpv_isEmbedding.isCompact_iff Set.univ` yields `CompactSpace (Spv A)`. -/

/-- The **Bool-valued recovered preorder** on `A` associated to `r : A × A → Bool`.
This is the pointwise Bool image of `vleOf (fun p ↦ r p = true)`; see
`vleOfBool_iff_vleOf_decide` below. -/
def vleOfBool (r : A × A → Bool) (f s : A) : Prop :=
  r (f, s) = true ∨ (r (s, s) = false ∧ r (f, f) = false)

omit [CommRing A] in
lemma vleOfBool_iff_vleOf_decide (r : A × A → Bool) (f s : A) :
    vleOfBool r f s ↔ vleOf (fun p ↦ r p = true) f s := by
  simp only [vleOfBool, vleOf, Bool.not_eq_true]

/-- A `r : A × A → Bool` is a **Bool valuation characteristic** iff the Prop-valued
function `fun p => r p = true` is a valuation characteristic in the sense of
`IsValuationChar`. -/
def IsValuationCharBool (r : A × A → Bool) : Prop :=
  IsValuationChar (fun p ↦ r p = true)

omit [CommRing A] in
/-- Coordinate-at-a-point evaluation is continuous on `A × A → Bool`. -/
lemma continuous_coord_bool (p : A × A) :
    Continuous (fun r : A × A → Bool ↦ r p) := continuous_apply p

omit [CommRing A] in
/-- Every singleton in the discrete `Bool` is open; hence `{r | r p = b}` is
open in the discrete product. -/
lemma isOpen_coord_eq (p : A × A) (b : Bool) :
    IsOpen {r : A × A → Bool | r p = b} :=
  (continuous_coord_bool p).isOpen_preimage {b} (isOpen_discrete {b})

omit [CommRing A] in
/-- The set `{r | r p = b}` is **closed** in the discrete product. -/
lemma isClosed_coord_eq (p : A × A) (b : Bool) :
    IsClosed {r : A × A → Bool | r p = b} :=
  (isClosed_discrete {b}).preimage (continuous_coord_bool p)

omit [CommRing A] in
/-- The set `{r | r (f,s) = true}` is closed (and open) in the discrete product. -/
lemma isClosed_coord_true (p : A × A) :
    IsClosed {r : A × A → Bool | r p = true} := isClosed_coord_eq p true

omit [CommRing A] in
/-- The set `{r | r (f,s) = false}` is closed (and open) in the discrete product. -/
lemma isClosed_coord_false (p : A × A) :
    IsClosed {r : A × A → Bool | r p = false} := isClosed_coord_eq p false

/-! #### Closedness of the individual `IsValuationChar` axioms (Bool form) -/

omit [CommRing A] in
/-- The set `{r | vleOfBool r f s}` is closed in the discrete product. -/
lemma isClosed_vleOfBool (f s : A) :
    IsClosed {r : A × A → Bool | vleOfBool r f s} := by
  -- vleOfBool r f s = r (f,s) = true ∨ (r (s,s) = false ∧ r (f,f) = false)
  have h1 : IsClosed {r : A × A → Bool | r (f, s) = true} := isClosed_coord_true (f, s)
  have h2 : IsClosed {r : A × A → Bool | r (s, s) = false} := isClosed_coord_false (s, s)
  have h3 : IsClosed {r : A × A → Bool | r (f, f) = false} := isClosed_coord_false (f, f)
  -- The target set is h1 ∪ (h2 ∩ h3).
  have : {r : A × A → Bool | vleOfBool r f s} =
      {r | r (f, s) = true} ∪ ({r | r (s, s) = false} ∩ {r | r (f, f) = false}) := by
    ext r; simp [vleOfBool]
  rw [this]; exact h1.union (h2.inter h3)

omit [CommRing A] in
/-- The set `{r | ¬ vleOfBool r u v}` is closed in the discrete product. -/
lemma isClosed_not_vleOfBool (u v : A) :
    IsClosed {r : A × A → Bool | ¬ vleOfBool r u v} := by
  -- ¬ vleOfBool r u v = (r (u,v) = false) ∧ (r (v,v) = true ∨ r (u,u) = true)
  have : {r : A × A → Bool | ¬ vleOfBool r u v} =
      {r | r (u, v) = false} ∩
        ({r | r (v, v) = true} ∪ {r | r (u, u) = true}) := by
    ext r
    constructor
    · intro h
      simp only [vleOfBool, not_or, not_and_or, Bool.not_eq_true, Bool.not_eq_false] at h
      refine ⟨h.1, ?_⟩
      rcases h.2 with h2 | h2
      · exact Or.inl h2
      · exact Or.inr h2
    · rintro ⟨h1, h2⟩ hv
      rcases hv with hv | ⟨hvv, huu⟩
      · exact absurd hv (by rw [h1]; decide)
      · rcases h2 with h2 | h2
        · exact absurd hvv (by rw [h2]; decide)
        · exact absurd huu (by rw [h2]; decide)
  rw [this]
  exact (isClosed_coord_false (u, v)).inter
    ((isClosed_coord_true (v, v)).union (isClosed_coord_true (u, u)))

omit [CommRing A] in
/-- **Closedness of `vle_total` in Bool form.** -/
lemma isClosed_vle_total_bool :
    IsClosed {r : A × A → Bool | ∀ f s : A, vleOfBool r f s ∨ vleOfBool r s f} := by
  rw [show {r : A × A → Bool | ∀ f s : A, vleOfBool r f s ∨ vleOfBool r s f} =
      ⋂ (f : A), ⋂ (s : A), {r | vleOfBool r f s ∨ vleOfBool r s f} by
    ext r; simp]
  exact isClosed_iInter fun f ↦ isClosed_iInter fun s ↦
    (isClosed_vleOfBool f s).union (isClosed_vleOfBool s f)

omit [CommRing A] in
/-- **Closedness of `vle_trans` in Bool form.** A single universally quantified
implication `A → B` is closed since `{r | A → B} = {r | ¬A} ∪ {r | B}`, and both
pieces are clopens in the Bool product. -/
lemma isClosed_vle_trans_bool :
    IsClosed {r : A × A → Bool |
      ∀ x y z : A, vleOfBool r x y → vleOfBool r y z → vleOfBool r x z} := by
  rw [show {r : A × A → Bool |
      ∀ x y z : A, vleOfBool r x y → vleOfBool r y z → vleOfBool r x z} =
      ⋂ (x : A), ⋂ (y : A), ⋂ (z : A),
        {r | vleOfBool r x y → vleOfBool r y z → vleOfBool r x z} by
    ext r; simp]
  refine isClosed_iInter fun x ↦ isClosed_iInter fun y ↦ isClosed_iInter fun z ↦ ?_
  have rewriteEq :
      {r : A × A → Bool |
        vleOfBool r x y → vleOfBool r y z → vleOfBool r x z} =
      {r | ¬ vleOfBool r x y} ∪ {r | ¬ vleOfBool r y z} ∪
        {r | vleOfBool r x z} := by
    ext r
    constructor
    · intro h
      by_cases h1 : vleOfBool r x y
      · by_cases h2 : vleOfBool r y z
        · exact Or.inr (h h1 h2)
        · exact Or.inl (Or.inr h2)
      · exact Or.inl (Or.inl h1)
    · rintro ((h1 | h2) | h3) hxy hyz
      · exact absurd hxy h1
      · exact absurd hyz h2
      · exact h3
  rw [rewriteEq]
  exact ((isClosed_not_vleOfBool x y).union (isClosed_not_vleOfBool y z)).union
    (isClosed_vleOfBool x z)

/-- **Closedness of `vle_add` in Bool form.** -/
lemma isClosed_vle_add_bool :
    IsClosed {r : A × A → Bool |
      ∀ x y z : A, vleOfBool r x z → vleOfBool r y z → vleOfBool r (x + y) z} := by
  rw [show {r : A × A → Bool |
      ∀ x y z : A, vleOfBool r x z → vleOfBool r y z → vleOfBool r (x + y) z} =
      ⋂ (x : A), ⋂ (y : A), ⋂ (z : A),
        {r | vleOfBool r x z → vleOfBool r y z → vleOfBool r (x + y) z} by
    ext r; simp]
  refine isClosed_iInter fun x ↦ isClosed_iInter fun y ↦ isClosed_iInter fun z ↦ ?_
  have rewriteEq :
      {r : A × A → Bool |
        vleOfBool r x z → vleOfBool r y z → vleOfBool r (x + y) z} =
      {r | ¬ vleOfBool r x z} ∪ {r | ¬ vleOfBool r y z} ∪
        {r | vleOfBool r (x + y) z} := by
    ext r
    constructor
    · intro h
      by_cases h1 : vleOfBool r x z
      · by_cases h2 : vleOfBool r y z
        · exact Or.inr (h h1 h2)
        · exact Or.inl (Or.inr h2)
      · exact Or.inl (Or.inl h1)
    · rintro ((h1 | h2) | h3) hxz hyz
      · exact absurd hxz h1
      · exact absurd hyz h2
      · exact h3
  rw [rewriteEq]
  exact ((isClosed_not_vleOfBool x z).union (isClosed_not_vleOfBool y z)).union
    (isClosed_vleOfBool (x + y) z)

/-- **Closedness of `mul_vle_mul_left` in Bool form.** -/
lemma isClosed_mul_vle_mul_left_bool :
    IsClosed {r : A × A → Bool |
      ∀ x y : A, vleOfBool r x y → ∀ z : A, vleOfBool r (x * z) (y * z)} := by
  rw [show {r : A × A → Bool |
      ∀ x y : A, vleOfBool r x y → ∀ z : A, vleOfBool r (x * z) (y * z)} =
      ⋂ (x : A), ⋂ (y : A), ⋂ (z : A),
        {r | vleOfBool r x y → vleOfBool r (x * z) (y * z)} by
    ext r; constructor
    · intro h; simp only [Set.mem_iInter, Set.mem_ofPred_eq]
      intro x y z hxy; exact h x y hxy z
    · intro h x y hxy z; simp only [Set.mem_iInter, Set.mem_ofPred_eq] at h
      exact h x y z hxy]
  refine isClosed_iInter fun x ↦ isClosed_iInter fun y ↦ isClosed_iInter fun z ↦ ?_
  have rewriteEq :
      {r : A × A → Bool |
        vleOfBool r x y → vleOfBool r (x * z) (y * z)} =
      {r | ¬ vleOfBool r x y} ∪ {r | vleOfBool r (x * z) (y * z)} := by
    ext r
    constructor
    · intro h
      by_cases h1 : vleOfBool r x y
      · exact Or.inr (h h1)
      · exact Or.inl h1
    · rintro (h1 | h2) hxy
      · exact absurd hxy h1
      · exact h2
  rw [rewriteEq]
  exact (isClosed_not_vleOfBool x y).union (isClosed_vleOfBool (x * z) (y * z))

/-- **Closedness of `vle_mul_cancel` in Bool form.** -/
lemma isClosed_vle_mul_cancel_bool :
    IsClosed {r : A × A → Bool |
      ∀ x y z : A, ¬ vleOfBool r z 0 → vleOfBool r (x * z) (y * z) → vleOfBool r x y} := by
  rw [show {r : A × A → Bool |
      ∀ x y z : A, ¬ vleOfBool r z 0 → vleOfBool r (x * z) (y * z) → vleOfBool r x y} =
      ⋂ (x : A), ⋂ (y : A), ⋂ (z : A),
        {r | ¬ vleOfBool r z 0 → vleOfBool r (x * z) (y * z) → vleOfBool r x y} by
    ext r; simp]
  refine isClosed_iInter fun x ↦ isClosed_iInter fun y ↦ isClosed_iInter fun z ↦ ?_
  have rewriteEq :
      {r : A × A → Bool |
        ¬ vleOfBool r z 0 → vleOfBool r (x * z) (y * z) → vleOfBool r x y} =
      {r | vleOfBool r z 0} ∪ {r | ¬ vleOfBool r (x * z) (y * z)} ∪
        {r | vleOfBool r x y} := by
    ext r
    constructor
    · intro h
      by_cases h1 : vleOfBool r z 0
      · exact Or.inl (Or.inl h1)
      · by_cases h2 : vleOfBool r (x * z) (y * z)
        · exact Or.inr (h h1 h2)
        · exact Or.inl (Or.inr h2)
    · rintro ((h1 | h2) | h3) hz hxz
      · exact absurd h1 hz
      · exact absurd hxz h2
      · exact h3
  rw [rewriteEq]
  exact ((isClosed_vleOfBool z 0).union (isClosed_not_vleOfBool (x * z) (y * z))).union
    (isClosed_vleOfBool x y)

/-- **Closedness of `not_vle_one_zero` in Bool form.** A single negated condition. -/
lemma isClosed_not_vle_one_zero_bool :
    IsClosed {r : A × A → Bool | ¬ vleOfBool r 1 0} := by
  have : {r : A × A → Bool | ¬ vleOfBool r 1 0} =
      {r | r (1, 0) = false} ∩
        ({r | r (0, 0) = true} ∪ {r | r (1, 1) = true}) := by
    ext r
    constructor
    · intro h
      simp only [vleOfBool, not_or, not_and_or, Bool.not_eq_true, Bool.not_eq_false] at h
      refine ⟨h.1, ?_⟩
      rcases h.2 with h2 | h2
      · exact Or.inl h2
      · exact Or.inr h2
    · rintro ⟨h1, h2⟩ hv
      rcases hv with hv | ⟨hvv, huu⟩
      · exact absurd hv (by rw [h1]; decide)
      · rcases h2 with h2 | h2
        · exact absurd hvv (by rw [h2]; decide)
        · exact absurd huu (by rw [h2]; decide)
  rw [this]
  exact (isClosed_coord_false (1, 0)).inter
    ((isClosed_coord_true (0, 0)).union (isClosed_coord_true (1, 1)))

/-- **Closedness of `apply_iff` (consistency) in Bool form.** The condition is
`r (f,s) = true ↔ vleOfBool r f s ∧ ¬ vleOfBool r s 0`. This is a finite Boolean
combination of coordinate conditions, hence closed. -/
lemma isClosed_apply_iff_bool :
    IsClosed {r : A × A → Bool |
      ∀ f s : A, (r (f, s) = true) ↔ vleOfBool r f s ∧ ¬ vleOfBool r s 0} := by
  rw [show {r : A × A → Bool |
      ∀ f s : A, (r (f, s) = true) ↔ vleOfBool r f s ∧ ¬ vleOfBool r s 0} =
      ⋂ (f : A), ⋂ (s : A),
        {r | (r (f, s) = true) ↔ vleOfBool r f s ∧ ¬ vleOfBool r s 0} by
    ext r; simp]
  refine isClosed_iInter fun f ↦ isClosed_iInter fun s ↦ ?_
  -- `P ↔ Q` = `(¬P ∨ Q) ∧ (P ∨ ¬Q)`.
  have rewriteEq :
      {r : A × A → Bool | (r (f, s) = true) ↔ vleOfBool r f s ∧ ¬ vleOfBool r s 0} =
      ({r | r (f, s) = false} ∪
        ({r | vleOfBool r f s} ∩ {r | ¬ vleOfBool r s 0})) ∩
      ({r | r (f, s) = true} ∪
        ({r | ¬ vleOfBool r f s} ∪ {r | vleOfBool r s 0})) := by
    ext r
    constructor
    · intro h
      refine ⟨?_, ?_⟩
      · by_cases hrfs : r (f, s) = true
        · exact Or.inr (h.mp hrfs)
        · left; exact (Bool.not_eq_true _).mp hrfs
      · by_cases hrhs : vleOfBool r f s ∧ ¬ vleOfBool r s 0
        · exact Or.inl (h.mpr hrhs)
        · right
          rw [not_and_or] at hrhs
          rcases hrhs with hrhs | hrhs
          · exact Or.inl hrhs
          · exact Or.inr (not_not.mp hrhs)
    · rintro ⟨h1, h2⟩
      constructor
      · intro hrfs
        rcases h1 with h1 | h1
        · rw [h1] at hrfs; exact absurd hrfs (by decide)
        · exact h1
      · rintro ⟨hlhs1, hlhs2⟩
        rcases h2 with h2 | h2
        · exact h2
        · rcases h2 with h2 | h2
          · exact absurd hlhs1 h2
          · exact absurd h2 hlhs2
  rw [rewriteEq]
  refine IsClosed.inter ?_ ?_
  · exact (isClosed_coord_false (f, s)).union
      ((isClosed_vleOfBool f s).inter (isClosed_not_vleOfBool s 0))
  · exact (isClosed_coord_true (f, s)).union
      ((isClosed_not_vleOfBool f s).union (isClosed_vleOfBool s 0))

/-! #### Combined closedness of `IsValuationCharBool` -/

/-- Unfolded description of `IsValuationCharBool` as the conjunction of seven
universally quantified conditions, each a closed set in the discrete product. -/
lemma isValuationCharBool_iff (r : A × A → Bool) :
    IsValuationCharBool r ↔
      (∀ f s : A, vleOfBool r f s ∨ vleOfBool r s f) ∧
      (∀ x y z : A, vleOfBool r x y → vleOfBool r y z → vleOfBool r x z) ∧
      (∀ x y z : A, vleOfBool r x z → vleOfBool r y z → vleOfBool r (x + y) z) ∧
      (∀ x y : A, vleOfBool r x y → ∀ z : A, vleOfBool r (x * z) (y * z)) ∧
      (∀ x y z : A, ¬ vleOfBool r z 0 → vleOfBool r (x * z) (y * z) → vleOfBool r x y) ∧
      (¬ vleOfBool r 1 0) ∧
      (∀ f s : A, (r (f, s) = true) ↔ vleOfBool r f s ∧ ¬ vleOfBool r s 0) := by
  simp only [IsValuationCharBool, vleOfBool_iff_vleOf_decide]
  refine ⟨fun hr ↦ ?_, fun hr ↦ ?_⟩
  · refine ⟨hr.vle_total, @hr.vle_trans, @hr.vle_add, @hr.mul_vle_mul_left,
      @hr.vle_mul_cancel, hr.not_vle_one_zero, ?_⟩
    intro f s
    have := hr.apply_iff f s
    -- This unfolds vleOf (fun p => r p = true) f s — already matches.
    exact this
  · obtain ⟨h1, h2, h3, h4, h5, h6, h7⟩ := hr
    exact {
      vle_total := h1
      vle_trans := @h2
      vle_add := @h3
      mul_vle_mul_left := @h4
      vle_mul_cancel := @h5
      not_vle_one_zero := h6
      apply_iff := h7
    }

/-- The set of Bool valuation characteristics is closed in the discrete product. -/
lemma isClosed_isValuationCharBool :
    IsClosed {r : A × A → Bool | IsValuationCharBool r} := by
  -- Unfold IsValuationCharBool to a conjunction of the seven axioms, each closed.
  have hEq : {r : A × A → Bool | IsValuationCharBool r} =
      {r : A × A → Bool | ∀ f s : A, vleOfBool r f s ∨ vleOfBool r s f} ∩
      {r : A × A → Bool |
        ∀ x y z : A, vleOfBool r x y → vleOfBool r y z → vleOfBool r x z} ∩
      {r : A × A → Bool |
        ∀ x y z : A, vleOfBool r x z → vleOfBool r y z → vleOfBool r (x + y) z} ∩
      {r : A × A → Bool |
        ∀ x y : A, vleOfBool r x y → ∀ z : A, vleOfBool r (x * z) (y * z)} ∩
      {r : A × A → Bool |
        ∀ x y z : A, ¬ vleOfBool r z 0 → vleOfBool r (x * z) (y * z) → vleOfBool r x y} ∩
      {r : A × A → Bool | ¬ vleOfBool r 1 0} ∩
      {r : A × A → Bool |
        ∀ f s : A, (r (f, s) = true) ↔ vleOfBool r f s ∧ ¬ vleOfBool r s 0} := by
    ext r
    simp only [Set.mem_ofPred_eq, Set.mem_inter_iff]
    rw [isValuationCharBool_iff]
    tauto
  rw [hEq]
  exact ((((((isClosed_vle_total_bool.inter isClosed_vle_trans_bool).inter
    isClosed_vle_add_bool).inter isClosed_mul_vle_mul_left_bool).inter
    isClosed_vle_mul_cancel_bool).inter isClosed_not_vle_one_zero_bool).inter
    isClosed_apply_iff_bool)

/-! #### Range of `ιSpvBool` equals the set of Bool valuation characteristics -/

/-- **Main range identity (Bool version).** The image of `ιSpvBool` is exactly the
set of Bool valuation characteristics. -/
theorem range_ιSpv_bool :
    Set.range (ιSpvBool : Spv A → (A × A → Bool)) = {r | IsValuationCharBool r} := by
  ext r
  constructor
  · rintro ⟨v, rfl⟩
    -- ιSpvBool v is a Bool valuation characteristic: transport IsValuationChar via the
    -- factorisation ιSpv v = fun p => ιSpvBool v p = true.
    change IsValuationCharBool (ιSpvBool v)
    change IsValuationChar (fun p ↦ ιSpvBool v p = true)
    -- Convert ιSpv v to `fun p => ιSpvBool v p = true` pointwise.
    have hconv : (fun p ↦ ιSpvBool v p = true) = ιSpv v := by
      funext p
      have := ιSpv_eq_boolToProp_comp_ιSpv_bool v
      rw [this]; rfl
    rw [hconv]
    exact ιSpv_mem_isValuationChar v
  · intro hr
    -- From IsValuationChar (fun p => r p = true), construct v = hr'.toSpv where
    -- hr' : IsValuationChar (fun p => r p = true). Then ιSpvBool v = r.
    have hr' : IsValuationChar (fun p ↦ r p = true) := hr
    refine ⟨hr'.toSpv, ?_⟩
    -- Show ιSpvBool hr'.toSpv = r.
    have key : ιSpv hr'.toSpv = fun p ↦ r p = true := ιSpv_toSpv hr'
    funext p
    show ιSpvBool hr'.toSpv p = r p
    simp only [ιSpvBool]
    have hιSpv_p : ιSpv hr'.toSpv p = (hr'.toSpv.vle p.1 p.2 ∧ ¬ hr'.toSpv.vle p.2 0) := rfl
    by_cases hb : r p = true
    · rw [hb]
      simp only [decide_eq_true_iff]
      rw [← hιSpv_p, key]; exact hb
    · have hbf : r p = false := (Bool.not_eq_true _).mp hb
      rw [hbf]
      simp only [decide_eq_false_iff_not]
      rw [← hιSpv_p, key]; exact hb

/-- **Closedness of the range of `ιSpvBool`.** -/
theorem isClosed_range_ιSpv_bool :
    IsClosed (Set.range (ιSpvBool : Spv A → (A × A → Bool))) := by
  rw [range_ιSpv_bool]
  exact isClosed_isValuationCharBool

/-! ### Conclusion: `CompactSpace (Spv A)` -/

/-- `Set.range ιSpvBool` is compact (closed subset of the compact space
`A × A → Bool`). -/
lemma isCompact_range_ιSpv_bool :
    IsCompact (Set.range (ιSpvBool : Spv A → (A × A → Bool))) :=
  isClosed_range_ιSpv_bool.isCompact

/-- `Set.range ιSpv` equals the image of `range ιSpvBool` under the pointwise
`boolToProp` map. -/
lemma range_ιSpv_eq_image_boolToProp :
    Set.range (ιSpv : Spv A → (A × A → Prop)) =
      (fun r : A × A → Bool ↦ fun p ↦ boolToProp (r p)) ''
        Set.range (ιSpvBool : Spv A → (A × A → Bool)) := by
  ext s
  constructor
  · rintro ⟨v, rfl⟩
    refine ⟨ιSpvBool v, ⟨v, rfl⟩, ?_⟩
    change (fun p ↦ boolToProp (ιSpvBool v p)) = _
    exact (ιSpv_eq_boolToProp_comp_ιSpv_bool v).symm
  · rintro ⟨r, ⟨v, rfl⟩, rfl⟩
    refine ⟨v, ?_⟩
    change _ = (fun p ↦ boolToProp (ιSpvBool v p))
    exact ιSpv_eq_boolToProp_comp_ιSpv_bool v

/-- `Set.range ιSpv` is compact in the Sierpinski product topology: it is the
continuous image of the closed range `range ιSpvBool` in the discrete Bool
product. -/
lemma isCompact_range_ιSpv :
    IsCompact (Set.range (ιSpv : Spv A → (A × A → Prop))) := by
  rw [range_ιSpv_eq_image_boolToProp]
  exact isCompact_range_ιSpv_bool.image continuous_boolToProp_pi

/-- **Capstone theorem: compactness of the valuation spectrum (Wedhorn Thm 4.9;
Huber 1993, Lemma 2.1 / Thm 3.1).** The valuation spectrum `Spv A` of a
commutative ring `A` is compact.

Proof: the Bool-valued Huber embedding `ιSpvBool : Spv A → (A × A → Bool)` has
closed image (each of the seven `IsValuationChar` axioms is a closed cylinder
condition; their intersection is closed). `(A × A → Bool)` is compact (Tychonoff +
`Finite Bool`), so `range ιSpvBool` is compact. The pointwise conversion map
`boolToProp : Bool → Prop` is continuous, giving `IsCompact (range ιSpv)`. By
`ιSpv_isEmbedding.isCompact_iff Set.univ`, this transfers back to compactness of
`Spv A`. -/
instance instCompactSpace : CompactSpace (Spv A) := by
  rw [← isCompact_univ_iff]
  -- We need: IsCompact (univ : Set (Spv A)). Use ιSpv_isEmbedding.isCompact_iff.
  rw [ιSpv_isEmbedding.isCompact_iff, Set.image_univ]
  exact isCompact_range_ιSpv

end ValuationSpectrum
