/-
Copyright (c) 2026 Christopher Birkbeck, Alex Torzewski. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christopher Birkbeck, Alex Torzewski
-/

/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import LeanPool.UniformSheafyTateDomains.AdicSpaces.WedhornLocalizedCor732Application
import LeanPool.UniformSheafyTateDomains.AdicSpaces.WedhornLocalizationContinuity
import LeanPool.UniformSheafyTateDomains.AdicSpaces.WedhornLocalCompatFromTestFamily

/-!
# Localized Tate-data derivation for `exists_dominating_unit_in_localization`

The previous file `WedhornLocalizedCor732Application.lean` (commit `863aa86`)
exposes the localized Cor 7.32 application with all localized
Wedhorn-Tate hypotheses as **explicit inputs**. This file derives the
strongest pieces of these from the global `PairOfDefinition A` plus
localization data `(T, s, hopen)`, removing them as explicit
hypotheses.

## What this file provides

1. **`locIdeal_eq_span_singleton_of_principal`** — principal-generator
   bridge: from `P.I = Ideal.span {π}` to `(locPairOfDefinition).I =
   Ideal.span {algebraMapD π}`. Direct via `Ideal.map_span` (or
   variants).

2. **`isTopologicallyNilpotent_algebraMapD_of_isTopologicallyNilpotent`**
   — TN transfer: from `IsTopologicallyNilpotent (P.A₀.subtype π)`
   in `A` to TN of `(locSubring).subtype (algebraMapD π)` in
   `Localization.Away s` under `locTopology`. Uses
   `IsTopologicallyNilpotent.map` (Mathlib) with continuity of
   `algebraMap A → Localization.Away s` from
   `locTopology_algebraMap_continuous` (committed `fd1a66c`).

3. **`isUnit_algebraMapD_of_isUnit`** — Unit transfer: from
   `IsUnit (P.A₀.subtype π)` in `A` to unit of `(locSubring).subtype
   (algebraMapD π)` in `Localization.Away s`. Direct via
   `RingHom.isUnit_map`.

## Single residual

The remaining explicit hypotheses for `exists_dominating_unit_in_localization`:

* `IsLinearTopology (Localization.Away s) (Localization.Away s)` for
  `locTopology P T s hopen` — structural, requires showing the
  `locNhd`-basis can be promoted to an ideal-basis (or that the
  generated ideals form a basis). The locNhd's are AddSubgroups, not
  in general ideals of `Localization.Away s`. The cleanest route is
  probably via `IsLinearTopology.mk_of_hasBasis'` with an explicit
  SMul-closure verification on `Submodule.span (Localization.Away s)
  (locNhd P T s n)`. This is the next concrete sub-target.

* `hArch_loc` (MulArchimedean for points in localized Spa) and
  `hT_loc` (no common zero on the localized Spa) — these depend on
  the global Wedhorn-Tate setup transferring through the localization;
  out of scope for this file.

## Notes

* No root import; leaf-level file.
* No edits to committed bridge files.
* No Lane B / Cor 8.32 / Jacobson / T001 / faithful-flatness /
  final-acyclicity content. -/

namespace ValuationSpectrum

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- **Principal generator transfer**: from `P.I = Ideal.span {π}` for
`π : P.A₀`, the local ideal of definition `(locPairOfDefinition P T s hopen).I`
is principally generated by `algebraMapD P T s π : locSubring P T s`. -/
theorem locIdeal_eq_span_singleton_of_principal
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s)
    (π : P.A₀) (hI : P.I = Ideal.span {π}) :
    letI : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
    (locPairOfDefinition P T s hopen).I = Ideal.span {algebraMapD P T s π} := by
  letI : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
  show locIdeal P T s = Ideal.span {algebraMapD P T s π}
  rw [locIdeal, hI, Ideal.map_span]
  congr 1
  ext x
  simp only [Set.mem_singleton_iff, Set.image_singleton]

/-- **Topologically-nilpotent transfer**: from `IsTopologicallyNilpotent
(P.A₀.subtype π)` in `A` to TN of the local generator
`(locSubring P T s).subtype (algebraMapD P T s π)` in `Localization.Away s`
under `locTopology P T s hopen`.

Uses `IsTopologicallyNilpotent.map` (Mathlib) with continuity of
`algebraMap A → Localization.Away s` (`locTopology_algebraMap_continuous`,
committed `fd1a66c`). -/
theorem isTopologicallyNilpotent_algebraMapD_of_isTopologicallyNilpotent
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s)
    (π : P.A₀) (hπ_tn : IsTopologicallyNilpotent (P.A₀.subtype π)) :
    letI : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
    IsTopologicallyNilpotent
      ((locPairOfDefinition P T s hopen).A₀.subtype (algebraMapD P T s π)) := by
  letI : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
  -- (locSubring P T s).subtype (algebraMapD P T s π) = algebraMap A _ (P.A₀.subtype π) by
  -- definition of algebraMapD as `(algebraMap.comp subtype).codRestrict`.
  show IsTopologicallyNilpotent
    (((locSubring P T s).subtype (algebraMapD P T s π)) : Localization.Away s)
  have heq : ((locSubring P T s).subtype (algebraMapD P T s π) :
      Localization.Away s) = algebraMap A (Localization.Away s) (P.A₀.subtype π) := rfl
  rw [heq]
  exact hπ_tn.map (locTopology_algebraMap_continuous P T s hopen)

/-- **Unit transfer**: from `IsUnit (P.A₀.subtype π)` in `A` to
`IsUnit ((locSubring P T s).subtype (algebraMapD P T s π))` in
`Localization.Away s`.

Direct via `RingHom.isUnit_map` for the ring hom `algebraMap A
(Localization.Away s)`. -/
theorem isUnit_algebraMapD_of_isUnit
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s)
    (π : P.A₀) (hπ_unit : IsUnit (P.A₀.subtype π)) :
    letI : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
    IsUnit ((locPairOfDefinition P T s hopen).A₀.subtype (algebraMapD P T s π)) := by
  letI : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
  show IsUnit (((locSubring P T s).subtype (algebraMapD P T s π)) :
    Localization.Away s)
  have heq : ((locSubring P T s).subtype (algebraMapD P T s π) :
      Localization.Away s) = algebraMap A (Localization.Away s) (P.A₀.subtype π) := rfl
  rw [heq]
  exact hπ_unit.map (algebraMap A (Localization.Away s))

/-! ### T213: localized test-family nonvanishing supplier

T206's item-8 input (no-common-zero on `Spa(Loc s, ⁺)` for the test
family `T_test_loc`) is the last per-cover residual after T208/T211.
T213 below produces the supplier in the **generic** form parameterised
directly by `(P, T, s, hopen)` and the per-cover-piece data
`(T_D, s_D)`, rather than the existing `RationalCoveringData`-specialised
`wedhorn_834_localizedTestFamily_nonvanishing_supplier`
(`Adic spaces/WedhornC1StrongSupplierBridge.lean:553`).

The proof is a clean reduction: at every `w` in the localised Spa,
return `τ := algebraMap A (Loc s) s_D` — which lies in
`localizedTestFamily s T_D s_D` by `Finset.mem_insert_self` (since
`localizedTestFamily = insert (algebraMap s_D) (T_D.image algebraMap)`)
— and use the supplied per-`w` non-vanishing of `algebraMap s_D`. -/

/-- **T213 generic localized test-family nonvanishing supplier**.

From the per-`w` non-vanishing of `algebraMap A (Loc s) s_D` on
`Spa(Localization.Away s, ⁺)` (under the `locTopology` /
`localizationLocSubringPlusSubring` choices), produce the
`localizedTestFamily s T_D s_D` no-common-zero condition required as
input to `Cor732.exists_dominating_unit` applied to the localised
ring.

**Inputs**:
* `(P, T, s, hopen)` — the standard `locTopology` / `locSubring` data.
* `(T_D, s_D)` — target cover-piece data (`s_D` is the cover-piece
  denominator; `T_D` is the cover-piece test family).
* `h_sD_ne` — per-`w` non-vanishing of `algebraMap A (Loc s) s_D` on
  `Spa(Loc s, ⁺)` (cover-piece denominator structural condition).

**Output**: per-`w`, `∃ τ ∈ localizedTestFamily s T_D s_D, ¬ w.vle τ 0`.

**Proof**: at each `w`, return `τ := algebraMap s_D` (in
`localizedTestFamily` by `Finset.mem_insert_self`); the supplied
`h_sD_ne` discharges the non-vanishing.

**Use**: this is the generic counterpart of
`wedhorn_834_localizedTestFamily_nonvanishing_supplier`
(`WedhornC1StrongSupplierBridge.lean:553`) — the same reduction,
parameterised by `(T_D, s_D)` directly rather than by
`(C : RationalCoveringData A, D : RationalLocData A)`. Suitable as the
`hT_loc` input at T206-style callsites that lack a
`RationalCoveringData` packaging. -/
theorem localizedTestFamily_nonvanishing_of_denominator_nonvanishing
    [PlusSubring A]
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s)
    (T_D : Finset A) (s_D : A)
    (h_sD_ne :
      letI : TopologicalSpace (Localization.Away s) :=
        locTopology P T s hopen
      letI : PlusSubring (Localization.Away s) :=
        localizationLocSubringPlusSubring P T s
      ∀ w ∈ Spa (Localization.Away s) (Localization.Away s)⁺,
        ¬ w.vle (algebraMap A (Localization.Away s) s_D) 0) :
    letI : TopologicalSpace (Localization.Away s) :=
      locTopology P T s hopen
    letI : PlusSubring (Localization.Away s) :=
      localizationLocSubringPlusSubring P T s
    ∀ w ∈ Spa (Localization.Away s) (Localization.Away s)⁺,
      ∃ τ ∈ localizedTestFamily s T_D s_D, ¬ w.vle τ 0 := by
  letI : TopologicalSpace (Localization.Away s) :=
    locTopology P T s hopen
  letI : PlusSubring (Localization.Away s) :=
    localizationLocSubringPlusSubring P T s
  letI : DecidableEq (Localization.Away s) := Classical.decEq _
  intro w hw
  refine ⟨algebraMap A (Localization.Away s) s_D, ?_, h_sD_ne w hw⟩
  unfold localizedTestFamily
  exact Finset.mem_insert_self _ _

end ValuationSpectrum
