/-
Copyright (c) 2026 Christopher Birkbeck, Alex Torzewski. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christopher Birkbeck, Alex Torzewski
-/
module


/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
public import LeanPool.UniformSheafyTateDomains.AdicSpaces.Wedhorn745PointwiseBaseRefinementDischarge
public import LeanPool.UniformSheafyTateDomains.AdicSpaces.WedhornDominatingUnitInequality

/-!
# Wedhorn 8.34(ii) — Multi-element σ-domination clearing primitives (T050)

T049 (commit `a14fc1a`) accepted the pointwise base-refinement bridge
and identified the remaining Wedhorn 8.34(ii) content as the
**multi-element σ-domination clearing lemma** documented in
`WedhornStandardCoverRefinement.lean:421-516`. This file lands the
**σ-power valuation arithmetic primitives** plus a substantive
reduction of the base rationalOpen subset clause to an explicit
per-`w` product-bound + lower-bound supplier, consuming the
**already-landed corrected multi-clearing**
`vle_of_dominating_unit_multi_corrected_at`
(`WedhornDominatingUnitInequality.lean:280`).

## Documented universality blocker

Per T035's analysis (`WedhornMaxElementSDComparison.lean`), the
**universal-over-Spa multi-element clearing** as stated in the
original `WedhornStandardCoverRefinement.lean:421-516` target
signature is **mathematically false** in general: T035's
counter-example (`A = ℚ_p, T_D = {1}, D_s = p, σ = p^N`) satisfies
all source restrictions yet violates the per-`t'` upper bound.
`WedhornDominatingUnitInequality.lean:240-262` documents this
blocker and lands the **corrected weakest-sufficient-pair form**:
the per-`w` clearing follows from the multi-element rational-subset
bound `w.vle (T_D.prod id) D_s` plus the per-element lower bound
`∀ t' ∈ T_D, w.vle 1 t'` — without σ-strict-domination.

This file lifts the corrected per-`w` clearing to the **base
rationalOpen subset clause** consumed by T049's pointwise C1
obligation, exposing the per-`w` product/lower-bound supplier as the
single named residual.

## What this file provides

* `vle_mul_pow_cancel_left` — σ-power cancellation primitive: from
  `w.vle (a ^ N * x) (a ^ N * y)` and `¬ w.vle a 0`, derive
  `w.vle x y`. Iterated `Spv.vle_mul_cancel`. Reusable mathlib-style.

* `not_vle_zero_pow_of_not_vle_zero` — non-vanishing power
  primitive: from `¬ w.vle a 0`, derive `¬ w.vle (a ^ N) 0`. Iterated
  cancellation. Reusable mathlib-style.

* `rationalOpen_subset_via_corrected_multi_clearing` — **the
  substantive reduction**: from a per-`w` product-bound + lower-bound
  supplier at each `w ∈ Spa(A, A⁺)` satisfying `w.vle f s` (the
  f-membership clause of `R(insert f T_base, s)`), derive the base
  rationalOpen inclusion `R(insert f T_base, s) ⊆ R(T_D, D_s)`.
  Proof: at any `v` in the LHS, extract `v.vle f s`, apply the
  per-`w` supplier to get `v.vle (T_D.prod id) D_s` and
  `∀ t' ∈ T_D, v.vle 1 t'`, then apply
  `vle_of_dominating_unit_multi_corrected_at` for the per-`t'` bound
  + non-vanishing, finally assembling rationalOpen membership.

* `exists_single_f_refinement_via_corrected_multi_clearing` —
  per-call existential wrapper: from `f`, the per-`w` supplier, and
  `v ∈ R(insert f C.base.T, C.base.s)`, produce the
  `exists_single_f_refinement_at_t_via_dominating_unit`-shape
  conclusion.

* `C1SupplierStrong_local_via_corrected_multi_clearing` — top-level
  C1 supplier wrapper. Takes per-call delivery of the per-`w` product-
  bound + lower-bound supplier plus rationalOpen membership and
  non-degeneracy of `f`, produces `C1SupplierStrong_local C` via T049.
  The named residual is the per-`w` product/lower-bound supplier —
  the natural Wedhorn 8.34(ii) Laurent-cover-refinement output.

## Why the per-`w` product/lower-bound supplier is closer to Wedhorn
8.34(ii) than T049

T049's residual is the per-call Wedhorn 7.45 cover-refinement
inclusion. T050's residual is the **per-`w` product/lower-bound
data** that LITERALLY produces the cover-refinement via
`vle_of_dominating_unit_multi_corrected_at`. This is exactly the
Wedhorn 8.34(ii) Laurent-cover-refinement output (PDF page 84): the
Laurent cover generated by `σ⁻¹ * f_i` partitions Spa, and on each
piece the multi-element rational-subset bound holds by construction.

## Notes

* No root import; leaf-level.
* Imports `Wedhorn745PointwiseBaseRefinementDischarge` (T049) and
  `WedhornDominatingUnitInequality` (the corrected multi-clearing).
* No edits to T031–T049 accepted leaves, root imports, or final
  theorem signatures.
* No revival of M-power-decay / σ-power-decay, T001/Lane-B,
  Cor 8.32/Jacobson, faithful-flatness, Zavyalov, or
  bivariate-overlap content.
* No global universal-over-Spa multi-clearing claim (per T035's
  counter-example).
-/

@[expose] public section

namespace ValuationSpectrum

variable {A : Type*} [CommRing A] [TopologicalSpace A] [PlusSubring A]
  [IsTopologicalRing A]

omit [TopologicalSpace A] [IsTopologicalRing A] [PlusSubring A] in
/-- **σ-power cancellation primitive** (T050 valuation arithmetic
primitive 1).

From `w.vle (a ^ N * x) (a ^ N * y)` and `¬ w.vle a 0`, derive
`w.vle x y`. Iterated `Spv.vle_mul_cancel`.

Reusable mathlib-style API supporting any σ-power cancellation step
in the Wedhorn 8.34(ii) σ-domination construction. -/
theorem vle_mul_pow_cancel_left
    {w : Spv A} {a : A} (ha : ¬ w.vle a 0) (N : ℕ) (x y : A)
    (h : w.vle (a ^ N * x) (a ^ N * y)) :
    w.vle x y := by
  induction N with
  | zero => simpa using h
  | succ N ih =>
    apply ih
    rw [pow_succ, mul_right_comm (a ^ N) a x, mul_right_comm (a ^ N) a y] at h
    exact w.vle_mul_cancel ha h

omit [TopologicalSpace A] [IsTopologicalRing A] [PlusSubring A] in
/-- **σ-power non-vanishing primitive** (T050 valuation arithmetic
primitive 2).

From `¬ w.vle a 0`, derive `¬ w.vle (a ^ N) 0`. Iterated
right-multiplication cancellation.

Reusable mathlib-style API supporting any positive-power
non-vanishing step in the Wedhorn 8.34(ii) σ-domination
construction. -/
theorem not_vle_zero_pow_of_not_vle_zero
    {w : Spv A} {a : A} (ha : ¬ w.vle a 0) (N : ℕ) :
    ¬ w.vle (a ^ N) 0 := by
  induction N with
  | zero => simp [w.not_vle_one_zero]
  | succ N ih =>
    intro h
    apply ih
    rw [pow_succ] at h
    exact w.vle_mul_cancel ha (by rwa [zero_mul])

omit [IsTopologicalRing A] in
/-- **Base rationalOpen inclusion via corrected multi-clearing**
(T050 main substantive theorem).

From a per-`w` product-bound + lower-bound supplier — at each
`w ∈ Spa(A, A⁺)` with `w.vle f s` (the `f`-membership clause of
`R(insert f T_base, s)`), supply
`w.vle (T_D.prod id) D_s` AND `∀ t' ∈ T_D, w.vle (1 : A) t'` —
derive the base rationalOpen subset
`R(insert f T_base, s) ⊆ R(T_D, D_s)` on `Spa(A, A⁺)`.

**Proof**: take `v` in the LHS. Extract `v.vle f s` from the
`f`-membership clause (since `f ∈ insert f T_base`). Apply the per-`w`
supplier at `v` to obtain `v.vle (T_D.prod id) D_s` and the
per-element lower bound. Apply `vle_of_dominating_unit_multi_corrected_at`
(`WedhornDominatingUnitInequality.lean:280`) to derive
`∀ t' ∈ T_D, v.vle t' D_s` and `¬ v.vle D_s 0`. Combined with the
Spa-membership of `v`, this yields `v ∈ R(T_D, D_s)`.

The per-`w` supplier is **the single named non-tautological
residual** — it captures exactly the Wedhorn 8.34(ii) Laurent-cover-
refinement output (PDF page 84) at the per-`w` level, with no
universal-over-Spa false claim. -/
theorem rationalOpen_subset_via_corrected_multi_clearing
    [DecidableEq A]
    (T_base T_D : Finset A) (s D_s f : A)
    (h_per_w :
      ∀ w ∈ Spa A A⁺,
        w.vle f s →
        w.vle (T_D.prod id) D_s ∧ (∀ t' ∈ T_D, w.vle (1 : A) t')) :
    rationalOpen (insert f T_base) s ⊆ rationalOpen T_D D_s := by
  intro v hv
  obtain ⟨hv_spa, hv_per_c, _hv_s_ne⟩ := hv
  obtain ⟨h_prod, h_lower⟩ :=
    h_per_w v hv_spa (hv_per_c f (Finset.mem_insert_self f T_base))
  obtain ⟨h_per_t, h_D_s_ne⟩ :=
    vle_of_dominating_unit_multi_corrected_at v h_prod h_lower
  exact ⟨hv_spa, h_per_t, h_D_s_ne⟩

/-- **Per-call existential C1 supply via corrected multi-clearing**
(T050 composed deliverable).

From `f`, the per-`w` product-bound + lower-bound supplier (specialised
to the C1 supplier's `(C.base.T, C.base.s, D.T, D.s)` tuple), and
`v`-side rationalOpen membership + `f`-non-degeneracy, produce the
strong-C1 existential conclusion `∃ f', v ∈ R(insert f' C.base.T,
C.base.s) ∧ R(insert f' C.base.T, C.base.s) ⊆ R(D.T, D.s) ∧
¬ v.vle f' 0`. -/
theorem exists_single_f_refinement_via_corrected_multi_clearing
    [DecidableEq A]
    (C : RationalCoveringData A) (D : RationalLocData A) (f : A)
    (h_per_w :
      ∀ w ∈ Spa A A⁺,
        w.vle f C.base.s →
        w.vle (D.T.prod id) D.s ∧ (∀ t' ∈ D.T, w.vle (1 : A) t'))
    {v : Spv A}
    (hv_in : v ∈ rationalOpen (insert f C.base.T) C.base.s)
    (hvf_ne : ¬ v.vle f 0) :
    ∃ f' : A,
      rationalOpen (insert f' C.base.T) C.base.s ⊆ rationalOpen D.T D.s ∧
      v ∈ rationalOpen (insert f' C.base.T) C.base.s ∧
      ¬ v.vle f' 0 :=
  ⟨f,
    rationalOpen_subset_via_corrected_multi_clearing C.base.T D.T C.base.s
      D.s f h_per_w,
    hv_in, hvf_ne⟩

/-- **Top-level: `C1SupplierStrong_local C` via corrected multi-
clearing** (T050 final deliverable).

Caller theorem producing `C1SupplierStrong_local C` from per-call
delivery of:

* `f : A` — the inserted refinement element.
* The per-`w` product-bound + lower-bound supplier `h_per_w` (the
  named residual: the Wedhorn 8.34(ii) Laurent-cover-refinement
  output at each `w` with `w.vle f C.base.s`).
* `v`-side rationalOpen membership and `f`-non-degeneracy.

Composes
`exists_single_f_refinement_via_corrected_multi_clearing` with T049's
`C1SupplierStrong_local_via_Wedhorn745_pointwise_refinement`.

**The single named non-tautological residual** is the per-`w`
product/lower-bound supplier — the precise per-`w` shape
`(T_D.prod id ≤ D_s) ∧ (∀ t' ∈ T_D, 1 ≤ t')` that Wedhorn 8.34(ii)'s
Laurent cover refinement is supposed to produce on each Laurent piece.
This is closer to the actual Wedhorn 8.34(ii) construction than
T049's pointwise C1 obligation: the residual specialises to the
Laurent-cover-refinement output, with no universal-over-Spa or
per-call existential indirection. -/
theorem C1SupplierStrong_local_via_corrected_multi_clearing
    [DecidableEq A]
    (P : PairOfDefinition A) (hA₀_le : P.A₀ ≤ A⁺)
    (hAplus_le_A₀ : (A⁺ : Set A) ⊆ P.A₀)
    (C : RationalCoveringData A)
    (hopen_base : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) C.base.s ∈ locSubring P C.base.T C.base.s)
    (h_per_call_components :
      ∀ D ∈ C.covers, ∀ v ∈ rationalOpen D.T D.s,
        ∀ t ∈ D.T, v.vle t D.s → ¬ v.vle D.s 0 →
        ∃ f : A,
          (∀ w ∈ Spa A A⁺,
            w.vle f C.base.s →
            w.vle (D.T.prod id) D.s ∧
            (∀ t' ∈ D.T, w.vle (1 : A) t')) ∧
          v ∈ rationalOpen (insert f C.base.T) C.base.s ∧
          ¬ v.vle f 0) :
    C1SupplierStrong_local C := by
  refine C1SupplierStrong_local_via_Wedhorn745_pointwise_refinement
    P hA₀_le hAplus_le_A₀ C hopen_base ?_
  intro D hD v hv t ht hvt hvD_s
  obtain ⟨f, h_per_w, hv_in_plus, hvf_ne⟩ :=
    h_per_call_components D hD v hv t ht hvt hvD_s
  exact exists_single_f_refinement_via_corrected_multi_clearing C D f
    h_per_w hv_in_plus hvf_ne

end ValuationSpectrum
