/-
Copyright (c) 2026 Christopher Birkbeck, Alex Torzewski. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christopher Birkbeck, Alex Torzewski
-/

/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import LeanPool.UniformSheafyTateDomains.AdicSpaces.LocalizationTopology

/-!
# Continuity of `algebraMap A → Localization.Away s` under `locTopology`

The final upstream API gap identified in `WedhornLocalizationPlus.lean` —
the continuity of `algebraMap A (Localization.Away s)` under
`locTopology P T s hopen` — is the last prerequisite for instantiating
the `comap_mem_rationalOpen_iff` rational-open transfer law of
`WedhornPrelocalizationTransfer.lean` for the `algebraMap A →
Localization.Away C.base.s` map of the Wedhorn 8.34(ii) Route B
pre-localisation step.

## Proof strategy

The `locTopology` is generated by the `RingSubgroupsBasis` of
neighborhoods `locNhd P T s n` (image of `(locIdeal)^n` in
`Localization.Away s`). For continuity of `algebraMap` at `0`:

1. Use `continuous_of_tendsto_nhds_zero` (Mathlib): for an additive
   monoid hom, `Tendsto f (𝓝 0) (𝓝 0)` suffices.
2. Use `Filter.HasBasis.tendsto_iff` with bases:
   * Source: `P.hasBasis_nhds_zero` — basis `Subtype.val '' (P.I^n)` in `A`
     (`Adic spaces/HuberRings.lean`).
   * Target: `(locBasis P T s hopen).hasBasis_nhds_zero` — basis
     `(locNhd P T s n : Set _)` in `Localization.Away s`
     (`Mathlib.Topology.Algebra.Nonarchimedean.Bases`).
3. For each `n` in the target basis, take `m := n` in the source basis.
4. For `a ∈ Subtype.val '' (P.I^n)`, decompose `a = (b : A)` with
   `b ∈ P.I^n`. Then `algebraMap a = (algebraMapD b :
   Localization.Away s)` (algebraMapD is `algebraMap.codRestrict` to
   `locSubring`).
5. Show `algebraMapD b ∈ (locIdeal)^n` via `locIdeal = Ideal.map
   algebraMapD P.I` and `Ideal.map_pow` plus `Ideal.mem_map_of_mem`.
6. Conclude `(algebraMapD b : Localization.Away s) ∈ locNhd P T s n`
   by the `locNhd` definition (`locNhd_preimage_eq_locIdeal_pow`
   inverse direction).

## What this file provides

`locTopology_algebraMap_continuous` — the named continuity lemma
`Continuous (algebraMap A (Localization.Away s))` under
`locTopology P T s hopen`. Closes the last upstream API gap for the
Wedhorn 8.34(ii) Route B pre-localisation rational-open transfer.

No Lane B / Cor 8.32 / Jacobson / faithful-flatness / T001 content. -/

namespace ValuationSpectrum

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- **Continuity of `algebraMap A (Localization.Away s)` under
`locTopology P T s hopen`** (Wedhorn 8.34(ii) Route B prerequisite).

Closes the last upstream gap for the rational-open comap pullback law
through the localisation map. With this lemma in hand, the chain
`localizationAwayPlusSubring` (`WedhornLocalizationPlus.lean`) +
`localizationAwayPlusSubring_aplus_le_comap` + this continuity lemma
+ `comap_mem_rationalOpen_iff` (`WedhornPrelocalizationTransfer.lean`)
discharges the rational-open transfer for the pre-localisation step.

**Proof**: continuity at `0` via `continuous_of_tendsto_nhds_zero`
(algebraMap is an additive monoid hom). The `Tendsto`-at-`0` reduces
to a basis-vs-basis check: for each `n` in the target's `locNhd`-basis,
take `n` in the source's `P.I^n`-basis and verify
`algebraMap '' (P.I^n) ⊆ locNhd P T s n` via `locIdeal = Ideal.map
algebraMapD P.I`, `Ideal.map_pow`, and `Ideal.mem_map_of_mem`. -/
theorem locTopology_algebraMap_continuous
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s) :
    @Continuous A (Localization.Away s) _
      (locTopology P T s hopen)
      (algebraMap A (Localization.Away s)) := by
  let : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
  let : IsTopologicalRing (Localization.Away s) :=
    (locBasis P T s hopen).toRingFilterBasis.isTopologicalRing
  refine continuous_of_tendsto_nhds_zero
    (f := (algebraMap A (Localization.Away s) :
      A →+* Localization.Away s).toAddMonoidHom) ?_
  rw [Filter.HasBasis.tendsto_iff P.hasBasis_nhds_zero
    (locBasis P T s hopen).hasBasis_nhds_zero]
  intro n _
  refine ⟨n, trivial, ?_⟩
  rintro a ⟨b, hb, rfl⟩
  have heq : algebraMap A (Localization.Away s) ((P.A₀.subtype) b) =
      ((algebraMapD P T s b : locSubring P T s) : Localization.Away s) := by
    rfl
  change algebraMap A (Localization.Away s) ((P.A₀.subtype) b) ∈
    (locNhd P T s n : Set (Localization.Away s))
  rw [heq]
  refine ⟨algebraMapD P T s b, ?_, rfl⟩
  rw [locIdeal, ← Ideal.map_pow]
  exact Ideal.mem_map_of_mem _ hb

end ValuationSpectrum
