/-
Copyright (c) 2026 Jukka Suomela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jukka Suomela
-/

import Mathlib.Tactic

import LeanPool.TwoColoringOneRound.LowerBound.N1000000Data

namespace Distributed2Coloring.LowerBound

namespace N1000000MuWitness

open Distributed2Coloring.LowerBound.N1000000Data

/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
abbrev LabelTriple := Nat × Nat × Nat

/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
structure PairMapData where
  /-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
  swap : Bool
  /-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
  srcU : LabelTriple
  /-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
  srcV : LabelTriple
  /-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
  tgtU : LabelTriple
  /-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
  tgtV : LabelTriple
  /-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
  srcSyms : List Nat
  /-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
  tgtSyms : List Nat
  /-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
  idxV : LabelTriple

-- For each `k : Fin muSupport.size`, we store a witness triangle labeling (u,v,w).
/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
abbrev muWitU : Array LabelTriple := #[
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
  (0, 1, 2),
]

/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
abbrev muWitV : Array LabelTriple := #[
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (3, 4, 5),
  (0, 3, 2),
  (1, 2, 3),
  (0, 3, 2),
  (0, 1, 3),
]

/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
abbrev muWitW : Array LabelTriple := #[
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (6, 7, 8),
  (1, 3, 2),
  (0, 2, 3),
  (0, 1, 3),
  (1, 3, 2),
]

-- Constraint kind: 0 = box, 1 = triangle.
/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
abbrev muKind : Array Nat := #[
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
]

-- For box constraints: variable index and coefficient (+1 or -1). Dummy values otherwise.
/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
abbrev muBoxVar : Array Nat := #[
  0,
  1,
  2,
  4,
  6,
  8,
  9,
  10,
  13,
  16,
  17,
  18,
  19,
  20,
  21,
  3,
  5,
  7,
  11,
  12,
  14,
  15,
  22,
  0,
  0,
  0,
  0,
]

/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
abbrev muBoxCoeff : Array Int := #[
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  0,
  0,
  0,
  0,
]

-- For triangle constraints: form ∈ {0,1,2,3} matching (tri0..tri3). Dummy 0 otherwise.
/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
abbrev muTriForm : Array Nat := #[
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  3,
  1,
  1,
]

-- For triangle constraints: (uv,uw,vw) variable indices. Dummy zeros otherwise.
/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
abbrev muTriVars : Array (Nat × Nat × Nat) := #[
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (0, 0, 0),
  (19, 20, 22),
  (11, 10, 22),
  (19, 7, 10),
  (7, 20, 11),
]

-- For triangle constraints: PairMap data for the three pairs (uv,uw,vw). Dummy otherwise.
/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
abbrev muMapUv : Array PairMapData := #[
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,
    1,
    2),
    srcV := (0,
    3,
    2),
    tgtU := (0,
    1,
    2),
    tgtV := (0,
    3,
    2),
    srcSyms := [0,
    1,
    2,
    3],
    tgtSyms := [0,
    1,
    2,
    3],
    idxV := (0,
    3,
    2) },
  { swap := true,
    srcU := (0,
    1,
    2),
    srcV := (3,
    0,
    1),
    tgtU := (1,
    2,
    3),
    tgtV := (0,
    1,
    2),
    srcSyms := [0,
    1,
    2,
    3],
    tgtSyms := [1,
    2,
    3,
    0],
    idxV := (3,
    0,
    1) },
  { swap := false,
    srcU := (0,
    1,
    2),
    srcV := (0,
    3,
    2),
    tgtU := (0,
    1,
    2),
    tgtV := (0,
    3,
    2),
    srcSyms := [0,
    1,
    2,
    3],
    tgtSyms := [0,
    1,
    2,
    3],
    idxV := (0,
    3,
    2) },
  { swap := false,
    srcU := (0,
    1,
    2),
    srcV := (0,
    1,
    3),
    tgtU := (0,
    1,
    2),
    tgtV := (0,
    1,
    3),
    srcSyms := [0,
    1,
    2,
    3],
    tgtSyms := [0,
    1,
    2,
    3],
    idxV := (0,
    1,
    3) },
]

/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
abbrev muMapUw : Array PairMapData := #[
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := true,
    srcU := (0,
    1,
    2),
    srcV := (3,
    0,
    2),
    tgtU := (1,
    3,
    2),
    tgtV := (0,
    1,
    2),
    srcSyms := [0,
    1,
    2,
    3],
    tgtSyms := [1,
    3,
    2,
    0],
    idxV := (3,
    0,
    2) },
  { swap := true,
    srcU := (0,
    1,
    2),
    srcV := (0,
    3,
    1),
    tgtU := (0,
    2,
    3),
    tgtV := (0,
    1,
    2),
    srcSyms := [0,
    1,
    2,
    3],
    tgtSyms := [0,
    2,
    3,
    1],
    idxV := (0,
    3,
    1) },
  { swap := false,
    srcU := (0,
    1,
    2),
    srcV := (0,
    1,
    3),
    tgtU := (0,
    1,
    2),
    tgtV := (0,
    1,
    3),
    srcSyms := [0,
    1,
    2,
    3],
    tgtSyms := [0,
    1,
    2,
    3],
    idxV := (0,
    1,
    3) },
  { swap := true,
    srcU := (0,
    1,
    2),
    srcV := (3,
    0,
    2),
    tgtU := (1,
    3,
    2),
    tgtV := (0,
    1,
    2),
    srcSyms := [0,
    1,
    2,
    3],
    tgtSyms := [1,
    3,
    2,
    0],
    idxV := (3,
    0,
    2) },
]

/-- Imported auxiliary declaration for the 2-coloring one-round formalization. -/
abbrev muMapVw : Array PairMapData := #[
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,0,0),
    srcV := (0,0,0),
    tgtU := (0,0,0),
    tgtV := (0,0,0),
    srcSyms := [],
    tgtSyms := [],
    idxV := (0,0,0) },
  { swap := false,
    srcU := (0,
    1,
    2),
    srcV := (3,
    1,
    2),
    tgtU := (0,
    3,
    2),
    tgtV := (1,
    3,
    2),
    srcSyms := [0,
    1,
    2,
    3],
    tgtSyms := [0,
    3,
    2,
    1],
    idxV := (3,
    1,
    2) },
  { swap := false,
    srcU := (0,
    1,
    2),
    srcV := (3,
    1,
    2),
    tgtU := (1,
    2,
    3),
    tgtV := (0,
    2,
    3),
    srcSyms := [0,
    1,
    2,
    3],
    tgtSyms := [1,
    2,
    3,
    0],
    idxV := (3,
    1,
    2) },
  { swap := false,
    srcU := (0,
    1,
    2),
    srcV := (0,
    3,
    1),
    tgtU := (0,
    3,
    2),
    tgtV := (0,
    1,
    3),
    srcSyms := [0,
    1,
    2,
    3],
    tgtSyms := [0,
    3,
    2,
    1],
    idxV := (0,
    3,
    1) },
  { swap := true,
    srcU := (0,
    1,
    2),
    srcV := (3,
    0,
    1),
    tgtU := (1,
    3,
    2),
    tgtV := (0,
    1,
    3),
    srcSyms := [0,
    1,
    2,
    3],
    tgtSyms := [1,
    3,
    2,
    0],
    idxV := (3,
    0,
    1) },
]

end N1000000MuWitness

end Distributed2Coloring.LowerBound
