"""Generate the repository ``NOTICE`` file from the project registry.

``NOTICE`` carries the third-party attribution that Apache-2.0 section 4(d)
and the MIT License require for every pooled project. It used to be
maintained by hand, which silently drifted: by the time this generator was
written, 75 of 141 projects had no entry at all.

Everything the list sections need already lives in ``LeanPool/projects.yml``
(each card declares ``license`` and ``source.github_repo``), so those are
derived rather than typed. The prose that cannot be derived -- upstream MIT
copyright lines, relicensing statements, and reproduced upstream NOTICE text
-- lives in ``NOTICE.extra.yml``, keyed by project directory.

Deliberately kept out of ``projects.yml``: that file is *content* under
``.github/workflows/content-pr-guard.yml``, so a PR may not touch it
alongside infrastructure. Keeping the prose in a separate infra-side file
lets NOTICE regeneration stay a non-content change.

Usage::

    python -m lean_pool.notice --repo ..            # rewrite NOTICE
    python -m lean_pool.notice --repo .. --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

# Column at which an entry's URL starts, matching the hand-written original.
URL_COLUMN = 37
# Indent for a project's prose note.
NOTE_INDENT = " " * 6
RULE = "-" * 80

HEADER = """\
Lean Pool
=========

Copyright the Lean Pool contributors and the respective project authors.

Lean Pool is licensed under the Apache License, Version 2.0. See the LICENSE
file for the full license text.

Lean Pool is an aggregation of third-party Lean 4 formalizations. Each project
under LeanPool/ is the work of its original authors, who retain copyright as
recorded in the per-file headers and in LeanPool/projects.yml. This NOTICE file
records, for every pooled project, the upstream repository it was imported from
and the license under which it was originally published.

This file is generated by python/lean_pool/notice.py from LeanPool/projects.yml
and NOTICE.extra.yml. Do not edit it by hand -- edit those inputs instead."""

APACHE_PREAMBLE = """\
These projects were imported from repositories already licensed under the
Apache License, Version 2.0, and are redistributed here under the same license."""

MIT_PREAMBLE = """\
These projects were imported from repositories licensed under the MIT License.
The MIT License grants the right to sublicense, so these projects are
redistributed here under the Apache License, Version 2.0. As the MIT License
requires, the original copyright notices are preserved below, together with the
MIT permission notice that follows them."""

MIT_PERMISSION_NOTICE = """\
  MIT License -- the following permission notice applies to every project
  listed in this section:

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE."""

ATTRIBUTION_PREAMBLE = """\
The following notices are reproduced from the upstream repositories' own NOTICE
files or LICENSE addenda. Only each project's Apache-2.0 Lean sources were
imported here; these notes preserve attribution and citation requests made by
the original authors."""


def _load_yaml(path: Path) -> Any:
    """Parse a YAML file, returning ``None`` when it does not exist."""
    if not path.is_file():
        return None
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def load_projects(root: Path) -> list[dict[str, Any]]:
    """Read the project cards from ``LeanPool/projects.yml``."""
    data = _load_yaml(root / "LeanPool" / "projects.yml")
    if isinstance(data, dict):
        data = data.get("projects", [])
    return list(data or [])


def load_extra(root: Path) -> dict[str, dict[str, str]]:
    """Read the per-project prose notes from ``NOTICE.extra.yml``."""
    data = _load_yaml(root / "NOTICE.extra.yml") or {}
    return {str(key): dict(value or {}) for key, value in data.items()}


def project_directory(project: dict[str, Any]) -> str:
    """Return a card's directory under ``LeanPool/`` (from its entry module)."""
    parts = str(project.get("entry_module", "")).split(".")
    return parts[1] if len(parts) > 1 else ""


def repository_url(project: dict[str, Any]) -> str:
    """Return the upstream GitHub URL a card was imported from."""
    repo = (project.get("source") or {}).get("github_repo", "")
    return f"https://github.com/{repo}" if repo else ""


def render_entry(directory: str, url: str) -> list[str]:
    """Render one ``LeanPool/<dir>   <url>`` line, wrapping long names.

    A directory name long enough to reach the URL column pushes the URL onto
    its own continuation line, aligned to the same column.
    """
    label = f"  LeanPool/{directory}"
    padding = URL_COLUMN - len(label)
    if padding >= 1:
        return [f"{label}{' ' * padding}{url}"]
    return [label, f"{' ' * URL_COLUMN}{url}"]


def render_note(note: str) -> list[str]:
    """Indent a prose note under its entry, preserving internal blank lines."""
    return [f"{NOTE_INDENT}{line}".rstrip() for line in note.splitlines()]


def _section(title: str, preamble: str, body: list[str]) -> list[str]:
    """Assemble a titled section; returns no lines when the body is empty."""
    if not body:
        return []
    return [RULE, title, RULE, "", preamble, "", *body]


def _entries(
    projects: list[dict[str, Any]],
    extra: dict[str, dict[str, str]],
    *,
    note_key: str | None,
) -> list[str]:
    """Render entry lines (with optional notes) for the given cards."""
    lines: list[str] = []
    for project in projects:
        directory = project_directory(project)
        lines.extend(render_entry(directory, repository_url(project)))
        note = extra.get(directory, {}).get(note_key) if note_key else None
        if note:
            lines.extend(render_note(note))
            lines.append("")
    # A trailing blank line belongs to the section separator, not the entry.
    while lines and lines[-1] == "":
        lines.pop()
    return lines


def render(projects: list[dict[str, Any]], extra: dict[str, dict[str, str]]) -> str:
    """Render the complete NOTICE text."""
    ordered = sorted(projects, key=project_directory)
    relicensed = [
        p for p in ordered if "relicensed" in extra.get(project_directory(p), {})
    ]
    relicensed_dirs = {project_directory(p) for p in relicensed}
    apache = [
        p
        for p in ordered
        if p.get("license") == "Apache-2.0"
        and project_directory(p) not in relicensed_dirs
    ]
    mit = [
        p
        for p in ordered
        if p.get("license") == "MIT" and project_directory(p) not in relicensed_dirs
    ]
    attributed = [
        p for p in ordered if extra.get(project_directory(p), {}).get("attribution")
    ]

    lines: list[str] = [HEADER, "", ""]
    lines += _section(
        "Projects originally licensed under the Apache License, Version 2.0",
        APACHE_PREAMBLE,
        _entries(apache, extra, note_key="note"),
    )
    lines += ["", ""]
    mit_body = _entries(mit, extra, note_key="note")
    if mit_body:
        mit_body += ["", MIT_PERMISSION_NOTICE]
    lines += _section(
        "Projects originally licensed under the MIT License", MIT_PREAMBLE, mit_body
    )
    if relicensed:
        lines += ["", ""]
        lines += _section(
            "Projects relicensed by their original author",
            "These projects were relicensed by their sole author before import.",
            _entries(relicensed, extra, note_key="relicensed"),
        )
    if attributed:
        lines += ["", ""]
        lines += _section(
            "Additional upstream attribution and citation notices",
            ATTRIBUTION_PREAMBLE,
            _entries(attributed, extra, note_key="attribution"),
        )
    return "\n".join(lines).rstrip("\n") + "\n"


def unregistered_notes(
    projects: list[dict[str, Any]], extra: dict[str, dict[str, str]]
) -> list[str]:
    """Return ``NOTICE.extra.yml`` keys that match no project directory.

    A stale key means a note silently stopped being emitted -- usually a
    project renamed or removed without its note following.
    """
    known = {project_directory(p) for p in projects}
    return sorted(key for key in extra if key not in known)


def build(root: Path) -> str:
    """Render NOTICE for the repository at ``root``."""
    projects = load_projects(root)
    extra = load_extra(root)
    stale = unregistered_notes(projects, extra)
    if stale:
        raise SystemExit(
            "NOTICE.extra.yml has notes for unknown projects: " + ", ".join(stale)
        )
    return render(projects, extra)


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--repo", type=Path, default=Path("."), help="repository root (default: .)"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if NOTICE is out of date",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Regenerate or verify NOTICE; return a process exit code."""
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    args = _parse_args(argv)
    root = args.repo.resolve()
    expected = build(root)
    path = root / "NOTICE"
    current = path.read_text(encoding="utf-8") if path.is_file() else ""

    if args.check:
        if current == expected:
            logger.info("NOTICE is up to date.")
            return 0
        logger.error(
            "NOTICE is out of date. Regenerate it with:\n"
            "  cd python && uv run python -m lean_pool.notice --repo .."
        )
        return 1

    if current == expected:
        logger.info("NOTICE is already up to date.")
        return 0
    path.write_text(expected, encoding="utf-8")
    logger.info("Wrote %s", path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
