/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, Claude Fable 5
-/
module

public import LeanPool.DavisKahan.ForTauCeti.Analysis.InnerProductSpace.BorelCalculus.CyclicIsometry
public import LeanPool.DavisKahan.ForTauCeti.Analysis.InnerProductSpace.BorelCalculus.PVM
public import Mathlib.Analysis.Normed.Operator.Extend
public import Mathlib.MeasureTheory.Function.ContinuousMapDense
public import Mathlib.MeasureTheory.Function.L2Space

/-!
# The cyclic multiplication model of the spectral theorem

Layer 2 of the Hahn--Hellinger stack.  Layer 1
(`ForTauCeti/Analysis/InnerProductSpace/BorelCalculus/CyclicIsometry.lean`) proved the single
identity

```text
‖f(a) ξ‖² = ∫ ‖f x‖² d(diagMeasure ha ξ)
```

and introduced the cyclic subspace generated by `ξ`.  This file turns that identity into a
map: `f ↦ f(a) ξ` is a **linear isometry of `L²(diagMeasure ha ξ)` into `H` whose range is
the cyclic subspace**, and the coordinate symbol acts through it as `a` itself.

The construction is the usual density/extension argument, assembled from three pieces.

1. `bddSymbols a` is the `ℂ`-submodule of bounded measurable symbols.  Two linear maps leave
   it: `symbolCalculus ha ξ` into `H`, and `symbolToLp ha ξ` into `L²`.  Layer 1 says these
   have the *same* norm (`norm_symbolCalculus`).
2. `denseRange_symbolToLp` says the second one has dense range.  This is where finiteness and
   regularity of `diagMeasure` are used: on the compact spectrum, continuous symbols are
   already dense in `L²` of a finite regular measure, and a continuous symbol is bounded and
   measurable.
3. `LinearMap.extendOfNorm` then extends `symbolCalculus` along `symbolToLp`, and the isometry
   identity propagates to the extension by density.

## Main results

* `TauCeti.BorelCalculus.denseRange_symbolToLp`: bounded measurable symbols are dense in `L²`
  of the scalar spectral measure.
* `TauCeti.BorelCalculus.norm_symbolCalculus`: the isometry identity, in norm form.
* `TauCeti.BorelCalculus.cyclicIsometry`: the linear isometry `L²(μ_ξ) →ₗᵢ[ℂ] H`.
* `TauCeti.BorelCalculus.range_cyclicIsometry`: its range is `cyclicSubspace ha ξ`.
* `TauCeti.BorelCalculus.coordMulLp`: multiplication by the coordinate, as a bounded operator
  on `L²(μ_ξ)`.
* `TauCeti.BorelCalculus.cyclicIsometry_coordMulLp`: **the intertwining law** — the isometry
  carries multiplication by the coordinate to the action of `a`.

## What is not here

Nothing about *several* cyclic subspaces: the orthogonal decomposition of `H` into countably
many of them (layer 3), the ordering by measure class (layer 4) and the multiplicity function
(layer 5) are all still open.  See the modules named above for the layer
plan and the cost of each.

## Provenance

* Original repository: Davis--Kahan/DKPS formalization (Kitware, Inc.).
* Extraction class: **authored in place** for the Tau Ceti staging layer.
* Spectra influence: **none** — this module imports only Mathlib and `ForTauCeti`.
-/

public section

open scoped InnerProductSpace
open MeasureTheory

namespace TauCeti

/-- The squared `L²` norm of the class of a square-integrable function is the integral of the
squared pointwise norm.

Stated for `ℂ` and `p = 2` only, which is the case the multiplication model needs; the proof
is the inner-product formula for `L²` together with `⟪z, z⟫ = ‖z‖²`. -/
theorem norm_toLp_two_sq {α : Type*} [MeasurableSpace α] {μ : Measure α} {f : α → ℂ}
    (hf : MemLp f 2 μ) : ‖hf.toLp f‖ ^ 2 = ∫ x, ‖f x‖ ^ 2 ∂μ := by
  have hinner : ((‖hf.toLp f‖ ^ 2 : ℝ) : ℂ) = ⟪hf.toLp f, hf.toLp f⟫_ℂ := by
    rw [inner_self_eq_norm_sq_to_K]; norm_cast
  rw [L2.inner_def] at hinner
  have hae : (fun x => ⟪(hf.toLp f : α → ℂ) x, (hf.toLp f : α → ℂ) x⟫_ℂ)
      =ᵐ[μ] fun x => ((‖f x‖ ^ 2 : ℝ) : ℂ) := by
    filter_upwards [hf.coeFn_toLp] with x hx
    rw [hx, inner_self_eq_norm_sq_to_K]
    norm_cast
  rw [integral_congr_ae hae, integral_complex_ofReal] at hinner
  exact_mod_cast hinner

/-- The squared `L²` norm of a class is the integral of the squared pointwise norm of any of
its representatives -- in particular of the canonical one. -/
theorem norm_Lp_two_sq {α : Type*} [MeasurableSpace α] {μ : Measure α}
    (F : MeasureTheory.Lp ℂ 2 μ) : ‖F‖ ^ 2 = ∫ x, ‖F x‖ ^ 2 ∂μ := by
  conv_lhs => rw [← MeasureTheory.Lp.toLp_coeFn F (MeasureTheory.Lp.memLp F)]
  exact norm_toLp_two_sq _

namespace BorelCalculus

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable {a : H →L[ℂ] H}

section Symbols

/-- **The bounded measurable symbols**, as a `ℂ`-submodule of all functions on the spectrum.

The Borel calculus takes a symbol *together with* a proof of `IsBddMeasurable`, which is a
`Prop`, so bundling the proof into the carrier loses nothing and gains a domain the
linear-algebra API can talk about. -/
def bddSymbols (a : H →L[ℂ] H) : Submodule ℂ (spectrum ℂ a → ℂ) where
  carrier := {f | IsBddMeasurable f}
  add_mem' hf hg := hf.add hg
  zero_mem' := ⟨measurable_const, 0, le_rfl, fun _ => by simp⟩
  smul_mem' c _ hf := hf.const_smul c

omit [CompleteSpace H] in
/-- Membership in `bddSymbols` is exactly admissibility for the Borel calculus. -/
theorem mem_bddSymbols {f : spectrum ℂ a → ℂ} : f ∈ bddSymbols a ↔ IsBddMeasurable f := Iff.rfl

omit [CompleteSpace H] in
/-- The admissibility proof carried by an element of `bddSymbols`.  Consumers cannot unfold
the submodule's carrier, so this is the accessor they use. -/
theorem isBddMeasurable_coe (f : bddSymbols a) :
    IsBddMeasurable (f : spectrum ℂ a → ℂ) := mem_bddSymbols.mp f.2

/-- **The calculus map on symbols**: `f ↦ f(a) ξ`, as a `ℂ`-linear map out of the bounded
measurable symbols. -/
noncomputable def symbolCalculus (ha : IsStarNormal a) (ξ : H) : bddSymbols a →ₗ[ℂ] H where
  toFun f := borelCalculus ha (isBddMeasurable_coe f) ξ
  map_add' f g := by
    have h : borelCalculus ha (isBddMeasurable_coe (f + g))
        = borelCalculus ha (isBddMeasurable_coe f) + borelCalculus ha (isBddMeasurable_coe g) :=
      borelCalculus_add ha (isBddMeasurable_coe f) (isBddMeasurable_coe g)
    rw [h]; rfl
  map_smul' c f := by
    have h : borelCalculus ha (isBddMeasurable_coe (c • f))
        = c • borelCalculus ha (isBddMeasurable_coe f) :=
      borelCalculus_const_smul ha c (isBddMeasurable_coe f)
    rw [h]; rfl

/-- The calculus map on symbols, unfolded. -/
@[simp] theorem symbolCalculus_apply (ha : IsStarNormal a) (ξ : H) (f : bddSymbols a) :
    symbolCalculus ha ξ f = borelCalculus ha (isBddMeasurable_coe f) ξ := (rfl)

/-- A bounded measurable symbol is square-integrable against the scalar spectral measure,
which is finite. -/
theorem memLp_two_of_isBddMeasurable (ha : IsStarNormal a) (ξ : H) {f : spectrum ℂ a → ℂ}
    (hf : IsBddMeasurable f) : MemLp f 2 (diagMeasure ha ξ) :=
  MemLp.of_bound hf.measurable.aestronglyMeasurable hf.chooseBound
    (Filter.Eventually.of_forall hf.norm_le_chooseBound)

/-- **The symbol-to-`L²` map**: a bounded measurable symbol, viewed as an element of `L²` of
the scalar spectral measure of `ξ`. -/
noncomputable def symbolToLp (ha : IsStarNormal a) (ξ : H) :
    bddSymbols a →ₗ[ℂ] Lp ℂ 2 (diagMeasure ha ξ) where
  toFun f := MemLp.toLp (f : spectrum ℂ a → ℂ)
    (memLp_two_of_isBddMeasurable ha ξ (isBddMeasurable_coe f))
  map_add' _ _ := MemLp.toLp_add _ _
  map_smul' c _ := MemLp.toLp_const_smul c _

/-- The symbol-to-`L²` map, unfolded. -/
theorem symbolToLp_apply (ha : IsStarNormal a) (ξ : H) (f : bddSymbols a) :
    symbolToLp ha ξ f = MemLp.toLp (f : spectrum ℂ a → ℂ)
      (memLp_two_of_isBddMeasurable ha ξ (isBddMeasurable_coe f)) := (rfl)

/-- The `L²` class of a bounded measurable symbol is represented by that symbol. -/
theorem coeFn_symbolToLp (ha : IsStarNormal a) (ξ : H) (f : bddSymbols a) :
    (symbolToLp ha ξ f : spectrum ℂ a → ℂ) =ᵐ[diagMeasure ha ξ] (f : spectrum ℂ a → ℂ) := by
  rw [symbolToLp_apply]
  exact MemLp.coeFn_toLp _

/-- The squared `L²` norm of a bounded measurable symbol. -/
theorem norm_symbolToLp_sq (ha : IsStarNormal a) (ξ : H) (f : bddSymbols a) :
    ‖symbolToLp ha ξ f‖ ^ 2 = ∫ x, ‖(f : spectrum ℂ a → ℂ) x‖ ^ 2 ∂(diagMeasure ha ξ) := by
  rw [symbolToLp_apply]
  exact norm_toLp_two_sq _

/-- **The isometry identity, in norm form.**  On bounded measurable symbols, `f ↦ f(a) ξ` has
exactly the `L²(μ_ξ)` norm of the symbol.

This is `norm_borelCalculus_apply_sq` (layer 1) with both sides recognised as squares of
norms; it is the hypothesis the extension in `cyclicIsometry` runs on. -/
theorem norm_symbolCalculus (ha : IsStarNormal a) (ξ : H) (f : bddSymbols a) :
    ‖symbolCalculus ha ξ f‖ = ‖symbolToLp ha ξ f‖ := by
  have hsq : ‖symbolCalculus ha ξ f‖ ^ 2 = ‖symbolToLp ha ξ f‖ ^ 2 := by
    rw [symbolCalculus_apply, norm_borelCalculus_apply_sq, norm_symbolToLp_sq]
  rw [← Real.sqrt_sq (norm_nonneg (symbolCalculus ha ξ f)),
    ← Real.sqrt_sq (norm_nonneg (symbolToLp ha ξ f)), hsq]

/-- The norm bound consumed by `LinearMap.extendOfNorm`: the constant is `1`, because the
symbol map is an isometry. -/
theorem exists_norm_symbolCalculus_le (ha : IsStarNormal a) (ξ : H) :
    ∃ C : ℝ, ∀ f : bddSymbols a, ‖symbolCalculus ha ξ f‖ ≤ C * ‖symbolToLp ha ξ f‖ :=
  ⟨1, fun f => by rw [one_mul, norm_symbolCalculus]⟩

end Symbols

section Density

/-- **Bounded measurable symbols are dense in `L²` of the scalar spectral measure.**

The spectrum is compact and `diagMeasure ha ξ` is a finite regular measure on it, so
continuous symbols are already dense (`ContinuousMap.toLp_denseRange`); and a continuous symbol
is bounded and measurable, hence lies in `bddSymbols`.  This is the only place regularity of
the diagonal measure is used. -/
theorem denseRange_symbolToLp (ha : IsStarNormal a) (ξ : H) :
    DenseRange (symbolToLp ha ξ) := by
  refine (ContinuousMap.toLp_denseRange (α := spectrum ℂ a) ℂ (diagMeasure ha ξ)
    (p := 2) ℂ (by simp)).mono ?_
  rintro _ ⟨g, rfl⟩
  refine ⟨⟨fun x => g x, mem_bddSymbols.mpr (IsBddMeasurable.of_continuous g)⟩, ?_⟩
  rw [symbolToLp_apply,
    ← Lp.toLp_coeFn (ContinuousMap.toLp 2 (diagMeasure ha ξ) ℂ g) (Lp.memLp _)]
  exact (MemLp.toLp_eq_toLp_iff _ _).2 (ContinuousMap.coeFn_toLp _ g).symm

end Density

section Isometry

/-- The extension of the symbol calculus along the symbol-to-`L²` map preserves norms.

Both sides are continuous in the `L²` variable and they agree on the dense range of
`symbolToLp` by `norm_symbolCalculus`, so they agree everywhere. -/
theorem norm_extendOfNorm_symbolCalculus (ha : IsStarNormal a) (ξ : H)
    (F : Lp ℂ 2 (diagMeasure ha ξ)) :
    ‖(symbolCalculus ha ξ).extendOfNorm (symbolToLp ha ξ) F‖ = ‖F‖ := by
  refine (denseRange_symbolToLp ha ξ).induction_on F
    (isClosed_eq (by fun_prop) continuous_norm) fun f => ?_
  rw [LinearMap.extendOfNorm_eq (denseRange_symbolToLp ha ξ)
    (exists_norm_symbolCalculus_le ha ξ) f]
  exact norm_symbolCalculus ha ξ f

/-- **The cyclic multiplication model, as an isometry.**  The map `f ↦ f(a) ξ` extends from
bounded measurable symbols to a linear isometry of `L²` of the scalar spectral measure of `ξ`
into the ambient Hilbert space.

Its range is the cyclic subspace generated by `ξ` (`range_cyclicIsometry`) and it carries
multiplication by the coordinate to `a` (`cyclicIsometry_coord_mul`); together those say that
`a` on the cyclic subspace *is* multiplication by the coordinate on `L²(μ_ξ)`. -/
noncomputable def cyclicIsometry (ha : IsStarNormal a) (ξ : H) :
    Lp ℂ 2 (diagMeasure ha ξ) →ₗᵢ[ℂ] H where
  toLinearMap := ((symbolCalculus ha ξ).extendOfNorm (symbolToLp ha ξ)).toLinearMap
  norm_map' := norm_extendOfNorm_symbolCalculus ha ξ

/-- **The defining property of the cyclic isometry**: on the class of a bounded measurable
symbol it is the Borel calculus at `ξ`. -/
theorem cyclicIsometry_symbolToLp (ha : IsStarNormal a) (ξ : H) (f : bddSymbols a) :
    cyclicIsometry ha ξ (symbolToLp ha ξ f) = borelCalculus ha (isBddMeasurable_coe f) ξ :=
  LinearMap.extendOfNorm_eq (denseRange_symbolToLp ha ξ)
    (exists_norm_symbolCalculus_le ha ξ) f

/-- The range of the cyclic isometry is closed: the domain is complete and the map preserves
distances. -/
theorem isClosed_range_cyclicIsometry (ha : IsStarNormal a) (ξ : H) :
    IsClosed ((LinearMap.range (cyclicIsometry ha ξ).toLinearMap : Submodule ℂ H) : Set H) := by
  rw [LinearMap.coe_range]
  exact (cyclicIsometry ha ξ).isometry.isUniformInducing.isComplete_range.isClosed

/-- **The cyclic isometry lands in the cyclic subspace.**  Every `L²` class is a limit of
bounded measurable symbols, whose images lie in the (closed) cyclic subspace. -/
theorem cyclicIsometry_mem_cyclicSubspace (ha : IsStarNormal a) (ξ : H)
    (F : Lp ℂ 2 (diagMeasure ha ξ)) : cyclicIsometry ha ξ F ∈ cyclicSubspace ha ξ := by
  refine (denseRange_symbolToLp ha ξ).induction_on F
    ((isClosed_cyclicSubspace ha ξ).preimage (cyclicIsometry ha ξ).continuous) fun f => ?_
  rw [cyclicIsometry_symbolToLp]
  exact borelCalculus_apply_mem_cyclicSubspace ha (isBddMeasurable_coe f) ξ

/-- **The range of the cyclic isometry is the cyclic subspace.**

One inclusion is `cyclicIsometry_mem_cyclicSubspace`.  The other is minimality of the cyclic
subspace: the calculus orbit lies in the range, which is a closed submodule. -/
theorem range_cyclicIsometry (ha : IsStarNormal a) (ξ : H) :
    LinearMap.range (cyclicIsometry ha ξ).toLinearMap = cyclicSubspace ha ξ := by
  refine le_antisymm (fun y hy => ?_) ?_
  · obtain ⟨F, rfl⟩ := hy
    exact cyclicIsometry_mem_cyclicSubspace ha ξ F
  · refine cyclicSubspace_le ha (isClosed_range_cyclicIsometry ha ξ) fun f hf => ?_
    exact ⟨symbolToLp ha ξ ⟨f, mem_bddSymbols.mpr hf⟩,
      cyclicIsometry_symbolToLp ha ξ ⟨f, mem_bddSymbols.mpr hf⟩⟩

end Isometry

section Intertwining

/-- The coordinate multiple of a bounded measurable symbol is again bounded measurable. -/
theorem isBddMeasurable_coord_mul {f : spectrum ℂ a → ℂ} (hf : IsBddMeasurable f) :
    IsBddMeasurable (fun w : spectrum ℂ a => (w : ℂ) * f w) :=
  (isBddMeasurable_coord (a := a)).mul hf

/-- The coordinate multiple of a bounded measurable symbol, as an element of `bddSymbols`. -/
theorem coordMul_mem_bddSymbols (f : bddSymbols a) :
    (fun w : spectrum ℂ a => (w : ℂ) * (f : spectrum ℂ a → ℂ) w) ∈ bddSymbols a :=
  mem_bddSymbols.mpr (isBddMeasurable_coord_mul (isBddMeasurable_coe f))

/-- **The intertwining law on symbols.**  Multiplying a symbol by the coordinate is applying
the operator to the value of the calculus.

This needs no spectral theorem: `borelCalculus_coord` says the calculus of the inclusion symbol
is `a` itself, and `borelCalculus_mul` says the calculus is multiplicative. -/
theorem symbolCalculus_coord_mul (ha : IsStarNormal a) (ξ : H) (f : bddSymbols a) :
    symbolCalculus ha ξ ⟨fun w : spectrum ℂ a => (w : ℂ) * (f : spectrum ℂ a → ℂ) w,
        coordMul_mem_bddSymbols f⟩
      = a (symbolCalculus ha ξ f) := by
  have h := borelCalculus_mul ha (isBddMeasurable_coord (a := a)) (isBddMeasurable_coe f)
  rw [borelCalculus_coord ha] at h
  have h2 := congrArg (fun T : H →L[ℂ] H => T ξ) h
  simpa using h2

/-- **The intertwining law, through the isometry.**  On the image of a bounded measurable
symbol, the cyclic isometry carries multiplication by the coordinate to the action of `a`.

Together with `range_cyclicIsometry` this identifies `a` on the cyclic subspace with
multiplication by the coordinate on `L²(μ_ξ)`: the two agree on a dense subspace, and both
sides are continuous. -/
theorem cyclicIsometry_coord_mul (ha : IsStarNormal a) (ξ : H) (f : bddSymbols a) :
    cyclicIsometry ha ξ (symbolToLp ha ξ
        ⟨fun w : spectrum ℂ a => (w : ℂ) * (f : spectrum ℂ a → ℂ) w,
          coordMul_mem_bddSymbols f⟩)
      = a (cyclicIsometry ha ξ (symbolToLp ha ξ f)) := by
  rw [cyclicIsometry_symbolToLp, cyclicIsometry_symbolToLp]
  exact symbolCalculus_coord_mul ha ξ f

end Intertwining

section Multiplication

/-- The coordinate multiple of an `L²` class is again `L²`, because the spectrum is bounded. -/
theorem memLp_coord_mul (ha : IsStarNormal a) (ξ : H) (F : Lp ℂ 2 (diagMeasure ha ξ)) :
    MemLp (fun w : spectrum ℂ a => (w : ℂ) * F w) 2 (diagMeasure ha ξ) := by
  refine MemLp.mono' ((Lp.memLp F).norm.const_mul
    (isBddMeasurable_coord (a := a)).chooseBound) ?_ ?_
  · exact (isBddMeasurable_coord (a := a)).measurable.aestronglyMeasurable.mul
      (Lp.aestronglyMeasurable F)
  · filter_upwards with w
    rw [norm_mul]
    exact mul_le_mul_of_nonneg_right ((isBddMeasurable_coord (a := a)).norm_le_chooseBound w)
      (norm_nonneg _)

/-- **The bound that makes coordinate multiplication a bounded operator.**  Squaring both
sides turns it into `∫ ‖w f w‖² ≤ C² ∫ ‖f w‖²`, which is `integral_mono` against the uniform
bound on the coordinate. -/
theorem norm_toLp_coord_mul_le (ha : IsStarNormal a) (ξ : H) (F : Lp ℂ 2 (diagMeasure ha ξ)) :
    ‖MemLp.toLp (fun w : spectrum ℂ a => (w : ℂ) * F w) (memLp_coord_mul ha ξ F)‖
      ≤ (isBddMeasurable_coord (a := a)).chooseBound * ‖F‖ := by
  set C := (isBddMeasurable_coord (a := a)).chooseBound with hCdef
  have hC0 : 0 ≤ C := (isBddMeasurable_coord (a := a)).chooseBound_nonneg
  have hmeas : AEStronglyMeasurable (fun w : spectrum ℂ a => (w : ℂ) * F w)
      (diagMeasure ha ξ) :=
    (isBddMeasurable_coord (a := a)).measurable.aestronglyMeasurable.mul
      (Lp.aestronglyMeasurable F)
  have hint1 : Integrable (fun w : spectrum ℂ a => ‖(w : ℂ) * F w‖ ^ 2) (diagMeasure ha ξ) :=
    (memLp_two_iff_integrable_sq_norm hmeas).mp (memLp_coord_mul ha ξ F)
  have hint2 : Integrable
      (fun w : spectrum ℂ a => ‖(F : spectrum ℂ a → ℂ) w‖ ^ 2) (diagMeasure ha ξ) :=
    (memLp_two_iff_integrable_sq_norm (Lp.aestronglyMeasurable F)).mp (Lp.memLp F)
  have hsq : ‖MemLp.toLp (fun w : spectrum ℂ a => (w : ℂ) * F w) (memLp_coord_mul ha ξ F)‖ ^ 2
      ≤ (C * ‖F‖) ^ 2 := by
    rw [norm_toLp_two_sq]
    calc ∫ w, ‖(w : ℂ) * F w‖ ^ 2 ∂(diagMeasure ha ξ)
        ≤ ∫ w, C ^ 2 * ‖(F : spectrum ℂ a → ℂ) w‖ ^ 2 ∂(diagMeasure ha ξ) := by
          refine integral_mono hint1 (hint2.const_mul _) fun w => ?_
          rw [norm_mul, mul_pow]
          have hw := (isBddMeasurable_coord (a := a)).norm_le_chooseBound w
          have hsqw : ‖(w : ℂ)‖ ^ 2 ≤ C ^ 2 := by nlinarith [norm_nonneg ((w : ℂ))]
          nlinarith [sq_nonneg ‖(F : spectrum ℂ a → ℂ) w‖]
      _ = C ^ 2 * ∫ w, ‖(F : spectrum ℂ a → ℂ) w‖ ^ 2 ∂(diagMeasure ha ξ) :=
          integral_const_mul _ _
      _ = (C * ‖F‖) ^ 2 := by rw [← norm_Lp_two_sq]; ring
  nlinarith [norm_nonneg (MemLp.toLp (fun w : spectrum ℂ a => (w : ℂ) * F w)
    (memLp_coord_mul ha ξ F)), mul_nonneg hC0 (norm_nonneg F)]

/-- **Multiplication by the coordinate**, as a bounded operator on `L²` of the scalar spectral
measure of `ξ`.  This is the operator the multiplication model says `a` becomes. -/
noncomputable def coordMulLp (ha : IsStarNormal a) (ξ : H) :
    Lp ℂ 2 (diagMeasure ha ξ) →L[ℂ] Lp ℂ 2 (diagMeasure ha ξ) :=
  LinearMap.mkContinuous
    { toFun := fun F => MemLp.toLp (fun w : spectrum ℂ a => (w : ℂ) * F w)
        (memLp_coord_mul ha ξ F)
      map_add' := fun F G => by
        rw [← MemLp.toLp_add (memLp_coord_mul ha ξ F) (memLp_coord_mul ha ξ G)]
        refine (MemLp.toLp_eq_toLp_iff _ _).2 ?_
        filter_upwards [Lp.coeFn_add F G] with w hw
        simp only [Pi.add_apply, hw]
        ring
      map_smul' := fun c F => by
        rw [RingHom.id_apply, ← MemLp.toLp_const_smul c (memLp_coord_mul ha ξ F)]
        refine (MemLp.toLp_eq_toLp_iff _ _).2 ?_
        filter_upwards [Lp.coeFn_smul c F] with w hw
        simp only [Pi.smul_apply, hw, smul_eq_mul]
        ring }
    (isBddMeasurable_coord (a := a)).chooseBound (norm_toLp_coord_mul_le ha ξ)

/-- Coordinate multiplication, unfolded. -/
theorem coordMulLp_apply (ha : IsStarNormal a) (ξ : H) (F : Lp ℂ 2 (diagMeasure ha ξ)) :
    coordMulLp ha ξ F = MemLp.toLp (fun w : spectrum ℂ a => (w : ℂ) * F w)
      (memLp_coord_mul ha ξ F) := (rfl)

/-- Coordinate multiplication really is pointwise multiplication by the coordinate. -/
theorem coeFn_coordMulLp (ha : IsStarNormal a) (ξ : H) (F : Lp ℂ 2 (diagMeasure ha ξ)) :
    (coordMulLp ha ξ F : spectrum ℂ a → ℂ)
      =ᵐ[diagMeasure ha ξ] fun w => (w : ℂ) * F w := by
  rw [coordMulLp_apply]
  exact MemLp.coeFn_toLp _

/-- On the class of a bounded measurable symbol, coordinate multiplication is multiplication
of symbols. -/
theorem coordMulLp_symbolToLp (ha : IsStarNormal a) (ξ : H) (f : bddSymbols a) :
    coordMulLp ha ξ (symbolToLp ha ξ f)
      = symbolToLp ha ξ ⟨fun w : spectrum ℂ a => (w : ℂ) * (f : spectrum ℂ a → ℂ) w,
        coordMul_mem_bddSymbols f⟩ := by
  rw [coordMulLp_apply, symbolToLp_apply ha ξ ⟨_, coordMul_mem_bddSymbols f⟩]
  refine (MemLp.toLp_eq_toLp_iff _ _).2 ?_
  filter_upwards [coeFn_symbolToLp ha ξ f] with w hw
  simp only [hw]

/-- **The multiplication model.**  The cyclic isometry intertwines multiplication by the
coordinate on `L²(μ_ξ)` with the operator `a` on `H`:

```text
Φ (w · F) = a (Φ F)   for every F in L²(μ_ξ).
```

Both sides are continuous in `F` and agree on the dense set of bounded measurable symbols,
where the identity is `symbolCalculus_coord_mul`.  With `range_cyclicIsometry` this is the
statement that `a`, restricted to the cyclic subspace generated by `ξ`, *is* multiplication by
the coordinate on `L²` of the scalar spectral measure of `ξ`. -/
theorem cyclicIsometry_coordMulLp (ha : IsStarNormal a) (ξ : H)
    (F : Lp ℂ 2 (diagMeasure ha ξ)) :
    cyclicIsometry ha ξ (coordMulLp ha ξ F) = a (cyclicIsometry ha ξ F) := by
  refine (denseRange_symbolToLp ha ξ).induction_on F
    (isClosed_eq ((cyclicIsometry ha ξ).continuous.comp (coordMulLp ha ξ).continuous)
      (a.continuous.comp (cyclicIsometry ha ξ).continuous)) fun f => ?_
  rw [coordMulLp_symbolToLp]
  exact cyclicIsometry_coord_mul ha ξ f

/-- **The cyclic subspace is invariant under its operator.**  Immediate from the model: `a`
becomes multiplication by the coordinate, which does not leave `L²(μ_ξ)`. -/
theorem apply_mem_cyclicSubspace (ha : IsStarNormal a) (ξ : H) {y : H}
    (hy : y ∈ cyclicSubspace ha ξ) : a y ∈ cyclicSubspace ha ξ := by
  rw [← range_cyclicIsometry ha ξ] at hy ⊢
  obtain ⟨F, rfl⟩ := hy
  exact ⟨coordMulLp ha ξ F, cyclicIsometry_coordMulLp ha ξ F⟩

end Multiplication

end BorelCalculus
end TauCeti
