/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, Claude Fable 5
-/
module

public import LeanPool.DavisKahan.ForTauCeti.Analysis.InnerProductSpace.BorelCalculus.Multiplicative

/-!
# The cyclic isometry of the Borel calculus

For a normal operator `a` and a vector `ξ`, the map

```text
f ↦ f(a) ξ
```

is an **isometry** from `L²` of the scalar spectral measure `diagMeasure ha ξ` into the
ambient Hilbert space:

```text
‖f(a) ξ‖² = ∫ ‖f x‖² d(diagMeasure ha ξ).
```

This single identity is the cornerstone of the multiplication model of the spectral
theorem: it is what makes the cyclic subspace generated by `ξ` unitarily equivalent to
`L²(μ_ξ)` with `a` acting as multiplication by the coordinate.  Building the multiplicity
theory (Hahn--Hellinger) on top of the repository's Borel calculus starts here — see
the multiplication model, the cyclic decomposition, and the multiplicity normal form above it.

The computation was already carried out inside the proof of
`norm_borelCalculus_apply_le`, where it appeared as an unnamed `have` on the way to a
norm bound.  It is stated here in its own right, in the `‖f x‖²` form rather than the
`(conj (f x) * f x).re` form the bound happened to need, because that is the form the
`L²` isometry consumes.

## Main results

* `TauCeti.BorelCalculus.norm_borelCalculus_apply_sq`: the isometry identity.
* `TauCeti.BorelCalculus.cyclicSubspace`: the closed cyclic subspace generated by `ξ`.
* `TauCeti.BorelCalculus.borelCalculus_apply_mem_cyclicSubspace` and
  `TauCeti.BorelCalculus.mem_cyclicSubspace_self`: the two facts that make it cyclic.

## Provenance

* Original repository: Davis--Kahan/DKPS formalization (Kitware, Inc.).
* Extraction class: **authored in place** for the Tau Ceti staging layer.
* Spectra influence: **none** — this module imports only Mathlib and `ForTauCeti`.
-/

public section

open scoped InnerProductSpace
open MeasureTheory

namespace TauCeti
namespace BorelCalculus

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable {a : H →L[ℂ] H}

/-- **The cyclic isometry identity.**  The squared norm of `f(a) ξ` is the `L²` norm of
the symbol against the scalar spectral measure of `ξ`.

Equivalently: `f ↦ f(a) ξ` is an isometry of `L²(diagMeasure ha ξ)` into `H`.  This is
the analytic content of the multiplication model of the spectral theorem, and it needs
nothing beyond multiplicativity of the calculus, its `⋆`-preservation, and the defining
property of the diagonal measure. -/
theorem norm_borelCalculus_apply_sq (ha : IsStarNormal a)
    {f : spectrum ℂ a → ℂ} (hf : IsBddMeasurable f) (ξ : H) :
    ‖borelCalculus ha hf ξ‖ ^ 2 = ∫ x, ‖f x‖ ^ 2 ∂(diagMeasure ha ξ) := by
  have hinner : ⟪borelCalculus ha hf ξ, borelCalculus ha hf ξ⟫_ℂ
      = ⟪ξ, (borelCalculus ha hf.conj * borelCalculus ha hf) ξ⟫_ℂ := by
    rw [borelCalculus_conj, _root_.mul_apply_eq_comp,
      ContinuousLinearMap.adjoint_inner_right]
  rw [← borelCalculus_mul, inner_borelCalculus_self] at hinner
  have hnorm : ⟪borelCalculus ha hf ξ, borelCalculus ha hf ξ⟫_ℂ
      = ((‖borelCalculus ha hf ξ‖ ^ 2 : ℝ) : ℂ) := by
    rw [inner_self_eq_norm_sq_to_K]; norm_cast
  rw [hnorm] at hinner
  have hre := congrArg Complex.re hinner
  rw [Complex.ofReal_re] at hre
  have hint : (∫ x, (starRingEnd ℂ) (f x) * f x ∂(diagMeasure ha ξ)).re
      = ∫ x, ((starRingEnd ℂ) (f x) * f x).re ∂(diagMeasure ha ξ) :=
    (integral_re ((hf.conj.mul hf).integrable _)).symm
  rw [hint] at hre
  -- `conj z * z` has real part `‖z‖²`.
  have hptwise : ∀ x : spectrum ℂ a,
      ((starRingEnd ℂ) (f x) * f x).re = ‖f x‖ ^ 2 := by
    intro x
    rw [Complex.mul_re, Complex.conj_re, Complex.conj_im,
      ← Complex.normSq_eq_norm_sq, Complex.normSq_apply]
    ring
  rw [hre]
  exact integral_congr_ae (Filter.Eventually.of_forall hptwise)

/-- The **cyclic subspace** generated by a vector: the closed span of the orbit of `ξ`
under the Borel calculus of `a`.

The multiplication model identifies this subspace with `L²` of the scalar spectral
measure of `ξ`, by `norm_borelCalculus_apply_sq`. -/
noncomputable def cyclicSubspace (ha : IsStarNormal a) (ξ : H) : Submodule ℂ H :=
  (Submodule.span ℂ
    {y : H | ∃ (f : spectrum ℂ a → ℂ) (hf : IsBddMeasurable f),
      borelCalculus ha hf ξ = y}).topologicalClosure

/-- Every value of the calculus at `ξ` lies in the cyclic subspace it generates. -/
theorem borelCalculus_apply_mem_cyclicSubspace (ha : IsStarNormal a)
    {f : spectrum ℂ a → ℂ} (hf : IsBddMeasurable f) (ξ : H) :
    borelCalculus ha hf ξ ∈ cyclicSubspace ha ξ :=
  (Submodule.span ℂ _).le_topologicalClosure
    (Submodule.subset_span ⟨f, hf, rfl⟩)

/-- The generating vector lies in its own cyclic subspace — the symbol is the constant
one, whose calculus is the identity. -/
theorem mem_cyclicSubspace_self (ha : IsStarNormal a) (ξ : H) :
    ξ ∈ cyclicSubspace ha ξ := by
  have h1 : IsBddMeasurable (fun _ : spectrum ℂ a => (1 : ℂ)) :=
    ⟨measurable_const, 1, zero_le_one, fun _ => by simp⟩
  have hmem := borelCalculus_apply_mem_cyclicSubspace ha h1 ξ
  rwa [borelCalculus_one ha h1, one_apply_eq_self] at hmem

/-- The cyclic subspace is closed, hence a complete space in its own right. -/
theorem isClosed_cyclicSubspace (ha : IsStarNormal a) (ξ : H) :
    IsClosed ((cyclicSubspace ha ξ : Submodule ℂ H) : Set H) :=
  (Submodule.span ℂ _).isClosed_topologicalClosure

/-- **Minimality of the cyclic subspace.**  It is contained in every closed submodule that
already contains the calculus orbit of `ξ`.

This is the elimination principle for `cyclicSubspace`, and it is what a call site needs
instead of the definition body: the definition is a `topologicalClosure` of a `span`, and
`Submodule.topologicalClosure_minimal` plus `Submodule.span_le` is exactly this statement.
Stated here so that consumers never unfold `cyclicSubspace`. -/
theorem cyclicSubspace_le (ha : IsStarNormal a) {ξ : H} {S : Submodule ℂ H}
    (hS : IsClosed (S : Set H))
    (h : ∀ (f : spectrum ℂ a → ℂ) (hf : IsBddMeasurable f), borelCalculus ha hf ξ ∈ S) :
    cyclicSubspace ha ξ ≤ S := by
  refine Submodule.topologicalClosure_minimal _ ?_ hS
  rw [Submodule.span_le]
  rintro y ⟨f, hf, rfl⟩
  exact h f hf

end BorelCalculus
end TauCeti
