/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, Claude Fable 5
-/
module

public import LeanPool.DavisKahan.ForTauCeti.Analysis.InnerProductSpace.BorelCalculus.CyclicModel
public import Mathlib.Analysis.InnerProductSpace.l2Space
public import Mathlib.Order.Zorn

/-!
# The cyclic decomposition of a Hilbert space under a normal operator

Layer 3 of the Hahn--Hellinger stack.  Layer 1
(`ForTauCeti/Analysis/InnerProductSpace/BorelCalculus/CyclicIsometry.lean`) built the cyclic
subspace generated by a single vector, and layer 2
(`ForTauCeti/Analysis/InnerProductSpace/BorelCalculus/CyclicModel.lean`) identified it with
`L²` of the scalar spectral measure of that vector.  This file assembles *all* of `H` out of
such pieces: for a bounded normal `a` there is a family of vectors whose cyclic subspaces are
pairwise orthogonal and together span `H`, so that

```text
H ≃ₗᵢ ℓ²-sum over i of L²(μ_{ξ i}),   a  ↦  coordinatewise multiplication.
```

## No separability hypothesis

**The index type is arbitrary and nothing here is countable.**  `lp`, `OrthogonalFamily`,
`IsHilbertSum` and `IsHilbertSum.mkInternal` are all stated by Mathlib over an arbitrary index
type, so the decomposition is produced by Zorn's lemma on sets of vectors and the index type is
whatever cardinality the maximal set has.  This matches the scope of the repository's
Davis--Kahan Theorem 3.1, which carries no separability hypothesis either.

A greedy `ℕ`-recursion against a dense sequence would have forced
`[TopologicalSpace.SeparableSpace H]`; that route was considered in
a greedy `ℕ`-recursion, which would have needed it; Zorn over an arbitrary index type does not.
Insisting on `ℕ` is what drags separability in, and nothing needs `ℕ`.

## The two mathematical steps

1. **Invariance passes to the orthogonal complement.**  If `K` is invariant under every
   `borelCalculus ha hf` then so is `Kᗮ`, because
   `⟪x, f(a) η⟫ = ⟪f(a)⋆ x, η⟫ = ⟪f̄(a) x, η⟫ = 0` for `x ∈ K` — the calculus is
   `⋆`-preserving (`borelCalculus_conj`) and `f̄(a) x` is back in `K`.  Consequently
   `cyclicSubspace ha η ≤ Kᗮ` whenever `η ∈ Kᗮ`, by minimality of the cyclic subspace.
2. **Maximality gives totality.**  Zorn produces a maximal set `S` of nonzero vectors with
   pairwise orthogonal cyclic subspaces.  If the closed span of those subspaces were not `⊤`,
   its orthogonal complement would contain a nonzero `η`; step 1 makes `cyclicSubspace ha η`
   orthogonal to all of them, so `insert η S` would still be admissible, contradicting
   maximality.

## Main results

* `TauCeti.BorelCalculus.IsCalculusInvariant`: invariance under the whole Borel calculus.
* `TauCeti.BorelCalculus.IsCalculusInvariant.orthogonal`: **the invariance lemma** — the
  orthogonal complement of a calculus-invariant subspace is calculus-invariant.
* `TauCeti.BorelCalculus.cyclicSubspace_le_orthogonal`: a vector of `Kᗮ` generates a cyclic
  subspace inside `Kᗮ`.
* `TauCeti.BorelCalculus.exists_orthogonalFamily_cyclicSubspace`: **the decomposition** — an
  orthogonal family of cyclic subspaces with dense span.
* `TauCeti.BorelCalculus.exists_isHilbertSum_cyclicSubspace`: the same, packaged as an
  `IsHilbertSum`.
* `TauCeti.BorelCalculus.exists_isHilbertSum_lp_diagMeasure` and
  `TauCeti.BorelCalculus.exists_linearIsometryEquiv_lp_diagMeasure`: `H` is the `ℓ²`-sum of the
  `L²` spaces of the scalar spectral measures, via layer 2's `cyclicIsometry`.

## What is not here

The decomposition is not yet organised by measure class: the vectors are unordered, the
measures `diagMeasure ha (ξ i)` are unrelated to one another, and no multiplicity function
appears.  Ordering them is layer 4 and the multiplicity function is layer 5; see
the uniform-multiplicity form, which replaces the separable normal form
`μ₁ ≫ μ₂ ≫ …` by the uniform-multiplicity decomposition indexed by cardinals.

## Provenance

* Original repository: Davis--Kahan/DKPS formalization (Kitware, Inc.).
* Extraction class: **authored in place** for the Tau Ceti staging layer.
* Spectra influence: **none** — this module imports only Mathlib and `ForTauCeti`.
-/

public section

open scoped InnerProductSpace
open MeasureTheory

universe u

namespace TauCeti
namespace BorelCalculus

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable {a : H →L[ℂ] H}

section Invariance

/-- A submodule is **calculus-invariant** when every value of the bounded Borel calculus of `a`
maps it into itself.

This is the hypothesis under which the orthogonal complement is again invariant, which is the
step that makes a maximal orthogonal family of cyclic subspaces total. -/
def IsCalculusInvariant (ha : IsStarNormal a) (K : Submodule ℂ H) : Prop :=
  ∀ (f : spectrum ℂ a → ℂ) (hf : IsBddMeasurable f), ∀ x ∈ K, borelCalculus ha hf x ∈ K

/-- Elimination form of `IsCalculusInvariant`, so a call site need not unfold the definition.

The definition body is not exposed outside this module, so this is what a downstream consumer
uses; `ForTauCeti/Analysis/InnerProductSpace/BorelCalculus/Restriction.lean` is the first. -/
theorem IsCalculusInvariant.borelCalculus_mem {ha : IsStarNormal a} {K : Submodule ℂ H}
    (hK : IsCalculusInvariant ha K) {f : spectrum ℂ a → ℂ} (hf : IsBddMeasurable f) {x : H}
    (hx : x ∈ K) : borelCalculus ha hf x ∈ K :=
  hK f hf x hx

/-- **A cyclic subspace is calculus-invariant.**

By minimality (`cyclicSubspace_le`) it suffices to check the calculus orbit of the generating
vector, where the statement is multiplicativity: `f(a) (g(a) ξ) = (f g)(a) ξ`. -/
theorem isCalculusInvariant_cyclicSubspace (ha : IsStarNormal a) (ξ : H) :
    IsCalculusInvariant ha (cyclicSubspace ha ξ) := by
  intro f hf
  have hle : cyclicSubspace ha ξ
      ≤ Submodule.comap (borelCalculus ha hf).toLinearMap (cyclicSubspace ha ξ) := by
    refine cyclicSubspace_le ha
      ((isClosed_cyclicSubspace ha ξ).preimage (borelCalculus ha hf).continuous) fun g hg => ?_
    have hmul : borelCalculus ha (hf.mul hg) ξ
        = borelCalculus ha hf (borelCalculus ha hg ξ) := by
      rw [borelCalculus_mul ha hf hg, _root_.mul_apply_eq_comp]
    change borelCalculus ha hf (borelCalculus ha hg ξ) ∈ cyclicSubspace ha ξ
    rw [← hmul]
    exact borelCalculus_apply_mem_cyclicSubspace ha (hf.mul hg) ξ
  exact fun x hx => hle hx

/-- A supremum of calculus-invariant submodules is calculus-invariant. -/
theorem isCalculusInvariant_iSup {ha : IsStarNormal a} {ι : Type*} {K : ι → Submodule ℂ H}
    (hK : ∀ i, IsCalculusInvariant ha (K i)) : IsCalculusInvariant ha (⨆ i, K i) := by
  intro f hf
  have hle : (⨆ i, K i) ≤ Submodule.comap (borelCalculus ha hf).toLinearMap (⨆ i, K i) := by
    refine iSup_le fun i => ?_
    intro x hx
    exact le_iSup K i (hK i f hf x hx)
  exact fun x hx => hle hx

/-- **The invariance lemma.**  The orthogonal complement of a calculus-invariant submodule is
calculus-invariant.

The two steps are exactly the ones inside `norm_borelCalculus_apply_sq`: the calculus is
`⋆`-preserving, so `⟪x, f(a) η⟫ = ⟪f̄(a) x, η⟫`, and `f̄(a) x` lies back in `K` by hypothesis,
so the inner product vanishes for `η ∈ Kᗮ`. -/
theorem IsCalculusInvariant.orthogonal {ha : IsStarNormal a} {K : Submodule ℂ H}
    (hK : IsCalculusInvariant ha K) : IsCalculusInvariant ha Kᗮ := by
  intro f hf η hη
  rw [Submodule.mem_orthogonal]
  intro x hx
  have hadj : ⟪x, borelCalculus ha hf η⟫_ℂ = ⟪borelCalculus ha hf.conj x, η⟫_ℂ := by
    rw [borelCalculus_conj ha hf, ContinuousLinearMap.adjoint_inner_left]
  rw [hadj]
  exact (Submodule.mem_orthogonal K η).mp hη _ (hK _ hf.conj x hx)

/-- **A vector of `Kᗮ` generates a cyclic subspace inside `Kᗮ`**, whenever `K` is
calculus-invariant.

This is the invariance lemma followed by minimality of the cyclic subspace: `Kᗮ` is closed and
contains the whole calculus orbit of `η`. -/
theorem cyclicSubspace_le_orthogonal {ha : IsStarNormal a} {K : Submodule ℂ H}
    (hK : IsCalculusInvariant ha K) {η : H} (hη : η ∈ Kᗮ) : cyclicSubspace ha η ≤ Kᗮ :=
  cyclicSubspace_le ha K.isClosed_orthogonal fun f hf => hK.orthogonal f hf η hη

end Invariance

section Zorn

/-- **The condition Zorn is run on**: a set of nonzero vectors whose cyclic subspaces are
pairwise orthogonal.

The condition has finite character — it constrains pairs — so chains close under union, which
is the only thing `zorn_subset` needs. -/
structure IsOrthogonalCyclicSet (ha : IsStarNormal a) (S : Set H) : Prop where
  /-- The zero vector is excluded, so that adjoining a new nonzero vector strictly enlarges the
  set. -/
  zero_notMem : (0 : H) ∉ S
  /-- Distinct members generate orthogonal cyclic subspaces. -/
  isOrtho : ∀ x ∈ S, ∀ y ∈ S, x ≠ y → cyclicSubspace ha x ⟂ cyclicSubspace ha y

/-- The union of a chain of orthogonal cyclic sets is again one: both conditions involve at most
two members at a time, and any two members of the union already lie in a common element of the
chain. -/
theorem isOrthogonalCyclicSet_sUnion (ha : IsStarNormal a) {c : Set (Set H)}
    (hc : ∀ s ∈ c, IsOrthogonalCyclicSet ha s) (hchain : IsChain (· ⊆ ·) c) :
    IsOrthogonalCyclicSet ha (⋃₀ c) := by
  constructor
  · rintro ⟨s, hs, h0⟩
    exact (hc s hs).zero_notMem h0
  · rintro x ⟨s, hs, hxs⟩ y ⟨t, ht, hyt⟩ hxy
    rcases eq_or_ne s t with rfl | hst
    · exact (hc s hs).isOrtho x hxs y hyt hxy
    · rcases hchain hs ht hst with h | h
      · exact (hc t ht).isOrtho x (h hxs) y hyt hxy
      · exact (hc s hs).isOrtho x hxs y (h hyt) hxy

/-- **Zorn's lemma applied to orthogonal cyclic sets.**  A maximal one exists.

No cardinality assumption enters: the maximal set is whatever it is, and its own subtype is the
index type of the decomposition. -/
theorem exists_maximal_isOrthogonalCyclicSet (ha : IsStarNormal a) :
    ∃ S : Set H, Maximal (IsOrthogonalCyclicSet ha) S := by
  obtain ⟨m, hm⟩ := zorn_subset {S : Set H | IsOrthogonalCyclicSet ha S} fun c hc hchain =>
    ⟨⋃₀ c, isOrthogonalCyclicSet_sUnion ha (fun s hs => hc hs) hchain,
      fun s hs => Set.subset_sUnion_of_mem hs⟩
  exact ⟨m, hm⟩

end Zorn

section Decomposition

/-- The cyclic subspaces generated by the members of an orthogonal cyclic set form an orthogonal
family, indexed by the set itself. -/
theorem orthogonalFamily_cyclicSubspace {ha : IsStarNormal a} {S : Set H}
    (hS : IsOrthogonalCyclicSet ha S) :
    OrthogonalFamily ℂ (fun ξ : S => (cyclicSubspace ha (ξ : H) : Submodule ℂ H))
      (fun ξ : S => (cyclicSubspace ha (ξ : H)).subtypeₗᵢ) :=
  OrthogonalFamily.of_pairwise fun _ _ hij =>
    hS.isOrtho _ (Subtype.coe_prop _) _ (Subtype.coe_prop _) (Subtype.coe_injective.ne hij)

/-- **Maximality gives a dense span.**  For a maximal orthogonal cyclic set the cyclic subspaces
of its members span `H` densely.

If they did not, the orthogonal complement of their supremum would contain a nonzero `η`.  The
supremum is calculus-invariant, so `cyclicSubspace ha η` sits inside that complement and is
therefore orthogonal to every member's cyclic subspace; then `insert η S` is still an orthogonal
cyclic set, so maximality forces `η ∈ S` — but then `η` is orthogonal to itself, hence zero. -/
theorem topologicalClosure_iSup_cyclicSubspace_of_maximal (ha : IsStarNormal a) {S : Set H}
    (hS : Maximal (IsOrthogonalCyclicSet ha) S) :
    (⊤ : Submodule ℂ H) ≤ (⨆ ξ : S, cyclicSubspace ha (ξ : H)).topologicalClosure := by
  have hle : ∀ v ∈ S, cyclicSubspace ha v ≤ ⨆ ξ : S, cyclicSubspace ha (ξ : H) := fun v hv =>
    le_iSup (fun ξ : S => cyclicSubspace ha (ξ : H)) ⟨v, hv⟩
  have hinv : IsCalculusInvariant ha (⨆ ξ : S, cyclicSubspace ha (ξ : H)) :=
    isCalculusInvariant_iSup fun ξ => isCalculusInvariant_cyclicSubspace ha (ξ : H)
  have hbot : (⨆ ξ : S, cyclicSubspace ha (ξ : H))ᗮ = ⊥ := by
    by_contra hne
    obtain ⟨η, hηmem, hη0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hne
    have hcyc : cyclicSubspace ha η ≤ (⨆ ξ : S, cyclicSubspace ha (ξ : H))ᗮ :=
      cyclicSubspace_le_orthogonal hinv hηmem
    have hins : IsOrthogonalCyclicSet ha (insert η S) := by
      constructor
      · rintro (h | h)
        · exact hη0 h.symm
        · exact hS.prop.zero_notMem h
      · rintro x (rfl | hx) y (rfl | hy) hxy
        · exact absurd rfl hxy
        · exact Submodule.isOrtho_iff_le.mpr
            (hcyc.trans (Submodule.orthogonal_le (hle y hy)))
        · exact (Submodule.isOrtho_iff_le.mpr
            (hcyc.trans (Submodule.orthogonal_le (hle x hx)))).symm
        · exact hS.prop.isOrtho x hx y hy hxy
    have hηS : η ∈ S := hS.mem_of_prop_insert hins
    exact hη0 (inner_self_eq_zero.mp
      ((Submodule.mem_orthogonal _ η).mp hηmem η (hle η hηS (mem_cyclicSubspace_self ha η))))
  exact (Submodule.topologicalClosure_eq_top_iff.mpr hbot).ge

/-- **The cyclic decomposition of a Hilbert space under a normal operator.**

There is a family of vectors, indexed by an arbitrary type, whose cyclic subspaces are pairwise
orthogonal and whose closed span is all of `H`.

**No separability hypothesis.**  The index type is the subtype of a Zorn-maximal set of vectors;
it has whatever cardinality it has, and nothing in the statement or the proof mentions
countability. -/
theorem exists_orthogonalFamily_cyclicSubspace (ha : IsStarNormal a) :
    ∃ (ι : Type u) (ξ : ι → H),
      OrthogonalFamily ℂ (fun i => (cyclicSubspace ha (ξ i) : Submodule ℂ H))
        (fun i => (cyclicSubspace ha (ξ i)).subtypeₗᵢ) ∧
      (⊤ : Submodule ℂ H) ≤ (⨆ i, cyclicSubspace ha (ξ i)).topologicalClosure := by
  obtain ⟨S, hS⟩ := exists_maximal_isOrthogonalCyclicSet ha
  exact ⟨S, Subtype.val, orthogonalFamily_cyclicSubspace hS.prop,
    topologicalClosure_iSup_cyclicSubspace_of_maximal ha hS⟩

/-- **The cyclic decomposition, as a Hilbert sum.**  `H` is the internal Hilbert sum of an
orthogonal family of cyclic subspaces of `a`.

This is `exists_orthogonalFamily_cyclicSubspace` fed to `IsHilbertSum.mkInternal`, whose
hypothesis is exactly the dense-span condition.  Each summand is complete because cyclic
subspaces are closed. -/
theorem exists_isHilbertSum_cyclicSubspace (ha : IsStarNormal a) :
    ∃ (ι : Type u) (ξ : ι → H),
      IsHilbertSum ℂ (fun i => (cyclicSubspace ha (ξ i) : Submodule ℂ H))
        (fun i => (cyclicSubspace ha (ξ i)).subtypeₗᵢ) := by
  obtain ⟨ι, ξ, hortho, htotal⟩ := exists_orthogonalFamily_cyclicSubspace ha
  refine ⟨ι, ξ, ?_⟩
  have hcomplete : ∀ i, CompleteSpace (cyclicSubspace ha (ξ i)) := by
    intro i
    have : IsClosed ((cyclicSubspace ha (ξ i) : Submodule ℂ H) : Set H) :=
      isClosed_cyclicSubspace ha (ξ i)
    infer_instance
  exact IsHilbertSum.mkInternal (𝕜 := ℂ) (F := fun i => cyclicSubspace ha (ξ i)) hortho htotal

end Decomposition

section LpModel

/-- **The `L²` form of the decomposition.**  `H` is the Hilbert sum of the `L²` spaces of the
scalar spectral measures of a family of vectors, embedded by layer 2's `cyclicIsometry`.

Orthogonality of the embeddings is orthogonality of their ranges, which are the cyclic
subspaces (`range_cyclicIsometry`); totality is the same rewriting.  Again no countability is
involved. -/
theorem exists_isHilbertSum_lp_diagMeasure (ha : IsStarNormal a) :
    ∃ (ι : Type u) (ξ : ι → H),
      IsHilbertSum ℂ (fun i => Lp ℂ 2 (diagMeasure ha (ξ i)))
        (fun i => cyclicIsometry ha (ξ i)) := by
  obtain ⟨ι, ξ, hortho, htotal⟩ := exists_orthogonalFamily_cyclicSubspace ha
  refine ⟨ι, ξ, IsHilbertSum.mk (𝕜 := ℂ) (G := fun i => Lp ℂ 2 (diagMeasure ha (ξ i)))
    (V := fun i => cyclicIsometry ha (ξ i)) (fun i j hij v w => ?_) ?_⟩
  · exact (hortho.isOrtho hij).inner_eq (cyclicIsometry_mem_cyclicSubspace ha (ξ i) v)
      (cyclicIsometry_mem_cyclicSubspace ha (ξ j) w)
  · simpa only [range_cyclicIsometry] using htotal

/-- **The multiplication model of a normal operator, globally.**  Every complex Hilbert space
carrying a bounded normal operator is isometrically the `ℓ²`-sum of `L²` spaces of scalar
spectral measures.

Combined with layer 2's intertwining law `cyclicIsometry_coordMulLp`, this says the operator
becomes coordinatewise multiplication by the spectral coordinate.  **The index type is
arbitrary: no separability hypothesis is used anywhere in the chain that produces it.** -/
theorem exists_linearIsometryEquiv_lp_diagMeasure (ha : IsStarNormal a) :
    ∃ (ι : Type u) (ξ : ι → H),
      Nonempty (H ≃ₗᵢ[ℂ] lp (fun i => Lp ℂ 2 (diagMeasure ha (ξ i))) 2) := by
  obtain ⟨ι, ξ, hsum⟩ := exists_isHilbertSum_lp_diagMeasure ha
  exact ⟨ι, ξ, ⟨hsum.linearIsometryEquiv⟩⟩

end LpModel

end BorelCalculus
end TauCeti
