/-
Copyright (c) 2026 Shengtong Zhang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Shengtong Zhang
-/

import Mathlib.RingTheory.GradedAlgebra.Radical
import LeanPool.Nikodym.Nikodym.LowerBound.Algebra.GradedLemmas
import LeanPool.Nikodym.Nikodym.LowerBound.Algebra.Dimension
import LeanPool.Nikodym.Nikodym.LowerBound.Algebra.Interface

/-!
# The homogenization bridge

This file implements blueprint node **A05** (design document §2): the passage between ideals of
`P = MvPolynomial (Fin d) K` and homogeneous ideals of `P̂ = MvPolynomial (Fin (d+1)) K`, where
the index `0` is the homogenizing variable `X₀` and `Fin.succ i` is the variable `Xᵢ` of `P`.

## Main declarations

* `Nikodym.LowerBound.dehom : P̂ →ₐ[K] P`, the dehomogenization `X₀ ↦ 1`, `X_{i+1} ↦ Xᵢ`;
* `Nikodym.LowerBound.homogenizeTo t F`, the homogenization of `F` to degree `t`, and the
  `K`-linear map `homogenizeToₗ t`;
* `Nikodym.LowerBound.homogenization I`, the homogeneous ideal generated by the homogenizations
  of the elements of `I` (the homogeneous core of `I.comap dehom`);
* the monomial bijection `dehom_homogenizeTo`, `homogenizeTo_dehom`, packaged as the linear
  isomorphism `dehomEquiv t : P̂_t ≃ₗ[K] P_{≤t}`;
* `mem_homogenization_iff`, `homogenizeTo_mem_homogenization_iff`, `map_dehom_homogenization`,
  `homogenization_mono`, `homogenization_injective`, `homogenization_isPrime`,
  `X_zero_notMem_homogenization`, `homogenization_ne_top`;
* `homHilbert_homogenization : homHilbert (homogenization I) t = hilbert I t`;
* `ker_dehom`, `comap_dehom_eq`, and `quotDim_homogenization : quotDim (homogenization I) =
  quotDim I + 1` for a prime `I`.
-/

namespace Nikodym.LowerBound

open MvPolynomial Module

attribute [local instance] MvPolynomial.gradedAlgebra

variable {K : Type*} [Field K] {d : ℕ}

/-! ### Exponent bookkeeping -/

section Finsupp

/-- Blueprint A05: the degree of `Finsupp.cons y s` is `y + s.degree`. -/
theorem degree_cons {n : ℕ} (y : ℕ) (s : Fin n →₀ ℕ) :
    (Finsupp.cons y s).degree = y + s.degree := by
  rw [Finsupp.degree_eq_sum, Finsupp.degree_eq_sum, Fin.sum_univ_succ, Finsupp.cons_zero]
  simp only [Finsupp.cons_succ]

/-- Blueprint A05: `β.degree = β 0 + β.tail.degree`. -/
theorem degree_eq_zero_add_degree_tail {n : ℕ} (β : Fin (n + 1) →₀ ℕ) :
    β.degree = β 0 + β.tail.degree := by
  conv_lhs => rw [← Finsupp.cons_tail β]
  rw [degree_cons]

/-- Blueprint A05: the tail has smaller degree. -/
theorem degree_tail_le {n : ℕ} (β : Fin (n + 1) →₀ ℕ) : β.tail.degree ≤ β.degree := by
  rw [degree_eq_zero_add_degree_tail β]
  exact Nat.le_add_left _ _

end Finsupp

/-! ### Dehomogenization -/

section Dehom

/-- Blueprint A05: the dehomogenization `X₀ ↦ 1`, `X_{i+1} ↦ Xᵢ`. -/
noncomputable def dehom : MvPolynomial (Fin (d + 1)) K →ₐ[K] MvPolynomial (Fin d) K :=
  aeval (Fin.cases 1 X)

@[simp]
theorem dehom_X_zero : dehom (X 0 : MvPolynomial (Fin (d + 1)) K) = 1 := by
  simp [dehom]

@[simp]
theorem dehom_X_succ (i : Fin d) : dehom (X i.succ : MvPolynomial (Fin (d + 1)) K) = X i := by
  simp [dehom]


theorem dehom_C (a : K) : dehom (C a : MvPolynomial (Fin (d + 1)) K) = C a := by
  simp [dehom, algebraMap_eq]

/-- Blueprint A05: `dehom` on monomials drops the exponent of `X₀`. -/
theorem dehom_monomial (β : Fin (d + 1) →₀ ℕ) (c : K) :
    dehom (monomial β c) = monomial β.tail c := by
  rw [dehom, aeval_monomial, monomial_eq, algebraMap_eq]
  congr 1
  rw [Finsupp.prod_fintype _ _ (fun _ ↦ pow_zero _), Finsupp.prod_fintype _ _ (fun _ ↦ pow_zero _),
    Fin.prod_univ_succ]
  simp [Finsupp.tail_apply]

/-- Blueprint A05: `dehom (rename Fin.succ F) = F`. -/
theorem dehom_rename_succ (F : MvPolynomial (Fin d) K) : dehom (rename Fin.succ F) = F := by
  rw [dehom, aeval_rename]
  have : (Fin.cases 1 X ∘ Fin.succ : Fin d → MvPolynomial (Fin d) K) = X := by
    funext i
    simp
  rw [this, aeval_X_left_apply]

/-- Blueprint A05: `dehom` is surjective. -/
theorem dehom_surjective : Function.Surjective (dehom : MvPolynomial (Fin (d + 1)) K →ₐ[K] _) :=
  fun F ↦ ⟨rename Fin.succ F, dehom_rename_succ F⟩

/-- Blueprint A05: `dehom` maps forms of degree `t` into `P_{≤t}`. -/
theorem dehom_mem_restrictTotalDegree {t : ℕ} {G : MvPolynomial (Fin (d + 1)) K}
    (hG : G.IsHomogeneous t) : dehom G ∈ restrictTotalDegree (Fin d) K t := by
  rw [G.as_sum, map_sum]
  refine Submodule.sum_mem _ fun β hβ ↦ ?_
  rw [dehom_monomial]
  exact monomial_mem_restrictTotalDegree
    ((degree_tail_le β).trans (degree_eq_of_isHomogeneous hG hβ).le) _

end Dehom

/-! ### Homogenization of polynomials -/

section HomogenizeTo

/-- Blueprint A05: the homogenization of `F` to degree `t`: each monomial `X^α` is multiplied by
`X₀^(t - |α|)`. -/
noncomputable def homogenizeTo (t : ℕ) (F : MvPolynomial (Fin d) K) :
    MvPolynomial (Fin (d + 1)) K :=
  ∑ α ∈ F.support, monomial (Finsupp.cons (t - α.degree) α) (F.coeff α)

theorem homogenizeTo_eq_sum (t : ℕ) (F : MvPolynomial (Fin d) K) :
    homogenizeTo t F =
      (AddMonoidAlgebra.coeff F).sum fun α c ↦ monomial (Finsupp.cons (t - α.degree) α) c :=
  sum_def.symm

theorem homogenizeTo_add (t : ℕ) (F G : MvPolynomial (Fin d) K) :
    homogenizeTo t (F + G) = homogenizeTo t F + homogenizeTo t G := by
  simp only [homogenizeTo_eq_sum, AddMonoidAlgebra.coeff_add]
  refine Finsupp.sum_add_index' ?_ ?_
  · intro α
    exact map_zero _
  · intro α b₁ b₂
    exact map_add _ _ _

theorem homogenizeTo_smul (t : ℕ) (a : K) (F : MvPolynomial (Fin d) K) :
    homogenizeTo t (a • F) = a • homogenizeTo t F := by
  simp only [homogenizeTo_eq_sum, AddMonoidAlgebra.coeff_smul]
  rw [Finsupp.sum_smul_index' (fun _ ↦ map_zero _), Finsupp.smul_sum]
  simp only [smul_monomial]

@[simp]
theorem homogenizeTo_monomial (t : ℕ) (α : Fin d →₀ ℕ) (c : K) :
    homogenizeTo t (monomial α c) = monomial (Finsupp.cons (t - α.degree) α) c := by
  rw [homogenizeTo_eq_sum, ← single_eq_monomial, AddMonoidAlgebra.coeff_single]
  exact Finsupp.sum_single_index (map_zero _)

/-- Blueprint A05: `homogenizeTo t` as a `K`-linear map. -/
noncomputable def homogenizeToₗ (t : ℕ) :
    MvPolynomial (Fin d) K →ₗ[K] MvPolynomial (Fin (d + 1)) K where
  toFun := homogenizeTo t
  map_add' := homogenizeTo_add t
  map_smul' := homogenizeTo_smul t

@[simp]
theorem homogenizeToₗ_apply (t : ℕ) (F : MvPolynomial (Fin d) K) :
    homogenizeToₗ t F = homogenizeTo t F :=
  rfl

/-- Blueprint A05: `dehom ∘ homogenizeTo t = id` (for every `F`; the degree hypothesis of the
blueprint is not needed). -/
theorem dehom_homogenizeTo (t : ℕ) (F : MvPolynomial (Fin d) K) :
    dehom (homogenizeTo t F) = F := by
  rw [homogenizeTo, map_sum]
  simp only [dehom_monomial, Finsupp.tail_cons]
  exact F.as_sum.symm

/-- Blueprint A05: the homogenization to degree `t` of a polynomial of degree `≤ t` is a form of
degree `t`. -/
theorem isHomogeneous_homogenizeTo {t : ℕ} {F : MvPolynomial (Fin d) K}
    (hF : F.totalDegree ≤ t) : (homogenizeTo t F).IsHomogeneous t := by
  refine IsHomogeneous.sum _ _ _ fun α hα ↦ isHomogeneous_monomial _ ?_
  have h1 : α.degree ≤ F.totalDegree := le_totalDegree hα
  rw [degree_cons]
  omega

/-- Blueprint A05: `homogenizeTo t ∘ dehom = id` on forms of degree `t`. -/
theorem homogenizeTo_dehom {t : ℕ} {G : MvPolynomial (Fin (d + 1)) K} (hG : G.IsHomogeneous t) :
    homogenizeTo t (dehom G) = G := by
  conv_lhs => rw [G.as_sum, map_sum, ← homogenizeToₗ_apply, map_sum]
  conv_rhs => rw [G.as_sum]
  refine Finset.sum_congr rfl fun β hβ ↦ ?_
  rw [homogenizeToₗ_apply, dehom_monomial, homogenizeTo_monomial]
  have h1 := degree_eq_of_isHomogeneous hG hβ
  have h2 := degree_eq_zero_add_degree_tail β
  have h3 : t - β.tail.degree = β 0 := by omega
  rw [h3, Finsupp.cons_tail]

/-- Blueprint A05: the monomial bijection between forms of degree `t` in `d + 1` variables and
polynomials of degree `≤ t` in `d` variables, as a `K`-linear isomorphism `P̂_t ≃ P_{≤t}` given
by `dehom` (inverse `homogenizeTo t`). -/
noncomputable def dehomEquiv (t : ℕ) :
    homogeneousSubmodule (Fin (d + 1)) K t ≃ₗ[K] restrictTotalDegree (Fin d) K t :=
  LinearEquiv.ofLinearMap
    ((dehom : MvPolynomial (Fin (d + 1)) K →ₐ[K] MvPolynomial (Fin d) K).toLinearMap.restrict
      fun G hG ↦ show dehom.toLinearMap G ∈ restrictTotalDegree (Fin d) K t from
        dehom_mem_restrictTotalDegree ((mem_homogeneousSubmodule _ _).mp hG))
    ((homogenizeToₗ t).restrict
      fun F hF ↦ show homogenizeToₗ t F ∈ homogeneousSubmodule (Fin (d + 1)) K t from
        (mem_homogeneousSubmodule _ _).mpr
          (isHomogeneous_homogenizeTo (mem_restrictTotalDegree_iff.mp hF)))
    (LinearMap.ext fun F ↦ Subtype.ext (by
      rw [LinearMap.comp_apply, LinearMap.restrict_apply, LinearMap.restrict_apply,
        LinearMap.id_apply, Subtype.coe_mk, Subtype.coe_mk, AlgHom.toLinearMap_apply,
        homogenizeToₗ_apply]
      exact dehom_homogenizeTo t F.1))
    (LinearMap.ext fun G ↦ Subtype.ext (by
      rw [LinearMap.comp_apply, LinearMap.restrict_apply, LinearMap.restrict_apply,
        LinearMap.id_apply, Subtype.coe_mk, Subtype.coe_mk, AlgHom.toLinearMap_apply,
        homogenizeToₗ_apply]
      exact homogenizeTo_dehom ((mem_homogeneousSubmodule _ _).mp G.2)))

@[simp]
theorem coe_dehomEquiv_apply (t : ℕ) (G : homogeneousSubmodule (Fin (d + 1)) K t) :
    (dehomEquiv t G : MvPolynomial (Fin d) K) = dehom G :=
  rfl

@[simp]
theorem coe_dehomEquiv_symm_apply (t : ℕ) (F : restrictTotalDegree (Fin d) K t) :
    ((dehomEquiv t).symm F : MvPolynomial (Fin (d + 1)) K) = homogenizeTo t F :=
  rfl

end HomogenizeTo

/-! ### Homogenization of ideals -/

section Homogenization

/-- Blueprint A05: the homogenization `Iʰ` of an ideal `I ⊆ P`: the largest homogeneous ideal of
`P̂` contained in `I.comap dehom`, i.e. the ideal generated by the homogenizations of the elements
of `I`. -/
noncomputable def homogenization (I : Ideal (MvPolynomial (Fin d) K)) :
    Ideal (MvPolynomial (Fin (d + 1)) K) :=
  ((I.comap dehom).homogeneousCore (homogeneousSubmodule (Fin (d + 1)) K)).toIdeal

variable (I : Ideal (MvPolynomial (Fin d) K))

/-- Blueprint A05: `Iʰ` is a homogeneous ideal. -/
theorem homogenization_isHomogeneous :
    (homogenization I).IsHomogeneous (homogeneousSubmodule (Fin (d + 1)) K) :=
  HomogeneousIdeal.isHomogeneous _

/-- Blueprint A05: `Iʰ ≤ dehom⁻¹(I)`. -/
theorem homogenization_le_comap : homogenization I ≤ I.comap dehom :=
  Ideal.toIdeal_homogeneousCore_le _ _

/-- Blueprint A05: `dehom G ∈ I` for `G ∈ Iʰ`. -/
theorem dehom_mem_of_mem_homogenization {G : MvPolynomial (Fin (d + 1)) K}
    (hG : G ∈ homogenization I) : dehom G ∈ I :=
  homogenization_le_comap I hG

variable {I}

/-- Blueprint A05: a form `G` lies in `Iʰ` iff `dehom G ∈ I`. -/
theorem mem_homogenization_iff {t : ℕ} {G : MvPolynomial (Fin (d + 1)) K} (hG : G.IsHomogeneous t)
    (I : Ideal (MvPolynomial (Fin d) K)) : G ∈ homogenization I ↔ dehom G ∈ I :=
  ⟨dehom_mem_of_mem_homogenization I, fun h ↦
    Ideal.mem_homogeneousCore_of_homogeneous_of_mem ⟨t, hG⟩ (Ideal.mem_comap.mpr h)⟩

/-- Blueprint A05: for `deg F ≤ t`, `homogenizeTo t F ∈ Iʰ` iff `F ∈ I`. -/
theorem homogenizeTo_mem_homogenization_iff {t : ℕ} {F : MvPolynomial (Fin d) K}
    (hF : F.totalDegree ≤ t) (I : Ideal (MvPolynomial (Fin d) K)) :
    homogenizeTo t F ∈ homogenization I ↔ F ∈ I := by
  rw [mem_homogenization_iff (isHomogeneous_homogenizeTo hF), dehom_homogenizeTo]

variable (I)

/-- Blueprint A05: the homogenization of `F` (to its own degree) lies in `Iʰ` when `F ∈ I`. -/
theorem homogenizeTo_mem_homogenization {F : MvPolynomial (Fin d) K} (hF : F ∈ I) :
    homogenizeTo F.totalDegree F ∈ homogenization I :=
  (homogenizeTo_mem_homogenization_iff le_rfl I).mpr hF

/-- Blueprint A05: `dehom (Iʰ) = I`. -/
theorem map_dehom_homogenization : (homogenization I).map dehom = I := by
  apply le_antisymm
  · exact Ideal.map_le_iff_le_comap.mpr (homogenization_le_comap I)
  · intro F hF
    have h := Ideal.mem_map_of_mem dehom (homogenizeTo_mem_homogenization I hF)
    rwa [dehom_homogenizeTo] at h

/-- Blueprint A05: homogenization is monotone. -/
theorem homogenization_mono : Monotone (homogenization (K := K) (d := d)) := fun _ _ h ↦
  Ideal.homogeneousCore_mono _ (Ideal.comap_mono h)

/-- Blueprint A05: homogenization is injective. -/
theorem homogenization_injective : Function.Injective (homogenization (K := K) (d := d)) := by
  intro I J h
  rw [← map_dehom_homogenization I, ← map_dehom_homogenization J, h]

/-- Blueprint A05: the homogenization of a prime ideal is prime. -/
instance homogenization_isPrime [I.IsPrime] : (homogenization I).IsPrime :=
  Ideal.IsPrime.homogeneousCore (Ideal.IsPrime.comap dehom)

/-- Blueprint A05: `X₀ ∉ Iʰ` for a proper ideal `I`. -/
theorem X_zero_notMem_homogenization (hI : I ≠ ⊤) : X 0 ∉ homogenization I := by
  rw [mem_homogenization_iff (isHomogeneous_X K 0), dehom_X_zero]
  exact fun h ↦ hI ((Ideal.eq_top_iff_one I).mpr h)

/-- Blueprint A05: `Iʰ` is proper for a proper ideal `I`. -/
theorem homogenization_ne_top (hI : I ≠ ⊤) : homogenization I ≠ ⊤ := by
  intro h
  apply hI
  rw [← map_dehom_homogenization I, h, Ideal.map_top]

/-- Blueprint A05: the homogenization of the unit ideal is the unit ideal. -/
theorem homogenization_top : homogenization (⊤ : Ideal (MvPolynomial (Fin d) K)) = ⊤ :=
  (Ideal.eq_top_iff_one _).mpr
    ((mem_homogenization_iff (isHomogeneous_one _ _) ⊤).mpr Submodule.mem_top)

end Homogenization

/-! ### The Hilbert functions agree -/

section HilbertFunction

variable (I : Ideal (MvPolynomial (Fin d) K))

/-- Blueprint A05: under `dehomEquiv t : P̂_t ≃ P_{≤t}`, the degree-`t` piece `Iʰ ⊓ P̂_t` (as a
subspace of `P̂_t`) corresponds to `I ⊓ P_{≤t}` (as a subspace of `P_{≤t}`). -/
theorem map_dehomEquiv_comap_homogenization (t : ℕ) :
    (((homogenization I).restrictScalars K).comap
        (homogeneousSubmodule (Fin (d + 1)) K t).subtype).map (dehomEquiv t).toLinearMap =
      (I.restrictScalars K).comap (restrictTotalDegree (Fin d) K t).subtype := by
  rw [Submodule.map_equiv_eq_comap_symm]
  ext F
  simp only [Submodule.mem_comap, Submodule.restrictScalars_mem, Submodule.subtype_apply,
    LinearEquiv.coe_coe, coe_dehomEquiv_symm_apply]
  exact homogenizeTo_mem_homogenization_iff (mem_restrictTotalDegree_iff.mp F.2) I

/-- Blueprint A05: **the homogeneous Hilbert function of `Iʰ` is the affine Hilbert function of
`I`**: `homHilbert (homogenization I) t = hilbert I t`. -/
theorem homHilbert_homogenization (t : ℕ) : homHilbert (homogenization I) t = hilbert I t := by
  have h1 := homHilbert_add_finrank_comap_subtype (homogenization I) t
  have h2 := finrank_map_mkₐ_add_finrank_comap_subtype I (restrictTotalDegree (Fin d) K t)
  have h3 : finrank K (homogeneousSubmodule (Fin (d + 1)) K t) =
      finrank K (restrictTotalDegree (Fin d) K t) :=
    (dehomEquiv t).finrank_eq
  have h4 : finrank K (((homogenization I).restrictScalars K).comap
        (homogeneousSubmodule (Fin (d + 1)) K t).subtype) =
      finrank K ((I.restrictScalars K).comap (restrictTotalDegree (Fin d) K t).subtype) := by
    rw [← map_dehomEquiv_comap_homogenization I t, LinearEquiv.finrank_map_eq]
  change _ = finrank K ((restrictTotalDegree (Fin d) K t).map (Ideal.Quotient.mkₐ K I).toLinearMap)
  omega

end HilbertFunction

/-! ### The kernel of `dehom` and the dimension of `Iʰ` -/

section Dimension

/-- Blueprint A05: `dehom` is evaluation at `X₀ = 1` after `finSuccEquiv`. -/
theorem dehom_eq_evalRingHom_comp_finSuccEquiv :
    (dehom (K := K) (d := d)).toRingHom =
      (Polynomial.evalRingHom (1 : MvPolynomial (Fin d) K)).comp
        (finSuccEquiv K d :
          MvPolynomial (Fin (d + 1)) K →+* Polynomial (MvPolynomial (Fin d) K)) := by
  apply ringHom_ext
  · intro a
    simp only [RingHom.comp_apply, AlgHom.toRingHom_eq_coe, dehom_C, RingHom.coe_coe,
      Polynomial.coe_evalRingHom]
    rw [← algebraMap_eq, ← algebraMap_eq, AlgEquiv.commutes, Polynomial.algebraMap_apply,
      Polynomial.eval_C]
  · intro i
    refine Fin.cases ?_ (fun j ↦ ?_) i
    · simp [finSuccEquiv_X_zero]
    · simp [finSuccEquiv_X_succ]

/-- Blueprint A05: `ker dehom = (X₀ - 1)`. -/
theorem ker_dehom :
    RingHom.ker (dehom : MvPolynomial (Fin (d + 1)) K →ₐ[K] MvPolynomial (Fin d) K) =
      Ideal.span {X 0 - 1} := by
  have h : RingHom.ker (dehom : MvPolynomial (Fin (d + 1)) K →ₐ[K] MvPolynomial (Fin d) K) =
      RingHom.ker (dehom (K := K) (d := d)).toRingHom := rfl
  rw [h, dehom_eq_evalRingHom_comp_finSuccEquiv, ← RingHom.comap_ker, Polynomial.ker_evalRingHom]
  change Ideal.comap (finSuccEquiv K d).toRingEquiv _ = _
  rw [← Ideal.map_symm (finSuccEquiv K d).toRingEquiv, Ideal.map_span, Set.image_singleton]
  congr 2
  apply (finSuccEquiv K d).toRingEquiv.injective
  rw [RingEquiv.apply_symm_apply]
  simp [finSuccEquiv_X_zero]

/-- Blueprint A05: `dehom⁻¹(I) = Iʰ + (X₀ - 1)`. -/
theorem comap_dehom_eq (I : Ideal (MvPolynomial (Fin d) K)) :
    I.comap dehom = homogenization I ⊔ Ideal.span {X 0 - 1} := by
  apply le_antisymm
  · intro G hG
    rw [Ideal.mem_comap] at hG
    have h1 : homogenizeTo (dehom G).totalDegree (dehom G) ∈ homogenization I :=
      homogenizeTo_mem_homogenization I hG
    have h2 : G - homogenizeTo (dehom G).totalDegree (dehom G) ∈ Ideal.span {X 0 - 1} := by
      rw [← ker_dehom, RingHom.mem_ker, map_sub, dehom_homogenizeTo, sub_self]
    have := Submodule.add_mem_sup h1 h2
    rwa [add_sub_cancel] at this
  · refine sup_le (homogenization_le_comap I) ?_
    rw [← ker_dehom]
    intro G hG
    rw [RingHom.mem_ker] at hG
    rw [Ideal.mem_comap, hG]
    exact I.zero_mem

/-- Blueprint A05: `P̂ ⧸ dehom⁻¹(I) ≃ P ⧸ I`. -/
noncomputable def quotientComapDehomEquiv (I : Ideal (MvPolynomial (Fin d) K)) :
    (MvPolynomial (Fin (d + 1)) K ⧸ I.comap dehom) ≃ₐ[K] MvPolynomial (Fin d) K ⧸ I :=
  (Ideal.quotientEquivAlgOfEq K (by
      ext G
      simp [RingHom.mem_ker, Ideal.Quotient.eq_zero_iff_mem])).trans
    (Ideal.quotientKerAlgEquivOfSurjective (f := (Ideal.Quotient.mkₐ K I).comp dehom)
      (Ideal.Quotient.mkₐ_surjective K I |>.comp dehom_surjective))

/-- Blueprint A05: for a prime `I`, `dim (P̂ ⧸ Iʰ) = dim (P ⧸ I) + 1`: the class of `X₀ - 1` is
a nonzero element of the domain `P̂ ⧸ Iʰ` generating the prime `dehom⁻¹(I) / Iʰ`, which is the
unique minimal prime over it, so A01 applies. -/
theorem ringKrullDim_quotient_homogenization (I : Ideal (MvPolynomial (Fin d) K)) [I.IsPrime] :
    ringKrullDim (MvPolynomial (Fin (d + 1)) K ⧸ homogenization I) =
      ringKrullDim (MvPolynomial (Fin d) K ⧸ I) + 1 := by
  have hI : I ≠ ⊤ := Ideal.IsPrime.ne_top'
  have hf : Ideal.Quotient.mk (homogenization I) (X 0 - 1) ≠ 0 := by
    rw [Ne, Ideal.Quotient.eq_zero_iff_mem]
    intro h
    exact homogenization_ne_top I hI ((Ideal.eq_top_iff_one _).mpr
      (one_mem_of_isHomogeneous_of_X_sub_one_mem (homogenization_isHomogeneous I) h))
  have hQ : (I.comap dehom).map (Ideal.Quotient.mk (homogenization I)) =
      Ideal.span {Ideal.Quotient.mk (homogenization I) (X 0 - 1)} := by
    rw [comap_dehom_eq, Ideal.map_sup, Ideal.map_quotient_self, bot_sup_eq, Ideal.map_span,
      Set.image_singleton]
  have : ((I.comap dehom).map (Ideal.Quotient.mk (homogenization I))).IsPrime :=
    Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective
      (by rw [Ideal.mk_ker]; exact homogenization_le_comap I)
  have hmin : (I.comap dehom).map (Ideal.Quotient.mk (homogenization I)) ∈
      (Ideal.span {Ideal.Quotient.mk (homogenization I) (X 0 - 1)}).minimalPrimes := by
    rw [← hQ, Ideal.minimalPrimes_eq_subsingleton_self]
    exact Set.mem_singleton _
  have h := ringKrullDim_quotient_add_one_of_mem_minimalPrimes K hf hmin
  rw [ringKrullDim_eq_of_ringEquiv (DoubleQuot.quotQuotEquivQuotOfLE (homogenization_le_comap I)),
    ringKrullDim_eq_of_ringEquiv (quotientComapDehomEquiv I).toRingEquiv] at h
  exact h.symm

/-- Blueprint A05: **`quotDim (homogenization I) = quotDim I + 1`** for a prime `I`. -/
theorem quotDim_homogenization (I : Ideal (MvPolynomial (Fin d) K)) [I.IsPrime] :
    quotDim (homogenization I) = quotDim I + 1 := by
  have h := ringKrullDim_quotient_homogenization I
  rw [← coe_quotDim _ (homogenization_ne_top I Ideal.IsPrime.ne_top'),
    ← coe_quotDim I Ideal.IsPrime.ne_top'] at h
  exact_mod_cast h

end Dimension

end Nikodym.LowerBound

/- Adapted for Lean Pool: module imports and compatibility with its pinned toolchain. -/
