/-
Copyright (c) 2026 Shengtong Zhang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Shengtong Zhang
-/

import LeanPool.Nikodym.Nikodym.LowerBound.Algebra.DimensionExtra

/-!
# Linear Noether normalization of a standard graded algebra

This file implements blueprint node **A02** of the algebra backend. Throughout,
`Q := MvPolynomial (Fin n) K` is the polynomial ring in `n` variables over a field `K`,
`𝔪ₙ := idealOfVars (Fin n) K` is the ideal generated by the variables, and `J` is a homogeneous
ideal of `Q` with respect to the standard grading `homogeneousSubmodule (Fin n) K`.

## Main declarations

* `exists_linear_normalization`: for `K` infinite and `J ≠ ⊤` homogeneous, there are
  `quotDim J` linear forms `y i` such that `MvPolynomial.aeval (mk J ∘ y)` is injective and
  `𝔪ₙ ^ N ≤ J ⊔ span (range y)` for some `N`.
* `exists_eq_add_sum_mul_of_pow_idealOfVars_le` (graded refinement of `𝔪ₙ ^ N ≤ J ⊔ (y)`): every
  form `F` of degree `t ≥ N` is `G + ∑ i, y i * H i` with `G ∈ J` and `H i` forms of degree `t - 1`.
* `span_image_mk_eq_top_of_pow_idealOfVars_le`, `finite_of_pow_idealOfVars_le'`,
  `finite_of_pow_idealOfVars_le`: graded Nakayama / module-finiteness of `Q ⧸ J` over
  `MvPolynomial (Fin s) K` acting through `y`, with the explicit generating set of classes of
  forms of degree `< N`.

## Sub-lemmas (blueprint A02.a–A02.h)

* A02.a `exists_linear_form_notMem`: a linear form outside finitely many ideals not containing `𝔪ₙ`.
* A02.b `le_idealOfVars_of_isHomogeneous_of_ne_top`, `quotDim_idealOfVars`,
  `eq_idealOfVars_of_quotDim_eq_zero`.
* A02.c `IsHomogeneous.minimalPrimes_isHomogeneous`: minimal primes of a homogeneous ideal are
  homogeneous (in any graded ring).
* A02.d `quotDim_sup_span_singleton_lt`: adding a linear form avoiding the minimal primes other
  than `𝔪ₙ` drops `quotDim`.
* A02.e `exists_linear_forms_quotDim_sup_eq_zero`: iterating A02.d.
* A02.f `pow_idealOfVars_le_of_quotDim_eq_zero`: `quotDim J = 0` gives `𝔪ₙ ^ N ≤ J`.
* A02.g `aeval_injective_of_pow_idealOfVars_le`: injectivity from dimension counting.
* A02.h the finiteness statements above.

## Conventions

Mathlib's graded-ring structure on `MvPolynomial` is a local instance
(`attribute [local instance] MvPolynomial.gradedAlgebra`); statements mention the grading
explicitly as `homogeneousSubmodule (Fin n) K`. The algebra structure of `Q ⧸ J` over
`MvPolynomial (Fin s) K` is never a global instance: the finiteness theorems take it either as an
instance argument together with the hypothesis
`algebraMap _ _ = (MvPolynomial.aeval fun i ↦ Ideal.Quotient.mk J (y i)).toRingHom`
(`finite_of_pow_idealOfVars_le'`), or install it with `letI` in the statement
(`finite_of_pow_idealOfVars_le`).
-/

namespace Nikodym.LowerBound

open MvPolynomial Ideal

attribute [local instance] MvPolynomial.gradedAlgebra

/-! ### A02.c: minimal primes of a homogeneous ideal are homogeneous (general graded rings) -/

section GradedRing

variable {ι σ A : Type*} [CommRing A] [AddCommMonoid ι] [LinearOrder ι]
  [IsOrderedCancelAddMonoid ι] [SetLike σ A] [AddSubmonoidClass σ A] (𝒜 : ι → σ) [GradedRing 𝒜]

/-- Blueprint A02.c: **the minimal primes of a homogeneous ideal are homogeneous.** For
`q ∈ J.minimalPrimes`, the homogeneous core of `q` is a prime containing `J` and contained in `q`,
hence equal to `q` by minimality. -/
theorem IsHomogeneous.minimalPrimes_isHomogeneous {J : Ideal A} (hJ : J.IsHomogeneous 𝒜)
    {q : Ideal A} (hq : q ∈ J.minimalPrimes) : q.IsHomogeneous 𝒜 := by
  have hprime : (q.homogeneousCore 𝒜).toIdeal.IsPrime := hq.1.1.homogeneousCore
  have hJq : J ≤ (q.homogeneousCore 𝒜).toIdeal :=
    hJ.toIdeal_homogeneousCore_eq_self.symm.trans_le (Ideal.homogeneousCore_mono 𝒜 hq.1.2)
  have heq : (q.homogeneousCore 𝒜).toIdeal = q :=
    le_antisymm (Ideal.toIdeal_homogeneousCore_le 𝒜 q)
      (hq.2 ⟨hprime, hJq⟩ (Ideal.toIdeal_homogeneousCore_le 𝒜 q))
  rw [← heq]
  exact (q.homogeneousCore 𝒜).isHomogeneous

end GradedRing

/-! ### Homogeneous components of products with a form -/

section Components

variable {σ R : Type*} [CommSemiring R]

/-- Blueprint A02.h, auxiliary: a form of degree `t` lies in `𝔪 ^ t`. -/
theorem IsHomogeneous.mem_pow_idealOfVars {F : MvPolynomial σ R} {t : ℕ} (hF : F.IsHomogeneous t) :
    F ∈ idealOfVars σ R ^ t := by
  rw [mem_pow_idealOfVars_iff]
  intro x hx
  rw [mem_support_iff] at hx
  rw [Finsupp.degree_eq_weight_one]
  exact (hF hx).ge

/-- Blueprint A02.h, auxiliary: the degree-`(m + e)` component of `c * y`, for a form `y` of
degree `e`, is `(c)_m * y`. (Named with the suffix `_right` to avoid a clash with the
field-specific `homogeneousComponent_mul_of_isHomogeneous` of `GradedLemmas.lean`, whose primed
variant has the same content; this version holds over any commutative semiring.) -/
theorem homogeneousComponent_mul_of_isHomogeneous_right {y : MvPolynomial σ R} {e : ℕ}
    (hy : y.IsHomogeneous e) (c : MvPolynomial σ R) (m : ℕ) :
    homogeneousComponent (m + e) (c * y) = homogeneousComponent m c * y := by
  classical
  ext d
  rw [coeff_homogeneousComponent, coeff_mul, coeff_mul]
  have key : ∀ x ∈ Finset.HasAntidiagonal.antidiagonal d, coeff x.2 y ≠ 0 →
      (d.degree = m + e ↔ x.1.degree = m) := by
    intro x hx hb
    have hx2 : x.2.degree = e := by
      rw [Finsupp.degree_eq_weight_one]
      exact hy hb
    rw [Finset.HasAntidiagonal.mem_antidiagonal] at hx
    have hsum := congrArg Finsupp.degree hx
    rw [map_add, hx2] at hsum
    omega
  split_ifs with hd
  · refine Finset.sum_congr rfl fun x hx ↦ ?_
    rw [coeff_homogeneousComponent]
    by_cases hb : coeff x.2 y = 0
    · simp [hb]
    · rw [if_pos ((key x hx hb).mp hd)]
  · symm
    refine Finset.sum_eq_zero fun x hx ↦ ?_
    rw [coeff_homogeneousComponent]
    by_cases hb : coeff x.2 y = 0
    · simp [hb]
    · rw [if_neg (fun h ↦ hd ((key x hx hb).mpr h)), zero_mul]

end Components

/-! ### The polynomial ring in `n` variables -/

section LinearNormalization

variable {K : Type*} [Field K] {n : ℕ}

/-! #### A02.b: proper homogeneous ideals lie in `𝔪ₙ` -/

/-- Blueprint A02.b: `𝔪ₙ` is a prime ideal. -/
theorem idealOfVars_isPrime : (idealOfVars (Fin n) K).IsPrime :=
  idealOfVars_isMaximal.isPrime

/-- Blueprint A02.b: `quotDim 𝔪ₙ = 0`. -/
theorem quotDim_idealOfVars : quotDim (idealOfVars (Fin n) K) = 0 :=
  quotDim_of_ringKrullDim_eq <| by
    rw [ringKrullDim_eq_zero_of_isField
      ((Ideal.Quotient.maximal_ideal_iff_isField_quotient _).mp idealOfVars_isMaximal),
      Nat.cast_zero]

/-- Blueprint A02.b: **a proper homogeneous ideal is contained in `𝔪ₙ`**: the degree-`0` component
of any element is a constant lying in the ideal, hence zero. -/
theorem le_idealOfVars_of_isHomogeneous_of_ne_top {J : Ideal (MvPolynomial (Fin n) K)} (hJ : J ≠ ⊤)
    (hJh : J.IsHomogeneous (homogeneousSubmodule (Fin n) K)) : J ≤ idealOfVars (Fin n) K := by
  intro f hf
  have h0 : homogeneousComponent 0 f ∈ J := homogeneousComponent_mem_of_mem hJh hf 0
  rw [homogeneousComponent_zero] at h0
  have hc : coeff 0 f = 0 := by
    by_contra hne
    exact hJ (J.eq_top_of_isUnit_mem h0 ((isUnit_iff_ne_zero.mpr hne).map C))
  rw [← pow_one (idealOfVars (Fin n) K), mem_pow_idealOfVars_iff']
  intro x hx
  rw [Nat.lt_one_iff, Finsupp.degree_eq_zero_iff] at hx
  subst hx
  exact hc

/-- Blueprint A02.b: a prime `p ≤ 𝔪ₙ` with `quotDim p = 0` equals `𝔪ₙ`. -/
theorem eq_idealOfVars_of_quotDim_eq_zero {p : Ideal (MvPolynomial (Fin n) K)} [p.IsPrime]
    (hp : p ≤ idealOfVars (Fin n) K) (h0 : quotDim p = 0) : p = idealOfVars (Fin n) K := by
  by_contra hne
  haveI := idealOfVars_isPrime (K := K) (n := n)
  have h := quotDim_lt_of_lt (lt_of_le_of_ne hp hne)
  rw [h0, quotDim_idealOfVars] at h
  exact lt_irrefl _ h

/-- Blueprint A02: the ideal generated by linear forms is homogeneous. -/
theorem isHomogeneous_span_range {s : ℕ} {y : Fin s → MvPolynomial (Fin n) K}
    (hy : ∀ i, (y i).IsHomogeneous 1) :
    (Ideal.span (Set.range y)).IsHomogeneous (homogeneousSubmodule (Fin n) K) := by
  refine Ideal.homogeneous_span _ _ ?_
  rintro _ ⟨i, rfl⟩
  exact ⟨1, hy i⟩

/-- Blueprint A02: for a proper homogeneous `J` and linear forms `y`, `J ⊔ (y) ≤ 𝔪ₙ`. -/
theorem sup_span_range_le_idealOfVars {J : Ideal (MvPolynomial (Fin n) K)} (hJ : J ≠ ⊤)
    (hJh : J.IsHomogeneous (homogeneousSubmodule (Fin n) K)) {s : ℕ}
    {y : Fin s → MvPolynomial (Fin n) K} (hy : ∀ i, (y i).IsHomogeneous 1) :
    J ⊔ Ideal.span (Set.range y) ≤ idealOfVars (Fin n) K := by
  refine sup_le (le_idealOfVars_of_isHomogeneous_of_ne_top hJ hJh) (Ideal.span_le.mpr ?_)
  rintro _ ⟨i, rfl⟩
  simpa using IsHomogeneous.mem_pow_idealOfVars (hy i)

/-- Blueprint A02: for a proper homogeneous `J` and linear forms `y`, `J ⊔ (y) ≠ ⊤`. -/
theorem sup_span_range_ne_top {J : Ideal (MvPolynomial (Fin n) K)} (hJ : J ≠ ⊤)
    (hJh : J.IsHomogeneous (homogeneousSubmodule (Fin n) K)) {s : ℕ}
    {y : Fin s → MvPolynomial (Fin n) K} (hy : ∀ i, (y i).IsHomogeneous 1) :
    J ⊔ Ideal.span (Set.range y) ≠ ⊤ :=
  ne_top_of_le_ne_top idealOfVars_isMaximal.ne_top (sup_span_range_le_idealOfVars hJ hJh hy)

/-- Blueprint A02: if `J ⊔ (y) = ⊤` for a homogeneous `J` and linear forms `y`, then `J = ⊤`. -/
theorem eq_top_of_sup_span_range_eq_top {J : Ideal (MvPolynomial (Fin n) K)}
    (hJh : J.IsHomogeneous (homogeneousSubmodule (Fin n) K)) {s : ℕ}
    {y : Fin s → MvPolynomial (Fin n) K} (hy : ∀ i, (y i).IsHomogeneous 1)
    (h : J ⊔ Ideal.span (Set.range y) = ⊤) : J = ⊤ := by
  by_contra hJ
  exact sup_span_range_ne_top hJ hJh hy h

/-! #### A02.a: prime avoidance for linear forms -/

/-- Blueprint A02.a: **a linear form outside finitely many ideals.** If none of the ideals `p i`
(finitely many) contains `𝔪ₙ`, there is a linear form outside all of them. The subspaces
`p i ∩ P_1` of the space `P_1` of linear forms are proper, and a finite union of proper subspaces
over an infinite field is not everything. -/
theorem exists_linear_form_notMem [Infinite K] {ι : Type*} [Finite ι]
    (p : ι → Ideal (MvPolynomial (Fin n) K)) (hp : ∀ i, ¬ idealOfVars (Fin n) K ≤ p i) :
    ∃ y : MvPolynomial (Fin n) K, y.IsHomogeneous 1 ∧ ∀ i, y ∉ p i := by
  let V : ι → Submodule K (homogeneousSubmodule (Fin n) K 1) := fun i ↦
    ((p i).restrictScalars K).comap (homogeneousSubmodule (Fin n) K 1).subtype
  have hV : ∀ i, V i ≠ ⊤ := by
    intro i hi
    apply hp i
    rw [idealOfVars, Ideal.span_le]
    rintro _ ⟨j, rfl⟩
    have hmem : (⟨X j, isHomogeneous_X K j⟩ : homogeneousSubmodule (Fin n) K 1) ∈ V i :=
      hi ▸ Submodule.mem_top
    exact hmem
  obtain ⟨x, hx⟩ := Submodule.exists_forall_notMem_of_forall_ne_top V hV
  exact ⟨x, x.2, fun i hi ↦ hx i hi⟩

/-! #### A02.f: dimension zero forces a power of `𝔪ₙ` -/

/-- Blueprint A02.f: **a proper homogeneous ideal of quotient dimension `0` contains a power of
`𝔪ₙ`.** Its minimal primes are homogeneous (A02.c), proper, hence `≤ 𝔪ₙ`, and of quotient
dimension `0`, hence `= 𝔪ₙ`; so its radical is `𝔪ₙ`, and `𝔪ₙ` is finitely generated. -/
theorem pow_idealOfVars_le_of_quotDim_eq_zero {J : Ideal (MvPolynomial (Fin n) K)}
    (hJh : J.IsHomogeneous (homogeneousSubmodule (Fin n) K)) (h0 : quotDim J = 0) :
    ∃ N : ℕ, idealOfVars (Fin n) K ^ N ≤ J := by
  refine Ideal.exists_pow_le_of_le_radical_of_fg ?_ (idealOfVars_fg _ _)
  rw [← Ideal.sInf_minimalPrimes, le_sInf_iff]
  intro p hp
  haveI := hp.1.1
  have hph := IsHomogeneous.minimalPrimes_isHomogeneous _ hJh hp
  have hpm : p ≤ idealOfVars (Fin n) K :=
    le_idealOfVars_of_isHomogeneous_of_ne_top hp.1.1.ne_top hph
  have hp0 : quotDim p = 0 :=
    Nat.eq_zero_of_le_zero (h0 ▸ quotDim_anti hp.1.2 hp.1.1.ne_top)
  exact (eq_idealOfVars_of_quotDim_eq_zero hpm hp0).ge

/-! #### A02.d, A02.e: cutting down the dimension by linear forms -/

/-- Blueprint A02.d: **a linear form avoiding the minimal primes other than `𝔪ₙ` drops the
dimension.** Every prime `q ⊇ J + (y)` contains a minimal prime `p` of `J`; either `p = 𝔪ₙ = q`
(dimension `0`), or `y ∉ p`, so `p < q` and `quotDim q < quotDim p ≤ quotDim J`. -/
theorem quotDim_sup_span_singleton_lt {J : Ideal (MvPolynomial (Fin n) K)} (hJ : J ≠ ⊤)
    (hJh : J.IsHomogeneous (homogeneousSubmodule (Fin n) K)) (hpos : 1 ≤ quotDim J)
    {y : MvPolynomial (Fin n) K} (hy1 : y.IsHomogeneous 1)
    (hy : ∀ p ∈ J.minimalPrimes, p ≠ idealOfVars (Fin n) K → y ∉ p) :
    quotDim (J ⊔ Ideal.span {y}) < quotDim J := by
  have hJ' : J ⊔ Ideal.span {y} ≠ ⊤ := by
    have h := sup_span_range_ne_top hJ hJh (y := fun _ : Fin 1 ↦ y) (fun _ ↦ hy1)
    rwa [Set.range_const] at h
  have hle : quotDim (J ⊔ Ideal.span {y}) ≤ quotDim J - 1 := by
    refine quotDim_le_of_forall_isPrime (fun q hq hJq ↦ ?_) hJ'
    haveI := hq
    obtain ⟨p, hp, hpq⟩ := Ideal.exists_minimalPrimes_le (le_sup_left.trans hJq)
    haveI := hp.1.1
    by_cases hpm : p = idealOfVars (Fin n) K
    · have hqm : q = idealOfVars (Fin n) K :=
        (idealOfVars_isMaximal.eq_of_le hq.ne_top (hpm ▸ hpq)).symm
      rw [hqm, quotDim_idealOfVars]
      exact Nat.zero_le _
    · have hyq : y ∈ q := hJq (Ideal.mem_sup_right (Ideal.mem_span_singleton_self y))
      have hlt : p < q := lt_of_le_of_ne hpq fun h ↦ hy p hp hpm (h ▸ hyq)
      have h1 := quotDim_lt_of_lt hlt
      have h2 := quotDim_anti hp.1.2 hp.1.1.ne_top
      omega
  omega

/-- Blueprint A02.e: **iterating A02.d.** For `K` infinite and `J ≠ ⊤` homogeneous with
`quotDim J ≤ k`, there are `k` linear forms `y` with `quotDim (J ⊔ (y)) = 0`. -/
theorem exists_linear_forms_quotDim_sup_eq_zero [Infinite K] :
    ∀ (k : ℕ) (J : Ideal (MvPolynomial (Fin n) K)), J ≠ ⊤ →
      J.IsHomogeneous (homogeneousSubmodule (Fin n) K) → quotDim J ≤ k →
      ∃ y : Fin k → MvPolynomial (Fin n) K,
        (∀ i, (y i).IsHomogeneous 1) ∧ quotDim (J ⊔ Ideal.span (Set.range y)) = 0
  | 0, J, _, _, hk => by
    refine ⟨Fin.elim0, fun i ↦ i.elim0, ?_⟩
    rw [Set.range_eq_empty, Ideal.span_empty, sup_bot_eq]
    exact Nat.eq_zero_of_le_zero hk
  | k + 1, J, hJ, hJh, hk => by
    by_cases h0 : quotDim J = 0
    · refine ⟨fun _ ↦ 0, fun _ ↦ isHomogeneous_zero _ _ _, ?_⟩
      rw [Set.range_const, Ideal.span_singleton_zero, sup_bot_eq]
      exact h0
    · have hpos : 1 ≤ quotDim J := Nat.one_le_iff_ne_zero.mpr h0
      set S : Set (Ideal (MvPolynomial (Fin n) K)) :=
        {p | p ∈ J.minimalPrimes ∧ p ≠ idealOfVars (Fin n) K} with hS
      have hfin : S.Finite :=
        (Ideal.finite_minimalPrimes_of_isNoetherianRing _ J).subset fun p hp ↦ hp.1
      haveI := hfin.to_subtype
      obtain ⟨y₀, hy₀1, hy₀⟩ := exists_linear_form_notMem (fun p : S ↦ p.1) fun p hle ↦ by
        haveI := p.2.1.1.1
        have hph := IsHomogeneous.minimalPrimes_isHomogeneous _ hJh p.2.1
        exact p.2.2 (le_antisymm (le_idealOfVars_of_isHomogeneous_of_ne_top p.2.1.1.1.ne_top hph)
          hle)
      have hlt : quotDim (J ⊔ Ideal.span {y₀}) < quotDim J :=
        quotDim_sup_span_singleton_lt hJ hJh hpos hy₀1 fun p hp hpm ↦ hy₀ ⟨p, hp, hpm⟩
      have hJ₁ : J ⊔ Ideal.span {y₀} ≠ ⊤ := by
        have h := sup_span_range_ne_top hJ hJh (y := fun _ : Fin 1 ↦ y₀) (fun _ ↦ hy₀1)
        rwa [Set.range_const] at h
      have hJ₁h : (J ⊔ Ideal.span {y₀}).IsHomogeneous (homogeneousSubmodule (Fin n) K) := by
        have h := hJh.sup (isHomogeneous_span_range (y := fun _ : Fin 1 ↦ y₀) (fun _ ↦ hy₀1))
        rwa [Set.range_const] at h
      obtain ⟨y', hy', h0'⟩ :=
        exists_linear_forms_quotDim_sup_eq_zero k (J ⊔ Ideal.span {y₀}) hJ₁ hJ₁h (by omega)
      refine ⟨Fin.cons y₀ y', fun i ↦ ?_, ?_⟩
      · refine Fin.cases hy₀1 (fun j ↦ ?_) i
        simpa using hy' j
      · rw [Fin.range_cons, Ideal.span_insert, ← sup_assoc]
        exact h0'

/-! #### A02.h: graded Nakayama -/

/-- Blueprint A02.h (graded refinement): **if `𝔪ₙ ^ N ≤ J ⊔ (y)` for linear forms `y`, every form
`F` of degree `t ≥ N` is `G + ∑ i, y i * H i` with `G ∈ J` and `H i` forms of degree `t - 1`.**
Write `F = G₀ + ∑ i, c i * y i` and take degree-`t` components. -/
theorem exists_eq_add_sum_mul_of_pow_idealOfVars_le {J : Ideal (MvPolynomial (Fin n) K)}
    (hJh : J.IsHomogeneous (homogeneousSubmodule (Fin n) K)) {s N : ℕ}
    {y : Fin s → MvPolynomial (Fin n) K} (hy : ∀ i, (y i).IsHomogeneous 1)
    (hN : idealOfVars (Fin n) K ^ N ≤ J ⊔ Ideal.span (Set.range y)) {t : ℕ} (ht : N ≤ t)
    {F : MvPolynomial (Fin n) K} (hF : F.IsHomogeneous t) :
    ∃ (G : MvPolynomial (Fin n) K) (H : Fin s → MvPolynomial (Fin n) K),
      G ∈ J ∧ (∀ i, (H i).IsHomogeneous (t - 1)) ∧ F = G + ∑ i, y i * H i := by
  have hFmem : F ∈ J ⊔ Ideal.span (Set.range y) :=
    hN (Ideal.pow_le_pow_right ht (IsHomogeneous.mem_pow_idealOfVars hF))
  obtain _ | t := t
  · -- degree `0`: then `N = 0`, so `J ⊔ (y) = ⊤` and `J = ⊤`.
    have hN0 : N = 0 := Nat.eq_zero_of_le_zero ht
    subst hN0
    have hJtop : J = ⊤ := eq_top_of_sup_span_range_eq_top hJh hy (top_le_iff.mp (by simpa using hN))
    exact ⟨F, fun _ ↦ 0, hJtop ▸ Submodule.mem_top, fun _ ↦ isHomogeneous_zero _ _ _, by simp⟩
  · obtain ⟨G₀, hG₀, Z, hZ, hFZ⟩ := Submodule.mem_sup.mp hFmem
    obtain ⟨c, rfl⟩ := (Submodule.mem_span_range_iff_exists_fun _).mp hZ
    refine ⟨homogeneousComponent (t + 1) G₀, fun i ↦ homogeneousComponent t (c i),
      homogeneousComponent_mem_of_mem hJh hG₀ _, fun i ↦ homogeneousComponent_isHomogeneous _ _, ?_⟩
    have hsum : ∀ i, homogeneousComponent (t + 1) (c i • y i) =
        y i * homogeneousComponent t (c i) := fun i ↦ by
      rw [smul_eq_mul, homogeneousComponent_mul_of_isHomogeneous_right (hy i), mul_comm]
    calc F = homogeneousComponent (t + 1) F := (homogeneousComponent_eq_self hF).symm
      _ = homogeneousComponent (t + 1) G₀ + ∑ i, homogeneousComponent (t + 1) (c i • y i) := by
        rw [← hFZ, map_add, map_sum]
      _ = _ := by simp_rw [hsum]

-- synthesizing `Module (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J)` from the `Algebra`
-- instance first explores `Submodule.Quotient.module'` and needs about `40000` heartbeats
/-- Blueprint A02.h: **graded Nakayama, spanning set.** Let `S := MvPolynomial (Fin s) K` act on
`Q ⧸ J` through `X i ↦ mk J (y i)` (an arbitrary algebra structure with this `algebraMap`). If
`𝔪ₙ ^ N ≤ J ⊔ (y)`, then `Q ⧸ J` is spanned over `S` by the classes of finitely many forms of
degree `< N` (the monomials of degree `< N`). -/
theorem span_image_mk_eq_top_of_pow_idealOfVars_le {J : Ideal (MvPolynomial (Fin n) K)}
    (hJh : J.IsHomogeneous (homogeneousSubmodule (Fin n) K)) {s N : ℕ}
    {y : Fin s → MvPolynomial (Fin n) K} (hy : ∀ i, (y i).IsHomogeneous 1)
    (hN : idealOfVars (Fin n) K ^ N ≤ J ⊔ Ideal.span (Set.range y))
    [Algebra (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J)]
    (halg : algebraMap (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J) =
      (MvPolynomial.aeval fun i ↦ Ideal.Quotient.mk J (y i)).toRingHom) :
    ∃ gens : Finset (MvPolynomial (Fin n) K), (∀ g ∈ gens, ∃ u < N, g.IsHomogeneous u) ∧
      Submodule.span (MvPolynomial (Fin s) K) (Ideal.Quotient.mk J '' gens) = ⊤ := by
  classical
  set gens : Finset (MvPolynomial (Fin n) K) :=
    ((exponentsLE n N).filter fun α ↦ α.degree < N).image fun α ↦ monomial α (1 : K) with hgens
  refine ⟨gens, fun g hg ↦ ?_, ?_⟩
  · rw [hgens, Finset.mem_image] at hg
    obtain ⟨α, hα, rfl⟩ := hg
    rw [Finset.mem_filter] at hα
    exact ⟨α.degree, hα.2, isHomogeneous_monomial _ rfl⟩
  set M := Submodule.span (MvPolynomial (Fin s) K) (Ideal.Quotient.mk J '' gens) with hM
  have hX : ∀ i, algebraMap (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J) (X i) =
      Ideal.Quotient.mk J (y i) := fun i ↦ by
    rw [halg, AlgHom.toRingHom_eq_coe, RingHom.coe_coe, aeval_X]
  have hC : ∀ a : K, algebraMap (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J) (C a) =
      Ideal.Quotient.mk J (C a) := fun a ↦ by
    rw [halg, AlgHom.toRingHom_eq_coe, RingHom.coe_coe, aeval_C, ← Ideal.Quotient.mk_algebraMap,
      MvPolynomial.algebraMap_eq]
  -- every form lies in `M`
  have hform : ∀ t : ℕ, ∀ F : MvPolynomial (Fin n) K, F.IsHomogeneous t →
      Ideal.Quotient.mk J F ∈ M := by
    intro t
    induction t using Nat.strong_induction_on with
    | _ t ih =>
      intro F hF
      by_cases ht : t < N
      · -- `F` is a `K`-combination of monomials of degree `t < N`
        rw [F.as_sum, map_sum]
        refine Submodule.sum_mem _ fun d hd ↦ ?_
        have hdeg : d.degree = t := by
          rw [Finsupp.degree_eq_weight_one]
          exact hF (mem_support_iff.mp hd)
        have hmon : monomial d (1 : K) ∈ gens := by
          rw [hgens, Finset.mem_image]
          exact ⟨d, Finset.mem_filter.mpr ⟨mem_exponentsLE.mpr (by omega), by omega⟩, rfl⟩
        have hmem : Ideal.Quotient.mk J (monomial d (1 : K)) ∈ M :=
          Submodule.subset_span (Set.mem_image_of_mem _ hmon)
        have heq : Ideal.Quotient.mk J (monomial d (coeff d F)) =
            (C (coeff d F) : MvPolynomial (Fin s) K) •
              Ideal.Quotient.mk J (monomial d (1 : K)) := by
          rw [Algebra.smul_def, hC, ← map_mul, C_mul_monomial, mul_one]
        rw [heq]
        exact M.smul_mem _ hmem
      · replace ht := not_lt.mp ht
        obtain _ | t := t
        · -- `N = 0`, so `J = ⊤`
          have hN0 : N = 0 := Nat.eq_zero_of_le_zero ht
          subst hN0
          have hJtop : J = ⊤ :=
            eq_top_of_sup_span_range_eq_top hJh hy (top_le_iff.mp (by simpa using hN))
          rw [Ideal.Quotient.eq_zero_iff_mem.mpr (hJtop ▸ Submodule.mem_top)]
          exact M.zero_mem
        · obtain ⟨G, H, hG, hH, hFGH⟩ :=
            exists_eq_add_sum_mul_of_pow_idealOfVars_le hJh hy hN ht hF
          rw [hFGH, map_add, Ideal.Quotient.eq_zero_iff_mem.mpr hG, zero_add, map_sum]
          refine Submodule.sum_mem _ fun i _ ↦ ?_
          rw [map_mul, ← hX, ← Algebra.smul_def]
          exact M.smul_mem _ (ih t (Nat.lt_succ_self t) (H i) (hH i))
  rw [eq_top_iff]
  rintro v -
  obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective v
  rw [← sum_homogeneousComponent f, map_sum]
  exact Submodule.sum_mem _ fun t _ ↦ hform t _ (homogeneousComponent_isHomogeneous t f)

-- synthesizing `Module (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J)` from the `Algebra`
-- instance first explores `Submodule.Quotient.module'` and needs about `40000` heartbeats
/-- Blueprint A02.h: **module-finiteness of `Q ⧸ J` over `MvPolynomial (Fin s) K`** (acting through
`X i ↦ mk J (y i)`) from `𝔪ₙ ^ N ≤ J ⊔ (y)`; version with the algebra structure as a hypothesis. -/
theorem finite_of_pow_idealOfVars_le' {J : Ideal (MvPolynomial (Fin n) K)}
    (hJh : J.IsHomogeneous (homogeneousSubmodule (Fin n) K)) {s N : ℕ}
    {y : Fin s → MvPolynomial (Fin n) K} (hy : ∀ i, (y i).IsHomogeneous 1)
    (hN : idealOfVars (Fin n) K ^ N ≤ J ⊔ Ideal.span (Set.range y))
    [Algebra (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J)]
    (halg : algebraMap (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J) =
      (MvPolynomial.aeval fun i ↦ Ideal.Quotient.mk J (y i)).toRingHom) :
    Module.Finite (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J) := by
  obtain ⟨gens, -, hspan⟩ := span_image_mk_eq_top_of_pow_idealOfVars_le hJh hy hN halg
  exact ⟨hspan ▸ Submodule.fg_span (gens.finite_toSet.image _)⟩

-- synthesizing `Module (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J)` from the `Algebra`
-- instance first explores `Submodule.Quotient.module'` and needs about `40000` heartbeats
/-- Blueprint A02.h: **module-finiteness of `Q ⧸ J` over `MvPolynomial (Fin s) K`** for the algebra
structure `(MvPolynomial.aeval fun i ↦ mk J (y i)).toRingHom.toAlgebra`, from
`𝔪ₙ ^ N ≤ J ⊔ (y)`. -/
theorem finite_of_pow_idealOfVars_le {J : Ideal (MvPolynomial (Fin n) K)}
    (hJh : J.IsHomogeneous (homogeneousSubmodule (Fin n) K)) {s N : ℕ}
    {y : Fin s → MvPolynomial (Fin n) K} (hy : ∀ i, (y i).IsHomogeneous 1)
    (hN : idealOfVars (Fin n) K ^ N ≤ J ⊔ Ideal.span (Set.range y)) :
    letI : Algebra (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J) :=
      (MvPolynomial.aeval (R := K) fun i ↦ Ideal.Quotient.mk J (y i)).toRingHom.toAlgebra
    Module.Finite (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J) := by
  letI : Algebra (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J) :=
    (MvPolynomial.aeval (R := K) fun i ↦ Ideal.Quotient.mk J (y i)).toRingHom.toAlgebra
  exact finite_of_pow_idealOfVars_le' hJh hy hN (RingHom.algebraMap_toAlgebra _)

/-! #### A02.g: injectivity by dimension counting -/

-- synthesizing `Module (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J)` from the `Algebra`
-- instance first explores `Submodule.Quotient.module'` and needs about `40000` heartbeats
/-- Blueprint A02.g: **injectivity of the linear normalization.** If `𝔪ₙ ^ N ≤ J ⊔ (y)` for `s`
linear forms `y` with `s ≤ quotDim J`, then `MvPolynomial.aeval (mk J ∘ y)` is injective: `Q ⧸ J`
is finite, hence integral, over its image `S ⧸ ker`, so `dim (S ⧸ ker) = quotDim J ≥ s`; a nonzero
kernel would force `dim (S ⧸ ker) + 1 ≤ dim S = s`. -/
theorem aeval_injective_of_pow_idealOfVars_le {J : Ideal (MvPolynomial (Fin n) K)} (hJ : J ≠ ⊤)
    (hJh : J.IsHomogeneous (homogeneousSubmodule (Fin n) K)) {s : ℕ} (hs : s ≤ quotDim J)
    {y : Fin s → MvPolynomial (Fin n) K} (hy : ∀ i, (y i).IsHomogeneous 1) {N : ℕ}
    (hN : idealOfVars (Fin n) K ^ N ≤ J ⊔ Ideal.span (Set.range y)) :
    Function.Injective (MvPolynomial.aeval (fun i ↦ Ideal.Quotient.mk J (y i)) :
      MvPolynomial (Fin s) K →ₐ[K] MvPolynomial (Fin n) K ⧸ J) := by
  set g : MvPolynomial (Fin s) K →ₐ[K] MvPolynomial (Fin n) K ⧸ J :=
    MvPolynomial.aeval fun i ↦ Ideal.Quotient.mk J (y i) with hg
  letI : Algebra (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J) := g.toRingHom.toAlgebra
  haveI : Module.Finite (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J) :=
    finite_of_pow_idealOfVars_le' hJh hy hN (RingHom.algebraMap_toAlgebra _)
  haveI : Algebra.IsIntegral (MvPolynomial (Fin s) K) (MvPolynomial (Fin n) K ⧸ J) :=
    Algebra.IsIntegral.of_finite _ _
  set ker := RingHom.ker g.toRingHom with hker
  suffices hbot : ker = ⊥ from
    (RingHom.injective_iff_ker_eq_bot g.toRingHom).mpr hbot
  by_contra hne
  obtain ⟨r, hr, hr0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hne
  -- the image `T := S ⧸ ker` and the integral injective map `T → Q ⧸ J`
  letI : Algebra (MvPolynomial (Fin s) K ⧸ ker) (MvPolynomial (Fin n) K ⧸ J) :=
    (RingHom.kerLift g.toRingHom).toAlgebra
  haveI : IsScalarTower (MvPolynomial (Fin s) K) (MvPolynomial (Fin s) K ⧸ ker)
      (MvPolynomial (Fin n) K ⧸ J) :=
    IsScalarTower.of_algebraMap_eq fun x ↦ (RingHom.kerLift_mk g.toRingHom x).symm
  haveI : Algebra.IsIntegral (MvPolynomial (Fin s) K ⧸ ker) (MvPolynomial (Fin n) K ⧸ J) :=
    ⟨fun x ↦ (Algebra.IsIntegral.isIntegral (R := MvPolynomial (Fin s) K) x).tower_top⟩
  haveI : FaithfulSMul (MvPolynomial (Fin s) K ⧸ ker) (MvPolynomial (Fin n) K ⧸ J) :=
    (faithfulSMul_iff_algebraMap_injective _ _).mpr (RingHom.kerLift_injective _)
  have h1 : ringKrullDim (MvPolynomial (Fin n) K ⧸ J) =
      ringKrullDim (MvPolynomial (Fin s) K ⧸ ker) :=
    ringKrullDim_eq_of_isIntegral
  have h2 : ringKrullDim (MvPolynomial (Fin s) K ⧸ ker) ≤
      ringKrullDim (MvPolynomial (Fin s) K ⧸ Ideal.span {r}) :=
    ringKrullDim_le_of_surjective
      (Ideal.Quotient.factor ((Ideal.span_singleton_le_iff_mem _).mpr hr))
      (Ideal.Quotient.factor_surjective _)
  have h3 : ringKrullDim (MvPolynomial (Fin s) K ⧸ Ideal.span {r}) + 1 ≤
      ringKrullDim (MvPolynomial (Fin s) K) :=
    ringKrullDim_quotient_succ_le_of_nonZeroDivisor (mem_nonZeroDivisors_of_ne_zero hr0)
  rw [ringKrullDim_mvPolynomial_fin_eq] at h3
  rw [← coe_quotDim J hJ] at h1
  have h4 : (quotDim J : WithBot ℕ∞) + 1 ≤ (s : WithBot ℕ∞) := by
    calc (quotDim J : WithBot ℕ∞) + 1 = ringKrullDim (MvPolynomial (Fin s) K ⧸ ker) + 1 := by
          rw [h1]
      _ ≤ ringKrullDim (MvPolynomial (Fin s) K ⧸ Ideal.span {r}) + 1 := by gcongr
      _ ≤ s := h3
  have h5 : quotDim J + 1 ≤ s := by exact_mod_cast h4
  omega

/-! #### The main theorem -/

/-- Blueprint A02: **linear Noether normalization of a standard graded algebra.** For `K` infinite
and `J ≠ ⊤` a homogeneous ideal of `Q = MvPolynomial (Fin n) K`, there are `quotDim J` linear forms
`y i` such that `MvPolynomial.aeval (mk J ∘ y) : MvPolynomial (Fin (quotDim J)) K →ₐ[K] Q ⧸ J` is
injective and `𝔪ₙ ^ N ≤ J ⊔ span (range y)` for some `N` (so `Q ⧸ J` is module-finite over the
image: `finite_of_pow_idealOfVars_le`). -/
theorem exists_linear_normalization [Infinite K] (J : Ideal (MvPolynomial (Fin n) K)) (hJ : J ≠ ⊤)
    (hJh : J.IsHomogeneous (homogeneousSubmodule (Fin n) K)) :
    ∃ y : Fin (quotDim J) → MvPolynomial (Fin n) K,
      (∀ i, (y i).IsHomogeneous 1) ∧
      Function.Injective (MvPolynomial.aeval (fun i ↦ Ideal.Quotient.mk J (y i)) :
        MvPolynomial (Fin (quotDim J)) K →ₐ[K] MvPolynomial (Fin n) K ⧸ J) ∧
      ∃ N : ℕ, idealOfVars (Fin n) K ^ N ≤ J ⊔ Ideal.span (Set.range y) := by
  obtain ⟨y, hy, h0⟩ := exists_linear_forms_quotDim_sup_eq_zero (quotDim J) J hJ hJh le_rfl
  obtain ⟨N, hN⟩ :=
    pow_idealOfVars_le_of_quotDim_eq_zero (hJh.sup (isHomogeneous_span_range hy)) h0
  exact ⟨y, hy, aeval_injective_of_pow_idealOfVars_le hJ hJh le_rfl hy hN, N, hN⟩

end LinearNormalization

end Nikodym.LowerBound

/- Adapted for Lean Pool: module imports and compatibility with its pinned toolchain. -/
