/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, Claude Opus 5
-/

/-
Adapted from: Spectra (https://github.com/adambornemann-glitch/Spectra),
  `Spectra/YosidaHille/Approximation/{Helpers,Defs}.lean` at commit
  `8dbaaf6728d1342ae16acf79fd7eef7c59b37e63`,
  Copyright (c) 2026 Spectra Formalization Project, `Authors: Adam Bornemann`,
  Apache 2.0.  Modified: see `## Provenance` (Apache 2.0 §4(b)); the donor's
  copyright and authorship notices are retained here and below (§4(c)).
-/
module

public import LeanPool.DavisKahan.ForTauCeti.Analysis.InnerProductSpace.LinearPMap.SelfAdjointResolvent
public import Mathlib.Analysis.Complex.Norm
public import Mathlib.Data.PNat.Basic
public import Mathlib.Algebra.Star.Unitary
public import Mathlib.Analysis.CStarAlgebra.Exponential
public import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap
public import LeanPool.DavisKahan.ForTauCeti.Analysis.InnerProductSpace.SkewAdjointExponential
public import LeanPool.DavisKahan.ForTauCeti.Analysis.InnerProductSpace.OneParameterUnitaryGroup.Basic

/-!
# The Yosida approximation of a self-adjoint operator

The bounded approximants used to build the unitary group generated by a
self-adjoint operator (Stone's theorem):

* `resolventAtIn A n = R(in)`, `resolventAtNegIn A n = R(-in)`;
* `yosidaApproximant A n = n² R(in) - in`, the Yosida approximant;
* `yosidaApproximantSym A n = (n²/2)(R(in) + R(-in))`, its symmetric form.

## Provenance

* **Original repository:** Spectra, commit `8dbaaf6728d1342ae16acf79fd7eef7c59b37e63`.
* **Original modules:** `Spectra/YosidaHille/Approximation/Helpers.lean` (the
  arithmetic of `I * n`) and `Spectra/YosidaHille/Approximation/Defs.lean`
  (`resolventAtIn`, `resolventAtNegIn`, `yosidaApproximant`, `yosidaApproximantSym`).
* **Original authors / copyright / licence:** Copyright (c) 2026 Spectra
  Formalization Project; `Authors: Adam Bornemann`; Apache 2.0.
* **Extraction class:** *adapted.*  The definitions are Spectra's; the arithmetic
  lemmas are transcribed; the hypothesis interface is changed — see below.
* **Semantic difference from the donor — one hypothesis instead of three.**
  Spectra threads `(hsym, hplus, hminus)` — formal self-adjointness plus `±i`
  deficiency-surjectivity — through every one of these definitions, because its
  resolvent is constructed from exactly those three inputs.  Here they collapse
  to a single `IsSelfAdjoint A`, because
  `TauCeti.LinearPMap.mem_resolventSet_of_im_ne_zero` (proved in
  `SelfAdjointResolvent.lean`) derives resolvent-set membership at *any* non-real
  point directly from self-adjointness.  That also removes the dependency on
  Spectra's `Resolvent/Range.lean` entirely.
-/

public section

namespace TauCeti
namespace LinearPMap

open Complex Filter
open scoped InnerProductSpace Topology

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-! ### Arithmetic of `I * n` for `n : ℕ+` -/

/-- `I * n` lies off the real axis, so the resolvent is defined there. -/
theorem I_mul_pnat_im_ne_zero (n : ℕ+) : (I * (n : ℂ)).im ≠ 0 := by
  simp only [mul_im, I_re, I_im, zero_mul, one_mul, zero_add]
  exact Nat.cast_ne_zero.mpr n.ne_zero

/-- `-I * n` lies off the real axis. -/
theorem neg_I_mul_pnat_im_ne_zero (n : ℕ+) : (-I * (n : ℂ)).im ≠ 0 := by
  simp only [neg_mul, neg_im]
  exact neg_ne_zero.mpr (I_mul_pnat_im_ne_zero n)

/-- The imaginary part of `i·n` is `n`. -/
theorem I_mul_pnat_im (n : ℕ+) : (I * (n : ℂ)).im = (n : ℝ) := by
  simp [mul_im]

/-- `|Im (i·n)| = n`.  The absolute value form is what the resolvent norm bound `‖R(z)‖ ≤ |Im z|⁻¹`
consumes. -/
theorem abs_I_mul_pnat_im (n : ℕ+) : |(I * (n : ℂ)).im| = (n : ℝ) := by
  rw [I_mul_pnat_im]
  exact abs_of_pos (Nat.cast_pos.mpr n.pos)

/-- `‖n²‖ = n²` for a positive natural cast into `ℂ`. -/
theorem norm_pnat_sq (n : ℕ+) : ‖((n : ℂ) ^ 2)‖ = (n : ℝ) ^ 2 := by
  rw [Complex.norm_pow, Complex.norm_natCast]

/-- `‖i·n‖ = n`. -/
theorem norm_I_mul_pnat (n : ℕ+) : ‖I * (n : ℂ)‖ = (n : ℝ) := by
  rw [Complex.norm_mul, Complex.norm_I, one_mul, Complex.norm_natCast]

/-! ### The resolvent at `±in` -/

variable {A : H →ₗ.[ℂ] H}

/-- The resolvent at `z = in`. -/
@[expose]
noncomputable def resolventAtIn (_hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  resolvent A (I * (n : ℂ))

/-- The resolvent at `z = -in`. -/
@[expose]
noncomputable def resolventAtNegIn (_hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  resolvent A (-I * (n : ℂ))

/-- `‖R(in)‖ ≤ 1/n`. -/
theorem norm_resolventAtIn_le (hA : IsSelfAdjoint A) (n : ℕ+) :
    ‖resolventAtIn hA n‖ ≤ ((n : ℝ))⁻¹ := by
  have h := norm_resolvent_le_of_im_ne_zero hA (I_mul_pnat_im_ne_zero n)
  rwa [abs_I_mul_pnat_im] at h

/-- `‖R(-in)‖ ≤ 1/n`. -/
theorem norm_resolventAtNegIn_le (hA : IsSelfAdjoint A) (n : ℕ+) :
    ‖resolventAtNegIn hA n‖ ≤ ((n : ℝ))⁻¹ := by
  have h := norm_resolvent_le_of_im_ne_zero hA (neg_I_mul_pnat_im_ne_zero n)
  have habs : |(-I * (n : ℂ)).im| = (n : ℝ) := by
    simp only [neg_mul, neg_im, abs_neg]
    exact abs_I_mul_pnat_im n
  rwa [habs] at h

/-! ### The Yosida approximants -/

/-- The **raw** Yosida approximant `Aₙ = -n² R(in) - in`.

Raw because it is **not self-adjoint**: it is built from the resolvent at the single
spectral point `in`, and the subtracted `in` is purely imaginary, so `Aₙ⋆ ≠ Aₙ`.  Nothing
below exponentiates it, and nothing should — a unitary group needs a self-adjoint
generator.  Use `yosidaApproximantSym`, which symmetrises over `±in`, is proved
self-adjoint by `isSelfAdjoint_yosidaApproxSym`, and is what `expApprox` and the Stone
uniqueness argument actually take exponentials of.  `yosidaApproxNeg` is its mirror. -/
noncomputable def yosidaApproximant (hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  -((n : ℂ) ^ 2 • resolventAtIn hA n) - (I * (n : ℂ)) • ContinuousLinearMap.id ℂ H

/-- The symmetric Yosida approximant `-(n²/2)(R(in) + R(-in))`. -/
@[expose]
noncomputable def yosidaApproximantSym (hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  (-((n : ℂ) ^ 2 / 2)) • (resolventAtIn hA n + resolventAtNegIn hA n)

/-- The mirrored Yosida approximant `Aₙ⁻ = -n² R(-in) + in`. -/
noncomputable def yosidaApproxNeg (hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  -((n : ℂ) ^ 2 • resolventAtNegIn hA n) + (I * (n : ℂ)) • ContinuousLinearMap.id ℂ H

/-- The contraction `Jₙ = in·R(in)`. -/
noncomputable def yosidaJ (hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  (I * (n : ℂ)) • resolventAtIn hA n

/-- The contraction `Jₙ⁻ = -in·R(-in)`. -/
noncomputable def yosidaJNeg (hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  (-I * (n : ℂ)) • resolventAtNegIn hA n

/-! ### Adjoints: the two resolvents are each other's -/

/-- `R(in)⋆ = R(-in)`. -/
theorem adjoint_resolventAtIn (hA : IsSelfAdjoint A) (n : ℕ+) :
    ContinuousLinearMap.adjoint (resolventAtIn hA n) = resolventAtNegIn hA n := by
  have hsym : A.IsFormalAdjoint A := by
    have h := _root_.LinearPMap.adjoint_isFormalAdjoint (T := A) hA.dense_domain
    rwa [_root_.LinearPMap.isSelfAdjoint_def.mp hA] at h
  symm
  rw [ContinuousLinearMap.eq_adjoint_iff]
  intro x y
  set hin := mem_resolventSet_of_im_ne_zero hA (I_mul_pnat_im_ne_zero n) with hin_def
  set hnin := mem_resolventSet_of_im_ne_zero hA (neg_I_mul_pnat_im_ne_zero n) with hnin_def
  set u : A.domain := ⟨resolvent A (-I * (n : ℂ)) x, resolvent_mem_domain hnin x⟩ with hu
  set v : A.domain := ⟨resolvent A (I * (n : ℂ)) y, resolvent_mem_domain hin y⟩ with hv
  have hux : (-I * (n : ℂ)) • (u : H) - A u = x := smul_sub_apply_resolvent hnin x
  have hvy : (I * (n : ℂ)) • (v : H) - A v = y := smul_sub_apply_resolvent hin y
  have hconj : (starRingEnd ℂ) (-I * (n : ℂ)) = I * (n : ℂ) := by
    rw [map_mul, map_neg, Complex.conj_I, Complex.conj_natCast, neg_neg]
  calc ⟪resolventAtNegIn hA n x, y⟫_ℂ
      = ⟪(u : H), (I * (n : ℂ)) • (v : H) - A v⟫_ℂ := by rw [hvy]; rfl
    _ = ⟪(-I * (n : ℂ)) • (u : H) - A u, (v : H)⟫_ℂ := by
        rw [inner_sub_left, inner_sub_right, inner_smul_left, inner_smul_right,
          hconj, hsym u v]
    _ = ⟪x, resolventAtIn hA n y⟫_ℂ := by rw [hux]; rfl

/-- `R(-in)⋆ = R(in)`. -/
theorem adjoint_resolventAtNegIn (hA : IsSelfAdjoint A) (n : ℕ+) :
    ContinuousLinearMap.adjoint (resolventAtNegIn hA n) = resolventAtIn hA n := by
  rw [← adjoint_resolventAtIn hA n, ContinuousLinearMap.adjoint_adjoint]

/-- **The symmetric Yosida approximant is self-adjoint.**  It is the `n²/2`-weighted
average of two resolvents that are each other's adjoint. -/
theorem isSelfAdjoint_yosidaApproxSym (hA : IsSelfAdjoint A) (n : ℕ+) :
    _root_.IsSelfAdjoint (yosidaApproximantSym hA n) := by
  rw [ContinuousLinearMap.isSelfAdjoint_iff_isSymmetric]
  intro x y
  have hscalar : (starRingEnd ℂ) (-((n : ℂ) ^ 2 / 2)) = -((n : ℂ) ^ 2 / 2) := by
    rw [map_neg, map_div₀, map_pow, Complex.conj_natCast, map_ofNat]
  have hIn : ⟪resolventAtIn hA n x, y⟫_ℂ = ⟪x, resolventAtNegIn hA n y⟫_ℂ := by
    rw [← adjoint_resolventAtIn hA n, ContinuousLinearMap.adjoint_inner_right]
  have hNIn : ⟪resolventAtNegIn hA n x, y⟫_ℂ = ⟪x, resolventAtIn hA n y⟫_ℂ := by
    rw [← adjoint_resolventAtNegIn hA n, ContinuousLinearMap.adjoint_inner_right]
  -- `IsSymmetric` unfolds to this by definition, but the goal is phrased through the
  -- `yosidaApproximantSymSA` bundle; no simp lemma strips a `selfAdjoint` coercion, so the
  -- inner-product form has to be stated before `hIn`/`hNIn` can be used.
  change ⟪yosidaApproximantSym hA n x, y⟫_ℂ = ⟪x, yosidaApproximantSym hA n y⟫_ℂ
  unfold yosidaApproximantSym
  simp only [smul_apply, add_apply, inner_smul_left, inner_smul_right,
    inner_add_left, inner_add_right, hscalar]
  rw [hIn, hNIn]
  ring

/-! ### Norm bounds -/

/-- `‖Aₙ‖ ≤ 2n`. -/
theorem norm_yosidaApprox_le (hA : IsSelfAdjoint A) (n : ℕ+) :
    ‖yosidaApproximant hA n‖ ≤ 2 * (n : ℝ) := by
  have hfirst : ‖-((n : ℂ) ^ 2 • resolventAtIn hA n)‖ ≤ (n : ℝ) := by
    calc ‖-((n : ℂ) ^ 2 • resolventAtIn hA n)‖
        = ‖((n : ℂ) ^ 2)‖ * ‖resolventAtIn hA n‖ := by rw [norm_neg, norm_smul]
      _ ≤ ‖((n : ℂ) ^ 2)‖ * ((n : ℝ))⁻¹ :=
          mul_le_mul_of_nonneg_left (norm_resolventAtIn_le hA n) (norm_nonneg _)
      _ = (n : ℝ) ^ 2 * ((n : ℝ))⁻¹ := by rw [norm_pnat_sq]
      _ = (n : ℝ) := by
          have : (n : ℝ) ≠ 0 := ne_of_gt (Nat.cast_pos.mpr n.pos)
          field_simp
  have hsecond : ‖(I * (n : ℂ)) • ContinuousLinearMap.id ℂ H‖ ≤ (n : ℝ) := by
    calc ‖(I * (n : ℂ)) • ContinuousLinearMap.id ℂ H‖
        = ‖I * (n : ℂ)‖ * ‖ContinuousLinearMap.id ℂ H‖ := norm_smul _ _
      _ ≤ ‖I * (n : ℂ)‖ * 1 :=
          mul_le_mul_of_nonneg_left ContinuousLinearMap.norm_id_le (norm_nonneg _)
      _ = (n : ℝ) := by rw [mul_one, norm_I_mul_pnat]
  calc ‖yosidaApproximant hA n‖
      ≤ ‖-((n : ℂ) ^ 2 • resolventAtIn hA n)‖
          + ‖(I * (n : ℂ)) • ContinuousLinearMap.id ℂ H‖ := norm_sub_le _ _
    _ ≤ (n : ℝ) + (n : ℝ) := add_le_add hfirst hsecond
    _ = 2 * (n : ℝ) := by ring

/-- `‖Jₙ‖ ≤ 1`. -/
theorem norm_yosidaJ_le (hA : IsSelfAdjoint A) (n : ℕ+) : ‖yosidaJ hA n‖ ≤ 1 := by
  have hn : (0 : ℝ) < (n : ℝ) := Nat.cast_pos.mpr n.pos
  calc ‖yosidaJ hA n‖
      = ‖I * (n : ℂ)‖ * ‖resolventAtIn hA n‖ := norm_smul _ _
    _ = (n : ℝ) * ‖resolventAtIn hA n‖ := by rw [norm_I_mul_pnat]
    _ ≤ (n : ℝ) * ((n : ℝ))⁻¹ :=
        mul_le_mul_of_nonneg_left (norm_resolventAtIn_le hA n) hn.le
    _ = 1 := by field_simp

/-- `‖Jₙ⁻‖ ≤ 1`. -/
theorem norm_yosidaJNeg_le (hA : IsSelfAdjoint A) (n : ℕ+) : ‖yosidaJNeg hA n‖ ≤ 1 := by
  have hn : (0 : ℝ) < (n : ℝ) := Nat.cast_pos.mpr n.pos
  have hcoeff : ‖(-I * (n : ℂ))‖ = (n : ℝ) := by
    rw [neg_mul, norm_neg, norm_I_mul_pnat]
  calc ‖yosidaJNeg hA n‖
      = ‖(-I * (n : ℂ))‖ * ‖resolventAtNegIn hA n‖ := norm_smul _ _
    _ = (n : ℝ) * ‖resolventAtNegIn hA n‖ := by rw [hcoeff]
    _ ≤ (n : ℝ) * ((n : ℝ))⁻¹ :=
        mul_le_mul_of_nonneg_left (norm_resolventAtNegIn_le hA n) hn.le
    _ = 1 := by field_simp

/-! ### Strong convergence `Jₙ → 1`

`Jₙ = -in·R(in)` converges strongly to the identity.  On the domain this is the
algebraic identity `Jₙφ = φ - R(in)(Aφ)` together with `‖R(in)‖ ≤ 1/n`; the
contraction bound `‖Jₙ‖ ≤ 1` then spreads it to all of `H` by density. -/

/-- On the domain, `Jₙ` splits off a resolvent: `Jₙφ = φ + R(in)(Aφ)`. -/
theorem yosidaJ_apply_of_mem_domain (hA : IsSelfAdjoint A) (n : ℕ+)
    (φ : H) (hφ : φ ∈ A.domain) :
    yosidaJ hA n φ = φ + resolventAtIn hA n (A ⟨φ, hφ⟩) := by
  have hz : (I * (n : ℂ)) ∈ resolventSet A :=
    mem_resolventSet_of_im_ne_zero hA (I_mul_pnat_im_ne_zero n)
  have h1 : resolvent A (I * (n : ℂ)) ((I * (n : ℂ)) • φ - A ⟨φ, hφ⟩) = φ :=
    resolvent_smul_sub_apply hz ⟨φ, hφ⟩
  -- rewrite inside `h1` rather than in the goal: `φ` occurs in `hφ`, so rewriting
  -- it in the goal produces an ill-typed motive
  have h2 : (I * (n : ℂ)) • resolvent A (I * (n : ℂ)) φ
      - resolvent A (I * (n : ℂ)) (A ⟨φ, hφ⟩) = φ := by
    rwa [map_sub, map_smul] at h1
  -- states the goal with the definition unfolded, in the shape the next step needs;
  -- there is no `_apply` lemma to rewrite with here.
  change (I * (n : ℂ)) • resolvent A (I * (n : ℂ)) φ
    = φ + resolvent A (I * (n : ℂ)) (A ⟨φ, hφ⟩)
  exact eq_add_of_sub_eq h2

/-- `Jₙφ → φ` for `φ` in the domain. -/
theorem tendsto_yosidaJ_of_mem_domain (hA : IsSelfAdjoint A) (φ : H) (hφ : φ ∈ A.domain) :
    Tendsto (fun n : ℕ+ => yosidaJ hA n φ) atTop (𝓝 φ) := by
  rw [Metric.tendsto_atTop]
  intro ε hε
  by_cases hz : ‖A ⟨φ, hφ⟩‖ = 0
  · refine ⟨1, fun n _ => ?_⟩
    rw [yosidaJ_apply_of_mem_domain hA n φ hφ, norm_eq_zero.mp hz]
    simpa using hε
  · have hpos : 0 < ‖A ⟨φ, hφ⟩‖ := (norm_nonneg _).lt_of_ne' hz
    refine ⟨⟨Nat.ceil (‖A ⟨φ, hφ⟩‖ / ε) + 1, Nat.add_one_pos _⟩, fun n hn => ?_⟩
    have hnpos : (0 : ℝ) < (n : ℝ) := Nat.cast_pos.mpr n.pos
    have heq : dist (yosidaJ hA n φ) φ = ‖resolventAtIn hA n (A ⟨φ, hφ⟩)‖ := by
      rw [dist_eq_norm, yosidaJ_apply_of_mem_domain hA n φ hφ]
      simp
    rw [heq]
    calc ‖resolventAtIn hA n (A ⟨φ, hφ⟩)‖
        ≤ ‖resolventAtIn hA n‖ * ‖A ⟨φ, hφ⟩‖ := ContinuousLinearMap.le_opNorm _ _
      _ ≤ ((n : ℝ))⁻¹ * ‖A ⟨φ, hφ⟩‖ := by
          gcongr
          exact norm_resolventAtIn_le hA n
      _ < ε := by
          rw [inv_mul_lt_iff₀ hnpos]
          have h1 : (⌈‖A ⟨φ, hφ⟩‖ / ε⌉₊ + 1 : ℕ) ≤ (n : ℕ) := hn
          calc ‖A ⟨φ, hφ⟩‖
              = (‖A ⟨φ, hφ⟩‖ / ε) * ε := by field_simp
            _ ≤ (⌈‖A ⟨φ, hφ⟩‖ / ε⌉₊ : ℝ) * ε := by gcongr; exact Nat.le_ceil _
            _ < ((⌈‖A ⟨φ, hφ⟩‖ / ε⌉₊ : ℝ) + 1) * ε := by nlinarith
            _ ≤ (n : ℝ) * ε := by gcongr; exact_mod_cast h1

/-- `Jₙ → 1` strongly on all of `H`, by density and `‖Jₙ‖ ≤ 1`. -/
theorem tendsto_yosidaJ (hA : IsSelfAdjoint A) (ψ : H) :
    Tendsto (fun n : ℕ+ => yosidaJ hA n ψ) atTop (𝓝 ψ) := by
  have hdense : Dense (A.domain : Set H) := hA.dense_domain
  rw [Metric.tendsto_atTop]
  intro ε hε
  obtain ⟨φ, hφmem, hφclose⟩ := Metric.mem_closure_iff.mp
    (hdense.closure_eq ▸ Set.mem_univ ψ) (ε / 3) (by linarith)
  obtain ⟨N, hN⟩ := (Metric.tendsto_atTop.mp
    (tendsto_yosidaJ_of_mem_domain hA φ hφmem)) (ε / 3) (by linarith)
  refine ⟨N, fun n hn => ?_⟩
  calc dist (yosidaJ hA n ψ) ψ
      ≤ dist (yosidaJ hA n ψ) (yosidaJ hA n φ) + dist (yosidaJ hA n φ) φ + dist φ ψ :=
        dist_triangle4 _ _ _ _
    _ = ‖yosidaJ hA n (ψ - φ)‖ + dist (yosidaJ hA n φ) φ + dist φ ψ := by
        rw [dist_eq_norm, ContinuousLinearMap.map_sub]
    _ ≤ ‖yosidaJ hA n‖ * ‖ψ - φ‖ + dist (yosidaJ hA n φ) φ + dist φ ψ := by
        gcongr; exact ContinuousLinearMap.le_opNorm _ _
    _ ≤ 1 * ‖ψ - φ‖ + dist (yosidaJ hA n φ) φ + dist φ ψ := by
        gcongr; exact norm_yosidaJ_le hA n
    _ = dist ψ φ + dist (yosidaJ hA n φ) φ + dist φ ψ := by rw [one_mul, ← dist_eq_norm]
    _ < ε / 3 + ε / 3 + ε / 3 := by
        gcongr
        · exact Metric.mem_ball.mp (hN n hn)
        · exact Metric.mem_ball'.mp hφclose
    _ = ε := by ring

/-! ### The mirror statements for `Jₙ⁻` -/

/-- On the domain, `Jₙ⁻φ = φ + R(-in)(Aφ)`. -/
theorem yosidaJNeg_apply_of_mem_domain (hA : IsSelfAdjoint A) (n : ℕ+)
    (φ : H) (hφ : φ ∈ A.domain) :
    yosidaJNeg hA n φ = φ + resolventAtNegIn hA n (A ⟨φ, hφ⟩) := by
  have hz : (-I * (n : ℂ)) ∈ resolventSet A :=
    mem_resolventSet_of_im_ne_zero hA (neg_I_mul_pnat_im_ne_zero n)
  have h1 : resolvent A (-I * (n : ℂ)) ((-I * (n : ℂ)) • φ - A ⟨φ, hφ⟩) = φ :=
    resolvent_smul_sub_apply hz ⟨φ, hφ⟩
  have h2 : (-I * (n : ℂ)) • resolvent A (-I * (n : ℂ)) φ
      - resolvent A (-I * (n : ℂ)) (A ⟨φ, hφ⟩) = φ := by
    rwa [map_sub, map_smul] at h1
  -- states the goal with the definition unfolded, in the shape the next step needs;
  -- there is no `_apply` lemma to rewrite with here.
  change (-I * (n : ℂ)) • resolvent A (-I * (n : ℂ)) φ
    = φ + resolvent A (-I * (n : ℂ)) (A ⟨φ, hφ⟩)
  exact eq_add_of_sub_eq h2

/-- `Jₙ⁻φ → φ` for `φ` in the domain. -/
theorem tendsto_yosidaJNeg_of_mem_domain (hA : IsSelfAdjoint A) (φ : H) (hφ : φ ∈ A.domain) :
    Tendsto (fun n : ℕ+ => yosidaJNeg hA n φ) atTop (𝓝 φ) := by
  rw [Metric.tendsto_atTop]
  intro ε hε
  by_cases hz : ‖A ⟨φ, hφ⟩‖ = 0
  · refine ⟨1, fun n _ => ?_⟩
    rw [yosidaJNeg_apply_of_mem_domain hA n φ hφ, norm_eq_zero.mp hz]
    simpa using hε
  · have hpos : 0 < ‖A ⟨φ, hφ⟩‖ := (norm_nonneg _).lt_of_ne' hz
    refine ⟨⟨Nat.ceil (‖A ⟨φ, hφ⟩‖ / ε) + 1, Nat.add_one_pos _⟩, fun n hn => ?_⟩
    have hnpos : (0 : ℝ) < (n : ℝ) := Nat.cast_pos.mpr n.pos
    have heq : dist (yosidaJNeg hA n φ) φ = ‖resolventAtNegIn hA n (A ⟨φ, hφ⟩)‖ := by
      rw [dist_eq_norm, yosidaJNeg_apply_of_mem_domain hA n φ hφ]
      simp
    rw [heq]
    calc ‖resolventAtNegIn hA n (A ⟨φ, hφ⟩)‖
        ≤ ‖resolventAtNegIn hA n‖ * ‖A ⟨φ, hφ⟩‖ := ContinuousLinearMap.le_opNorm _ _
      _ ≤ ((n : ℝ))⁻¹ * ‖A ⟨φ, hφ⟩‖ := by
          gcongr
          exact norm_resolventAtNegIn_le hA n
      _ < ε := by
          rw [inv_mul_lt_iff₀ hnpos]
          have h1 : (⌈‖A ⟨φ, hφ⟩‖ / ε⌉₊ + 1 : ℕ) ≤ (n : ℕ) := hn
          calc ‖A ⟨φ, hφ⟩‖
              = (‖A ⟨φ, hφ⟩‖ / ε) * ε := by field_simp
            _ ≤ (⌈‖A ⟨φ, hφ⟩‖ / ε⌉₊ : ℝ) * ε := by gcongr; exact Nat.le_ceil _
            _ < ((⌈‖A ⟨φ, hφ⟩‖ / ε⌉₊ : ℝ) + 1) * ε := by nlinarith
            _ ≤ (n : ℝ) * ε := by gcongr; exact_mod_cast h1

/-- `Jₙ⁻ → 1` strongly on all of `H`. -/
theorem tendsto_yosidaJNeg (hA : IsSelfAdjoint A) (ψ : H) :
    Tendsto (fun n : ℕ+ => yosidaJNeg hA n ψ) atTop (𝓝 ψ) := by
  have hdense : Dense (A.domain : Set H) := hA.dense_domain
  rw [Metric.tendsto_atTop]
  intro ε hε
  obtain ⟨φ, hφmem, hφclose⟩ := Metric.mem_closure_iff.mp
    (hdense.closure_eq ▸ Set.mem_univ ψ) (ε / 3) (by linarith)
  obtain ⟨N, hN⟩ := (Metric.tendsto_atTop.mp
    (tendsto_yosidaJNeg_of_mem_domain hA φ hφmem)) (ε / 3) (by linarith)
  refine ⟨N, fun n hn => ?_⟩
  calc dist (yosidaJNeg hA n ψ) ψ
      ≤ dist (yosidaJNeg hA n ψ) (yosidaJNeg hA n φ) + dist (yosidaJNeg hA n φ) φ
          + dist φ ψ := dist_triangle4 _ _ _ _
    _ = ‖yosidaJNeg hA n (ψ - φ)‖ + dist (yosidaJNeg hA n φ) φ + dist φ ψ := by
        rw [dist_eq_norm, ContinuousLinearMap.map_sub]
    _ ≤ ‖yosidaJNeg hA n‖ * ‖ψ - φ‖ + dist (yosidaJNeg hA n φ) φ + dist φ ψ := by
        gcongr; exact ContinuousLinearMap.le_opNorm _ _
    _ ≤ 1 * ‖ψ - φ‖ + dist (yosidaJNeg hA n φ) φ + dist φ ψ := by
        gcongr; exact norm_yosidaJNeg_le hA n
    _ = dist ψ φ + dist (yosidaJNeg hA n φ) φ + dist φ ψ := by rw [one_mul, ← dist_eq_norm]
    _ < ε / 3 + ε / 3 + ε / 3 := by
        gcongr
        · exact Metric.mem_ball.mp (hN n hn)
        · exact Metric.mem_ball'.mp hφclose
    _ = ε := by ring

/-! ### The approximants factor through the contractions -/

/-- `(-in)² = -n²`. -/
private theorem negI_pnat_sq (n : ℕ+) :
    (-I * (n : ℂ)) * (-I * (n : ℂ)) = -((n : ℂ) ^ 2) := by
  rw [show (-I * (n : ℂ)) * (-I * (n : ℂ)) = (I * I) * (n : ℂ) ^ 2 by ring, Complex.I_mul_I]
  ring

/-- `(in)² = -n²`. -/
private theorem I_pnat_sq (n : ℕ+) :
    (I * (n : ℂ)) * (I * (n : ℂ)) = -((n : ℂ) ^ 2) := by
  rw [show (I * (n : ℂ)) * (I * (n : ℂ)) = (I * I) * (n : ℂ) ^ 2 by ring, Complex.I_mul_I]
  ring

/-- On the domain, `Aₙ` factors through `Jₙ`: `Aₙφ = Jₙ(Aφ)`. -/
theorem yosidaApprox_apply_of_mem_domain (hA : IsSelfAdjoint A) (n : ℕ+)
    (φ : H) (hφ : φ ∈ A.domain) :
    yosidaApproximant hA n φ = yosidaJ hA n (A ⟨φ, hφ⟩) := by
  have h := yosidaJ_apply_of_mem_domain hA n φ hφ
  have hRA : resolvent A (I * (n : ℂ)) (A ⟨φ, hφ⟩)
      = (I * (n : ℂ)) • resolvent A (I * (n : ℂ)) φ - φ := by
    have h0 : (I * (n : ℂ)) • resolvent A (I * (n : ℂ)) φ
        = φ + resolvent A (I * (n : ℂ)) (A ⟨φ, hφ⟩) := h
    rw [h0]; abel
  -- The goal is the squared-resolvent identity with the `n ^ 2` factor already
  -- collected; `hRA` is stated in the un-collected form, so `rw [hRA]` matches only
  -- after the two sides are put in this shape.
  change -((n : ℂ) ^ 2 • resolvent A (I * (n : ℂ)) φ) - (I * (n : ℂ)) • φ
    = (I * (n : ℂ)) • resolvent A (I * (n : ℂ)) (A ⟨φ, hφ⟩)
  rw [hRA, smul_sub, smul_smul, I_pnat_sq]
  module

/-- `Aₙφ → Aφ` on the domain. -/
theorem tendsto_yosidaApprox_of_mem_domain (hA : IsSelfAdjoint A) (ψ : H) (hψ : ψ ∈ A.domain) :
    Tendsto (fun n : ℕ+ => yosidaApproximant hA n ψ) atTop (𝓝 (A ⟨ψ, hψ⟩)) := by
  simp only [fun n => yosidaApprox_apply_of_mem_domain hA n ψ hψ]
  exact tendsto_yosidaJ hA (A ⟨ψ, hψ⟩)

/-- On the domain, `Aₙ⁻` factors through `Jₙ⁻`. -/
theorem yosidaApproxNeg_apply_of_mem_domain (hA : IsSelfAdjoint A) (n : ℕ+)
    (φ : H) (hφ : φ ∈ A.domain) :
    yosidaApproxNeg hA n φ = yosidaJNeg hA n (A ⟨φ, hφ⟩) := by
  have h := yosidaJNeg_apply_of_mem_domain hA n φ hφ
  have hRA : resolvent A (-I * (n : ℂ)) (A ⟨φ, hφ⟩)
      = (-I * (n : ℂ)) • resolvent A (-I * (n : ℂ)) φ - φ := by
    have h0 : (-I * (n : ℂ)) • resolvent A (-I * (n : ℂ)) φ
        = φ + resolvent A (-I * (n : ℂ)) (A ⟨φ, hφ⟩) := h
    rw [h0]; abel
  -- Mirror of the previous lemma with the opposite sign; same reason `rw [hRA]`
  -- cannot fire on the goal as elaborated.
  change -((n : ℂ) ^ 2 • resolvent A (-I * (n : ℂ)) φ) + (I * (n : ℂ)) • φ
    = (-I * (n : ℂ)) • resolvent A (-I * (n : ℂ)) (A ⟨φ, hφ⟩)
  rw [hRA, smul_sub, smul_smul, negI_pnat_sq]
  module

/-- `Aₙ⁻φ → Aφ` on the domain. -/
theorem tendsto_yosidaApproxNeg_of_mem_domain (hA : IsSelfAdjoint A) (φ : H) (hφ : φ ∈ A.domain) :
    Tendsto (fun n : ℕ+ => yosidaApproxNeg hA n φ) atTop (𝓝 (A ⟨φ, hφ⟩)) := by
  simp only [fun n => yosidaApproxNeg_apply_of_mem_domain hA n φ hφ]
  exact tendsto_yosidaJNeg hA (A ⟨φ, hφ⟩)

/-- The symmetric approximant is the average of the two one-sided ones. -/
theorem yosidaApproxSym_eq_avg (hA : IsSelfAdjoint A) (n : ℕ+) :
    yosidaApproximantSym hA n = (1 / 2 : ℂ) • (yosidaApproximant hA n + yosidaApproxNeg hA n) := by
  unfold yosidaApproximantSym yosidaApproximant yosidaApproxNeg
  module

/-- `Aₙˢʸᵐφ → Aφ` on the domain. -/
theorem tendsto_yosidaApproxSym_of_mem_domain (hA : IsSelfAdjoint A) (φ : H) (hφ : φ ∈ A.domain) :
    Tendsto (fun n : ℕ+ => yosidaApproximantSym hA n φ) atTop (𝓝 (A ⟨φ, hφ⟩)) := by
  have hhalf : ((1 : ℂ) / 2) • (A ⟨φ, hφ⟩ + A ⟨φ, hφ⟩) = A ⟨φ, hφ⟩ := by module
  have := ((tendsto_yosidaApprox_of_mem_domain hA φ hφ).add
    (tendsto_yosidaApproxNeg_of_mem_domain hA φ hφ)).const_smul ((1 : ℂ) / 2)
  rw [hhalf] at this
  refine this.congr fun n => ?_
  rw [yosidaApproxSym_eq_avg hA n]
  rfl

/-! ### The approximating unitary groups `exp(i t Aₙˢʸᵐ)`

Spectra builds the bounded exponential from its power series and proves
summability, the group law, and unitarity by hand
(`YosidaHille/Approximation/ExpBounded/{Helpers,Adjoint,Unitary}.lean`, 576
lines).  **Mathlib already has all of it**: `NormedSpace.exp` on the C⋆-algebra
`H →L[ℂ] H`, and `selfAdjoint.expUnitary a = exp (I • a)`, which is by
construction a term of `unitary`.  So none of those three modules is ported. -/

/-- `t • Aₙˢʸᵐ` as an element of the self-adjoint subspace. -/
noncomputable def yosidaApproximantSymSA (hA : IsSelfAdjoint A) (n : ℕ+) (t : ℝ) :
    selfAdjoint (H →L[ℂ] H) :=
  ⟨(t : ℂ) • yosidaApproximantSym hA n, by
    rw [selfAdjoint.mem_iff, star_smul, (isSelfAdjoint_yosidaApproxSym hA n).star_eq,
      Complex.star_def, Complex.conj_ofReal]⟩

/-- The approximating unitary `exp(i t Aₙˢʸᵐ)`. -/
noncomputable def expApprox (hA : IsSelfAdjoint A) (n : ℕ+) (t : ℝ) : H →L[ℂ] H :=
  (selfAdjoint.expUnitary (yosidaApproximantSymSA hA n t) : H →L[ℂ] H)

/-- `exp(i·0·Aₙˢʸᵐ) = 1`. -/
@[simp] theorem expApprox_zero (hA : IsSelfAdjoint A) (n : ℕ+) :
    expApprox hA n 0 = 1 := by
  have h : yosidaApproximantSymSA hA n 0 = 0 := by
    ext
    simp [yosidaApproximantSymSA]
  simp [expApprox, h]

/-- The group law in `t`. -/
theorem expApprox_add (hA : IsSelfAdjoint A) (n : ℕ+) (s t : ℝ) :
    expApprox hA n (s + t) = expApprox hA n s * expApprox hA n t := by
  have hcomm : Commute ((yosidaApproximantSymSA hA n s : H →L[ℂ] H))
      ((yosidaApproximantSymSA hA n t : H →L[ℂ] H)) := by
    -- `Commute` unfolds to a product equation, but both factors are `yosidaApproximantSymSA`
    -- bundles; `smul_mul_smul_comm` is stated for plain `ContinuousLinearMap`, so the
    -- coercion has to be pushed through before it applies.
    change ((s : ℂ) • yosidaApproximantSym hA n) * ((t : ℂ) • yosidaApproximantSym hA n)
       = ((t : ℂ) • yosidaApproximantSym hA n) * ((s : ℂ) • yosidaApproximantSym hA n)
    rw [smul_mul_smul_comm, smul_mul_smul_comm, mul_comm ((s : ℂ)) ((t : ℂ))]
  have hsum : yosidaApproximantSymSA hA n (s + t)
      = yosidaApproximantSymSA hA n s + yosidaApproximantSymSA hA n t := by
    ext
    simp [yosidaApproximantSymSA, Complex.ofReal_add, add_smul]
  -- `expUnitary` returns a unitary, and the goal compares its coercion to a plain
  -- operator. No simp lemma unfolds `selfAdjoint.expUnitary` under the coercion, so
  -- `hcomm.expUnitary_add` cannot be rewritten against the goal as stated.
  change ((selfAdjoint.expUnitary (yosidaApproximantSymSA hA n (s + t))) : H →L[ℂ] H) = _
  rw [hsum, hcomm.expUnitary_add]
  rfl

/-- `exp(i t Aₙˢʸᵐ)` is unitary, hence preserves the inner product. -/
theorem inner_expApprox (hA : IsSelfAdjoint A) (n : ℕ+) (t : ℝ) (x y : H) :
    ⟪expApprox hA n t x, expApprox hA n t y⟫_ℂ = ⟪x, y⟫_ℂ := by
  have hstar : (ContinuousLinearMap.adjoint (expApprox hA n t)) * expApprox hA n t = 1 := by
    have := Unitary.coe_star_mul_self (selfAdjoint.expUnitary (yosidaApproximantSymSA hA n t))
    rwa [ContinuousLinearMap.star_eq_adjoint] at this
  calc ⟪expApprox hA n t x, expApprox hA n t y⟫_ℂ
      = ⟪(ContinuousLinearMap.adjoint (expApprox hA n t)) (expApprox hA n t x), y⟫_ℂ := by
        rw [ContinuousLinearMap.adjoint_inner_left]
    _ = ⟪((ContinuousLinearMap.adjoint (expApprox hA n t)) * expApprox hA n t) x, y⟫_ℂ := (rfl)
    _ = ⟪x, y⟫_ℂ := by rw [hstar]; rfl

/-! ### The approximants commute

Each `Aₙˢʸᵐ` is a scalar combination of resolvents, and resolvents commute, so
the symmetric approximants pairwise commute.  This is what lets the Duhamel
estimate be applied to the pair `(Aₘˢʸᵐ, Aₙˢʸᵐ)`. -/

/-- The symmetric Yosida approximants commute pairwise. -/
theorem commute_yosidaApproxSym (hA : IsSelfAdjoint A) (m n : ℕ+) :
    Commute (yosidaApproximantSym hA m) (yosidaApproximantSym hA n) := by
  have hIn : ∀ k : ℕ+, (I * (k : ℂ)) ∈ resolventSet A := fun k =>
    mem_resolventSet_of_im_ne_zero hA (I_mul_pnat_im_ne_zero k)
  have hNIn : ∀ k : ℕ+, (-I * (k : ℂ)) ∈ resolventSet A := fun k =>
    mem_resolventSet_of_im_ne_zero hA (neg_I_mul_pnat_im_ne_zero k)
  unfold yosidaApproximantSym resolventAtIn resolventAtNegIn
  refine Commute.smul_left ?_ _ |>.smul_right _
  refine Commute.add_left ?_ ?_ <;> refine Commute.add_right ?_ ?_ <;>
    first
      | exact resolvent_commute (hIn m) (hIn n)
      | exact resolvent_commute (hIn m) (hNIn n)
      | exact resolvent_commute (hNIn m) (hIn n)
      | exact resolvent_commute (hNIn m) (hNIn n)

/-! ### The approximating flows are Cauchy -/

/-- `expApprox` is the skew-adjoint exponential of `i Aₙˢʸᵐ`. -/
theorem expApprox_eq_expTime (hA : IsSelfAdjoint A) (n : ℕ+) (t : ℝ) :
    expApprox hA n t = expTime (I • yosidaApproximantSym hA n) t := by
  rw [expTime_def, TauCeti.real_smul_I_smul]
  rfl

/-- The Duhamel estimate, specialised to two approximants. -/
theorem norm_expApprox_sub_le (hA : IsSelfAdjoint A) (m n : ℕ+) (t : ℝ) (ψ : H) :
    ‖expApprox hA m t ψ - expApprox hA n t ψ‖
      ≤ |t| * ‖yosidaApproximantSym hA m ψ - yosidaApproximantSym hA n ψ‖ := by
  rw [expApprox_eq_expTime, expApprox_eq_expTime]
  have h := norm_expTime_sub_expTime_le (isSelfAdjoint_yosidaApproxSym hA m)
    (isSelfAdjoint_yosidaApproxSym hA n) (commute_yosidaApproxSym hA m n) t ψ
  refine h.trans (le_of_eq ?_)
  congr 1
  have : (I • yosidaApproximantSym hA m - I • yosidaApproximantSym hA n) ψ
      = I • (yosidaApproximantSym hA m ψ - yosidaApproximantSym hA n ψ) := by
    simp only [sub_apply, smul_apply, smul_sub]
  rw [this, norm_smul, Complex.norm_I, one_mul]

/-- On the domain, the approximating flows form a Cauchy sequence. -/
theorem cauchySeq_expApprox_of_mem_domain (hA : IsSelfAdjoint A) (t : ℝ)
    (ψ : H) (hψ : ψ ∈ A.domain) :
    CauchySeq (fun n : ℕ+ => expApprox hA n t ψ) := by
  have hconv := tendsto_yosidaApproxSym_of_mem_domain hA ψ hψ
  have hCauchy : CauchySeq (fun n : ℕ+ => yosidaApproximantSym hA n ψ) := hconv.cauchySeq
  rw [Metric.cauchySeq_iff] at hCauchy ⊢
  intro ε hε
  by_cases ht0 : t = 0
  · -- every term is `ψ`
    refine ⟨1, fun m _ n _ => ?_⟩
    subst ht0
    simpa [expApprox_zero] using hε
  · have ht : 0 < |t| := abs_pos.mpr ht0
    obtain ⟨N, hN⟩ := hCauchy (ε / |t|) (by positivity)
    refine ⟨N, fun m hm n hn => ?_⟩
    have hd := hN m hm n hn
    rw [dist_eq_norm] at hd ⊢
    calc ‖expApprox hA m t ψ - expApprox hA n t ψ‖
        ≤ |t| * ‖yosidaApproximantSym hA m ψ - yosidaApproximantSym hA n ψ‖ :=
          norm_expApprox_sub_le hA m n t ψ
      _ < |t| * (ε / |t|) := mul_lt_mul_of_pos_left hd ht
      _ = ε := by field_simp

/-- The approximating flows are isometric. -/
theorem norm_expApprox (hA : IsSelfAdjoint A) (n : ℕ+) (t : ℝ) (ψ : H) :
    ‖expApprox hA n t ψ‖ = ‖ψ‖ := by
  rw [expApprox_eq_expTime]
  exact norm_expTime_I_smul _ (isSelfAdjoint_yosidaApproxSym hA n) t ψ

/-- **The approximating flows are Cauchy at every vector**, by density and
isometry. -/
theorem cauchySeq_expApprox (hA : IsSelfAdjoint A) (t : ℝ) (ψ : H) :
    CauchySeq (fun n : ℕ+ => expApprox hA n t ψ) := by
  have hdense : Dense (A.domain : Set H) := hA.dense_domain
  rw [Metric.cauchySeq_iff]
  intro ε hε
  obtain ⟨φ, hφmem, hφclose⟩ := Metric.mem_closure_iff.mp
    (hdense.closure_eq ▸ Set.mem_univ ψ) (ε / 3) (by linarith)
  obtain ⟨N, hN⟩ := (Metric.cauchySeq_iff.mp
    (cauchySeq_expApprox_of_mem_domain hA t φ hφmem)) (ε / 3) (by linarith)
  refine ⟨N, fun m hm n hn => ?_⟩
  have hmφ : dist (expApprox hA m t ψ) (expApprox hA m t φ) = dist ψ φ := by
    rw [dist_eq_norm, dist_eq_norm, ← ContinuousLinearMap.map_sub, norm_expApprox]
  have hnφ : dist (expApprox hA n t φ) (expApprox hA n t ψ) = dist φ ψ := by
    rw [dist_eq_norm, dist_eq_norm, ← ContinuousLinearMap.map_sub, norm_expApprox]
  calc dist (expApprox hA m t ψ) (expApprox hA n t ψ)
      ≤ dist (expApprox hA m t ψ) (expApprox hA m t φ)
          + dist (expApprox hA m t φ) (expApprox hA n t φ)
          + dist (expApprox hA n t φ) (expApprox hA n t ψ) := dist_triangle4 _ _ _ _
    _ = dist ψ φ + dist (expApprox hA m t φ) (expApprox hA n t φ) + dist φ ψ := by
        rw [hmφ, hnφ]
    _ < ε / 3 + ε / 3 + ε / 3 := by
        refine add_lt_add (add_lt_add hφclose (hN m hm n hn)) ?_
        rw [dist_comm]
        exact hφclose
    _ = ε := by ring

/-! ### The limit flow `exp(itA)` -/

/-- The strong limit of the approximating flows, pointwise. -/
noncomputable def expLimitFun (hA : IsSelfAdjoint A) (t : ℝ) (ψ : H) : H :=
  limUnder atTop (fun n : ℕ+ => expApprox hA n t ψ)

/-- The approximating flows converge to `expLimitFun`.  This is the defining property: the limit is
defined as `limUnder`, which only names a value, so every fact about it is proved by transporting a
fact about the approximants along this convergence. -/
theorem tendsto_expLimitFun (hA : IsSelfAdjoint A) (t : ℝ) (ψ : H) :
    Tendsto (fun n : ℕ+ => expApprox hA n t ψ) atTop (𝓝 (expLimitFun hA t ψ)) :=
  (cauchySeq_expApprox hA t ψ).tendsto_limUnder

/-- The limit flow is additive, by uniqueness of limits applied to the additive approximants. -/
theorem expLimitFun_add (hA : IsSelfAdjoint A) (t : ℝ) (x y : H) :
    expLimitFun hA t (x + y) = expLimitFun hA t x + expLimitFun hA t y := by
  refine tendsto_nhds_unique (tendsto_expLimitFun hA t (x + y)) ?_
  simpa only [map_add] using
    (tendsto_expLimitFun hA t x).add (tendsto_expLimitFun hA t y)

/-- The limit flow is complex-homogeneous. -/
theorem expLimitFun_smul (hA : IsSelfAdjoint A) (t : ℝ) (c : ℂ) (x : H) :
    expLimitFun hA t (c • x) = c • expLimitFun hA t x := by
  refine tendsto_nhds_unique (tendsto_expLimitFun hA t (c • x)) ?_
  simpa only [map_smul] using (tendsto_expLimitFun hA t x).const_smul c

/-- The limit flow is norm-preserving: the approximants all are, and the norm passes to the
limit. -/
theorem norm_expLimitFun (hA : IsSelfAdjoint A) (t : ℝ) (ψ : H) :
    ‖expLimitFun hA t ψ‖ = ‖ψ‖ := by
  refine tendsto_nhds_unique ((tendsto_expLimitFun hA t ψ).norm) ?_
  simpa only [norm_expApprox] using tendsto_const_nhds

/-- The limit flow `exp(itA)` as a bounded operator. -/
@[expose]
noncomputable def expLimit (hA : IsSelfAdjoint A) (t : ℝ) : H →L[ℂ] H :=
  LinearMap.mkContinuous
    { toFun := expLimitFun hA t
      map_add' := expLimitFun_add hA t
      map_smul' := fun c x => by simpa using expLimitFun_smul hA t c x }
    1
    (fun ψ => by simp [norm_expLimitFun])

/-- The bundled limit flow acts as `expLimitFun`. -/
@[simp] theorem expLimit_apply (hA : IsSelfAdjoint A) (t : ℝ) (ψ : H) :
    expLimit hA t ψ = expLimitFun hA t ψ := (rfl)
/-- Norm preservation, restated for the bundled operator `expLimit`. -/

theorem norm_expLimit_apply (hA : IsSelfAdjoint A) (t : ℝ) (ψ : H) :
    ‖expLimit hA t ψ‖ = ‖ψ‖ := norm_expLimitFun hA t ψ

/-! ### The limit flow is a one-parameter unitary group -/

/-- The limit flow is the identity at time zero. -/
@[simp] theorem expLimit_zero (hA : IsSelfAdjoint A) : expLimit hA 0 = 1 := by
  ext ψ
  refine tendsto_nhds_unique (tendsto_expLimitFun hA 0 ψ) ?_
  simp [expApprox_zero]

/-- The limit flow preserves inner products.  With `norm_expLimit_apply` and the group law this
is what makes `expLimit` unitary rather than merely isometric. -/
theorem inner_expLimit (hA : IsSelfAdjoint A) (t : ℝ) (ψ φ : H) :
    ⟪expLimit hA t ψ, expLimit hA t φ⟫_ℂ = ⟪ψ, φ⟫_ℂ := by
  refine tendsto_nhds_unique
    (((tendsto_expLimitFun hA t ψ).inner (tendsto_expLimitFun hA t φ))) ?_
  simpa only [inner_expApprox] using tendsto_const_nhds

/-- The group law `exp(i(s+t)A) = exp(isA) ∘ exp(itA)`.  Proved by splitting the approximation
error in two, since the approximants satisfy it only in the limit. -/
theorem expLimit_add (hA : IsSelfAdjoint A) (s t : ℝ) :
    expLimit hA (s + t) = (expLimit hA s).comp (expLimit hA t) := by
  ext ψ
  refine tendsto_nhds_unique (tendsto_expLimitFun hA (s + t) ψ) ?_
  -- `expApprox n s (expApprox n t ψ) → U s (U t ψ)`: split the error in two
  have hstep : Tendsto (fun n : ℕ+ => expApprox hA n s (expApprox hA n t ψ)) atTop
      (𝓝 (expLimit hA s (expLimit hA t ψ))) := by
    rw [Metric.tendsto_atTop]
    intro ε hε
    obtain ⟨N₁, hN₁⟩ := (Metric.tendsto_atTop.mp (tendsto_expLimitFun hA t ψ)) (ε / 2)
      (by linarith)
    obtain ⟨N₂, hN₂⟩ := (Metric.tendsto_atTop.mp
      (tendsto_expLimitFun hA s (expLimit hA t ψ))) (ε / 2) (by linarith)
    refine ⟨max N₁ N₂, fun n hn => ?_⟩
    have h1 : dist (expApprox hA n s (expApprox hA n t ψ))
        (expApprox hA n s (expLimit hA t ψ)) < ε / 2 := by
      rw [dist_eq_norm, ← ContinuousLinearMap.map_sub, norm_expApprox, ← dist_eq_norm]
      exact hN₁ n (le_trans (le_max_left _ _) hn)
    have h2 : dist (expApprox hA n s (expLimit hA t ψ))
        (expLimit hA s (expLimit hA t ψ)) < ε / 2 :=
      hN₂ n (le_trans (le_max_right _ _) hn)
    calc dist (expApprox hA n s (expApprox hA n t ψ)) (expLimit hA s (expLimit hA t ψ))
        ≤ dist (expApprox hA n s (expApprox hA n t ψ))
            (expApprox hA n s (expLimit hA t ψ))
          + dist (expApprox hA n s (expLimit hA t ψ))
            (expLimit hA s (expLimit hA t ψ)) := dist_triangle _ _ _
      _ < ε / 2 + ε / 2 := add_lt_add h1 h2
      _ = ε := by ring
  refine hstep.congr fun n => ?_
  rw [expApprox_add]
  rfl

/-! ### Strong continuity -/

/-- Duhamel against the zero generator: `‖exp(iτAₙˢʸᵐ)ψ - ψ‖ ≤ |τ| ‖Aₙˢʸᵐψ‖`. -/
theorem norm_expApprox_sub_self_le (hA : IsSelfAdjoint A) (n : ℕ+) (τ : ℝ) (ψ : H) :
    ‖expApprox hA n τ ψ - ψ‖ ≤ |τ| * ‖yosidaApproximantSym hA n ψ‖ := by
  have hzero : expTime ((I : ℂ) • (0 : H →L[ℂ] H)) τ = 1 := by
    simp [expTime_def]
  have h := norm_expTime_sub_expTime_le (isSelfAdjoint_yosidaApproxSym hA n)
    (IsSelfAdjoint.zero (H →L[ℂ] H)) (Commute.zero_right _) τ ψ
  rw [hzero] at h
  simp only [one_apply_eq_self, smul_zero, sub_zero] at h
  rw [← expApprox_eq_expTime] at h
  refine h.trans (le_of_eq ?_)
  congr 1
  rw [show ((I : ℂ) • yosidaApproximantSym hA n) ψ
        = (I : ℂ) • (yosidaApproximantSym hA n ψ) from rfl,
    norm_smul, Complex.norm_I, one_mul]

/-- On the domain the limit flow is Lipschitz in `t`. -/
theorem norm_expLimit_sub_self_le (hA : IsSelfAdjoint A) (τ : ℝ)
    (ψ : H) (hψ : ψ ∈ A.domain) :
    ‖expLimit hA τ ψ - ψ‖ ≤ |τ| * ‖A ⟨ψ, hψ⟩‖ := by
  have hlim : Tendsto (fun n : ℕ+ => ‖expApprox hA n τ ψ - ψ‖) atTop
      (𝓝 ‖expLimit hA τ ψ - ψ‖) :=
    ((tendsto_expLimitFun hA τ ψ).sub tendsto_const_nhds).norm
  have hbnd : Tendsto (fun n : ℕ+ => |τ| * ‖yosidaApproximantSym hA n ψ‖) atTop
      (𝓝 (|τ| * ‖A ⟨ψ, hψ⟩‖)) :=
    ((tendsto_yosidaApproxSym_of_mem_domain hA ψ hψ).norm).const_mul _
  exact le_of_tendsto_of_tendsto' hlim hbnd fun n => norm_expApprox_sub_self_le hA n τ ψ

/-- `t ↦ exp(itA)ψ` is continuous for `ψ` in the domain. -/
theorem continuous_expLimit_of_mem_domain (hA : IsSelfAdjoint A)
    (ψ : H) (hψ : ψ ∈ A.domain) :
    Continuous (fun t : ℝ => expLimit hA t ψ) := by
  have hlip : ∀ s t : ℝ, ‖expLimit hA t ψ - expLimit hA s ψ‖ ≤ |t - s| * ‖A ⟨ψ, hψ⟩‖ := by
    intro s t
    have hsplit : expLimit hA t ψ = expLimit hA s (expLimit hA (t - s) ψ) := by
      rw [← ContinuousLinearMap.comp_apply, ← expLimit_add]
      congr 2
      ring
    rw [hsplit]
    have : expLimit hA s (expLimit hA (t - s) ψ) - expLimit hA s ψ
        = expLimit hA s (expLimit hA (t - s) ψ - ψ) := by
      rw [ContinuousLinearMap.map_sub]
    rw [this, norm_expLimit_apply]
    exact norm_expLimit_sub_self_le hA (t - s) ψ hψ
  rw [Metric.continuous_iff]
  intro s ε hε
  rcases eq_or_ne ‖A ⟨ψ, hψ⟩‖ 0 with h0 | h0
  · refine ⟨1, one_pos, fun t _ => ?_⟩
    have := hlip s t
    rw [h0, mul_zero] at this
    rw [dist_eq_norm]
    exact lt_of_le_of_lt this hε
  · have hpos : 0 < ‖A ⟨ψ, hψ⟩‖ := (norm_nonneg _).lt_of_ne' h0
    refine ⟨ε / ‖A ⟨ψ, hψ⟩‖, by positivity, fun t ht => ?_⟩
    rw [dist_eq_norm] at ht ⊢
    calc ‖expLimit hA t ψ - expLimit hA s ψ‖
        ≤ |t - s| * ‖A ⟨ψ, hψ⟩‖ := hlip s t
      _ < (ε / ‖A ⟨ψ, hψ⟩‖) * ‖A ⟨ψ, hψ⟩‖ := by
          exact mul_lt_mul_of_pos_right (by rwa [← Real.norm_eq_abs]) hpos
      _ = ε := by field_simp

/-- `t ↦ exp(itA)ψ` is continuous for every `ψ`, by density and isometry. -/
theorem continuous_expLimit (hA : IsSelfAdjoint A) (ψ : H) :
    Continuous (fun t : ℝ => expLimit hA t ψ) := by
  have hdense : Dense (A.domain : Set H) := hA.dense_domain
  rw [Metric.continuous_iff]
  intro s ε hε
  obtain ⟨φ, hφmem, hφclose⟩ := Metric.mem_closure_iff.mp
    (hdense.closure_eq ▸ Set.mem_univ ψ) (ε / 3) (by linarith)
  obtain ⟨δ, hδ, hcont⟩ := Metric.continuous_iff.mp
    (continuous_expLimit_of_mem_domain hA φ hφmem) s (ε / 3) (by linarith)
  refine ⟨δ, hδ, fun t ht => ?_⟩
  have hshift : ∀ r : ℝ, dist (expLimit hA r ψ) (expLimit hA r φ) = dist ψ φ := by
    intro r
    rw [dist_eq_norm, dist_eq_norm, ← ContinuousLinearMap.map_sub, norm_expLimit_apply]
  calc dist (expLimit hA t ψ) (expLimit hA s ψ)
      ≤ dist (expLimit hA t ψ) (expLimit hA t φ)
          + dist (expLimit hA t φ) (expLimit hA s φ)
          + dist (expLimit hA s φ) (expLimit hA s ψ) := dist_triangle4 _ _ _ _
    _ = dist ψ φ + dist (expLimit hA t φ) (expLimit hA s φ) + dist ψ φ := by
        rw [hshift t, dist_comm (expLimit hA s φ) (expLimit hA s ψ), hshift s]
    _ < ε / 3 + ε / 3 + ε / 3 :=
        add_lt_add (add_lt_add hφclose (hcont t ht)) hφclose
    _ = ε := by ring

/-- **Stone's theorem, the construction half.**  A self-adjoint operator
generates a one-parameter unitary group. -/
@[expose]
noncomputable def genToGroup (hA : IsSelfAdjoint A) : TauCeti.OneParameterUnitaryGroup H where
  U := expLimit hA
  unitary := inner_expLimit hA
  group_law := expLimit_add hA
  identity := by
    rw [expLimit_zero]
    rfl
  strong_continuous := continuous_expLimit hA

end LinearPMap
end TauCeti
