/-
Copyright (c) 2026 Nathan Pflueger. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nathan Pflueger
-/

import LeanPool.BrillNoetherGraphs.Bananas.Classification.BridgelessDegreeOneClasses
import LeanPool.BrillNoetherGraphs.Bananas.Classification.BridgelessGenusOneTopology
import LeanPool.BrillNoetherGraphs.Bananas.Classification.BridgelessGenusTwoClassification
import LeanPool.BrillNoetherGraphs.Bananas.Classification.BridgelessGenusTwoCornerAlgebra
import LeanPool.BrillNoetherGraphs.Bananas.Classification.BridgelessGenusTwoDegreeShape
import LeanPool.BrillNoetherGraphs.Bananas.Classification.BridgelessGenusTwoKGeneralReduction
import LeanPool.BrillNoetherGraphs.Bananas.Classification.BridgelessGenusTwoNonrecurrence
import LeanPool.BrillNoetherGraphs.Bananas.Classification.BridgelessGenusTwoPseudocore
import LeanPool.BrillNoetherGraphs.Bananas.Classification.BridgelessGenusTwoTopology
import LeanPool.BrillNoetherGraphs.Bananas.Classification.CorrectedBananaSimple
import LeanPool.BrillNoetherGraphs.Bananas.Classification.CorrectedBananaTheorem117
import LeanPool.BrillNoetherGraphs.Bananas.Classification.CorrectedBananaTorsion
import LeanPool.BrillNoetherGraphs.Bananas.Classification.CorrectedMidpointKGeneral
import LeanPool.BrillNoetherGraphs.Bananas.Classification.GenusOneKGeneral
import LeanPool.BrillNoetherGraphs.Bananas.Classification.GenusOneRankDelta
import LeanPool.BrillNoetherGraphs.Bananas.Classification.GenusTwoDegreeTwo
import LeanPool.BrillNoetherGraphs.Bananas.Classification.GenusTwoReduction
import LeanPool.BrillNoetherGraphs.Bananas.Classification.PointedGenusOneKGeneral
import LeanPool.BrillNoetherGraphs.Bananas.Classification.SciWeierstrass
import LeanPool.BrillNoetherGraphs.Bananas.Classification.WeierstrassPartition

/-! Supporting modules for Brill–Noether theory and gonality of finite graphs. -/
