/-
Copyright (c) 2026 Christopher Birkbeck, Alex Torzewski. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christopher Birkbeck, Alex Torzewski
-/
module


/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
public import LeanPool.UniformSheafyTateDomains.AdicSpaces.PerfectoidRing
public import Mathlib.RingTheory.WittVector.Basic

/-!
# Nonarchimedean Scottish Book — Problem 33

**Proposer:** Kiran Kedlaya
**Date:** 7 July 2020

## Problem Statement

Let (R, R+) be a perfectoid Huber pair in characteristic p. Equip W(R+) with the
(p, [x])-adic topology for a topologically nilpotent unit x in R. Is W(R+) sheafy?

## Notes

None.

## Status

Open.

## Formalization

We state: for a perfectoid ring `R` of characteristic `p` with pseudo-uniformizer `x`,
the ring of `p`-typical Witt vectors `W(R°)` (equipped with appropriate topology) is sheafy.

The Witt vector ring `WittVector p R°` carries a `(p, [x])`-adic topology generated by the
ideal `(p, [x])` where `[x]` is the Teichmuller lift of `x`. This topology is stated
existentially since constructing it requires substantial Witt vector infrastructure.
-/

@[expose] public section

open TopologicalRing ValuationSpectrum

namespace ScottishBook

universe u

/-- **Scottish Book Problem 33** (Kedlaya, 7 Jul 2020):
*For a perfectoid pair `(R, R⁺)` in characteristic `p`, the Witt vector ring `W(R⁺)` with
the `(p, [x])`-adic topology is sheafy.*

This is an **open problem** — the `sorry` is intentional and represents the open question.

The statement says: for a perfectoid ring `R` of characteristic `p`, there exists a sheafy
Huber pair structure on `WittVector p (powerBoundedSubring.toSubring R)`.
The topology is generated by the ideal `(p, [ϖ])` where `ϖ` is a pseudo-uniformizer. -/
theorem problem33
    (p : ℕ) [Fact (Nat.Prime p)]
    (R : Type u) [CommRing R] [TopologicalSpace R] [IsTopologicalRing R]
    [UniformSpace R] [IsLinearTopology R R]
    [CharP R p] [IsPerfectoidRing p R]
    [PlusSubring R] [IsHuberRing R] :
    let W := WittVector p ↥(powerBoundedSubring.toSubring R)
    ∃ (τ : TopologicalSpace W) (ps : @PlusSubring W _)
      (h₁ : @IsTopologicalRing W τ _)
      (h₂ : @IsHuberRing W _ τ)
      (hT2 : @T2Space W τ) (hNA : @NonarchimedeanRing W _ τ)
      (hCS : @CompleteSpace W
        (@IsTopologicalAddGroup.rightUniformSpace W _ τ (letI := h₁; inferInstance)))
      (hIR : @IsRingOfIntegralElements W _ τ (@PlusSubring.toSubring W _ ps)),
    @IsSheafy W _ τ h₁ ps h₂ hT2 hNA hCS hIR := by
  sorry

end ScottishBook
