/-
Copyright (c) 2026 Arseniy Akopyan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Arseniy Akopyan
-/
module


public import LeanPool.NandakumarRamanaRao.NRR.PrimePolyhedron.FoxNeuwirth.RouteBBadSetNullity
public import Mathlib.MeasureTheory.Measure.Prod

/-!
# Route B: vector-fiber elimination of the barycentric witness

The scalar-fiber argument of Step 4 is insufficient after existentially
quantifying over barycentric witnesses.  The correct fiber is the complete
`p`-vector attached to one retained movable vertex.

Fix all other vertex values.  If the selected vertex has positive barycentric
weight and the affine face value lies on the diagonal line, then its vector is
contained in the affine set generated by

* the remaining `p - 2` retained face vertices, and
* the diagonal direction `1`.

This affine set has dimension at most `(p - 2) + 1 = p - 1` in `Real^p`, and
therefore has zero `p`-dimensional Lebesgue measure.  Fubini then gives nullity
of the complete bad parameter set.

The Fubini lemma below supplies the measure-theoretic step. The concrete
vector-block geometry and coordinate transport are provided by the downstream
construction.
-/

public section

namespace NRR

open MeasureTheory
open scoped BigOperators

namespace FoxNeuwirthOrderComplex
namespace EquivariantPrismStableRelativeBoundary
namespace ExplicitAffineRelativeCollar
namespace RouteB

open Parameters
open RelativeGenericity
open EquivariantPrismGenericPerturbation

/-- A product set whose every vector fiber is null is null.  This is the exact
Fubini step needed by the vector-block argument. -/
theorem volume_prod_eq_zero_of_fiberwise_eq_zero
    {X Y : Type*}
    [MeasurableSpace X] [MeasurableSpace Y]
    (μ : Measure X) (ν : Measure Y)
     [SFinite ν]
    (s : Set (X × Y))
    (hs : MeasurableSet s)
    (hfiber : ∀ x, ν {y | (x, y) ∈ s} = 0) :
    (μ.prod ν) s = 0 := by
  rw [Measure.prod_apply hs]
  have hfiber' : (fun x => ν (Prod.mk x ⁻¹' s)) = 0 := by
    funext x
    exact hfiber x
  rw [hfiber']
  exact lintegral_zero

end RouteB
end ExplicitAffineRelativeCollar
end EquivariantPrismStableRelativeBoundary
end FoxNeuwirthOrderComplex
end NRR
