/-
Copyright (c) 2026 KT. Wu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: KT. Wu
-/
/-
  The Analytic σ-algebra σ(Σ₁¹)

  References:
  - Kechris, Classical Descriptive Set Theory, §18
  - Bertsekas–Shreve, Definition 7.19–7.20
-/
import LeanPool.BicausalOT.BicausalOT.DescriptiveSetTheory.AnalyticSet

/-!
# AnalyticSigmaAlgebra

Supporting results for bicausal optimal transport and measurable selection.
-/

open MeasureTheory Set

noncomputable section

variable {X : Type*} [TopologicalSpace X]

/-- σ(Σ₁¹): the σ-algebra generated by the analytic subsets. (BS, Def 7.19) -/
@[reducible]
def analyticMeasurableSpace (X : Type*) [TopologicalSpace X] : MeasurableSpace X :=
  MeasurableSpace.generateFrom { s : Set X | AnalyticSet s }

namespace MeasureTheory.AnalyticSet

theorem mem_analyticMeasurableSpace {s : Set X}
    (hs : AnalyticSet s) :
    @MeasurableSet X (analyticMeasurableSpace X) s :=
  MeasurableSpace.measurableSet_generateFrom hs

theorem compl_mem_analyticMeasurableSpace {s : Set X}
    (hs : AnalyticSet s) :
    @MeasurableSet X (analyticMeasurableSpace X) sᶜ :=
  hs.mem_analyticMeasurableSpace.compl

end MeasureTheory.AnalyticSet

theorem borel_le_analyticMeasurableSpace
    [PolishSpace X] [MeasurableSpace X] [BorelSpace X] :
    ‹MeasurableSpace X› ≤ analyticMeasurableSpace X :=
  fun _ hs => hs.analyticSet.mem_analyticMeasurableSpace

/-- Open sets in Polish spaces are analytic. -/
theorem IsOpen.analyticSet [PolishSpace X] {s : Set X} (hs : IsOpen s) :
    AnalyticSet s := by
  rw [show s = id '' s from (image_id s).symm]
  exact hs.analyticSet_image continuous_id

/-- A function is analytically measurable (BS, Def 7.20) if preimages of Borel
    sets in the codomain land in σ(Σ₁¹) on the domain. -/
def AnalyticallyMeasurable {Y : Type*} [TopologicalSpace Y]
    (f : X → Y) : Prop :=
  @Measurable X Y (analyticMeasurableSpace X) (borel Y) f

/-- Continuous functions between Polish spaces are analytically measurable. -/
theorem Continuous.analyticallyMeasurable
    [PolishSpace X]
    {Y : Type*} [TopologicalSpace Y]
    {f : X → Y} (hf : Continuous f) : AnalyticallyMeasurable f := by
  intro s hs
  induction hs with
  | basic s hs => exact (hf.isOpen_preimage _ hs).analyticSet.mem_analyticMeasurableSpace
  | empty => exact @MeasurableSet.empty X (analyticMeasurableSpace X)
  | compl _ _ ih => exact ih.compl
  | iUnion _ _ ih => rw [Set.preimage_iUnion]; exact .iUnion ih

/-- Composition: analytically measurable after Borel measurable is
    analytically measurable. Used for the general reduction. -/
theorem AnalyticallyMeasurable.comp_borel
    {Y Z : Type*} [TopologicalSpace Y] [TopologicalSpace Z]
    {f : X → Y} {g : Y → Z}
    (hf : AnalyticallyMeasurable f)
    (hg : @Measurable Y Z (borel Y) (borel Z) g) :
    AnalyticallyMeasurable (g ∘ f) :=
  fun _ hs => hf (hg hs)

/-- Continuous functions are Borel-Borel measurable. -/
theorem Continuous.borel_borel_measurable
    {Y : Type*} [TopologicalSpace Y]
    {f : X → Y} (hf : Continuous f) :
    @Measurable X Y (borel X) (borel Y) f := by
  intro s hs
  induction hs with
  | basic s hs => exact MeasurableSpace.measurableSet_generateFrom (hf.isOpen_preimage _ hs)
  | empty => exact @MeasurableSet.empty X (borel X)
  | compl _ _ ih => exact ih.compl
  | iUnion _ _ ih => rw [Set.preimage_iUnion]; exact .iUnion ih

/-- Composition of analytically measurable with continuous is
    analytically measurable. -/
theorem AnalyticallyMeasurable.comp_continuous
    {Y Z : Type*} [TopologicalSpace Y] [TopologicalSpace Z]
    {f : X → Y} {g : Y → Z}
    (hf : AnalyticallyMeasurable f) (hg : Continuous g) :
    AnalyticallyMeasurable (g ∘ f) :=
  hf.comp_borel hg.borel_borel_measurable

end
