/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, Claude Opus 5
-/
module

public import LeanPool.DavisKahan.DavisKahan.Sources.DavisKahan1970.TanTwoThetaUnboundedKyFan
public import LeanPool.DavisKahan.DavisKahan.Sources.DavisKahan1970.SineTheta.Lemma61
public import LeanPool.DavisKahan.ForTauCeti.Analysis.OperatorIdeal.ApproximationNumber.GramResolvent
public import LeanPool.DavisKahan.ForTauCeti.Analysis.OperatorIdeal.ApproximationNumber.TangentTransfer
public import LeanPool.DavisKahan.ForTauCeti.Analysis.OperatorIdeal.ApproximationNumber.SubspaceTransport
public import LeanPool.DavisKahan.DavisKahan.DoubleAngle.AngleTransport
public import LeanPool.DavisKahan.DavisKahan.InfiniteDimensional.DoubleAngle
public import LeanPool.DavisKahan.DavisKahan.Geometry.Polar.DirectRotation
public import LeanPool.DavisKahan.ForTauCeti.Analysis.SpecialFunctions.TanArcsin
public import LeanPool.DavisKahan.DavisKahan.Sources.DavisKahan1970.Ideals.SpectralSelection

/-! # Tan Two Theta Unbounded Gram Bridge -/

@[expose] public section

open TauCeti.DavisKahan.Angle


open TauCeti.DavisKahan.Sylvester

/-!
# The typed tangent/sine Gram-resolvent bridge in the unbounded reflection picture

`TanTwoThetaUnboundedKyFan.lean` builds the genuine reflection tangent
`tan 2Θ₀ = sin 2Θ₀ · (cos 2Θ₀)⁻¹` as `unboundedReflectionTangent U Z`, an
*ambient* operator on `H`.  This module compresses it to the directed block
coordinate `U → Uᗮ` and proves the approximation-number transfer

`aₙ(T₀) ≤ tan (arcsin aₙ(S₀))`

for the directed tangent corner `T₀` and the directed sine corner `S₀`.

## Why the typed corners

`unboundedReflectionTangent U Z` carries *both* off-diagonal corners `U → Uᗮ`
and `Uᗮ → U`, so its approximation-number sequence lists each directed singular
value twice.  Every statement here is therefore phrased with
`blockCompression Uᗮ U`, which is the `U → Uᗮ` corner as a map between the
subspaces themselves.

## The route

The reflection blocks `C = U.diagonalPart Z` and `S = U.offDiagonalPart Z` of an
involution satisfy `C² + S² = 1`, and the tangent satisfies `T C = S`.  Writing
`D = (C²)⁻¹` this forces the closed form

`T⋆T = D - 1`,

from which the Gram resolvent equation `T⋆T = S² + S² (T⋆T)` is pure algebra in
the commutative subalgebra generated by `C²`.  Because `T` maps `U` into `Uᗮ`
and `T⋆` maps `Uᗮ` into `U`, that ambient identity restricts verbatim to the
typed corners, and `TauCeti.ApproximationNumber.approximationNumber_le_of_gramResolvent`
applies with `X := S₀` and the endomorphism slot filled by `gramOperator T₀`.

No extremality, attainment or eigenbasis hypothesis occurs anywhere: the
statement is about the two corners alone.

## Main results

* `gramOperator_reflectionTangentCorner_moebius` — the typed Gram resolvent
  equation.
* `approximationNumber_reflectionTangentCorner_le` — Checkpoint A,
  `aₙ(T₀) ≤ tan (arcsin aₙ(S₀))`.
* `approximationNumber_reflectionTangentCorner` — the same as an *equality*, so
  the corner carries the paper's `|tan 2θⱼ|` sequence exactly.

## References

* C. Davis and W. M. Kahan, *The rotation of eigenvectors by a perturbation.
  III*, SIAM J. Numer. Anal. 7 (1970), 1--46, Section 7.
-/

namespace TauCeti
namespace DavisKahan1970

open scoped InnerProductSpace

open TauCeti.DavisKahan.ExactSinTheta
open TauCeti.ApproximationNumber
open scoped TauCeti.CompleteSubspace

noncomputable section

universe u

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H]

variable {U : Submodule ℂ H} [U.HasOrthogonalProjection] {Z : H →L[ℂ] H}

/-! ### A commutation lemma for `Ring.inverse` -/

/-- An element commuting with a unit commutes with that unit's ring inverse.
Mathlib has the statement for `Invertible` and for groups, but not for
`Ring.inverse` of an `IsUnit`, which is the form the reflection blocks produce. -/
theorem commute_ringInverse {R : Type*} [Ring R] {x u : R} (hu : IsUnit u)
    (h : Commute x u) : Commute x (Ring.inverse u) := by
  have h1 : u * Ring.inverse u = 1 := Ring.mul_inverse_cancel u hu
  have h2 : Ring.inverse u * u = 1 := Ring.inverse_mul_cancel u hu
  have e1 : Ring.inverse u * (x * u) * Ring.inverse u = Ring.inverse u * x := by
    calc Ring.inverse u * (x * u) * Ring.inverse u
        = Ring.inverse u * x * (u * Ring.inverse u) := by noncomm_ring
      _ = Ring.inverse u * x := by rw [h1, mul_one]
  have e2 : Ring.inverse u * (u * x) * Ring.inverse u = x * Ring.inverse u := by
    calc Ring.inverse u * (u * x) * Ring.inverse u
        = Ring.inverse u * u * x * Ring.inverse u := by noncomm_ring
      _ = x * Ring.inverse u := by rw [h2, one_mul]
  have hxu : x * u = u * x := h.eq
  exact ((e1.symm.trans (by rw [hxu])).trans e2).symm

/-! ### The block structure of the reflection tangent -/

variable (U Z) in
omit [CompleteSpace H] in
/-- The orthogonal projection commutes with the diagonal block: `P C = C P`.
This is the operator form of "`C` preserves both `U` and `Uᗮ`". -/
theorem commute_starProjection_diagonalPart :
    Commute U.starProjection (U.diagonalPart Z) := by
  change U.starProjection * U.diagonalPart Z = U.diagonalPart Z * U.starProjection
  refine ContinuousLinearMap.ext fun x => ?_
  simp only [_root_.mul_apply_eq_comp]
  have hsplit : U.starProjection x + Uᗮ.starProjection x = x :=
    Submodule.starProjection_add_starProjection_orthogonal x
  have hpU : U.starProjection x ∈ U := U.starProjection_apply_mem x
  have hrU : Uᗮ.starProjection x ∈ Uᗮ := Uᗮ.starProjection_apply_mem x
  have hCp : U.diagonalPart Z (U.starProjection x) ∈ U :=
    TauCeti.diagonalPart_mem_of_mem U Z hpU
  have hCr : U.diagonalPart Z (Uᗮ.starProjection x) ∈ Uᗮ :=
    TauCeti.diagonalPart_mem_orthogonal_of_mem_orthogonal U Z hrU
  have hexp : U.diagonalPart Z x =
      U.diagonalPart Z (U.starProjection x) +
        U.diagonalPart Z (Uᗮ.starProjection x) := by
    rw [← map_add, hsplit]
  rw [hexp, map_add, Submodule.starProjection_eq_self_iff.mpr hCp,
    (Submodule.starProjection_apply_eq_zero_iff (K := U)).mpr hCr, add_zero]

variable (U Z) in
omit [CompleteSpace H] in
/-- The reflection tangent, unfolded.  The definition lives in a different
module, so consumers rewrite with this. -/
theorem unboundedReflectionTangent_eq :
    unboundedReflectionTangent U Z =
      U.offDiagonalPart Z *
        Ring.inverse (U.diagonalPart Z * U.diagonalPart Z) * U.diagonalPart Z :=
  rfl

variable (U Z) in
omit [CompleteSpace H] in
/-- The inverse of the squared diagonal block preserves `U`. -/
theorem ringInverse_diagonalPart_sq_mem_of_mem
    (hCC : IsUnit (U.diagonalPart Z * U.diagonalPart Z)) {y : H} (hy : y ∈ U) :
    Ring.inverse (U.diagonalPart Z * U.diagonalPart Z) y ∈ U := by
  have hcomm : Commute U.starProjection
      (Ring.inverse (U.diagonalPart Z * U.diagonalPart Z)) :=
    commute_ringInverse hCC
      ((commute_starProjection_diagonalPart U Z).mul_right
        (commute_starProjection_diagonalPart U Z))
  have h := congrArg (fun S : H →L[ℂ] H => S y) hcomm.eq
  simp only [_root_.mul_apply_eq_comp] at h
  refine Submodule.starProjection_eq_self_iff.mp ?_
  rw [h, Submodule.starProjection_eq_self_iff.mpr hy]

variable (U Z) in
omit [CompleteSpace H] in
/-- The reflection tangent carries `U` into `Uᗮ`: it is a purely off-diagonal
operator. -/
theorem unboundedReflectionTangent_mem_orthogonal_of_mem
    (hCC : IsUnit (U.diagonalPart Z * U.diagonalPart Z)) {y : H} (hy : y ∈ U) :
    unboundedReflectionTangent U Z y ∈ Uᗮ := by
  rw [unboundedReflectionTangent_eq]
  simp only [_root_.mul_apply_eq_comp]
  exact TauCeti.offDiagonalPart_mem_orthogonal_of_mem U Z
    (ringInverse_diagonalPart_sq_mem_of_mem U Z hCC
      (TauCeti.diagonalPart_mem_of_mem U Z hy))

/-! ### The ambient Gram resolvent identity -/

variable (U Z) in
/-- **The closed form of the tangent's Gram operator.**  `T⋆T = (cos² 2Θ₀)⁻¹ - 1`.

This is the whole of the Möbius transfer: it needs only `T C = S`, `C² + S² = 1`
and invertibility of `C²`, and it puts `T⋆T` inside the commutative subalgebra
generated by `C²`. -/
theorem adjoint_mul_unboundedReflectionTangent
    (hZsa : IsSelfAdjoint Z) (hZ2 : Z * Z = 1)
    (hCC : IsUnit (U.diagonalPart Z * U.diagonalPart Z)) :
    (unboundedReflectionTangent U Z).adjoint * unboundedReflectionTangent U Z =
      Ring.inverse (U.diagonalPart Z * U.diagonalPart Z) - 1 := by
  set C := U.diagonalPart Z with hCdef
  set S := U.offDiagonalPart Z with hSdef
  set T := unboundedReflectionTangent U Z with hTdef
  set D := Ring.inverse (C * C) with hDdef
  have hCsa : IsSelfAdjoint C := TauCeti.isSelfAdjoint_diagonalPart (U := U) hZsa
  have hSsa : IsSelfAdjoint S := TauCeti.isSelfAdjoint_offDiagonalPart (U := U) hZsa
  have hTC : T * C = S := unboundedReflectionTangent_comp_diagonalPart hCC
  -- the adjoint form `C T⋆ = S`
  have hCT : C * T.adjoint = S := by
    have h := congrArg ContinuousLinearMap.adjoint hTC
    rw [ContinuousLinearMap.mul_def, ContinuousLinearMap.adjoint_comp,
      ← ContinuousLinearMap.mul_def, hCsa.adjoint_eq, hSsa.adjoint_eq] at h
    exact h
  -- the sandwiched Gram operator
  have hsand : C * (T.adjoint * T) * C = S * S := by
    calc C * (T.adjoint * T) * C = (C * T.adjoint) * (T * C) := by noncomm_ring
      _ = S * S := by rw [hCT, hTC]
  have hSS : S * S = 1 - C * C := by
    have h := TauCeti.diagonalPart_sq_add_offDiagonalPart_sq (U := U) hZ2
    rw [← hCdef, ← hSdef] at h
    rw [← h]
    abel
  have hDc : D * (C * C) = 1 := Ring.inverse_mul_cancel _ hCC
  have hcD : (C * C) * D = 1 := Ring.mul_inverse_cancel _ hCC
  calc T.adjoint * T
      = D * (C * C) * (T.adjoint * T) * ((C * C) * D) := by
        rw [hDc, hcD, one_mul, mul_one]
    _ = D * (C * (C * (T.adjoint * T) * C) * C) * D := by noncomm_ring
    _ = D * (C * (S * S) * C) * D := by rw [hsand]
    _ = D * (C * (1 - C * C) * C) * D := by rw [hSS]
    _ = D * (C * C) * D - D * (C * C) * ((C * C) * D) := by noncomm_ring
    _ = D - 1 := by rw [hDc, one_mul, one_mul, hcD]

variable (U Z) in
/-- **The ambient Gram resolvent equation.**  `T⋆T = S² + S² (T⋆T)`, that is
`tan² = sin² + sin² tan²`. -/
theorem adjoint_mul_unboundedReflectionTangent_moebius
    (hZsa : IsSelfAdjoint Z) (hZ2 : Z * Z = 1)
    (hCC : IsUnit (U.diagonalPart Z * U.diagonalPart Z)) :
    (unboundedReflectionTangent U Z).adjoint * unboundedReflectionTangent U Z =
      U.offDiagonalPart Z * U.offDiagonalPart Z +
        U.offDiagonalPart Z * U.offDiagonalPart Z *
          ((unboundedReflectionTangent U Z).adjoint *
            unboundedReflectionTangent U Z) := by
  set C := U.diagonalPart Z with hCdef
  set S := U.offDiagonalPart Z with hSdef
  set D := Ring.inverse (C * C) with hDdef
  have hG : (unboundedReflectionTangent U Z).adjoint *
      unboundedReflectionTangent U Z = D - 1 :=
    adjoint_mul_unboundedReflectionTangent U Z hZsa hZ2 hCC
  have hSS : S * S = 1 - C * C := by
    have h := TauCeti.diagonalPart_sq_add_offDiagonalPart_sq (U := U) hZ2
    rw [← hCdef, ← hSdef] at h
    rw [← h]
    abel
  have hcD : (C * C) * D = 1 := Ring.mul_inverse_cancel _ hCC
  rw [hG, hSS]
  have hexp : (1 - C * C) + (1 - C * C) * (D - 1) = D - (C * C) * D := by
    noncomm_ring
  rw [hexp, hcD]

/-! ### The typed corners -/

section ScalarGenericCorners

variable {𝕜 : Type*} [RCLike 𝕜] {G : Type u} [NormedAddCommGroup G]
  [InnerProductSpace 𝕜 G] [CompleteSpace G]

/-- The directed sine corner `S₀ : U → Uᗮ`. -/
abbrev reflectionSineCorner (U : Submodule 𝕜 G) [U.HasOrthogonalProjection]
    (Z : G →L[𝕜] G) : U →L[𝕜] Uᗮ := blockCompression Uᗮ U Z

/-- **A compression out of `Γ` does not see the reflection through `Γ`.**

`blockCompression Ω Γ K` feeds `K` only vectors of `Γ`, and the reflection
through `Γ` fixes those, so post-composing `K` with it changes nothing.  This is
what lets a corner of the reflection tangent be read as a corner of the paper's
own double-angle representative. -/
theorem blockCompression_mul_reflectionOperator
    (Ω Γ : Submodule 𝕜 G) [Ω.HasOrthogonalProjection] [Γ.HasOrthogonalProjection]
    (K : G →L[𝕜] G) :
    blockCompression Ω Γ (K * Γ.reflectionOperator)
      = blockCompression Ω Γ K := by
  ext x
  simp only [blockCompression, ContinuousLinearMap.coe_comp, Function.comp_apply,
    mul_apply_eq_comp, Submodule.subtypeL_apply]
  rw [Submodule.reflectionOperator_apply_of_mem Γ x.2]

/-- **A `Γ → Γᗮ` compression only sees the `Γᗮ ← Γ` block of a diagonal pair.**

`diagonalPair Γᗮ Γ K` is `P_Γᗮ K P_Γ + P_Γ K P_Γᗮ`.  Compressed out of `Γ`,
the second summand dies -- it starts by projecting onto `Γᗮ`, which kills every
vector of `Γ` -- and the first is the block itself, because the compression's
own adjoint already projects onto `Γᗮ`.

This is the step from the paper's block representative to the block spelling its
directed corner uses. -/
theorem blockCompression_diagonalPair
    (Γ : Submodule 𝕜 G) [Γ.HasOrthogonalProjection] [Γᗮ.HasOrthogonalProjection]
    (K : G →L[𝕜] G) :
    blockCompression Γᗮ Γ (diagonalPair Γᗮ Γ K)
      = blockCompression Γᗮ Γ K := by
  ext x
  have hzero : Γᗮ.starProjection (x : G) = 0 :=
    Submodule.starProjection_orthogonal_apply_eq_zero x.2
  have hself : Γ.starProjection (x : G) = (x : G) :=
    Submodule.starProjection_eq_self_iff.mpr x.2
  simp only [blockCompression, diagonalPair, ContinuousLinearMap.coe_comp,
    Function.comp_apply, add_apply, Submodule.subtypeL_apply,
    hzero, hself, map_zero, add_zero, Submodule.adjoint_subtypeL]
  rw [← Submodule.starProjection_apply, ← Submodule.starProjection_apply]
  exact Submodule.starProjection_eq_self_iff.mpr (Γᗮ.starProjection_apply_mem _)

/-- The directed tangent corner `T₀ : U → Uᗮ`. -/
abbrev reflectionTangentCorner (U : Submodule 𝕜 G) [U.HasOrthogonalProjection]
    (Z : G →L[𝕜] G) : U →L[𝕜] Uᗮ :=
  blockCompression Uᗮ U (unboundedReflectionTangent U Z)

section CompressionAlgebra

variable (Ω Γ : Submodule 𝕜 G) [Ω.HasOrthogonalProjection] [Γ.HasOrthogonalProjection]

/-- The adjoint of a block compression is the transposed block compression of
the adjoint. -/
theorem adjoint_blockCompression (K : G →L[𝕜] G) :
    (blockCompression Ω Γ K).adjoint = blockCompression Γ Ω K.adjoint := by
  rw [blockCompression, blockCompression, ContinuousLinearMap.adjoint_comp,
    ContinuousLinearMap.adjoint_comp, ContinuousLinearMap.adjoint_adjoint,
    ContinuousLinearMap.comp_assoc]

omit [Γ.HasOrthogonalProjection] in
/-- The block compression, evaluated in the ambient space. -/
theorem coe_blockCompression_apply (K : G →L[𝕜] G) (y : Γ) :
    ((blockCompression Ω Γ K y : Ω) : G) = Ω.starProjection (K (y : G)) := by
  rw [blockCompression]
  simp only [ContinuousLinearMap.comp_apply, Submodule.subtypeL_apply,
    Submodule.adjoint_subtypeL]
  exact Submodule.coe_orthogonalProjectionOnto_apply Ω _

end CompressionAlgebra

end ScalarGenericCorners

section GramCompressionAlgebra

variable (Ω Γ : Submodule ℂ H) [Ω.HasOrthogonalProjection] [Γ.HasOrthogonalProjection]

/-- The Gram operator of a block compression, evaluated in the ambient space.
`gramOperator` is complex-only, so this companion of
`coe_blockCompression_apply` stays at `ℂ`. -/
theorem coe_gramOperator_blockCompression_apply (K : H →L[ℂ] H) (y : Γ) :
    ((gramOperator (blockCompression Ω Γ K) y : Γ) : H) =
      Γ.starProjection (K.adjoint (Ω.starProjection (K (y : H)))) := by
  rw [gramOperator]
  simp only [ContinuousLinearMap.comp_apply]
  rw [adjoint_blockCompression, coe_blockCompression_apply,
    coe_blockCompression_apply]

end GramCompressionAlgebra

/-- The Gram operator of the directed sine corner is the ambient `S²`,
restricted to `U`. -/
theorem coe_gramOperator_reflectionSineCorner_apply (hZsa : IsSelfAdjoint Z)
    (y : U) :
    ((gramOperator (reflectionSineCorner U Z) y : U) : H) =
      U.offDiagonalPart Z (U.offDiagonalPart Z (y : H)) := by
  rw [reflectionSineCorner, coe_gramOperator_blockCompression_apply,
    hZsa.adjoint_eq]
  have h1 : Uᗮ.starProjection (Z (y : H)) = U.offDiagonalPart Z (y : H) :=
    (TauCeti.offDiagonalPart_apply_of_mem U Z y.2).symm
  rw [h1]
  have h2 : U.starProjection (Z (U.offDiagonalPart Z (y : H))) =
      U.offDiagonalPart Z (U.offDiagonalPart Z (y : H)) :=
    (TauCeti.offDiagonalPart_apply_of_mem_orthogonal U Z
      (TauCeti.offDiagonalPart_mem_orthogonal_of_mem U Z y.2)).symm
  rw [h2]

/-- The Gram operator of the directed tangent corner is the ambient `T⋆T`,
restricted to `U`. -/
theorem coe_gramOperator_reflectionTangentCorner_apply
    (hZsa : IsSelfAdjoint Z) (hZ2 : Z * Z = 1)
    (hCC : IsUnit (U.diagonalPart Z * U.diagonalPart Z)) (y : U) :
    ((gramOperator (reflectionTangentCorner U Z) y : U) : H) =
      ((unboundedReflectionTangent U Z).adjoint *
        unboundedReflectionTangent U Z) (y : H) := by
  rw [reflectionTangentCorner, coe_gramOperator_blockCompression_apply]
  have hTy : unboundedReflectionTangent U Z (y : H) ∈ Uᗮ :=
    unboundedReflectionTangent_mem_orthogonal_of_mem U Z hCC y.2
  rw [Submodule.starProjection_eq_self_iff.mpr hTy]
  have hG : ((unboundedReflectionTangent U Z).adjoint *
      unboundedReflectionTangent U Z) (y : H) ∈ U := by
    rw [adjoint_mul_unboundedReflectionTangent U Z hZsa hZ2 hCC]
    simp only [_root_.sub_apply, _root_.one_apply_eq_self]
    exact U.sub_mem (ringInverse_diagonalPart_sq_mem_of_mem U Z hCC y.2) y.2
  rw [show (unboundedReflectionTangent U Z).adjoint
        (unboundedReflectionTangent U Z (y : H)) =
      ((unboundedReflectionTangent U Z).adjoint *
        unboundedReflectionTangent U Z) (y : H) from rfl,
    Submodule.starProjection_eq_self_iff.mpr hG]

/-- **The typed Gram resolvent equation.**  On the trial subspace,

`gramOperator T₀ = gramOperator S₀ + gramOperator S₀ ∘ gramOperator T₀`,

which is exactly the hypothesis shape of
`TauCeti.ApproximationNumber.approximationNumber_le_of_gramResolvent`. -/
theorem gramOperator_reflectionTangentCorner_moebius
    (hZsa : IsSelfAdjoint Z) (hZ2 : Z * Z = 1)
    (hCC : IsUnit (U.diagonalPart Z * U.diagonalPart Z)) (y : U) :
    gramOperator (reflectionTangentCorner U Z) y =
      gramOperator (reflectionSineCorner U Z) y +
        gramOperator (reflectionSineCorner U Z)
          (gramOperator (reflectionTangentCorner U Z) y) := by
  refine Subtype.ext ?_
  rw [Submodule.coe_add,
    coe_gramOperator_reflectionTangentCorner_apply hZsa hZ2 hCC,
    coe_gramOperator_reflectionSineCorner_apply hZsa,
    coe_gramOperator_reflectionSineCorner_apply hZsa,
    coe_gramOperator_reflectionTangentCorner_apply hZsa hZ2 hCC]
  have h := congrArg (fun S : H →L[ℂ] H => S (y : H))
    (adjoint_mul_unboundedReflectionTangent_moebius U Z hZsa hZ2 hCC)
  simpa only [_root_.add_apply, _root_.mul_apply_eq_comp] using h

/-- The directed sine corner is bounded by the ambient odd block. -/
theorem norm_reflectionSineCorner_le :
    ‖reflectionSineCorner U Z‖ ≤ ‖U.offDiagonalPart Z‖ := by
  refine ContinuousLinearMap.opNorm_le_bound _ (norm_nonneg _) fun y => ?_
  have hcoe : ((reflectionSineCorner U Z y : Uᗮ) : H) =
      U.offDiagonalPart Z (y : H) := by
    rw [reflectionSineCorner, coe_blockCompression_apply]
    exact (TauCeti.offDiagonalPart_apply_of_mem U Z y.2).symm
  have hn : ‖reflectionSineCorner U Z y‖ = ‖U.offDiagonalPart Z (y : H)‖ := by
    rw [← hcoe]
    rfl
  rw [hn]
  exact (U.offDiagonalPart Z).le_opNorm _

/-! ### Checkpoint A -/

/-- **Checkpoint A: the directed tangent corner is dominated by the directed
sine corner through the tangent of the arcsine.**

`aₙ(T₀) ≤ tan (arcsin aₙ(S₀))`.

The only hypotheses are self-adjointness and involutivity of the reflection and
the pole exclusion `‖sin 2Θ₀‖ < 1`.  No eigenfamily, no extremality clause, no
finite-rank selection. -/
theorem approximationNumber_reflectionTangentCorner_le
    (hZsa : IsSelfAdjoint Z) (hZ2 : Z * Z = 1)
    (hS1 : ‖U.offDiagonalPart Z‖ < 1) (n : ℕ) :
    (reflectionTangentCorner U Z).approximationNumber n ≤
      Real.tan (Real.arcsin
        ((reflectionSineCorner U Z).approximationNumber n)) := by
  have hCC : IsUnit (U.diagonalPart Z * U.diagonalPart Z) := by
    refine isUnit_diagonalPart_sq hZ2 ?_
    have h := norm_mul_le (U.offDiagonalPart Z) (U.offDiagonalPart Z)
    nlinarith [norm_nonneg (U.offDiagonalPart Z)]
  have hX1 : ‖reflectionSineCorner U Z‖ < 1 :=
    lt_of_le_of_lt norm_reflectionSineCorner_le hS1
  set sig := (reflectionSineCorner U Z).approximationNumber n with hsigdef
  have hsig0 : 0 ≤ sig := ContinuousLinearMap.approximationNumber_nonneg _ _
  have hsiglt : sig < 1 :=
    lt_of_le_of_lt (ContinuousLinearMap.approximationNumber_le_norm _ n) hX1
  have hres := approximationNumber_le_of_gramResolvent (reflectionSineCorner U Z)
    hX1 (gramOperator_reflectionTangentCorner_moebius hZsa hZ2 hCC) n
  rw [approximationNumber_gramOperator_complex (reflectionTangentCorner U Z) n] at hres
  have hden : (0 : ℝ) < 1 - sig ^ 2 := by nlinarith
  have hsqrt : Real.sqrt (1 - sig ^ 2) * Real.sqrt (1 - sig ^ 2) = 1 - sig ^ 2 :=
    Real.mul_self_sqrt hden.le
  have htanSq : Real.tan (Real.arcsin sig) ^ 2 = sig ^ 2 / (1 - sig ^ 2) := by
    rw [Real.tan_arcsin, div_pow]
    congr 1
    nlinarith [hsqrt]
  have hc0 : 0 ≤ (reflectionTangentCorner U Z).approximationNumber n :=
    ContinuousLinearMap.approximationNumber_nonneg _ _
  have ht0 : 0 ≤ Real.tan (Real.arcsin sig) := TanArcsin.tanArcsin_nonneg hsig0
  nlinarith [hres, htanSq]

/-- **Checkpoint A, as an equality.**

`aₙ(T₀) = tan (arcsin aₙ(S₀))` for every `n`: the directed tangent corner does
not merely obey the tangent bound, it *is* the tangent of the angle the directed
sine corner presents, singular value by singular value.

The reverse of `approximationNumber_reflectionTangentCorner_le` was out of reach
while only the forward Gram-resolvent transfer existed.  It is the *forward*
transfer for the inverse Möbius map `u ↦ u/(1+u)`, which is what
`TauCeti.ApproximationNumber.approximationNumber_le_of_gramContraction` supplies;
`approximationNumber_eq_tanArcsin_of_gramMoebius` puts the two together, and the
typed Gram relation `gramOperator_reflectionTangentCorner_moebius` is exactly its
hypothesis.

This is the statement a `tan 2Θ₀` bound in a unitarily invariant norm needs: the
paper's `tan 2Θ₀` is the sequence `|tan 2θⱼ|`, and this says the corner's
singular values are that sequence, each directed angle appearing once. -/
theorem approximationNumber_reflectionTangentCorner
    (hZsa : IsSelfAdjoint Z) (hZ2 : Z * Z = 1)
    (hS1 : ‖U.offDiagonalPart Z‖ < 1) (n : ℕ) :
    (reflectionTangentCorner U Z).approximationNumber n =
      Real.tan (Real.arcsin
        ((reflectionSineCorner U Z).approximationNumber n)) := by
  have hCC : IsUnit (U.diagonalPart Z * U.diagonalPart Z) := by
    refine isUnit_diagonalPart_sq hZ2 ?_
    have h := norm_mul_le (U.offDiagonalPart Z) (U.offDiagonalPart Z)
    nlinarith [norm_nonneg (U.offDiagonalPart Z)]
  have hX1 : ‖reflectionSineCorner U Z‖ < 1 :=
    lt_of_le_of_lt norm_reflectionSineCorner_le hS1
  exact approximationNumber_eq_tanArcsin_of_gramMoebius (reflectionSineCorner U Z)
    (reflectionTangentCorner U Z) hX1
    (gramOperator_reflectionTangentCorner_moebius hZsa hZ2 hCC) n

section IdealBlockBridge

variable (U V : Submodule ℂ H) [U.HasOrthogonalProjection] [V.HasOrthogonalProjection]

/-- **The directed sine corner carries the paper's `sin 2Θ₀` singular values.**

`reflectionSineCorner U J_V : U → Uᗮ` is `P_{Uᗮ} J_V |_U`, the corner the
unbounded `tan 2Θ` argument works in.  `DavisKahan.sinTwoThetaIdealBlock U V` is
`P_U P_{J_V Uᗮ}`, the ambient block whose approximation numbers
`DavisKahan.sinTwoThetaIdealBlock_hasSameApproximationNumbers` identifies with
those of the paper's `sin 2Θ₀`.  The two have the same singular values.

The route is three moves and no defect hypothesis: extending the corner to the
ambient space gives `P_{Uᗮ} J_V P_U`; taking adjoints gives `P_U J_V P_{Uᗮ}`;
and `P_{J_V Uᗮ} = J_V P_{Uᗮ} J_V` turns the ideal block into that same operator
composed with the involution `J_V`, which no singular value sees.

In particular each principal angle is counted **once**, as the directed
statement requires -- the ambient `unboundedReflectionTangent U J_V` counts it
twice, which is why the directed clause must not be routed through it. -/
theorem hasSameApproximationNumbers_reflectionSineCorner_sinTwoThetaIdealBlock :
    (reflectionSineCorner U V.reflectionOperator).HasSameApproximationNumbers
      (DavisKahan.sinTwoThetaIdealBlock U V) := by
  set J : H →L[ℂ] H := V.reflectionOperator with hJdef
  have hJsa : IsSelfAdjoint J :=
    TauCeti.DavisKahanExt.isSelfAdjoint_reflectionOperator V
  have hJ2 : J * J = 1 := TauCeti.DavisKahan.reflectionOperator_mul_self_complex V
  have hJJ : ∀ x, J (J x) = x := fun x => by
    have h := congrArg (fun T : H →L[ℂ] H => T x) hJ2
    simpa using h
  have hJnorm : ‖J‖ ≤ 1 :=
    ContinuousLinearMap.opNorm_le_bound _ zero_le_one fun x => by
      rw [TauCeti.norm_apply_of_isSelfAdjoint_of_mul_self hJsa hJ2, one_mul]
  -- the corner, extended to the ambient space
  have hamb : Uᗮ.subtypeL ∘L reflectionSineCorner U J ∘L U.subtypeL.adjoint
      = Uᗮ.starProjection ∘L J ∘L U.starProjection := by
    ext x
    simp only [ContinuousLinearMap.comp_apply, reflectionSineCorner,
      blockCompression, Submodule.adjoint_subtypeL, Submodule.subtypeL_apply,
      Submodule.coe_orthogonalProjectionOnto_apply]
  -- its adjoint
  have hstar : star (Uᗮ.starProjection ∘L J ∘L U.starProjection)
      = U.starProjection ∘L J ∘L Uᗮ.starProjection := by
    change star (Uᗮ.starProjection * J * U.starProjection) = _
    rw [star_mul, star_mul, hJsa.star_eq,
      (isSelfAdjoint_starProjection U).star_eq,
      (isSelfAdjoint_starProjection Uᗮ).star_eq]
    rfl
  -- the ideal block is that adjoint, composed with the involution
  have hblock : DavisKahan.sinTwoThetaIdealBlock U V
      = (U.starProjection ∘L J ∘L Uᗮ.starProjection) ∘L J := by
    rw [DavisKahan.sinTwoThetaIdealBlock,
      DavisKahan.starProjection_map_unitary Uᗮ V.reflection]
    unfold DavisKahan.boundedUnitaryConjugate
    rw [Submodule.reflection_symm]
    rfl
  intro n
  calc (reflectionSineCorner U J).approximationNumber n
      = (Uᗮ.subtypeL ∘L reflectionSineCorner U J ∘L
          U.subtypeL.adjoint).approximationNumber n :=
        ((ContinuousLinearMap.hasSameApproximationNumbers_ambientSubspaceBlock U Uᗮ
          (reflectionSineCorner U J)) n).symm
    _ = (Uᗮ.starProjection ∘L J ∘L U.starProjection).approximationNumber n := by
        rw [hamb]
    _ = (U.starProjection ∘L J ∘L Uᗮ.starProjection).approximationNumber n := by
        rw [← hstar, ContinuousLinearMap.star_eq_adjoint,
          ContinuousLinearMap.approximationNumber_adjoint]
    _ = ((U.starProjection ∘L J ∘L Uᗮ.starProjection) ∘L J).approximationNumber n :=
        (ContinuousLinearMap.hasSameApproximationNumbers_comp_right hJnorm hJnorm
          hJJ n).symm
    _ = (DavisKahan.sinTwoThetaIdealBlock U V).approximationNumber n := by rw [hblock]

end IdealBlockBridge

/-! ### Checkpoint B: the Gram-selected vectors are fixed by the cutoff

`GramSpectralBandModel` promises only that its selected vectors lie in
`X.polarInitial`.  It does *not* promise they are fixed by any cutoff, so
cutoff-fixity is a proof obligation rather than a library theorem.  It is
however free once the operator being selected is already post-composed with the
cutoff: the kernel of the cutoff is contained in the kernel of the composite, so
the initial space of the composite avoids it entirely. -/

section CutoffFixity

variable {E0 : Type*} [NormedAddCommGroup E0] [InnerProductSpace ℂ E0]
  [CompleteSpace E0]
variable {E1 : Type*} [NormedAddCommGroup E1] [InnerProductSpace ℂ E1]
  [CompleteSpace E1]

/-- **The polar initial space of `Y ∘ P` is fixed by the orthogonal projection
`P`.**

`ker P ≤ ker (Y ∘ P)`, so `(ker (Y ∘ P))ᗮ ≤ (ker P)ᗮ = range P`; on the range of
an idempotent self-adjoint `P` the projection is the identity.  Written out
directly, without passing through `range P`, because the intermediate
`(ker P)ᗮ = range P` step needs a closedness argument that the two orthogonality
relations here make unnecessary. -/
theorem eq_of_mem_polarInitial_comp {P : E0 →L[ℂ] E0} (hPsa : IsSelfAdjoint P)
    (hPid : IsIdempotentElem P) (Y : E0 →L[ℂ] E1) {v : E0}
    (hv : v ∈ (Y ∘L P).polarInitial) : P v = v := by
  have hPP : ∀ w : E0, P (P w) = P w := fun w => by
    have h := congrArg (fun T : E0 →L[ℂ] E0 => T w) hPid.eq
    simpa only [_root_.mul_apply_eq_comp] using h
  -- the defect lies in the kernel of the composite
  have hker : v - P v ∈ LinearMap.ker (Y ∘L P).toLinearMap := by
    change (Y ∘L P) (v - P v) = 0
    simp only [ContinuousLinearMap.comp_apply, map_sub, hPP v, sub_self]
  have hmem : v - P v ∈ (Y ∘L P).polarInitialᗮ := by
    rw [ContinuousLinearMap.polarInitial_orthogonal_eq_ker]
    exact hker
  have hv0 : ⟪v, v - P v⟫_ℂ = 0 :=
    (Submodule.mem_orthogonal _ _).mp hmem v hv
  have hPv0 : ⟪P v, v - P v⟫_ℂ = 0 := by
    have hsym := TauCeti.inner_swap_of_isSelfAdjoint hPsa
    rw [inner_sub_right, hsym v v, hsym v (P v), hPP v, sub_self]
  have hzero : ⟪v - P v, v - P v⟫_ℂ = 0 := by
    rw [inner_sub_left, hv0, hPv0, sub_zero]
  have := inner_self_eq_zero.mp hzero
  rw [sub_eq_zero] at this
  exact this.symm

end CutoffFixity

section ScalarGenericCutoff

variable {𝕜 : Type*} [RCLike 𝕜] {G : Type u} [NormedAddCommGroup G]
  [InnerProductSpace 𝕜 G] [CompleteSpace G]

variable {U : Submodule 𝕜 G} [U.HasOrthogonalProjection]
variable {A : G →ₗ.[𝕜] G} {τ : ℝ}

/-- The bounded cutoff, compressed to the trial subspace `U`.  The cutoff's
range already lies in `U`, so this loses nothing. -/
def cutoffCorner (Ω : TauCeti.BoundedCutoff A U τ) : U →L[𝕜] U :=
  blockCompression U U Ω.toProj

/-- The compressed cutoff, evaluated in the ambient space. -/
theorem coe_cutoffCorner_apply (Ω : TauCeti.BoundedCutoff A U τ) (y : U) :
    ((cutoffCorner Ω y : U) : G) = Ω.toProj (y : G) := by
  rw [cutoffCorner, coe_blockCompression_apply]
  exact Submodule.starProjection_eq_self_iff.mpr (Ω.mem_subspace _)

/-- The compressed cutoff is idempotent. -/
theorem isIdempotentElem_cutoffCorner (Ω : TauCeti.BoundedCutoff A U τ) :
    IsIdempotentElem (cutoffCorner Ω) := by
  refine ContinuousLinearMap.ext fun y => ?_
  refine Subtype.ext ?_
  rw [_root_.mul_apply_eq_comp, coe_cutoffCorner_apply, coe_cutoffCorner_apply,
    Ω.toProj_apply_toProj]

/-- The compressed cutoff is self-adjoint. -/
theorem isSelfAdjoint_cutoffCorner (Ω : TauCeti.BoundedCutoff A U τ) :
    IsSelfAdjoint (cutoffCorner Ω) := by
  refine ContinuousLinearMap.isSelfAdjoint_iff_isSymmetric.mpr fun y z => ?_
  change ⟪cutoffCorner Ω y, z⟫_𝕜 = ⟪y, cutoffCorner Ω z⟫_𝕜
  have hy : ((cutoffCorner Ω y : U) : G) = Ω.toProj (y : G) :=
    coe_cutoffCorner_apply Ω y
  have hz : ((cutoffCorner Ω z : U) : G) = Ω.toProj (z : G) :=
    coe_cutoffCorner_apply Ω z
  have h1 : ⟪cutoffCorner Ω y, z⟫_𝕜 = ⟪Ω.toProj (y : G), (z : G)⟫_𝕜 := by
    rw [← hy]; rfl
  have h2 : ⟪y, cutoffCorner Ω z⟫_𝕜 = ⟪(y : G), Ω.toProj (z : G)⟫_𝕜 := by
    rw [← hz]; rfl
  rw [h1, h2]
  exact TauCeti.inner_swap_of_isSelfAdjoint Ω.isSelfAdjoint _ _

/-- **The compressed cutoff is an orthogonal projection, unconditionally.**

`isIdempotentElem_cutoffCorner` and `isSelfAdjoint_cutoffCorner` prove it for
*every* `BoundedCutoff`, so no consumer of `cutoffCorner` has to ask for it as a
hypothesis. -/
theorem isOrthogonalProjectionMap_cutoffCorner (Ω : TauCeti.BoundedCutoff A U τ) :
    TauCeti.ApproximationNumber.IsOrthogonalProjectionMap (cutoffCorner Ω) := by
  refine ⟨?_, ContinuousLinearMap.isSelfAdjoint_iff_isSymmetric.mp
    (isSelfAdjoint_cutoffCorner Ω)⟩
  rw [← ContinuousLinearMap.mul_def]
  exact (isIdempotentElem_cutoffCorner Ω).eq

end ScalarGenericCutoff

variable {A : H →ₗ.[ℂ] H} {τ : ℝ}

/-- **Checkpoint B.**  Every vector of the polar initial space of the
cutoff-composed sine corner is fixed by the cutoff, in the ambient space.  This
is the hypothesis `hxΩ : ∀ i, Ω.toProj (x i) = x i` that every Section 7 lemma
of `TanTwoThetaUnboundedKyFan` demands of its selected family. -/
theorem toProj_eq_of_mem_polarInitial_comp_cutoffCorner
    (Ω : TauCeti.BoundedCutoff A U τ) {v : U}
    (hv : v ∈ (reflectionSineCorner U Z ∘L cutoffCorner Ω).polarInitial) :
    Ω.toProj (v : H) = (v : H) := by
  have h := eq_of_mem_polarInitial_comp (isSelfAdjoint_cutoffCorner Ω)
    (isIdempotentElem_cutoffCorner Ω) (reflectionSineCorner U Z) hv
  rw [← coe_cutoffCorner_apply Ω v, h]

/-- **Checkpoint B, in the form the spectral selection produces it.**  The
vectors a `GramSpectralBandModel` selects for the cutoff-composed sine corner are
cutoff-fixed. -/
theorem gramSpectralBandModel_toProj_right
    (Ω : TauCeti.BoundedCutoff A U τ) {k : ℕ} {ρ : ℝ}
    (M : TauCeti.DavisKahan.GramSpectralBandModel
      (reflectionSineCorner U Z ∘L cutoffCorner Ω) k ρ) (i : Fin M.count) :
    Ω.toProj ((M.right i : U) : H) = ((M.right i : U) : H) :=
  toProj_eq_of_mem_polarInitial_comp_cutoffCorner Ω (M.right_mem_polarInitial i)

/-! ### The Ky Fan prefix form, and the cutoff limit

These are the two ends of the target chain that do not depend on the Section 7
approximate-eigenfamily estimate: the left inequality
`kyFan k T₀ ≤ ∑ tan (arcsin aₙ(S₀))` is Checkpoint A summed, and the cutoff
limit is what lets a fixed-cutoff prefix bound be released to `Ω → I`. -/

/-- **The left half of the target chain.**  The Ky Fan prefix of the directed
tangent corner is dominated by the directed sine corner's tangent prefix sums.
No finite family is asked to realise or attain anything. -/
theorem kyFan_reflectionTangentCorner_le
    (hZsa : IsSelfAdjoint Z) (hZ2 : Z * Z = 1)
    (hS1 : ‖U.offDiagonalPart Z‖ < 1) (k : ℕ) :
    kyFanApproximationGauge k (reflectionTangentCorner U Z) ≤
      ∑ n ∈ Finset.range k, Real.tan (Real.arcsin
        ((reflectionSineCorner U Z).approximationNumber n)) := by
  rw [kyFanApproximationGauge, ContinuousLinearMap.kyFanGauge]
  exact Finset.sum_le_sum fun n _ =>
    approximationNumber_reflectionTangentCorner_le hZsa hZ2 hS1 n

/-- **The cutoff limit for the tangent prefix sums.**

As an orthogonal-projection net increases strongly to the identity of `U`, the
prefix sums `∑_{n<k} tan (arcsin aₙ(S₀ ∘L Ω))` converge to
`∑_{n<k} tan (arcsin aₙ(S₀))`.

The pole is never approached: `aₙ(S₀ ∘L Ω) ≤ ‖S₀‖ < 1` uniformly in `Ω`, so
`s ↦ tan (arcsin s)` is continuous at every value in play, and the prefix is a
finite sum.  This is the step that releases a fixed-cutoff prefix bound to the
full trial subspace. -/
theorem tendsto_sum_tanArcsin_approximationNumber_reflectionSineCorner_comp
    (hS1 : ‖U.offDiagonalPart Z‖ < 1)
    {ι : Type*} {P : ι → U →L[ℂ] U} {l : Filter ι}
    (hPproj : ∀ i, TauCeti.ApproximationNumber.IsOrthogonalProjectionMap (P i))
    (hP : TauCeti.ApproximationNumber.StronglyTendsto P l
      (ContinuousLinearMap.id ℂ U))
    (k : ℕ) :
    Filter.Tendsto
      (fun i => ∑ n ∈ Finset.range k, Real.tan (Real.arcsin
        ((reflectionSineCorner U Z ∘L P i).approximationNumber n)))
      l (nhds (∑ n ∈ Finset.range k, Real.tan (Real.arcsin
        ((reflectionSineCorner U Z).approximationNumber n)))) := by
  refine tendsto_finsetSum _ fun n _ => ?_
  have h0 : 0 ≤ (reflectionSineCorner U Z).approximationNumber n :=
    ContinuousLinearMap.approximationNumber_nonneg _ _
  have h1 : (reflectionSineCorner U Z).approximationNumber n < 1 :=
    lt_of_le_of_lt (ContinuousLinearMap.approximationNumber_le_norm _ n)
      (lt_of_le_of_lt norm_reflectionSineCorner_le hS1)
  exact (TanArcsin.continuousAt_tanArcsin h0 h1).tendsto.comp
    (TauCeti.ApproximationNumber.approximationSingularValue_comp_strongProjection_tendsto_complex
      hPproj hP n (reflectionSineCorner U Z))

end

end DavisKahan1970
end TauCeti
