/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/

import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.ArchimedeanSplitting
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.CardinalTruncation
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.CardinalTruncationDomainEmbedding
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.CardinalTruncationDomainEquiv
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.CardinalTruncationIrreducible
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.CardinalTruncationResidue
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.CharZero
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.CoefficientMap
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.ConvexFactorSupport
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.ConvexQuotientSplitting
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Degree
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.DegreeTermCount
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.DegreeValuation
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Domain
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.DomainEmbedding
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.DomainEquiv
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.DomainOrderType
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.EPrimitive
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.FactorCoefficients
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Factorization
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.FiniteSupport
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.FiniteSupportConstantTermOne
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.FiniteSupportGCDProof
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.FiniteSupportMonoidAlgebra
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.FiniteSupportNormalization
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.FiniteSupportNormalizedGCD
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.FiniteSupportResidue
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.FiniteSupportScalarExtension
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.FiniteSupportScalarTensor
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.FiniteSupportUnit
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Germ
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.IntegerPart
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Iterate
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.IterateOrderType
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.LimitTailQuotient
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Monomial
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Multiplicativity
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Negative
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.NegativeMonomialIdeal
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Nonpositive
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.NonpositiveCoefficientMap
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.NonpositiveDomainEquiv
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.NormalForm
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrderType
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrderedIntervalSum
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.PolynomialAlgebra
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Primality
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.PrincipalAddition
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.RealSupportSupremum
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.SeparatedPieceSum
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.SeparatedSupport
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.SourceStatements
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.SubgroupAlgebra
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.SubgroupGCD
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.SubgroupSupport
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.SupportArchimedeanClasses
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.SupportSupremum
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Tests
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Translation
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.Truncation
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.TruncationIntegerPartPrimal
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.WeakNormalForm

/-! Supporting modules for Conway refinement for omnific integers. -/
