/-
Copyright (c) 2026 Dmitrii Zakharov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dmitrii Zakharov
-/
module


public import LeanPool.ErdosGinzburgZiv.EGZ.Decomposition.CenteredLift
public import LeanPool.ErdosGinzburgZiv.EGZ.Convex.HollowReduction
public import Mathlib.LinearAlgebra.Dimension.Free

/-!
# Coordinates for support-generated integer lattices

Every nonempty finite integer support admits affine integer coordinates in
its own generated lattice. Finiteness of the collection of bounded supports
then makes coordinate and prime-saturation bounds uniform in the support.
-/

@[expose] public section

open scoped BigOperators

namespace EGZ

namespace IntCoord

/-- Realification as an integer-linear map. -/
def realLinearMap (n : ℕ) : IntCoord n →ₗ[ℤ] RealCoord n where
  toFun := real
  map_add' z w := by ext i; simp [real]
  map_smul' c z := by ext i; simp [real]

end IntCoord

/-- Integer coordinates on precisely the affine lattice generated by `S`.
The ambient dimension need not equal the rank of that lattice. -/
structure IntegerLatticeChart {n : ℕ} (S : Finset (IntCoord n)) where
  /-- The number of integer coordinates needed for the affine lattice chart. -/
  rank : ℕ
  rank_le : rank ≤ n
  /-- The injective integer affine parametrization of the support's affine span. -/
  map : IntCoord rank →ᵃ[ℤ] IntCoord n
  injective : Function.Injective map
  range_eq : Set.range map = (affineSpan ℤ (S : Set (IntCoord n)) : Set (IntCoord n))

/-- A nonempty finite support has affine integer coordinates, including when
its affine span has smaller dimension than its ambient space. -/
theorem exists_integerLatticeChart {n : ℕ} (S : Finset (IntCoord n))
    (hS : S.Nonempty) : Nonempty (IntegerLatticeChart S) := by
  classical
  obtain ⟨o, ho⟩ := hS
  let A := affineSpan ℤ (S : Set (IntCoord n))
  let D := A.direction
  let b := Module.finBasis ℤ D
  let L : IntCoord (Module.finrank ℤ D) →ₗ[ℤ] IntCoord n :=
    D.subtype.comp b.equivFun.symm.toLinearMap
  let f : IntCoord (Module.finrank ℤ D) →ᵃ[ℤ] IntCoord n :=
    (AffineEquiv.vaddConst ℤ o).toAffineMap.comp L.toAffineMap
  have hoA : o ∈ A := subset_affineSpan ℤ _ ho
  have hrank : Module.finrank ℤ D ≤ n := by
    simpa using D.finrank_le
  refine ⟨⟨Module.finrank ℤ D, hrank, f, ?_, ?_⟩⟩
  · exact (AffineEquiv.vaddConst ℤ o).injective.comp
      (Subtype.val_injective.comp b.equivFun.symm.injective)
  · ext q
    constructor
    · rintro ⟨z, rfl⟩
      exact A.vadd_mem_of_mem_direction (b.equivFun.symm z).property hoA
    · intro hq
      let v : D := ⟨q -ᵥ o, A.vsub_mem_direction hq hoA⟩
      refine ⟨b.equivFun v, ?_⟩
      change ((b.equivFun.symm (b.equivFun v) : D) : IntCoord n) + o = q
      rw [b.equivFun.symm_apply_apply]
      exact sub_add_cancel q o

namespace IntegerLatticeChart

/-- The real images of chart coordinates are exactly the support-generated
affine lattice used by the convex flag definitions. -/
theorem range_real_eq {n : ℕ} {S : Finset (IntCoord n)}
    (C : IntegerLatticeChart S) :
    Set.range (fun q : IntCoord C.rank ↦ (C.map q).real) =
      affineIntSpan (IntCoord.real '' (S : Set (IntCoord n))) := by
  rw [affineIntSpan_eq_affineSpan_int]
  calc
    Set.range (fun q : IntCoord C.rank ↦ (C.map q).real) =
        IntCoord.real '' Set.range C.map :=
      Set.range_comp (@IntCoord.real n) (fun q : IntCoord C.rank ↦ C.map q)
    _ = IntCoord.real '' (affineSpan ℤ (S : Set (IntCoord n)) : Set (IntCoord n)) := by
      rw [C.range_eq]
    _ = (affineSpan ℤ (IntCoord.real '' (S : Set (IntCoord n))) : Set (RealCoord n)) :=
      congrArg (fun A : AffineSubspace ℤ (RealCoord n) ↦ (A : Set (RealCoord n)))
        (AffineSubspace.map_span (IntCoord.realLinearMap n).toAffineMap _)

/-- The linear part of a chart parametrizes the direction lattice. -/
theorem linear_range_eq {n : ℕ} {S : Finset (IntCoord n)}
    (C : IntegerLatticeChart S) :
    LinearMap.range C.map.linear = vectorSpan ℤ (S : Set (IntCoord n)) := by
  have h := C.map.map_vectorSpan (s := Set.univ)
  rw [← direction_affineSpan, AffineSubspace.span_univ, AffineSubspace.direction_top,
    Submodule.map_top, Set.image_univ, C.range_eq,
    ← direction_affineSpan, AffineSubspace.affineSpan_coe, direction_affineSpan] at h
  exact h

/-- Every generator has coordinates in its generated lattice. -/
theorem exists_map_eq {n : ℕ} {S : Finset (IntCoord n)}
    (C : IntegerLatticeChart S) {z : IntCoord n} (hz : z ∈ S) :
    ∃ q : IntCoord C.rank, C.map q = z := by
  apply C.range_eq.symm.subset
  exact subset_affineSpan ℤ _ hz

/-- The finitely many generators have a common coordinate bound in any
chosen chart. -/
theorem exists_support_bound {n : ℕ} {S : Finset (IntCoord n)}
    (C : IntegerLatticeChart S) :
    ∃ B : ℕ, ∀ z ∈ S, ∃ q : IntCoord C.rank,
      C.map q = z ∧ latticeSupNorm q ≤ B := by
  classical
  choose coord hcoord using fun z : S ↦ C.exists_map_eq z.property
  refine ⟨Finset.univ.sup (fun z : S ↦ latticeSupNorm (coord z)), ?_⟩
  intro z hz
  exact ⟨coord ⟨z, hz⟩, hcoord ⟨z, hz⟩,
    Finset.le_sup (f := fun z : S ↦ latticeSupNorm (coord z))
      (Finset.mem_univ (⟨z, hz⟩ : S))⟩

/-- All lattice points in an old coordinate box have bounded new
coordinates. This controls an entire node polytope, not just its generators. -/
theorem exists_box_bound {n : ℕ} {S : Finset (IntCoord n)}
    (C : IntegerLatticeChart S) (K : ℕ) :
    ∃ B : ℕ, ∀ q : IntCoord C.rank,
      latticeSupNorm (C.map q) ≤ K → latticeSupNorm q ≤ B := by
  classical
  let T := (latticeBox n K).preimage C.map C.injective.injOn
  refine ⟨T.sup latticeSupNorm, ?_⟩
  intro q hq
  exact Finset.le_sup (Finset.mem_preimage.mpr (mem_latticeBox.mpr hq))

end IntegerLatticeChart

/-- In a fixed ambient dimension there are only finitely many possible
supports in a fixed box, so one chart bound works for all of them. -/
theorem exists_bounded_integerLatticeChart (n K : ℕ) :
    ∃ B : ℕ, ∀ S : Finset (IntCoord n), S.Nonempty →
      (∀ z ∈ S, latticeSupNorm z ≤ K) →
      ∃ C : IntegerLatticeChart S, ∀ q : IntCoord C.rank,
        latticeSupNorm (C.map q) ≤ K → latticeSupNorm q ≤ B := by
  classical
  have hex (S : Finset (IntCoord n)) :
      ∃ B : ℕ, S.Nonempty → ∃ C : IntegerLatticeChart S,
        ∀ q : IntCoord C.rank,
          latticeSupNorm (C.map q) ≤ K → latticeSupNorm q ≤ B := by
    by_cases hS : S.Nonempty
    · obtain ⟨C⟩ := exists_integerLatticeChart S hS
      obtain ⟨B, hB⟩ := C.exists_box_bound K
      exact ⟨B, fun _ ↦ ⟨C, hB⟩⟩
    · exact ⟨0, fun h ↦ (hS h).elim⟩
  choose bound hbound using hex
  refine ⟨(latticeBox n K).powerset.sup bound, ?_⟩
  intro S hS hSK
  obtain ⟨C, hC⟩ := hbound S hS
  refine ⟨C, fun q hq ↦ (hC q hq).trans (Finset.le_sup ?_)⟩
  exact Finset.mem_powerset.mpr (fun z hz ↦ mem_latticeBox.mpr (hSK z hz))

/-- A monotone coordinate bound depending only on the upper dimension and
the old coordinate bound, as required by the minimal decomposition lemma. -/
theorem exists_uniform_integerLatticeChart_bound (d : ℕ) :
    ∃ A : ℕ → ℕ, Monotone A ∧ (∀ K, K ≤ A K) ∧
      ∀ K n, n ≤ d → ∀ S : Finset (IntCoord n), S.Nonempty →
        (∀ z ∈ S, latticeSupNorm z ≤ K) →
        ∃ C : IntegerLatticeChart S, ∀ q : IntCoord C.rank,
          latticeSupNorm (C.map q) ≤ K → latticeSupNorm q ≤ A K := by
  classical
  choose bound hbound using exists_bounded_integerLatticeChart
  let B (K : ℕ) := (Finset.range (d + 1)).sup (fun n ↦ bound n K)
  let A (K : ℕ) := K ⊔ (Finset.range (K + 1)).sup B
  have hBA (K : ℕ) : B K ≤ A K :=
    (Finset.le_sup (Finset.mem_range.mpr (Nat.lt_succ_self K))).trans le_sup_right
  refine ⟨A, ?_, fun K ↦ le_sup_left, ?_⟩
  · intro K L hKL
    exact sup_le_sup hKL (Finset.sup_mono (Finset.range_mono (Nat.add_le_add_right hKL 1)))
  · intro K n hn S hS hSK
    obtain ⟨C, hC⟩ := hbound n K S hS hSK
    refine ⟨C, fun q hq ↦ (hC q hq).trans ?_⟩
    exact (Finset.le_sup (Finset.mem_range.mpr (Nat.lt_succ_of_le hn))).trans (hBA K)

/-- One prime threshold excludes torsion in the quotients by all lattices
generated by supports in a fixed box, simultaneously in every rank at most
`d`. There is no dependence on the support or on the number of flag nodes. -/
theorem exists_uniform_bounded_direction_saturation (d K : ℕ) :
    ∃ B : ℕ, ∀ {p : ℕ}, p.Prime → B < p →
      ∀ n, n ≤ d → ∀ S : Finset (IntCoord n),
        (∀ z ∈ S, latticeSupNorm z ≤ K) → ∀ {v : IntCoord n},
          (p : ℤ) • v ∈ vectorSpan ℤ (S : Set (IntCoord n)) →
          v ∈ vectorSpan ℤ (S : Set (IntCoord n)) := by
  classical
  have hex (n : ℕ) := Submodule.exists_uniform_prime_saturation_bound
    (Pi.basisFun ℤ (Fin n)) (latticeBox n K).powerset
    (fun S : Finset (IntCoord n) ↦ vectorSpan ℤ (S : Set (IntCoord n)))
  choose bound hbound using hex
  refine ⟨(Finset.range (d + 1)).sup bound, ?_⟩
  intro p hp hBp n hn S hS v hv
  apply hbound n hp
    (lt_of_le_of_lt (Finset.le_sup (Finset.mem_range.mpr (Nat.lt_succ_of_le hn))) hBp)
    S ?_ hv
  exact Finset.mem_powerset.mpr (fun z hz ↦ mem_latticeBox.mpr (hS z hz))

/-- For sufficiently large primes, congruence of ambient coordinates
reflects congruence in any chart of a bounded support-generated lattice.
This is the injectivity assertion for the natural map of lattice quotients
in the minimal decomposition lemma. -/
theorem exists_uniform_integerLatticeChart_mod_injective (d K : ℕ) :
    ∃ B : ℕ, ∀ {p : ℕ}, p.Prime → B < p →
      ∀ n, n ≤ d → ∀ S : Finset (IntCoord n),
        (∀ z ∈ S, latticeSupNorm z ≤ K) →
        ∀ C : IntegerLatticeChart S, ∀ q r : IntCoord C.rank,
          (C.map q).mod p = (C.map r).mod p → q.mod p = r.mod p := by
  obtain ⟨B, hB⟩ := exists_uniform_bounded_direction_saturation d K
  refine ⟨B, ?_⟩
  intro p hp hBp n hn S hS C q r hmod
  have hzero : (C.map q - C.map r).mod p = 0 := by
    ext i
    have hi := congrFun hmod i
    simpa [IntCoord.mod, Int.cast_sub, sub_eq_zero] using hi
  obtain ⟨v, hv⟩ := IntCoord.exists_smul_eq_of_mod_eq_zero _ hzero
  have hvspan : v ∈ vectorSpan ℤ (S : Set (IntCoord n)) := by
    apply hB hp hBp n hn S hS
    rw [hv, ← C.linear_range_eq]
    exact ⟨q - r, C.map.linearMap_vsub q r⟩
  rw [← C.linear_range_eq] at hvspan
  obtain ⟨t, ht⟩ := hvspan
  have hdiff : (p : ℤ) • t = q - r := by
    apply C.map.linear_injective_iff.mpr C.injective
    rw [map_smul, ht, hv]
    exact (C.map.linearMap_vsub q r).symm
  ext i
  have hi := congrFun hdiff i
  have hcast := congrArg (fun z : ℤ ↦ (z : ZMod p)) hi
  simpa [IntCoord.mod, sub_eq_zero] using hcast.symm

end EGZ
