/-
Copyright (c) 2026 Dmitrii Zakharov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dmitrii Zakharov
-/

import LeanPool.ErdosGinzburgZiv.EGZ.Decomposition.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.Data.Nat.Find

/-!
# Maximal independent thin directions

Fibre-constant affine functionals form a submodule containing all constants.
A greedy extension by thin functionals therefore stops after at most `d`
steps. The selected directions have the prescribed stage-dependent widths,
and every direction outside the final submodule is thick at the next stage.
-/

namespace EGZ

namespace FpRepresentation

variable {p d : ℕ} [Fact p.Prime] {F : ConvexFlag}

/-- Affine functionals constant on every fibre inside the represented space. -/
def fiberConstantSubmodule (R : FpRepresentation p d F) (x : F.Node) :
    Submodule (ZMod p) (FpCoord p d →ᵃ[ZMod p] ZMod p) where
  carrier := {ξ | ∀ v w, v ∈ R.space x → w ∈ R.space x →
    R.map x v = R.map x w → ξ v = ξ w}
  zero_mem' := fun _ _ _ _ _ ↦ rfl
  add_mem' hξ hη := by
    intro v w hv hw heq
    exact congrArg₂ (· + ·) (hξ v w hv hw heq) (hη v w hv hw heq)
  smul_mem' c ξ hξ := by
    intro v w hv hw heq
    exact congrArg (c • ·) (hξ v w hv hw heq)

theorem mem_fiberConstantSubmodule_iff (R : FpRepresentation p d F) (x : F.Node)
    (ξ : FpCoord p d →ᵃ[ZMod p] ZMod p) :
    ξ ∈ R.fiberConstantSubmodule x ↔ ¬ R.NonconstantOnFibers x ξ := by
  constructor
  · intro h ⟨v, w, hv, hw, heq, hne⟩
    exact hne (h v w hv hw heq)
  · intro h v w hv hw heq
    by_contra hne
    exact h ⟨v, w, hv, hw, heq, hne⟩

theorem const_mem_fiberConstantSubmodule (R : FpRepresentation p d F) (x : F.Node)
    (c : ZMod p) : AffineMap.const (ZMod p) (FpCoord p d) c ∈ R.fiberConstantSubmodule x :=
  fun _ _ _ _ _ ↦ rfl

theorem finrank_affineFunctionals :
    Module.finrank (ZMod p) (FpCoord p d →ᵃ[ZMod p] ZMod p) = d + 1 := by
  rw [AffineMap.finrank_eq]
  simp

/-- Constants account for at least one dimension of the fibre-constant space. -/
theorem finrank_fiberConstantSubmodule_pos (R : FpRepresentation p d F) (x : F.Node) :
    0 < Module.finrank (ZMod p) (R.fiberConstantSubmodule x) := by
  apply Module.finrank_pos_iff_exists_ne_zero.mpr
  refine ⟨⟨AffineMap.const (ZMod p) (FpCoord p d) 1,
    R.const_mem_fiberConstantSubmodule x 1⟩, ?_⟩
  intro h
  have heq := congrArg
    (fun ξ : R.fiberConstantSubmodule x ↦ (ξ : FpCoord p d →ᵃ[ZMod p] ZMod p) 0) h
  exact one_ne_zero heq

/-- At most `d` independent directions can be added to the fibre-constant space. -/
theorem finrank_quotient_fiberConstantSubmodule_le (R : FpRepresentation p d F) (x : F.Node) :
    Module.finrank (ZMod p)
      ((FpCoord p d →ᵃ[ZMod p] ZMod p) ⧸ R.fiberConstantSubmodule x) ≤ d := by
  have h := (R.fiberConstantSubmodule x).finrank_quotient_add_finrank
  rw [finrank_affineFunctionals] at h
  have hpos := R.finrank_fiberConstantSubmodule_pos x
  omega

end FpRepresentation

section Greedy

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V] [FiniteDimensional K V]

/-- A finite prefix of independent extensions of an initial submodule.
Only indices below `length` carry conditions; the remaining values are irrelevant. -/
structure DirectionChain (W : Submodule K V) (P : ℕ → V → Prop) (length : ℕ) where
  /-- The successive subspaces generated by adjoining the chosen directions to the initial
  space. -/
  space : ℕ → Submodule K V
  /-- The direction adjoined at each step of the chain. -/
  direction : ℕ → V
  initial : space 0 = W
  step : ∀ i, i < length → space (i + 1) = space i ⊔ Submodule.span K {direction i}
  independent : ∀ i, i < length → direction i ∉ space i
  selected : ∀ i, i < length → P i (direction i)

namespace DirectionChain

variable {W : Submodule K V} {P : ℕ → V → Prop} {k : ℕ}

/-- The chain of length zero that stays at the initial subspace. -/
def empty (W : Submodule K V) (P : ℕ → V → Prop) : DirectionChain W P 0 where
  space _ := W
  direction _ := 0
  initial := rfl
  step _ h := (Nat.not_lt_zero _ h).elim
  independent _ h := (Nat.not_lt_zero _ h).elim
  selected _ h := (Nat.not_lt_zero _ h).elim

/-- Add one selected direction outside the final submodule. -/
noncomputable def append (D : DirectionChain W P k) (ξ : V)
    (hξ : ξ ∉ D.space k) (hP : P k ξ) : DirectionChain W P (k + 1) := by
  classical
  refine
    { space := Function.update D.space (k + 1) (D.space k ⊔ Submodule.span K {ξ})
      direction := Function.update D.direction k ξ
      initial := by simp [D.initial]
      step := ?_
      independent := ?_
      selected := ?_ }
  · intro i hi
    by_cases hik : i = k
    · subst i
      simp
    · have hil : i < k := by omega
      have h1 : i + 1 ≠ k + 1 := by omega
      have h2 : i ≠ k + 1 := by omega
      simpa [Function.update_of_ne h1, Function.update_of_ne h2, Function.update_of_ne hik]
        using D.step i hil
  · intro i hi
    by_cases hik : i = k
    · subst i
      simpa using hξ
    · have hil : i < k := by omega
      have h2 : i ≠ k + 1 := by omega
      simpa [Function.update_of_ne h2, Function.update_of_ne hik] using D.independent i hil
  · intro i hi
    by_cases hik : i = k
    · subst i
      simpa using hP
    · have hil : i < k := by omega
      simpa [Function.update_of_ne hik] using D.selected i hil

/-- Each independent singleton extension adds exactly one dimension. -/
theorem finrank_space (D : DirectionChain W P k) (i : ℕ) (hi : i ≤ k) :
    Module.finrank K (D.space i) = Module.finrank K W + i := by
  induction i with
  | zero => rw [D.initial, Nat.add_zero]
  | succ i ih =>
    have hik : i < k := by omega
    rw [D.step i hik, Submodule.finrank_sup_span_singleton (D.independent i hik), ih (by omega)]
    omega

theorem length_le_finrank_quotient (D : DirectionChain W P k) :
    k ≤ Module.finrank K (V ⧸ W) := by
  have hle := (D.space k).finrank_le
  rw [D.finrank_space k le_rfl] at hle
  have hquot := W.finrank_quotient_add_finrank
  omega

omit [FiniteDimensional K V] in
/-- The enlarged space lies in every submodule containing the initial
space and all the selected directions. -/
theorem space_le_of_mem (D : DirectionChain W P k) (U : Submodule K V)
    (hW : W ≤ U) (hdir : ∀ j, j < k → D.direction j ∈ U)
    (i : ℕ) (hi : i ≤ k) : D.space i ≤ U := by
  induction i with
  | zero => rw [D.initial]; exact hW
  | succ i ih =>
    have hik : i < k := by omega
    rw [D.step i hik]
    apply sup_le (ih (by omega))
    apply Submodule.span_le.mpr
    intro ξ hξ
    rw [Set.mem_singleton_iff] at hξ
    rw [hξ]
    exact hdir i hik

omit [FiniteDimensional K V] in
/-- If a first-stage direction exists, a maximal chain has positive length. -/
theorem length_pos_of_exists (D : DirectionChain W P k)
    (hmax : ∀ ξ, ξ ∉ D.space k → ¬ P k ξ)
    (hex : ∃ ξ, ξ ∉ W ∧ P 0 ξ) : 0 < k := by
  apply Nat.pos_of_ne_zero
  intro hk
  subst k
  obtain ⟨ξ, hξ, hP⟩ := hex
  exact hmax ξ (by simpa only [D.initial] using hξ) hP

end DirectionChain

/-- A maximal chain exists for arbitrary predicates assigned to its stages.
Maximality is tested using the predicate for the next stage. -/
theorem exists_maximal_directionChain (W : Submodule K V) (P : ℕ → V → Prop) :
    ∃ k, k ≤ Module.finrank K (V ⧸ W) ∧ ∃ D : DirectionChain W P k,
      ∀ ξ, ξ ∉ D.space k → ¬ P k ξ := by
  classical
  let Q (k : ℕ) := Nonempty (DirectionChain W P k)
  let n := Module.finrank K (V ⧸ W)
  let k := Nat.findGreatest Q n
  have hk : Q k := Nat.findGreatest_spec (Nat.zero_le n) ⟨DirectionChain.empty W P⟩
  obtain ⟨D⟩ := hk
  refine ⟨k, D.length_le_finrank_quotient, D, ?_⟩
  intro ξ hξ hP
  let D' := D.append ξ hξ hP
  exact Nat.findGreatest_is_greatest (Nat.lt_succ_self k) D'.length_le_finrank_quotient ⟨D'⟩

end Greedy

/-- Maximal independent thin functionals with the paper's stage-dependent
width and error parameters. The first selected direction uses stage one. -/
theorem exists_maximal_thinDirections {p d : ℕ} [Fact p.Prime] {F : ConvexFlag}
    (R : FpRepresentation p d F) (x : F.Node) (w : FpCoord p d → ℕ)
    (t : ℕ → ℕ) (δ : ℝ) :
    ∃ k, k ≤ d ∧ ∃ D : DirectionChain (R.fiberConstantSubmodule x)
      (fun i ξ ↦ IsThinAlong w ξ (t (i + 1)) ((3 : ℝ) ^ (i + 1) * δ)) k,
      ∀ ξ, ξ ∉ D.space k → IsThickAlong w ξ (t (k + 1)) ((3 : ℝ) ^ (k + 1) * δ) := by
  obtain ⟨k, hk, D, hmax⟩ := exists_maximal_directionChain (R.fiberConstantSubmodule x)
    (fun i ξ ↦ IsThinAlong w ξ (t (i + 1)) ((3 : ℝ) ^ (i + 1) * δ))
  exact ⟨k, hk.trans (R.finrank_quotient_fiberConstantSubmodule_le x), D, hmax⟩

end EGZ
