/-
Copyright (c) 2026 Egor Lyfar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Egor Lyfar
-/

import LeanPool.Erdos97ConvexOctagon.CoveragePatternChoices0Validity
import LeanPool.Erdos97ConvexOctagon.CoveragePatternChoices1Validity
import LeanPool.Erdos97ConvexOctagon.CoveragePatternChoices2Validity
import LeanPool.Erdos97ConvexOctagon.CoveragePatternChoices3Validity
import LeanPool.Erdos97ConvexOctagon.CoveragePatternChoices4Validity
import LeanPool.Erdos97ConvexOctagon.CoveragePatternChoices5Validity
import LeanPool.Erdos97ConvexOctagon.CoveragePatternChoices6Validity
import LeanPool.Erdos97ConvexOctagon.CoveragePatternChoices7Validity
import LeanPool.Erdos97ConvexOctagon.CoverageHardChoices0Validity
import LeanPool.Erdos97ConvexOctagon.CoverageHardChoices1Validity
import LeanPool.Erdos97ConvexOctagon.CoverageHardChoices2Validity
import LeanPool.Erdos97ConvexOctagon.CoverageHardChoices3Validity
import LeanPool.Erdos97ConvexOctagon.CoverageHardChoices4Validity
import LeanPool.Erdos97ConvexOctagon.CoverageHardChoices5Validity
import LeanPool.Erdos97ConvexOctagon.CoverageHardChoices6Validity

/-! # Aggregated static coverage-summary choice validity -/
