/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, Claude Opus 5
-/
module

public import LeanPool.DavisKahan.ForTauCeti.Analysis.InnerProductSpace.OperatorModulus
public import LeanPool.DavisKahan.ForTauCeti.Analysis.InnerProductSpace.Projection.Blocks

/-!
# Reflecting one projection through another doubles the angle

Let `p` and `q` be orthogonal projections and let `x = 2q - 1` be the reflection
through the range of `q`.  Then

`x p x - p = 2 x (p q - q p)`,

and because `x` is a self-adjoint unitary the modulus of the left side is twice
the modulus of the commutator.  The commutator in turn is computed by a purely
algebraic identity in the `⋆`-ring generated by two idempotents:

`(q p - p q)⋆ (q p - p q) = d² - d⁴`,  `d = p - q`.

Since `|d| = sin Θ` and `(1 - d²)^{1/2} = cos Θ` for the angle `Θ` between the
two ranges, this says `|q p - p q| = sin Θ cos Θ`, hence

`|x p x - p| = 2 sin Θ cos Θ = sin 2Θ`.

That is the operator form of the Davis--Kahan Section 7 observation that
reflecting a subspace through another doubles the principal angles; the
`sin 2Θ` theorem is obtained by applying an ordinary `sin Θ` theorem to the
reflected pair.  The identity here is an *operator* identity, so it upgrades the
already-known equality of operator norms to equality under every unitarily
invariant norm.

## Main results

* `TauCeti.commutator_mul_self_of_isIdempotentElem`: the ring identity
  `(q p - p q)² = d⁴ - d²`.
* `TauCeti.reflect_sub_eq_two_mul`: `x p x - p = 2 (x (p q - q p))` for
  `x = q + q - 1`.
* `TauCeti.reflect_mul_self_of_isIdempotentElem`: `x² = 1`.
* `TauCeti.gram_reflect_sub`: the Gram operator of `x p x - p` is
  `4 (d² - d⁴)`.

## References

* C. Davis and W. M. Kahan, *The rotation of eigenvectors by a perturbation.
  III*, SIAM J. Numer. Anal. 7 (1970), 1--46, Section 7, equations (7.1)--(7.5).
-/

public section

namespace TauCeti

open scoped InnerProductSpace

section RingIdentities

variable {R : Type*} [Ring R] {p q : R}

/-- **The commutator of two idempotents, squared.**  With `d = p - q`,
`(q p - p q)² = d⁴ - d²`.  Purely algebraic: no order, norm, or involution is
used, and both idempotents are only assumed idempotent. -/
theorem commutator_mul_self_of_isIdempotentElem
    (hp : IsIdempotentElem p) (hq : IsIdempotentElem q) :
    (q * p - p * q) * (q * p - p * q) =
      ((p - q) * (p - q)) * ((p - q) * (p - q)) - (p - q) * (p - q) := by
  have hp' : p * p = p := hp
  have hq' : q * q = q := hq
  have hpl : ∀ x : R, p * (p * x) = p * x := fun x => by rw [← mul_assoc, hp']
  have hql : ∀ x : R, q * (q * x) = q * x := fun x => by rw [← mul_assoc, hq']
  simp only [sub_mul, mul_sub, mul_assoc, hp', hq', hpl, hql]
  abel

/-- The reflection `x = q + q - 1` through the range of an idempotent is an
involution. -/
theorem reflect_mul_self_of_isIdempotentElem (hq : IsIdempotentElem q) :
    (q + q - 1) * (q + q - 1) = 1 := by
  have hq' : q * q = q := hq
  simp only [sub_mul, mul_sub, add_mul, mul_add, mul_one, one_mul, hq']
  abel

/-- **The reflection displacement.**  Conjugating `p` by the reflection
`x = q + q - 1` displaces it by twice `x` times the commutator. -/
theorem reflect_sub_eq_two_mul (hq : IsIdempotentElem q) :
    (q + q - 1) * p * (q + q - 1) - p =
      (q + q - 1) * (p * q - q * p) + (q + q - 1) * (p * q - q * p) := by
  have hx : (q + q - 1) * ((q + q - 1) * p) = p := by
    rw [← mul_assoc, reflect_mul_self_of_isIdempotentElem hq, one_mul]
  calc (q + q - 1) * p * (q + q - 1) - p
      = (q + q - 1) * (p * (q + q - 1)) -
          (q + q - 1) * ((q + q - 1) * p) := by rw [hx, mul_assoc]
    _ = (q + q - 1) * (p * (q + q - 1) - (q + q - 1) * p) :=
        (mul_sub (q + q - 1) (p * (q + q - 1)) ((q + q - 1) * p)).symm
    _ = (q + q - 1) * ((p * q - q * p) + (p * q - q * p)) := by
        congr 1
        simp only [mul_add, add_mul, mul_one, one_mul, mul_sub, sub_mul]
        abel
    _ = (q + q - 1) * (p * q - q * p) + (q + q - 1) * (p * q - q * p) := by
        rw [mul_add]

end RingIdentities

section Hilbert

universe u

variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℂ E]
  [CompleteSpace E]

/-- **The Gram operator of the reflection displacement.**  For orthogonal
projections `P` and `Q` on a complex Hilbert space and `X = Q + Q - 1` the
reflection through the range of `Q`,

`(X P X - P)⋆ (X P X - P) = 4 (D² - D⁴)`,  `D = P - Q`.

Since `|D|` is the ambient `sin Θ` of the pair of ranges and `(1 - D²)^{1/2}` is
`cos Θ`, the right-hand side is `(sin 2Θ)²`. -/
theorem gram_reflect_sub {P Q : E →L[ℂ] E}
    (hP : IsIdempotentElem P) (hQ : IsIdempotentElem Q)
    (hPs : IsSelfAdjoint P) (hQs : IsSelfAdjoint Q) :
    star ((Q + Q - 1) * P * (Q + Q - 1) - P) *
        ((Q + Q - 1) * P * (Q + Q - 1) - P) =
      (4 : ℂ) • ((P - Q) * (P - Q) -
        ((P - Q) * (P - Q)) * ((P - Q) * (P - Q))) := by
  set X : E →L[ℂ] E := Q + Q - 1 with hXdef
  set C : E →L[ℂ] E := P * Q - Q * P with hCdef
  have hone : IsSelfAdjoint (1 : E →L[ℂ] E) := star_one _
  have hXs : IsSelfAdjoint X := by
    rw [hXdef]
    exact (hQs.add hQs).sub hone
  have hXX : X * X = 1 := reflect_mul_self_of_isIdempotentElem hQ
  have hdisp : X * P * X - P = X * C + X * C := reflect_sub_eq_two_mul hQ
  have hCstar : star C = -C := by
    rw [hCdef, star_sub, star_mul, star_mul, hPs.star_eq, hQs.star_eq]
    abel
  have hCC : C * C =
      ((P - Q) * (P - Q)) * ((P - Q) * (P - Q)) - (P - Q) * (P - Q) := by
    have h := commutator_mul_self_of_isIdempotentElem hQ hP
    have hswap : (P - Q) * (P - Q) = (Q - P) * (Q - P) := by
      rw [show P - Q = -(Q - P) from by abel, neg_mul_neg]
    rw [hCdef, hswap]
    exact h
  have hgram : star (X * C + X * C) * (X * C + X * C) =
      -((C * C + C * C) + (C * C + C * C)) := by
    have hstar : star (X * C + X * C) = -C * X + -C * X := by
      rw [star_add, star_mul, hXs.star_eq, hCstar]
    have expand : (-C * X + -C * X) * (X * C + X * C) =
        -C * ((X * X) * C) + -C * ((X * X) * C) +
          (-C * ((X * X) * C) + -C * ((X * X) * C)) := by
      simp only [add_mul, mul_add, mul_assoc]
    rw [hstar, expand, hXX, one_mul]
    simp only [neg_mul]
    abel
  rw [hdisp, hgram, hCC]
  module

end Hilbert

end TauCeti
