/-
Copyright (c) 2026 Arseniy Akopyan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Arseniy Akopyan
-/
module


public import Mathlib.Algebra.Category.ModuleCat.Biproducts
public import Mathlib.Algebra.Homology.HomologicalComplexAbelian
public import Mathlib.Algebra.Homology.HomologicalComplexBiprod
public import Mathlib.Tactic
public import LeanPool.NandakumarRamanaRao.NRR.OddSphereDegree.AlgebraicTopology.CoordinateProjection
public import LeanPool.NandakumarRamanaRao.NRR.OddSphereDegree.AlgebraicTopology.SmallChainsQuasiIso

/-! # Mayer Vietoris SES -/

@[expose] public section

open CategoryTheory AlgebraicTopology Limits TopologicalSpace
open SphereOddDegree.AffineBarycentricSubdivision

namespace SphereOddDegree


variable (R : Type) [CommRing R] {X : TopCat.{0}}
open Classical in
/-- The open-cover data supplied by two open sets whose union is the whole space. -/
def twoSetCover (U V : Opens X) (hUV : U ⊔ V = ⊤) : OpenCoverData X where
  sets := {(U : Set X), (V : Set X)}
  isOpen_mem := by
    rintro S (rfl | rfl)
    · exact U.isOpen
    · exact V.isOpen
  covers := by
    intro x
    have hx : x ∈ ((U ⊔ V : Opens X) : Set X) := by rw [hUV]; trivial
    rw [Opens.coe_sup] at hx
    rcases hx with hxU | hxV
    · exact ⟨(U : Set X), Set.mem_insert _ _, hxU⟩
    · exact ⟨(V : Set X), Set.mem_insert_of_mem _ rfl, hxV⟩

open Classical in
theorem twoSetCover_memU (U V : Opens X) (hUV : U ⊔ V = ⊤) :
    (U : Set X) ∈ (twoSetCover U V hUV).sets :=
  Set.mem_insert _ _

open Classical in
theorem twoSetCover_memV (U V : Opens X) (hUV : U ⊔ V = ⊤) :
    (V : Set X) ∈ (twoSetCover U V hUV).sets :=
  Set.mem_insert_of_mem _ rfl

open Classical in
/-- The chain complex generated by simplices small for the two-set open cover. -/
noncomputable def twoOpenCoverSmallChains (R : Type) [CommRing R]
    {X : TopCat.{0}} (U V : Opens X) (hUV : U ⊔ V = ⊤) :
    ChainComplex (ModuleCat.{0} R) ℕ :=
  smallChainComplex R X (twoSetCover U V hUV)

open Classical in
/-- Include chains supported in the intersection into chains supported in the first open set. -/
noncomputable def mvInclUVU (U V : Opens X) :
    subChainComplex R X ((U : Set X) ∩ (V : Set X)) ⟶ subChainComplex R X (U : Set X) :=
  subChainInclusion _ _ Set.inter_subset_left

open Classical in
/-- Include chains supported in the intersection into chains supported in the second open set. -/
noncomputable def mvInclUVV (U V : Opens X) :
    subChainComplex R X ((U : Set X) ∩ (V : Set X)) ⟶ subChainComplex R X (V : Set X) :=
  subChainInclusion _ _ Set.inter_subset_right

open Classical in
/-- Include chains supported in the first open set into the small-chain complex of the cover. -/
noncomputable def mvInclUSmall (U V : Opens X) (hUV : U ⊔ V = ⊤) :
    subChainComplex R X (U : Set X) ⟶ twoOpenCoverSmallChains R U V hUV :=
  subChainToSmall (twoSetCover U V hUV) _ (twoSetCover_memU U V hUV)

open Classical in
/-- Include chains supported in the second open set into the small-chain complex of the cover. -/
noncomputable def mvInclVSmall (U V : Opens X) (hUV : U ⊔ V = ⊤) :
    subChainComplex R X (V : Set X) ⟶ twoOpenCoverSmallChains R U V hUV :=
  subChainToSmall (twoSetCover U V hUV) _ (twoSetCover_memV U V hUV)

open Classical in
theorem mvIncl_comp_eq (U V : Opens X) (hUV : U ⊔ V = ⊤) :
    mvInclUVU R U V ≫ mvInclUSmall R U V hUV
      = mvInclUVV R U V ≫ mvInclVSmall R U V hUV := by
  apply HomologicalComplex.hom_ext
  intro k
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  rintro ⟨c, hc⟩
  apply Subtype.ext
  rfl

open Classical in
/-- The signed pair of inclusions from the intersection into the two open sets. -/
noncomputable def mvLeftChainMap (U V : Opens X) :
    subChainComplex R X ((U : Set X) ∩ (V : Set X)) ⟶
      subChainComplex R X (U : Set X) ⊞ subChainComplex R X (V : Set X) :=
  biprod.lift (mvInclUVU R U V) (-(mvInclUVV R U V))

open Classical in
/-- Add the two inclusions into the small-chain complex of the cover. -/
noncomputable def mvRightChainMap (U V : Opens X) (hUV : U ⊔ V = ⊤) :
    subChainComplex R X (U : Set X) ⊞ subChainComplex R X (V : Set X) ⟶
      twoOpenCoverSmallChains R U V hUV :=
  biprod.desc (mvInclUSmall R U V hUV) (mvInclVSmall R U V hUV)

open Classical in
theorem mvLeft_comp_mvRight (U V : Opens X) (hUV : U ⊔ V = ⊤) :
    mvLeftChainMap R U V ≫ mvRightChainMap R U V hUV = 0 := by
  rw [mvLeftChainMap, mvRightChainMap, biprod.lift_desc, mvIncl_comp_eq R U V hUV]
  simp [Preadditive.neg_comp]

open Classical in
/-- The Mayer–Vietoris short complex of intersection, component, and small chains. -/
noncomputable def mvShortComplex (U V : Opens X) (hUV : U ⊔ V = ⊤) :
    ShortComplex (ChainComplex (ModuleCat.{0} R) ℕ) where
  X₁ := subChainComplex R X ((U : Set X) ∩ (V : Set X))
  X₂ := subChainComplex R X (U : Set X) ⊞ subChainComplex R X (V : Set X)
  X₃ := twoOpenCoverSmallChains R U V hUV
  f := mvLeftChainMap R U V
  g := mvRightChainMap R U V hUV
  zero := mvLeft_comp_mvRight R U V hUV

open Classical in
/-- A simplex lies in the second open set but is not subordinate to the first. -/
def IsSubVnotU (U V : Opens X) {n : ℕ} (σ : singularSimplices X n) : Prop :=
  IsSubordinate (V : Set X) σ ∧ ¬ IsSubordinate (U : Set X) σ

open Classical in
theorem keepHom_small_mem_U (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ)
    (c : singularChainGroup R X k)
    (hc : c ∈ smallChainSubmodule R X (twoSetCover U V hUV) k) :
    (keepHom R X (IsSubordinate (U : Set X))).hom c ∈ subChainSubmodule R X (U : Set X) k := by
  refine Submodule.span_induction ?_ ?_ ?_ ?_ hc
  · rintro _ ⟨σ, hσ, rfl⟩; rw [keepHom_generator]; split_ifs <;> simp_all? [IsSubordinate]
    exact chainGenerator_mem_subChainSubmodule ‹_›
  · simp [keepHom]
  · intro x y hx hy hx' hy'; rw [map_add]; exact Submodule.add_mem _ hx' hy'
  · intro a x hx hx'; rw [map_smul]; exact Submodule.smul_mem _ _ hx'

open Classical in
theorem keepHom_small_mem_V (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ)
    (c : singularChainGroup R X k)
    (hc : c ∈ smallChainSubmodule R X (twoSetCover U V hUV) k) :
    (keepHom R X (IsSubVnotU U V)).hom c ∈ subChainSubmodule R X (V : Set X) k := by
  refine Submodule.span_induction ?_ ?_ ?_ ?_ hc
  · rintro _ ⟨σ, hσ, rfl⟩; rw [keepHom_generator]; split_ifs <;> simp_all? [IsSubVnotU]
    exact chainGenerator_mem_subChainSubmodule (by tauto)
  · simp [keepHom]
  · intro x y hx hy hx' hy'; rw [map_add]; exact Submodule.add_mem _ hx' hy'
  · intro a x hx hx'; rw [map_smul]; exact Submodule.smul_mem _ _ hx'

open Classical in
theorem keepHom_split_small (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ)
    (c : singularChainGroup R X k)
    (hc : c ∈ smallChainSubmodule R X (twoSetCover U V hUV) k) :
    (keepHom R X (IsSubordinate (U : Set X))).hom c
      + (keepHom R X (IsSubVnotU U V)).hom c = c := by
  refine Submodule.span_induction ?_ ?_ ?_ ?_ hc
  · rintro _ ⟨σ, hσ, rfl⟩
    rw [keepHom_generator, keepHom_generator]
    split_ifs <;> simp_all? [IsSubordinate, IsSubVnotU]
    contrapose! hσ
    simp_all [IsSmallSimplex, twoSetCover]
  · simp
  · intro x y hx hy hx' hy'; rw [map_add, map_add, ← add_add_add_comm, hx', hy']
  · intro a x hx hx'; rw [map_smul, map_smul, ← smul_add, hx']

open Classical in
theorem keepHom_V_mem_UV (U V : Opens X) (k : ℕ)
    (c : singularChainGroup R X k)
    (hc : c ∈ subChainSubmodule R X (V : Set X) k) :
    (keepHom R X (IsSubordinate (U : Set X))).hom c
      ∈ subChainSubmodule R X ((U : Set X) ∩ (V : Set X)) k := by
  have := keepHom_mem_subChainSubmodule (S := (U : Set X)) (T := (V : Set X)) hc
  simpa using this

open Classical in
/-- Restrict a generator-retaining projection to specified source and target submodules. -/
noncomputable def restrictKeep {n : ℕ} (P : singularSimplices X n → Prop) [DecidablePred P]
    (p q : Submodule R (singularChainGroup R X n))
    (hmaps : ∀ c ∈ p, (keepHom R X P).hom c ∈ q) :
    ModuleCat.of R p ⟶ ModuleCat.of R q :=
  ModuleCat.ofHom (LinearMap.codRestrict q ((keepHom R X P).hom.comp p.subtype)
    (fun c => hmaps c.1 c.2))

open Classical in
@[simp] theorem restrictKeep_val {n : ℕ} (P : singularSimplices X n → Prop) [DecidablePred P]
    (p q : Submodule R (singularChainGroup R X n))
    (hmaps : ∀ c ∈ p, (keepHom R X P).hom c ∈ q) (c : p) :
    (((restrictKeep R P p q hmaps).hom c) : singularChainGroup R X n)
      = (keepHom R X P).hom (c : singularChainGroup R X n) :=
  rfl

open Classical in
/-- Route the simplices subordinate to the first open set into its chain group. -/
noncomputable def routeU (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ) :
    (twoOpenCoverSmallChains R U V hUV).X k ⟶
      (subChainComplex R X (U : Set X)).X k :=
  restrictKeep R (IsSubordinate (U : Set X)) _ _ (keepHom_small_mem_U R U V hUV k)

open Classical in
/-- Route the remaining simplices of the two-set cover into the second open set. -/
noncomputable def routeV (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ) :
    (twoOpenCoverSmallChains R U V hUV).X k ⟶
      (subChainComplex R X (V : Set X)).X k :=
  restrictKeep R (IsSubVnotU U V) _ _ (keepHom_small_mem_V R U V hUV k)

open Classical in
/-- Retain the simplices of the second open set that also lie in the first. -/
noncomputable def projVtoUV (U V : Opens X) (k : ℕ) :
    (subChainComplex R X (V : Set X)).X k ⟶
      (subChainComplex R X ((U : Set X) ∩ (V : Set X))).X k :=
  restrictKeep R (IsSubordinate (U : Set X)) _ _ (keepHom_V_mem_UV R U V k)

open Classical in
theorem keepHom_PV_eq_zero_of_mem_U (U V : Opens X) (k : ℕ)
    (c : singularChainGroup R X k) (hc : c ∈ subChainSubmodule R X (U : Set X) k) :
    (keepHom R X (IsSubVnotU U V)).hom c = 0 := by
  refine Submodule.span_induction ?_ ?_ ?_ ?_ hc
  · rintro _ ⟨σ, hσ, rfl⟩; rw [keepHom_generator]; split_ifs <;> simp_all [IsSubVnotU]
  · simp
  · intro x y hx hy hx' hy'; rw [map_add, hx', hy', add_zero]
  · intro a x hx hx'; rw [map_smul, hx', smul_zero]

open Classical in
theorem mvInclU_small_comp_routeU (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ) :
    (mvInclUSmall R U V hUV).f k ≫ routeU R U V hUV k = 𝟙 _ := by
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  rintro ⟨c, hc⟩
  apply Subtype.ext
  simp only [ModuleCat.hom_comp,  ModuleCat.hom_id]
  change (keepHom R X (IsSubordinate (U : Set X))).hom c = c
  exact keepHom_eq_self_of_mem hc

open Classical in
theorem mvInclU_small_comp_routeV (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ) :
    (mvInclUSmall R U V hUV).f k ≫ routeV R U V hUV k = 0 := by
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  rintro ⟨c, hc⟩
  apply Subtype.ext
  simp only [ModuleCat.hom_comp,  ModuleCat.hom_zero]
  change (keepHom R X (IsSubVnotU U V)).hom c = 0
  exact keepHom_PV_eq_zero_of_mem_U R U V k c hc

open Classical in
theorem mvInclV_small_comp_routeU (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ) :
    (mvInclVSmall R U V hUV).f k ≫ routeU R U V hUV k
      = projVtoUV R U V k ≫ (mvInclUVU R U V).f k := by
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  rintro ⟨c, hc⟩
  apply Subtype.ext
  rfl

open Classical in
theorem keepHom_split_subV (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ)
    (c : singularChainGroup R X k) (hc : c ∈ subChainSubmodule R X (V : Set X) k) :
    (keepHom R X (IsSubordinate (U : Set X))).hom c
      + (keepHom R X (IsSubVnotU U V)).hom c = c := by
  exact keepHom_split_small R U V hUV k c (subChainSubmodule_le_smallChainSubmodule
    (twoSetCover_memV U V hUV) k hc)

open Classical in
theorem mvInclUV_V_comp_projVtoUV (U V : Opens X) (k : ℕ) :
    (mvInclUVV R U V).f k ≫ projVtoUV R U V k = 𝟙 _ := by
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  rintro ⟨c, hc⟩
  apply Subtype.ext
  simp only [ModuleCat.hom_comp,  ModuleCat.hom_id]
  change (keepHom R X (IsSubordinate (U : Set X))).hom c = c
  exact keepHom_eq_self_of_mem (subChainSubmodule_mono Set.inter_subset_left k hc)

open Classical in
theorem projVtoUV_inclUV_V_add_inclV_routeV (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ) :
    ((projVtoUV R U V k ≫ (mvInclUVV R U V).f k :
        (subChainComplex R X (V : Set X)).X k
          ⟶ (subChainComplex R X (V : Set X)).X k)
      + ((mvInclVSmall R U V hUV).f k ≫ routeV R U V hUV k :
        (subChainComplex R X (V : Set X)).X k
          ⟶ (subChainComplex R X (V : Set X)).X k))
      = 𝟙 ((subChainComplex R X (V : Set X)).X k) := by
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  rintro ⟨c, hc⟩
  apply Subtype.ext
  simp only [ModuleCat.hom_add, ModuleCat.hom_comp,
    ModuleCat.hom_id]
  exact keepHom_split_subV R U V hUV k c hc

open Classical in
/-- The degreewise module short complex underlying the Mayer–Vietoris construction. -/
noncomputable abbrev mvSplitSC (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ) :
    ShortComplex (ModuleCat.{0} R) :=
  ShortComplex.mk
    (biprod.lift ((mvInclUVU R U V).f k) (-(mvInclUVV R U V).f k))
    (biprod.desc ((mvInclUSmall R U V hUV).f k) ((mvInclVSmall R U V hUV).f k))
    (by
      rw [biprod.lift_desc]
      have : (mvInclUVU R U V).f k ≫ (mvInclUSmall R U V hUV).f k
          = (mvInclUVV R U V).f k ≫ (mvInclVSmall R U V hUV).f k := by
        apply ModuleCat.hom_ext
        apply LinearMap.ext
        rintro ⟨c, hc⟩
        apply Subtype.ext
        rfl
      rw [this, Preadditive.neg_comp, add_neg_cancel])

open Classical in
/-- The degreewise splitting obtained by routing each simplex to one open set. -/
noncomputable def mvSplitting (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ) :
    (mvSplitSC R U V hUV k).Splitting where
  r := biprod.desc 0 (-projVtoUV R U V k)
  s := biprod.lift (routeU R U V hUV k) (routeV R U V hUV k)
  f_r := by
    change biprod.lift ((mvInclUVU R U V).f k) (-(mvInclUVV R U V).f k) ≫
           biprod.desc 0 (-projVtoUV R U V k) = 𝟙 _
    rw [biprod.lift_desc, comp_zero, Preadditive.neg_comp, Preadditive.comp_neg, neg_neg, zero_add]
    exact mvInclUV_V_comp_projVtoUV R U V k
  s_g := by
    change biprod.lift (routeU R U V hUV k) (routeV R U V hUV k) ≫
           biprod.desc ((mvInclUSmall R U V hUV).f k) ((mvInclVSmall R U V hUV).f k) = 𝟙 _
    rw [biprod.lift_desc]
    apply ModuleCat.hom_ext
    apply LinearMap.ext
    rintro ⟨c, hc⟩
    apply Subtype.ext
    simp only [ModuleCat.hom_add, ModuleCat.hom_comp,
      ModuleCat.hom_id]
    exact keepHom_split_small R U V hUV k c hc
  id := by
    change biprod.desc 0 (-projVtoUV R U V k) ≫
           biprod.lift ((mvInclUVU R U V).f k) (-(mvInclUVV R U V).f k) +
           biprod.desc ((mvInclUSmall R U V hUV).f k) ((mvInclVSmall R U V hUV).f k) ≫
           biprod.lift (routeU R U V hUV k) (routeV R U V hUV k) = 𝟙 _
    apply biprod.hom_ext'
    · apply biprod.hom_ext
      · simp only [Preadditive.comp_add, biprod.inl_desc_assoc, zero_comp,
          Category.assoc, biprod.lift_fst, Category.id_comp, zero_add, biprod.inl_fst]
        exact mvInclU_small_comp_routeU R U V hUV k
      · simp only [Preadditive.comp_add, biprod.inl_desc_assoc, zero_comp,
          Category.assoc, biprod.lift_snd, Category.id_comp, zero_add, biprod.inl_snd]
        exact mvInclU_small_comp_routeV R U V hUV k
    · apply biprod.hom_ext
      · simp only [Preadditive.comp_add, Preadditive.add_comp, biprod.inr_desc_assoc,
          Preadditive.neg_comp, Category.assoc, biprod.lift_fst, Category.id_comp, biprod.inr_fst]
        rw [mvInclV_small_comp_routeU R U V hUV k]
        abel
      · simp only [Preadditive.comp_add, Preadditive.add_comp, biprod.inr_desc_assoc,
          Preadditive.neg_comp, Preadditive.comp_neg, Category.assoc, biprod.lift_snd,
          neg_neg, Category.id_comp, biprod.inr_snd]
        exact projVtoUV_inclUV_V_add_inclV_routeV R U V hUV k

open Classical in
theorem biprodXIso_lift_f
    {K L M : ChainComplex (ModuleCat.{0} R) ℕ} (a : K ⟶ L) (b : K ⟶ M) (k : ℕ) :
    (biprod.lift a b).f k ≫ (HomologicalComplex.biprodXIso L M k).hom
      = biprod.lift (a.f k) (b.f k) :=
  biprod.map_lift_mapBiprod (HomologicalComplex.eval (ModuleCat.{0} R) (ComplexShape.down ℕ) k)
    L M a b

open Classical in
theorem biprodXIso_desc_f
    {K L M : ChainComplex (ModuleCat.{0} R) ℕ} (a : L ⟶ K) (b : M ⟶ K) (k : ℕ) :
    (HomologicalComplex.biprodXIso L M k).hom ≫ biprod.desc (a.f k) (b.f k)
      = (biprod.desc a b).f k :=
  biprod.mapBiprod_hom_desc (HomologicalComplex.eval (ModuleCat.{0} R) (ComplexShape.down ℕ) k)
    L M a b

open Classical in
/-- Identify evaluation of the chain short complex with its explicit degreewise form. -/
noncomputable def mvEvalIso (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ) :
    ((HomologicalComplex.eval (ModuleCat.{0} R) (ComplexShape.down ℕ) k).mapShortComplex.obj
      (mvShortComplex R U V hUV)) ≅ mvSplitSC R U V hUV k :=
  ShortComplex.isoMk (Iso.refl _)
    (HomologicalComplex.biprodXIso (subChainComplex R X (U : Set X)) (subChainComplex R X (V :
      Set X)) k)
    (Iso.refl _)
    (by
      change 𝟙 _ ≫ biprod.lift ((mvInclUVU R U V).f k) (-(mvInclUVV R U V).f k) =
           (mvLeftChainMap R U V).f k ≫
             (HomologicalComplex.biprodXIso (subChainComplex R X ↑U) (subChainComplex R X ↑V) k).hom
      rw [Category.id_comp]
      exact (biprodXIso_lift_f (R := R) (mvInclUVU R U V) (-mvInclUVV R U V) k).symm)
    (by
      change (HomologicalComplex.biprodXIso (subChainComplex R X ↑U) (subChainComplex R X ↑V)
        k).hom ≫
             biprod.desc ((mvInclUSmall R U V hUV).f k) ((mvInclVSmall R U V hUV).f k) =
           (mvRightChainMap R U V hUV).f k ≫ 𝟙 _
      rw [Category.comp_id]
      exact biprodXIso_desc_f (R := R) (mvInclUSmall R U V hUV) (mvInclVSmall R U V hUV) k)

open Classical in
theorem mvShortComplex_degreewise_shortExact (U V : Opens X) (hUV : U ⊔ V = ⊤) (k : ℕ) :
    ((HomologicalComplex.eval (ModuleCat.{0} R) (ComplexShape.down ℕ) k).mapShortComplex.obj
      (mvShortComplex R U V hUV)).ShortExact :=
  ShortComplex.shortExact_of_iso (mvEvalIso R U V hUV k).symm (mvSplitting R U V hUV k).shortExact

open Classical in
theorem mvShortComplex_shortExact (U V : Opens X) (hUV : U ⊔ V = ⊤) :
    (mvShortComplex R U V hUV).ShortExact :=
  HomologicalComplex.shortExact_of_degreewise_shortExact (mvShortComplex R U V hUV)
    (mvShortComplex_degreewise_shortExact R U V hUV)

end SphereOddDegree
