/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, Claude Opus 5
-/
module

public import LeanPool.DavisKahan.ForTauCeti.Analysis.InnerProductSpace.RealSpectrumDiagonalMeasure

/-!
# The cyclic multiplication model of a self-adjoint operator, on its real spectrum

`ForTauCeti/Analysis/InnerProductSpace/BorelCalculus/CyclicModel.lean` builds
`TauCeti.BorelCalculus.cyclicIsometry ha ξ : Lp ℂ 2 (diagMeasure ha ξ) →ₗᵢ[ℂ] H`, whose range
is the cyclic subspace generated by `ξ`.  Its domain is `L²` of a measure on `spectrum ℂ a`.
This module restates that isometry, and the identification of its range, over `spectrum ℝ a`
for a self-adjoint `a`.

## Why this costs nothing

The three preceding modules did all the work.  `realSpectrumHomeomorph` moved the spectrum,
`realSpectrumBddSymbols` moved the symbols, and `realSpectrumDiagMeasureLpEquiv` moved the
`L²` space -- and that last transport is a linear isometric *equivalence*, not merely a linear
isometry, because the underlying map is a Borel isomorphism.  So the real-spectrum model is
literally the old isometry precomposed with an isometric equivalence, and the range of a
composite whose right factor is **surjective** is the range of its left factor.  No density
argument is re-run here: every use of `denseRange_symbolToLp` in the library is inside
`BorelCalculus/CyclicModel.lean`, and this module does not mention it.

The refuted route -- lowering the symbol *codomain* to `ℝ` while `H` stays complex -- died at
exactly this statement, because the range of the resulting map is a real subspace while
`cyclicSubspace` is complex.  Lowering the *domain* instead keeps every scalar at `ℂ`, so the
obstruction does not arise: the transport is an equivalence of `ℂ`-Hilbert spaces.

## Main results

* `TauCeti.BorelCalculus.realSpectrumCyclicIsometry`: **the deliverable** -- the linear
  isometry `Lp ℂ 2 (realSpectrumDiagMeasure ha ξ) →ₗᵢ[ℂ] H`, with
  `realSpectrumCyclicIsometry_apply` as its characteristic equation and
  `realSpectrumCyclicIsometry_eq_borelCalculus` tying it back to the Borel calculus itself.
* `TauCeti.BorelCalculus.range_toLinearMap_realSpectrumDiagMeasureLpEquiv`: the `L²`
  transport is surjective, which is the only new fact the range argument consumes.
* `TauCeti.BorelCalculus.range_realSpectrumCyclicIsometry`: **the range theorem** -- the range
  is `cyclicSubspace ha.isStarNormal ξ`, exactly as for `range_cyclicIsometry`.
* `TauCeti.BorelCalculus.realSpectrumCyclicIsometry_mem_cyclicSubspace` and
  `TauCeti.BorelCalculus.exists_realSpectrumCyclicIsometry_eq`: the two directions of the
  range theorem in element form.

## What is deliberately not delivered

Nothing here touches `BorelCalculus/`.  The intertwining law (`cyclicIsometry_coordMulLp`)
is *not* transported: multiplication by the coordinate on the real spectrum is multiplication
by a **real** coordinate, which is a different operator on the nose, and relating the two is a
separate statement with its own cost.  Only the isometry and its range are moved here, which
is what a real-spectrum `SameSpectralMultiplicity` needs first.

## Provenance

* Original repository: Davis--Kahan/DKPS formalization (Kitware, Inc.); written here, new for
  this library.
* Extraction class: **new**.  The construction is one composition; the range theorem is
  `LinearMap.range_comp_of_range_eq_top` against the existing `range_cyclicIsometry`.
* Original authors / copyright: Jon Crall, Claude Opus 5; Copyright (c) 2026 Kitware, Inc.;
  Apache 2.0.
* Spectra influence: **none** -- this module imports only Mathlib and `ForTauCeti`.
-/

@[expose] public section

open MeasureTheory

namespace TauCeti
namespace BorelCalculus

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable {a : H →L[ℂ] H}

section Isometry

/-- **The cyclic multiplication model of a self-adjoint operator, over its real spectrum.**

The map `f ↦ f(a) ξ`, with the symbol read on `spectrum ℝ a` rather than on `spectrum ℂ a`:
it is `cyclicIsometry ha.isStarNormal ξ` precomposed with the `L²` transport
`realSpectrumDiagMeasureLpEquiv ha ξ`.  Composing a linear isometry with a linear isometric
equivalence is again a linear isometry, so no norm computation is repeated.

Note the two distinct witnesses: `diagMeasure` and `cyclicIsometry` take `IsStarNormal a`,
while `realSpectrumHomeomorph` and everything built on it takes `IsSelfAdjoint a`.  This
definition holds the self-adjointness witness and passes `ha.isStarNormal` where the older
layer needs it. -/
noncomputable def realSpectrumCyclicIsometry (ha : IsSelfAdjoint a) (ξ : H) :
    Lp ℂ 2 (realSpectrumDiagMeasure ha ξ) →ₗᵢ[ℂ] H :=
  (cyclicIsometry ha.isStarNormal ξ).comp (realSpectrumDiagMeasureLpEquiv ha ξ).toLinearIsometry

private theorem realSpectrumCyclicIsometry_apply_aux (ha : IsSelfAdjoint a) (ξ : H)
    (F : Lp ℂ 2 (realSpectrumDiagMeasure ha ξ)) :
    realSpectrumCyclicIsometry ha ξ F
      = cyclicIsometry ha.isStarNormal ξ (realSpectrumDiagMeasureLpEquiv ha ξ F) := rfl

/-- **The characteristic equation.**  The real-spectrum model is the complex-spectrum model
read after the `L²` transport, so no consumer needs the body of the definition. -/
theorem realSpectrumCyclicIsometry_apply (ha : IsSelfAdjoint a) (ξ : H)
    (F : Lp ℂ 2 (realSpectrumDiagMeasure ha ξ)) :
    realSpectrumCyclicIsometry ha ξ F
      = cyclicIsometry ha.isStarNormal ξ (realSpectrumDiagMeasureLpEquiv ha ξ F) :=
  realSpectrumCyclicIsometry_apply_aux ha ξ F

/-- **The characteristic equation against the Borel calculus.**  Whenever the transported
class is the class of a bounded measurable symbol, the real-spectrum model returns the value
of the Borel calculus of that symbol at `ξ` -- which is the defining property
`cyclicIsometry_symbolToLp` of the complex-spectrum model, moved across the transport. -/
theorem realSpectrumCyclicIsometry_eq_borelCalculus (ha : IsSelfAdjoint a) (ξ : H)
    (F : Lp ℂ 2 (realSpectrumDiagMeasure ha ξ)) (f : bddSymbols a)
    (hF : realSpectrumDiagMeasureLpEquiv ha ξ F = symbolToLp ha.isStarNormal ξ f) :
    realSpectrumCyclicIsometry ha ξ F
      = borelCalculus ha.isStarNormal (isBddMeasurable_coe f) ξ := by
  rw [realSpectrumCyclicIsometry_apply, hF]
  exact cyclicIsometry_symbolToLp ha.isStarNormal ξ f

end Isometry

section Range

/-- **The `L²` transport is surjective**, as a linear map.  This is the only new fact the
range theorem consumes: `realSpectrumDiagMeasureLpEquiv` is an equivalence, so its underlying
linear map has full range. -/
theorem range_toLinearMap_realSpectrumDiagMeasureLpEquiv (ha : IsSelfAdjoint a) (ξ : H) :
    LinearMap.range (realSpectrumDiagMeasureLpEquiv ha ξ).toLinearIsometry.toLinearMap = ⊤ :=
  LinearMap.range_eq_top.mpr (realSpectrumDiagMeasureLpEquiv ha ξ).surjective

private theorem realSpectrumCyclicIsometry_toLinearMap_aux (ha : IsSelfAdjoint a) (ξ : H) :
    (realSpectrumCyclicIsometry ha ξ).toLinearMap
      = (cyclicIsometry ha.isStarNormal ξ).toLinearMap.comp
          (realSpectrumDiagMeasureLpEquiv ha ξ).toLinearIsometry.toLinearMap := rfl

/-- **The range of the real-spectrum cyclic isometry is the cyclic subspace.**

This is `range_cyclicIsometry` unchanged: the range of a composite whose right factor is
surjective is the range of its left factor, and the right factor here is an isometric
*equivalence*.  In particular the density argument of `BorelCalculus/CyclicModel.lean` is not
re-run -- it is used through `range_cyclicIsometry` and nowhere else. -/
theorem range_realSpectrumCyclicIsometry (ha : IsSelfAdjoint a) (ξ : H) :
    LinearMap.range (realSpectrumCyclicIsometry ha ξ).toLinearMap
      = cyclicSubspace ha.isStarNormal ξ := by
  rw [realSpectrumCyclicIsometry_toLinearMap_aux,
    LinearMap.range_comp_of_range_eq_top _
      (range_toLinearMap_realSpectrumDiagMeasureLpEquiv ha ξ)]
  exact range_cyclicIsometry ha.isStarNormal ξ

/-- **The real-spectrum model lands in the cyclic subspace**: the easy half of the range
theorem, in element form. -/
theorem realSpectrumCyclicIsometry_mem_cyclicSubspace (ha : IsSelfAdjoint a) (ξ : H)
    (F : Lp ℂ 2 (realSpectrumDiagMeasure ha ξ)) :
    realSpectrumCyclicIsometry ha ξ F ∈ cyclicSubspace ha.isStarNormal ξ := by
  rw [← range_realSpectrumCyclicIsometry ha ξ]
  exact ⟨F, rfl⟩

/-- **The real-spectrum model exhausts the cyclic subspace**: the substantial half of the
range theorem, in element form.  Every vector of the cyclic subspace generated by `ξ` is the
value of the model at some `L²` class of a symbol on the **real** spectrum. -/
theorem exists_realSpectrumCyclicIsometry_eq (ha : IsSelfAdjoint a) (ξ : H) {y : H}
    (hy : y ∈ cyclicSubspace ha.isStarNormal ξ) :
    ∃ F : Lp ℂ 2 (realSpectrumDiagMeasure ha ξ), realSpectrumCyclicIsometry ha ξ F = y := by
  rw [← range_realSpectrumCyclicIsometry ha ξ] at hy
  obtain ⟨F, hFy⟩ := hy
  exact ⟨F, hFy⟩

end Range

end BorelCalculus
end TauCeti
