/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, Claude Opus 5
Adapted from: Spectra (https://github.com/adambornemann-glitch/Spectra),
  `Spectra/YosidaHille/Approximation/Commutation.lean` at commit
  `8dbaaf6728d1342ae16acf79fd7eef7c59b37e63`,
  Copyright (c) 2026 Spectra Formalization Project, `Authors: Adam Bornemann`,
  Apache 2.0.  Modified: see `## Provenance` (Apache 2.0 §4(b)); the donor's
  copyright and authorship notices are retained here and below (§4(c)).
-/
module

public import Mathlib.Analysis.SpecialFunctions.Exponential
public import Mathlib.Analysis.CStarAlgebra.Exponential
public import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus
public import Mathlib.Analysis.Calculus.Deriv.Mul

/-!
# The unitary group generated by a bounded skew-adjoint operator

For a bounded skew-adjoint `B` on a complex Hilbert space, `t ↦ exp (t • B)` is a
one-parameter unitary group.  The result this file exists for is the **Duhamel
estimate**

`‖exp (t • Bₘ) ψ - exp (t • Bₙ) ψ‖ ≤ |t| ‖(Bₘ - Bₙ) ψ‖`

for *commuting* skew-adjoint `Bₘ`, `Bₙ`.  It is what makes the Yosida
approximants `exp(i t Aₙˢʸᵐ)ψ` a Cauchy sequence, and hence what produces the
unitary group generated by an unbounded self-adjoint operator.

## Sources

That a bounded skew-adjoint operator exponentiates to a strongly continuous
one-parameter unitary group, and that this is the bounded case of Stone's theorem,
is standard (Reed--Simon, *Methods of Modern Mathematical Physics I*).  No source
is followed for the presentation.

## Provenance

* **Original repository:** Spectra, commit `8dbaaf6728d1342ae16acf79fd7eef7c59b37e63`.
* **Original module:** `Spectra/YosidaHille/Approximation/Commutation.lean`
  (`norm_expBounded_pairwise_le` and its supporting commutation lemmas).
* **Original authors / copyright / licence:** Copyright (c) 2026 Spectra
  Formalization Project; `Authors: Adam Bornemann`; Apache 2.0.
* **Extraction class:** *adapted.*  The proof architecture — differentiate
  `s ↦ exp((t-s)Bₙ) exp(sBₘ) ψ`, recognise the derivative as
  `exp((t-s)Bₙ) exp(sBₘ) (Bₘ - Bₙ) ψ`, integrate, and bound the integrand by
  unitarity — is Spectra's, and is the classical Duhamel argument.
* **Semantic differences from the donor:**
  1. Stated over Mathlib's `NormedSpace.exp` rather than Spectra's hand-rolled
     `expBounded` power series.  Spectra proves the two agree
     (`expBounded_eq_exp`), so nothing is lost; what *is* saved is the 576 lines
     of `ExpBounded/{Helpers,Adjoint,Unitary}` establishing summability, the
     group law and unitarity, all of which Mathlib already has.
  2. Unitarity comes from `selfAdjoint.expUnitary`, and the derivative from
     `hasDerivAt_exp_smul_const` — Mathlib's derivative of `t ↦ exp (t • x)` in a
     *non-commutative* algebra.
-/

public section

namespace TauCeti

open Complex NormedSpace
open scoped InnerProductSpace

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- `B` is skew-adjoint: `B⋆ = -B`. -/
def IsSkewAdjointCLM (B : H →L[ℂ] H) : Prop :=
  ContinuousLinearMap.adjoint B = -B

/-- `I • S` is skew-adjoint when `S` is self-adjoint. -/
theorem isSkewAdjointCLM_I_smul {S : H →L[ℂ] H} (hS : IsSelfAdjoint S) :
    IsSkewAdjointCLM (I • S) := by
  have : ContinuousLinearMap.adjoint (I • S) = (starRingEnd ℂ) I • ContinuousLinearMap.adjoint S :=
    ContinuousLinearMap.adjoint.map_smulₛₗ I S
  rw [IsSkewAdjointCLM, this, Complex.conj_I,
    (ContinuousLinearMap.isSelfAdjoint_iff'.mp hS), neg_smul]

/-- The exponential of a bounded operator scaled by a real time. -/
noncomputable def expTime (B : H →L[ℂ] H) (t : ℝ) : H →L[ℂ] H :=
  exp (t • B)

/-- **The flow unfolded.**  The characteristic lemma for `expTime`: a consumer in
another module that needs `exp (t • B)` should rewrite with this rather than
reach through the definition.

Written when this module stopped exposing its bodies:
`LinearPMap/YosidaApproximation.lean` was doing `rw [expTime]` and
`simp [expTime]`, which only works while the body is exposed. -/
theorem expTime_def (B : H →L[ℂ] H) (t : ℝ) : expTime B t = exp (t • B) := (rfl)

/-- The flow is the identity at time zero. -/
@[simp] theorem expTime_zero (B : H →L[ℂ] H) : expTime B 0 = 1 := by
  simp [expTime]

/-- `t ↦ exp (t • B)` has derivative `exp (t • B) * B`. -/
theorem hasDerivAt_expTime (B : H →L[ℂ] H) (t : ℝ) :
    HasDerivAt (expTime B) (expTime B t * B) t :=
  hasDerivAt_exp_smul_const (𝕂 := ℝ) B t

/-- `B` commutes with its own exponential. -/
theorem commute_expTime (B : H →L[ℂ] H) (t : ℝ) : Commute B (expTime B t) :=
  ((Commute.refl B).smul_right t).exp_right

/-- Commuting operators have commuting exponentials. -/
theorem commute_expTime_of_commute {B C : H →L[ℂ] H} (h : Commute B C) (t : ℝ) :
    Commute C (expTime B t) :=
  ((h.symm.smul_right t)).exp_right

/-! ### Unitarity -/

omit [CompleteSpace H] in
/-- `t • (I • S) = I • ((t : ℂ) • S)`: the real and complex scalings agree. -/
theorem real_smul_I_smul (S : H →L[ℂ] H) (t : ℝ) :
    t • (I • S) = I • ((t : ℂ) • S) := by
  rw [smul_comm]
  congr 1

/-- For self-adjoint `S`, `exp (t • (I • S))` is unitary, hence norm-preserving. -/
theorem norm_expTime_I_smul (S : H →L[ℂ] H) (hS : IsSelfAdjoint S) (t : ℝ) (ψ : H) :
    ‖expTime (I • S) t ψ‖ = ‖ψ‖ := by
  have hsa : ((t : ℂ) • S) ∈ selfAdjoint (H →L[ℂ] H) := by
    rw [selfAdjoint.mem_iff, star_smul, hS.star_eq, Complex.star_def, Complex.conj_ofReal]
  have hval : expTime (I • S) t = (selfAdjoint.expUnitary ⟨(t : ℂ) • S, hsa⟩ : H →L[ℂ] H) := by
    rw [expTime, real_smul_I_smul]
    rfl
  have hstar : (ContinuousLinearMap.adjoint (expTime (I • S) t)) * expTime (I • S) t = 1 := by
    rw [hval]
    have := Unitary.coe_star_mul_self (selfAdjoint.expUnitary ⟨(t : ℂ) • S, hsa⟩)
    rwa [ContinuousLinearMap.star_eq_adjoint] at this
  have hinner : ⟪expTime (I • S) t ψ, expTime (I • S) t ψ⟫_ℂ = ⟪ψ, ψ⟫_ℂ := by
    calc ⟪expTime (I • S) t ψ, expTime (I • S) t ψ⟫_ℂ
        = ⟪(ContinuousLinearMap.adjoint (expTime (I • S) t)) (expTime (I • S) t ψ), ψ⟫_ℂ := by
          rw [ContinuousLinearMap.adjoint_inner_left]
      _ = ⟪((ContinuousLinearMap.adjoint (expTime (I • S) t)) * expTime (I • S) t) ψ, ψ⟫_ℂ := rfl
      _ = ⟪ψ, ψ⟫_ℂ := by rw [hstar]; rfl
  -- take real parts: `re ⟪x, x⟫ = ‖x‖ ^ 2`
  have h1 : ‖expTime (I • S) t ψ‖ ^ 2 = ‖ψ‖ ^ 2 := by
    rw [← @inner_self_eq_norm_sq ℂ, ← @inner_self_eq_norm_sq ℂ, hinner]
  have h2 := congrArg Real.sqrt h1
  rwa [Real.sqrt_sq (norm_nonneg _), Real.sqrt_sq (norm_nonneg _)] at h2

/-! ### The Duhamel estimate -/

/-- `s ↦ exp((t-s) • Bₙ)` differentiates to `-(exp((t-s) • Bₙ) * Bₙ)`. -/
private theorem hasDerivAt_expTime_sub (B : H →L[ℂ] H) (t s : ℝ) :
    HasDerivAt (fun s : ℝ => expTime B (t - s)) (-(expTime B (t - s) * B)) s := by
  have h2 : HasDerivAt (fun s : ℝ => t - s) (-1) s := by
    simpa using (hasDerivAt_id s).const_sub t
  simpa [Function.comp_def] using (hasDerivAt_expTime B (t - s)).scomp s h2

/-- `s ↦ exp(s • B) ψ` differentiates to `(exp(s • B) * B) ψ`. -/
@[simp]
theorem hasDerivAt_expTime_apply (B : H →L[ℂ] H) (ψ : H) (s : ℝ) :
    HasDerivAt (fun s : ℝ => expTime B s ψ) ((expTime B s * B) ψ) s := by
  have h := ((ContinuousLinearMap.apply ℂ H ψ).restrictScalars ℝ).hasFDerivAt.comp_hasDerivAt s
    (hasDerivAt_expTime B s)
  exact HasDerivAt.congr_deriv h rfl

/-- **The Duhamel estimate.**  For commuting skew-adjoint generators the two
unitary flows differ by at most `|t|` times the difference of the generators. -/
theorem norm_expTime_sub_expTime_le {Sm Sn : H →L[ℂ] H}
    (hm : IsSelfAdjoint Sm) (hn : IsSelfAdjoint Sn) (hcomm : Commute Sm Sn)
    (t : ℝ) (ψ : H) :
    ‖expTime (I • Sm) t ψ - expTime (I • Sn) t ψ‖
      ≤ |t| * ‖(I • Sm - I • Sn) ψ‖ := by
  set Bm : H →L[ℂ] H := I • Sm with hBm
  set Bn : H →L[ℂ] H := I • Sn with hBn
  have hBcomm : Commute Bm Bn := (hcomm.smul_left I).smul_right I
  -- the derivative of the interpolating path
  have hderiv : ∀ s : ℝ, HasDerivAt
      (fun s => expTime Bn (t - s) (expTime Bm s ψ))
      (expTime Bn (t - s) (expTime Bm s ((Bm - Bn) ψ))) s := by
    intro s
    have hf := hasDerivAt_expTime_sub Bn t s
    have hu := hasDerivAt_expTime_apply Bm ψ s
    -- `Bn` commutes with `exp(s • Bm)`
    have hcEn : Commute Bn (expTime Bm s) := commute_expTime_of_commute hBcomm s
    have hswap : Bn (expTime Bm s ψ) = expTime Bm s (Bn ψ) := by
      have h := congrArg (fun T : H →L[ℂ] H => T ψ) hcEn
      simpa using h
    have hval : expTime Bn (t - s) (expTime Bm s ((Bm - Bn) ψ))
        = (-(expTime Bn (t - s) * Bn)) (expTime Bm s ψ)
          + expTime Bn (t - s) ((expTime Bm s * Bm) ψ) := by
      have hsub : expTime Bm s ((Bm - Bn) ψ)
          = (expTime Bm s * Bm) ψ - Bn (expTime Bm s ψ) := by
        rw [hswap]
        simp only [sub_apply, map_sub]
        rfl
      rw [hsub, map_sub]
      simp only [neg_apply]
      abel
    -- `clm_apply` differentiates in `ℝ`, so the ℂ-linear operators must have their
    -- scalars restricted first
    have hf' := (ContinuousLinearMap.restrictScalarsL ℂ H H ℝ ℝ).hasFDerivAt.comp_hasDerivAt s hf
    rw [hval]
    simpa using HasDerivAt.clm_apply hf' hu
  -- continuity of the derivative, for integrability
  have hcont : Continuous
      (fun s : ℝ => expTime Bn (t - s) (expTime Bm s ((Bm - Bn) ψ))) := by
    have cBn : Continuous (fun τ : ℝ => expTime Bn τ) :=
      Differentiable.continuous fun τ => (hasDerivAt_expTime Bn τ).differentiableAt
    have cBm : Continuous (fun τ : ℝ => expTime Bm τ) :=
      Differentiable.continuous fun τ => (hasDerivAt_expTime Bm τ).differentiableAt
    exact (cBn.comp (continuous_const.sub continuous_id)).clm_apply
      (cBm.clm_apply continuous_const)
  -- fundamental theorem of calculus
  have hftc : (∫ s in (0 : ℝ)..t, expTime Bn (t - s) (expTime Bm s ((Bm - Bn) ψ)))
      = expTime Bm t ψ - expTime Bn t ψ := by
    have h := intervalIntegral.integral_eq_sub_of_hasDerivAt
      (f := fun s => expTime Bn (t - s) (expTime Bm s ψ))
      (fun s _ => hderiv s) (hcont.intervalIntegrable 0 t)
    simpa using h
  -- the integrand has constant norm, by unitarity of both flows
  have hnorm : ∀ s : ℝ,
      ‖expTime Bn (t - s) (expTime Bm s ((Bm - Bn) ψ))‖ = ‖(Bm - Bn) ψ‖ := by
    intro s
    rw [hBn, norm_expTime_I_smul Sn hn, hBm, norm_expTime_I_smul Sm hm]
  calc ‖expTime Bm t ψ - expTime Bn t ψ‖
      = ‖∫ s in (0 : ℝ)..t, expTime Bn (t - s) (expTime Bm s ((Bm - Bn) ψ))‖ := by rw [hftc]
    _ ≤ ‖(Bm - Bn) ψ‖ * |t - 0| := by
        refine intervalIntegral.norm_integral_le_of_norm_le_const fun s _ => ?_
        exact le_of_eq (hnorm s)
    _ = |t| * ‖(Bm - Bn) ψ‖ := by rw [sub_zero, mul_comm]

end TauCeti
