/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking, Claude Opus 5
-/
module

public import LeanPool.DavisKahan.DavisKahan.SpectralTheory.SpectralRestriction
public import LeanPool.DavisKahan.ForTauCeti.Analysis.InnerProductSpace.LinearPMap.YosidaApproximation

/-!
# Self-adjoint operators on spectral ranges

For a self-adjoint operator `A` and a measurable spectral set `B`, this file
packages the restriction of `A` to the range of `E_A(B)` as a partial map,
self-adjoint by a separate theorem, whose subtype inclusion maps the restricted
domain into
`A.domain` and intertwines the two operators.

## Provenance

Until 2026-07-28 this went through `vendor/Spectra`'s Stone theory: the unitary
group `genToGroup hA` was restricted to the spectral range (which required
`spectralCalculus_group_comm` to see that the projection commutes with the
group), and the restricted operator was recovered as the *Stone generator* of
the restricted group, self-adjoint by
`Spectra.Resolvent.generator_isSelfAdjoint`.  Identifying it with `A` on the
range then needed `generator_genToGroup`, i.e. the hard direction of Stone's
theorem.

None of that is necessary.  The restriction is definable directly — domain
`{x ∈ ran E_A(B) | x ∈ dom A}`, action `x ↦ A x` — and is self-adjoint by the
`(· ± i)`-surjectivity criterion, because the resolvent preserves the spectral
range (it commutes with the projection: both are images of the same Borel
calculus of the Cayley transform).  See
`ForTauCeti/Analysis/InnerProductSpace/LinearPMap/SpectralMeasure.lean`,
`specRestrict` and `isSelfAdjoint_specRestrict`.  The declarations this module
exports downstream are unchanged; the group-theoretic scaffolding that
supported them is gone.
-/

@[expose] public section

open scoped InnerProductSpace
open Filter Topology

namespace TauCeti
namespace DavisKahan

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H]

/-- The restriction of a self-adjoint operator to one of its spectral ranges.

Stated over the Davis--Kahan spectral subspace rather than `specRange`, which it
is definitionally; the instances downstream key on this name. -/
noncomputable def selfAdjointSpectralRestriction
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A)
    (B : Set ℝ) (hB : MeasurableSet B) :
    selfAdjointSpectralSubspace A hA B hB →ₗ.[ℂ]
      selfAdjointSpectralSubspace A hA B hB :=
  TauCeti.LinearPMap.specRestrict hA B hB

/-- The spectral restriction is self-adjoint. -/
theorem selfAdjointSpectralRestriction_isSelfAdjoint
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A)
    (B : Set ℝ) (hB : MeasurableSet B) :
    IsSelfAdjoint (selfAdjointSpectralRestriction A hA B hB) :=
  TauCeti.LinearPMap.isSelfAdjoint_specRestrict hA B hB

/-- The spectral-range inclusion maps the restricted operator domain into the
ambient operator domain. -/
theorem selfAdjointSpectralRestriction_inclusion_mem_domain
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A)
    (B : Set ℝ) (hB : MeasurableSet B)
    (x : (selfAdjointSpectralRestriction A hA B hB).domain) :
    selfAdjointSpectralSubspaceInclusion A hA B hB
        (x : selfAdjointSpectralSubspace A hA B hB) ∈ A.domain :=
  x.2

/-- The spectral-range inclusion intertwines the restricted closed operator
with the ambient self-adjoint operator. -/
theorem selfAdjointSpectralRestriction_inclusion_intertwines
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A)
    (B : Set ℝ) (hB : MeasurableSet B)
    (x : (selfAdjointSpectralRestriction A hA B hB).domain) :
    A ⟨selfAdjointSpectralSubspaceInclusion A hA B hB
          (x : selfAdjointSpectralSubspace A hA B hB),
        selfAdjointSpectralRestriction_inclusion_mem_domain A hA B hB x⟩ =
      selfAdjointSpectralSubspaceInclusion A hA B hB
        (selfAdjointSpectralRestriction A hA B hB x) :=
  rfl

/-- The one-parameter unitary group generated by the spectral restriction. -/
noncomputable def selfAdjointSpectralSubspaceUnitaryGroup
    (A : H →ₗ.[ℂ] H) (hA : IsSelfAdjoint A)
    (B : Set ℝ) (hB : MeasurableSet B) :
    TauCeti.OneParameterUnitaryGroup (selfAdjointSpectralSubspace A hA B hB) :=
  TauCeti.LinearPMap.genToGroup
    (TauCeti.LinearPMap.isSelfAdjoint_specRestrict hA B hB)

end DavisKahan
end TauCeti
