/-
Copyright (c) 2026 Kenny Lau, Bhavik Mehta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau, Bhavik Mehta
-/

import Mathlib.Tactic.NormNum.Prime
import LeanPool.PrimeCert.Pocklington

/-! # Primality proofs for small primes

Primes 2–293 are certified via `pock%`; primes 301–2300 are generated by `norm_num`
(via the `make%` macro). These supply the `PrimeCert.prime_N` declarations used by
the `small` certificate method.
-/

namespace PrimeCert

theorem prime_2 : Nat.Prime 2 := Nat.prime_two
theorem prime_3 : Nat.Prime 3 := Nat.prime_three
theorem prime_5 : Nat.Prime 5 := pock% [2; (5, 2, 2 ^ 2)]
theorem prime_7 : Nat.Prime 7 := pock% [3; (7, 2, 3)]
theorem prime_11 : Nat.Prime 11 := pock% [5; (11, 2, 5)]
theorem prime_13 : Nat.Prime 13 := pock% [2; (13, 2, 2 ^ 2)]
theorem prime_17 : Nat.Prime 17 := pock% [2; (17, 3, 2 ^ 3)]
theorem prime_19 : Nat.Prime 19 := pock% [3; (19, 2, 3 ^ 2)]
theorem prime_23 : Nat.Prime 23 := pock% [11; (23, 2, 11)]
theorem prime_29 : Nat.Prime 29 := pock% [7; (29, 2, 7)]
theorem prime_31 : Nat.Prime 31 := pock% [2, 3; (31, 3, 2 * 3)]
theorem prime_37 : Nat.Prime 37 := pock% [3; (37, 2, 3 ^ 2)]
theorem prime_41 : Nat.Prime 41 := pock% [2; (41, 3, 2 ^ 3)]
theorem prime_43 : Nat.Prime 43 := pock% [7; (43, 2, 7)]
theorem prime_47 : Nat.Prime 47 := pock% [23; (47, 2, 23)]
theorem prime_53 : Nat.Prime 53 := pock% [13; (53, 2, 13)]
theorem prime_59 : Nat.Prime 59 := pock% [29; (59, 2, 29)]
theorem prime_61 : Nat.Prime 61 := pock% [2, 3; (61, 2, 2 ^ 2 * 3)]
theorem prime_67 : Nat.Prime 67 := pock% [11; (67, 2, 11)]
theorem prime_71 : Nat.Prime 71 := pock% [2, 5; (71, 7, 2 * 5)]
theorem prime_73 : Nat.Prime 73 := pock% [3; (73, 2, 3 ^ 2)]
theorem prime_79 : Nat.Prime 79 := pock% [13; (79, 2, 13)]
theorem prime_83 : Nat.Prime 83 := pock% [41; (83, 2, 41)]
theorem prime_89 : Nat.Prime 89 := pock% [11; (89, 2, 11)]
theorem prime_97 : Nat.Prime 97 := pock% [2; (97, 5, 2 ^ 4)]

theorem prime_101 : Nat.Prime 101 := pock% [5; (101, 2, 5 ^ 2)]
theorem prime_103 : Nat.Prime 103 := pock% [17; (103, 2, 17)]
theorem prime_107 : Nat.Prime 107 := pock% [53; (107, 2, 53)]
theorem prime_109 : Nat.Prime 109 := pock% [3; (109, 3, 3 ^ 3)]
theorem prime_113 : Nat.Prime 113 := pock% [2; (113, 3, 2 ^ 4)]
theorem prime_127 : Nat.Prime 127 := pock% [2, 7; (127, 3, 2 * 7)]
theorem prime_131 : Nat.Prime 131 := pock% [13; (131, 2, 13)]
theorem prime_137 : Nat.Prime 137 := pock% [17; (137, 2, 17)]
theorem prime_139 : Nat.Prime 139 := pock% [23; (139, 2, 23)]
theorem prime_149 : Nat.Prime 149 := pock% [37; (149, 2, 37)]
theorem prime_151 : Nat.Prime 151 := pock% [5; (151, 3, 5 ^ 2)]
theorem prime_157 : Nat.Prime 157 := pock% [13; (157, 2, 13)]
theorem prime_163 : Nat.Prime 163 := pock% [3; (163, 2, 3 ^ 4)]
theorem prime_167 : Nat.Prime 167 := pock% [83; (167, 2, 83)]
theorem prime_173 : Nat.Prime 173 := pock% [43; (173, 2, 43)]
theorem prime_179 : Nat.Prime 179 := pock% [89; (179, 2, 89)]
theorem prime_181 : Nat.Prime 181 := pock% [2, 5; (181, 2, 2 ^ 2 * 5)]
theorem prime_191 : Nat.Prime 191 := pock% [19; (191, 2, 19)]
theorem prime_193 : Nat.Prime 193 := pock% [2; (193, 5, 2 ^ 6)]
theorem prime_197 : Nat.Prime 197 := pock% [7; (197, 2, 7 ^ 2)]
theorem prime_199 : Nat.Prime 199 := pock% [2, 3; (199, 3, 2 * 3 ^ 2)]

theorem prime_211 : Nat.Prime 211 := pock% [3, 5; (211, 2, 3 * 5)]
theorem prime_223 : Nat.Prime 223 := pock% [37; (223, 2, 37)]
theorem prime_227 : Nat.Prime 227 := pock% [113; (227, 2, 113)]
theorem prime_229 : Nat.Prime 229 := pock% [19; (229, 2, 19)]
theorem prime_233 : Nat.Prime 233 := pock% [29; (233, 2, 29)]
theorem prime_239 : Nat.Prime 239 := pock% [17; (239, 2, 17)]
theorem prime_241 : Nat.Prime 241 := pock% [2; (241, 7, 2 ^ 4)]
theorem prime_251 : Nat.Prime 251 := pock% [5; (251, 3, 5 ^ 3)]
theorem prime_257 : Nat.Prime 257 := pock% [2; (257, 3, 2 ^ 8)]
theorem prime_263 : Nat.Prime 263 := pock% [131; (263, 2, 131)]
theorem prime_269 : Nat.Prime 269 := pock% [67; (269, 2, 67)]
theorem prime_271 : Nat.Prime 271 := pock% [3; (271, 2, 3 ^ 3)]
theorem prime_277 : Nat.Prime 277 := pock% [23; (277, 2, 23)]
theorem prime_281 : Nat.Prime 281 := pock% [2, 5; (281, 3, 2 ^ 3 * 5)]
theorem prime_283 : Nat.Prime 283 := pock% [47; (283, 2, 47)]
theorem prime_293 : Nat.Prime 293 := pock% [73; (293, 2, 73)]

local elab "make%" a:num b:num : command => do
  for i in Array.range' a.getNat b.getNat do
    if Nat.Prime i then
      have iStx := Lean.Syntax.mkNatLit i
      have name := Lean.mkIdent <| Lean.Name.mkSimple s!"prime_{i}"
      Lean.Elab.Command.elabCommand =<< `(command| theorem $name : Nat.Prime $iStx := by norm_num)

make% 301 2000


end PrimeCert
