"""Render the candidates README from a Reservoir manifest.

The candidates README is the human-facing index of every Lean package
known to Reservoir. We render the table fresh from the manifest each
time rather than storing per-package metadata files, so there is only
one source of truth for the descriptive fields.

The renderer replaces the content between two HTML comment markers in
``aggregator/candidates/README.md``:

    <!-- BEGIN AUTOGENERATED TABLE -->
    ...generated table goes here...
    <!-- END AUTOGENERATED TABLE -->
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from lean_pool.aggregator.reservoir import Build, Package, ReservoirManifest

logger = logging.getLogger(__name__)

BEGIN_MARKER = "<!-- BEGIN AUTOGENERATED TABLE -->"
END_MARKER = "<!-- END AUTOGENERATED TABLE -->"

_MARKER_BLOCK = re.compile(
    re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
    re.DOTALL,
)

_TABLE_HEADER = (
    "| Stars | Package | Description | License | Lean | Updated | Build |\n"
    "| ---: | --- | --- | --- | --- | --- | :---: |\n"
)

_DESCRIPTION_LIMIT = 120

_GITHUB_URL_RE = re.compile(
    r"github\.com/(?P<owner>[^/\s]+)/(?P<name>[^/\s#?]+?)(?:\.git)?/?(?:[\s?#]|$)",
    re.IGNORECASE,
)

# Suffixes commonly tacked onto Lean repo names that shouldn't affect
# whether two URLs refer to the same repo (Lake project naming convention,
# git clone URL convention).
_REPO_NAME_SUFFIXES = (".lean", ".git")

# Strip the ``leanprover/lean4:`` channel prefix from a ``lean-toolchain``
# pin so the table cell shows just the version (e.g. ``v4.30.0``).
_TOOLCHAIN_PREFIX_RE = re.compile(r"^leanprover/lean4:", re.IGNORECASE)


def canonical_key(owner: str, name: str) -> str:
    """Reduce ``owner/name`` to a case- and suffix-insensitive key.

    Two URLs that point at the same GitHub repo should produce the same
    key even when one uses ``Repo.lean`` and the other uses ``Repo``,
    or when casing differs.
    """
    lowered = name.lower()
    for suffix in _REPO_NAME_SUFFIXES:
        if lowered.endswith(suffix):
            lowered = lowered[: -len(suffix)]
            break
    return f"{owner.lower()}/{lowered}"


def package_key(package: Package) -> str | None:
    """Return the canonical GitHub key for a package, if derivable.

    Tries each ``sources[*].repoUrl``/``gitUrl`` first because Reservoir
    sets ``fullName`` to the lakefile package name, which can differ
    from the GitHub repo path (e.g. ``argumentcomputer/Straume`` for
    the repo at ``argumentcomputer/straume``). Falls back to splitting
    ``fullName`` only if no source URL is present.
    """
    for source in package.get("sources") or []:
        for url_field in ("repoUrl", "gitUrl"):
            url = source.get(url_field) or ""
            match = _GITHUB_URL_RE.search(url + " ")
            if match:
                return canonical_key(match["owner"], match["name"])
    full_name = package.get("fullName") or ""
    if "/" in full_name:
        owner, _, name = full_name.partition("/")
        return canonical_key(owner, name)
    return None


def _escape_cell(value: str) -> str:
    """Make a string safe to embed in a markdown table cell.

    Replaces newlines with spaces, collapses whitespace, and escapes
    pipe characters so they don't break column boundaries.
    """
    collapsed = " ".join(value.split())
    return collapsed.replace("|", r"\|")


def _truncate(text: str, limit: int) -> str:
    """Truncate ``text`` to ``limit`` characters with an ellipsis."""
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


def _repo_url(package: Package) -> str | None:
    """Return the package's primary repository URL, if available."""
    sources = package.get("sources") or []
    if not sources:
        return None
    return sources[0].get("repoUrl") or sources[0].get("gitUrl")


def _build_glyph(build: Build | None) -> str:
    """Render a build result as a single glyph for the table."""
    if build is None:
        return "–"
    built = build.get("built")
    if built is True:
        return "✓"
    if built is False:
        return "✗"
    return "–"


def read_toolchain(clones_dir: Path, key: str) -> str | None:
    """Read the root ``lean-toolchain`` pin for a cloned repo.

    Looks for ``<clones_dir>/<owner>/<name>/lean-toolchain`` (the
    canonical key controls the directory layout the cloner writes to)
    and returns just the version part with the ``leanprover/lean4:``
    channel prefix stripped, so callers see ``v4.30.0`` rather than
    ``leanprover/lean4:v4.30.0``.

    Args:
        clones_dir: Root of the local clone cache.
        key: Canonical ``owner/name`` key from :func:`package_key`.

    Returns:
        The toolchain version, or ``None`` if the file is missing,
        unreadable, or empty.
    """
    owner, _, name = key.partition("/")
    path = clones_dir / owner / name / "lean-toolchain"
    if not path.is_file():
        return None
    try:
        text = path.read_text(encoding="utf-8", errors="replace").strip()
    except OSError:
        return None
    if not text:
        return None
    stripped = _TOOLCHAIN_PREFIX_RE.sub("", text, count=1).strip()
    return stripped or None


def _row(package: Package, toolchain: str | None) -> str:
    """Render a single package as a markdown table row."""
    full_name = package["fullName"]
    repo_url = _repo_url(package)
    name_cell = f"[{full_name}]({repo_url})" if repo_url else full_name

    raw_description = package.get("description") or ""
    description = _escape_cell(_truncate(raw_description, _DESCRIPTION_LIMIT))
    license_name = _escape_cell(package.get("license") or "")
    toolchain_cell = _escape_cell(toolchain or "")

    # Reservoir reports updatedAt as ISO-8601; the leading 10 chars are the
    # date portion, which is the only granularity that's useful here.
    updated = (package.get("updatedAt") or "")[:10]

    builds = package.get("builds") or []
    build_glyph = _build_glyph(builds[0] if builds else None)

    stars = package.get("stars", 0)
    return (
        f"| {stars} | {name_cell} | {description} | "
        f"{license_name} | {toolchain_cell} | {updated} | {build_glyph} |"
    )


def render_table(manifest: ReservoirManifest, clones_dir: Path | None = None) -> str:
    """Render the manifest as a markdown table.

    Packages are deduplicated by :func:`package_key` first (the first
    occurrence wins, so callers should put authoritative entries —
    typically Reservoir packages — before the fallback list), then
    sorted by star count descending with ``fullName`` tiebreak.

    Args:
        manifest: The full Reservoir manifest with packages in priority
            order.
        clones_dir: If set, the directory of local shallow clones
            (produced by ``lean_pool.aggregator clone``). When present,
            each row's Lean column is read from the repo's
            ``lean-toolchain`` file; otherwise that column is blank.

    Returns:
        A markdown table including header, separator, and one row per
        unique package.
    """
    seen: set[str] = set()
    deduped: list[Package] = []
    for package in manifest["packages"]:
        key = package_key(package)
        if key is None:
            deduped.append(package)
            continue
        if key in seen:
            continue
        seen.add(key)
        deduped.append(package)

    packages = sorted(
        deduped,
        key=lambda p: (-p.get("stars", 0), p["fullName"].lower()),
    )

    def _toolchain_for(package: Package) -> str | None:
        if clones_dir is None:
            return None
        key = package_key(package)
        if key is None:
            return None
        return read_toolchain(clones_dir, key)

    rows = "\n".join(_row(p, _toolchain_for(p)) for p in packages)
    return _TABLE_HEADER + rows + "\n"


def update_readme(readme_path: Path, table: str) -> None:
    """Replace the autogenerated block in ``readme_path`` with ``table``.

    Args:
        readme_path: Path to the candidates README. Must already
            contain both BEGIN and END autogenerated markers.
        table: Markdown content to insert between the markers.
    """
    original = readme_path.read_text()
    if not _MARKER_BLOCK.search(original):
        raise ValueError(
            f"Could not find autogenerated markers in {readme_path}. "
            f"Expected '{BEGIN_MARKER}' ... '{END_MARKER}'."
        )
    replacement = f"{BEGIN_MARKER}\n{table}{END_MARKER}"
    updated = _MARKER_BLOCK.sub(replacement, original, count=1)
    readme_path.write_text(updated)
    logger.info("Updated %s", readme_path)
