"""Render the candidates README from a Reservoir manifest.

The candidates README is the human-facing index of every Lean package
known to Reservoir. We render the table fresh from the manifest each
time rather than storing per-package metadata files, so there is only
one source of truth for the descriptive fields.

The renderer replaces the content between two HTML comment markers in
``aggregator/candidates/README.md``:

    <!-- BEGIN AUTOGENERATED TABLE -->
    ...generated table goes here...
    <!-- END AUTOGENERATED TABLE -->
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from lean_pool.aggregator.reservoir import Build, Package, ReservoirManifest

logger = logging.getLogger(__name__)

BEGIN_MARKER = "<!-- BEGIN AUTOGENERATED TABLE -->"
END_MARKER = "<!-- END AUTOGENERATED TABLE -->"

_MARKER_BLOCK = re.compile(
    re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
    re.DOTALL,
)

_TABLE_HEADER = (
    "| Stars | Package | Description | License | Updated | Build |\n"
    "| ---: | --- | --- | --- | --- | :---: |\n"
)

_DESCRIPTION_LIMIT = 120


def _escape_cell(value: str) -> str:
    """Make a string safe to embed in a markdown table cell.

    Replaces newlines with spaces, collapses whitespace, and escapes
    pipe characters so they don't break column boundaries.
    """
    collapsed = " ".join(value.split())
    return collapsed.replace("|", r"\|")


def _truncate(text: str, limit: int) -> str:
    """Truncate ``text`` to ``limit`` characters with an ellipsis."""
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


def _repo_url(package: Package) -> str | None:
    """Return the package's primary repository URL, if available."""
    sources = package.get("sources") or []
    if not sources:
        return None
    return sources[0].get("repoUrl") or sources[0].get("gitUrl")


def _build_glyph(build: Build | None) -> str:
    """Render a build result as a single glyph for the table."""
    if build is None:
        return "–"
    built = build.get("built")
    if built is True:
        return "✓"
    if built is False:
        return "✗"
    return "–"


def _row(package: Package) -> str:
    """Render a single package as a markdown table row."""
    full_name = package["fullName"]
    repo_url = _repo_url(package)
    name_cell = f"[{full_name}]({repo_url})" if repo_url else full_name

    raw_description = package.get("description") or ""
    description = _escape_cell(_truncate(raw_description, _DESCRIPTION_LIMIT))
    license_name = _escape_cell(package.get("license") or "")

    # Reservoir reports updatedAt as ISO-8601; the leading 10 chars are the
    # date portion, which is the only granularity that's useful here.
    updated = (package.get("updatedAt") or "")[:10]

    builds = package.get("builds") or []
    build_glyph = _build_glyph(builds[0] if builds else None)

    stars = package.get("stars", 0)
    return (
        f"| {stars} | {name_cell} | {description} | "
        f"{license_name} | {updated} | {build_glyph} |"
    )


def render_table(manifest: ReservoirManifest) -> str:
    """Render the manifest as a markdown table.

    Packages are sorted by star count descending, with ties broken by
    ``fullName`` to keep diffs stable. The returned string includes a
    trailing newline.

    Args:
        manifest: The full Reservoir manifest.

    Returns:
        A markdown table including header, separator, and one row per
        package.
    """
    packages = sorted(
        manifest["packages"],
        key=lambda p: (-p.get("stars", 0), p["fullName"].lower()),
    )
    rows = "\n".join(_row(p) for p in packages)
    return _TABLE_HEADER + rows + "\n"


def update_readme(readme_path: Path, table: str) -> None:
    """Replace the autogenerated block in ``readme_path`` with ``table``.

    Args:
        readme_path: Path to the candidates README. Must already
            contain both BEGIN and END autogenerated markers.
        table: Markdown content to insert between the markers.
    """
    original = readme_path.read_text()
    if not _MARKER_BLOCK.search(original):
        raise ValueError(
            f"Could not find autogenerated markers in {readme_path}. "
            f"Expected '{BEGIN_MARKER}' ... '{END_MARKER}'."
        )
    replacement = f"{BEGIN_MARKER}\n{table}{END_MARKER}"
    updated = _MARKER_BLOCK.sub(replacement, original, count=1)
    readme_path.write_text(updated)
    logger.info("Updated %s", readme_path)
