/-
Copyright (c) 2026 Barinder S. Banwait. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Barinder S. Banwait
-/

import Mathlib.Algebra.QuadraticAlgebra.Basic
import Mathlib.RingTheory.Adjoin.Basic
import LeanPool.RamanujanNagell.QuadraticIntegers.RingOfIntegers

open QuadraticAlgebra

noncomputable section

/-! ## The field isomorphism K' ≃ₐ[ℚ] K

We construct an explicit ℚ-algebra isomorphism between
  K' = QuadraticAlgebra ℚ (-7) 0   (ω' satisfies (ω')² = -7)
  K  = QuadraticAlgebra ℚ (-2) 1   (ω  satisfies ω²  = -2 + ω)

The isomorphism sends ω' ↦ 2ω - 1 (in K), since:
  (2ω - 1)² = 4ω² - 4ω + 1 = 4(-2 + ω) - 4ω + 1 = -8 + 4ω - 4ω + 1 = -7  ✓

The inverse sends ω ↦ (ω' + 1)/2 (in K').
-/

-- Use a local abbreviation to avoid exporting `K` into the importer's namespace.
-- Callers should use `QuadraticAlgebra ℚ (-2 : ℤ) 1` directly.
private abbrev Klocal := QuadraticAlgebra ℚ (-2 : ℤ) 1

/-- The ℚ-algebra map K' → K sending ω' ↦ 2ω - 1. -/
def toK : K' →ₐ[ℚ] Klocal :=
  QuadraticAlgebra.lift ⟨2 * (ω : Klocal) - 1, by
    -- Need: (2ω-1)² = (-7:ℚ)•1 + 0•(2ω-1)  in Klocal
    -- Verified component-wise: .re = 1 - 8 = -7, .im = -2 - 2 + 4 = 0
    ext
    · simp [re_mul, im_mul, omega_re, omega_im]; ring
    · simp [re_mul, im_mul, omega_re, omega_im]; ring⟩

/-- The ℚ-algebra map K → K' sending ω ↦ (ω' + 1)/2. -/
def toK' : Klocal →ₐ[ℚ] K' :=
  QuadraticAlgebra.lift ⟨(1/2 : ℚ) • ((ω : K') + 1), by
    -- Need: ((ω'+1)/2)² = (-2:ℚ)•1 + 1•((ω'+1)/2)  in K'
    -- LHS: (-7+2ω'+1)/4 = -3/2 + ω'/2 = -2 + (ω'+1)/2 = RHS  ✓
    ext
    · simp [re_mul, omega_re, omega_im, re_smul, im_smul]; ring
    · simp [im_mul, omega_re, omega_im, re_smul, im_smul]; ring⟩

/-- The field isomorphism K' ≃ₐ[ℚ] K. -/
def fieldIso : K' ≃ₐ[ℚ] Klocal :=
  AlgEquiv.ofAlgHom toK toK'
    (QuadraticAlgebra.algHom_ext (by
      simp only [AlgHom.comp_apply, AlgHom.id_apply]
      simp [toK, toK', lift, omega_re, omega_im, re_smul, im_smul, smul_add, smul_smul]
      ext
      · simp [re_smul, re_mul, omega_re, omega_im]
      · simp [im_smul, im_mul, omega_re, omega_im, smul_eq_mul]))
    (QuadraticAlgebra.algHom_ext (by
      simp only [AlgHom.comp_apply, AlgHom.id_apply]
      simp [toK, toK', lift, omega_re, omega_im, re_smul, im_smul, smul_add, smul_smul]))

/-- The isomorphism sends ω' to 2ω - 1. -/
lemma fieldIso_omega : fieldIso (ω : K') = 2 * (ω : Klocal) - 1 := by
  simp [fieldIso, toK, lift]

-- Provide the natural ℤ-algebra map from the integer quadratic algebra to the rational one.
def OK_to_K : QuadraticAlgebra ℤ (-2 : ℤ) 1 →ₐ[ℤ] Klocal :=
  QuadraticAlgebra.lift ⟨(ω : Klocal), by
    -- lift requires us to prove: u * u = a • 1 + b • u
    -- Here, a = -2:ℤ and b = 1:ℤ, so the goal is:
    -- ω * ω = (-2:ℤ) • 1 + (1:ℤ) • ω

    -- We use the real lemma which gives the relation over ℚ:
    -- ω * ω = (-2:ℚ) • 1 + (1:ℚ) • ω
    rw [omega_mul_omega_eq_add]
    -- push_cast handles converting the ℤ scalar multiplication (•)
    -- into the ℚ scalar multiplication expected by Klocal.
    push_cast
    rfl
    ⟩

-- Define the Algebra instance directly from this ℤ-algebra homomorphism
instance alg_int_K : Algebra (QuadraticAlgebra ℤ (-2 : ℤ) 1) Klocal :=
  OK_to_K.toAlgebra

-- The scalar tower now closes easily because the commutativity with ℤ
-- is baked into the definition of an AlgHom over ℤ.
instance hST : IsScalarTower ℤ (QuadraticAlgebra ℤ (-2 : ℤ) 1) Klocal :=
  IsScalarTower.of_algebraMap_eq fun r => (OK_to_K.commutes r).symm

/-- Every element of `QuadraticAlgebra ℤ a b` is generated by `ω` as a ℤ-algebra. -/
lemma quadraticAlgebra_adjoin_omega_eq_top (a b : ℤ) :
    Algebra.adjoin ℤ ({ω} : Set (QuadraticAlgebra ℤ a b)) = ⊤ := by
  rw [Algebra.eq_top_iff]
  intro x
  have hx : x = algebraMap ℤ _ x.re + x.im • ω := by
    apply QuadraticAlgebra.ext <;> simp
  rw [hx]
  exact Subalgebra.add_mem _
    (Subalgebra.algebraMap_mem _ _)
    (Subalgebra.smul_mem _ (Algebra.self_mem_adjoin_singleton ℤ ω) _)

/-- fieldIso sends (1+ω')/2 to ω. -/
private lemma fieldIso_half_omega_plus_one :
    fieldIso ((1 / 2 : ℚ) • ((ω : K') + 1)) = (ω : Klocal) := by
  rw [map_smul, map_add, fieldIso_omega, map_one]
  ext
  · simp [ omega_re, Algebra.smul_def]
  · simp [omega_im, Algebra.smul_def]

/-- `QuadraticAlgebra ℤ (-2) 1` is an integral closure of ℤ in K, via the algebra map
`OK_to_K` (sending ω ↦ ω). This is the transport of `ring_of_integers_neg7` along
`fieldIso : K' ≃ₐ[ℚ] K`.

The explicit hypothesis `h_omega` pins down the algebra map `algebraMap A K` by requiring
it sends ω to ω; at the call site (Helpers.lean), this is satisfied by `OK_to_K.toAlgebra`. -/
lemma isIntegralClosure_K
    [Algebra (QuadraticAlgebra ℤ (-2 : ℤ) 1) (QuadraticAlgebra ℚ (-2 : ℤ) 1)]
    [IsScalarTower ℤ (QuadraticAlgebra ℤ (-2 : ℤ) 1) (QuadraticAlgebra ℚ (-2 : ℤ) 1)]
    (h_omega : algebraMap (QuadraticAlgebra ℤ (-2 : ℤ) 1) (QuadraticAlgebra ℚ (-2 : ℤ) 1)
                 (ω : QuadraticAlgebra ℤ (-2 : ℤ) 1) = (ω : QuadraticAlgebra ℚ (-2 : ℤ) 1)) :
    IsIntegralClosure (QuadraticAlgebra ℤ (-2 : ℤ) 1) ℤ (QuadraticAlgebra ℚ (-2 : ℤ) 1) := by
  haveI hIC_K' : IsIntegralClosure (QuadraticAlgebra ℤ (-2 : ℤ) 1) ℤ K' := ring_of_integers_neg7
  -- Key: fieldIso commutes with the algebra maps from A
  have h_comm : ∀ y : QuadraticAlgebra ℤ (-2 : ℤ) 1,
      fieldIso (algebraMap (QuadraticAlgebra ℤ (-2 : ℤ) 1) K' y) =
      algebraMap (QuadraticAlgebra ℤ (-2 : ℤ) 1) Klocal y := by
    intro ⟨n, m⟩
    simp only [mk_eq_add_smul_omega, map_add, map_zsmul,
               algebraMap_omega_K', fieldIso_half_omega_plus_one, h_omega]
    congr 1
    simp only [← coe_algebraMap, ← IsScalarTower.algebraMap_apply ℤ _ K',
               ← IsScalarTower.algebraMap_apply ℤ _ Klocal]
    exact (fieldIso.restrictScalars ℤ).commutes n
  apply IsIntegralClosure.mk
  · -- algebraMap A Klocal is injective
    intro a b hab
    apply IsIntegralClosure.algebraMap_injective (QuadraticAlgebra ℤ (-2 : ℤ) 1) ℤ K'
    apply fieldIso.injective
    simp only [h_comm, hab]
  · -- isIntegral_iff for Klocal
    intro x
    constructor
    · intro hx
      -- Transport integrality from Klocal to K' via fieldIso.symm
      have hx' : IsIntegral ℤ (fieldIso.symm x) :=
        (isIntegral_algEquiv (fieldIso.restrictScalars ℤ).symm).mpr hx
      obtain ⟨y, hy⟩ := (IsIntegralClosure.isIntegral_iff (A := QuadraticAlgebra ℤ (-2 : ℤ) 1) (R := ℤ)).mp hx'
      exact ⟨y, by rw [← h_comm, hy, AlgEquiv.apply_symm_apply]⟩
    · rintro ⟨y, hy⟩
      rw [← hy, ← h_comm]
      exact (isIntegral_algEquiv (fieldIso.restrictScalars ℤ)).mpr
              (IsIntegralClosure.isIntegral_iff.mpr ⟨y, rfl⟩)

end
