/-
Copyright (c) 2026 Dmitrii Zakharov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dmitrii Zakharov
-/

import LeanPool.ErdosGinzburgZiv.EGZ.Convex.Homogenization
import LeanPool.ErdosGinzburgZiv.EGZ.Convex.LeastFaceInterior
import LeanPool.ErdosGinzburgZiv.EGZ.Convex.VertexWeights
import Mathlib.Data.Nat.Prime.Infinite

/-!
# Reduction of hollow polytopes modulo a prime

This module proves the geometric bridge used by the polynomial method.  For
every hollow rational polytope, a sufficiently large prime sees its vertices
as a `p`-hollow configuration.  The proof uses integral homogenization and
uniform saturation of the submodules generated by the vertices of every
face.
-/

open scoped BigOperators

namespace EGZ

namespace IntCoord

/-- Lift a coordinatewise zero reduction modulo `p` to divisibility by `p`
in the integral coordinate module. -/
theorem exists_smul_eq_of_mod_eq_zero {p d : ℕ} (x : IntCoord d)
    (h : x.mod p = 0) :
    ∃ z : IntCoord d, (p : ℤ) • z = x := by
  have hj (j : Fin d) : (p : ℤ) ∣ x j := by
    rw [← ZMod.intCast_zmod_eq_zero_iff_dvd]
    exact congrFun h j
  choose z hz using hj
  refine ⟨z, ?_⟩
  funext j
  simpa [smul_eq_mul] using (hz j).symm

end IntCoord

namespace RationalPolytope

/-- The vertices of every hollow rational polytope admit a `p`-hollow
reduction for some prime `p`. -/
theorem hasPrimeHollowReduction_of_isHollow {d : ℕ}
    (P : RationalPolytope d) (hP : P.IsHollow) :
    P.HasPrimeHollowReduction := by
  classical
  let H := P.vertexHomogenization
  obtain ⟨B, hB⟩ := H.exists_uniform_face_saturation_bound
  obtain ⟨p, hBp, hp⟩ := Nat.exists_infinite_primes (B + 1)
  have hBp' : B < p := by omega
  let _ : Fintype P.vertexSet := P.finite_vertexSet.fintype
  let e : Fin P.vertexSet.ncard ≃ P.vertexSet :=
    Fintype.equivOfCardEq (by
      rw [Fintype.card_fin, Set.fintypeCard_eq_ncard])
  let v : Fin P.vertexSet.ncard → FpVec p d := fun i ↦
    (H.scaledVertex (e i)).mod p
  refine ⟨p, hp, v, ?_⟩
  intro α hsum
  constructor
  · intro hzero
    let scaledSum : IntCoord d :=
      ∑ i, α i • H.scaledVertex (e i)
    have hscaledMod : scaledSum.mod p = 0 := by
      funext j
      have hj := congrFun hzero j
      simpa [scaledSum, v, IntCoord.mod, Finset.sum_apply] using hj
    obtain ⟨z, hz⟩ := IntCoord.exists_smul_eq_of_mod_eq_zero scaledSum hscaledMod
    let q : RealCoord d := (H.denominator : ℝ)⁻¹ • z.real
    have hDne : (H.denominator : ℝ) ≠ 0 := by
      exact_mod_cast (Nat.ne_of_gt H.denominator_pos)
    have hpne : (p : ℝ) ≠ 0 := by
      exact_mod_cast hp.ne_zero
    have hzreal : z.real = (H.denominator : ℝ) • q := by
      funext j
      simp only [q, IntCoord.real_apply, Pi.smul_apply, smul_eq_mul]
      field_simp
    let weight : Fin P.vertexSet.ncard → ℝ := fun i ↦ (α i : ℝ) / p
    have hweight0 : ∀ i, 0 ≤ weight i := by
      intro i
      exact div_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _)
    have hweightsum : (∑ i, weight i) = 1 := by
      dsimp [weight]
      simp only [div_eq_mul_inv]
      rw [← Finset.sum_mul]
      have hsumReal : (∑ i, (α i : ℝ)) = p := by exact_mod_cast hsum
      rw [hsumReal]
      exact div_self hpne
    have hbary : q = ∑ i, weight i • (e i : RealCoord d) := by
      funext j
      have hzj := congrFun hz j
      have hzjReal : (p : ℝ) * (z j : ℝ) =
          ∑ i, (α i : ℝ) * (H.scaledVertex (e i) j : ℝ) := by
        simpa [scaledSum, Finset.sum_apply, smul_eq_mul] using
          congrArg (· : ℤ → ℝ) hzj
      have hscaled (i : Fin P.vertexSet.ncard) :
          (H.scaledVertex (e i) j : ℝ) =
            (H.denominator : ℝ) * (e i : RealCoord d) j :=
        congrFun (H.scaledVertex_real (e i)) j
      simp_rw [hscaled] at hzjReal
      let S : ℝ := ∑ i, (α i : ℝ) * (e i : RealCoord d) j
      have hrel : (p : ℝ) * (z j : ℝ) =
          (H.denominator : ℝ) * S := by
        calc
          (p : ℝ) * (z j : ℝ) =
              ∑ i, (α i : ℝ) *
                ((H.denominator : ℝ) * (e i : RealCoord d) j) := hzjReal
          _ = (H.denominator : ℝ) * S := by
            rw [Finset.mul_sum]
            apply Finset.sum_congr rfl
            intro i _
            ring
      dsimp [q, weight]
      simp only [Pi.smul_apply, smul_eq_mul, Finset.sum_apply]
      change (H.denominator : ℝ)⁻¹ * (z j : ℝ) =
        ∑ i, ((α i : ℝ) / p) * (e i : RealCoord d) j
      calc
        (H.denominator : ℝ)⁻¹ * (z j : ℝ) =
            (z j : ℝ) / H.denominator := by
          rw [div_eq_mul_inv]
          ring
        _ = S / p := (div_eq_div_iff hDne hpne).2 (by
          simpa [mul_comm] using hrel)
        _ = ∑ i, ((α i : ℝ) / p) * (e i : RealCoord d) j := by
          dsimp [S]
          simp only [div_eq_mul_inv]
          rw [Finset.sum_mul]
          apply Finset.sum_congr rfl
          intro i _
          ring
    have hqP : q ∈ P.carrier := by
      rw [hbary]
      apply P.convex.sum_mem (t := Finset.univ) (w := weight)
        (z := fun i ↦ (e i : RealCoord d))
      · intro i _
        exact hweight0 i
      · simpa using hweightsum
      · intro i _
        exact extremePoints_subset (e i).property
    obtain ⟨F, hFleast⟩ :=
      RationalPolytope.Face.exists_isLeastFaceAt P hqP
    have hvertexF (i : Fin P.vertexSet.ncard) (hi : 0 < α i) :
        (e i : RealCoord d) ∈ F.carrier := by
      apply F.mem_of_pos_of_eq_convexCombination
        (fun j ↦ (e j : RealCoord d)) weight q (i := i)
      · intro j
        exact extremePoints_subset (e j).property
      · exact hweight0
      · exact hweightsum
      · exact hbary
      · exact hFleast.1
      · dsimp [weight]
        positivity
    have hsumSub :
        (∑ i, (α i : ℤ) • H.homogenizedVertex (e i)) ∈
          H.faceSubmodule F := by
      apply Submodule.sum_mem
      intro i _
      by_cases hi : α i = 0
      · simp [hi]
      · apply Submodule.smul_mem
        exact H.homogenizedVertex_mem_faceSubmodule F (e i)
          (hvertexF i (Nat.pos_of_ne_zero hi))
    have hhomogenized :
        (p : ℤ) • z.homogenize =
          ∑ i, (α i : ℤ) • H.homogenizedVertex (e i) := by
      funext j
      refine Fin.lastCases ?_ (fun k ↦ ?_) j
      · simp only [Pi.smul_apply, smul_eq_mul, IntCoord.homogenize_last,
          H.homogenizedVertex_last, mul_one, Finset.sum_apply]
        exact_mod_cast hsum.symm
      · have hzk := congrFun hz k
        simpa [scaledSum, Finset.sum_apply, smul_eq_mul] using hzk
    have hpsub : (p : ℤ) • z.homogenize ∈ H.faceSubmodule F := by
      rw [hhomogenized]
      exact hsumSub
    have hzsub : z.homogenize ∈ H.faceSubmodule F := hB hp hBp' F hpsub
    have hqspan : q ∈ affineIntSpan (P.vertexSet ∩ F.carrier) :=
      (H.homogenize_mem_faceSubmodule_iff F hzreal).mp hzsub
    have hqvertex : q ∈ P.vertexSet := by
      apply hP q hqP
      exact ⟨F, hFleast.mem_relInterior, hqspan⟩
    have heq_of_pos (i : Fin P.vertexSet.ncard) (hi : 0 < α i) :
        (e i : RealCoord d) = q := by
      apply RationalPolytope.eq_of_pos_of_eq_convexCombination_of_mem_vertexSet
        (P := P) (fun j ↦ (e j : RealCoord d)) weight q
      · intro j
        exact extremePoints_subset (e j).property
      · exact hweight0
      · exact hweightsum
      · exact hbary
      · exact hqvertex
      · dsimp [weight]
        positivity
    have hexpos : ∃ i, 0 < α i := by
      by_contra h
      push Not at h
      have hzeroCoeff : ∀ i, α i = 0 := by
        intro i
        exact Nat.eq_zero_of_le_zero (h i)
      have : (∑ i, α i) = 0 := by simp [hzeroCoeff]
      rw [hsum] at this
      exact hp.ne_zero this
    obtain ⟨i, hi⟩ := hexpos
    have hzeroOff : ∀ j, j ≠ i → α j = 0 := by
      intro j hji
      by_contra hj
      have heji : e j = e i := by
        apply Subtype.ext
        exact (heq_of_pos j (Nat.pos_of_ne_zero hj)).trans
          (heq_of_pos i hi).symm
      exact hji (e.injective heji)
    refine ⟨i, ?_⟩
    have hsingle : (∑ j, α j) = α i := by
      apply Finset.sum_eq_single i
      · intro j _ hji
        exact hzeroOff j hji
      · simp
    exact hsingle.symm.trans hsum
  · rintro ⟨i, hi⟩
    have hzeroOff : ∀ j, j ≠ i → α j = 0 := by
      intro j hji
      have hsumErase : ∑ k ∈ (Finset.univ.erase i), α k = 0 := by
        have hdecomp := Finset.sum_erase_add (s := Finset.univ)
          (f := α) (Finset.mem_univ i)
        rw [hsum, hi] at hdecomp
        omega
      exact Finset.sum_eq_zero_iff.mp hsumErase j (by simp [hji])
    rw [Finset.sum_eq_single i]
    · rw [hi]
      exact FpVec.characteristic_nsmul p (v i)
    · intro j _ hji
      simp [hzeroOff j hji]
    · simp

end RationalPolytope

/-- The unconditional dimensionwise reduction bridge from hollow rational
polytopes to prime-field `p`-hollow configurations. -/
theorem hollowReductionBridge (d : ℕ) : HollowReductionBridge d := by
  intro P hP
  exact P.hasPrimeHollowReduction_of_isHollow hP

end EGZ
