/-
Copyright (c) 2026 Dmitrii Zakharov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dmitrii Zakharov
-/
module


public import LeanPool.ErdosGinzburgZiv.EGZ.Convex.HollowBound

/-!
# Integral homogenization of rational polytope vertices

This module chooses one common denominator for the vertices of a rational
polytope, embeds the resulting integral coordinates into one higher dimension
with final coordinate `1`, and forms the integer submodule generated by the
vertices on each face.  The final coordinate turns linear combinations in the
homogenized module into affine combinations in the original polytope.
-/

@[expose] public section

open scoped BigOperators

namespace EGZ

namespace IntCoord

/-- Add a final affine coordinate equal to one. -/
def homogenize {d : ℕ} (z : IntCoord d) : IntCoord (d + 1) :=
  Fin.lastCases 1 z

@[simp]
theorem homogenize_last {d : ℕ} (z : IntCoord d) :
    z.homogenize (Fin.last d) = 1 := by
  simp [homogenize]

@[simp]
theorem homogenize_castSucc {d : ℕ} (z : IntCoord d) (i : Fin d) :
    z.homogenize i.castSucc = z i := by
  simp [homogenize]

end IntCoord

namespace RationalPolytope

/-- A simultaneous choice of integral scaled coordinates for all vertices of
`P`.  Positivity of `denominator` is recorded so that scaling can be
cancelled over the reals. -/
structure VertexHomogenization {d : ℕ} (P : RationalPolytope d) where
  /-- Common positive denominator used to scale the rational vertices. -/
  denominator : ℕ
  denominator_pos : 0 < denominator
  /-- Integer coordinates of the vertices after scaling by the common denominator. -/
  scaledVertex : P.vertexSet → IntCoord d
  scaledVertex_real : ∀ q,
    (scaledVertex q).real = (denominator : ℝ) • (q : RealCoord d)

/-- The canonical common-denominator choice supplied by finiteness and
rationality of the vertex set. -/
noncomputable def vertexHomogenization {d : ℕ} (P : RationalPolytope d) :
    VertexHomogenization P := by
  classical
  let hcommon :=
    Set.Finite.exists_common_integral_nsmul P.finite_vertexSet
      (fun q hq ↦ P.rational_of_mem_vertexSet hq)
  let D := Classical.choose hcommon
  have hD : 0 < D := (Classical.choose_spec hcommon).1
  have hIntegral : ∀ q ∈ P.vertexSet, IsIntegral ((D : ℝ) • q) :=
    (Classical.choose_spec hcommon).2
  refine ⟨D, hD, fun q ↦ Classical.choose (hIntegral q q.property), ?_⟩
  intro q
  exact Classical.choose_spec (hIntegral q q.property)

namespace VertexHomogenization

/-- Homogenized integral coordinate of a vertex. -/
def homogenizedVertex {d : ℕ} {P : RationalPolytope d}
    (H : VertexHomogenization P) (q : P.vertexSet) : IntCoord (d + 1) :=
  (H.scaledVertex q).homogenize

@[simp]
theorem homogenizedVertex_last {d : ℕ} {P : RationalPolytope d}
    (H : VertexHomogenization P) (q : P.vertexSet) :
    H.homogenizedVertex q (Fin.last d) = 1 := by
  simp [homogenizedVertex]

@[simp]
theorem homogenizedVertex_castSucc {d : ℕ} {P : RationalPolytope d}
    (H : VertexHomogenization P) (q : P.vertexSet) (i : Fin d) :
    H.homogenizedVertex q i.castSucc = H.scaledVertex q i := by
  simp [homogenizedVertex]

/-- Homogenized vertices lying on a face. -/
def faceHomogenizedSet {d : ℕ} {P : RationalPolytope d}
    (H : VertexHomogenization P) (F : P.Face) : Set (IntCoord (d + 1)) :=
  Set.range (fun q : {q : RealCoord d // q ∈ P.vertexSet ∩ F.carrier} ↦
    H.homogenizedVertex ⟨q.1, q.2.1⟩)

/-- The integer submodule generated by homogenized vertices on a face. -/
def faceSubmodule {d : ℕ} {P : RationalPolytope d}
    (H : VertexHomogenization P) (F : P.Face) :
    Submodule ℤ (IntCoord (d + 1)) :=
  Submodule.span ℤ (H.faceHomogenizedSet F)

/-- A vertex lying on `F` is one of the generators of the face submodule. -/
theorem homogenizedVertex_mem_faceSubmodule {d : ℕ}
    {P : RationalPolytope d} (H : VertexHomogenization P) (F : P.Face)
    (q : P.vertexSet) (hqF : (q : RealCoord d) ∈ F.carrier) :
    H.homogenizedVertex q ∈ H.faceSubmodule F := by
  apply Submodule.subset_span
  exact ⟨⟨q, q.property, hqF⟩, rfl⟩

/-- Membership of an integral point with final coordinate `1` in the
homogenized face submodule is equivalent to affine-integer-span membership of
the corresponding real point. -/
theorem homogenize_mem_faceSubmodule_iff {d : ℕ} {P : RationalPolytope d}
    (H : VertexHomogenization P) (F : P.Face)
    {q : RealCoord d} {z : IntCoord d}
    (hz : z.real = (H.denominator : ℝ) • q) :
    z.homogenize ∈ H.faceSubmodule F ↔
      q ∈ affineIntSpan (P.vertexSet ∩ F.carrier) := by
  classical
  constructor
  · intro hmem
    obtain ⟨k, coeff, gen, hgen⟩ :=
      Submodule.mem_span_set'.mp hmem
    choose points hpoints using fun i ↦ (gen i).property
    refine ⟨k, fun i ↦ (points i : RealCoord d), coeff,
      fun i ↦ (points i).property, ?_, ?_⟩
    · have hlast := congrFun hgen (Fin.last d)
      simp_rw [← hpoints] at hlast
      simpa [homogenizedVertex] using hlast
    · funext j
      simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul]
      have hcoord := congrFun hgen j.castSucc
      simp_rw [← hpoints] at hcoord
      have hscaled (i : Fin k) :
          ((H.scaledVertex ⟨(points i).1, (points i).2.1⟩ j : ℤ) : ℝ) =
            (H.denominator : ℝ) * (points i).1 j := by
        exact congrFun (H.scaledVertex_real
          ⟨(points i).1, (points i).2.1⟩) j
      have hzj := congrFun hz j
      simp only [IntCoord.real_apply, Pi.smul_apply, smul_eq_mul] at hzj
      simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul,
        homogenizedVertex, IntCoord.homogenize_castSucc] at hcoord
      have hcoordReal :
          ∑ i, (coeff i : ℝ) *
              ((H.scaledVertex ⟨(points i).1, (points i).2.1⟩ j : ℤ) : ℝ) =
            (z j : ℝ) := by
        exact_mod_cast hcoord
      rw [hzj] at hcoordReal
      simp_rw [hscaled] at hcoordReal
      have hDne : (H.denominator : ℝ) ≠ 0 := by
        exact_mod_cast (Nat.ne_of_gt H.denominator_pos)
      apply (mul_left_cancel₀ hDne)
      rw [Finset.mul_sum]
      calc
        (H.denominator : ℝ) * q j =
            ∑ i, (coeff i : ℝ) *
              ((H.denominator : ℝ) * (points i).1 j) := hcoordReal.symm
        _ = ∑ i, (H.denominator : ℝ) *
            ((coeff i : ℝ) * (points i).1 j) := by
          apply Finset.sum_congr rfl
          intro i _
          ring
  · rintro ⟨k, points, coeff, hpoints, hsum, hq⟩
    rw [faceSubmodule, Submodule.mem_span_set']
    let facePoint (i : Fin k) :
        {q : RealCoord d // q ∈ P.vertexSet ∩ F.carrier} :=
      ⟨points i, hpoints i⟩
    let gen (i : Fin k) : H.faceHomogenizedSet F :=
      ⟨H.homogenizedVertex ⟨points i, (hpoints i).1⟩,
        ⟨facePoint i, rfl⟩⟩
    refine ⟨k, coeff, gen, ?_⟩
    funext j
    refine Fin.lastCases ?_ (fun l ↦ ?_) j
    · simpa [gen, homogenizedVertex] using hsum
    · have hzj := congrFun hz l
      have hqj := congrFun hq l
      have hscaled (i : Fin k) := congrFun
        (H.scaledVertex_real ⟨points i, (hpoints i).1⟩) l
      simp only [IntCoord.real_apply, Pi.smul_apply, smul_eq_mul] at hzj hscaled
      simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul] at hqj
      apply (Int.cast_injective : Function.Injective ((↑) : ℤ → ℝ))
      simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, gen,
        homogenizedVertex, IntCoord.homogenize_castSucc]
      push_cast
      simp_rw [hscaled]
      rw [hzj, hqj, Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro i _
      ring

/-- A single threshold makes every face submodule `p`-saturated. -/
theorem exists_uniform_face_saturation_bound {d : ℕ}
    {P : RationalPolytope d} (H : VertexHomogenization P) :
    ∃ B : ℕ, ∀ {p : ℕ}, p.Prime → B < p →
      ∀ F : P.Face, ∀ {x : IntCoord (d + 1)},
        (p : ℤ) • x ∈ H.faceSubmodule F → x ∈ H.faceSubmodule F := by
  classical
  obtain ⟨B, hB⟩ := Submodule.exists_uniform_prime_saturation_bound
    (Pi.basisFun ℤ (Fin (d + 1))) (Finset.univ : Finset P.Face) H.faceSubmodule
  exact ⟨B, fun hp hBp F ↦ hB hp hBp F (Finset.mem_univ F)⟩

end VertexHomogenization

end RationalPolytope

end EGZ
