/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, Claude Opus 5
-/
module

public import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Commute
public import Mathlib.Analysis.SpecialFunctions.ContinuousFunctionalCalculus.Rpow.Basic

/-!
# Commutation descends from the square of a nonnegative element

If `a` is nonnegative then `a` is `CFC.sqrt (a * a)`, and `CFC.sqrt` is a limit of
polynomials in its argument, so anything commuting with `a * a` already commutes with `a`:

```text
0 ≤ a → Commute (a * a) b → Commute a b
```

This is the "pass to the square root through the functional calculus" step of a classical
argument that otherwise gets rewritten by hand at each use: one shows `f(a²) b = b f(a²)`
for polynomials `f`, extends to continuous `f` by Stone--Weierstrass, and then takes
`f = √`.  Mathlib supplies both halves — `Commute.cfcₙ_nnreal` for the extension and
`CFC.sqrt_mul_self` for the evaluation — but not the composite.

The converse `Commute a b → Commute (a * a) b` is `Commute.mul_left`, needs no hypothesis
on `a`, and is not restated here.

## Two positive elements

The two-sided form used in practice — `a² x = x c²` with `0 ≤ a`, `0 ≤ c` and `x` an
intertwiner between two *different* spaces — reduces to this one whenever the two spaces are
orthogonal summands of a common space: take `a ⊕ c` on the sum, which is nonnegative, and
observe that its square commutes with the off-diagonal block `x` exactly when `a² x = x c²`.
Davis--Kahan's Proposition 3.1 is proved that way in
`DavisKahan/Geometry/Polar/DirectRotationSquare.lean`, so no rectangular functional-calculus
intertwiner is needed.

## Provenance

* Original repository: Davis--Kahan/DKPS formalization (Kitware, Inc.).
* Original module: authored here, for the third clause of Davis--Kahan (1970),
  Proposition 3.1 ("the direct rotation is characterized by property (i) alone"), whose
  printed proof is exactly this step at `f = √`.
* Extraction class: **authored in place**, for Tau Ceti.
* Proposed Mathlib destination:
  `Mathlib/Analysis/SpecialFunctions/ContinuousFunctionalCalculus/Rpow/Basic.lean`,
  beside `CFC.sqrt_mul_self`.
* Spectra influence: **none** — imports only Mathlib.
-/

public section

namespace TauCeti

section NonUnital

variable {A : Type*} [PartialOrder A] [NonUnitalRing A] [TopologicalSpace A] [StarRing A]
  [Module ℝ A] [SMulCommClass ℝ A A] [IsScalarTower ℝ A A] [StarOrderedRing A]
  [NonUnitalContinuousFunctionalCalculus ℝ A IsSelfAdjoint] [NonnegSpectrumClass ℝ A]
  [IsTopologicalRing A] [T2Space A]

/-- **What commutes with the square of a nonnegative element commutes with the element.**

`a` is the unique nonnegative square root of `a * a`, and the functional calculus builds it
inside the closed subalgebra generated by `a * a`, so `b` cannot tell the two apart. -/
theorem commute_of_commute_mul_self {a b : A} (ha : 0 ≤ a) (h : Commute (a * a) b) :
    Commute a b := by
  have hsqrt : Commute (CFC.sqrt (a * a)) b := Commute.cfcₙ_nnreal h _
  rwa [CFC.sqrt_mul_self a ha] at hsqrt

end NonUnital

end TauCeti
