/-
Copyright (c) 2026 Shengtong Zhang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Shengtong Zhang
-/
module


public import Mathlib.RingTheory.MvPolynomial.Ideal
public import LeanPool.Nikodym.Nikodym.LowerBound.PolynomialSpaces

/-!
# Point ideals and finite jet quotients

This file implements blueprint node **F03** of the lower-bound side of the sharp finite-field
Nikodym exponent.

For a point `x : Fin d → K` we define

* `Nikodym.LowerBound.pointIdeal x`: the maximal ideal `𝔪ₓ = ker (eval x)` of
  `P_d = MvPolynomial (Fin d) K`, with `pointIdeal_eq_span : 𝔪ₓ = (X i - C (x i))_i`;
* `Nikodym.LowerBound.translate x`: the translation automorphism `X i ↦ X i - C (x i)` of `P_d`,
  which carries the ideal `𝔪₀ = MvPolynomial.idealOfVars (Fin d) K` of the origin onto `𝔪ₓ`;
* `Nikodym.LowerBound.jetIdeal I x r = I ⊔ 𝔪ₓ ^ r`, the jet space
  `Nikodym.LowerBound.JetSpace I x r = P_d ⧸ (I ⊔ 𝔪ₓ ^ r)` (written `Q_{I,x}(r)` in the blueprint)
  and its dimension `Nikodym.LowerBound.jetDim I x r = dim_K Q_{I,x}(r)`.

The main results are

* `instModuleFiniteJetSpace`: every jet space is finite-dimensional;
* `finrank_quotient_pointIdeal_pow` / `jetDim_bot`:
  `dim_K (P_d ⧸ 𝔪ₓ ^ r) = (r - 1 + d).choose d` for `r ≥ 1`, and the equivalent
  `jetDim_pointIdeal_pow : jetDim ⊥ x r = (r + d - 1).choose d`;
* `jetSpace_subsingleton_of_not_le` / `jetDim_eq_zero_of_not_le`: if `I ⊄ 𝔪ₓ` then
  `Q_{I,x}(r) = 0`.

No localizations appear: everything is phrased with global quotients of `P_d`.
-/

@[expose] public section

namespace Nikodym.LowerBound

open MvPolynomial

variable {K : Type*} [Field K] {d : ℕ}

/-! ### Point ideals -/

section PointIdeal

/-- Blueprint F03: the point ideal `𝔪ₓ = ker (ev_x)` of a point `x : Fin d → K`. -/
noncomputable def pointIdeal (x : Fin d → K) : Ideal (MvPolynomial (Fin d) K) :=
  RingHom.ker (eval x)

variable {x : Fin d → K}

/-- Blueprint F03: `f ∈ 𝔪ₓ` iff `f(x) = 0`. -/
theorem mem_pointIdeal {f : MvPolynomial (Fin d) K} : f ∈ pointIdeal x ↔ eval x f = 0 :=
  RingHom.mem_ker

/-- Blueprint F03: evaluation at a point is surjective onto `K`. -/
theorem eval_surjective (x : Fin d → K) : Function.Surjective (eval x) := fun a ↦
  ⟨C a, eval_C a⟩

/-- Blueprint F03: `𝔪ₓ` is a maximal ideal. -/
theorem pointIdeal_isMaximal (x : Fin d → K) : (pointIdeal x).IsMaximal :=
  RingHom.ker_isMaximal_of_surjective _ (eval_surjective x)

/-- Blueprint F03: `𝔪ₓ` is a proper ideal. -/
theorem pointIdeal_ne_top (x : Fin d → K) : pointIdeal x ≠ ⊤ :=
  (pointIdeal_isMaximal x).ne_top

/-- Blueprint F03: `𝔪ₓ` is a prime ideal. -/
theorem pointIdeal_isPrime (x : Fin d → K) : (pointIdeal x).IsPrime :=
  (pointIdeal_isMaximal x).isPrime

/-- Blueprint F03: the linear forms `X i - x i` lie in `𝔪ₓ`. -/
theorem X_sub_C_mem_pointIdeal (x : Fin d → K) (i : Fin d) :
    (X i - C (x i) : MvPolynomial (Fin d) K) ∈ pointIdeal x := by
  simp [mem_pointIdeal]

/-- Blueprint F03: the ideal generated by the linear forms `X i - x i` is contained in `𝔪ₓ`. -/
theorem span_le_pointIdeal (x : Fin d → K) :
    Ideal.span (Set.range fun i ↦ (X i - C (x i) : MvPolynomial (Fin d) K)) ≤ pointIdeal x := by
  rw [Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  exact X_sub_C_mem_pointIdeal x i

/-- Blueprint F03: the point ideal of the origin is `MvPolynomial.idealOfVars`, the ideal
generated by the variables. -/
theorem pointIdeal_zero : pointIdeal (0 : Fin d → K) = idealOfVars (Fin d) K := by
  ext f
  rw [mem_pointIdeal, eval_zero, ← pow_one (idealOfVars (Fin d) K), mem_pow_idealOfVars_iff',
    constantCoeff_eq]
  constructor
  · intro h α hα
    rw [Nat.lt_one_iff, Finsupp.degree_eq_zero_iff] at hα
    subst hα
    exact h
  · intro h
    exact h 0 (by simp)

/-- The ideal of the origin `𝔪 = idealOfVars (Fin d) K` is maximal. -/
theorem idealOfVars_isMaximal : (idealOfVars (Fin d) K).IsMaximal :=
  pointIdeal_zero (K := K) (d := d) ▸ pointIdeal_isMaximal 0

/-- The ideal of the origin is proper. -/
theorem idealOfVars_ne_top : idealOfVars (Fin d) K ≠ ⊤ :=
  idealOfVars_isMaximal.ne_top

end PointIdeal

/-! ### Translation to the origin -/

section Translate

/-- Blueprint F03: the translation automorphism `τₓ : X i ↦ X i - x i` of `P_d`. It satisfies
`ev_x ∘ τₓ = ev_0` and carries `𝔪₀` onto `𝔪ₓ`. -/
noncomputable def translate (x : Fin d → K) :
    MvPolynomial (Fin d) K ≃ₐ[K] MvPolynomial (Fin d) K :=
  AlgEquiv.ofAlgHom (aeval fun i ↦ X i - C (x i)) (aeval fun i ↦ X i + C (x i))
    (by ext i; simp [algebraMap_eq]) (by ext i; simp [algebraMap_eq])

variable (x : Fin d → K)

/-- Blueprint F03: `τₓ f = f(X - x)`, i.e. `τₓ = aeval (X i - x i)`. -/
theorem translate_apply (f : MvPolynomial (Fin d) K) :
    translate x f = aeval (fun i ↦ X i - C (x i)) f :=
  rfl

/-- Blueprint F03: `τₓ⁻¹ = aeval (X i + x i)`. -/
theorem translate_symm_apply (f : MvPolynomial (Fin d) K) :
    (translate x).symm f = aeval (fun i ↦ X i + C (x i)) f :=
  rfl

@[simp]
theorem translate_X (i : Fin d) : translate x (X i) = X i - C (x i) :=
  aeval_X _ i

@[simp]
theorem translate_symm_X (i : Fin d) : (translate x).symm (X i) = X i + C (x i) :=
  aeval_X _ i

@[simp]
theorem translate_C (a : K) : translate x (C a) = C a := by
  rw [translate_apply, aeval_C, algebraMap_eq]

@[simp]
theorem translate_symm_C (a : K) : (translate x).symm (C a) = C a := by
  rw [translate_symm_apply, aeval_C, algebraMap_eq]

/-- Blueprint F03: `ev_0 ∘ τₓ⁻¹ = ev_x`. -/
theorem eval_zero_comp_translate_symm :
    (eval (0 : Fin d → K)).comp ((translate x).symm : MvPolynomial (Fin d) K →+* _) = eval x := by
  apply ringHom_ext
  · intro a
    simp
  · intro i
    simp

/-- Blueprint F03: `ev_0 (τₓ⁻¹ f) = ev_x f`. -/
theorem eval_zero_translate_symm (f : MvPolynomial (Fin d) K) :
    eval (0 : Fin d → K) ((translate x).symm f) = eval x f :=
  RingHom.congr_fun (eval_zero_comp_translate_symm x) f

/-- Blueprint F03: `ev_x (τₓ f) = ev_0 f`. -/
theorem eval_translate (f : MvPolynomial (Fin d) K) :
    eval x (translate x f) = eval (0 : Fin d → K) f := by
  rw [← eval_zero_translate_symm x, AlgEquiv.symm_apply_apply]

/-- Blueprint F03: `𝔪ₓ = τₓ(𝔪₀)`. -/
theorem pointIdeal_eq_map :
    pointIdeal x = (idealOfVars (Fin d) K).map
      (translate x : MvPolynomial (Fin d) K →+* MvPolynomial (Fin d) K) := by
  ext f
  rw [Ideal.mem_map_iff_of_surjective
    (translate x : MvPolynomial (Fin d) K →+* MvPolynomial (Fin d) K) (translate x).surjective,
    ← pointIdeal_zero]
  constructor
  · intro hf
    refine ⟨(translate x).symm f, ?_, (translate x).apply_symm_apply f⟩
    rw [mem_pointIdeal] at hf ⊢
    rw [eval_zero_translate_symm]
    exact hf
  · rintro ⟨g, hg, rfl⟩
    rw [mem_pointIdeal] at hg ⊢
    rw [RingHom.coe_coe, eval_translate]
    exact hg

/-- Blueprint F03: `𝔪ₓ ^ r = τₓ(𝔪₀ ^ r)`. -/
theorem pointIdeal_pow_eq_map (r : ℕ) :
    pointIdeal x ^ r = (idealOfVars (Fin d) K ^ r).map
      (translate x : MvPolynomial (Fin d) K →+* MvPolynomial (Fin d) K) := by
  rw [Ideal.map_pow, pointIdeal_eq_map]

/-- Blueprint F03: `𝔪ₓ` is generated by the linear forms `X i - x i`. -/
theorem pointIdeal_eq_span :
    pointIdeal x = Ideal.span (Set.range fun i ↦ (X i - C (x i) : MvPolynomial (Fin d) K)) := by
  rw [pointIdeal_eq_map, idealOfVars, Ideal.map_span, ← Set.range_comp]
  congr 2
  funext i
  simp

/-- Blueprint F03: for any ideal `I`, `I ⊔ 𝔪ₓ ^ r = τₓ(τₓ⁻¹(I) ⊔ 𝔪₀ ^ r)`. -/
theorem sup_pointIdeal_pow_eq_map (I : Ideal (MvPolynomial (Fin d) K)) (r : ℕ) :
    I ⊔ pointIdeal x ^ r =
      (I.comap (translate x : MvPolynomial (Fin d) K →+* MvPolynomial (Fin d) K) ⊔
        idealOfVars (Fin d) K ^ r).map
          (translate x : MvPolynomial (Fin d) K →+* MvPolynomial (Fin d) K) := by
  rw [Ideal.map_sup, Ideal.map_comap_of_surjective
    (translate x : MvPolynomial (Fin d) K →+* MvPolynomial (Fin d) K) (translate x).surjective,
    pointIdeal_pow_eq_map]

end Translate

/-! ### Quotients by powers of the ideal of the origin -/

section Origin

/-- Blueprint F03: if `𝔪₀ ^ r ≤ J`, then `P_d ⧸ J` is spanned by the classes of the polynomials of
total degree at most `r - 1`. -/
theorem map_restrictTotalDegree_eq_top_of_pow_idealOfVars_le {J : Ideal (MvPolynomial (Fin d) K)}
    {r : ℕ} (hJ : idealOfVars (Fin d) K ^ r ≤ J) :
    (restrictTotalDegree (Fin d) K (r - 1)).map (Ideal.Quotient.mkₐ K J).toLinearMap = ⊤ := by
  classical
  rw [eq_top_iff]
  rintro v -
  obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective v
  induction f using MvPolynomial.induction_on' with
  | monomial α a =>
    by_cases hα : α.degree ≤ r - 1
    · exact Submodule.mem_map_of_mem (monomial_mem_restrictTotalDegree hα a)
    · have hmem : monomial α a ∈ J := by
        refine hJ ((mem_pow_idealOfVars_iff _ _).mpr fun β hβ ↦ ?_)
        rw [support_monomial] at hβ
        split_ifs at hβ
        · simp at hβ
        · rw [Finset.mem_singleton] at hβ
          subst hβ
          omega
      rw [Ideal.Quotient.eq_zero_iff_mem.mpr hmem]
      exact Submodule.zero_mem _
  | add p q hp hq =>
    rw [map_add]
    exact Submodule.add_mem _ hp hq

/-- Blueprint F03: if `𝔪₀ ^ r ≤ J`, then `P_d ⧸ J` is finite-dimensional. -/
theorem finite_quotient_of_pow_idealOfVars_le {J : Ideal (MvPolynomial (Fin d) K)} {r : ℕ}
    (hJ : idealOfVars (Fin d) K ^ r ≤ J) : Module.Finite K (MvPolynomial (Fin d) K ⧸ J) := by
  refine Module.Finite.of_surjective
    ((Ideal.Quotient.mkₐ K J).toLinearMap ∘ₗ (restrictTotalDegree (Fin d) K (r - 1)).subtype) ?_
  rw [← LinearMap.range_eq_top, LinearMap.range_comp, Submodule.range_subtype]
  exact map_restrictTotalDegree_eq_top_of_pow_idealOfVars_le hJ

/-- Blueprint F03: for `r ≥ 1`, the monomials of degree `< r` form a basis of `P_d ⧸ 𝔪₀ ^ r`, so
`dim_K (P_d ⧸ 𝔪₀ ^ r) = (r - 1 + d).choose d`. -/
theorem finrank_quotient_pow_idealOfVars {r : ℕ} (hr : 1 ≤ r) :
    Module.finrank K (MvPolynomial (Fin d) K ⧸ idealOfVars (Fin d) K ^ r) =
      (r - 1 + d).choose d := by
  set φ := (Ideal.Quotient.mkₐ K (idealOfVars (Fin d) K ^ r)).toLinearMap ∘ₗ
    (restrictTotalDegree (Fin d) K (r - 1)).subtype with hφ
  have hsurj : Function.Surjective φ := by
    rw [← LinearMap.range_eq_top, hφ, LinearMap.range_comp, Submodule.range_subtype]
    exact map_restrictTotalDegree_eq_top_of_pow_idealOfVars_le le_rfl
  have hinj : Function.Injective φ := by
    intro f g hfg
    have h1 : (f : MvPolynomial (Fin d) K) - g ∈ idealOfVars (Fin d) K ^ r :=
      Ideal.Quotient.eq.mp hfg
    have h2 : (f : MvPolynomial (Fin d) K) - g ∈ restrictTotalDegree (Fin d) K (r - 1) :=
      Submodule.sub_mem _ f.2 g.2
    rw [mem_pow_idealOfVars_iff] at h1
    rw [mem_restrictTotalDegree_iff_forall_support] at h2
    have h3 : ((f : MvPolynomial (Fin d) K) - g).support = ∅ := by
      rw [Finset.eq_empty_iff_forall_notMem]
      intro α hα
      have := h1 α hα
      have := h2 α hα
      omega
    exact Subtype.ext (sub_eq_zero.mp (support_eq_empty.mp h3))
  rw [← (LinearEquiv.ofBijective φ ⟨hinj, hsurj⟩).finrank_eq, finrank_restrictTotalDegree]

end Origin

/-! ### Jet ideals and jet spaces -/

section Jets

variable (I : Ideal (MvPolynomial (Fin d) K)) (x : Fin d → K) (r : ℕ)

/-- Blueprint F03: the jet ideal `I + 𝔪ₓ ^ r` (ideal supremum). -/
noncomputable def jetIdeal : Ideal (MvPolynomial (Fin d) K) :=
  I ⊔ pointIdeal x ^ r

/-- Blueprint F03: the jet space `Q_{I,x}(r) = P_d ⧸ (I + 𝔪ₓ ^ r)`. -/
abbrev JetSpace : Type _ :=
  MvPolynomial (Fin d) K ⧸ jetIdeal I x r

/-- Blueprint F03: the jet dimension `j_{I,x}(r) = dim_K Q_{I,x}(r)`. -/
noncomputable def jetDim : ℕ :=
  Module.finrank K (JetSpace I x r)

theorem le_jetIdeal_left : I ≤ jetIdeal I x r := le_sup_left

theorem pointIdeal_pow_le_jetIdeal : pointIdeal x ^ r ≤ jetIdeal I x r := le_sup_right

/-- Blueprint F03: the jet ideal of the zero ideal is `𝔪ₓ ^ r`. -/
theorem jetIdeal_bot : jetIdeal (⊥ : Ideal (MvPolynomial (Fin d) K)) x r = pointIdeal x ^ r :=
  bot_sup_eq _

/-- Blueprint F03: translation identifies `Q_{I,x}(r)` with the jet space at the origin of the
translated ideal `τₓ⁻¹(I)`. -/
noncomputable def jetSpaceEquivOrigin :
    (MvPolynomial (Fin d) K ⧸
      (I.comap (translate x : MvPolynomial (Fin d) K →+* MvPolynomial (Fin d) K) ⊔
        idealOfVars (Fin d) K ^ r)) ≃ₐ[K] JetSpace I x r :=
  Ideal.quotientEquivAlg _ _ (translate x) (sup_pointIdeal_pow_eq_map x I r)

/-- Blueprint F03: jet spaces are finite-dimensional. -/
instance instModuleFiniteJetSpace : Module.Finite K (JetSpace I x r) :=
  haveI := finite_quotient_of_pow_idealOfVars_le (K := K) (d := d)
    (J := I.comap (translate x : MvPolynomial (Fin d) K →+* MvPolynomial (Fin d) K) ⊔
      idealOfVars (Fin d) K ^ r) (r := r) le_sup_right
  Module.Finite.equiv (jetSpaceEquivOrigin I x r).toLinearEquiv

/-- Blueprint F03: `P_d ⧸ 𝔪ₓ ^ r` is finite-dimensional. -/
instance instModuleFiniteQuotientPointIdealPow :
    Module.Finite K (MvPolynomial (Fin d) K ⧸ pointIdeal x ^ r) :=
  Module.Finite.equiv (Ideal.quotientEquivAlgOfEq K (jetIdeal_bot x r)).toLinearEquiv

/-- Blueprint F03: for `r ≥ 1`, `dim_K (P_d ⧸ 𝔪ₓ ^ r) = (r - 1 + d).choose d`: translation to the
origin identifies `P_d ⧸ 𝔪ₓ ^ r` with the span of the monomials of degree `< r`. -/
theorem finrank_quotient_pointIdeal_pow {r : ℕ} (hr : 1 ≤ r) :
    Module.finrank K (MvPolynomial (Fin d) K ⧸ pointIdeal x ^ r) = (r - 1 + d).choose d := by
  rw [← finrank_quotient_pow_idealOfVars (K := K) (d := d) hr]
  exact (Ideal.quotientEquivAlg _ _ (translate x)
    (pointIdeal_pow_eq_map x r)).toLinearEquiv.finrank_eq.symm

/-- Blueprint F03: `j_{(0),x}(r) = (r - 1 + d).choose d` for `r ≥ 1`. -/
theorem jetDim_bot {r : ℕ} (hr : 1 ≤ r) :
    jetDim (⊥ : Ideal (MvPolynomial (Fin d) K)) x r = (r - 1 + d).choose d := by
  rw [jetDim, ← finrank_quotient_pointIdeal_pow x hr]
  exact (Ideal.quotientEquivAlgOfEq K (jetIdeal_bot x r)).toLinearEquiv.finrank_eq

/-- Blueprint F03: `j_{(0),x}(r) = (r + d - 1).choose d` for `r ≥ 1`. -/
theorem jetDim_pointIdeal_pow {r : ℕ} (hr : 1 ≤ r) :
    jetDim (⊥ : Ideal (MvPolynomial (Fin d) K)) x r = (r + d - 1).choose d := by
  rw [jetDim_bot x hr]
  congr 2
  omega

/-- Blueprint F03: if `I ⊄ 𝔪ₓ`, then `I + 𝔪ₓ = P_d`. -/
theorem sup_pointIdeal_eq_top_of_not_le {I : Ideal (MvPolynomial (Fin d) K)} {x : Fin d → K}
    (h : ¬ I ≤ pointIdeal x) : I ⊔ pointIdeal x = ⊤ := by
  by_contra hne
  have heq : pointIdeal x = I ⊔ pointIdeal x :=
    (pointIdeal_isMaximal x).eq_of_le hne le_sup_right
  exact h (heq ▸ le_sup_left)

/-- Blueprint F03: if `I ⊄ 𝔪ₓ`, then `I + 𝔪ₓ ^ r = P_d` for every `r`. -/
theorem jetIdeal_eq_top_of_not_le {I : Ideal (MvPolynomial (Fin d) K)} {x : Fin d → K}
    (h : ¬ I ≤ pointIdeal x) (r : ℕ) : jetIdeal I x r = ⊤ :=
  Ideal.sup_pow_eq_top' (sup_pointIdeal_eq_top_of_not_le h)

/-- Blueprint F03: if `I ⊄ 𝔪ₓ`, then the jet space `Q_{I,x}(r)` is zero. -/
theorem jetSpace_subsingleton_of_not_le {I : Ideal (MvPolynomial (Fin d) K)} {x : Fin d → K}
    (h : ¬ I ≤ pointIdeal x) (r : ℕ) : Subsingleton (JetSpace I x r) :=
  Ideal.Quotient.subsingleton_iff.mpr (jetIdeal_eq_top_of_not_le h r)

/-- Blueprint F03: if `I ⊄ 𝔪ₓ`, then `j_{I,x}(r) = 0`. -/
theorem jetDim_eq_zero_of_not_le {I : Ideal (MvPolynomial (Fin d) K)} {x : Fin d → K}
    (h : ¬ I ≤ pointIdeal x) (r : ℕ) : jetDim I x r = 0 :=
  haveI := jetSpace_subsingleton_of_not_le h r
  Module.finrank_zero_of_subsingleton

end Jets

end Nikodym.LowerBound

/- Adapted for Lean Pool: module imports and compatibility with its pinned toolchain. -/
