/-
Copyright (c) 2026 Scott Armstrong, Tuomo Kuusi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Tuomo Kuusi
-/

import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.AssemblyPieces
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.BesovLeGagliardo
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.CenteredCubeDivergenceRescaling
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.CenteredCubeEuclideanH2
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.CenteredCubeEuclideanL2
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.CenteredCubeFractionalCZ
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.CenteredCubeFractionalCZFullNorm
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.CenteredCubeFractionalGradientMemLp
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ClassicalDualComparison
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.CongruenceAE
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.Constants
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ContinuousInterpolation
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ContinuousKFunctional
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ConvexApproxGagliardoLpBound
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ConvexApproxGagliardoSmoothing
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.Definitions
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.DefinitionsAPI
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ENNRealBridge
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanGagliardoCoordinateBridgeP
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanH2
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWsp
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspCompletedDualExtension
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspCompletedDualGraph
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspCongruence
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspDilation
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspExactOverlapFullControl
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspLegacyCircComparison
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspLocalization
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspLpMembership
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspNegativeLocalization
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspPowerTwoBridge
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspSmoothDensity
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspSmoothDual
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspSmoothDualBesovBound
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspSmoothDualFieldPairing
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspSmoothDualNegativeBesov
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspSmoothGraph
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspSmoothMembership
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.EuclideanWspTranslation
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapEuclideanComparison
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapEuclideanFullComparison
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapEuclideanLpComparison
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapEuclideanLpDisjointBridge
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapEuclideanPoincare
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapFinitePAveraging
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapFinitePDepthTriangle
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapFinitePFullCZ
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapFinitePGlobalBound
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapFinitePHomogeneity
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapFinitePOneDepthCZ
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapFinitePPDESplitting
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapFinitePPoincareDepth
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapScalarComparison
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ExactOverlapScalarPComparison
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.GagliardoLeBesov
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.JensenStep
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.OverlapCount
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.OverlapIntegral
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.PairCapture
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.ShellGeometry
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.TailSummation
import LeanPool.CoarseGraining.Homogenization.Sobolev.Fractional.UnitCubeEuclideanL2

/-! Supporting modules for Coarse-graining theory for elliptic equations. -/
