/-
Copyright (c) 2026 OpenAI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: OpenAI
-/
module

public import LeanPool.NavierStokesAndEuler.Euler.PacketSourceProfiles
public import LeanPool.NavierStokesAndEuler.Euler.PacketCylinderHighParity
public import LeanPool.NavierStokesAndEuler.Euler.PacketProfileParity
import LeanPool.NavierStokesAndEuler.Euler.PacketPrimaryParity
import LeanPool.NavierStokesAndEuler.Euler.TransversePacketParity
public import LeanPool.NavierStokesAndEuler.Euler.CylinderFieldReflection
public import LeanPool.NavierStokesAndEuler.Euler.TransversePacketCorrectorOperator
import LeanPool.NavierStokesAndEuler.Euler.PacketProfilesRegularity
import LeanPool.NavierStokesAndEuler.Euler.MeanPacketParity
import LeanPool.NavierStokesAndEuler.Euler.PacketCylinderRecursiveAdmissibility
import LeanPool.NavierStokesAndEuler.Euler.TransversePacketPressureGradientProperties
import LeanPool.NavierStokesAndEuler.Euler.TransversePacketPressureParity

/-! Joint parity of every profile generated by the literal source operators. -/

section

/-! One actual mean/transverse solve preserves every joint profile symmetry. -/

@[expose] public section

noncomputable section

namespace EulerPacketCylinderField.ProfileParity

open Set EulerSmoothLimit EulerPacketPointJets EulerPacketProfileRecursion
  EulerLpCylinderTranslation EulerCylinderFieldReflection

variable {P : ℝ} [Fact (0 < P)] (M : EulerMeanPacketProvider.Data)
  {U : Type*} [NormedAddCommGroup U] [InnerProductSpace ℝ U] [CompleteSpace U]
  (D : EulerTransversePacketProvider.Data U) (hT : M.T = D.T)
  (I : EulerTransversePacketProvider.InitialData P D)
  {O : Operators} (C : CoefficientData P M.T O)
  (hmean : O.meanSolve = EulerMeanPacketProvider.meanSolve M)
  (hhigh : O.highSolve = EulerTransversePacketProvider.highSolve P D I)
  (hcorrector : O.curlCorrector = D.curlCorrector P)
  (E : CoefficientEven M.T O) (eM : EulerMeanPacketProvider.EvenData M)
  (hSym : ∀ x, -x ∈ D.support ↔ x ∈ D.support)
  (hF : ∀ t x, D.F.field t (-x) = D.F.field t x)
  (hDM : ∀ t x, D.M.field t (-x) = D.M.field t x)
  (hI : reflection P (I.value : CylinderL2 P U) = -(I.value : CylinderL2 P U))
  {p : ℕ} {a : ℕ → Profile}

include hT I C hmean hhigh hcorrector E eM hSym hF hDM hI in
theorem step (hp : 2 ≤ p)
    (G : ∀ i, i < p → ProfileRegularity P M.T M.T_pos.le D.support (a i))
    (H : ∀ i, i < p → ProfileParity M.T (a i)) :
    ProfileParity M.T (EulerPacketProfileRecursion.step O p a) := by
  let F := ProfileRegularity.prefixFields G
  let W := G (p-1) (by omega)
  have Hpre := prefixOdd H
  let hm : Nonempty (EulerMeanPacketProvider.Forcing M (EulerPacketProfileRecursion.meanForce O p
      a)) :=
    ⟨F.meanForcing M C (by omega) W.correctorDerivative W.corrector_time W.pressure⟩
  let hh : Nonempty (EulerTransversePacketProvider.Forcing P D
      (EulerPacketProfileRecursion.highForce O p a)) :=
    ⟨F.highForcing M D hT C hp W.correctorDerivative W.corrector_time W.pressure hmean
      (ProfileRegularity.prefixLocality G) W.pressure_zero⟩
  let GH := Classical.choice hh
  have hmOdd := F.meanForce_odd Hpre C E (by omega) M.T_pos W.correctorDerivative
    W.corrector_time W.pressure (H (p-1) (by omega)).pressure
  have hm0 (t : Icc (0 : ℝ) M.T) (x : Space) :
      EulerPacketProfileRecursion.meanForce O p a (t,(-x,0)) =
        -EulerPacketProfileRecursion.meanForce O p a (t,(x,0)) := by
    simpa only [neg_zero] using hmOdd t x 0
  have hhOdd : JointOdd D.T (EulerPacketProfileRecursion.highForce O p a) :=
    (F.actualHighForce_odd M Hpre C E eM hp W.correctorDerivative W.corrector_time
      W.pressure (H (p-1) (by omega)).pressure hmean).changeTime hT
  refine {
    high := ?_
    mean := ?_
    corrector := ?_
    pressure := ?_
    highPressure := ?_
    meanPressure := ?_ }
  · intro t x θ
    let td : Icc (0 : ℝ) D.T := ⟨t,by rw [← hT]; exact t.property⟩
    change (O.highSolve (EulerPacketProfileRecursion.highForce O p a)).1 (t,(-x,-θ)) =
      -(O.highSolve (EulerPacketProfileRecursion.highForce O p a)).1 (t,(x,θ))
    rw [hhigh,EulerTransversePacketProvider.highSolve_of_admissible D I _ hh]
    exact GH.vector_odd I hSym hF hDM hhOdd hI td x θ
  · intro t x θ
    change (O.meanSolve (EulerPacketProfileRecursion.meanForce O p a)).1 (t,(-x,-θ)) =
      -(O.meanSolve (EulerPacketProfileRecursion.meanForce O p a)).1 (t,(x,θ))
    rw [hmean]
    exact EulerMeanPacketProvider.meanSolve_odd M eM _ hm hm0 t x θ
  · intro t x θ
    let td : Icc (0 : ℝ) D.T := ⟨t,by rw [← hT]; exact t.property⟩
    change O.curlCorrector (O.highSolve (EulerPacketProfileRecursion.highForce O p a)).1
        (t,(-x,-θ)) =
      -O.curlCorrector (O.highSolve (EulerPacketProfileRecursion.highForce O p a)).1 (t,(x,θ))
    rw [hcorrector,hhigh,EulerTransversePacketProvider.highSolve_of_admissible D I _ hh,
      GH.curlCorrector_eq I td (-x) (-θ),GH.curlCorrector_eq I td x θ]
    exact GH.corrector_odd_of_data I hSym hF hDM hhOdd hI td x θ
  · intro t x θ
    let td : Icc (0 : ℝ) D.T := ⟨t,by rw [← hT]; exact t.property⟩
    change pressureGradient (O.highSolve (EulerPacketProfileRecursion.highForce O p a)).2
        (t,(-x,-θ)) =
      -pressureGradient (O.highSolve (EulerPacketProfileRecursion.highForce O p a)).2 (t,(x,θ))
    rw [hhigh,EulerTransversePacketProvider.highSolve_of_admissible D I _ hh]
    exact GH.scalarGradient_odd I hSym hF hDM hhOdd hI td x θ
  · intro t x θ
    let td : Icc (0 : ℝ) D.T := ⟨t,by rw [← hT]; exact t.property⟩
    change (O.highSolve (EulerPacketProfileRecursion.highForce O p a)).2 (t,(-x,-θ)) =
      (O.highSolve (EulerPacketProfileRecursion.highForce O p a)).2 (t,(x,θ))
    rw [hhigh,EulerTransversePacketProvider.highSolve_of_admissible D I _ hh]
    exact GH.scalar_even I hSym hF hDM hhOdd hI td x θ
  · intro t x θ
    change (O.meanSolve (EulerPacketProfileRecursion.meanForce O p a)).2 (t,(-x,-θ)) =
      (O.meanSolve (EulerPacketProfileRecursion.meanForce O p a)).2 (t,(x,θ))
    rw [hmean]
    exact EulerMeanPacketProvider.meanSolve_even M eM _ hm hm0 t x θ

end EulerPacketCylinderField.ProfileParity

end
end

end

section

/-! Every profile in the literal recursively generated family has the source parity. -/

@[expose] public section

noncomputable section

namespace EulerPacketCylinderField

open Set EulerSmoothLimit EulerPacketPointJets EulerPacketProfileRecursion
  EulerLpCylinderTranslation EulerCylinderFieldReflection

variable {P : ℝ} [Fact (0 < P)] (M : EulerMeanPacketProvider.Data)
  {U : Type*} [NormedAddCommGroup U] [InnerProductSpace ℝ U] [CompleteSpace U]
  (D : EulerTransversePacketProvider.Data U) (hT : M.T = D.T)
  (I : EulerTransversePacketProvider.InitialData P D)
  {O : Operators} (C : CoefficientData P M.T O)
  (hmean : O.meanSolve = EulerMeanPacketProvider.meanSolve M)
  (hhigh : O.highSolve = EulerTransversePacketProvider.highSolve P D I)
  (hcorrector : O.curlCorrector = D.curlCorrector P)
  (E : CoefficientEven M.T O) (eM : EulerMeanPacketProvider.EvenData M)
  (hSym : ∀ x, -x ∈ D.support ↔ x ∈ D.support)
  (hF : ∀ t x, D.F.field t (-x) = D.F.field t x)
  (hDM : ∀ t x, D.M.field t (-x) = D.M.field t x)
  (hI : reflection P (I.value : CylinderL2 P U) = -(I.value : CylinderL2 P U))
  (primary : Profile) (hprimary : ProfileRegularity P M.T M.T_pos.le D.support primary)
  (hprimaryParity : ProfileParity M.T primary)

include hT I C hmean hhigh hcorrector E eM hSym hF hDM hI hprimary hprimaryParity in
theorem profiles_parity (p : ℕ) : ProfileParity M.T (profiles O primary p) := by
  induction p using Nat.strong_induction_on with
  | h p ih =>
    by_cases hp0 : p = 0
    · subst p
      rw [profiles_zero]
      exact ProfileParity.zero M.T
    by_cases hp1 : p = 1
    · subst p
      rw [profiles_one]
      exact hprimaryParity
    have hp : 2 ≤ p := by omega
    let G : ∀ i, i < p → ProfileRegularity P M.T M.T_pos.le D.support (profiles O primary i) :=
      fun i _ => profileWitness M D hT I C hmean hhigh hcorrector primary hprimary i
    rw [profiles_step O primary p hp]
    exact ProfileParity.step M D hT I C hmean hhigh hcorrector E eM hSym hF hDM hI hp G ih

end EulerPacketCylinderField

end
end

end

@[expose] public section

noncomputable section

namespace EulerPacketCylinderField

open Set EulerSmoothLimit EulerPacketProfileRecursion
  EulerLpCylinderTranslation EulerCylinderFieldReflection

variable (P : ℝ) [Fact (0 < P)] (M : EulerMeanPacketProvider.Data)
  {U : Type*} [NormedAddCommGroup U] [InnerProductSpace ℝ U] [CompleteSpace U]
  (D : EulerTransversePacketProvider.Data U)
  (I Iprimary : EulerTransversePacketProvider.InitialData P D)

theorem sourceCoefficientEven
    (hF : ∀ t x, D.F.field t (-x) = D.F.field t x)
    (hM : ∀ t x, D.M.field t (-x) = D.M.field t x) :
    CoefficientEven M.T (sourceOperators P M D I) where
  inverse t x _ := D.inverse_even hF (D.clamp t) x
  strain t x _ := hM (D.clamp t) x
  normal t x _ := D.normal_even hF (D.clamp t) x

theorem sourceProfiles_parity (hT : M.T = D.T)
    (eM : EulerMeanPacketProvider.EvenData M)
    (hSym : ∀ x, -x ∈ D.support ↔ x ∈ D.support)
    (hF : ∀ t x, D.F.field t (-x) = D.F.field t x)
    (hDM : ∀ t x, D.M.field t (-x) = D.M.field t x)
    (hI : reflection P (I.value : CylinderL2 P U) = -(I.value : CylinderL2 P U))
    (hIprimary : reflection P (Iprimary.value : CylinderL2 P U) = -(Iprimary.value : CylinderL2 P
        U))
    (p : ℕ) : ProfileParity M.T (sourceProfiles P M D I Iprimary p) :=
  profiles_parity M D hT I (sourceCoefficientData P M D I hT) rfl rfl rfl
    (sourceCoefficientEven P M D I hF hDM) eM hSym hF hDM hI
    (homogeneousPrimary D Iprimary (sourceOperators P M D I))
    ((homogeneousPrimaryRegularity D Iprimary (sourceOperators P M D I) rfl).changeTime hT.symm
        M.T_pos.le)
    ((homogeneousPrimaryParity D Iprimary (sourceOperators P M D I) rfl hSym hF hDM
        hIprimary).changeTime hT.symm) p

theorem sourceProfiles_time_derivatives_odd (hT : M.T = D.T)
    (eM : EulerMeanPacketProvider.EvenData M)
    (hSym : ∀ x, -x ∈ D.support ↔ x ∈ D.support)
    (hF : ∀ t x, D.F.field t (-x) = D.F.field t x)
    (hDM : ∀ t x, D.M.field t (-x) = D.M.field t x)
    (hI : reflection P (I.value : CylinderL2 P U) = -(I.value : CylinderL2 P U))
    (hIprimary : reflection P (Iprimary.value : CylinderL2 P U) = -(Iprimary.value : CylinderL2 P
        U))
    (p : ℕ) :
    let G := sourceProfileWitness P M D hT I Iprimary p
    JointOdd M.T G.highT ∧ JointOdd M.T G.meanT ∧ JointOdd M.T G.correctorT := by
  let G := sourceProfileWitness P M D hT I Iprimary p
  have H := sourceProfiles_parity P M D I Iprimary hT eM hSym hF hDM hI hIprimary p
  exact ⟨ProfileParity.highDerivative_odd M.T_pos G H,
    ProfileParity.meanDerivative_odd M.T_pos G H,ProfileParity.correctorDerivative_odd M.T_pos G H⟩

end EulerPacketCylinderField
