/-
Copyright (c) 2026 William Whistler. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Whistler
-/

import LeanPool.RegtsSevenster.RS.Classical.Algebra.TraceCriterion
import LeanPool.RegtsSevenster.RS.Classical.CatTheory.KaroubiLinear
import LeanPool.RegtsSevenster.RS.Classical.CatTheory.KaroubiTrace
import LeanPool.RegtsSevenster.RS.Classical.Algebra.FactorialTrace
import LeanPool.RegtsSevenster.RS.Classical.CatTheory.Growth
import LeanPool.RegtsSevenster.RS.Classical.CatTheory.Intertwine
import LeanPool.RegtsSevenster.RS.Classical.CatTheory.Length
import LeanPool.RegtsSevenster.RS.Classical.CatTheory.LengthBound
import LeanPool.RegtsSevenster.RS.Classical.CatTheory.LinearCategory
import LeanPool.RegtsSevenster.RS.Classical.CatTheory.PartialTrace
import LeanPool.RegtsSevenster.RS.Classical.CatTheory.TensorPow
import LeanPool.RegtsSevenster.RS.Classical.CatTheory.Trace
import LeanPool.RegtsSevenster.RS.Classical.CatTheory.UnitEnd
import LeanPool.RegtsSevenster.RS.Classical.CatTheory.WhiskerAdditive
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.DeligneBridge
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.DelignePackage
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.DelignePackageRestrict
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.DeligneTheorem
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.EulerianIndependence
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.FibreTransport
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.KoszulAction
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.OmegaPerm
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.OmegaTensorPower
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.SchurPackage
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.SectorDischarge
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.SectorIntertwine
import LeanPool.RegtsSevenster.RS.Classical.Interfaces.TotalDimension
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.BlockKill
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.BranchTrace
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CentralElem
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CharClass
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CharDecomp
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CharEquiv
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.ColourCycleSum
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.ColourWeight
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CommutantBound
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.ContentCount
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CycleFactor
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CycleSum
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CycleSumPrep
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.EndSum
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.FibreCard
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.FixWeight
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.HVal
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.IdempotentBridge
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.JTChar
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.JTIntChar
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.JTIrreducible
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.JTOrtho
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.JTPad
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.JTSimple
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.KillSimples
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.MixedCount
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.MixedFixed
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.NativeAction
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.NativeFaithful
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.NativeTable
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.OrbitBridge
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.Package
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PackageAssembly
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PairChar
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PairInner
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PairOrbit
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PairStab
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PairTuple
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PairingPos
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PermModule
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PowerSurj
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.RegularTrace
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SameCycleQuot
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.ScalarTrace
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SchurAction
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SigmaCycleType
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SignResolve
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SignedTensor
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SimpleEmbed
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SquareGrowth
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SquareGrowthSharp
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SquareStair
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.StabCount
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.TensorNonvanishing
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.TensorTrace
import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.WordCommutant
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourAction
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourConj
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourConjStep
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourConjTop
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourEval
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourExtendSwap
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourFormMatch
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourMerge
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourMergeOdd
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourPairing
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourPairingSymm
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourPower
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourTotal
import LeanPool.RegtsSevenster.RS.Classical.Super.ColourWord
import LeanPool.RegtsSevenster.RS.Classical.Super.OrthonormalBasis
import LeanPool.RegtsSevenster.RS.Classical.Super.PowBraid
import LeanPool.RegtsSevenster.RS.Classical.Super.SuperVect
import LeanPool.RegtsSevenster.RS.Classical.Super.SymplecticBasis
import LeanPool.RegtsSevenster.RS.Classical.Super.TotalSpace
import LeanPool.RegtsSevenster.RS.Classical.Super.WordSignPerm
import LeanPool.RegtsSevenster.RS.Classical.SymFun.AlternantExpand
import LeanPool.RegtsSevenster.RS.Classical.SymFun.AlternantPieri
import LeanPool.RegtsSevenster.RS.Classical.SymFun.AlternantStrict
import LeanPool.RegtsSevenster.RS.Classical.SymFun.Bialternant
import LeanPool.RegtsSevenster.RS.Classical.SymFun.BinomialDet
import LeanPool.RegtsSevenster.RS.Classical.SymFun.BinomialH
import LeanPool.RegtsSevenster.RS.Classical.SymFun.CoeffExtract
import LeanPool.RegtsSevenster.RS.Classical.SymFun.CoeffSplit
import LeanPool.RegtsSevenster.RS.Classical.SymFun.DeltaSeq
import LeanPool.RegtsSevenster.RS.Classical.SymFun.DescVandermonde
import LeanPool.RegtsSevenster.RS.Classical.SymFun.DimFormula
import LeanPool.RegtsSevenster.RS.Classical.SymFun.EHConv
import LeanPool.RegtsSevenster.RS.Classical.SymFun.EHDischarge
import LeanPool.RegtsSevenster.RS.Classical.SymFun.HInsert
import LeanPool.RegtsSevenster.RS.Classical.SymFun.HProdCoeff
import LeanPool.RegtsSevenster.RS.Classical.SymFun.HSubZ
import LeanPool.RegtsSevenster.RS.Classical.SymFun.HookVanishing
import LeanPool.RegtsSevenster.RS.Classical.SymFun.JTDetExpand
import LeanPool.RegtsSevenster.RS.Classical.SymFun.JTGuard
import LeanPool.RegtsSevenster.RS.Classical.SymFun.LGVStrict
import LeanPool.RegtsSevenster.RS.Classical.SymFun.PieriChain
import LeanPool.RegtsSevenster.RS.Classical.SymFun.PowCount
import LeanPool.RegtsSevenster.RS.Classical.SymFun.PowerSums
import LeanPool.RegtsSevenster.RS.Classical.SymFun.RationalityFromRecurrence
import LeanPool.RegtsSevenster.RS.Classical.SymFun.RecurrenceFromVanishing
import LeanPool.RegtsSevenster.RS.Classical.SymFun.SubsetEH
import LeanPool.RegtsSevenster.RS.Classical.SymFun.SuperPowerSums
import LeanPool.RegtsSevenster.RS.Classical.SymFun.TCount
import LeanPool.RegtsSevenster.RS.Classical.SymFun.TIdentity
import LeanPool.RegtsSevenster.RS.Classical.SymFun.ZetaExp
import LeanPool.RegtsSevenster.RS.Classical.SymFun.ZetaRational
import LeanPool.RegtsSevenster.RS.Classical.SymFun.ZetaSeries
import LeanPool.RegtsSevenster.RS.Novel.Extraction.StdRigid
import LeanPool.RegtsSevenster.RS.Novel.Extraction.StdSuper
