/-
Copyright (c) 2026 Juliane Trianon Fraga and Vinicius de Oliveira Rodrigues. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Juliane Trianon Fraga, Vinicius de Oliveira Rodrigues
-/

import Mathlib.Algebra.BigOperators.Finsupp.Basic
import Mathlib.Algebra.Module.NatInt
import Mathlib.Logic.Encodable.Pi
import Mathlib.Order.Filter.Cofinite
import Mathlib.Order.Filter.Ultrafilter.Defs
import Mathlib.Order.Interval.Finset.Nat
import Mathlib.SetTheory.Cardinal.Cofinality.Ordinal
import Mathlib.SetTheory.Cardinal.Continuum

/-!
# ZFC foundations used by the Wallace construction

This file records the parts of the set-theoretic and topological construction that can be
checked directly against mathlib.  In particular, it proves the ultrafilter extension step and
the basic facts about the initial topology generated by a family of circle-valued characters.

No declaration in this file is an axiom and no proof is omitted.
-/

open Filter Set
open scoped Cardinal

universe u v w

namespace Wallace

noncomputable section

/-! ## Families with the finite-intersection property -/

/-- Any proper filter extending the cofinite filter admits a free ultrafilter refinement. -/
theorem exists_free_ultrafilter_le_filter {α : Type u} (l : Filter α) [l.NeBot]
    (hl : l ≤ cofinite) :
    ∃ p : Ultrafilter α,
      (p : Filter α) ≤ l ∧ (p : Filter α) ≤ cofinite := by
  refine ⟨Ultrafilter.of l, Ultrafilter.of_le l, ?_⟩
  exact (Ultrafilter.of_le l).trans hl

/-! ## Characters of a free Abelian group -/

/-- The homomorphism out of a free Abelian group determined by its values on the standard
basis. -/
def finsuppAddHomOfBasis {ι : Type u} {A : Type v} [AddCommGroup A]
    (z : ι → A) : (ι →₀ ℤ) →+ A :=
  Finsupp.liftAddHom fun i => (zmultiplesHom A) (z i)

@[simp]
theorem finsuppAddHomOfBasis_single {ι : Type u} {A : Type v} [AddCommGroup A]
    (z : ι → A) (i : ι) (n : ℤ) :
    finsuppAddHomOfBasis z (Finsupp.single i n) = n • z i := by
  simp [finsuppAddHomOfBasis]

/-! ## The initial topology generated by circle-valued characters -/

/-! ## Cardinal bookkeeping for the continuum-indexed free group -/

/-- König's theorem gives the strict uncountable cofinality of the continuum.  This is the
precise fact used to bound a countable union of supports below the initial ordinal of `𝔠`. -/
theorem aleph0_lt_cof_continuum : ℵ₀ < (𝔠 : Cardinal).ord.cof := by
  rw [← Cardinal.two_power_aleph0]
  exact Cardinal.lt_cof_ord_power le_rfl (by simp)

/-! ## A continuum-sized almost-disjoint family -/

/-- A concrete node on the binary tree: a level and the values below that level. -/
abbrev BinaryTreeNode := Σ n : ℕ, Fin n → Bool

/-- The length-`n` initial segment of a binary stream. -/
def binaryPrefix (x : ℕ → Bool) (n : ℕ) : BinaryTreeNode :=
  ⟨n, fun i => x i⟩

/-- The branch through the binary tree associated to a stream. -/
def binaryBranch (x : ℕ → Bool) : Set BinaryTreeNode :=
  Set.range (binaryPrefix x)

theorem binaryPrefix_injective (x : ℕ → Bool) :
    Function.Injective (binaryPrefix x) := by
  intro m n h
  exact congrArg Sigma.fst h

/-- Every branch is infinite. -/
theorem binaryBranch_infinite (x : ℕ → Bool) : (binaryBranch x).Infinite := by
  exact Set.infinite_range_of_injective (binaryPrefix_injective x)

/-- If two branches share a node at level `n`, then their streams agree below `n`. -/
theorem eq_on_Iio_of_binaryPrefix_eq {x y : ℕ → Bool} {m n : ℕ}
    (h : binaryPrefix x m = binaryPrefix y n) :
    m = n ∧ ∀ k < m, x k = y k := by
  have hmn : m = n := congrArg Sigma.fst h
  subst n
  refine ⟨rfl, ?_⟩
  have hfun : (fun i : Fin m => x i) = fun i : Fin m => y i :=
    eq_of_heq (Sigma.mk.inj_iff.mp h).2
  intro k hk
  exact congrFun hfun ⟨k, hk⟩

/-- Distinct binary streams define branches with finite intersection. -/
theorem binaryBranch_inter_finite {x y : ℕ → Bool} (hxy : x ≠ y) :
    (binaryBranch x ∩ binaryBranch y).Finite := by
  obtain ⟨k, hk⟩ : ∃ k, x k ≠ y k := by
    simpa only [Function.ne_iff] using hxy
  refine (Set.finite_Iic k).image (binaryPrefix x) |>.subset ?_
  intro z hz
  rcases hz.1 with ⟨m, rfl⟩
  rcases hz.2 with ⟨n, hmn⟩
  have hmn' := (eq_on_Iio_of_binaryPrefix_eq hmn).1
  subst n
  refine ⟨m, ?_, rfl⟩
  by_contra hmk
  have hkm : k < m := Nat.lt_of_not_ge hmk
  exact hk ((eq_on_Iio_of_binaryPrefix_eq hmn).2 k hkm).symm

/-- The binary-tree node type is infinite. -/
theorem binaryTreeNode_infinite : Infinite BinaryTreeNode :=
  Infinite.of_injective (binaryPrefix fun _ => false)
    (binaryPrefix_injective fun _ => false)

/-- A fixed identification of the countably infinite binary tree with `ℕ`. -/
def binaryTreeNodeEquivNat : BinaryTreeNode ≃ ℕ := by
  letI : Infinite BinaryTreeNode := binaryTreeNode_infinite
  letI : Denumerable BinaryTreeNode :=
    Denumerable.ofEncodableOfInfinite BinaryTreeNode
  exact Denumerable.eqv BinaryTreeNode

/-- The same branch family, transported to an almost-disjoint family literally on `ℕ`. -/
def binaryBranchOnNat (x : ℕ → Bool) : Set ℕ :=
  binaryTreeNodeEquivNat '' binaryBranch x

theorem binaryBranchOnNat_infinite (x : ℕ → Bool) :
    (binaryBranchOnNat x).Infinite := by
  exact (binaryBranch_infinite x).image binaryTreeNodeEquivNat.injective.injOn

theorem binaryBranchOnNat_inter_finite {x y : ℕ → Bool} (hxy : x ≠ y) :
    (binaryBranchOnNat x ∩ binaryBranchOnNat y).Finite := by
  change (binaryTreeNodeEquivNat '' binaryBranch x ∩
    binaryTreeNodeEquivNat '' binaryBranch y).Finite
  rw [← Set.image_inter binaryTreeNodeEquivNat.injective]
  exact (binaryBranch_inter_finite hxy).image binaryTreeNodeEquivNat

/-! ## A reusable transfinite-iteration fact -/

end

end Wallace
