/-
Copyright (c) 2026 Juliane Trianon Fraga and Vinicius de Oliveira Rodrigues. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Juliane Trianon Fraga, Vinicius de Oliveira Rodrigues
-/

import Mathlib

/-!
# ZFC foundations used by the Wallace construction

This file records the parts of the set-theoretic and topological construction that can be
checked directly against mathlib.  In particular, it proves the ultrafilter extension step and
the basic facts about the initial topology generated by a family of circle-valued characters.

No declaration in this file is an axiom and no proof is omitted.
-/

open Filter Set Topology
open scoped Cardinal

universe u v w

namespace Wallace

noncomputable section

/-! ## Families with the finite-intersection property -/

/-- A family of sets has the finite-intersection property when every finite subfamily has
nonempty intersection.  The empty finite subfamily is included, so this also records that the
underlying type is nonempty whenever the property holds. -/
def HasFiniteIntersectionProperty {α : Type u} (𝒜 : Set (Set α)) : Prop :=
  ∀ T : Finset (Set α), (↑T : Set (Set α)) ⊆ 𝒜 →
    (⋂₀ (↑T : Set (Set α))).Nonempty

/-- The ultrafilter lemma in the exact finite-intersection form needed in the construction. -/
theorem exists_ultrafilter_extending_fip {α : Type u} {𝒜 : Set (Set α)}
    (h𝒜 : HasFiniteIntersectionProperty 𝒜) :
    ∃ p : Ultrafilter α, 𝒜 ⊆ (p : Filter α).sets :=
  Ultrafilter.exists_ultrafilter_of_finite_inter_nonempty 𝒜 h𝒜

/-- If a finite-intersection family contains every cofinite set, its ultrafilter extension is
free (expressed by lying below the cofinite filter in the filter order). -/
theorem exists_free_ultrafilter_extending_fip {α : Type u} {𝒜 : Set (Set α)}
    (h𝒜 : HasFiniteIntersectionProperty 𝒜)
    (hcofinite : (cofinite : Filter α).sets ⊆ 𝒜) :
    ∃ p : Ultrafilter α,
      𝒜 ⊆ (p : Filter α).sets ∧ (p : Filter α) ≤ cofinite := by
  obtain ⟨p, hp⟩ := exists_ultrafilter_extending_fip h𝒜
  refine ⟨p, hp, ?_⟩
  intro s hs
  exact hp (hcofinite hs)

/-- Any proper filter extending the cofinite filter admits a free ultrafilter refinement. -/
theorem exists_free_ultrafilter_le_filter {α : Type u} (l : Filter α) [l.NeBot]
    (hl : l ≤ cofinite) :
    ∃ p : Ultrafilter α,
      (p : Filter α) ≤ l ∧ (p : Filter α) ≤ cofinite := by
  refine ⟨Ultrafilter.of l, Ultrafilter.of_le l, ?_⟩
  exact (Ultrafilter.of_le l).trans hl

/-- A filter below the cofinite filter contains no finite set. -/
theorem finite_not_mem_of_le_cofinite {α : Type u} {l : Filter α}
    [l.NeBot] (hl : l ≤ cofinite) {s : Set α} (hs : s.Finite) : s ∉ l := by
  intro hsl
  exact compl_notMem hsl (hl hs.compl_mem_cofinite)

/-! ## Characters of a free Abelian group -/

/-- The homomorphism out of a free Abelian group determined by its values on the standard
basis. -/
def finsuppAddHomOfBasis {ι : Type u} {A : Type v} [AddCommGroup A]
    (z : ι → A) : (ι →₀ ℤ) →+ A :=
  Finsupp.liftAddHom fun i => (zmultiplesHom A) (z i)

@[simp]
theorem finsuppAddHomOfBasis_single {ι : Type u} {A : Type v} [AddCommGroup A]
    (z : ι → A) (i : ι) (n : ℤ) :
    finsuppAddHomOfBasis z (Finsupp.single i n) = n • z i := by
  simp [finsuppAddHomOfBasis]

@[simp]
theorem finsuppAddHomOfBasis_single_one {ι : Type u} {A : Type v} [AddCommGroup A]
    (z : ι → A) (i : ι) :
    finsuppAddHomOfBasis z (Finsupp.single i 1) = z i := by
  simp

/-! ## The initial topology generated by circle-valued characters -/

/-- The diagonal homomorphism associated to a family of characters. -/
def characterDiagonal {G : Type u} {I : Type v} [AddGroup G]
    (χ : I → G →+ UnitAddCircle) : G →+ (I → UnitAddCircle) where
  toFun x i := χ i x
  map_zero' := by ext i; simp
  map_add' x y := by ext i; simp

@[simp]
theorem characterDiagonal_apply {G : Type u} {I : Type v} [AddGroup G]
    (χ : I → G →+ UnitAddCircle) (x : G) (i : I) :
    characterDiagonal χ x i = χ i x :=
  rfl

/-- Point-separation stated at zero, the natural form for additive characters. -/
def CharactersSeparatePoints {G : Type u} {I : Type v} [AddGroup G]
    (χ : I → G →+ UnitAddCircle) : Prop :=
  ∀ x : G, (∀ i, χ i x = 0) → x = 0

theorem characterDiagonal_injective {G : Type u} {I : Type v} [AddGroup G]
    {χ : I → G →+ UnitAddCircle} (hχ : CharactersSeparatePoints χ) :
    Function.Injective (characterDiagonal χ) := by
  intro x y hxy
  apply sub_eq_zero.mp
  apply hχ (x - y)
  intro i
  have hi : χ i x = χ i y := by
    simpa only [characterDiagonal_apply] using congrFun hxy i
  rw [map_sub, hi, sub_self]

/-- The initial topology generated by all members of `χ`.  Equivalently, this is the topology
induced by the diagonal map into the corresponding power of the circle. -/
@[reducible]
def characterTopology {G : Type u} {I : Type v} [AddGroup G]
    (χ : I → G →+ UnitAddCircle) : TopologicalSpace G :=
  TopologicalSpace.induced (characterDiagonal χ) inferInstance

/-- The uniformity induced by the same diagonal map. -/
@[reducible]
def characterUniformSpace {G : Type u} {I : Type v} [AddGroup G]
    (χ : I → G →+ UnitAddCircle) : UniformSpace G :=
  UniformSpace.comap (characterDiagonal χ) inferInstance

theorem characterUniformSpace_toTopology {G : Type u} {I : Type v} [AddGroup G]
    (χ : I → G →+ UnitAddCircle) :
    (characterUniformSpace χ).toTopologicalSpace = characterTopology χ :=
  rfl

/-- The diagonal description really is the infimum of the topologies induced by the individual
characters. -/
theorem characterTopology_eq_iInf {G : Type u} {I : Type v} [AddGroup G]
    (χ : I → G →+ UnitAddCircle) :
    characterTopology χ =
      ⨅ i, TopologicalSpace.induced (χ i : G → UnitAddCircle) inferInstance := by
  change TopologicalSpace.induced (fun x i => χ i x) Pi.topologicalSpace = _
  exact induced_to_pi fun x i => χ i x

/-- Universal property of the initial character topology. -/
theorem le_characterTopology_iff {G : Type u} {I : Type v} [AddGroup G]
    (χ : I → G →+ UnitAddCircle) (t : TopologicalSpace G) :
    t ≤ characterTopology χ ↔
      ∀ i, @Continuous G UnitAddCircle t inferInstance (χ i) := by
  change t ≤ TopologicalSpace.induced (characterDiagonal χ) inferInstance ↔ _
  rw [← continuous_iff_le_induced]
  exact continuous_pi_iff

/-- Every generating character is continuous for the initial topology. -/
theorem continuous_character {G : Type u} {I : Type v} [AddGroup G]
    (χ : I → G →+ UnitAddCircle) (i : I) :
    @Continuous G UnitAddCircle (characterTopology χ) inferInstance (χ i) := by
  exact (le_characterTopology_iff χ (characterTopology χ)).1 le_rfl i

/-- The initial character topology is a topological group topology. -/
theorem characterTopology_isTopologicalAddGroup
    {G : Type u} {I : Type v} [AddGroup G]
    (χ : I → G →+ UnitAddCircle) :
    @IsTopologicalAddGroup G (characterTopology χ) _ := by
  exact topologicalAddGroup_induced (characterDiagonal χ)

/-- A point-separating family of characters makes its initial topology Hausdorff. -/
theorem characterTopology_t2Space
    {G : Type u} {I : Type v} [AddGroup G]
    {χ : I → G →+ UnitAddCircle} (hχ : CharactersSeparatePoints χ) :
    @T2Space G (characterTopology χ) := by
  letI : TopologicalSpace G := characterTopology χ
  exact (characterDiagonal_injective hχ).isEmbedding_induced.t2Space

/-- The diagonal map is uniformly inducing for the pulled-back uniformity. -/
theorem characterDiagonal_isUniformInducing
    {G : Type u} {I : Type v} [AddGroup G]
    (χ : I → G →+ UnitAddCircle) :
    @IsUniformInducing G (I → UnitAddCircle)
      (characterUniformSpace χ) inferInstance (characterDiagonal χ) :=
  by
    letI : UniformSpace G := characterUniformSpace χ
    exact ⟨rfl⟩

/-- The pulled-back character uniformity is totally bounded: it is induced from a compact
power of the circle.  This is the precise uniform-space content of precompactness here. -/
theorem characterUniformSpace_totallyBounded
    {G : Type u} {I : Type v} [AddGroup G]
    (χ : I → G →+ UnitAddCircle) :
    @TotallyBounded G (characterUniformSpace χ) Set.univ := by
  letI : UniformSpace G := characterUniformSpace χ
  have htarget : TotallyBounded (Set.univ : Set (I → UnitAddCircle)) :=
    isCompact_univ.totallyBounded
  simpa using totallyBounded_preimage (characterDiagonal_isUniformInducing χ) htarget

/-! ## Cardinal bookkeeping for the continuum-indexed free group -/

/-- The free Abelian group on `ℝ` has cardinality continuum. -/
theorem mk_continuumFreeAbelianGroup : #(ℝ →₀ ℤ) = 𝔠 := by
  rw [Cardinal.mk_finsupp_of_infinite, Cardinal.mk_real, Cardinal.mk_int]
  exact max_eq_left Cardinal.aleph0_le_continuum

/-- The collection of all sequences in the continuum-indexed free group still has cardinality
continuum. -/
theorem mk_continuumFreeAbelianGroup_sequences : #(ℕ → (ℝ →₀ ℤ)) = 𝔠 := by
  rw [Cardinal.mk_arrow, mk_continuumFreeAbelianGroup, Cardinal.mk_nat]
  simpa only [Cardinal.lift_id] using Cardinal.continuum_power_aleph0

/-- König's theorem gives the strict uncountable cofinality of the continuum.  This is the
precise fact used to bound a countable union of supports below the initial ordinal of `𝔠`. -/
theorem aleph0_lt_cof_continuum : ℵ₀ < (𝔠 : Cardinal).ord.cof := by
  rw [← Cardinal.two_power_aleph0]
  exact Cardinal.lt_cof_ord_power le_rfl (by simp)

/-- A countable supremum of cardinals strictly below the continuum remains below the
continuum. -/
theorem iSup_nat_lt_continuum {f : ℕ → Cardinal.{0}}
    (hf : ∀ n, f n < 𝔠) : ⨆ n, f n < 𝔠 := by
  apply Cardinal.iSup_lt_of_lt_cof_ord
  · simpa only [Cardinal.mk_nat] using aleph0_lt_cof_continuum
  · exact hf

/-- Ordinal form of the same boundedness fact: countably many ordinals below the initial
ordinal of the continuum have supremum below it. -/
theorem iSup_nat_ordinal_lt_continuum {f : ℕ → Ordinal.{0}}
    (hf : ∀ n, f n < (𝔠 : Cardinal).ord) :
    ⨆ n, f n < (𝔠 : Cardinal).ord := by
  apply Ordinal.iSup_lt_of_lt_cof
  · simpa only [Cardinal.mk_nat] using aleph0_lt_cof_continuum
  · exact hf

/-- An explicit injective sequence in the free group, supported on one basis vector. -/
def basisRaySequence (r : ℝ) (n : ℕ) : ℝ →₀ ℤ :=
  Finsupp.single r (n : ℤ)

theorem basisRaySequence_injective (r : ℝ) :
    Function.Injective (basisRaySequence r) := by
  intro m n hmn
  have := congrArg (fun z : ℝ →₀ ℤ => z r) hmn
  simpa [basisRaySequence] using this

/-- Distinct basis vectors give distinct injective sequences. -/
theorem basisRaySequence_family_injective :
    Function.Injective (fun r : ℝ =>
      (⟨basisRaySequence r, basisRaySequence_injective r⟩ :
        {s : ℕ → (ℝ →₀ ℤ) // Function.Injective s})) := by
  intro r s hrs
  have hfun : basisRaySequence r = basisRaySequence s :=
    congrArg Subtype.val hrs
  have hzero := congrArg (fun q : ℕ → (ℝ →₀ ℤ) => q 1 r) hfun
  by_contra hrs'
  simp [basisRaySequence, hrs'] at hzero

/-- Hence every subtype of sequences, in particular the injective sequences used by the paper,
has cardinality at most continuum. -/
theorem mk_injective_continuumFreeAbelianGroup_sequences_le :
    #({s : ℕ → (ℝ →₀ ℤ) // Function.Injective s}) ≤ 𝔠 := by
  exact (Cardinal.mk_subtype_le _).trans_eq mk_continuumFreeAbelianGroup_sequences

/-- The injective sequences in the continuum-indexed free group have cardinality exactly
continuum. -/
theorem mk_injective_continuumFreeAbelianGroup_sequences :
    #({s : ℕ → (ℝ →₀ ℤ) // Function.Injective s}) = 𝔠 := by
  apply le_antisymm mk_injective_continuumFreeAbelianGroup_sequences_le
  rw [← Cardinal.mk_real]
  exact Cardinal.mk_le_of_injective basisRaySequence_family_injective

/-- A genuine enumeration (equivalence), not merely a cardinal upper bound, of the injective
sequences by a continuum-sized index type. -/
def injectiveSequenceEnumeration :
    ℝ ≃ {s : ℕ → (ℝ →₀ ℤ) // Function.Injective s} :=
  Classical.choice <| Cardinal.eq.mp <|
    Cardinal.mk_real.trans mk_injective_continuumFreeAbelianGroup_sequences.symm

/-! ## A continuum-sized almost-disjoint family -/

/-- A concrete node on the binary tree: a level and the values below that level. -/
abbrev BinaryTreeNode := Σ n : ℕ, Fin n → Bool

/-- The length-`n` initial segment of a binary stream. -/
def binaryPrefix (x : ℕ → Bool) (n : ℕ) : BinaryTreeNode :=
  ⟨n, fun i => x i⟩

/-- The branch through the binary tree associated to a stream. -/
def binaryBranch (x : ℕ → Bool) : Set BinaryTreeNode :=
  Set.range (binaryPrefix x)

theorem binaryPrefix_injective (x : ℕ → Bool) :
    Function.Injective (binaryPrefix x) := by
  intro m n h
  exact congrArg Sigma.fst h

/-- Every branch is infinite. -/
theorem binaryBranch_infinite (x : ℕ → Bool) : (binaryBranch x).Infinite := by
  exact Set.infinite_range_of_injective (binaryPrefix_injective x)

/-- If two branches share a node at level `n`, then their streams agree below `n`. -/
theorem eq_on_Iio_of_binaryPrefix_eq {x y : ℕ → Bool} {m n : ℕ}
    (h : binaryPrefix x m = binaryPrefix y n) :
    m = n ∧ ∀ k < m, x k = y k := by
  have hmn : m = n := congrArg Sigma.fst h
  subst n
  refine ⟨rfl, ?_⟩
  have hfun : (fun i : Fin m => x i) = fun i : Fin m => y i :=
    eq_of_heq (Sigma.mk.inj_iff.mp h).2
  intro k hk
  exact congrFun hfun ⟨k, hk⟩

/-- Distinct binary streams define branches with finite intersection. -/
theorem binaryBranch_inter_finite {x y : ℕ → Bool} (hxy : x ≠ y) :
    (binaryBranch x ∩ binaryBranch y).Finite := by
  obtain ⟨k, hk⟩ : ∃ k, x k ≠ y k := by
    simpa only [Function.ne_iff] using hxy
  refine (Set.finite_Iic k).image (binaryPrefix x) |>.subset ?_
  intro z hz
  rcases hz.1 with ⟨m, rfl⟩
  rcases hz.2 with ⟨n, hmn⟩
  have hmn' := (eq_on_Iio_of_binaryPrefix_eq hmn).1
  subst n
  refine ⟨m, ?_, rfl⟩
  by_contra hmk
  have hkm : k < m := Nat.lt_of_not_ge hmk
  exact hk ((eq_on_Iio_of_binaryPrefix_eq hmn).2 k hkm).symm

/-- The branch assignment is injective. -/
theorem binaryBranch_injective : Function.Injective binaryBranch := by
  intro x y hxy
  by_contra hne
  have hfinite := binaryBranch_inter_finite hne
  rw [hxy, inter_self] at hfinite
  exact (binaryBranch_infinite y) hfinite

/-- The concrete almost-disjoint family of binary-tree branches has cardinality continuum. -/
theorem mk_binaryBranch_family : #(Set.range binaryBranch) = 𝔠 := by
  rw [Cardinal.mk_range_eq binaryBranch binaryBranch_injective, Cardinal.mk_arrow,
    Cardinal.mk_bool, Cardinal.mk_nat]
  simp only [Cardinal.lift_id, Cardinal.two_power_aleph0]

/-- A packaged continuum-sized almost-disjoint family: every member is infinite, distinct
members have finite intersection, and the family itself has cardinality continuum. -/
theorem binaryBranch_family_spec :
    (∀ A ∈ Set.range binaryBranch, A.Infinite) ∧
    ((Set.range binaryBranch).Pairwise fun A B => (A ∩ B).Finite) ∧
    #(Set.range binaryBranch) = 𝔠 := by
  refine ⟨?_, ?_, mk_binaryBranch_family⟩
  · rintro A ⟨x, rfl⟩
    exact binaryBranch_infinite x
  · rintro A ⟨x, rfl⟩ B ⟨y, rfl⟩ hAB
    apply binaryBranch_inter_finite
    intro hxy
    exact hAB (congrArg binaryBranch hxy)

/-- The binary-tree node type used above is countable. -/
theorem binaryTreeNode_countable : Countable BinaryTreeNode :=
  inferInstance

/-- The binary-tree node type is infinite. -/
theorem binaryTreeNode_infinite : Infinite BinaryTreeNode :=
  Infinite.of_injective (binaryPrefix fun _ => false)
    (binaryPrefix_injective fun _ => false)

/-- A fixed identification of the countably infinite binary tree with `ℕ`. -/
def binaryTreeNodeEquivNat : BinaryTreeNode ≃ ℕ := by
  letI : Infinite BinaryTreeNode := binaryTreeNode_infinite
  letI : Denumerable BinaryTreeNode :=
    Denumerable.ofEncodableOfInfinite BinaryTreeNode
  exact Denumerable.eqv BinaryTreeNode

/-- The same branch family, transported to an almost-disjoint family literally on `ℕ`. -/
def binaryBranchOnNat (x : ℕ → Bool) : Set ℕ :=
  binaryTreeNodeEquivNat '' binaryBranch x

theorem binaryBranchOnNat_infinite (x : ℕ → Bool) :
    (binaryBranchOnNat x).Infinite := by
  exact (binaryBranch_infinite x).image binaryTreeNodeEquivNat.injective.injOn

theorem binaryBranchOnNat_inter_finite {x y : ℕ → Bool} (hxy : x ≠ y) :
    (binaryBranchOnNat x ∩ binaryBranchOnNat y).Finite := by
  change (binaryTreeNodeEquivNat '' binaryBranch x ∩
    binaryTreeNodeEquivNat '' binaryBranch y).Finite
  rw [← Set.image_inter binaryTreeNodeEquivNat.injective]
  exact (binaryBranch_inter_finite hxy).image binaryTreeNodeEquivNat

theorem binaryBranchOnNat_injective : Function.Injective binaryBranchOnNat :=
  binaryTreeNodeEquivNat.injective.image_injective.comp binaryBranch_injective

/-- Standard ZFC form: there is an explicit almost-disjoint family on `ℕ` of cardinality
continuum. -/
theorem binaryBranchOnNat_family_spec :
    (∀ A ∈ Set.range binaryBranchOnNat, A.Infinite) ∧
    ((Set.range binaryBranchOnNat).Pairwise fun A B => (A ∩ B).Finite) ∧
    #(Set.range binaryBranchOnNat) = 𝔠 := by
  refine ⟨?_, ?_, ?_⟩
  · rintro A ⟨x, rfl⟩
    exact binaryBranchOnNat_infinite x
  · rintro A ⟨x, rfl⟩ B ⟨y, rfl⟩ hAB
    apply binaryBranchOnNat_inter_finite
    intro hxy
    exact hAB (congrArg binaryBranchOnNat hxy)
  · rw [Cardinal.mk_range_eq binaryBranchOnNat binaryBranchOnNat_injective,
      Cardinal.mk_arrow, Cardinal.mk_bool, Cardinal.mk_nat]
    simp only [Cardinal.lift_id, Cardinal.two_power_aleph0]

/-! ## A reusable transfinite-iteration fact -/

/-- Inflationary transfinite iteration is monotone in the ordinal-like index.  This records the
mathlib recursion principle used for monotone bookkeeping constructions. -/
theorem transfiniteIterate_mono
    {L : Type u} [CompleteLattice L]
    {J : Type v} [LinearOrder J] [OrderBot J] [SuccOrder J] [WellFoundedLT J]
    (φ : L → L) (x : L) (hφ : ∀ y, y ≤ φ y) :
    Monotone (fun j : J => transfiniteIterate φ j x) :=
  monotone_transfiniteIterate φ x hφ

end

end Wallace
