/-
Copyright (c) 2026 Nathan Pflueger. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nathan Pflueger
-/
module

public import LeanPool.BrillNoetherGraphs.Bananas

/-!
# Standalone graph and banana vocabulary

Basic graph, divisor, and banana path data used by the paper-facing statements.
These declarations keep their independent `TMB` meanings and storage conventions.
-/

@[expose] public section

/-!
## Standalone mathematical vocabulary

The declarations in this section deliberately use only Mathlib. They give
the reader-facing meanings of the graph, divisor, banana, marking, and
transmission notation appearing below; none aliases the implementation
library. Everything lives in the namespace `TMB`, which no library
declaration inhabits, so that a solution file importing the implementation
library can repeat this block verbatim without any name collision.

The definitions are written to follow the implementation library's own
definitions as closely as possible (so that a solution can bridge them by
unfolding), but they are independent declarations. Small proof fields needed
to construct structures (for example, the additivity fields of `deg`) are
ordinary definitional well-formedness proofs written with deterministic
tactics, not solutions to any of the paper's theorem statements.
-/

namespace TMB

universe u v

open Multiset Finset

/-! ### Graphs and divisors -/

/-- A finite, nonempty, loopless undirected multigraph. Each edge occurrence
is stored once, using either ordering of its endpoints. -/
structure CFGraph where
  /-- The finite nonempty vertex type of the loopless multigraph. -/
  V : Type u
  [instDecidableEq : DecidableEq V]
  [instFintype : Fintype V]
  [instNonempty : Nonempty V]
  /-- The multiset of unoriented edge occurrences, each stored once as an ordered endpoint pair;
  repeated pairs represent parallel edges. -/
  edges : Multiset (V × V)
  loopless : ∀ x, (x, x) ∉ edges

attribute [instance] CFGraph.instDecidableEq CFGraph.instFintype
  CFGraph.instNonempty

/-- Number of edge occurrences joining two vertices. -/
def numEdges (G : CFGraph) (x y : G.V) : ℕ :=
  Multiset.card (G.edges.filter fun e => e = (x, y) ∨ e = (y, x))

/-- Connectivity in cut form. -/
def graphConnected (G : CFGraph) : Prop :=
  ∀ S : Finset G.V, (∃ x y : G.V, x ∈ S ∧ y ∉ S) →
    ∃ x ∈ S, ∃ y ∉ S, numEdges G x y > 0

/-- Cyclomatic genus `|E| - |V| + 1`. -/
def genus (G : CFGraph) : ℤ :=
  Multiset.card G.edges - Fintype.card G.V + 1

/-- Valence of a vertex. -/
def vertexDegree (G : CFGraph) (x : G.V) : ℤ :=
  ∑ y : G.V, (numEdges G x y : ℤ)

/-- An integral divisor on a graph. -/
abbrev CFDiv (G : CFGraph) := G.V → ℤ

/-- One chip at `x`. -/
def oneChip {G : CFGraph} (x : G.V) : CFDiv G :=
  fun y => if y = x then 1 else 0

/-- Edges leaving `x` towards the complement of `S`, with multiplicity. -/
def outdegreeSet (G : CFGraph) (S : Finset G.V) (x : G.V) : ℤ :=
  ∑ y ∈ (univ \ S), (numEdges G x y : ℤ)

/-- The principal divisor obtained by firing `x` once. -/
def firingVector (G : CFGraph) (x : G.V) : CFDiv G :=
  fun y => if y = x then -vertexDegree G x else numEdges G x y

/-- The subgroup generated by vertex firings. -/
def principalDivisors (G : CFGraph) : AddSubgroup (CFDiv G) :=
  AddSubgroup.closure (Set.range (firingVector G))

/-- Linear equivalence of divisors. -/
def linearEquiv (G : CFGraph) (D E : CFDiv G) : Prop :=
  E - D ∈ principalDivisors G

/-- An effective divisor has nonnegative coefficients. -/
def effective {G : CFGraph} (D : CFDiv G) : Prop :=
  ∀ x : G.V, D x ≥ 0

/-- Effective divisors as an additive submonoid. -/
def Eff (G : CFGraph) : AddSubmonoid (CFDiv G) where
  carrier := {D : CFDiv G | effective D}
  zero_mem' := by
    intro x
    exact le_refl (0 : ℤ)
  add_mem' := by
    intro D E hD hE x
    exact add_nonneg (hD x) (hE x)

/-- A divisor is winnable if its class has an effective representative. -/
def winnable (G : CFGraph) (D : CFDiv G) : Prop :=
  ∃ E ∈ Eff G, linearEquiv G D E

/-- Divisor degree. The short proofs certify that summation is additive. -/
def deg {G : CFGraph} : CFDiv G →+ ℤ where
  toFun D := ∑ x, D x
  map_zero' := by
    simp only [Pi.zero_apply, Finset.sum_const_zero]
  map_add' := by
    intro D E
    simp only [Pi.add_apply, Finset.sum_add_distrib]

/-- Effective divisors of a prescribed degree. -/
def effOfDegree (G : CFGraph) (d : ℤ) : Set (CFDiv G) :=
  {E | effective E ∧ deg E = d}

/-- Baker--Norine rank at least `r`, in subtraction-test form. -/
def rankGeq (G : CFGraph) (D : CFDiv G) (r : ℤ) : Prop :=
  ∀ E ∈ effOfDegree G r, winnable G (D - E)

/-- Exact rank as adjacent lower-bound tests. -/
def rankEq (G : CFGraph) (D : CFDiv G) (r : ℤ) : Prop :=
  rankGeq G D r ∧ ¬ rankGeq G D (r + 1)

open Classical in
/-- The unique exact rank when it exists, and `-1` as a fallback. -/
noncomputable def rank (G : CFGraph) (D : CFDiv G) : ℤ :=
  if h : ∃ r, rankEq G D r then Classical.choose h else -1

/-- The canonical divisor `K(x) = val(x) - 2`. -/
def canonicalDivisor (G : CFGraph) : CFDiv G :=
  fun x => vertexDegree G x - 2

/-- Effective away from `q`. -/
def qEffective {G : CFGraph} (q : G.V) (D : CFDiv G) : Prop :=
  ∀ x : G.V, x ≠ q → D x ≥ 0

/-- Firing `S` keeps every vertex of `S` out of debt. -/
def legalSet (G : CFGraph) (D : CFDiv G) (S : Finset G.V) : Prop :=
  ∀ x ∈ S, outdegreeSet G S x ≤ D x

/-- A `q`-reduced divisor: effective away from `q`, and no nonempty set
avoiding `q` can be fired legally. -/
def qReduced (G : CFGraph) (q : G.V) (D : CFDiv G) : Prop :=
  qEffective q D ∧
  ∀ S : Finset G.V, q ∉ S → S.Nonempty → ¬ legalSet G D S

/-! ### Brill--Noether parameters -/

/-- The width `g - d + r` of the Brill--Noether rectangle. -/
def rectangleWidth (G : CFGraph) (r d : ℤ) : ℤ :=
  genus G - d + r

/-- The Brill--Noether number. -/
def bnNumber (G : CFGraph) (r d : ℤ) : ℤ :=
  genus G - (r + 1) * rectangleWidth G r d

/-- Existence of a degree-`d` divisor of rank at least `r`. -/
def BNExists (G : CFGraph) (r d : ℤ) : Prop :=
  ∃ D : CFDiv G, deg D = d ∧ rank G D ≥ r

/-! ### Graph isomorphisms and vertex gluing -/

/-- A graph isomorphism is a vertex equivalence preserving multiplicities. -/
structure CFGraphIso (G : CFGraph.{u}) (H : CFGraph.{v}) where
  /-- The bijection of vertices whose edge-multiplicity preservation makes this a graph
  isomorphism. -/
  vertexEquiv : G.V ≃ H.V
  map_num_edges : ∀ x y : G.V,
    numEdges H (vertexEquiv x) (vertexEquiv y) = numEdges G x y

/-- Push a divisor forward along a graph isomorphism. -/
def CFGraphIso.mapDiv {G : CFGraph.{u}} {H : CFGraph.{v}} (φ : CFGraphIso G H)
    (D : CFDiv G) : CFDiv H :=
  fun y => D (φ.vertexEquiv.symm y)

/-- Embed a right-factor vertex into a vertex wedge. -/
def wedgeRightVertex (G : CFGraph.{u}) (H : CFGraph.{v})
    (x : G.V) (y : H.V) : H.V → Sum G.V {b : H.V // b ≠ y} :=
  fun b => if h : b = y then Sum.inl x else Sum.inr ⟨b, h⟩

/-- Identify `x` and `y` in the disjoint union of two graphs. -/
def vertexWedge (G : CFGraph.{u}) (H : CFGraph.{v})
    (x : G.V) (y : H.V) : CFGraph.{max u v} where
  V := Sum G.V {b : H.V // b ≠ y}
  edges :=
    G.edges.map (fun e => (Sum.inl e.1, Sum.inl e.2)) +
      H.edges.map (fun e =>
        (wedgeRightVertex G H x y e.1, wedgeRightVertex G H x y e.2))
  loopless := by
    intro z hz
    rw [Multiset.mem_add] at hz
    rcases hz with hG | hH
    · rw [Multiset.mem_map] at hG
      obtain ⟨⟨a, b⟩, hab, hEq⟩ := hG
      cases z with
      | inl z =>
          have ha : a = z := Sum.inl.inj (congrArg Prod.fst hEq)
          have hb : b = z := Sum.inl.inj (congrArg Prod.snd hEq)
          subst ha
          subst hb
          exact G.loopless _ hab
      | inr z => exact Sum.inl_ne_inr (congrArg Prod.fst hEq)
    · rw [Multiset.mem_map] at hH
      obtain ⟨⟨a, b⟩, hab, hEq⟩ := hH
      have hmap : wedgeRightVertex G H x y a = wedgeRightVertex G H x y b :=
        (congrArg Prod.fst hEq).trans (congrArg Prod.snd hEq).symm
      have hab' : a = b := by
        simp only [wedgeRightVertex] at hmap
        by_cases ha : a = y
        · by_cases hb : b = y
          · exact ha.trans hb.symm
          · rw [dif_pos ha, dif_neg hb] at hmap
            exact absurd hmap Sum.inl_ne_inr
        · by_cases hb : b = y
          · rw [dif_neg ha, dif_pos hb] at hmap
            exact absurd hmap Sum.inr_ne_inl
          · rw [dif_neg ha, dif_neg hb] at hmap
            exact congrArg Subtype.val (Sum.inr.inj hmap)
      subst hab'
      exact H.loopless _ hab

/-- Add factor divisors on their vertex wedge. -/
def wedgeAddDivisor (G : CFGraph.{u}) (H : CFGraph.{v})
    (x : G.V) (y : H.V) (D : CFDiv G) (E : CFDiv H) :
    CFDiv (vertexWedge G H x y) :=
  Sum.elim (fun a => D a + if a = x then E y else 0) (fun b => E b.1)

/-- A graph with ordered outside marks. -/
structure MarkedGraph where
  /-- The underlying graph on which the two ordered outside marks lie. -/
  graph : CFGraph.{0}
  /-- The left outside mark, retained as the left mark when another factor is glued on the
  right. -/
  left : graph.V
  /-- The right outside mark, identified with the next factor's left mark in a chain. -/
  right : graph.V

namespace MarkedGraph

/-- Glue the right mark of `M` to the left mark of `N`. -/
abbrev wedge (M N : MarkedGraph) : MarkedGraph where
  graph := vertexWedge M.graph N.graph M.right N.left
  left := Sum.inl M.left
  right := wedgeRightVertex M.graph N.graph M.right N.left N.right

/-- Left-associated iterated vertex gluing. -/
def chain (M : MarkedGraph) : List MarkedGraph → MarkedGraph
  | [] => M
  | N :: rest => chain (M.wedge N) rest

end MarkedGraph

/-- Total multiplicity of the edges leaving `S`. -/
def cutMultiplicity (G : CFGraph) (S : Finset G.V) : ℤ :=
  ∑ x ∈ S, outdegreeSet G S x

/-- Every nonempty proper cut has at least two crossing edges. -/
def TwoEdgeCutCondition (G : CFGraph) : Prop :=
  ∀ S : Finset G.V, S.Nonempty → S ≠ Finset.univ →
    2 ≤ cutMultiplicity G S

/-- A pointed genus-one graph whose marked point is the unique vertex in its
degree-zero linear-equivalence class. -/
structure PointedGenusOneRigid (H : CFGraph) (y : H.V) : Prop where
  connected : graphConnected H
  genus_one : genus H = 1
  exists_ne : ∃ p : H.V, p ≠ y
  nontrivial : ∀ p : H.V, p ≠ y →
    ¬ linearEquiv H (oneChip y - oneChip p) 0

/-! ### Banana graphs -/

/-- A positive integral banana graph with `g + 1` labelled strands between
two multivalent vertices `0` and `1`.  Each strand records which multivalent
vertex is its tail and which is its head (a storage orientation only; the
graph below is undirected), together with its positive length. -/
structure Banana (g : ℕ) where
  /-- The chosen tail pole of each of the `g + 1` banana strands. -/
  tail : Fin (g + 1) → Fin 2
  /-- The chosen head pole of each banana strand, required to differ from its tail. -/
  head : Fin (g + 1) → Fin 2
  /-- The number of edges in each subdivided banana strand, required to be positive. -/
  length : Fin (g + 1) → ℕ
  core_loopless : ∀ α, tail α ≠ head α
  length_pos : ∀ α, 0 < length α

namespace Banana

variable {g : ℕ} (B : Banana g)

/-- Interior vertices remember their strand and offset; offset `j` denotes
path position `j + 1` from the tail. -/
abbrev Interior := Σ α : Fin (g + 1), Fin (B.length α - 1)

/-- Vertices are the two multivalent vertices and all strand interiors. -/
abbrev Vertex := Fin 2 ⊕ B.Interior

/-- Unit steps along all strands. -/
abbrev Step := Σ α : Fin (g + 1), Fin (B.length α)

/-- Positions `0, ..., length` along a strand, measured from its tail. -/
abbrev PathPosition (α : Fin (g + 1)) := Fin (B.length α + 1)

/-- A multivalent vertex. -/
def coreVertex (i : Fin 2) : B.Vertex := Sum.inl i

/-- An interior vertex. -/
def interiorVertex (α : Fin (g + 1)) (offset : Fin (B.length α - 1)) :
    B.Vertex :=
  Sum.inr ⟨α, offset⟩

/-- The left endpoint of a unit step. -/
def stepLeft (α : Fin (g + 1)) (offset : Fin (B.length α)) : B.Vertex :=
  if hzero : offset.val = 0 then B.coreVertex (B.tail α)
  else B.interiorVertex α ⟨offset.val - 1, by have := offset.isLt; omega⟩

/-- The right endpoint of a unit step. -/
def stepRight (α : Fin (g + 1)) (offset : Fin (B.length α)) : B.Vertex :=
  if hlast : offset.val + 1 = B.length α then B.coreVertex (B.head α)
  else B.interiorVertex α ⟨offset.val, by have := offset.isLt; omega⟩

/-- The ordered pair emitted by one unit step. -/
def unitEdge (step : B.Step) : B.Vertex × B.Vertex :=
  (B.stepLeft step.1 step.2, B.stepRight step.1 step.2)

theorem stepLeft_ne_stepRight (α : Fin (g + 1)) (offset : Fin (B.length α)) :
    B.stepLeft α offset ≠ B.stepRight α offset := by
  unfold stepLeft stepRight
  by_cases hzero : offset.val = 0
  · rw [dif_pos hzero]
    by_cases hlast : offset.val + 1 = B.length α
    · rw [dif_pos hlast]
      intro heq
      exact B.core_loopless α (Sum.inl.inj heq)
    · rw [dif_neg hlast]
      exact Sum.inl_ne_inr
  · rw [dif_neg hzero]
    by_cases hlast : offset.val + 1 = B.length α
    · rw [dif_pos hlast]
      exact Sum.inr_ne_inl
    · rw [dif_neg hlast]
      intro heq
      have h : offset.val - 1 = offset.val :=
        congrArg (fun z : B.Interior => z.2.val) (Sum.inr.inj heq)
      omega

end Banana

end TMB
