/-
Copyright (c) 2026 Gregory Morse. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gregory Morse
-/
module

public import LeanPool.BooleanMultiplication.N4.FirstJet

/-!
# Rank-four support and the first Hasse jet

This file supplies the linear-algebra step used implicitly in the manuscript's
first-feedback argument.  The support of a two-form is the span of its eight
columns.  Each of the nine non-rational rank-two Hankel words has four
explicitly independent columns.  Consequently, if such a word is written as
the sum of two decomposable forms, all four factors belong to its support.

The only finite certificates below concern the nine fixed Hankel words and
their eight columns.  They do not enumerate circuits or Boolean functions.
-/

public section

namespace UnrestrictedBooleanMul
namespace N4

noncomputable section

/-- One column of a two-form coordinate matrix. -/
def twoFormColumn (q : TwoForm) (j : Fin 8) : LinearForm :=
  fun i => q i j

/-- The subspace spanned by the columns of a two-form. -/
def twoFormSupport (q : TwoForm) : Submodule F₂ LinearForm :=
  Submodule.span F₂ (Set.range (twoFormColumn q))

/-- Four pivot columns for every non-rational rank-two Hankel word.  The two
infinity tangents use the last two rows and columns; all other words use the
first two. -/
def outsideSupportPivot : Fin 9 → Fin 4 → Fin 8 :=
  ![![0, 1, 4, 5], ![0, 1, 4, 5],
    ![0, 1, 4, 5], ![0, 1, 4, 5],
    ![2, 3, 6, 7], ![2, 3, 6, 7],
    ![0, 1, 4, 5], ![0, 1, 4, 5], ![0, 1, 4, 5]]

/-- One of four pivot columns of a non-rational rank-two target Hankel form. -/
def outsideSelectedColumn (i : Fin 9) (k : Fin 4) : LinearForm :=
  twoFormColumn (targetTwo (outsideRankTwoWord i)) (outsideSupportPivot i k)

theorem outsideSelectedColumn_linearIndependent (i : Fin 9) :
    LinearIndependent F₂ (outsideSelectedColumn i) := by
  rw [Fintype.linearIndependent_iff]
  fin_cases i <;> decide

/-- Every column is generated by the four pivots.  This is a 9-by-8 matrix
calculation, kept existential so no large coefficient table enters the
trusted source. -/
theorem outsideColumn_generated (i : Fin 9) (j : Fin 8) :
    ∃ coeff : Fin 4 → F₂,
      twoFormColumn (targetTwo (outsideRankTwoWord i)) j =
        ∑ k : Fin 4, coeff k • outsideSelectedColumn i k := by
  fin_cases i <;> fin_cases j <;> decide

theorem outsideSupport_eq_selectedSpan (i : Fin 9) :
    twoFormSupport (targetTwo (outsideRankTwoWord i)) =
      Submodule.span F₂ (Set.range (outsideSelectedColumn i)) := by
  apply le_antisymm
  · rw [twoFormSupport, Submodule.span_le]
    rintro _ ⟨j, rfl⟩
    rcases outsideColumn_generated i j with ⟨coeff, hcoeff⟩
    rw [hcoeff]
    apply Submodule.sum_mem
    intro k _
    exact Submodule.smul_mem _ _
      (Submodule.subset_span ⟨k, rfl⟩)
  · rw [Submodule.span_le]
    rintro _ ⟨k, rfl⟩
    exact Submodule.subset_span ⟨outsideSupportPivot i k, rfl⟩

theorem outsideSupport_finrank (i : Fin 9) :
    Module.finrank F₂ (twoFormSupport (targetTwo (outsideRankTwoWord i))) = 4 := by
  rw [outsideSupport_eq_selectedSpan]
  exact finrank_span_eq_card (outsideSelectedColumn_linearIndependent i)

/-- The ordered family consisting of four specified linear forms. -/
def fourVectorFamily (u z p w : LinearForm) : Fin 4 → LinearForm :=
  ![u, z, p, w]

/-- The subspace spanned by four specified linear forms. -/
def fourVectorSpan (u z p w : LinearForm) : Submodule F₂ LinearForm :=
  Submodule.span F₂ (Set.range (fourVectorFamily u z p w))

theorem fourVectorSpan_finrank_le (u z p w : LinearForm) :
    Module.finrank F₂ (fourVectorSpan u z p w) ≤ 4 := by
  exact (finrank_span_le_card (Set.range (fourVectorFamily u z p w))).trans
    (by
      convert! Fintype.card_range_le (fourVectorFamily u z p w)
      rw [Set.toFinset_card])

theorem twoFormSupport_le_fourVectorSpan
    (q : TwoForm) (u z p w : LinearForm)
    (hq : q = vectorWedge u z + vectorWedge p w) :
    twoFormSupport q ≤ fourVectorSpan u z p w := by
  rw [twoFormSupport, Submodule.span_le]
  rintro _ ⟨j, rfl⟩
  have hcolumn : twoFormColumn q j =
      z j • u + u j • z + w j • p + p j • w := by
    rw [hq]
    funext k
    simp [twoFormColumn, vectorWedge]
    ring
  rw [hcolumn]
  apply Submodule.add_mem
  · apply Submodule.add_mem
    · apply Submodule.add_mem
      · exact Submodule.smul_mem _ _
          (Submodule.subset_span ⟨0, by simp [fourVectorFamily]⟩)
      · exact Submodule.smul_mem _ _
          (Submodule.subset_span ⟨1, by simp [fourVectorFamily]⟩)
    · exact Submodule.smul_mem _ _
        (Submodule.subset_span ⟨2, by simp [fourVectorFamily]⟩)
  · exact Submodule.smul_mem _ _
      (Submodule.subset_span ⟨3, by simp [fourVectorFamily]⟩)

/-- A rank-four two-form expressed as two wedges has all four displayed
vectors in its intrinsic column support. -/
theorem decomposition_vectors_mem_outside_support
    (i : Fin 9) (u z p w : LinearForm)
    (hq : targetTwo (outsideRankTwoWord i) =
      vectorWedge u z + vectorWedge p w) :
    u ∈ twoFormSupport (targetTwo (outsideRankTwoWord i)) ∧
      p ∈ twoFormSupport (targetTwo (outsideRankTwoWord i)) := by
  have hle := twoFormSupport_le_fourVectorSpan
    (targetTwo (outsideRankTwoWord i)) u z p w hq
  have hdim : Module.finrank F₂ (fourVectorSpan u z p w) ≤
      Module.finrank F₂
        (twoFormSupport (targetTwo (outsideRankTwoWord i))) := by
    rw [outsideSupport_finrank]
    exact fourVectorSpan_finrank_le u z p w
  have heq : twoFormSupport (targetTwo (outsideRankTwoWord i)) =
      fourVectorSpan u z p w :=
    Submodule.eq_of_le_of_finrank_le hle hdim
  constructor
  · rw [heq]
    exact Submodule.subset_span ⟨0, by simp [fourVectorFamily]⟩
  · rw [heq]
    exact Submodule.subset_span ⟨2, by simp [fourVectorFamily]⟩

/-- Locate either first-jet tangent at a rational place in the outside-target table. -/
def outsideTangentIndex (theta : Fin 3) (eps : F₂) : Fin 9 :=
  ![![0, 1], ![2, 3], ![4, 5]] theta (if eps = 0 then 0 else 1)

theorem outsideWord_tangent (theta : Fin 3) (eps : F₂) :
    outsideRankTwoWord (outsideTangentIndex theta eps) =
      rationalTangentAt theta eps := by
  fin_cases theta <;> rcases f2_eq_zero_or_one eps with rfl | rfl <;>
    decide


/-- A nonzero vector from a rational-place plane can occur in an outside
rank-two support only for one of the two tangent words at that place. -/
theorem nonzero_place_vector_classifies_outside_support :
    ∀ (theta : Fin 3) (a b : F₂) (i : Fin 9) (coeff : Fin 4 → F₂),
      (a ≠ 0 ∨ b ≠ 0) →
      quarticSupportVector theta a b =
        ∑ k : Fin 4, coeff k • outsideSelectedColumn i k →
      ∃ eps : F₂, i = outsideTangentIndex theta eps := by
  decide


/-- A vector supported on the first two coefficients of each input polynomial. -/
@[expose] def normalizedFirstJetVector (pa pb ja jb : F₂) : LinearForm :=
  ![pa, ja, 0, 0, pb, jb, 0, 0]

theorem normalizedFirstJetVector_eq (pa pb ja jb : F₂) :
    normalizedFirstJetVector pa pb ja jb =
      pa • aLinear 0 + pb • bLinear 0 +
        ja • aLinear 1 + jb • bLinear 1 := by
  funext i
  fin_cases i <;>
    simp [normalizedFirstJetVector, aLinear, bLinear, aCoord, bCoord, Pi.basisFun]

/-- After place normalization, the vector has first-jet support and a nonzero jet component. -/
@[expose]
def InNormalizedFirstJet (theta : Fin 3) (u : LinearForm) : Prop :=
  ∃ pa pb ja jb : F₂,
    normalizePlaceLinear theta u = normalizedFirstJetVector pa pb ja jb ∧
    (ja ≠ 0 ∨ jb ≠ 0)


private def tangentSupportCombination
    (theta : Fin 3) (eps : F₂) (coeff : Fin 4 → F₂) : LinearForm :=
  ∑ k : Fin 4,
    coeff k • outsideSelectedColumn (outsideTangentIndex theta eps) k

/-- Check a fixed rational-place tangent on the sixteen coefficient vectors. -/
macro (name := solveTangentSupportCertificate) "solve_tangent_support_certificate" : tactic =>
  `(tactic|
    (intro coeff
     rcases f2_eq_zero_or_one (coeff 0) with h0 | h0 <;>
       rcases f2_eq_zero_or_one (coeff 1) with h1 | h1 <;>
       rcases f2_eq_zero_or_one (coeff 2) with h2 | h2 <;>
       rcases f2_eq_zero_or_one (coeff 3) with h3 | h3
     all_goals
       have hcoeff : coeff = ![coeff 0, coeff 1, coeff 2, coeff 3] := by
         funext k
         fin_cases k <;> rfl
       rw [hcoeff]
       simp only [h0, h1, h2, h3]
       unfold InNormalizedFirstJet tangentSupportCombination
       decide))

/- Splitting this fixed six-point calculation keeps each kernel reduction
small.  Each certificate ranges over only the sixteen vectors in `F₂⁴`. -/
private theorem tangent_support_zero_zero :
    ∀ coeff : Fin 4 → F₂,
      vectorWedgeTwo (tangentSupportCombination 0 0 coeff)
          (rationalTwo (rationalSingleton 0)) ≠ 0 →
      InNormalizedFirstJet 0 (tangentSupportCombination 0 0 coeff) := by
  solve_tangent_support_certificate

private theorem tangent_support_zero_one :
    ∀ coeff : Fin 4 → F₂,
      vectorWedgeTwo (tangentSupportCombination 0 1 coeff)
          (rationalTwo (rationalSingleton 0)) ≠ 0 →
      InNormalizedFirstJet 0 (tangentSupportCombination 0 1 coeff) := by
  solve_tangent_support_certificate

private theorem tangent_support_one_zero :
    ∀ coeff : Fin 4 → F₂,
      vectorWedgeTwo (tangentSupportCombination 1 0 coeff)
          (rationalTwo (rationalSingleton 1)) ≠ 0 →
      InNormalizedFirstJet 1 (tangentSupportCombination 1 0 coeff) := by
  solve_tangent_support_certificate

private theorem tangent_support_one_one :
    ∀ coeff : Fin 4 → F₂,
      vectorWedgeTwo (tangentSupportCombination 1 1 coeff)
          (rationalTwo (rationalSingleton 1)) ≠ 0 →
      InNormalizedFirstJet 1 (tangentSupportCombination 1 1 coeff) := by
  solve_tangent_support_certificate

private theorem tangent_support_two_zero :
    ∀ coeff : Fin 4 → F₂,
      vectorWedgeTwo (tangentSupportCombination 2 0 coeff)
          (rationalTwo (rationalSingleton 2)) ≠ 0 →
      InNormalizedFirstJet 2 (tangentSupportCombination 2 0 coeff) := by
  solve_tangent_support_certificate

private theorem tangent_support_two_one :
    ∀ coeff : Fin 4 → F₂,
      vectorWedgeTwo (tangentSupportCombination 2 1 coeff)
          (rationalTwo (rationalSingleton 2)) ≠ 0 →
      InNormalizedFirstJet 2 (tangentSupportCombination 2 1 coeff) := by
  solve_tangent_support_certificate

/-- The support calculation also recovers the nonzero first-jet component of
the seed linear form after normalizing its rational place to zero. -/
theorem tangent_support_normalizes_firstJet :
    ∀ (theta : Fin 3) (eps : F₂) (coeff : Fin 4 → F₂),
      vectorWedgeTwo
          (∑ k : Fin 4,
            coeff k • outsideSelectedColumn (outsideTangentIndex theta eps) k)
          (rationalTwo (rationalSingleton theta)) ≠ 0 →
      InNormalizedFirstJet theta
        (∑ k : Fin 4,
          coeff k • outsideSelectedColumn (outsideTangentIndex theta eps) k) := by
  intro theta eps coeff
  change
    vectorWedgeTwo (tangentSupportCombination theta eps coeff)
        (rationalTwo (rationalSingleton theta)) ≠ 0 →
      InNormalizedFirstJet theta (tangentSupportCombination theta eps coeff)
  fin_cases theta <;> rcases f2_eq_zero_or_one eps with rfl | rfl
  · exact tangent_support_zero_zero coeff
  · exact tangent_support_zero_one coeff
  · exact tangent_support_one_zero coeff
  · exact tangent_support_one_one coeff
  · exact tangent_support_two_zero coeff
  · exact tangent_support_two_one coeff


theorem rationalTwo_singleton (theta : Fin 3) :
    rationalTwo (rationalSingleton theta) = rationalPlaceTwo theta := by
  fin_cases theta <;> decide

/-- The equal-singleton branch of the low--low collision is exactly a first
Hasse jet.  This is the algebraic content of Proposition `firstjet` after the
common rational place has been identified. -/
theorem same_singleton_collision_firstJet
    (theta : Fin 3) (N N' z w : LinearForm)
    (gamma : Fin 3 → F₂) (c : TargetCoeff)
    (hcubicNonzero :
      vectorWedgeTwo N (rationalTwo (rationalSingleton theta)) ≠ 0)
    (hsum : InPlaceSupport theta (N + N'))
    (htargetNonrational : ¬ IsRationalCoeff c)
    (htarget : targetTwo c = rationalTwo gamma +
      vectorWedge z N + vectorWedge w N') :
    ∃ eps : F₂,
      c + rationalCoeffRep gamma = rationalTangentAt theta eps ∧
      InNormalizedFirstJet theta N := by
  let p : LinearForm := N + N'
  have hp : p ≠ 0 := by
    intro hpzero
    have hNN' : N = N' := by
      funext i
      have hi := congrFun hpzero i
      exact (add_eq_zero_iff_eq_neg.mp hi).trans (neg_eq_self_f2 _)
    apply htargetNonrational
    rw [hNN'] at htarget
    exact target_rational_of_same_second_wedge htarget
  let delta : TargetCoeff := c + rationalCoeffRep gamma
  have hdelta : targetTwo delta =
      vectorWedge N (z + w) + vectorWedge p w := by
    rw [show targetTwo delta = targetTwo c +
      targetTwo (rationalCoeffRep gamma) by
        exact targetTwoLinear.map_add _ _]
    rw [targetTwo_rationalCoeffRep, htarget]
    dsimp [p]
    funext i j
    simp only [Pi.add_apply, vectorWedge]
    ring_nf
    simp [N3Certificate.two_eq_zero_f2]
  have hdeltaRank : HankelRankLETwo delta :=
    target_sum_two_decomposable_rankTwo hdelta
  have hdeltaNonrational : ¬ IsRationalCoeff delta := by
    intro hrat
    rcases (IsRationalCoeff_iff delta).mp hrat with ⟨eta, heta⟩
    apply htargetNonrational
    apply (IsRationalCoeff_iff c).mpr
    refine ⟨eta + gamma, ?_⟩
    rw [rationalCoeffRep_add, ← heta]
    dsimp [delta]
    funext i
    simp only [Pi.add_apply]
    ring_nf
    simp [N3Certificate.two_eq_zero_f2]
  have hdeltaNonzero : delta ≠ 0 := by
    intro hz
    apply hdeltaNonrational
    rw [hz]
    exact ⟨0, 0, 0, by simp⟩
  rcases (outside_rankTwo_classification delta).mp
      ⟨hdeltaRank, hdeltaNonzero, hdeltaNonrational⟩ with ⟨i, hi⟩
  have houtside : targetTwo (outsideRankTwoWord i) =
      vectorWedge N (z + w) + vectorWedge p w := by
    rw [← hi]
    exact hdelta
  rcases decomposition_vectors_mem_outside_support
      i N (z + w) p w houtside with ⟨hNsupport, hpsupport⟩
  have hpSelected : p ∈
      Submodule.span F₂ (Set.range (outsideSelectedColumn i)) := by
    rwa [outsideSupport_eq_selectedSpan] at hpsupport
  rcases (Submodule.mem_span_range_iff_exists_fun (R := F₂)
      (v := outsideSelectedColumn i) (x := p)).mp hpSelected with
    ⟨pcoeff, hpcoeff⟩
  rcases hsum with ⟨a, b, hpPlace⟩
  have hab : a ≠ 0 ∨ b ≠ 0 := by
    by_cases ha : a = 0
    · by_cases hb : b = 0
      · exfalso
        apply hp
        dsimp [p]
        rw [hpPlace, ha, hb]
        simp
      · exact Or.inr hb
    · exact Or.inl ha
  have hpRep : quarticSupportVector theta a b =
      ∑ k : Fin 4, pcoeff k • outsideSelectedColumn i k := by
    rw [quarticSupportVector, ← hpPlace]
    exact hpcoeff.symm
  rcases nonzero_place_vector_classifies_outside_support
      theta a b i pcoeff hab hpRep with ⟨eps, hiTangent⟩
  subst i
  have hNSelected : N ∈ Submodule.span F₂
      (Set.range (outsideSelectedColumn (outsideTangentIndex theta eps))) := by
    rwa [outsideSupport_eq_selectedSpan] at hNsupport
  rcases (Submodule.mem_span_range_iff_exists_fun (R := F₂)
      (v := outsideSelectedColumn (outsideTangentIndex theta eps))
      (x := N)).mp hNSelected with ⟨ncoeff, hncoeff⟩
  have hnCubic : vectorWedgeTwo
      (∑ k : Fin 4,
        ncoeff k • outsideSelectedColumn (outsideTangentIndex theta eps) k)
      (rationalTwo (rationalSingleton theta)) ≠ 0 := by
    rw [hncoeff]
    exact hcubicNonzero
  refine ⟨eps, hi.trans (outsideWord_tangent theta eps), ?_⟩
  have hnormal := tangent_support_normalizes_firstJet
    theta eps ncoeff hnCubic
  rwa [hncoeff] at hnormal

/-- The exterior first-jet normal form with a nonzero seed cubic and a non-rational target. -/
def ExteriorFirstJetNormalForm : Prop :=
  ∃ (theta : Fin 3) (eps : F₂) (seedLinear : LinearForm)
    (rationalCoeff : Fin 3 → F₂) (targetCoeff : TargetCoeff),
    vectorWedgeTwo seedLinear (rationalTwo (rationalSingleton theta)) ≠ 0 ∧
    ¬ IsRationalCoeff targetCoeff ∧
    targetCoeff + rationalCoeffRep rationalCoeff =
      rationalTangentAt theta eps ∧
    InNormalizedFirstJet theta seedLinear

/-- Classify a reduced collision without discarding its coefficient and linear witnesses. -/
theorem exteriorFirstJetReducedCollision_classification
    {seedCoeff childCoeff rationalCoeff : Fin 3 → F₂}
    {seedLinear seedCompanion childLinear childCompanion : LinearForm}
    {targetCoeff : TargetCoeff}
    (hseedCoeff : seedCoeff ≠ 0) (hchildCoeff : childCoeff ≠ 0)
    (hcubicNonzero : vectorWedgeTwo seedLinear (rationalTwo seedCoeff) ≠ 0)
    (hcubic : vectorWedgeTwo seedLinear (rationalTwo seedCoeff) =
      vectorWedgeTwo childLinear (rationalTwo childCoeff))
    (htargetNonrational : ¬ IsRationalCoeff targetCoeff)
    (htarget : targetTwo targetCoeff = rationalTwo rationalCoeff +
      vectorWedge seedCompanion seedLinear + vectorWedge childCompanion childLinear) :
    ∃ (theta : Fin 3) (eps : F₂),
      seedCoeff = rationalSingleton theta ∧ childCoeff = rationalSingleton theta ∧
      vectorWedgeTwo seedLinear (rationalTwo (rationalSingleton theta)) ≠ 0 ∧
      targetCoeff + rationalCoeffRep rationalCoeff = rationalTangentAt theta eps ∧
      InNormalizedFirstJet theta seedLinear := by
  rcases cubic_collision_forces_common_singleton
      seedCoeff childCoeff seedLinear childLinear
      seedCompanion childCompanion rationalCoeff targetCoeff
      hseedCoeff hchildCoeff hcubic htargetNonrational htarget with
    ⟨theta, hseedSingleton, hchildSingleton⟩
  rw [hseedSingleton] at hcubicNonzero hcubic
  rw [hchildSingleton] at hcubic
  have hsum := cubic_equal_support_relation
    (rationalSingleton theta) (rationalSingleton theta)
    seedLinear childLinear hcubic theta
  have hsum' : InPlaceSupport theta (seedLinear + childLinear) := by
    simpa [rationalSingleton_apply_self] using hsum
  rcases same_singleton_collision_firstJet theta
      seedLinear childLinear seedCompanion childCompanion
      rationalCoeff targetCoeff hcubicNonzero hsum'
      htargetNonrational htarget with ⟨eps, hdelta, hnormal⟩
  exact ⟨theta, eps, hseedSingleton, hchildSingleton, hcubicNonzero, hdelta, hnormal⟩

/-- Circuit-independent endpoint of the first low-low feedback analysis. -/
theorem exteriorFirstJetReducedCollision_normalForm
    (h : ExteriorFirstJetReducedCollision) : ExteriorFirstJetNormalForm := by
  rcases h with
    ⟨seedCoeff, childCoeff, rationalCoeff,
      seedLinear, seedCompanion, childLinear, childCompanion, targetCoeff,
      hseedCoeff, hchildCoeff, hcubicNonzero, hcubic,
      htargetNonrational, htarget⟩
  rcases exteriorFirstJetReducedCollision_classification
      hseedCoeff hchildCoeff hcubicNonzero hcubic htargetNonrational htarget with
    ⟨theta, eps, _hseedSingleton, _hchildSingleton, hnonzero, hdelta, hnormal⟩
  exact ⟨theta, eps, seedLinear, rationalCoeff, targetCoeff,
    hnonzero, htargetNonrational, hdelta, hnormal⟩

theorem NormalizedEight.exteriorFirstJetNormalForm
    {C : Circuit 8 8} (h : NormalizedEight C) :
    ExteriorFirstJetNormalForm :=
  exteriorFirstJetReducedCollision_normalForm
    (exteriorFirstJetCollision_reduced h.exteriorFirstJetCollision)

/-- The full ANF target normal form associated with a first-jet seed. -/
@[expose]
def FirstJetTargetNormalForm
    (g target targetAffine : ANF 8) (targetCoeff : TargetCoeff) : Prop :=
  ∃ (theta : Fin 3) (eps : F₂)
    (seedLinear seedCompanion : LinearForm) (seedRho : F₂)
    (rationalCoeff : Fin 3 → F₂),
    targetAffine ∈ affine 8 ∧
    target = targetAffine + targetANF targetCoeff ∧
    anfThreeProjection g =
      vectorWedgeTwo seedLinear (rationalTwo (rationalSingleton theta)) ∧
    anfTwoProjection g =
      seedRho • rationalTwo (rationalSingleton theta) +
        vectorWedge seedCompanion seedLinear +
        booleanContraction seedLinear
          (rationalTwo (rationalSingleton theta)) ∧
    vectorWedgeTwo seedLinear (rationalTwo (rationalSingleton theta)) ≠ 0 ∧
    targetCoeff + rationalCoeffRep rationalCoeff =
      rationalTangentAt theta eps ∧
    InNormalizedFirstJet theta seedLinear

/-- Correlated version of the first-jet theorem: the tangent classification
belongs to the particular target witness appearing in the low--low
collision, not merely to an unrelated existential representative. -/
theorem cubicLowLowNormalCollisionAt_targetNormalForm
    {g target targetAffine : ANF 8} {targetCoeff : TargetCoeff}
    (h : CubicLowLowNormalCollisionAt g target targetAffine targetCoeff) :
    FirstJetTargetNormalForm g target targetAffine targetCoeff := by
  rcases cubicLowLowNormalCollisionAt_exterior h with
    ⟨htargetAffine, htargetRep, seedCoeff, childCoeff, lowCoeff,
      seedLinear, seedCompanion, childLinear, childCompanion, seedRho, childRho,
      hseedCoeff, hchildCoeff, hgCubic, hgQuadratic, hgCubicNonzero,
      hcubic, htargetNonrational, hquadratic⟩
  rcases exteriorFirstJetCollision_reduce_quadratic hcubic hquadratic with
    ⟨rationalCoeff, htargetReduced⟩
  rcases exteriorFirstJetReducedCollision_classification
      hseedCoeff hchildCoeff hgCubicNonzero hcubic htargetNonrational htargetReduced with
    ⟨theta, eps, hseedSingleton, _hchildSingleton, hnonzero, hdelta, hnormal⟩
  rw [hseedSingleton] at hgCubic hgQuadratic
  exact ⟨theta, eps, seedLinear, seedCompanion, seedRho, rationalCoeff,
    htargetAffine, htargetRep, hgCubic, hgQuadratic, hnonzero, hdelta, hnormal⟩

theorem cubicLowLowNormalCollision_targetNormalForm
    {g : ANF 8} (h : CubicLowLowNormalCollision g) :
    ∃ (target targetAffine : ANF 8) (targetCoeff : TargetCoeff),
      FirstJetTargetNormalForm g target targetAffine targetCoeff := by
  rcases h with ⟨target, targetAffine, targetCoeff, hAt⟩
  exact ⟨target, targetAffine, targetCoeff,
    cubicLowLowNormalCollisionAt_targetNormalForm hAt⟩

end

end N4
end UnrestrictedBooleanMul
