/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/

import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.AlgebraicIndependence
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.BerarducciPrimitives
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.ComplexityDecrease
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.Convolution
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.ConvolutionList
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.ConvolutionRemainder
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.CriticalPoint
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.OrdinalValueFinalSegment
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.OrdinalValueSubmultiplicative
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.PrincipalComponent
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.PrincipalComponentDegree
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.PrincipalComponentTensor
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.PrincipalSubring
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.PrincipalSubringFiniteSupport
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.PrincipalSubringFraction
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.PrincipalSubringTensor
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.PrincipalValue
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.ResidualPoint
import LeanPool.ConwayRefinement.ConwayRefinement.HahnSeries.OrdinalValue.Tests.SectionSixThree

/-! Supporting modules for Conway refinement for omnific integers. -/
