/-
Copyright (c) 2026 William Whistler. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Whistler
-/

import LeanPool.RegtsSevenster.RS.Classical.Deligne.UnitFreeMod
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistFreeTensor
import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZigzagTransferIso
import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorZigzag
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeTransport
import LeanPool.RegtsSevenster.RS.Classical.Deligne.InitDatum
import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddLinePairing
import LeanPool.RegtsSevenster.RS.Classical.Deligne.BigTensor

/-!
# The odd twist of a duality datum

A self-dual object of the ambient category makes the free module
it generates self-dual over any commutative base: the duality
datum over the trivial base is carried onto the free module and
then base-changed, and both steps preserve the zigzag laws.  For
an odd line the self-duality is the square trivialisation, so
tensoring a duality datum with the line datum and transporting
along the twist shuffle gives the odd twist of a duality datum,
zigzag laws included.
-/

namespace RS

open CategoryTheory MonoidalCategory Limits
open scoped MonObj

universe v u

variable {D : Type u}

section SelfDual

/-- The self-duality datum over the trivial base, carried onto
the free module of the trivial base. -/
noncomputable def unitFreeDatum
    [Category.{v} D] [MonoidalCategory D] [SymmetricCategory D]
    [HasCoequalizers D]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorLeft Z)]
    (V : D) [ExactPairing V V] :
    ModDualityDatum (𝟙_ D) (freeMod (𝟙_ D) V)
      (freeMod (𝟙_ D) V) :=
  (unitBaseDatum V V).transferIso (𝟙_ D)
    (unitFreeIso V).symm (unitFreeIso V).symm

/-- The carried datum satisfies the zigzag laws. -/
theorem unitFreeDatum_zigzag
    [Category.{v} D] [MonoidalCategory D] [SymmetricCategory D]
    [Preadditive D] [MonoidalPreadditive D] [HasFiniteBiproducts D]
    [HasCoequalizers D]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorLeft Z)]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorRight Z)]
    (V : D) [ExactPairing V V] :
    ModZigzagDatum (𝟙_ D) (unitFreeDatum V) :=
  modZigzagDatum_transferIso (𝟙_ D) (unitBaseDatum V V)
    (unitFreeIso V).symm (unitFreeIso V).symm
    (unitBaseDatum_zigzag V V)

/-- **The free module on a self-dual object is self-dual** over
any commutative base. -/
noncomputable def freeSelfDatum
    [Category.{v} D] [MonoidalCategory D] [SymmetricCategory D]
    [HasCoequalizers D]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorLeft Z)]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorRight Z)]
    (A : D) [MonObj A] [IsCommMonObj A] (V : D) [ExactPairing V V] :
    ModDualityDatum A (freeMod A V) (freeMod A V) :=
  (baseChangeDatum (𝟙_ D) A η[A] (unitFreeDatum V)).transferIso A
    (baseChangeFreeIso (𝟙_ D) A η[A] V).symm
    (baseChangeFreeIso (𝟙_ D) A η[A] V).symm

/-- The free self-duality datum satisfies the zigzag laws. -/
theorem freeSelfDatum_zigzag
    [Category.{v} D] [MonoidalCategory D] [SymmetricCategory D]
    [Preadditive D] [MonoidalPreadditive D] [HasFiniteBiproducts D]
    [HasCoequalizers D]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorLeft Z)]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorRight Z)]
    (A : D) [MonObj A] [IsCommMonObj A] (V : D) [ExactPairing V V] :
    ModZigzagDatum A (freeSelfDatum A V) :=
  modZigzagDatum_transferIso A
    (baseChangeDatum (𝟙_ D) A η[A] (unitFreeDatum V))
    (baseChangeFreeIso (𝟙_ D) A η[A] V).symm
    (baseChangeFreeIso (𝟙_ D) A η[A] V).symm
    (baseChangeZigzag D (𝟙_ D) _ _ (freeMod (𝟙_ D) V)
      (freeMod (𝟙_ D) V) (unitFreeDatum V)
      (unitFreeDatum_zigzag V) A _ _ η[A] _)

end SelfDual

section Twist

/-- **The line datum**: the module generated by the odd line is
self-dual over any commutative base. -/
noncomputable def lineDatum
    [Category.{v} D] [MonoidalCategory D] [SymmetricCategory D]
    [Preadditive D] [MonoidalPreadditive D] [HasCoequalizers D]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorLeft Z)]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorRight Z)]
    (A : D) [MonObj A] [IsCommMonObj A] (L : OddLine D) :
    ModDualityDatum A (freeMod A L.obj) (freeMod A L.obj) :=
  letI := L.exactPairing
  freeSelfDatum A L.obj

/-- The line datum satisfies the zigzag laws. -/
theorem lineDatum_zigzag
    [Category.{v} D] [MonoidalCategory D] [SymmetricCategory D]
    [Preadditive D] [MonoidalPreadditive D] [HasFiniteBiproducts D]
    [HasCoequalizers D]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorLeft Z)]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorRight Z)]
    (A : D) [MonObj A] [IsCommMonObj A] (L : OddLine D) :
    ModZigzagDatum A (lineDatum A L) :=
  letI := L.exactPairing
  freeSelfDatum_zigzag A L.obj

/-- **The odd twist of a duality datum**: tensor with the line
datum and transport along the twist shuffle. -/
noncomputable def twistDatum
    [Category.{v} D] [MonoidalCategory D] [SymmetricCategory D]
    [Preadditive D] [MonoidalPreadditive D] [HasCoequalizers D]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorLeft Z)]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorRight Z)]
    (A : D) [MonObj A] [IsCommMonObj A] (L : OddLine D) {M : Mod D A}
    {M' : Mod D A}
    (d : ModDualityDatum A M M') :
    ModDualityDatum A (tensorLeftMod A L.obj M)
      (tensorLeftMod A L.obj M') :=
  (tensorDatum A (lineDatum A L) d).transferIso A
    (freeTensorTwistIso A L.obj M).symm
    (freeTensorTwistIso A L.obj M').symm

/-- **The odd twist preserves the zigzag laws.** -/
theorem twistDatum_zigzag
    [Category.{v} D] [MonoidalCategory D] [SymmetricCategory D]
    [Preadditive D] [MonoidalPreadditive D] [HasFiniteBiproducts D]
    [HasCoequalizers D]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorLeft Z)]
    [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair (tensorRight Z)]
    (A : D) [MonObj A] [IsCommMonObj A] (L : OddLine D) {M : Mod D A}
    {M' : Mod D A}
    (d : ModDualityDatum A M M')
    (hz : ModZigzagDatum A d) :
    ModZigzagDatum A (twistDatum A L d) :=
  modZigzagDatum_transferIso A (tensorDatum A (lineDatum A L) d)
    (freeTensorTwistIso A L.obj M).symm
    (freeTensorTwistIso A L.obj M').symm
    (tensorDatum_zigzag A (lineDatum A L) d
      (lineDatum_zigzag A L) hz)

end Twist

end RS
