/-
Copyright (c) 2026 Arthur Freitas Ramos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Arthur Freitas Ramos
-/
module

public import LeanPool.StallingsFolding.Flower

/-!
# Verified witness for the Challenge

The witness is the folded automaton returned by `foldWords`. The main theorem
of the implementation proves its based-loop subgroup is precisely the
subgroup generated by the input list.
-/

@[expose] public section

namespace Stallings

/-- This definition repeats the Challenge's self-contained transition-table
specification. Its value is selected by Comparator along with the theorem. -/
def completeStatement (S : List (List (Fin 2 × Bool))) : Prop :=
  ∃ (V : Type) (_ : Fintype V) (base : V)
    (next : V → (Fin 2 × Bool) → Option V),
    (∀ v x w, next v x = some w → next w (x.1, !x.2) = some v) ∧
    ∀ g : FreeGroup (Fin 2),
      (let run : List (Fin 2 × Bool) → Option V := fun word =>
        word.foldl (fun state letter =>
          state.bind fun vertex => next vertex letter) (some base)
       run (FreeGroup.toWord g) = some base) ↔
        g ∈ Subgroup.closure
          (Set.range fun i : Fin S.length => FreeGroup.mk (S.get i))

private theorem foldlRun_none {V : Type*} (G : InverseAutomaton V) (w : Word) :
    w.foldl (fun state letter => state.bind fun vertex => G.next vertex letter)
      none = none := by
  induction w with
  | nil => rfl
  | cons x xs ih => simp [List.foldl_cons, ih]

private theorem foldl_run_eq {V : Type*} (G : InverseAutomaton V) (v : V)
    (w : Word) :
    w.foldl (fun state letter => state.bind fun vertex => G.next vertex letter)
      (some v) = G.run v w := by
  induction w generalizing v with
  | nil => rfl
  | cons x xs ih =>
      cases hnext : G.next v x with
      | none => simp [List.foldl_cons, hnext, InverseAutomaton.run, foldlRun_none]
      | some u =>
          simpa [List.foldl_cons, hnext, InverseAutomaton.run] using ih (v := u)

/-- The constructive finite-recognizer result, witnessed by the computed fold. -/
theorem folded_recognizer_exists (S : List (List (Fin 2 × Bool))) :
    completeStatement S := by
  classical
  unfold completeStatement
  refine ⟨FlowerVertex S, inferInstance, (foldWords S).base, (foldWords S).next,
    ?_, ?_⟩
  · intro v x w h
    simpa [letterInv] using (foldWords S).inverse_next h
  · intro g
    change (FreeGroup.toWord g).foldl
        (fun state letter => state.bind fun vertex => (foldWords S).next vertex letter)
        (some (foldWords S).base) = some (foldWords S).base ↔
      g ∈ generatorSubgroup S
    rw [foldl_run_eq (foldWords S) (foldWords S).base (FreeGroup.toWord g)]
    have hcorrect := InverseAutomaton.accepts_iff_mem_loopSubgroup (foldWords S) g
    have hrun : (foldWords S).run (foldWords S).base (FreeGroup.toWord g) =
        some (foldWords S).base ↔ g ∈ (foldWords S).loopSubgroup := by
      simpa [InverseAutomaton.accepts] using hcorrect
    rw [foldWords_loopSubgroup_eq_generatorSubgroup] at hrun
    exact hrun

end Stallings
