/-
Copyright (c) 2026 Jack McKoen. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jack McKoen
-/
import Mathlib.CategoryTheory.SmallObject.TransfiniteCompositionLifting
import Mathlib.SetTheory.Cardinal.Order
import Mathlib.CategoryTheory.SmallObject.Basic
import LeanPool.Quasicategory.PushoutProduct.Basic

universe w v u

namespace CategoryTheory

variable {C : Type u} [Category.{v} C]

namespace MorphismProperty

variable (T : MorphismProperty C)

inductive Morphism {X Y : C} (p : X ⟶ Y) : {A B : C} → (A ⟶ B) → Prop
  | mk : (Morphism p) p

section Morphism

variable {X Y : C} (p : X ⟶ Y)

/-- the class of a single morphism `p`. -/
def morphism : MorphismProperty C := fun _ _ i ↦ (Morphism p) i

/-- a morphism `p` has rlp wrt a class `T` of morphisms iff every morphism in `T` has llp wrt `p`. -/
lemma morphism_rlp_iff : T.rlp p ↔ T ≤ (morphism p).llp :=
  ⟨fun hp _ _ _ hi _ _ _ ⟨⟩ ↦ hp _ hi, fun h _ _ i hi ↦ h i hi _ .mk⟩

lemma morphism_llp_iff : T.llp p ↔ T ≤ (morphism p).rlp :=
  ⟨fun hp _ _ _ hi _ _ _ ⟨⟩ ↦ hp _ hi, fun h _ _ i hi ↦ h i hi _ .mk⟩

lemma morphism_le_iff : morphism p ≤ T ↔ T p :=
  ⟨fun h ↦ h _ .mk, fun h _ _ _ ⟨⟩ ↦ h⟩

end Morphism

section LiftingProperty

open Limits

variable {X Y : C} {p : X ⟶ Y}

variable [HasInitial C] [InitialMonoClass C]

@[simp]
noncomputable
def _root_.CategoryTheory.HasLiftingProperty.section_of_initial_to_left
    (h : HasLiftingProperty (initial.to Y) p) : Y ⟶ X :=
  (h.sq_hasLift (CommSq.mk (initial.hom_ext (initial.to X ≫ p) (initial.to Y ≫ 𝟙 Y)))).exists_lift.some.l

noncomputable
instance splitEpi_of_monomorphisms_rlp
    (hp : (monomorphisms C).rlp p) : SplitEpi p where
  section_ := (hp _ (initial.mono_from _ _)).section_of_initial_to_left
  id := CategoryTheory.CommSq.LiftStruct.fac_right _

end LiftingProperty

section Saturated

class Saturated : Prop where
  IsStableUnderCobaseChange : T.IsStableUnderCobaseChange
  IsStableUnderRetracts : T.IsStableUnderRetracts
  IsStableUnderCoproducts : IsStableUnderCoproducts.{w} T
  IsStableUnderTransfiniteComposition : IsStableUnderTransfiniteComposition.{w} T

instance [h : T.Saturated] : T.IsStableUnderCobaseChange :=
  h.IsStableUnderCobaseChange

instance [h : T.Saturated] : T.IsStableUnderRetracts :=
  h.IsStableUnderRetracts

instance [h : Saturated.{w} T] : IsStableUnderTransfiniteComposition.{w} T :=
  h.IsStableUnderTransfiniteComposition

instance [h : Saturated.{w} T] : IsStableUnderCoproducts.{w} T :=
  h.IsStableUnderCoproducts

instance llp_isSaturated : Saturated T.llp :=
  ⟨T.llp_isStableUnderCobaseChange, T.llp_isStableUnderRetracts, ⟨T.llp_isStableUnderCoproductsOfShape⟩, ⟨T.isStableUnderTransfiniteCompositionOfShape_llp⟩⟩

/-- weakly saturated classes contain all isomorphisms. -/
lemma Saturated.isomorphisms_le [Saturated T] :
    isomorphisms C ≤ T := fun _ _ p hp ↦
  letI : IsIso p := hp
  Saturated.IsStableUnderCobaseChange.of_isPushout (IsPushout.of_vert_isIso ⟨rfl⟩) (ContainsIdentities.id_mem _)

open Limits in
/-- inductive type defining the saturated class generated by a morphism property -/
inductive SaturatedClass (T : MorphismProperty C) : {X Y : C} → (X ⟶ Y) → Prop
  | of ⦃X Y : C⦄ (f : X ⟶ Y) (h : T f) : SaturatedClass T f
  | pushout ⦃X Y Z W : C⦄ ⦃f : X ⟶ Y⦄ ⦃g : X ⟶ Z⦄ ⦃inl : Z ⟶ W⦄ ⦃inr : Y ⟶ W⦄ (_ : IsPushout g f inl inr) : SaturatedClass T f → SaturatedClass T inl
  | retract ⦃X Y Z W : C⦄ ⦃f : X ⟶ Y⦄ ⦃g : Z ⟶ W⦄ (_ : RetractArrow f g) : SaturatedClass T g → SaturatedClass T f
  | coproduct (J : Type w) (X₁ X₂ : Discrete J ⥤ C) (c₁ : Cocone X₁) (c₂ : Cocone X₂) (h₁ : IsColimit c₁) (_ : IsColimit c₂)
      (f : X₁ ⟶ X₂) : (_ : ∀ (j : Discrete J), (SaturatedClass T) (f.app j)) → SaturatedClass T (h₁.desc (Cocone.mk _ (f ≫ c₂.ι)))
  | transfinite (J : Type w) [LinearOrder J] [SuccOrder J] [OrderBot J] [WellFoundedLT J]
      {X Y : C} (f : X ⟶ Y) (hf : CategoryTheory.TransfiniteCompositionOfShape J f) :
        (∀ (j : J), (hj : ¬IsMax j) → SaturatedClass T (hf.F.map (homOfLE (Order.le_succ j)))) → SaturatedClass T f

/-- the weakly saturated class generated by a morphism property. -/
def saturation : MorphismProperty C := fun _ _ f ↦ SaturatedClass.{w} T f

-- do galois connection, galois insertion

instance (T : MorphismProperty C) : Saturated.{w} (saturation.{w} T) where
  IsStableUnderCobaseChange := ⟨fun h hf ↦ .pushout h hf⟩
  IsStableUnderRetracts := ⟨fun h hf ↦ .retract h hf⟩
  IsStableUnderCoproducts := ⟨fun J _ _ _ _ _ h₂ f hf ↦
    .coproduct J _ _ _ _ _ h₂ f hf⟩
  IsStableUnderTransfiniteComposition := ⟨fun J _ _ _ _ ↦
    ⟨fun _ _ f hf ↦ .transfinite J f _ hf.some.map_mem⟩⟩

lemma le_saturation : T ≤ T.saturation := .of

lemma Saturated.le_iff (S : MorphismProperty C) [Saturated.{w} S] : T ≤ S ↔ (saturation.{w} T) ≤ S := by
  constructor
  · intro h _ _ f hf
    induction hf with
    | of f hf => exact h _ hf
    | pushout h _ hf => exact Saturated.IsStableUnderCobaseChange.of_isPushout h hf
    | retract h _ hf => exact Saturated.IsStableUnderRetracts.of_retract h hf
    | coproduct J X₁ X₂ c₁ c₂ h₁ h₂ f hf hs =>
      exact (Saturated.IsStableUnderCoproducts.isStableUnderCoproductsOfShape J).colimitsOfShape_le _ ⟨X₁, X₂, c₁, c₂, h₁, h₂, f, hs⟩
    | transfinite J f hF h' h'' =>
      exact (Saturated.IsStableUnderTransfiniteComposition.isStableUnderTransfiniteCompositionOfShape J).le _ ⟨hF, h''⟩
  · exact T.le_saturation.trans

lemma llp_rlp_eq_saturation {T : MorphismProperty C} [HasSmallObjectArgument.{w} T] :
    T.rlp.llp = saturation.{w} T := by
  apply le_antisymm
  · rw [llp_rlp_of_hasSmallObjectArgument, retracts_le_iff,
      transfiniteCompositions_le_iff, pushouts_le_iff, coproducts_le_iff]
    exact le_saturation _
  · rw [← Saturated.le_iff]
    exact T.le_llp_rlp

lemma saturation_saturation_eq {T : MorphismProperty C} :
    saturation.{w} (saturation.{w} T) = saturation.{w} T := by
  apply le_antisymm
  · rw [← Saturated.le_iff]
  · exact le_saturation _

section PushoutProduct

open PushoutProduct MonoidalCategory Limits

variable [MonoidalCategory C] [HasPushouts C]

variable {A B : C} (ι : A ⟶ B)

/-- `T.pushoutProduct ι` is the class of all morphisms `i` such that `ι □ i` is in `T`. -/
@[simp]
def pushoutProduct : MorphismProperty C := fun _ _ i ↦ T (ι □ i)

variable [∀ S : C, Limits.PreservesColimitsOfSize (tensorLeft S)]

instance [T.IsStableUnderCobaseChange] : IsStableUnderCobaseChange (T.pushoutProduct ι) where
  of_isPushout h hg := by
    dsimp
    exact IsStableUnderCobaseChange.of_isPushout (leftFunctor_map_preserves_pushouts ι h) hg

instance [T.IsStableUnderRetracts] : IsStableUnderRetracts (T.pushoutProduct ι) where
  of_retract h hg := by
    dsimp
    exact IsStableUnderRetracts.of_retract (Retract.map h (leftFunctor ι)) hg

instance [hT : RespectsIso T] : (T.pushoutProduct ι).RespectsIso where
  precomp := by
    intro X Y Z i hi f hf
    dsimp only [pushoutProduct]
    letI : IsIso (ι □ i) := sorry
    simp
    sorry
  postcomp := sorry

/-
    apply IsStableUnderCoproductsOfShape.mk
    intro X₁ X₂ hX₁ hX₂ f hf
    dsimp only [pushoutProduct] at hf ⊢
    let X₁' : J → C := fun j ↦ pushout (ι ▷ X₁ j) (A ◁ f j)
    let X₂' : J → C := fun j ↦ B ⊗ X₂ j
    let hX₁' : HasCoproduct X₁' := by
      sorry
    let hX₂' : HasCoproduct X₂' := by
      sorry
    let f' : (j : J) → X₁' j ⟶ X₂' j := fun j ↦ ι □ (f j)
    sorry
-/

instance [IsStableUnderCoproducts.{w} T] : IsStableUnderCoproducts.{w} (T.pushoutProduct ι) where
  isStableUnderCoproductsOfShape J := by

    refine (isStableUnderColimitsOfShape_iff_colimitsOfShape_le _ (Discrete J)).mpr ?_
    intro X Y f hf
    cases hf with
    | mk X₁ X₂ c₁ c₂ h₁ h₂ f hf =>
    dsimp only [pushoutProduct]
    dsimp only [MorphismProperty.functorCategory, pushoutProduct] at hf
    apply (IsStableUnderCoproducts.isStableUnderCoproductsOfShape J).colimitsOfShape_le
    let α := h₁.desc { pt := c₂.pt, ι := f ≫ c₂.ι }
    let f' := descFunctor f ι
    let c₁' := c₁' ι c₂ h₁ f
    let h₁' : Limits.IsColimit c₁' := c₁'_isColimit ι c₂ h₁ h₂ f
    let c₂' := (tensorLeft B).mapCocone c₂
    let h₂' : Limits.IsColimit c₂' := Limits.isColimitOfPreserves (tensorLeft B) h₂
    convert colimitsOfShape.mk (natTransLeftFunctor f ι) (X₂ ⋙ tensorLeft B) c₁' c₂' h₁' h₂' f' hf
    convert h₁'.uniq _ _ _
    · rfl
    · rfl
    · intro j
      dsimp only [c₁', PushoutProduct.c₁', c₂', f', descFunctor, tensorLeft, curriedTensor,
        Functor.mapCocone]
      simp [Functor.PushoutObjObj.ι]
      apply pushout.hom_ext
      · simp [← MonoidalCategory.whiskerLeft_comp]
      · simp [whisker_exchange]

open Limits in
instance [T.IsStableUnderCobaseChange] [IsStableUnderTransfiniteComposition.{w} T] : IsStableUnderTransfiniteComposition.{w} (T.pushoutProduct ι) where
  isStableUnderTransfiniteCompositionOfShape J _ _ _ _ := by
    rw [isStableUnderTransfiniteCompositionOfShape_iff.{w}]
    intro X Y f' ⟨hf⟩
    apply T.transfiniteCompositions_le
    rw [transfiniteCompositions_iff]
    refine ⟨J, _, _, _, _, ⟨(leftFunctor_preserves_transfiniteComposition J ι f' hf.1), ?_⟩⟩

    intro j hj
    dsimp only [leftFunctor_preserves_transfiniteComposition]
    exact IsStableUnderCobaseChange.of_isPushout (newPushoutIsPushout ι hf.F (Cocone.mk _ hf.incl) j) (hf.map_mem j hj)

instance [Saturated.{w} T]
      [∀ (S : C), PreservesColimitsOfSize.{w, w, v, v, u, u} (tensorLeft S)] :
    Saturated.{w} (T.pushoutProduct ι) where
  IsStableUnderCobaseChange := by infer_instance
  IsStableUnderRetracts := by infer_instance
  IsStableUnderCoproducts := by infer_instance
  IsStableUnderTransfiniteComposition := by infer_instance

end PushoutProduct

end Saturated

end MorphismProperty

end CategoryTheory
