/-
Copyright (c) 2026 Martin Dvořák. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Martin Dvořák
-/
import LeanPool.Chomsky.Classes.ContextFree.ClosureProperties.Concatenation
import LeanPool.Chomsky.Classes.ContextFree.ClosureProperties.Reverse
import LeanPool.Chomsky.Classes.ContextFree.ClosureProperties.Union
import LeanPool.Chomsky.Classes.Unrestricted.Basics.Uniqueness
import LeanPool.Chomsky.Classes.Unrestricted.ClosureProperties.Reverse
import LeanPool.Chomsky.Classes.Unrestricted.ClosureProperties.Star
import LeanPool.Chomsky.Classes.Unrestricted.NormalForms.Kuroda

/-!
# Chomsky hierarchy in Lean 4

Source: arxiv:2302.06420, url:https://github.com/madvorak/chomsky
Authors: Martin Dvořák
Status: verified
Main declarations: `Chomsky.CF_subclass_GG`, `Chomsky.GG_of_GG_u_GG`, `Chomsky.GG_of_star_GG`
Tags: formal-languages, chomsky-hierarchy, context-free-grammar, closure-properties
MSC: 68Q42
-/

/-!
A formalization of the Chomsky hierarchy of formal languages: general (unrestricted)
grammars and context-free grammars, their derivation relations, and closure properties.
It is shown that context-free languages form a subclass of the languages generated by
general grammars, and that both classes are closed under union, concatenation, and
reversal (with the class of general-grammar languages additionally closed under the
Kleene star). The Kuroda normal form for general grammars is also defined.
-/
