/-
Copyright (c) 2026 ClassificationOfSurfaces contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ryan McCorvie, Jack McCarthy
-/
module

public import LeanPool.ClassificationOfSurfaces.API
public import LeanPool.ClassificationOfSurfaces.Basic
public import LeanPool.ClassificationOfSurfaces.CanonicalCoordinates
public import LeanPool.ClassificationOfSurfaces.CanonicalGeneratorMaps
public import LeanPool.ClassificationOfSurfaces.CanonicalPairings
public import LeanPool.ClassificationOfSurfaces.CanonicalWords
public import LeanPool.ClassificationOfSurfaces.CellComplex
public import LeanPool.ClassificationOfSurfaces.CellComplexQuotient
public import LeanPool.ClassificationOfSurfaces.DiskSquare
public import LeanPool.ClassificationOfSurfaces.EvalStatement
public import LeanPool.ClassificationOfSurfaces.Examples
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicCancellation
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicCanonical
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicCanonicalRealization
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicCrosscap
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicDerivedRewrites
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicDyck
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicFaceMerge
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicMoveRealization
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicMoves
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicNormalization
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicNormalizationResult
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicP1
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicP1Realization
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicP2
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicP2DegenerateRealization
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicP2Realization
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicPresentation
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicRealization
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicReduction
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicSignedRealization
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicSphereRealization
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicTerminalNormalization
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicTriangulation
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicUnorientedRealization
public import LeanPool.ClassificationOfSurfaces.FiniteCyclicWordReduction
public import LeanPool.ClassificationOfSurfaces.GeometricTriangulationRealization
public import LeanPool.ClassificationOfSurfaces.LeanEval.ChallengeDeps
public import LeanPool.ClassificationOfSurfaces.LeanEval.RepresentativeSanity
public import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveControlledApproximation
public import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveFanAffine
public import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveFanComplex
public import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveOpenComplex
public import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveOpenCover
public import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveTileComplex
public import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveTriangulation
public import LeanPool.ClassificationOfSurfaces.Moise.AmbientHomeomorph
public import LeanPool.ClassificationOfSurfaces.Moise.Anchors
public import LeanPool.ClassificationOfSurfaces.Moise.BoundaryInvariant
public import LeanPool.ClassificationOfSurfaces.Moise.BrokenLine
public import LeanPool.ClassificationOfSurfaces.Moise.Brouwer
public import LeanPool.ClassificationOfSurfaces.Moise.ChartExtraction
public import LeanPool.ClassificationOfSurfaces.Moise.ChartInduction
public import LeanPool.ClassificationOfSurfaces.Moise.ChartPatch
public import LeanPool.ClassificationOfSurfaces.Moise.CommonSubdivision
public import LeanPool.ClassificationOfSurfaces.Moise.ConeExtension
public import LeanPool.ClassificationOfSurfaces.Moise.Countermodels
public import LeanPool.ClassificationOfSurfaces.Moise.DualConnectivity
public import LeanPool.ClassificationOfSurfaces.Moise.ElementaryMove
public import LeanPool.ClassificationOfSurfaces.Moise.EmbeddedComplexValence
public import LeanPool.ClassificationOfSurfaces.Moise.FacewiseComparison
public import LeanPool.ClassificationOfSurfaces.Moise.FineSubdivision
public import LeanPool.ClassificationOfSurfaces.Moise.FinitePLHomeomorph
public import LeanPool.ClassificationOfSurfaces.Moise.FreeTriangle
public import LeanPool.ClassificationOfSurfaces.Moise.FreeTriangleMove
public import LeanPool.ClassificationOfSurfaces.Moise.FrontierGlue
public import LeanPool.ClassificationOfSurfaces.Moise.GeometricTriangulation
public import LeanPool.ClassificationOfSurfaces.Moise.GraphPolygonalization
public import LeanPool.ClassificationOfSurfaces.Moise.GraphRefinement
public import LeanPool.ClassificationOfSurfaces.Moise.GraphSubdivision
public import LeanPool.ClassificationOfSurfaces.Moise.HalfPlanePolygon
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicCellwiseExtension
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicCloseCellwiseExtension
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicCloseGraphApproximation
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicComplex
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicFaceBoundary
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicFaceExtension
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicFaceFilling
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicFaceModel
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicFineSubdivision
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicGraphApproximation
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicGraphModel
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicGraphPL
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicMarkedFan
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicMidpointSubdivision
public import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicSubdivision
public import LeanPool.ClassificationOfSurfaces.Moise.LineSubdivision
public import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteCellwiseExtension
public import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteControlledApproximation
public import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteFaceBoundary
public import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteFaceExtension
public import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteFaceFilling
public import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteFaceModel
public import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteGraphApproximation
public import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteGraphPL
public import LeanPool.ClassificationOfSurfaces.Moise.LocallyFinitePLApproximation
public import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteSidePreservation
public import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteTriangulation
public import LeanPool.ClassificationOfSurfaces.Moise.NoRetraction
public import LeanPool.ClassificationOfSurfaces.Moise.OpenMidpointComplex
public import LeanPool.ClassificationOfSurfaces.Moise.PLApproximation
public import LeanPool.ClassificationOfSurfaces.Moise.PLMoves
public import LeanPool.ClassificationOfSurfaces.Moise.PlaneComplex
public import LeanPool.ClassificationOfSurfaces.Moise.PlaneCycle
public import LeanPool.ClassificationOfSurfaces.Moise.PolygonalArc
public import LeanPool.ClassificationOfSurfaces.Moise.PolygonalArcModel
public import LeanPool.ClassificationOfSurfaces.Moise.PolygonalCrosscut
public import LeanPool.ClassificationOfSurfaces.Moise.PolygonalFamilyPolyhedron
public import LeanPool.ClassificationOfSurfaces.Moise.PolygonalJordan
public import LeanPool.ClassificationOfSurfaces.Moise.PolygonalPolyhedron
public import LeanPool.ClassificationOfSurfaces.Moise.PolygonalSchoenflies
public import LeanPool.ClassificationOfSurfaces.Moise.PuncturedSurface
public import LeanPool.ClassificationOfSurfaces.Moise.RelativeSynchronizedArrangement
public import LeanPool.ClassificationOfSurfaces.Moise.ThinKiteMove
public import LeanPool.ClassificationOfSurfaces.NormalForm
public import LeanPool.ClassificationOfSurfaces.P2DegenerateDisk
public import LeanPool.ClassificationOfSurfaces.PolygonCellRadial
public import LeanPool.ClassificationOfSurfaces.PolygonalQuotient
public import LeanPool.ClassificationOfSurfaces.RepresentativeCarrier
public import LeanPool.ClassificationOfSurfaces.Representatives
public import LeanPool.ClassificationOfSurfaces.SignedPresentation
public import LeanPool.ClassificationOfSurfaces.SphereCarrierGeometry
public import LeanPool.ClassificationOfSurfaces.SphereHemisphere
public import LeanPool.ClassificationOfSurfaces.SphereQuotientHomeomorph
public import LeanPool.ClassificationOfSurfaces.StrongVertexStar
public import LeanPool.ClassificationOfSurfaces.Surface
public import LeanPool.ClassificationOfSurfaces.Topology.InvarianceOfDomain
public import LeanPool.ClassificationOfSurfaces.TriangleCell
public import LeanPool.ClassificationOfSurfaces.Triangulation
public import LeanPool.ClassificationOfSurfaces.WeightedCircle
import Mathlib.Analysis.SpecialFunctions.Bernstein
import Mathlib.CategoryTheory.Category.Init
import Mathlib.MeasureTheory.Covering.Besicovitch

/-!
# Classification of Compact Surfaces

Source: url:https://github.com/mccorvie/classification-of-surfaces/tree/master/ClassificationOfSurfaces
Authors: Ryan McCorvie, Jack McCarthy, SF Lean Meetup contributors
Status: verified
Main declarations: `LeanEval.Topology.ClassificationOfSurfaces.classification_of_surfaces`
Tags: geometric-topology, low-dimensional-topology, surfaces, manifolds, triangulation
MSC: 57K20, 57N05
-/

@[expose] public section
