/-
Copyright (c) 2026 ClassificationOfSurfaces contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ryan McCorvie, Jack McCarthy
-/

import LeanPool.ClassificationOfSurfaces.API
import LeanPool.ClassificationOfSurfaces.Basic
import LeanPool.ClassificationOfSurfaces.CanonicalCoordinates
import LeanPool.ClassificationOfSurfaces.CanonicalGeneratorMaps
import LeanPool.ClassificationOfSurfaces.CanonicalPairings
import LeanPool.ClassificationOfSurfaces.CanonicalWords
import LeanPool.ClassificationOfSurfaces.CellComplex
import LeanPool.ClassificationOfSurfaces.CellComplexQuotient
import LeanPool.ClassificationOfSurfaces.DiskSquare
import LeanPool.ClassificationOfSurfaces.EvalStatement
import LeanPool.ClassificationOfSurfaces.Examples
import LeanPool.ClassificationOfSurfaces.FiniteCyclicCancellation
import LeanPool.ClassificationOfSurfaces.FiniteCyclicCanonical
import LeanPool.ClassificationOfSurfaces.FiniteCyclicCanonicalRealization
import LeanPool.ClassificationOfSurfaces.FiniteCyclicCrosscap
import LeanPool.ClassificationOfSurfaces.FiniteCyclicDerivedRewrites
import LeanPool.ClassificationOfSurfaces.FiniteCyclicDyck
import LeanPool.ClassificationOfSurfaces.FiniteCyclicFaceMerge
import LeanPool.ClassificationOfSurfaces.FiniteCyclicMoveRealization
import LeanPool.ClassificationOfSurfaces.FiniteCyclicMoves
import LeanPool.ClassificationOfSurfaces.FiniteCyclicNormalization
import LeanPool.ClassificationOfSurfaces.FiniteCyclicNormalizationResult
import LeanPool.ClassificationOfSurfaces.FiniteCyclicP1
import LeanPool.ClassificationOfSurfaces.FiniteCyclicP1Realization
import LeanPool.ClassificationOfSurfaces.FiniteCyclicP2
import LeanPool.ClassificationOfSurfaces.FiniteCyclicP2DegenerateRealization
import LeanPool.ClassificationOfSurfaces.FiniteCyclicP2Realization
import LeanPool.ClassificationOfSurfaces.FiniteCyclicPresentation
import LeanPool.ClassificationOfSurfaces.FiniteCyclicRealization
import LeanPool.ClassificationOfSurfaces.FiniteCyclicReduction
import LeanPool.ClassificationOfSurfaces.FiniteCyclicSignedRealization
import LeanPool.ClassificationOfSurfaces.FiniteCyclicSphereRealization
import LeanPool.ClassificationOfSurfaces.FiniteCyclicTerminalNormalization
import LeanPool.ClassificationOfSurfaces.FiniteCyclicTriangulation
import LeanPool.ClassificationOfSurfaces.FiniteCyclicUnorientedRealization
import LeanPool.ClassificationOfSurfaces.FiniteCyclicWordReduction
import LeanPool.ClassificationOfSurfaces.GeometricTriangulationRealization
import LeanPool.ClassificationOfSurfaces.LeanEval.ChallengeDeps
import LeanPool.ClassificationOfSurfaces.LeanEval.RepresentativeSanity
import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveControlledApproximation
import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveFanAffine
import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveFanComplex
import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveOpenComplex
import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveOpenCover
import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveTileComplex
import LeanPool.ClassificationOfSurfaces.Moise.AdaptiveTriangulation
import LeanPool.ClassificationOfSurfaces.Moise.AmbientHomeomorph
import LeanPool.ClassificationOfSurfaces.Moise.Anchors
import LeanPool.ClassificationOfSurfaces.Moise.BoundaryInvariant
import LeanPool.ClassificationOfSurfaces.Moise.BrokenLine
import LeanPool.ClassificationOfSurfaces.Moise.Brouwer
import LeanPool.ClassificationOfSurfaces.Moise.ChartExtraction
import LeanPool.ClassificationOfSurfaces.Moise.ChartInduction
import LeanPool.ClassificationOfSurfaces.Moise.ChartPatch
import LeanPool.ClassificationOfSurfaces.Moise.CommonSubdivision
import LeanPool.ClassificationOfSurfaces.Moise.ConeExtension
import LeanPool.ClassificationOfSurfaces.Moise.Countermodels
import LeanPool.ClassificationOfSurfaces.Moise.DualConnectivity
import LeanPool.ClassificationOfSurfaces.Moise.ElementaryMove
import LeanPool.ClassificationOfSurfaces.Moise.EmbeddedComplexValence
import LeanPool.ClassificationOfSurfaces.Moise.FacewiseComparison
import LeanPool.ClassificationOfSurfaces.Moise.FineSubdivision
import LeanPool.ClassificationOfSurfaces.Moise.FinitePLHomeomorph
import LeanPool.ClassificationOfSurfaces.Moise.FreeTriangle
import LeanPool.ClassificationOfSurfaces.Moise.FreeTriangleMove
import LeanPool.ClassificationOfSurfaces.Moise.FrontierGlue
import LeanPool.ClassificationOfSurfaces.Moise.GeometricTriangulation
import LeanPool.ClassificationOfSurfaces.Moise.GraphPolygonalization
import LeanPool.ClassificationOfSurfaces.Moise.GraphRefinement
import LeanPool.ClassificationOfSurfaces.Moise.GraphSubdivision
import LeanPool.ClassificationOfSurfaces.Moise.HalfPlanePolygon
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicCellwiseExtension
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicCloseCellwiseExtension
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicCloseGraphApproximation
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicComplex
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicFaceBoundary
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicFaceExtension
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicFaceFilling
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicFaceModel
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicFineSubdivision
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicGraphApproximation
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicGraphModel
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicGraphPL
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicMarkedFan
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicMidpointSubdivision
import LeanPool.ClassificationOfSurfaces.Moise.IntrinsicSubdivision
import LeanPool.ClassificationOfSurfaces.Moise.LineSubdivision
import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteCellwiseExtension
import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteControlledApproximation
import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteFaceBoundary
import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteFaceExtension
import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteFaceFilling
import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteFaceModel
import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteGraphApproximation
import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteGraphPL
import LeanPool.ClassificationOfSurfaces.Moise.LocallyFinitePLApproximation
import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteSidePreservation
import LeanPool.ClassificationOfSurfaces.Moise.LocallyFiniteTriangulation
import LeanPool.ClassificationOfSurfaces.Moise.NoRetraction
import LeanPool.ClassificationOfSurfaces.Moise.OpenMidpointComplex
import LeanPool.ClassificationOfSurfaces.Moise.PLApproximation
import LeanPool.ClassificationOfSurfaces.Moise.PLMoves
import LeanPool.ClassificationOfSurfaces.Moise.PlaneComplex
import LeanPool.ClassificationOfSurfaces.Moise.PlaneCycle
import LeanPool.ClassificationOfSurfaces.Moise.PolygonalArc
import LeanPool.ClassificationOfSurfaces.Moise.PolygonalArcModel
import LeanPool.ClassificationOfSurfaces.Moise.PolygonalCrosscut
import LeanPool.ClassificationOfSurfaces.Moise.PolygonalFamilyPolyhedron
import LeanPool.ClassificationOfSurfaces.Moise.PolygonalJordan
import LeanPool.ClassificationOfSurfaces.Moise.PolygonalPolyhedron
import LeanPool.ClassificationOfSurfaces.Moise.PolygonalSchoenflies
import LeanPool.ClassificationOfSurfaces.Moise.PuncturedSurface
import LeanPool.ClassificationOfSurfaces.Moise.RelativeSynchronizedArrangement
import LeanPool.ClassificationOfSurfaces.Moise.ThinKiteMove
import LeanPool.ClassificationOfSurfaces.NormalForm
import LeanPool.ClassificationOfSurfaces.P2DegenerateDisk
import LeanPool.ClassificationOfSurfaces.PolygonCellRadial
import LeanPool.ClassificationOfSurfaces.PolygonalQuotient
import LeanPool.ClassificationOfSurfaces.RepresentativeCarrier
import LeanPool.ClassificationOfSurfaces.Representatives
import LeanPool.ClassificationOfSurfaces.SignedPresentation
import LeanPool.ClassificationOfSurfaces.SphereCarrierGeometry
import LeanPool.ClassificationOfSurfaces.SphereHemisphere
import LeanPool.ClassificationOfSurfaces.SphereQuotientHomeomorph
import LeanPool.ClassificationOfSurfaces.StrongVertexStar
import LeanPool.ClassificationOfSurfaces.Surface
import LeanPool.ClassificationOfSurfaces.Topology.InvarianceOfDomain
import LeanPool.ClassificationOfSurfaces.TriangleCell
import LeanPool.ClassificationOfSurfaces.Triangulation
import LeanPool.ClassificationOfSurfaces.WeightedCircle

/-!
# Classification of Compact Surfaces

Source: url:https://github.com/mccorvie/classification-of-surfaces/tree/master/ClassificationOfSurfaces
Authors: Ryan McCorvie, Jack McCarthy, SF Lean Meetup contributors
Status: verified
Main declarations: `LeanEval.Topology.ClassificationOfSurfaces.classification_of_surfaces`
Tags: geometric-topology, low-dimensional-topology, surfaces, manifolds, triangulation
MSC: 57K20, 57N05
-/
