/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, Aristotle
-/

import LeanPool.ForwardEuler.Main

/-!
# Forward Euler Method

A formal proof of convergence of the forward Euler method for ordinary
differential equations.

Given an ODE `y'(t) = v(t, y(t))` with `y(t₀) = y₀`, where
`v : ℝ × E → E` is a vector field on a normed space `E`, this project
defines the Euler approximation and proves that it converges to the true
solution as the step size `h → 0⁺`.

## Main results

- `ODE.EulerMethod.dist_deriv_le` — the Euler derivative is uniformly close
  to the vector field along the path:
  `dist(deriv(t), v(t, path(t))) ≤ h * (L + K * M)`.
- `ODE.EulerMethod.dist_path_le` — Grönwall bound on the distance between
  the Euler path and the true solution.
- `ODE.EulerMethod.tendsto_path` — `path(v, h, t₀, y₀, t) → sol(t)` as
  `h → 0⁺`.

## Source

Imported from <https://github.com/Vilin97/forward_euler>. Initial code
was generated by [Aristotle](https://aristotle.harmonic.fun); see the
upstream blueprint and dependency graph linked from that repository's
README for the full mathematical exposition.

## Authors

Vasily Ilin (with Aristotle).

## Status

Sorry-free. Ported from `Vilin97/forward_euler` (originally Lean
v4.28.0-rc1) to Lean Pool's pinned toolchain (Lean v4.30.0-rc2 /
Mathlib v4.30.0-rc2). Single-tactic adjustment: one `grind` invocation
in `tendsto_path` was replaced with `simp [gronwallBound_ε0_δ0]`
because `grind`'s heuristics tightened between v4.28 and v4.30. The
rest of the upstream proof is verbatim. Builds cleanly.
-/
