/-
Copyright (c) 2026 Math Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Math Inc.
-/

import LeanPool.KakeyaFiniteFields.Main

/-!
# Kakeya sets in finite fields

Source: url:https://github.com/math-inc/KakeyaFiniteFields
Authors: Math Inc.
Status: verified
Main declarations: `LeanPool.KakeyaFiniteFields.kakeya_set_bound`
Tags: combinatorics, polynomials, field-theory
-/

/-!
## Mathematical overview

Fix `n : ℕ` and a finite field `F` with `q = #F` elements. A *Kakeya set*
`K ⊆ Fin n → F` is a set that contains a full line `{b + t • d | t : F}` in
every direction `d`. Dvir's 2008 theorem, formalized here as
`LeanPool.KakeyaFiniteFields.kakeya_set_bound`, states that any such set has
size at least `Cₙ · q ^ n`, where `Cₙ = (n!)⁻¹ > 0` depends only on `n`.

The proof is the polynomial method. If `|K| < binom(q+n-1, n)`, the space of
polynomials of total degree `≤ q - 1` outdimensions the evaluation space, so a
nonzero such polynomial `P` vanishes on `K` (`step1`). Restricting `P` to any
line of `K` gives a univariate polynomial of degree `< q` with `q` roots, hence
zero (`step2`); comparing top coefficients forces the degree-`(q-1)`
homogeneous component of `P` to vanish on every direction, hence to be zero
(`step3`); multiplying by a high power of a coordinate and inducting on the
degree shows `P = 0` (`step4`), contradicting `step1`. The cardinality bound
then follows from `q ^ n ≤ n! · binom(q+n-1, n)`.

## Provenance

Imported from <https://github.com/math-inc/KakeyaFiniteFields>; the Lean
statements and proofs were generated by Gauss, [Math Inc.](https://www.math.inc/)'s
autoformalization agent, from a LaTeX blueprint following Zeev Dvir,
*On the size of Kakeya sets in finite fields* (2008). Upstream contains no
`sorry`s. Ported from Lean v4.26.0 to Lean Pool's v4.30.0-rc2.

The upstream repository does not currently ship a license file; see
`IMPORT_NOTES.md` in the repository root for details.
-/
