/-
Copyright (c) 2026 Wei Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Wei Wang
-/
module

public import LeanPool.LeanStationaryHarmonicMaps.Examples.StationaryMonotonicity
public import LeanPool.LeanStationaryHarmonicMaps.Examples.UseMainTheorem
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.API
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.BallIntegralAC
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.Basic
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.BoundaryBasics
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.BoundaryFromRadial
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.CenterTranslation
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.EnergyQuantities
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.Euclidean
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.FirstVariationBridge
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.L2LocBridge
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.MainTheorem
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.Monotonicity
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.MonotonicityEuclidean
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.MonotonicityFinal
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.MonotonicityRoutes
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.PrimitiveCutoffs
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.RadialCutoffs
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.RadialGeometry
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.RadialIdentity
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.RadialIntegrability
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.RadialMeasure
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.RadiusAnalysis
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.RadiusFormulas
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.RadiusPrimitive
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.RadiusWeightedDerivative
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.RadiusWeightedRepresentation
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.RadiusWeights
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.SobolevBridge
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.SobolevWitness
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.StationarityBridge
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.StationaryMap
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.WeakGradientBridge
public import LeanPool.LeanStationaryHarmonicMaps.StationaryHarmonicMap.WeakStationarity

/-!
# Monotonicity Formula for Stationary Harmonic Maps

Source: doi:10.1007/978-3-0348-9193-6
Authors: Wei Wang
Status: verified
Main declarations: `LeanStationaryHarmonicMaps.StationaryHarmonicMap.StationaryW12LocMap`
Tags: analysis, pde, harmonic-maps, monotonicity-formula, sobolev
MSC: 58E20, 35J50
-/

@[expose] public section
