/-
Copyright (c) 2026 William Whistler. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: William Whistler
-/

module

public import LeanPool.RegtsSevenster.RS
public import LeanPool.RegtsSevenster.RS.Assembly.Blueprint
public import LeanPool.RegtsSevenster.RS.Assembly.BlueprintConverse
public import LeanPool.RegtsSevenster.RS.Assembly.BlueprintDeligne
public import LeanPool.RegtsSevenster.RS.Assembly.BlueprintFactorial
public import LeanPool.RegtsSevenster.RS.Assembly.BlueprintSchur
public import LeanPool.RegtsSevenster.RS.Assembly.BlueprintStatement
public import LeanPool.RegtsSevenster.RS.Classical
public import LeanPool.RegtsSevenster.RS.Classical.Algebra.FactorialTrace
public import LeanPool.RegtsSevenster.RS.Classical.Algebra.TraceCriterion
public import LeanPool.RegtsSevenster.RS.Classical.CatTheory.Growth
public import LeanPool.RegtsSevenster.RS.Classical.CatTheory.Intertwine
public import LeanPool.RegtsSevenster.RS.Classical.CatTheory.KaroubiLinear
public import LeanPool.RegtsSevenster.RS.Classical.CatTheory.KaroubiTrace
public import LeanPool.RegtsSevenster.RS.Classical.CatTheory.Length
public import LeanPool.RegtsSevenster.RS.Classical.CatTheory.LengthBound
public import LeanPool.RegtsSevenster.RS.Classical.CatTheory.LinearCategory
public import LeanPool.RegtsSevenster.RS.Classical.CatTheory.PartialTrace
public import LeanPool.RegtsSevenster.RS.Classical.CatTheory.TensorPow
public import LeanPool.RegtsSevenster.RS.Classical.CatTheory.Trace
public import LeanPool.RegtsSevenster.RS.Classical.CatTheory.UnitEnd
public import LeanPool.RegtsSevenster.RS.Classical.CatTheory.WhiskerAdditive
public import LeanPool.RegtsSevenster.RS.Classical.Deligne
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.AltPow
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.AltPowAct
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeAdjoint
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeBiprod
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeCoherence
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeDatum
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeFree
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeLinear
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeMonoidal
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeTensor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeTransport
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BaseChangeZigzag
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BigTensor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BigTensorUnit
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BiprodPow
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BiprodTransfer
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BlockUnits
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.BraidCoherence
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainAlgebra
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainB
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBGr
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBGraded
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBGradedLaws
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBInd
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBNonzero
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBofA
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainBridge
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainDelta
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainIns
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainIns.Base
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainIns.FirstSlot
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainIns.SecondSlot
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainMul
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainMulHet
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainMulLaws
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainNonzero
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainShift
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainStage2
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ChainUnit
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.CharSplit
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.CommonAlgebra
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.CoprodPreserve
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.CountableDescent
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.CountableDescentClose
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.CountableNullstellensatz
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.CoverFactor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.CycleSplit
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.DayCalculus
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.DayType
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.DeligneAssembly
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.DescentClose
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.DevissageBound
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.DoubledAbelian
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.DoubledGrowth
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.DoubledLine
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.DoubledScalar
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.DoubledSmall
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.DoubledSplit
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Doubling
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.DualityMate
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.EvenEmbedMonoidal
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ExactFromShort
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FactorialBeats
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreAdditive
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreBridge
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreEps
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreExact
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreFaithful
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreFunctor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreLinear
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreMix
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreMonoidal
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreMu
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreMuNat
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreOverComplex
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreOverSplitting
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreRestrict
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FibreStrong
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FiltNil
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FlatLimit
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeCollapseAlg
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeMixRetract
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeModAdjoint
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeModBiprod
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeModFunctor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeModShuffle
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeModShuffleCoh
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeModTensor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeNormalise
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeNormaliseBase
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeNormaliseStep
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreePow
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreePowDesc
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreePowInsert
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeSlide
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeSummand
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.FreeTwistPi
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaAlgebra
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaBiprod
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaComplex
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaCountable
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaModule
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaModuleFunctor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPair
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairAdd
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairFreeFree
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairFreeMix
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairNat
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairRetract
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairRetractRight
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaPairUnit
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaShift
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GammaTwistLeft
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GeneratorAlgebra
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.GrowthDichotomy
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.HomFinite
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.HookMult
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.HookZero
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IdemCut
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IdempotentLength
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ImageSubalgebra
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndAllColim
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndBigTensorUnit
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndCoeq
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndCompact
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndDayClosure
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndImage
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndKill
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndLocallyMixed
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndMonoidal
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndOfLinear
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndOfMonoidal
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndPointTensor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndSchur
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndSchurKilled
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndSimple
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndSplit
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndSplitSection
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndTensorExact
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.IndUnitNonzero
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.InitDatum
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.InitState
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.InterchangeAct
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.KernelPow
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.KeyLemma
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.KeyLemmaClose
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.KeyLemmaData
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.KillerNonempty
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.KronKill
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.LambdaCoend
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixDegenerate
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixShuffle
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixShuffleLine
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixSumPow
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixWhisker
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixWhiskerAll
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixedConc
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixedDiag
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.MixedTransport
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModAbelian
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModAssoc
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModBiprod
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModContractL
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModCross
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModDual
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModIns
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModMulti
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModMultiTriple
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModPowCast
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModPowDescent
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModPowDescentClose
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModPowStage
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModSchur
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModSchurSummand
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModTensor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ModZero
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.MuInterchange
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.MulBy
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.NatChain
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.NewtonConv
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.NullPoint
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddLineMap
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddLinePairing
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddParity
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddPermSign
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddSquare
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.OddSquareIso
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PairCarrier
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PairMul
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PairPerm
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PermNat
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PermRepChar
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PieriPos
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PlainShuffle
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointBaseChange
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointFibre
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointMonoidal
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointMonoidal.Calculus
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointMonoidal.Coherence
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointMonoidal.Comparison
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointMonoidal.Functor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointMonoidal.Residue
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PointTensor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowAct
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowActMul
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowChain
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowCopairing
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowDatum
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowInduct
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowMerge
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowPairSucc
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowPairing
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowPoint
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowSucc
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowSuccMod
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowTriangle
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowZig
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PowZigzag
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.PresentedQuotient
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Prop21
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Prop21Core
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Prop21General
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Prop29
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Prop29Close
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Prop29State
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Rappel210
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Rappel210Bridge
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Rappel210Chain
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Rappel210Close
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Rappel210Ind
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.Rappel210Reduce
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.RegularSum
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.RhoBiprod
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.RhoTwist
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.RowColIdem
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SandwichMerge
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SandwichRetract
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SandwichZig
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ScalarBraiding
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ScalarLinear
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ScalarUnitEquiv
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ScalarUnitInd
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SchurTransport
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SchurVanishing
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SeedIns
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ShapeAlgebra
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ShapeFintype
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SignConj
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SimpleGenerator
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SimplePoint
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SimpleQuotient
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SimpleScalars
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SimpleSplit
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SmallReduction
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitAdjoint
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitAssemble
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitClosure
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitComplement
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitEverything
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitExact
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitExtract
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitExtractDual
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitMonHom
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitPairDef
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitReduce
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplitTransport
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SplittingAlgebra
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.StateTransport
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.StepA
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.StepATransport
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.StepB
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperEmbed
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperEmbed.Letters
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperEmbed.Signs
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperEmbed.Standard
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperEvenRing
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperGamma
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperGammaInst
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModAbelian
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModBiprod
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModBiprodMap
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModHom
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModIso
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModMonoidal
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModShift
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModShiftUnit
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperModTensor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperPointMod
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperRealize
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperSeries
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperSmall
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperValues
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SuperVectSchur
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SymAlg
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SymDatum
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.SymMul
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorDatum
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorExact
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorMuBraid
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorPowZero
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorTransfer
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TensorZigzag
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TrichotomyClose
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistBiprod
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistCoherence
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistDatum
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistFreeTensor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistMixLine
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistPow
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistShuffle
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistState
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistSymPow
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.TwistUnitor
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.UnitBase
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.UnitFreeMod
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.UnitMod
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.UnitSimple
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.UnitStage
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.UniversalAlgebra
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.WhiskerFaithful
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.WordMap
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZagAction
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZigzagCarrier
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZigzagNonzero
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZigzagSandwich
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZigzagTransfer
public import LeanPool.RegtsSevenster.RS.Classical.Deligne.ZigzagTransferIso
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.DeligneBridge
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.DelignePackage
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.DelignePackageRestrict
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.DeligneTheorem
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.EulerianIndependence
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.FibreTransport
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.KoszulAction
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.OmegaPerm
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.OmegaTensorPower
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.SchurPackage
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.SectorDischarge
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.SectorIntertwine
public import LeanPool.RegtsSevenster.RS.Classical.Interfaces.TotalDimension
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.BlockKill
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.BranchTrace
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CentralElem
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CharClass
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CharDecomp
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CharEquiv
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.ColourCycleSum
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.ColourWeight
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CommutantBound
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.ContentCount
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CycleFactor
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CycleSum
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.CycleSumPrep
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.EndSum
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.FibreCard
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.FixWeight
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.HVal
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.IdempotentBridge
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.JTChar
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.JTIntChar
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.JTIrreducible
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.JTOrtho
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.JTPad
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.JTSimple
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.KillSimples
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.MixedCount
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.MixedFixed
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.NativeAction
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.NativeFaithful
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.NativeTable
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.OrbitBridge
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.Package
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PackageAssembly
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PairChar
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PairInner
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PairOrbit
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PairStab
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PairTuple
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PairingPos
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PermModule
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.PowerSurj
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.RegularTrace
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SameCycleQuot
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.ScalarTrace
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SchurAction
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SigmaCycleType
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SignResolve
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SignedTensor
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SimpleEmbed
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SquareGrowth
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SquareGrowthSharp
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.SquareStair
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.StabCount
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.TensorNonvanishing
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.TensorTrace
public import LeanPool.RegtsSevenster.RS.Classical.SchurTheory.WordCommutant
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourAction
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourConj
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourConjStep
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourConjTop
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourEval
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourExtendSwap
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourFormMatch
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourMerge
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourMergeOdd
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourPairing
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourPairingSymm
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourPower
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourTotal
public import LeanPool.RegtsSevenster.RS.Classical.Super.ColourWord
public import LeanPool.RegtsSevenster.RS.Classical.Super.OrthonormalBasis
public import LeanPool.RegtsSevenster.RS.Classical.Super.PowBraid
public import LeanPool.RegtsSevenster.RS.Classical.Super.SuperVect
public import LeanPool.RegtsSevenster.RS.Classical.Super.SymplecticBasis
public import LeanPool.RegtsSevenster.RS.Classical.Super.TotalSpace
public import LeanPool.RegtsSevenster.RS.Classical.Super.WordSignPerm
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.AlternantExpand
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.AlternantPieri
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.AlternantStrict
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.Bialternant
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.BinomialDet
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.BinomialH
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.CoeffExtract
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.CoeffSplit
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.DeltaSeq
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.DescVandermonde
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.DimFormula
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.EHConv
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.EHDischarge
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.HInsert
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.HProdCoeff
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.HSubZ
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.HookVanishing
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.JTDetExpand
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.JTGuard
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.LGVStrict
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.PieriChain
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.PowCount
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.PowerSums
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.RationalityFromRecurrence
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.RecurrenceFromVanishing
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.SubsetEH
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.SuperPowerSums
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.TCount
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.TIdentity
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.ZetaExp
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.ZetaRational
public import LeanPool.RegtsSevenster.RS.Classical.SymFun.ZetaSeries
public import LeanPool.RegtsSevenster.RS.Common
public import LeanPool.RegtsSevenster.RS.Common.DiagramChain
public import LeanPool.RegtsSevenster.RS.Common.ExponentialGrowth
public import LeanPool.RegtsSevenster.RS.Common.FactorialBound
public import LeanPool.RegtsSevenster.RS.Common.FinSlots
public import LeanPool.RegtsSevenster.RS.Common.ListAttach
public import LeanPool.RegtsSevenster.RS.Common.ListPairs
public import LeanPool.RegtsSevenster.RS.Common.ListSign
public import LeanPool.RegtsSevenster.RS.Common.MathlibDeps
public import LeanPool.RegtsSevenster.RS.Common.NilpotentMap
public import LeanPool.RegtsSevenster.RS.Common.NilpotentPowerTrace
public import LeanPool.RegtsSevenster.RS.Common.PairDisjoint
public import LeanPool.RegtsSevenster.RS.Common.PermCongr
public import LeanPool.RegtsSevenster.RS.Common.PermTopSplit
public import LeanPool.RegtsSevenster.RS.Common.ProdSum
public import LeanPool.RegtsSevenster.RS.Common.RowLenChain
public import LeanPool.RegtsSevenster.RS.Common.RowSpanRank
public import LeanPool.RegtsSevenster.RS.Common.TraceSeparation
public import LeanPool.RegtsSevenster.RS.Common.YoungDiagrams
public import LeanPool.RegtsSevenster.RS.Definitions
public import LeanPool.RegtsSevenster.RS.DimensionDefinitions
public import LeanPool.RegtsSevenster.RS.Glossary
public import LeanPool.RegtsSevenster.RS.Novel
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.AdjSwapBmc
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.AdjacentWord
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BasisCoord
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BasisSplit
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BetaData
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BetaDiag
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BetaDiagForm
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BetaFlip
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BlockAlign
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BlockCanon
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BlockData
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BlockOddList
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BlockParity
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BlockRestrict
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BlockSigma
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BlockSort
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.BraidWord
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CanonColour
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CanonPerm
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CapClosed
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CapExpansion
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CapFun
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CapMatch
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CapPeel
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CapPeelSplit
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CapPerm
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CapSplit
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CapVal
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.ChainLists
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CircleModel
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CircleScalar
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CircuitCount
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.ClosedTransition
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.ConcatSign
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CoordInterface
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CoordOf
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.CoreParity
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.EdgeSign
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.EvForm
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.EvFormOdd
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.EvLeaf
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.FibreParam
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.FlagEnum
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.GlobalSlotList
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.HRS
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.IndexPerm
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.ListSignPerm
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.MasterSum
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.ModelCoord
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.ModelPermCoord
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.ModelStarVec
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.MultiStar
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.NFDef
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.NFValue
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.OddFlip
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.OddListMultiset
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.OddPair
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.OddSignProd
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.OmegaCotensor
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.OmegaStarVec
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.OmegaTensor
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.OmegaTransport
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.OneBasis
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.OrbitCard
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.OutSignEdges
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.PairEnum
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.PairList
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.ParameterModel
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.PatternInv
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.PowMerge
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.RegroupSign
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.Reindex
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.ReindexBij
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.ReindexHeart
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.ReindexVanish
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.RepFlag
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.RiffleSign
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.SignPair
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.SkeinPowBraid
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.SlotPairing
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.SortFactor
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.SortPerm
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.StarClassFactor
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.StarPeel
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.StarPerm
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.StarRepeat
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.StarSymm
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.StarTensorClass
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.StdTransport
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.StrandTransport
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.TauCount
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.TauKey
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.TopBraidMerge
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.TwoBasis
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.VertexSign
public import LeanPool.RegtsSevenster.RS.Novel.Coordinates.VertexValue
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.AtomDichotomy
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.AtomicIdempotents
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.BlockAssembly
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.BlockBounds
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.BlockCycle
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.BlockFactor
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.BlockFactorialTrace
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.BlockSplice
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.BlockTower
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.CycleNormal
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.CycleTrace
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.EnvAbelian
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.EnvDeligne
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.EnvDelignePackage
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.EnvGenerator
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.EnvGrowth
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.EnvInstances
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.EnvSemisimple
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.FactorialTrace
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.Frobenius
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.HookConfinement
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.HookConfinementSharp
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.KaroubiEmbBraided
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.KaroubiMonoidal
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.KaroubiRigid
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.KaroubiSemisimple
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.MatBraided
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.MatEmbMonoidal
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.MatMonoidal
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.MatRigid
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.MatSemisimple
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.NilpotentMatTrace
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.NilpotentTrace
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.ObjectTower
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.PermTrace
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.RankDimension
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.ScalarPermTrace
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.ScalarTrace
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.SemisimpleAll
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.SemisimpleEnd
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.SkeinDimBound
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.SkeinTower
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.SkeinTrace
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.SuperKill
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.SymPerm
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.SymPermCast
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.TensorPowHom
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.TensorPowSplit
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.TraceZeta
public import LeanPool.RegtsSevenster.RS.Novel.Envelope.TraceZetaSharp
public import LeanPool.RegtsSevenster.RS.Novel.Extraction.CircleValue
public import LeanPool.RegtsSevenster.RS.Novel.Extraction.CoordIso
public import LeanPool.RegtsSevenster.RS.Novel.Extraction.Coordinates
public import LeanPool.RegtsSevenster.RS.Novel.Extraction.CopairUnique
public import LeanPool.RegtsSevenster.RS.Novel.Extraction.Nondegenerate
public import LeanPool.RegtsSevenster.RS.Novel.Extraction.SnakeTransport
public import LeanPool.RegtsSevenster.RS.Novel.Extraction.StdDuality
public import LeanPool.RegtsSevenster.RS.Novel.Extraction.StdRigid
public import LeanPool.RegtsSevenster.RS.Novel.Extraction.StdSuper
public import LeanPool.RegtsSevenster.RS.Novel.Skein.AllInternalAgreement
public import LeanPool.RegtsSevenster.RS.Novel.Skein.AllInternalIndependence
public import LeanPool.RegtsSevenster.RS.Novel.Skein.BraidedInstance
public import LeanPool.RegtsSevenster.RS.Novel.Skein.BraidedNat
public import LeanPool.RegtsSevenster.RS.Novel.Skein.BundleClose
public import LeanPool.RegtsSevenster.RS.Novel.Skein.BundleMapClasses
public import LeanPool.RegtsSevenster.RS.Novel.Skein.BundleTensor
public import LeanPool.RegtsSevenster.RS.Novel.Skein.CanonExistence
public import LeanPool.RegtsSevenster.RS.Novel.Skein.CanonTransport
public import LeanPool.RegtsSevenster.RS.Novel.Skein.CanonicalFrame
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ChainAgreement
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ChordCount
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ChordLabels
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ChordParity
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ChordSwapParity
public import LeanPool.RegtsSevenster.RS.Novel.Skein.CloseRotate
public import LeanPool.RegtsSevenster.RS.Novel.Skein.CloseRotateLeft
public import LeanPool.RegtsSevenster.RS.Novel.Skein.CloseUnion
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ClosedAgreement
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ClosedCutDispatch
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ClosedIdentify
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ClosedTopSum
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ColourEmbedding
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ColourGlue
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ColourPadding
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ColourRecursion
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ComposeAssoc
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ComposeNormal
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ComposeRelabel
public import LeanPool.RegtsSevenster.RS.Novel.Skein.Composition
public import LeanPool.RegtsSevenster.RS.Novel.Skein.CompositionEquiv
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ConnectionRank
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ConverseAssembly
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ConverseDischarge
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ConverseFamily
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ConverseGram
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ConverseIdentity
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ConverseLift
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ConversePair
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ConverseTrip
public import LeanPool.RegtsSevenster.RS.Novel.Skein.CrossingDelta
public import LeanPool.RegtsSevenster.RS.Novel.Skein.CutMatching
public import LeanPool.RegtsSevenster.RS.Novel.Skein.CutSubsetSum
public import LeanPool.RegtsSevenster.RS.Novel.Skein.DirMatching
public import LeanPool.RegtsSevenster.RS.Novel.Skein.DisjSubsetSplit
public import LeanPool.RegtsSevenster.RS.Novel.Skein.DisjUnionFactor
public import LeanPool.RegtsSevenster.RS.Novel.Skein.DisjUnionFactor.A
public import LeanPool.RegtsSevenster.RS.Novel.Skein.DisjUnionFactor.B
public import LeanPool.RegtsSevenster.RS.Novel.Skein.DisjUnionFactor.C
public import LeanPool.RegtsSevenster.RS.Novel.Skein.DisjUnionProduct
public import LeanPool.RegtsSevenster.RS.Novel.Skein.EdgeColouring
public import LeanPool.RegtsSevenster.RS.Novel.Skein.EdgeSum
public import LeanPool.RegtsSevenster.RS.Novel.Skein.EdgeTerm
public import LeanPool.RegtsSevenster.RS.Novel.Skein.Eulerian
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ExactPairingInstance
public import LeanPool.RegtsSevenster.RS.Novel.Skein.FibreValue
public import LeanPool.RegtsSevenster.RS.Novel.Skein.FlagGraph
public import LeanPool.RegtsSevenster.RS.Novel.Skein.FlipSignForm
public import LeanPool.RegtsSevenster.RS.Novel.Skein.FlipSignProduct
public import LeanPool.RegtsSevenster.RS.Novel.Skein.FourLabelParity
public import LeanPool.RegtsSevenster.RS.Novel.Skein.FragmentEquiv
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GenBoundaryStates
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueAmbient
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueChord
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueChords
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueCircuitDelta
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueComm
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueCrossDelta
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueFold
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueLedger
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GluePathMatch
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueRelTransport
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueSplit
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueSplitProof
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueSplitProof.A
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueSplitProof.C
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GlueSubsetBij
public import LeanPool.RegtsSevenster.RS.Novel.Skein.GramRank
public import LeanPool.RegtsSevenster.RS.Novel.Skein.HomCompose
public import LeanPool.RegtsSevenster.RS.Novel.Skein.HomSpaces
public import LeanPool.RegtsSevenster.RS.Novel.Skein.HomTensor
public import LeanPool.RegtsSevenster.RS.Novel.Skein.HomTraceCyclic
public import LeanPool.RegtsSevenster.RS.Novel.Skein.HomTraceNondegenerate
public import LeanPool.RegtsSevenster.RS.Novel.Skein.IdentityLaw
public import LeanPool.RegtsSevenster.RS.Novel.Skein.IdentityLawRight
public import LeanPool.RegtsSevenster.RS.Novel.Skein.InterfaceAlternate
public import LeanPool.RegtsSevenster.RS.Novel.Skein.InterfaceContract
public import LeanPool.RegtsSevenster.RS.Novel.Skein.InterfaceCut
public import LeanPool.RegtsSevenster.RS.Novel.Skein.InterfaceOrderIso
public import LeanPool.RegtsSevenster.RS.Novel.Skein.InterfaceShift
public import LeanPool.RegtsSevenster.RS.Novel.Skein.InvolutionCard
public import LeanPool.RegtsSevenster.RS.Novel.Skein.LabelChords
public import LeanPool.RegtsSevenster.RS.Novel.Skein.LedgerCast
public import LeanPool.RegtsSevenster.RS.Novel.Skein.LedgerRecursion
public import LeanPool.RegtsSevenster.RS.Novel.Skein.LedgerSets
public import LeanPool.RegtsSevenster.RS.Novel.Skein.LedgerStage
public import LeanPool.RegtsSevenster.RS.Novel.Skein.LedgerValue
public import LeanPool.RegtsSevenster.RS.Novel.Skein.LoopExample
public import LeanPool.RegtsSevenster.RS.Novel.Skein.LoopVerify
public import LeanPool.RegtsSevenster.RS.Novel.Skein.MixedPartition
public import LeanPool.RegtsSevenster.RS.Novel.Skein.MonoidalInstance
public import LeanPool.RegtsSevenster.RS.Novel.Skein.MonoidalNat
public import LeanPool.RegtsSevenster.RS.Novel.Skein.MonoidalStruct
public import LeanPool.RegtsSevenster.RS.Novel.Skein.Multiplicativity
public import LeanPool.RegtsSevenster.RS.Novel.Skein.NonSeparatedStep
public import LeanPool.RegtsSevenster.RS.Novel.Skein.OpenCircuits
public import LeanPool.RegtsSevenster.RS.Novel.Skein.OrbitParities
public import LeanPool.RegtsSevenster.RS.Novel.Skein.OrientExistence
public import LeanPool.RegtsSevenster.RS.Novel.Skein.OrientationFlip
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PairCloseComm
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PairedAssembly
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PairingConnectivity
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PairingSignature
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PairingSwap
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PairingValue
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PartialClose
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PartialCloseCompose
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PartialCloseTensor
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PathCanon
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PathLedger
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PathMatch
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PermCompose
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PermFragment
public import LeanPool.RegtsSevenster.RS.Novel.Skein.PropThreeOpen
public import LeanPool.RegtsSevenster.RS.Novel.Skein.RSTensor
public import LeanPool.RegtsSevenster.RS.Novel.Skein.RelTransition
public import LeanPool.RegtsSevenster.RS.Novel.Skein.RelValue
public import LeanPool.RegtsSevenster.RS.Novel.Skein.RelabelChords
public import LeanPool.RegtsSevenster.RS.Novel.Skein.RelabelInvariance
public import LeanPool.RegtsSevenster.RS.Novel.Skein.RepairInvariance
public import LeanPool.RegtsSevenster.RS.Novel.Skein.RigidInstance
public import LeanPool.RegtsSevenster.RS.Novel.Skein.RigidityClasses
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ScalarClass
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ScalarFunctional
public import LeanPool.RegtsSevenster.RS.Novel.Skein.SeparatedParity
public import LeanPool.RegtsSevenster.RS.Novel.Skein.SimpleUnit
public import LeanPool.RegtsSevenster.RS.Novel.Skein.SkeinCatInstance
public import LeanPool.RegtsSevenster.RS.Novel.Skein.SkeinCategory
public import LeanPool.RegtsSevenster.RS.Novel.Skein.SkeinIdeal
public import LeanPool.RegtsSevenster.RS.Novel.Skein.SkeinIdealLeft
public import LeanPool.RegtsSevenster.RS.Novel.Skein.SkeinLinear
public import LeanPool.RegtsSevenster.RS.Novel.Skein.SnakeClasses
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StarCompClass
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StarDecomposition
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StarEnum
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StarExplode
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StarPrep
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StarTrace
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StateFlipSet
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StatusSet
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StepFrame
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StepLedger
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StepStatus
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StepStatusNonsep
public import LeanPool.RegtsSevenster.RS.Novel.Skein.StrandBundle
public import LeanPool.RegtsSevenster.RS.Novel.Skein.SumLexOrder
public import LeanPool.RegtsSevenster.RS.Novel.Skein.SuperGram
public import LeanPool.RegtsSevenster.RS.Novel.Skein.SuperSpace
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TensorAssoc
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TensorComm
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TensorCompClass
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TensorFragment
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TensorIdeal
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TensorInterchange
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TensorUnit
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ThroughEdgeCut
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ThroughIndCFalse
public import LeanPool.RegtsSevenster.RS.Novel.Skein.ThroughValue
public import LeanPool.RegtsSevenster.RS.Novel.Skein.Trace
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TraceCyclic
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TraceNondegenerate
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TransitionExists
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TransitionMove
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TransposeLedger
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TwoPathNonSep
public import LeanPool.RegtsSevenster.RS.Novel.Skein.TwoPathStep
public import LeanPool.RegtsSevenster.RS.Novel.Skein.VertexOddSign
public import LeanPool.RegtsSevenster.RS.Novel.Skein.VertexSum
public import LeanPool.RegtsSevenster.RS.QuantSector
public import LeanPool.RegtsSevenster.RS.StatementConverse
public import LeanPool.RegtsSevenster.RS.Summit
public import LeanPool.RegtsSevenster.RS.TheoremConverse
public import LeanPool.RegtsSevenster.RS.TheoremDimension
public import LeanPool.RegtsSevenster.RS.TheoremForward
public import LeanPool.RegtsSevenster.RS.TheoremPadding
public import LeanPool.RegtsSevenster.RS.TheoremQuant
public import LeanPool.RegtsSevenster.RS.TheoremTotal
public import LeanPool.RegtsSevenster.Solution

/-!
# A proof of the Regts–Sevenster conjecture, formalized

Source: url:https://github.com/willwhistler/regts-sevenster
Authors: William Whistler
Status: verified
Main declarations: `RS.regts_sevenster_characterisation`
Tags: graph-parameters, tensor-categories, partition-functions
MSC: 05C50, 18M20
-/
