/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall
-/
module

public import Mathlib.Analysis.InnerProductSpace.LinearPMap
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.RingTheory.PicardGroup
public import Mathlib.Tactic

/-!
# Davis--Kahan 1970: the four Section 2 theorems

The namespace is `RotationOfEigenvectors`, after the paper's title.  Everything
below is ordinary Mathlib vocabulary; the only non-Mathlib names are the source
objects defined here.

Two conventions, stated once.  There is no functional calculus anywhere: a
unitarily invariant norm sees only the singular-value sequence, so every angle
quantity is either an explicit block of orthogonal projections or a sequence of
trigonometric functions of singular values.  And `‖tan Θ‖` is evaluated on the
tangent *sequence*, with each tangent theorem *concluding* that the tangent has
no pole rather than assuming it away.
-/

@[expose] public section

namespace RotationOfEigenvectors

open scoped InnerProductSpace NNReal ENNReal

universe u v w

/-! ## 1. Singular values -/

section SingularValues

variable {𝕜 : Type u} [NontriviallyNormedField 𝕜]
variable {E : Type v} [SeminormedAddCommGroup E] [NormedSpace 𝕜 E]
variable {F : Type w} [SeminormedAddCommGroup F] [NormedSpace 𝕜 F]

/-- The `n`-th singular value of a bounded operator, zero-based: the
operator-norm distance from `T` to the operators of rank at most `n`.  `a₀ T =
‖T‖`, and for a compact operator this is the usual decreasing sequence. -/
noncomputable def singularValue (T : E →L[𝕜] F) (n : ℕ) : ℝ :=
  ⨅ R : {R : E →L[𝕜] F // LinearMap.rank (R.1 : E →ₗ[𝕜] F) ≤ (n : Cardinal)},
    ‖T - R.1‖

end SingularValues

/-! ## 2. The symmetric-norming presentation of the source norm quantifier

The paper quantifies over arbitrary normalized unitarily invariant norms.  This
Challenge uses the canonical dimension-coherent symmetric-norming presentation:
a two-sided unitarily invariant seminorm on `n × n` complex matrices in every
dimension, normalized on rank one and unchanged by appending a zero singular
value, extended to operators through approximation singular values.

This Lean type is not literally the entire source norm class in infinite
dimension.  The included formalization proves, via the strong Fan-dominance
criterion used by Davis and Kahan, that the *inequalities* quantified over all
such symmetric norming functions are equivalent to the corresponding universal
unitarily invariant norm estimates.  In particular the formal development also
covers Fan-dominant norms not generated by a symmetric gauge.  The distinction is
recorded explicitly in `formalization.yaml`; it is a presentation choice, not a
claim that the two norm types are definitionally identical. -/

section Norms

/-- The operator with real diagonal `x` in an orthonormal basis. -/
noncomputable def diagOp {n : ℕ} {E : Type v} [NormedAddCommGroup E]
    [InnerProductSpace ℂ E] (b : OrthonormalBasis (Fin n) ℂ E) (x : Fin n → ℝ) :
    E →ₗ[ℂ] E :=
  ∑ i, ((x i : ℝ) : ℂ) • (InnerProductSpace.rankOne ℂ (b i) (b i)).toLinearMap

/-- A two-sided unitarily invariant seminorm on the operators of a
finite-dimensional complex inner product space. -/
structure UISeminorm (E : Type v) [NormedAddCommGroup E] [InnerProductSpace ℂ E]
    [FiniteDimensional ℂ E] where
  /-- The underlying function on operators. -/
  toFun : (E →ₗ[ℂ] E) → ℝ
  /-- Subadditivity. -/
  add_le : ∀ A B, toFun (A + B) ≤ toFun A + toFun B
  /-- Absolute homogeneity. -/
  smul : ∀ (a : ℂ) (A), toFun (a • A) = ‖a‖ * toFun A
  /-- Two-sided unitary invariance -- the defining property. -/
  invariant : ∀ (U V : E ≃ₗᵢ[ℂ] E) (A),
    toFun (U.toLinearMap ∘ₗ A ∘ₗ V.toLinearMap) = toFun A

/-- The symmetric gauge: the seminorm's value on the diagonal operator. -/
noncomputable def UISeminorm.gauge {n : ℕ} {E : Type v} [NormedAddCommGroup E]
    [InnerProductSpace ℂ E] [FiniteDimensional ℂ E] (N : UISeminorm E)
    (b : OrthonormalBasis (Fin n) ℂ E) (x : Fin n → ℝ) : ℝ :=
  N.toFun (diagOp b x)

/-- Append one trailing zero to a finite vector of singular values. -/
def zeroPad {n : ℕ} (x : Fin n → ℝ) : Fin (n + 1) → ℝ :=
  Fin.lastCases 0 x

/-- A dimension-coherent normalized symmetric norming function.

This is the Challenge's canonical presentation of the source norm quantifier.
The source's broader unitary-invariant-norm class is related to it by the
formalized Fan-dominance equivalence described above. -/
structure SymmetricNormingFunction where
  /-- A unitarily invariant seminorm in each finite dimension. -/
  finiteNorm : ∀ n : ℕ, UISeminorm (EuclideanSpace ℂ (Fin n))
  /-- Normalisation on a single unit singular value. -/
  normalized :
    (finiteNorm 1).gauge (EuclideanSpace.basisFun (Fin 1) ℂ) (fun _ => 1) = 1
  /-- Appending a zero singular value does not change the value. -/
  zero_pad : ∀ {n : ℕ} (x : Fin n → ℝ),
    (finiteNorm (n + 1)).gauge (EuclideanSpace.basisFun (Fin (n + 1)) ℂ)
        (zeroPad x) =
      (finiteNorm n).gauge (EuclideanSpace.basisFun (Fin n) ℂ) x

/-- The extended symmetric-norming value of a scalar sequence: the supremum
over its finite prefixes.  A norm of `tan Θ` is evaluated on the sequence
`tan θ₁, tan θ₂, …`. -/
noncomputable def SymmetricNormingFunction.evalSeq (N : SymmetricNormingFunction) (s : ℕ → ℝ) :
  ℝ≥0∞ :=
  ⨆ n : ℕ, ENNReal.ofReal
    ((N.finiteNorm n).gauge (EuclideanSpace.basisFun (Fin n) ℂ)
      (fun i => s (i : ℕ)))

/-- The sequence lies in the norm's ideal. -/
def SymmetricNormingFunction.SeqFinite (N : SymmetricNormingFunction) (s : ℕ → ℝ) : Prop :=
  N.evalSeq s ≠ ⊤

/-- The real-valued norm of a sequence, meaningful on the ideal. -/
noncomputable def SymmetricNormingFunction.seqNorm (N : SymmetricNormingFunction) (s : ℕ → ℝ) : ℝ :=
  (N.evalSeq s).toReal

section NormEval

variable {𝕜 : Type u} [RCLike 𝕜]
variable {E : Type v} [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
variable {F : Type v} [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]

/-- The symmetric-norming extended value on an operator: its value on the
singular-value sequence, and `⊤` exactly off the associated ideal. -/
noncomputable def SymmetricNormingFunction.eval (N : SymmetricNormingFunction) (T : E →L[𝕜] F) :
  ℝ≥0∞ :=
  N.evalSeq (fun n => singularValue T n)

/-- The operator lies in the norm's ideal. -/
def SymmetricNormingFunction.Finite (N : SymmetricNormingFunction) (T : E →L[𝕜] F) : Prop :=
  N.eval T ≠ ⊤

/-- The real-valued norm, meaningful on the ideal. -/
noncomputable def SymmetricNormingFunction.norm (N : SymmetricNormingFunction) (T : E →L[𝕜] F) :
  ℝ := (N.eval T).toReal

end NormEval

end Norms

/-- A subspace with an orthogonal projection is closed, hence complete. -/
local instance instCompleteSpaceOfHasOrthogonalProjection {𝕜 : Type u} [RCLike 𝕜]
    {E : Type v} [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    (W : Submodule 𝕜 E) [W.HasOrthogonalProjection] : CompleteSpace W := by
  have hclosed : IsClosed (W : Set E) := by
    rw [← Submodule.orthogonal_orthogonal W]
    exact Submodule.isClosed_orthogonal _
  exact hclosed.completeSpace_coe

/-! ## 3. The paper's block data

Section 1 fixes a self-adjoint `A`, a bounded self-adjoint perturbation `H`, and
two reducing decompositions: `E₀` spans the trial subspace with block `A₀`, and
`F₀, F₁` span the exact subspaces of `A + H` with complementary block `Λ₁`.  The
residual is `R = (A + H) E₀ − E₀ A₀`.  Neither decomposition is assumed
spectral. -/

section BlockData

variable {𝕜 : Type u} [RCLike 𝕜]
variable {E F G K : Type v}
  [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
  [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
  [NormedAddCommGroup G] [InnerProductSpace 𝕜 G] [CompleteSpace G]
  [NormedAddCommGroup K] [InnerProductSpace 𝕜 K] [CompleteSpace K]

/-- A coordinate map is an isometry onto its range. -/
def IsIsometric (T : E →L[𝕜] F) : Prop := ∀ x, ‖T x‖ = ‖x‖

/-- The trial-coordinate half of the setup: `E₀` is an isometric coordinate map
for the trial subspace and `R` the residual `A E₀ − E₀ A₀`; `A₀` is a partial
map, so it may be unbounded. -/
structure IsTrialResidual (A : E →ₗ.[𝕜] E) (A₀ : F →ₗ.[𝕜] F)
    (E₀ : F →L[𝕜] E) (R : F →L[𝕜] E) : Prop where
  /-- The trial coordinate map is isometric. -/
  isometry : IsIsometric E₀
  /-- It carries the trial domain into the ambient domain. -/
  mapsDomain : ∀ x : A₀.domain, E₀ (x : F) ∈ A.domain
  /-- `R` is the residual there. -/
  residualEquation : ∀ x : A₀.domain,
    A ⟨E₀ (x : F), mapsDomain x⟩ - E₀ (A₀ x) = R (x : F)

/-- The exact-coordinate half: `F₀` and `F₁` are complementary exhaustive
isometries and `F₁` intertwines `A` with the complementary block `Λ₁`. -/
structure IsExactDecomposition (A : E →ₗ.[𝕜] E) (Λ₁ : G →ₗ.[𝕜] G)
    (F₀ : K →L[𝕜] E) (F₁ : G →L[𝕜] E) : Prop where
  /-- The desired coordinate map is isometric. -/
  desiredIsometry : IsIsometric F₀
  /-- The complementary coordinate map is isometric. -/
  complementIsometry : IsIsometric F₁
  /-- The two ranges are orthogonal. -/
  orthogonal : F₀.adjoint ∘L F₁ = 0
  /-- Together they exhaust the space. -/
  complete : F₀ ∘L F₀.adjoint + F₁ ∘L F₁.adjoint = ContinuousLinearMap.id 𝕜 E
  /-- `F₁` carries the block domain into the ambient domain. -/
  mapsDomain : ∀ y : Λ₁.domain, F₁ (y : G) ∈ A.domain
  /-- and intertwines the two operators there. -/
  intertwines : ∀ y : Λ₁.domain, A ⟨F₁ (y : G), mapsDomain y⟩ = F₁ (Λ₁ y)

/-- **The trial data of a subspace**, in the source's own shape `(1.8)`:
a trial operator `A₀` on the subspace, possibly unbounded, and a *bounded*
residual `R` with `A z = A₀ z + R z` on the trial domain.  The compression is a
partial map because the Appendix to Section 6 allows the tangent theorem's `A₀`
to be unbounded. -/
structure TrialBlock (A : E →ₗ.[𝕜] E) (U : Submodule 𝕜 E)
    [U.HasOrthogonalProjection] where
  /-- The trial block `A₀`, a partial map on the trial subspace. -/
  compression : U →ₗ.[𝕜] U
  /-- `A₀` is self-adjoint. -/
  compression_selfAdjoint : IsSelfAdjoint compression
  /-- The bounded residual `R`. -/
  residual : U →L[𝕜] E
  /-- Trial vectors in the compression's domain lie in the ambient domain. -/
  mem_domain : ∀ z : compression.domain, ((z : U) : E) ∈ A.domain
  /-- and there `A z = A₀ z + R z`, which is `(1.8)`. -/
  action_eq : ∀ z : compression.domain,
    A ⟨((z : U) : E), mem_domain z⟩ =
      ((compression z : U) : E) + residual ((z : U))

/-- **The trial data of a subspace with a bounded compression**, in the source's
shape `(1.8)`: a bounded self-adjoint `A₀` on a trial subspace inside `dom A`,
and a bounded residual `R` with `A z = A₀ z + R z` there.

The Appendix to Section 6 relaxes the sine family -- the `sin Θ` theorem,
Proposition 6.1 and Theorem 6.1 -- to allow **one** of `A₀`, `Λ₁` to be
unbounded, and reserves "both may be unbounded" for the tangent theorem.  Here
the unwanted exact block is the unbounded one. -/
structure BoundedTrialBlock (A : E →ₗ.[𝕜] E) (U : Submodule 𝕜 E)
    [U.HasOrthogonalProjection] where
  /-- The trial block `A₀`, bounded on the trial subspace. -/
  compression : U →L[𝕜] U
  /-- `A₀` is self-adjoint. -/
  compression_selfAdjoint : IsSelfAdjoint compression
  /-- The bounded residual `R`. -/
  residual : U →L[𝕜] E
  /-- The trial subspace lies inside the ambient domain. -/
  mem_domain : ∀ z : U, ((z : U) : E) ∈ A.domain
  /-- and there `A z = A₀ z + R z`, which is `(1.8)`. -/
  action_eq : ∀ z : U,
    A ⟨((z : U) : E), mem_domain z⟩ = ((compression z : U) : E) + residual z

/-- **Rayleigh--Ritz trial data**: trial data whose residual is orthogonal to the
trial subspace.  This is the source's `H₀ = 0` in the form `(1.8)` takes when
`A₀ = E₀^*(A+H)E₀`, the extra hypothesis the `tan Θ` theorem imposes and the
`sin Θ` and `sin 2Θ` theorems do not. -/
structure RitzData (A : E →ₗ.[𝕜] E) (U : Submodule 𝕜 E)
    [U.HasOrthogonalProjection] extends TrialBlock A U where
  /-- The residual is orthogonal to the trial subspace. -/
  residual_orthogonal : ∀ z z' : U, ⟪residual z, ((z' : U) : E)⟫_𝕜 = 0

end BlockData

/-! ## 4. The source separation -/

section Separation

variable {𝕜 : Type u} [RCLike 𝕜]
variable {E : Type v} [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
variable {F : Type v} [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]

/-- The real resolvent set: the shifted operator has a bounded two-sided
inverse. -/
def realResolventSet (A : E →ₗ.[𝕜] E) : Set ℝ :=
  {lam : ℝ | ∃ R : E →L[𝕜] E,
      (∀ x : A.domain, R (A x - (lam : 𝕜) • (x : E)) = (x : E)) ∧
      (∀ y : E, ∃ h : R y ∈ A.domain,
        A ⟨R y, h⟩ - (lam : 𝕜) • R y = y)}

/-- The real spectrum. -/
def realSpectrum (A : E →ₗ.[𝕜] E) : Set ℝ := (realResolventSet A)ᶜ

/-- The quadratic form of `A` is at least `c` on its domain. -/
def SemiboundedBelow (A : E →ₗ.[𝕜] E) (c : ℝ) : Prop :=
  ∀ x : A.domain, c * ‖(x : E)‖ ^ 2 ≤ RCLike.re ⟪A x, (x : E)⟫_𝕜

/-- The quadratic form of `A` is at most `c` on its domain. -/
def SemiboundedAbove (A : E →ₗ.[𝕜] E) (c : ℝ) : Prop :=
  ∀ x : A.domain, RCLike.re ⟪A x, (x : E)⟫_𝕜 ≤ c * ‖(x : E)‖ ^ 2

/-- **The source separation of two blocks by a gap of width `δ`.**
`intervalExterior` is the printed interval/exterior condition, symmetric in the
two blocks; the two ordered constructors are the half-infinite configurations the
source explicitly permits, in which both blocks may have unbounded spectrum. -/
inductive SylvesterGap (A : E →ₗ.[𝕜] E) (B : F →ₗ.[𝕜] F) (δ : ℝ) : Prop where
  | intervalExterior {β α : ℝ} (hβα : β ≤ α)
      (hgap :
        (realSpectrum A ⊆ Set.Icc β α ∧
          realSpectrum B ⊆ {x | x ≤ β - δ ∨ α + δ ≤ x}) ∨
        (realSpectrum B ⊆ Set.Icc β α ∧
          realSpectrum A ⊆ {x | x ≤ β - δ ∨ α + δ ≤ x}))
  | leftAboveRightBelow (c : ℝ)
      (hA : SemiboundedBelow A (c + δ)) (hB : SemiboundedAbove B c)
  | leftBelowRightAbove (c : ℝ)
      (hA : SemiboundedAbove A c) (hB : SemiboundedBelow B (c + δ))

/-- **The oriented separation printed in the `sin 2Θ` theorem.**
The first block is the source's `Λ₀` and the second is `Λ₁`: for a finite
interval, `Λ₀` lies inside `[β, α]` while `Λ₁` lies outside the enlarged open
interval `(β - δ, α + δ)`.  The second constructor is exactly the lower
half-line extension stated immediately after the four Section 2 theorems.  This
is intentionally narrower than `SylvesterGap`, whose interval constructor is
symmetric and is appropriate for the printed `sin Θ` theorem. -/
inductive SinTwoThetaGap (A : E →ₗ.[𝕜] E) (B : F →ₗ.[𝕜] F) (δ : ℝ) : Prop where
  | intervalExterior {β α : ℝ} (hβα : β ≤ α)
      (hA : realSpectrum A ⊆ Set.Icc β α)
      (hB : realSpectrum B ⊆ {x | x ≤ β - δ ∨ α + δ ≤ x})
  | leftBelowRightAbove (c : ℝ)
      (hA : SemiboundedAbove A c) (hB : SemiboundedBelow B (c + δ))

end Separation

/-! ## 5. Reducing subspaces and their blocks

Section 1 says in as many words that neither `P` nor `Q` is assumed to be a
spectral projector: what the theorems assume is that the decomposition *reduces*
the operator and that its two blocks are separated. -/

section Reducing

variable {𝕜 : Type u} [RCLike 𝕜]
variable {E : Type v} [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]

/-- A subspace reduces a partial map when both projections preserve its domain
and both summands are invariant. -/
def Reduces (A : E →ₗ.[𝕜] E) (U : Submodule 𝕜 E) [U.HasOrthogonalProjection] :
    Prop :=
  (∀ x : A.domain, U.starProjection (x : E) ∈ A.domain) ∧
  (∀ x : A.domain, Uᗮ.starProjection (x : E) ∈ A.domain) ∧
  (∀ x : A.domain, (x : E) ∈ U → A x ∈ U) ∧
  (∀ x : A.domain, (x : E) ∈ Uᗮ → A x ∈ Uᗮ)

/-- The block of `A` on a reducing subspace. -/
noncomputable def block (A : E →ₗ.[𝕜] E) (U : Submodule 𝕜 E)
    [U.HasOrthogonalProjection] (h : Reduces A U) : U →ₗ.[𝕜] U where
  domain :=
    { carrier := {x : U | (x : E) ∈ A.domain}
      zero_mem' := A.domain.zero_mem
      add_mem' := fun hx hy => A.domain.add_mem hx hy
      smul_mem' := fun c _ hx => A.domain.smul_mem c hx }
  toFun :=
    { toFun := fun x => ⟨A ⟨((x : U) : E), x.2⟩, h.2.2.1 _ ((x : U)).2⟩
      map_add' := fun x y => by
        apply Subtype.ext
        exact congrArg (fun z : A.domain => (A z : E)) (Subtype.ext rfl) |>.trans
          (A.map_add ⟨((x : U) : E), x.2⟩ ⟨((y : U) : E), y.2⟩)
      map_smul' := fun c x => by
        apply Subtype.ext
        exact congrArg (fun z : A.domain => (A z : E)) (Subtype.ext rfl) |>.trans
          (A.map_smul c ⟨((x : U) : E), x.2⟩) }

/-- Adding a bounded operator to a partial map, on the same domain. -/
noncomputable def addBounded (A : E →ₗ.[𝕜] E) (V : E →L[𝕜] E) : E →ₗ.[𝕜] E where
  domain := A.domain
  toFun := A.toFun + V.toLinearMap.domRestrict A.domain

omit [CompleteSpace E] in
/-- The orthogonal complement of a reducing subspace also reduces the operator,
so the ambient separation hypothesis can name both blocks. -/
theorem Reduces.orthogonal {A : E →ₗ.[𝕜] E} {U : Submodule 𝕜 E}
    [U.HasOrthogonalProjection] (h : Reduces A U) : Reduces A Uᗮ := by
  obtain ⟨h₁, h₂, h₃, h₄⟩ := h
  refine ⟨h₂, ?_, h₄, ?_⟩
  · intro x
    simpa only [Submodule.orthogonal_orthogonal] using h₁ x
  · intro x hx
    rw [Submodule.orthogonal_orthogonal] at hx ⊢
    exact h₃ x hx

end Reducing

/-! ## 6. The angle quantities

The *sines* are explicit operators; the *tangents* are sequences, `‖tan Θ‖` being
the norm's value on `tan θ₁, tan θ₂, …`. -/

section Angles

variable {𝕜 : Type u} [RCLike 𝕜]
variable {E F K : Type v}
  [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
  [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
  [NormedAddCommGroup K] [InnerProductSpace 𝕜 K] [CompleteSpace K]

/-- `sin Θ₀` in coordinates: the part of the trial coordinate map that misses the
exact subspace, the source's `Q^⊥E₀`. -/
noncomputable def directedSine (E₀ : F →L[𝕜] E) (F₀ : K →L[𝕜] E) : F →L[𝕜] E :=
  (ContinuousLinearMap.id 𝕜 E - F₀ ∘L F₀.adjoint) ∘L E₀

/-- `sin Θ₀` for a trial *subspace*: `Q^⊥E₀ = P_{Vᗮ}|_U`. -/
noncomputable def directedSineBlock (U V : Submodule 𝕜 E)
     [V.HasOrthogonalProjection] : U →L[𝕜] E :=
  Vᗮ.starProjection ∘L U.subtypeL

/-- `sin Θ`, the ambient sine: the projector difference, whose singular values
are the sines of the principal angles, each occurring twice. -/
noncomputable def ambientSine (U V : Submodule 𝕜 E)
    [U.HasOrthogonalProjection] [V.HasOrthogonalProjection] : E →L[𝕜] E :=
  V.starProjection - U.starProjection

/-- `sin 2Θ`, the ambient double-angle sine: the projector difference between `U`
and its mirror image in `V`.  Reflecting `U` in `V` doubles every principal
angle. -/
noncomputable def ambientDoubleSine (U V : Submodule 𝕜 E)
    [U.HasOrthogonalProjection] [V.HasOrthogonalProjection] : E →L[𝕜] E :=
  (U.map (V.reflection.toLinearEquiv : E →ₗ[𝕜] E)).starProjection - U.starProjection

/-- `sin 2Θ₀`, the directed double-angle sine. -/
noncomputable def directedDoubleSine (U V : Submodule 𝕜 E)
    [U.HasOrthogonalProjection] [V.HasOrthogonalProjection] : E →L[𝕜] E :=
  U.starProjection ∘L
    (Uᗮ.map (V.reflection.toLinearEquiv : E →ₗ[𝕜] E)).starProjection

/-! ### Tangents of an angle presented by its sine

The argument of `tanSeq` is always a sine: `tan Θ₀` is a trigonometric function
of the *angle*, presented here by an operator whose singular values are its
sines.  The residual is the right-hand side and has nothing to do with the
left.

**A doubled angle is presented by its own sine, never by doubling the ordered
sines of the single angle.**  `θ ↦ sin 2θ` is not monotone on `[0, π/2]`, so
`n ↦ sin (2 arcsin (aₙ(sin Θ)))` need not be the ordered singular-value sequence
of `sin 2Θ` -- at principal angles `75°` and `30°` the two sequences are in
opposite order.  The `tan 2Θ` clauses below therefore read the doubled tangent
off `ambientDoubleSine` and `directedDoubleSine`, through the same monotone
`u ↦ tan (arcsin u)` that `tan Θ` uses, and `|tan 2θ| = tan (arcsin |sin 2θ|)`
supplies the source's absolute value with no branch choice. -/

/-- The sequence `tan θ₀, tan θ₁, …`, where `sin θₙ` is the `n`-th singular value
of the sine operator `S`. -/
noncomputable def tanSeq {X Y : Type v}
    [NormedAddCommGroup X] [InnerProductSpace 𝕜 X]
    [NormedAddCommGroup Y] [InnerProductSpace 𝕜 Y]
    (S : X →L[𝕜] Y) (n : ℕ) : ℝ :=
  Real.tan (Real.arcsin (singularValue S n))

/-- **No principal angle of `S` is a right angle**, so every `tan θₙ` is a
genuine tangent rather than the value Lean's field division assigns at a pole.
Equivalently `‖S‖ < 1`, since `a₀ S = ‖S‖`.  Davis and Kahan derive this rather
than assuming it, so it appears below as a conclusion -- for the double-angle
clauses too, where `S` is the double-angle sine and the condition is the
quarter-turn exclusion `‖sin 2Θ‖ < 1`. -/
def TangentDefined {X Y : Type v}
    [NormedAddCommGroup X] [InnerProductSpace 𝕜 X]
    [NormedAddCommGroup Y] [InnerProductSpace 𝕜 Y]
    (S : X →L[𝕜] Y) : Prop :=
  ∀ n, Real.cos (Real.arcsin (singularValue S n)) ≠ 0


end Angles

end RotationOfEigenvectors
