/-
Copyright (c) 2026 Dmitrii Zakharov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dmitrii Zakharov
-/
module


public import LeanPool.ErdosGinzburgZiv.EGZ.Convex.FiniteHull
public import LeanPool.ErdosGinzburgZiv.EGZ.ConvexFlag.FaceModel
public import LeanPool.ErdosGinzburgZiv.EGZ.ConvexFlag.Helly
public import Mathlib.Analysis.Convex.Independent

/-!
# The face-flag Helly bound used in Theorem 1.12

This file is an intentionally stronger regression check than merely storing
the inequality `hellyConstant Ω ≤ hollowPolytopeNumber d` in a face-flag
adapter.  It separates the proof in the paper into three cases (a repeated
physical point, failure of convex position, and the hollow-polytope case),
and proves that the resulting physical certificate contradicts Helly
independence.

The two face/lattice facts used by the reduction are stated independently of
Helly constants:

* physical affine combinations lift to flag convex combinations; and
* an affine-integer-span certificate on the positive support makes the lift
  integral.

The canonical face model in `EGZ.ConvexFlag.FaceModel` now proves both facts.
This file also proves that a nonvertex intrinsic integer point of a finite
convex hull admits the required nontrivial positive-support representation.

The polytope in this file is the *working polytope*
`convexHull ℝ (Function.support w)` from the first paragraph of the proof of
Theorem 1.12, not necessarily the polytope in the theorem statement.  This
distinction is essential: an unsupported zero-dimensional face has no
affine lattice generated by the support.
-/

@[expose] public section

open scoped BigOperators

namespace EGZ

/-- A physical convex combination with no coefficient equal to one. -/
structure PhysicalNontrivialCombination {d n : ℕ} (P : RationalPolytope d)
    (points : Fin n → RealCoord d) where
  /-- Point represented by the convex combination. -/
  result : RealCoord d
  result_mem : result ∈ P.carrier
  /-- Nonnegative coefficients of the convex combination. -/
  weight : Fin n → ℝ
  nonnegative : ∀ i, 0 ≤ weight i
  sum_eq_one : (∑ i, weight i) = 1
  barycenter : result = ∑ i, weight i • points i
  nontrivial : ∀ i, weight i ≠ 1

namespace PhysicalNontrivialCombination

/-- The physical points occurring with strictly positive coefficient. -/
def activeSet {d n : ℕ} {P : RationalPolytope d}
    {points : Fin n → RealCoord d}
    (c : PhysicalNontrivialCombination P points) : Set (RealCoord d) :=
  points '' {i | 0 < c.weight i}

/-- The certificate produced in the hollow-polytope case: the result is in
the affine integer span of the points used with positive coefficient. -/
def IsActiveSpanIntegral {d n : ℕ} {P : RationalPolytope d}
    {points : Fin n → RealCoord d}
    (c : PhysicalNontrivialCombination P points) : Prop :=
  c.result ∈ affineIntSpan c.activeSet

end PhysicalNontrivialCombination

private theorem weight_ne_one_of_barycenter_not_mem_range
    {d n : ℕ} {points : Fin n → RealCoord d} {q : RealCoord d}
    (weight : Fin n → ℝ) (hweight0 : ∀ i, 0 ≤ weight i)
    (hweightsum : (∑ i, weight i) = 1)
    (hbary : q = ∑ i, weight i • points i)
    (hqnotrange : q ∉ Set.range points) : ∀ i, weight i ≠ 1 := by
  intro i hi
  have hsum_erase : ∑ j ∈ (Finset.univ.erase i), weight j = 0 := by
    have hdecomp := Finset.sum_erase_add (s := Finset.univ)
      (f := weight) (Finset.mem_univ i)
    rw [hweightsum, hi] at hdecomp
    linarith
  have hzero : ∀ j, j ≠ i → weight j = 0 := by
    intro j hji
    have hj : j ∈ Finset.univ.erase i := by simp [hji]
    exact (Finset.sum_eq_zero_iff_of_nonneg
      (fun z _ ↦ hweight0 z)).mp hsum_erase j hj
  have hbar : (∑ j, weight j • points j) = points i := by
    rw [Finset.sum_eq_single i]
    · simp [hi]
    · intro j _ hji
      simp [hzero j hji]
    · simp
  exact hqnotrange ⟨i, (hbary.trans hbar).symm⟩

/-- A nonvertex intrinsic integer point of a finite convex hull has a
nontrivial convex representation whose positive support certifies its
affine integer span.

The construction first averages all indexed vertices on the minimal face.
If that centroid is not the given point, relative-interior extension writes
the point strictly between the centroid and another point of the face.  A
convex representation of the latter point then completes the desired
representation while retaining every face vertex with positive weight. -/
theorem FiniteHullModel.nonvertex_intrinsic_combination
    {d n : ℕ} {points : Fin n → RealCoord d}
    (H : FiniteHullModel points) (q : RealCoord d)
    (hqmem : q ∈ H.polytope.carrier)
    (hqintrinsic : H.polytope.IsIntrinsicInteger q)
    (hqnotvertex : q ∉ H.polytope.vertexSet) :
    ∃ c : PhysicalNontrivialCombination H.polytope points,
      c.result = q ∧ c.IsActiveSpanIntegral := by
  classical
  obtain ⟨F, hqrel, k, certPoints, coeff, hcert, hcoeffsum, hcertsum⟩ :=
    hqintrinsic
  have hk : 0 < k := by
    by_contra hk0
    have : k = 0 := Nat.eq_zero_of_not_pos hk0
    subst k
    simp at hcoeffsum
  let faceIndices : Finset (Fin n) :=
    Finset.univ.filter (fun i ↦ points i ∈ F.carrier)
  have hfaceIndices : faceIndices.Nonempty := by
    have hcert0 := (hcert ⟨0, hk⟩).1
    rw [H.vertexSet_eq] at hcert0
    obtain ⟨i, hi⟩ := hcert0
    refine ⟨i, ?_⟩
    simp only [faceIndices, Finset.mem_filter, Finset.mem_univ, true_and]
    rw [hi]
    exact (hcert ⟨0, hk⟩).2
  let faceWeight : Fin n → ℝ := fun i ↦
    if i ∈ faceIndices then (faceIndices.card : ℝ)⁻¹ else 0
  have hfaceWeight0 : ∀ i, 0 ≤ faceWeight i := by
    intro i
    simp only [faceWeight]
    split_ifs <;> positivity
  have hfaceWeightsum : (∑ i, faceWeight i) = 1 := by
    simp only [faceWeight, ← Finset.sum_filter]
    rw [Finset.sum_const, nsmul_eq_mul]
    simp [hfaceIndices.ne_empty]
  let x : RealCoord d := ∑ i, faceWeight i • points i
  have hxF : x ∈ F.carrier := by
    rw [show x = ∑ i ∈ faceIndices,
        (faceIndices.card : ℝ)⁻¹ • points i by
      simp [x, faceWeight]]
    apply F.convex.sum_mem
    · intro i hi
      positivity
    · rw [Finset.sum_const, nsmul_eq_mul]
      simp [hfaceIndices.ne_empty]
    · intro i hi
      exact (Finset.mem_filter.mp hi).2
  by_cases hqx : q = x
  · subst x
    let weight := faceWeight
    have hactive : H.polytope.vertexSet ∩ F.carrier ⊆
        points '' {i | 0 < weight i} := by
      rintro y ⟨hyvertex, hyF⟩
      rw [H.vertexSet_eq] at hyvertex
      obtain ⟨i, rfl⟩ := hyvertex
      refine ⟨i, ?_, rfl⟩
      have hi : i ∈ faceIndices := by
        simp [faceIndices, hyF]
      change 0 < weight i
      simp only [weight, faceWeight, hi, ite_eq_left]
      apply inv_pos.mpr
      exact_mod_cast (Finset.card_pos.mpr hfaceIndices)
    refine ⟨{
      result := q
      result_mem := hqmem
      weight := weight
      nonnegative := hfaceWeight0
      sum_eq_one := hfaceWeightsum
      barycenter := hqx
      nontrivial := weight_ne_one_of_barycenter_not_mem_range
        (points := points) (q := q) weight hfaceWeight0 hfaceWeightsum hqx
        (by
          intro hqrange
          apply hqnotvertex
          rw [H.vertexSet_eq]
          exact hqrange) }, rfl, ?_⟩
    exact ⟨k, certPoints, coeff, fun i ↦ hactive (hcert i),
      hcoeffsum, hcertsum⟩
  · obtain ⟨z, hzF, a, b, ha, hb, hab, haxb⟩ :=
      exists_openSegment_of_mem_intrinsicInterior hqrel hxF hqx
    have hzP : z ∈ H.polytope.carrier := F.subset_polytope hzF
    rw [H.carrier_eq, convexHull_range_eq_exists_affineCombination] at hzP
    obtain ⟨s, wz, hwz0, hwzsum, hwzaff⟩ := hzP
    let zWeight : Fin n → ℝ := fun i ↦ if i ∈ s then wz i else 0
    have hzWeight0 : ∀ i, 0 ≤ zWeight i := by
      intro i
      by_cases hi : i ∈ s
      · simp [zWeight, hi, hwz0 i hi]
      · simp [zWeight, hi]
    have hzWeightsum : (∑ i, zWeight i) = 1 := by
      rw [show (∑ i, zWeight i) = ∑ i ∈ s, wz i by simp [zWeight]]
      exact hwzsum
    have hzbar : z = ∑ i, zWeight i • points i := by
      rw [show (∑ i, zWeight i • points i) =
          ∑ i ∈ s, wz i • points i by simp [zWeight]]
      rw [← Finset.affineCombination_eq_linear_combination s points wz hwzsum]
      exact hwzaff.symm
    let weight : Fin n → ℝ := fun i ↦ a * faceWeight i + b * zWeight i
    have hweight0 : ∀ i, 0 ≤ weight i := by
      intro i
      exact add_nonneg (mul_nonneg ha.le (hfaceWeight0 i))
        (mul_nonneg hb.le (hzWeight0 i))
    have hweightsum : (∑ i, weight i) = 1 := by
      calc
        (∑ i, weight i) = a * (∑ i, faceWeight i) +
            b * (∑ i, zWeight i) := by
          rw [show (∑ i, weight i) =
              (∑ i, a * faceWeight i) + (∑ i, b * zWeight i) by
            simp [weight, Finset.sum_add_distrib]]
          rw [Finset.mul_sum, Finset.mul_sum]
        _ = 1 := by
          rw [hfaceWeightsum, hzWeightsum]
          simpa using hab
    have hbary : q = ∑ i, weight i • points i := by
      calc
        q = a • x + b • z := haxb.symm
        _ = a • (∑ i, faceWeight i • points i) +
            b • (∑ i, zWeight i • points i) := by rw [hzbar]
        _ = ∑ i, weight i • points i := by
          simp [weight, add_smul, mul_smul, Finset.sum_add_distrib,
            Finset.smul_sum]
    have hactive : H.polytope.vertexSet ∩ F.carrier ⊆
        points '' {i | 0 < weight i} := by
      rintro y ⟨hyvertex, hyF⟩
      rw [H.vertexSet_eq] at hyvertex
      obtain ⟨i, rfl⟩ := hyvertex
      refine ⟨i, ?_, rfl⟩
      have hi : i ∈ faceIndices := by simp [faceIndices, hyF]
      have hfacepos : 0 < faceWeight i := by
        simp only [faceWeight, hi, ite_eq_left]
        apply inv_pos.mpr
        exact_mod_cast (Finset.card_pos.mpr hfaceIndices)
      exact add_pos_of_pos_of_nonneg (mul_pos ha hfacepos)
        (mul_nonneg hb.le (hzWeight0 i))
    refine ⟨{
      result := q
      result_mem := hqmem
      weight := weight
      nonnegative := hweight0
      sum_eq_one := hweightsum
      barycenter := hbary
      nontrivial := weight_ne_one_of_barycenter_not_mem_range
        (points := points) (q := q) weight hweight0 hweightsum hbary
        (by
          intro hqrange
          apply hqnotvertex
          rw [H.vertexSet_eq]
          exact hqrange) }, rfl, ?_⟩
    exact ⟨k, certPoints, coeff, fun i ↦ hactive (hcert i),
      hcoeffsum, hcertsum⟩

/-- Pure convex/lattice geometry needed for the hollow-polytope case.

The finite rational hull, its vertex identification, and the positive-support
nonvertex representation are now unconditional.  The remaining field is the
boundedness property required by the `sSup` definition of `L(d)`. -/
structure HollowPolytopeGeometry (d : ℕ) where
  hollowCounts_bddAbove :
    BddAbove {n : ℕ | AdmitsHollowPolytopeVertexCount d n}

namespace HollowPolytopeGeometry

/-- Boundedness makes the `sSup` definition of `L(d)` an actual upper
bound.  Without this hypothesis, `sSup` of an unbounded set of naturals is
zero, so this step cannot be recovered from the bare definition. -/
theorem hollowCard_le {d : ℕ} (G : HollowPolytopeGeometry d)
    (Q : RationalPolytope d) (hQ : Q.IsHollow) :
    Q.vertexSet.ncard ≤ hollowPolytopeNumber d := by
  unfold hollowPolytopeNumber
  apply le_csSup G.hollowCounts_bddAbove
  exact ⟨Q, hQ, rfl⟩

/-- The paper's hollow-polytope branch, derived from the explicit geometric
obligations above. -/
theorem hollowCase {d n : ℕ} (G : HollowPolytopeGeometry d)
    (points : Fin n → RealCoord d) (hinjective : Function.Injective points)
    (hrational : ∀ i, IsRational (points i))
    (hconvex : IsInConvexPosition points)
    (hlarge : hollowPolytopeNumber d < n) :
    ∃ (H : FiniteHullModel points)
      (c : PhysicalNontrivialCombination H.polytope points),
      c.IsActiveSpanIntegral := by
  classical
  have hnpos : 0 < n := lt_of_le_of_lt (Nat.zero_le _) hlarge
  let H := finiteHullModel points hnpos hinjective hrational hconvex
  have hcard : H.polytope.vertexSet.ncard = n := by
    rw [H.vertexSet_eq, Set.ncard_range_of_injective hinjective]
    simp
  have hnotHollow : ¬ H.polytope.IsHollow := by
    intro hhollow
    have hle := G.hollowCard_le H.polytope hhollow
    rw [hcard] at hle
    exact (Nat.not_le_of_lt hlarge) hle
  rw [RationalPolytope.IsHollow] at hnotHollow
  push Not at hnotHollow
  obtain ⟨q, hqmem, hqint, hqnotvertex⟩ := hnotHollow
  obtain ⟨c, rfl, hcspan⟩ :=
    H.nonvertex_intrinsic_combination q hqmem hqint hqnotvertex
  exact ⟨H, c, hcspan⟩

end HollowPolytopeGeometry

namespace FaceFlagCombinationLaws

/-- Failure of convex position already supplies the nontrivial integral
combination from the second case in the paper. -/
theorem of_not_convexPosition {d n : ℕ} {P : RationalPolytope d}
    {A : FaceFlagModel P} (laws : FaceFlagCombinationLaws A)
    (points : Fin n → A.flag.Point)
    (hproper : ∀ i, points i ∈ A.proper)
    (hintegral : ∀ i, (points i).IsIntegral)
    (hnotconvex :
      ¬ IsInConvexPosition (fun i ↦ A.physical (points i) (hproper i))) :
    ∃ (weight : Fin n → ℝ) (result : A.flag.Point),
      ConvexFlag.ConvexCombination points weight result ∧
        result.IsIntegral ∧ ∀ i, weight i ≠ 1 := by
  classical
  unfold IsInConvexPosition at hnotconvex
  push Not at hnotconvex
  obtain ⟨i, weight, hnonnegative, hsum, hbarycenter, hnontrivial⟩ := hnotconvex
  refine ⟨weight, points i, ?_, hintegral i, hnontrivial⟩
  exact laws.combination_of_physical points hproper weight (points i) (hproper i)
    hnonnegative hsum hbarycenter

/-- A repeated physical point supplies the half-half combination from the
first case in the paper. -/
theorem of_physical_duplicate {d n : ℕ} {P : RationalPolytope d}
    {A : FaceFlagModel P} (laws : FaceFlagCombinationLaws A)
    (points : Fin n → A.flag.Point)
    (hproper : ∀ i, points i ∈ A.proper)
    (hintegral : ∀ i, (points i).IsIntegral)
    {i j : Fin n} (hij : i ≠ j)
    (hphysical : A.physical (points i) (hproper i) =
      A.physical (points j) (hproper j)) :
    ∃ (weight : Fin n → ℝ) (result : A.flag.Point),
      ConvexFlag.ConvexCombination points weight result ∧
        result.IsIntegral ∧ ∀ k, weight k ≠ 1 := by
  classical
  let weight : Fin n → ℝ := fun k ↦
    (if k = i then (1 / 2 : ℝ) else 0) +
      (if k = j then (1 / 2 : ℝ) else 0)
  have hnonnegative : ∀ k, 0 ≤ weight k := by
    intro k
    simp only [weight]
    split_ifs <;> positivity
  have hsum : (∑ k, weight k) = 1 := by
    rw [show (∑ k, weight k) =
        (∑ k, if k = i then (1 / 2 : ℝ) else 0) +
          ∑ k, if k = j then (1 / 2 : ℝ) else 0 by
      simp only [weight, Finset.sum_add_distrib]]
    simp
    norm_num
  have hbarycenter :
      A.physical (points i) (hproper i) =
        ∑ k, weight k • A.physical (points k) (hproper k) := by
    rw [show (∑ k, weight k • A.physical (points k) (hproper k)) =
        (∑ k, (if k = i then (1 / 2 : ℝ) else 0) •
          A.physical (points k) (hproper k)) +
        (∑ k, (if k = j then (1 / 2 : ℝ) else 0) •
          A.physical (points k) (hproper k)) by
      simp only [weight, add_smul, Finset.sum_add_distrib]]
    simp only [ite_smul, zero_smul, Fintype.sum_ite_eq']
    rw [← hphysical, ← add_smul]
    norm_num
  have hnontrivial : ∀ k, weight k ≠ 1 := by
    intro k
    simp only [weight]
    split_ifs with hki hkj
    · exact (hij (hki.symm.trans hkj)).elim
    · norm_num
    · norm_num
    · norm_num
  refine ⟨weight, points i, ?_, hintegral i, hnontrivial⟩
  exact laws.combination_of_physical points hproper weight (points i) (hproper i)
    hnonnegative hsum hbarycenter

/-- The hollow-polytope case lifts the intrinsic integer certificate through
the face-lattice compatibility law. -/
theorem of_hollowCase {d n : ℕ} {P : RationalPolytope d}
    {A : FaceFlagModel P} (laws : FaceFlagCombinationLaws A)
    (points : Fin n → A.flag.Point)
    (hproper : ∀ i, points i ∈ A.proper)
    (hintegral : ∀ i, (points i).IsIntegral)
    (c : PhysicalNontrivialCombination P
      (fun i ↦ A.physical (points i) (hproper i)))
    (hcspan : c.IsActiveSpanIntegral) :
    ∃ (weight : Fin n → ℝ) (result : A.flag.Point),
      ConvexFlag.ConvexCombination points weight result ∧
        result.IsIntegral ∧ ∀ i, weight i ≠ 1 := by
  let result := A.lift c.result c.result_mem
  have hresult : result ∈ A.proper := A.lift_proper c.result c.result_mem
  have hphysical : A.physical result hresult =
      ∑ i, c.weight i • A.physical (points i) (hproper i) := by
    rw [A.physical_lift]
    exact c.barycenter
  have hcomb : ConvexFlag.ConvexCombination points c.weight result :=
    laws.combination_of_physical points hproper c.weight result hresult
      c.nonnegative c.sum_eq_one hphysical
  refine ⟨c.weight, result, hcomb, ?_, c.nontrivial⟩
  apply laws.integral_of_activeSpan points hproper hintegral c.weight result
    hresult hcomb
  simpa [result, PhysicalNontrivialCombination.IsActiveSpanIntegral,
    PhysicalNontrivialCombination.activeSet] using hcspan

/-- Full three-case reduction for a family larger than `L(d)`. -/
theorem exists_nontrivial_integral_combination_of_large
    {d n : ℕ} {P : RationalPolytope d}
    {A : FaceFlagModel P} (laws : FaceFlagCombinationLaws A)
    (G : HollowPolytopeGeometry d)
    (points : Fin n → A.flag.Point)
    (hproper : ∀ i, points i ∈ A.proper)
    (hintegral : ∀ i, (points i).IsIntegral)
    (hrational : ∀ i,
      IsRational (A.physical (points i) (hproper i)))
    (hlarge : hollowPolytopeNumber d < n) :
    ∃ (weight : Fin n → ℝ) (result : A.flag.Point),
      ConvexFlag.ConvexCombination points weight result ∧
        result.IsIntegral ∧ ∀ i, weight i ≠ 1 := by
  classical
  let physical : Fin n → RealCoord d :=
    fun i ↦ A.physical (points i) (hproper i)
  by_cases hinjective : Function.Injective physical
  · by_cases hconvex : IsInConvexPosition physical
    · obtain ⟨H, c, hcspan⟩ :=
        G.hollowCase physical hinjective (by simpa [physical] using hrational)
          hconvex hlarge
      have hresultP : c.result ∈ P.carrier := by
        have hrange : Set.range physical ⊆ P.carrier := by
          rintro x ⟨i, hi⟩
          rw [← hi]
          exact (A.properEquiv ⟨points i, hproper i⟩).2
        apply convexHull_min hrange P.convex
        rw [← H.carrier_eq]
        exact c.result_mem
      let cP : PhysicalNontrivialCombination P physical :=
        { result := c.result
          result_mem := hresultP
          weight := c.weight
          nonnegative := c.nonnegative
          sum_eq_one := c.sum_eq_one
          barycenter := c.barycenter
          nontrivial := c.nontrivial }
      have hcPspan : cP.IsActiveSpanIntegral := by
        exact hcspan
      exact laws.of_hollowCase points hproper hintegral cP hcPspan
    · exact laws.of_not_convexPosition points hproper hintegral (by
        simpa [physical] using hconvex)
  · obtain ⟨i, j, hphysical, hij⟩ := Function.not_injective_iff.mp hinjective
    exact laws.of_physical_duplicate points hproper hintegral hij (by
      simpa [physical] using hphysical)

/-- The desired face-flag bound, with no wholesale `helly_bound` hypothesis.
It follows by applying the three-case reduction to a hypothetical
Helly-independent family of excessive size. -/
theorem hellyConstant_le_hollowPolytopeNumber
    {d : ℕ} {P : RationalPolytope d}
    {A : FaceFlagModel P} (laws : FaceFlagCombinationLaws A)
    (G : HollowPolytopeGeometry d)
    (hrational : ∀ (q : A.flag.Point) (hq : q ∈ A.proper),
      q.IsIntegral → IsRational (A.physical q hq)) :
    ConvexFlag.hellyConstant A.proper ≤ hollowPolytopeNumber d := by
  obtain ⟨points, hind⟩ := ConvexFlag.hellyConstant_spec A.proper
  by_contra hle
  have hlarge : hollowPolytopeNumber d < ConvexFlag.hellyConstant A.proper :=
    Nat.lt_of_not_ge hle
  obtain ⟨weight, result, hcomb, hintegral, hnontrivial⟩ :=
    laws.exists_nontrivial_integral_combination_of_large G points hind.proper
      hind.integral
      (fun i ↦ hrational (points i) (hind.proper i) (hind.integral i)) hlarge
  obtain ⟨i, hi⟩ := hind.only_trivial weight result hcomb hintegral
  exact hnontrivial i hi

end FaceFlagCombinationLaws

end EGZ
