/-
Copyright (c) 2026 Dmitrii Zakharov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dmitrii Zakharov
-/

import LeanPool.ErdosGinzburgZiv.EGZ.Convex.Polytope
import LeanPool.ErdosGinzburgZiv.EGZ.Convex.LeastFaceInterior
import LeanPool.ErdosGinzburgZiv.EGZ.ConvexFlag.Centerpoint
import LeanPool.ErdosGinzburgZiv.EGZ.ConvexFlag.FaceModel
import LeanPool.ErdosGinzburgZiv.EGZ.Consistency.FaceFlagHellyBound

/-!
# Regression check for Theorem 1.12

This file isolates the geometric facts needed to pass from the centerpoint
theorem for convex flags to the polytope statement.  Following the proof in
the paper, the flag is built over the working polytope
`Q = convexHull ℝ (Function.support w)`, then its output is transported to
the minimal containing face of the original polytope `P`.

The file does not postulate that this support-hull face flag exists.  Instead
it verifies, without any local `sorry`, that the explicit construction
obligations below suffice.  In particular, the Helly bound is derived from
the three-case check in `FaceFlagHellyBound`, rather than stored as a field.
-/

open scoped BigOperators

namespace EGZ

/-- Every member of a set belongs to its affine integer span. -/
theorem mem_affineIntSpan_of_mem {d : ℕ} {S : Set (RealCoord d)}
    {q : RealCoord d} (hq : q ∈ S) : q ∈ affineIntSpan S := by
  refine ⟨1, fun _ ↦ q, fun _ ↦ 1, ?_, ?_, ?_⟩
  · exact fun _ ↦ hq
  · simp
  · simp

/-- The exact obligations supplied by the canonical face flag of the support
hull and by the reduction back to the original polytope.

It is essential that `model` presents `working`, not all of `P`: an
unsupported zero-dimensional face of `P` has no affine lattice generated by
the support.  The fields `outputFace` and `integral_output_span` encode the
paper's final passage from a face of `working` to the minimal containing face
of `P`. -/
structure SupportHullFaceFlagAdapter {d : ℕ} (P : RationalPolytope d)
    (w : RealCoord d → NNReal) where
  /-- Rational polytope given by the convex hull of the weighted support. -/
  working : RationalPolytope d
  working_carrier_eq :
    working.carrier = convexHull ℝ (Function.support w)
  working_subset_original : working.carrier ⊆ P.carrier
  /-- Face-flag model of the working support polytope. -/
  model : FaceFlagModel working
  laws : FaceFlagCombinationLaws model
  supportLift_integral : ∀ x (_hx : x ∈ Function.support w)
      (hxQ : x ∈ working.carrier),
    (model.lift x hxQ).IsIntegral
  integralPhysical_rational : ∀ (q : model.flag.Point)
      (hq : q ∈ model.proper),
    q.IsIntegral → IsRational (model.physical q hq)
  /-- Face of the original polytope assigned to each proper flag point. -/
  outputFace : {q : model.flag.Point // q ∈ model.proper} → P.Face
  physical_mem_output_relInterior : ∀
      (q : {q : model.flag.Point // q ∈ model.proper}),
    model.physical q.1 q.2 ∈ (outputFace q).relInterior
  integral_output_span : ∀
      (q : {q : model.flag.Point // q ∈ model.proper}),
    q.1.IsIntegral →
      model.physical q.1 q.2 ∈
        affineIntSpan (Function.support w ∩ (outputFace q).carrier)
  /-- Lift a physical affine functional to a linear function at the top flag node. -/
  topFunctional : (RealCoord d →ᵃ[ℝ] ℝ) → model.flag.LinearFunction
  topFunctional_base : ∀ xi, (topFunctional xi).base = ⊤
  topFunctional_eval : ∀ xi
      (q : {q : model.flag.Point // q ∈ model.proper})
      (hq : (topFunctional xi).EvaluableAt q.1),
    (topFunctional xi).eval q.1 hq = xi (model.physical q.1 q.2)

namespace SupportHullFaceFlagAdapter

/-- Every support point lies in the working support hull. -/
theorem support_mem_working {d : ℕ} {P : RationalPolytope d}
    {w : RealCoord d → NNReal} (A : SupportHullFaceFlagAdapter P w) :
    Function.support w ⊆ A.working.carrier := by
  rw [A.working_carrier_eq]
  exact subset_convexHull ℝ _

/-- The support-hull reduction retains the original theorem's hypothesis that
all weighted points lie in `P`. -/
theorem support_subset_original {d : ℕ} {P : RationalPolytope d}
    {w : RealCoord d → NNReal} (A : SupportHullFaceFlagAdapter P w) :
    Function.support w ⊆ P.carrier :=
  A.support_mem_working.trans A.working_subset_original

/-- A top-based flag functional is evaluable at every flag point. -/
theorem topFunctional_evaluable {d : ℕ} {P : RationalPolytope d}
    {w : RealCoord d → NNReal} (A : SupportHullFaceFlagAdapter P w)
    (xi : RealCoord d →ᵃ[ℝ] ℝ) (q : A.model.flag.Point) :
    (A.topFunctional xi).EvaluableAt q := by
  unfold ConvexFlag.LinearFunction.EvaluableAt
  rw [A.topFunctional_base]
  exact le_top

end SupportHullFaceFlagAdapter

/-- The canonical support-hull face flag required in Theorem 1.12.

Its nodes are the faces of `convexHull ℝ (Function.support w)`.  A point is
based at its least containing face, whose lattice is the affine integer span
of the support points on that face.  The output face is the least face of the
original polytope containing the physical point. -/
noncomputable def canonicalSupportHullFaceFlagAdapter
    {d : ℕ} (P : RationalPolytope d) (w : RealCoord d → NNReal)
    (hfinite : (Function.support w).Finite) (hnonzero : w ≠ 0)
    (hsupport : Function.support w ⊆ P.carrier)
    (hrational : ∀ q ∈ Function.support w, IsRational q) :
    SupportHullFaceFlagAdapter P w := by
  classical
  let S : Set (RealCoord d) := Function.support w
  have hSne : S.Nonempty := by
    exact Function.support_nonempty_iff.mpr hnonzero
  let Q : RationalPolytope d :=
    RationalPolytope.ofFiniteConvexHull S hfinite hSne hrational
  let M : FaceFlagModel Q := canonicalFaceFlagModel Q
  have hQP : Q.carrier ⊆ P.carrier := by
    exact RationalPolytope.ofFiniteConvexHull_subset S hfinite hSne hrational
      hsupport P.convex
  have pmem (q : {q : M.flag.Point // q ∈ M.proper}) :
      M.physical q.1 q.2 ∈ P.carrier :=
    hQP (M.properEquiv q).property
  let out (q : {q : M.flag.Point // q ∈ M.proper}) : P.Face :=
    Classical.choose
      (RationalPolytope.Face.exists_isLeastFaceAt P (pmem q))
  have hout (q : {q : M.flag.Point // q ∈ M.proper}) :
      RationalPolytope.Face.IsLeastFaceAt P (M.physical q.1 q.2) (out q) :=
    Classical.choose_spec
      (RationalPolytope.Face.exists_isLeastFaceAt P (pmem q))
  refine {
    working := Q
    working_carrier_eq := by
      exact RationalPolytope.ofFiniteConvexHull_carrier S hfinite hSne hrational
    working_subset_original := hQP
    model := M
    laws := canonicalFaceFlagCombinationLaws Q
    supportLift_integral := ?_
    integralPhysical_rational := ?_
    outputFace := out
    physical_mem_output_relInterior := ?_
    integral_output_span := ?_
    topFunctional := fun xi ↦ { base := ⊤, toAffine := xi }
    topFunctional_base := by intro; rfl
    topFunctional_eval := ?_ }
  · intro x hx hxQ
    let q : M.flag.Point := M.lift x hxQ
    have hqproper : q ∈ M.proper := M.lift_proper x hxQ
    have hleast : RationalPolytope.Face.IsLeastFaceAt Q q.val q.base := by
      exact hqproper
    have hval : q.val = x := by
      have hphysical := M.physical_lift x hxQ
      change q.val = x at hphysical
      exact hphysical
    change q.val ∈ affineIntSpan
      (q.base.generatorFinset : Set (RealCoord d))
    rw [hval]
    apply subset_affineIntSpan
    change x ∈ q.base.generatorFinset
    apply Finset.mem_filter.mpr
    refine ⟨?_, ?_⟩
    · change x ∈ hfinite.toFinset
      simpa [S] using hx
    · rw [← hval]
      exact hleast.1
  · intro q hq hqint
    change IsRational q.val
    change q.val ∈ affineIntSpan
      (q.base.generatorFinset : Set (RealCoord d)) at hqint
    apply isRational_of_mem_affineIntSpan _ hqint
    intro x hx
    exact Q.generators_rational x
      (q.base.generatorFinset_subset (by simpa using hx))
  · intro q
    exact (hout q).mem_relInterior
  · intro q hqint
    have hleastQ : RationalPolytope.Face.IsLeastFaceAt Q q.1.val q.1.base := by
      exact q.2
    have hphys : M.physical q.1 q.2 = q.1.val := rfl
    have hleastP : RationalPolytope.Face.IsLeastFaceAt P q.1.val (out q) := by
      simpa [hphys] using hout q
    have hqQ : q.1.val ∈ Q.carrier :=
      q.1.base.subset_polytope hleastQ.1
    let R : Q.Face := (out q).restrict hQP
      ⟨q.1.val, hqQ, hleastP.1⟩
    have hbaseR : q.1.base ≤ R := by
      apply hleastQ.2 R
      exact ⟨hqQ, hleastP.1⟩
    change q.1.val ∈ affineIntSpan
      (Function.support w ∩ (out q).carrier)
    change q.1.val ∈ affineIntSpan
      (q.1.base.generatorFinset : Set (RealCoord d)) at hqint
    apply affineIntSpan_mono _ hqint
    intro x hx
    have hxmem : x ∈ q.1.base.generatorFinset := by simpa using hx
    have hxparts := Finset.mem_filter.mp hxmem
    have hxR : x ∈ R.carrier := hbaseR hxparts.2
    refine ⟨?_, ?_⟩
    · have hxgen := hxparts.1
      change x ∈ hfinite.toFinset at hxgen
      simpa [S] using hxgen
    · exact hxR.2
  · intro xi q hq
    change xi q.1.val = xi q.1.val
    rfl

private theorem support_sum_eq_totalWeight {d n : ℕ}
    (w : RealCoord d → NNReal) (hfinite : (Function.support w).Finite)
    (e : Fin n ≃ Function.support w) :
    (∑ i, (w (e i) : ℝ)) = (totalWeight w : ℝ) := by
  classical
  let _ : Fintype (Function.support w) := hfinite.fintype
  have htotal : (∑ i, w (e i)) = totalWeight w := by
    calc
      (∑ i, w (e i)) = ∑ x : Function.support w, w x :=
        e.sum_comp (fun x : Function.support w ↦ w x.1)
      _ = ∑ᶠ x : Function.support w, w x :=
        (finsum_eq_sum_of_fintype _).symm
      _ = ∑ᶠ x ∈ Function.support w, w x :=
        finsum_set_coe_eq_finsum_mem (Function.support w)
      _ = ∑ᶠ x, w x := finsum_mem_support w
      _ = totalWeight w := rfl
  exact_mod_cast htotal

private theorem support_sum_ite_eq_upperHalfspaceWeight {d n : ℕ}
    (w : RealCoord d → NNReal) (hfinite : (Function.support w).Finite)
    (e : Fin n ≃ Function.support w) (q : RealCoord d)
    (xi : RealCoord d →ᵃ[ℝ] ℝ) :
    (∑ i, if xi q ≤ xi (e i).1 then (w (e i) : ℝ) else 0) =
      (upperHalfspaceWeight w q xi : ℝ) := by
  classical
  let _ : Fintype (Function.support w) := hfinite.fintype
  let g : RealCoord d → NNReal := fun x ↦ if xi q ≤ xi x then w x else 0
  have hg_support : Function.support g ⊆ Function.support w := by
    intro x hx hw
    apply hx
    simp [g, hw]
  have hupper : (∑ i, g (e i)) = upperHalfspaceWeight w q xi := by
    calc
      (∑ i, g (e i)) = ∑ x : Function.support w, g x :=
        e.sum_comp (fun x : Function.support w ↦ g x.1)
      _ = ∑ᶠ x : Function.support w, g x :=
        (finsum_eq_sum_of_fintype _).symm
      _ = ∑ᶠ x ∈ Function.support w, g x :=
        finsum_set_coe_eq_finsum_mem (Function.support w)
      _ = ∑ᶠ x ∈ Set.univ, g x := by
        apply finsum_mem_inter_support_eq' g
        intro x hx
        exact ⟨fun _ ↦ Set.mem_univ x, fun _ ↦ hg_support hx⟩
      _ = ∑ᶠ x, g x := finsum_mem_univ g
      _ = upperHalfspaceWeight w q xi := rfl
  calc
    (∑ i, if xi q ≤ xi (e i).1 then (w (e i) : ℝ) else 0) =
        ∑ i, ((g (e i) : NNReal) : ℝ) := by
      apply Fintype.sum_congr
      intro i
      by_cases h : xi q ≤ xi (e i).1 <;> simp [g, h]
    _ = (upperHalfspaceWeight w q xi : ℝ) := by
      exact_mod_cast hupper

/-- Regression theorem for the proof of Theorem 1.12.  Once the support-hull
face flag and the independent convex-geometric bundle have been constructed,
Corollary 3.14 implies the desired conclusion for the original polytope.

The Helly bound used below is proved by
`FaceFlagCombinationLaws.hellyConstant_le_hollowPolytopeNumber`; it is not an
assumption of the adapter. -/
theorem polytopeCenterpointConclusion_of_supportHullFaceFlagAdapter
    {d : ℕ} (P : RationalPolytope d) (w : RealCoord d → NNReal)
    (hfinite : (Function.support w).Finite) (hnonzero : w ≠ 0)
    (G : HollowPolytopeGeometry d)
    (A : SupportHullFaceFlagAdapter P w) :
    PolytopeCenterpointConclusion P w := by
  classical
  let _ : Fintype (Function.support w) := hfinite.fintype
  let e : Fin (Fintype.card (Function.support w)) ≃ Function.support w :=
    (Fintype.equivFin (Function.support w)).symm
  let points (i : Fin (Fintype.card (Function.support w))) :
      A.model.flag.Point :=
    A.model.lift (e i).1 (A.support_mem_working (e i).2)
  let weight (i : Fin (Fintype.card (Function.support w))) : ℝ :=
    (w (e i) : ℝ)
  have hproper : ∀ i, points i ∈ A.model.proper := by
    intro i
    exact A.model.lift_proper (e i).1 (A.support_mem_working (e i).2)
  have hpoints_injective : Function.Injective points := by
    intro i j hij
    have hsub :
        (⟨points i, hproper i⟩ :
            {q : A.model.flag.Point // q ∈ A.model.proper}) =
          ⟨points j, hproper j⟩ := Subtype.ext hij
    have hphys := congrArg A.model.properEquiv hsub
    apply e.injective
    apply Subtype.ext
    calc
      (e i).1 = A.model.physical (points i) (hproper i) := by
        symm
        exact A.model.physical_lift (e i).1
          (A.support_mem_working (e i).2)
      _ = A.model.physical (points j) (hproper j) :=
        congrArg Subtype.val hphys
      _ = (e j).1 := by
        exact A.model.physical_lift (e j).1
          (A.support_mem_working (e j).2)
  have hintegral : ∀ i, (points i).IsIntegral := by
    intro i
    exact A.supportLift_integral (e i).1 (e i).2
      (A.support_mem_working (e i).2)
  have hweight : ∀ i, 0 ≤ weight i := by
    intro i
    exact NNReal.zero_le_coe
  have hweight_pos : ∀ i, 0 < weight i := by
    intro i
    exact_mod_cast (pos_iff_ne_zero.mpr (e i).2)
  have htotal_pos : 0 < ∑ i, weight i := by
    obtain ⟨x, hx⟩ := Function.support_nonempty_iff.mpr hnonzero
    let i := e.symm ⟨x, hx⟩
    exact lt_of_lt_of_le (hweight_pos i)
      (Finset.single_le_sum (fun j _ ↦ hweight j) (Finset.mem_univ i))
  obtain ⟨q, hqproper, hqintegral, hqcenter⟩ :=
    ConvexFlag.flagCenterpoint A.model.proper points hpoints_injective hproper
      hintegral weight hweight htotal_pos
  let qproper : {q : A.model.flag.Point // q ∈ A.model.proper} :=
    ⟨q, hqproper⟩
  let qphysical : RealCoord d := A.model.physical q hqproper
  refine ⟨A.outputFace qproper, qphysical,
    A.physical_mem_output_relInterior qproper, ?_, ?_⟩
  · intro xi
    let flagXi := A.topFunctional xi
    have hqeval : flagXi.EvaluableAt q :=
      A.topFunctional_evaluable xi q
    have hflag := hqcenter flagXi hqeval
    have htotal : (∑ i, weight i) = (totalWeight w : ℝ) := by
      simpa [weight] using support_sum_eq_totalWeight w hfinite e
    have hupper :
        ConvexFlag.upperWeight points weight flagXi q hqeval =
          (upperHalfspaceWeight w qphysical xi : ℝ) := by
      have hfilter :
          Finset.univ.filter (fun i ↦
              ∃ hi : flagXi.EvaluableAt (points i),
                flagXi.eval q hqeval ≤ flagXi.eval (points i) hi) =
            Finset.univ.filter (fun i ↦ xi qphysical ≤ xi (e i).1) := by
        ext i
        simp only [Finset.mem_filter, Finset.mem_univ, true_and]
        have hcenterEval : flagXi.eval q hqeval = xi qphysical := by
          exact A.topFunctional_eval xi qproper hqeval
        constructor
        · rintro ⟨hi, hle⟩
          have hinputEval : flagXi.eval (points i) hi = xi (e i).1 := by
            calc
              flagXi.eval (points i) hi =
                  xi (A.model.physical (points i) (hproper i)) :=
                A.topFunctional_eval xi ⟨points i, hproper i⟩ hi
              _ = xi (e i).1 := by
                rw [show A.model.physical (points i) (hproper i) = (e i).1 by
                  exact A.model.physical_lift (e i).1
                    (A.support_mem_working (e i).2)]
          simpa [hcenterEval, hinputEval] using hle
        · intro hle
          let hi : flagXi.EvaluableAt (points i) :=
            A.topFunctional_evaluable xi (points i)
          refine ⟨hi, ?_⟩
          have hinputEval : flagXi.eval (points i) hi = xi (e i).1 := by
            calc
              flagXi.eval (points i) hi =
                  xi (A.model.physical (points i) (hproper i)) :=
                A.topFunctional_eval xi ⟨points i, hproper i⟩ hi
              _ = xi (e i).1 := by
                rw [show A.model.physical (points i) (hproper i) = (e i).1 by
                  exact A.model.physical_lift (e i).1
                    (A.support_mem_working (e i).2)]
          simpa [hcenterEval, hinputEval] using hle
      unfold ConvexFlag.upperWeight
      rw [hfilter, Finset.sum_filter]
      simpa [weight] using
        support_sum_ite_eq_upperHalfspaceWeight w hfinite e qphysical xi
    rw [htotal, hupper] at hflag
    have hhelly :
        ConvexFlag.hellyConstant A.model.proper ≤ hollowPolytopeNumber d :=
      A.laws.hellyConstant_le_hollowPolytopeNumber G
        A.integralPhysical_rational
    have hLpos : 0 < ConvexFlag.hellyConstant A.model.proper :=
      ConvexFlag.hellyConstant_pos_of_weighted_points points weight hproper
        hintegral hweight htotal_pos
    have hHpos : 0 < hollowPolytopeNumber d :=
      lt_of_lt_of_le hLpos hhelly
    have hdenom :
        (totalWeight w : ℝ) / (hollowPolytopeNumber d : ℝ) ≤
          (totalWeight w : ℝ) /
            (ConvexFlag.hellyConstant A.model.proper : ℝ) := by
      exact div_le_div_of_nonneg_left (NNReal.zero_le_coe)
        (by exact_mod_cast hLpos) (by exact_mod_cast hhelly)
    have hreal :
        (totalWeight w : ℝ) / (hollowPolytopeNumber d : ℝ) ≤
          (upperHalfspaceWeight w qphysical xi : ℝ) := hdenom.trans hflag
    have hnn :
        totalWeight w / (hollowPolytopeNumber d : NNReal) ≤
          upperHalfspaceWeight w qphysical xi := by
      exact_mod_cast hreal
    simpa [div_eq_mul_inv, mul_comm] using hnn
  · exact A.integral_output_span qproper hqintegral

/-- The face-flag and centerpoint parts of Theorem 1.12 are unconditional;
only boundedness of hollow-polytope vertex counts remains as an input here. -/
theorem polytopeCenterpointConclusion_of_hollowGeometry
    {d : ℕ} (P : RationalPolytope d) (w : RealCoord d → NNReal)
    (hfinite : (Function.support w).Finite) (hnonzero : w ≠ 0)
    (hsupport : Function.support w ⊆ P.carrier)
    (hrational : ∀ q ∈ Function.support w, IsRational q)
    (G : HollowPolytopeGeometry d) :
    PolytopeCenterpointConclusion P w :=
  polytopeCenterpointConclusion_of_supportHullFaceFlagAdapter
    P w hfinite hnonzero G
      (canonicalSupportHullFaceFlagAdapter P w hfinite hnonzero
        hsupport hrational)

/-- The two construction theorems still needed to discharge Theorem 1.12
itself.  This packages no conclusion about centerpoints: it contains only
the global hollow-polytope geometry and the construction of the canonical
support-hull face flag from the hypotheses of the theorem. -/
structure TheoremOneTwelveSetup (d : ℕ) where
  hollowGeometry : HollowPolytopeGeometry d
  /-- Construct a support-hull face-flag adapter for each admissible weighted polytope. -/
  supportHullFaceFlag : ∀ (P : RationalPolytope d)
      (w : RealCoord d → NNReal),
    (Function.support w).Finite →
    w ≠ 0 →
    Function.support w ⊆ P.carrier →
    (∀ q ∈ Function.support w, IsRational q) →
    SupportHullFaceFlagAdapter P w

/-- The canonical face model discharges the construction field of
`TheoremOneTwelveSetup`; the setup is therefore equivalent in practice to
the independent hollow-polytope boundedness theorem. -/
noncomputable def TheoremOneTwelveSetup.ofHollowGeometry
    {d : ℕ} (G : HollowPolytopeGeometry d) : TheoremOneTwelveSetup d where
  hollowGeometry := G
  supportHullFaceFlag := fun P w hfinite hnonzero hsupport hrational ↦
    canonicalSupportHullFaceFlagAdapter P w hfinite hnonzero hsupport hrational

/-- Exact assembly check against the corrected statement of Theorem 1.12.
Once `TheoremOneTwelveSetup d` is constructed, no further geometric
assumptions are needed. -/
theorem polytopeCenterpointConclusion_of_theoremOneTwelveSetup
    {d : ℕ} (D : TheoremOneTwelveSetup d)
    (P : RationalPolytope d) (w : RealCoord d → NNReal)
    (hfinite : (Function.support w).Finite)
    (hnonzero : w ≠ 0)
    (hsupport : Function.support w ⊆ P.carrier)
    (hrational : ∀ q ∈ Function.support w, IsRational q) :
    PolytopeCenterpointConclusion P w :=
  polytopeCenterpointConclusion_of_supportHullFaceFlagAdapter
    P w hfinite hnonzero D.hollowGeometry
      (D.supportHullFaceFlag P w hfinite hnonzero hsupport hrational)

end EGZ
