/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking
-/

import LeanPool.DavisKahan.DavisKahan.Sources.DavisKahan1970.Section9.ExactData

/-!
# Davis--Kahan 1970, Section 9: rank-one Schur correction

The Schur complement appearing after equation (9.11) has a rank-one
correction proportional to the matrix with diagonal entries `1` and
off-diagonal entries `-1`.  This file isolates the exact two-dimensional
algebra.  In particular, subtracting that correction is a scalar diagonal
shift plus a purely off-diagonal perturbation, and division by the Ritz gap
produces the coefficient `sqrt 3 / 30` used in the final individual-vector
estimate.
-/

namespace TauCeti
namespace DavisKahan1970
namespace Section9

/-- The rank-one positive semidefinite matrix generated by `(1,-1)`. -/
def differenceGram (q : ℝ) : SymmetricTwoByTwo where
  a₀₀ := q
  a₀₁ := -q
  a₁₁ := q

/-- The Schur-reduced matrix obtained from a diagonal Ritz matrix by
subtracting the rank-one correction. -/
def schurReducedTwoByTwo (d₀ d₁ q : ℝ) : SymmetricTwoByTwo where
  a₀₀ := d₀ - q
  a₀₁ := q
  a₁₁ := d₁ - q

/-- The diagonal shift in the Schur-reduced matrix. -/
def shiftedRitzDiagonal (d₀ d₁ q : ℝ) : SymmetricTwoByTwo where
  a₀₀ := d₀ - q
  a₀₁ := 0
  a₁₁ := d₁ - q

/-- The purely off-diagonal part of the Schur-reduced matrix. -/
def offDiagonalSwap (q : ℝ) : SymmetricTwoByTwo where
  a₀₀ := 0
  a₀₁ := q
  a₁₁ := 0

/-- Entries of the Schur-reduced 2x2 block, computed explicitly. -/
lemma schurReducedTwoByTwo_entries (d₀ d₁ q : ℝ) :
    (schurReducedTwoByTwo d₀ d₁ q).a₀₀ =
        (shiftedRitzDiagonal d₀ d₁ q).a₀₀ + (offDiagonalSwap q).a₀₀ ∧
    (schurReducedTwoByTwo d₀ d₁ q).a₀₁ =
        (shiftedRitzDiagonal d₀ d₁ q).a₀₁ + (offDiagonalSwap q).a₀₁ ∧
    (schurReducedTwoByTwo d₀ d₁ q).a₁₁ =
        (shiftedRitzDiagonal d₀ d₁ q).a₁₁ + (offDiagonalSwap q).a₁₁ := by
  simp [schurReducedTwoByTwo, shiftedRitzDiagonal, offDiagonalSwap]

/-- Subtracting `q [[1,-1],[-1,1]]` from `diag(d0,d1)` gives the source's
shifted diagonal plus off-diagonal perturbation. -/
lemma schurReducedTwoByTwo_eq_sub_differenceGram (d₀ d₁ q : ℝ) :
    (schurReducedTwoByTwo d₀ d₁ q).a₀₀ = d₀ - (differenceGram q).a₀₀ ∧
    (schurReducedTwoByTwo d₀ d₁ q).a₀₁ = 0 - (differenceGram q).a₀₁ ∧
    (schurReducedTwoByTwo d₀ d₁ q).a₁₁ = d₁ - (differenceGram q).a₁₁ := by
  simp [schurReducedTwoByTwo, differenceGram]

/-- The exact separation of the two Ritz values. -/
lemma ritz_gap_exact (ε : ℝ) :
    ritzHigh ε - ritzLow ε = ε * Real.sqrt 3 / 3 := by
  simpa [div_eq_mul_inv, mul_assoc] using ritzHigh_sub_ritzLow ε

/-- The source coefficient in one half of the `tan(2 psi)` estimate. -/
lemma half_tanTwoPsi_coefficient_identity :
    (Real.sqrt 3 / 30 : ℝ) = 1 / (10 * Real.sqrt 3) := by
  have h3 : Real.sqrt (3 : ℝ) ^ 2 = 3 := Real.sq_sqrt (by norm_num)
  have hs : Real.sqrt (3 : ℝ) ≠ 0 := ne_of_gt (Real.sqrt_pos.2 (by norm_num))
  field_simp [hs]
  nlinarith

/-- Exact scalar reduction used after (9.11).  If the rank-one Schur
coefficient is bounded by `epsilon^2 / (30 D)`, then one half of the resulting
`tan(2 psi)` ratio is bounded by `(sqrt 3 / 30) epsilon / D`.

The theorem is deliberately stated without trigonometry: the Section 7
`tan(2 Theta)` theorem supplies the interpretation of `2 q / RitzGap` as an
angle bound. -/
theorem half_tanTwoPsi_ratio_lt
    {ε D q : ℝ} (hε : 0 < ε) (hD : 0 < D)
    (_hq0 : 0 ≤ q) (hq : q < ε ^ 2 / (30 * D)) :
    q / (ritzHigh ε - ritzLow ε) <
      (Real.sqrt 3 / 30) * ε / D := by
  have hs : 0 < Real.sqrt (3 : ℝ) := Real.sqrt_pos.2 (by norm_num)
  have hgap : 0 < ritzHigh ε - ritzLow ε := by
    rw [ritz_gap_exact]
    positivity
  have hright :
      ε ^ 2 / (30 * D) / (ritzHigh ε - ritzLow ε) =
        (Real.sqrt 3 / 30) * ε / D := by
    rw [ritz_gap_exact]
    field_simp [ne_of_gt hε, ne_of_gt hD, ne_of_gt hs]
    nlinarith [Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 3)]
  calc
    q / (ritzHigh ε - ritzLow ε) <
        (ε ^ 2 / (30 * D)) / (ritzHigh ε - ritzLow ε) :=
      div_lt_div_of_pos_right hq hgap
    _ = (Real.sqrt 3 / 30) * ε / D := hright

/-- Replacing `D = 500 - lambda` by the smaller certified denominator
`500 - alphaHat` weakens the bound in the correct direction. -/
theorem half_tanTwoPsi_ratio_lt_of_eigenvalue_upper
    {ε lam alphaHat q : ℝ}
    (hε : 0 < ε) (halpha : alphaHat < 500) (hlam : lam ≤ alphaHat)
    (hq0 : 0 ≤ q) (hq : q < ε ^ 2 / (30 * (500 - lam))) :
    q / (ritzHigh ε - ritzLow ε) <
      (Real.sqrt 3 / 30) * ε / (500 - alphaHat) := by
  have hDlam : 0 < 500 - lam := by linarith
  have hDα : 0 < 500 - alphaHat := by linarith
  have hfirst := half_tanTwoPsi_ratio_lt hε hDlam hq0 hq
  have hcoeff : 0 ≤ (Real.sqrt 3 / 30) * ε := by positivity
  have hden : 500 - alphaHat ≤ 500 - lam := by linarith
  have hmono :
      (Real.sqrt 3 / 30) * ε / (500 - lam) ≤
        (Real.sqrt 3 / 30) * ε / (500 - alphaHat) := by
    apply (div_le_div_iff₀ hDlam hDα).2
    exact mul_le_mul_of_nonneg_left hden hcoeff
  exact hfirst.trans_le hmono

end Section9
end DavisKahan1970
end TauCeti
