/-
Copyright (c) 2026 Bryan Ehrlich. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bryan Ehrlich
-/
/-
Copyright (c) 2026 Bryan Ehrlich. All rights reserved.
Released under Apache 2.0 license.
Authors: Bryan Ehrlich
-/
import LeanPool.EuclideanJordan.EuclideanJordan.Frame


/-!
# Powers of a single element, and how far power associativity gets

Power associativity — Albert's theorem, that the subalgebra generated by one element of a
Jordan algebra is associative — is the gateway to the Jordan spectral theorem: the spectral
resolution of `x` lives inside `ℝ[x]`, and that argument needs `ℝ[x]` associative before it can
start.

★ **`EuclideanJordan/PowerAssoc.lean` proves the theorem itself** (`jpow_mul_jpow`,
unconditional). This file is the *reduction* that made it reachable: it cuts power
associativity down to a single family of commutator statements and discharges the first three
members. It is kept because the reduction, not the induction, is where the content is.

## The reduction

Write `CommuteAt x m` for *`L_{x^{m+1}}` commutes with `L_x`*:

  `∀ w, x ∘ (x^{m+1} ∘ w) = x^{m+1} ∘ (x ∘ w)`.

Then `jpow_mul_jpow_of_commuteAt` says: **`CommuteAt x m` alone gives
`x^{m+1} ∘ x^{n+1} = x^{m+n+2}` for every `n`.** So full power associativity is exactly
`∀ m, CommuteAt x m`, and nothing else is missing.

★ The reduction itself does **not** use the Jordan identity — its `omit` line says so. Every
bit of Jordan content in power associativity is concentrated in `CommuteAt`. **This is the
part that held up**: it is what let `EuclideanJordan/PowerAssoc.lean` attack a single commutator
    family
instead of the product law, and the proof there is exactly that attack.

## What is discharged here

| `m` | statement | source |
| --- | --- | --- |
| `0` | `L_x` commutes with `L_x` | trivial |
| `1` | `L_x` commutes with `L_{x²}` | **the Jordan identity itself** |
| `2` | `L_x` commutes with `L_{x³}` | one instance of `two_lin1_apply` |

★ All three are **subsumed** by `commuteAt_all` in `EuclideanJordan/PowerAssoc.lean`. They are
kept because they are the elementary route, because `commuteAt_one` *is* the Jordan identity in
this vocabulary, and because `commuteAt_two` is what made the general pattern visible.

★ **Do not read `sq_mul_jpow` as power associativity.** It is the `m = 1` row of the table
above and nothing more.
-/

namespace EuclideanJordan

section Pow

variable {J : Type*} [NonUnitalNonAssocCommRing J] [IsCommJordan J]

/-- `jpow x n = x^{n+1}`. Indexed from `1` rather than `0` so that no unit is assumed —
the Peirce layer of this development is unit-free and this stays so. -/
def jpow (x : J) : ℕ → J
  | 0 => x
  | (n + 1) => x * jpow x n

omit [IsCommJordan J] in
@[simp] theorem jpow_zero (x : J) : jpow x 0 = x := rfl

omit [IsCommJordan J] in
@[simp] theorem jpow_succ (x : J) (n : ℕ) : jpow x (n + 1) = x * jpow x n := rfl

omit [IsCommJordan J] in
theorem jpow_succ' (x : J) (n : ℕ) : jpow x (n + 1) = jpow x n * x := by
  rw [jpow_succ, mul_comm]

/-- `L_{x^{m+1}}` commutes with `L_x`. Power associativity is exactly `∀ m, CommuteAt x m`
(see `jpow_mul_jpow_of_commuteAt`). -/
def CommuteAt (x : J) (m : ℕ) : Prop := ∀ w : J, x * (jpow x m * w) = jpow x m * (x * w)

omit [IsCommJordan J] in
/-- **The reduction.** A single commutation hypothesis at `m` gives the whole `m`-th row of
the power table.

★ Note the `omit`: this holds in *any* commutative non-associative ring. The Jordan identity
is not used, which localises all of Albert's difficulty in `CommuteAt`. -/
theorem jpow_mul_jpow_of_commuteAt {x : J} {m : ℕ} (h : CommuteAt x m) (n : ℕ) :
    jpow x m * jpow x n = jpow x (m + n + 1) := by
  induction n with
  | zero => rw [jpow_zero, ← jpow_succ', Nat.add_zero]
  | succ n ih =>
      rw [jpow_succ, ← h (jpow x n), ih,
        show m + (n + 1) + 1 = (m + n + 1) + 1 from by omega]
      exact (jpow_succ x (m + n + 1)).symm

omit [IsCommJordan J] in
/-- `m = 0`: `L_x` commutes with itself. -/
theorem commuteAt_zero (x : J) : CommuteAt x 0 := fun _ => rfl

/-- `m = 1`: `L_x` commutes with `L_{x²}`. **This is the Jordan identity**, in the operator
form Mathlib states it (`commute_lmul_lmul_sq`). -/
theorem commuteAt_one (x : J) : CommuteAt x 1 := by
  intro w
  have h := IsCommJordan.lmul_comm_rmul_rmul x w
  -- `(x * w) * (x * x) = x * (w * (x * x))`
  calc x * (jpow x 1 * w) = x * ((x * x) * w) := rfl
    _ = x * (w * (x * x)) := by rw [mul_comm (x * x) w]
    _ = (x * w) * (x * x) := h.symm
    _ = (x * x) * (x * w) := mul_comm _ _
    _ = jpow x 1 * (x * w) := rfl

/-- **`x² ∘ x^{n+1} = x^{n+3}`.** The `m = 1` row. -/
theorem sq_mul_jpow (x : J) (n : ℕ) : (x * x) * jpow x n = jpow x (n + 2) := by
  have := jpow_mul_jpow_of_commuteAt (commuteAt_one x) n
  rw [show (1 : ℕ) + n + 1 = n + 2 from by omega] at this
  exact this

end Pow

section PowTwo

variable {J : Type*} [NonUnitalNonAssocCommRing J] [IsCommJordan J] [Module ℝ J]

/-- `m = 2`: **`L_x` commutes with `L_{x³}`.** One instance of the linearised Jordan
identity: at `a := x`, `b := x²` the first bracket of `two_lin1_apply` cancels against
itself, leaving exactly this. -/
theorem commuteAt_two (x : J) : CommuteAt x 2 := by
  intro w
  have h := two_lin1_apply x (jpow x 1) w
  simp only [jpow_succ, jpow_zero, sub_self, smul_zero, zero_add] at h
  refine sub_eq_zero.mp (nsmul_eq_zero_iff' (n := 4) (by norm_num) ?_)
  rw [← h]
  abel

/-- **`x³ ∘ x^{n+1} = x^{n+4}`.** The `m = 2` row. -/
theorem cube_mul_jpow (x : J) (n : ℕ) : jpow x 2 * jpow x n = jpow x (n + 3) := by
  have := jpow_mul_jpow_of_commuteAt (commuteAt_two x) n
  rw [show (2 : ℕ) + n + 1 = n + 3 from by omega] at this
  exact this

omit [IsCommJordan J] [Module ℝ J] in
/-- **Power associativity, as the single statement that remains.** Everything else is
`jpow_mul_jpow_of_commuteAt`. -/
theorem jpow_mul_jpow_of_forall_commuteAt {x : J} (h : ∀ m, CommuteAt x m) (m n : ℕ) :
    jpow x m * jpow x n = jpow x (m + n + 1) :=
  jpow_mul_jpow_of_commuteAt (h m) n

end PowTwo

end EuclideanJordan
