/-
Copyright (c) 2026 Matevz Miščič, Maša Žaucer, Job Petrovčič. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matevz Miščič, Maša Žaucer, Job Petrovčič
-/
import Mathlib.Algebra.Ring.Basic
import Mathlib.Data.Set.Basic
import Mathlib.RingTheory.Ideal.Defs
import Mathlib.Tactic.NoncommRing
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import LeanPool.ArtinWedderburn.IdealProd

/-!
# Left and right multiplication sets

Provides `left_mul a = Ra`, `right_mul a = aR`, the `left_ideal_of_element` constructor, and
the consequence that `aRb = 0` collapses these auxiliary sets to zero. Used by the prime ring
characterisation.
-/

namespace LeanPool.ArtinWedderburn

variable {R : Type*} [Ring R] (a b : R)

-- left_mul a is the set Ra
/-- The set `Ra = {r * a | r : R}` of left multiples of `a`. -/
def left_mul (a : R) : Set R := {x | ∃ r : R, x = r * a}

-- right_mul a is the set aR
/-- The set `aR = {a * r | r : R}` of right multiples of `a`. -/
def right_mul (a : R) : Set R := {x | ∃ r : R, x = a * r}

theorem left_mul_zero_impl_mul_zero : both_mul a b = {0} → a * b = 0 := by
  intro h
  have k : a * b ∈ both_mul a b := by use 1; simp
  rw [h] at k
  exact k

theorem in_particular (a c b : R) : both_mul a b = {0} → a * c * b = 0 := by
  intro h
  have k : a * c * b ∈ both_mul a b := by use c
  rw [h] at k
  exact k

open Pointwise Set

-- aRb = 0 implies Ra = 0 or Rb = 0
theorem both_mul_zero_one_left_zero :
    both_mul a b = {0} → (left_mul a) * (left_mul b) = {0} := by
  intro h
  apply Set.ext_iff.mpr
  intro x
  constructor
  · rintro ⟨y, ⟨r, hr⟩, z, ⟨s, hs⟩, hx⟩
    simp only at hx
    calc
      x = y * z := by rw [← hx]
      _ = (r * a) * (s * b) := by rw [hr, hs]
      _ = r * (a * s * b) := by noncomm_ring
      _ = r * 0 := by rw [in_particular a s b h]
      _ = 0 := by noncomm_ring
  · intro hx
    rw [Set.mem_singleton_iff] at hx
    refine ⟨0, ⟨0, by noncomm_ring⟩, 0, ⟨0, by noncomm_ring⟩, ?_⟩
    simp only [mul_zero]
    exact hx.symm

/-- The principal left ideal `Ra` generated by `a`, packaged as an `Ideal R`. -/
def left_ideal_of_element (a : R) : Ideal R :=
  { carrier := left_mul a,
    zero_mem' := by use 0; noncomm_ring,
    add_mem' := by
      rintro x y ⟨r, hr⟩ ⟨s, hs⟩
      use r + s
      rw [hr, hs]
      noncomm_ring,
    smul_mem' := by
      rintro x y ⟨r, hr⟩
      use x * r
      rw [hr]
      noncomm_ring }

theorem carrier_of_left_ideal_of_element (a : R) :
    (left_ideal_of_element a).carrier = left_mul a := rfl

end LeanPool.ArtinWedderburn
