/-
Copyright (c) 2026 Jon Crall, Edward Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, Edward Wang
-/

import LeanPool.DavisKahan.DavisKahan.SpectralTheory.AbstractSpectrum
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.All
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.BoundedFromSpectrum
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.BoundedSelfAdjointSpectralProjection
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.BoundedTruncation
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.CayleySelectorBridge
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.CentralBand
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.CircleContour
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.CircleRieszEndpoints
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.CircleRieszIntegral
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.CircleRieszProjection
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.Complexification
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.ContinuationContour
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.ContinuationRieszIntegral
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.FormMethod
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.FormSpectrumBounds
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.GapResolvent
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.GraphSubspace
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.OperatorAngle
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.OrderedHalfLine
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.PartialMap
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.Real
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.ReducingSpectrumUnion
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.ReducingSubspace
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.ReflectionRestriction
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.ResolventOperator
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.SelfAdjointBorelCalculus
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.SpectralCutoff
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.SpectralGapFormBounds
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.SpectralRestriction
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.SpectralRestrictionLocalization
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.SpectralRestrictionOperator
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.UnboundedBandLipschitz
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.UnboundedCentralBand
import LeanPool.DavisKahan.DavisKahan.SpectralTheory.UnboundedDirectedGapBound

/-! Supporting modules for Davis–Kahan rotation of eigenvectors. -/
