/-
Copyright (c) 2026 n-yamaguchi-0729. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: n-yamaguchi-0729
-/
module


public import LeanPool.ClassFieldTheory.ClassFieldTheory.Definitions.ConductorsAndRayClassFields.RayClassModulus
public import LeanPool.ClassFieldTheory.ClassFieldTheory.Definitions.FrobeniusAndHilbertClassFields.NumberFieldFractionalIdealGroup
public import Mathlib.RingTheory.ClassGroup.Basic
/-!
# Narrow ideal classes

The narrow class group is the group of nonzero fractional ideals modulo
principal ideals generated by elements positive at every real place.  This
ideal-theoretic definition does not depend on the ray class group.
-/

@[expose] public section

open scoped NumberField
open NumberField

noncomputable
section

namespace ClassFieldTheory

universe u

/-- Nonzero field elements positive at every real place. -/
def totallyPositiveFieldUnits
    (K : Type u) [Field K] [NumberField K] : Subgroup Kˣ where
  carrier := {x | ∀ v : RayClassRealPlace K,
    0 < v.1.embedding_of_isReal v.2 (x : K)}
  one_mem' := by
    intro v
    simp
  mul_mem' := by
    intro x y hx hy v
    simpa only [Units.val_mul, map_mul] using mul_pos (hx v) (hy v)
  inv_mem' := by
    intro x hx v
    simpa only [Units.val_inv_eq_inv_val, map_inv₀] using inv_pos.mpr (hx v)

/-- Principal fractional ideals with a totally positive generator. -/
def narrowPrincipalIdealSubgroup
    (K : Type u) [Field K] [NumberField K] :
    Subgroup (NumberFieldFractionalIdealGroup K) :=
  (totallyPositiveFieldUnits K).map (toPrincipalIdeal (𝓞 K) K)

/-- The ideal-theoretic narrow class group of a number field. -/
abbrev NarrowClassGroup
    (K : Type u) [Field K] [NumberField K] :=
  NumberFieldFractionalIdealGroup K ⧸ narrowPrincipalIdealSubgroup K

end ClassFieldTheory
