/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking
-/
import LeanPool.DavisKahan.DavisKahan.Sources.DavisKahan1970.Ideals.SequenceGauge
import LeanPool.DavisKahan.DavisKahan.Sources.DavisKahan1970.SineTheta.Norms.UnitaryInvariantNormLaws
import LeanPool.DavisKahan.DavisKahan.Sources.DavisKahan1970.Ideals.NormCorrespondence

/-!
# Fan dominance for standard symmetric ideals

There are two distinct constructions around the minimal ideal and they should
not be conflated:

* `FiniteRankGaugeClosure N A` is the literal closure of finite-rank operators
  in the gauge associated with `N`.
* `MinimalFullySymmetricMem N A` is its weak-majorization-saturated envelope.

The second construction is fully symmetric by definition, so its Fan-dominance
theorem is an explicit transitivity argument and requires no automation.  The
classical theorem that the raw finite-rank gauge closure is already fully
symmetric is recorded separately as the equality problem between these two
predicates.  Until that order-continuity/density bridge is proved, the standard
`.minimal` completion uses the honest fully symmetric envelope rather than
claiming an unproved property of the raw closure.
-/

namespace TauCeti
namespace SymmetricIdeal

open scoped BigOperators
open DavisKahan.ExactSinTheta

noncomputable section

universe u v

variable {𝕜 : Type u} [RCLike 𝕜]
variable {E F : Type v}
variable [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
variable [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]

/-- Literal membership in the gauge closure of the finite-rank operators. -/
def FiniteRankGaugeClosure
    (N : SymmetricNormingFunction) (A : E →L[𝕜] F) : Prop :=
  N.Mem A ∧
    ∀ ε : ℝ, 0 < ε →
      ∃ R : E →L[𝕜] F,
        R.rank < Cardinal.aleph0 ∧ N.Mem (A - R) ∧ N.gauge (A - R) < ε

/-- Backwards-compatible name for the raw finite-rank gauge closure. -/
abbrev FiniteRankApproximable
    (N : SymmetricNormingFunction) (A : E →L[𝕜] F) : Prop :=
  FiniteRankGaugeClosure N A

/-- The minimal fully symmetric envelope generated by the finite-rank gauge
closure.  An operator belongs when it is weakly submajorized by an operator in
the literal finite-rank closure. -/
def MinimalFullySymmetricMem
    (N : SymmetricNormingFunction) (A : E →L[𝕜] F) : Prop :=
  ∃ B : E →L[𝕜] F,
    FiniteRankGaugeClosure N B ∧
      ∀ k : ℕ, kyFanApproximationGauge k A ≤ kyFanApproximationGauge k B

omit [CompleteSpace E] [CompleteSpace F] in
/-- Every member of the raw finite-rank closure belongs to its fully symmetric
envelope. -/
theorem minimalFullySymmetricMem_of_finiteRankGaugeClosure
    (N : SymmetricNormingFunction) {A : E →L[𝕜] F}
    (hA : FiniteRankGaugeClosure N A) :
    MinimalFullySymmetricMem N A :=
  ⟨A, hA, fun _ => le_rfl⟩

omit [CompleteSpace E] [CompleteSpace F] in
/-- Membership in the fully symmetric envelope implies membership in the
maximal/Fatou ideal. -/
theorem mem_of_minimalFullySymmetricMem
    (N : SymmetricNormingFunction) {A : E →L[𝕜] F}
    (hA : MinimalFullySymmetricMem N A) : N.Mem A := by
  obtain ⟨B, hB, hAB⟩ := hA
  exact N.mem_of_all_mul_kyFan_le
    (c := 1) (by norm_num) hB.1 (by
      intro k
      simpa only [one_mul] using hAB k)

/-- The literal finite-rank gauge closure is adjoint-stable.

If `R` approximates `A` to within `ε`, then `R†` approximates `A†` to within the
same `ε`, because taking adjoints is subtractive, preserves finite rank, and
leaves every source gauge unchanged. -/
theorem finiteRankGaugeClosure_adjoint
    (N : SymmetricNormingFunction) {A : E →L[𝕜] F}
    (hA : FiniteRankGaugeClosure N A) :
    FiniteRankGaugeClosure N A.adjoint := by
  refine ⟨(N.mem_adjoint_iff A).mpr hA.1, ?_⟩
  intro ε hε
  obtain ⟨R, hrank, hmem, hgauge⟩ := hA.2 ε hε
  have hsub : A.adjoint - R.adjoint = (A - R).adjoint := (map_sub _ A R).symm
  refine ⟨R.adjoint, ContinuousLinearMap.rank_adjoint_lt_aleph0 R hrank, ?_, ?_⟩
  · rw [hsub]
    exact (N.mem_adjoint_iff _).mpr hmem
  · rw [hsub, N.gauge_adjoint]
    exact hgauge

/-- The minimal fully symmetric envelope is adjoint-stable. -/
theorem minimalFullySymmetricMem_adjoint
    (N : SymmetricNormingFunction) {A : E →L[𝕜] F}
    (hA : MinimalFullySymmetricMem N A) :
    MinimalFullySymmetricMem N A.adjoint := by
  obtain ⟨B, hB, hAB⟩ := hA
  refine ⟨B.adjoint, finiteRankGaugeClosure_adjoint N hB, fun k => ?_⟩
  rw [kyFanApproximationGauge_adjoint, kyFanApproximationGauge_adjoint]
  exact hAB k

/-- The two standard completions generated by a coherent symmetric norming
function. -/
inductive StandardSymmetricCompletion where
  | maximal
  | minimal
  deriving DecidableEq

/-- A standard symmetric ideal is a coherent source norm together with its
maximal/Fatou or minimal fully symmetric completion. -/
structure StandardSymmetricIdeal where
  /-- The symmetric norming function defining the ideal gauge. -/
  norm : SymmetricNormingFunction
  /-- The choice of standard completion of the symmetric operator ideal. -/
  completion : StandardSymmetricCompletion

namespace StandardSymmetricIdeal

/-- Membership in a standard completion. -/
def Mem (I : StandardSymmetricIdeal) (A : E →L[𝕜] F) : Prop :=
  match I.completion with
  | .maximal => I.norm.Mem A
  | .minimal => MinimalFullySymmetricMem I.norm A

/-- Both completions carry the same gauge. -/
def gauge (I : StandardSymmetricIdeal) (A : E →L[𝕜] F) : ℝ :=
  I.norm.gauge A

/-- Every standard completion is adjoint-stable. -/
theorem mem_adjoint (I : StandardSymmetricIdeal) {A : E →L[𝕜] F}
    (hA : I.Mem A) : I.Mem A.adjoint := by
  cases I with
  | mk N completion =>
      cases completion with
      | maximal => exact (N.mem_adjoint_iff A).mpr hA
      | minimal => exact minimalFullySymmetricMem_adjoint N hA

/-- Every standard gauge is invariant under adjoint. -/
theorem gauge_adjoint (I : StandardSymmetricIdeal) (A : E →L[𝕜] F) :
    I.gauge A.adjoint = I.gauge A :=
  I.norm.gauge_adjoint A

end StandardSymmetricIdeal

omit [CompleteSpace E] [CompleteSpace F] in
/-- Fan dominance for the minimal fully symmetric envelope.

The witness from `B` remains a witness for `A`, because weak submajorization is
transitive.  The gauge inequality is the already proved maximal/Fatou Fan
inequality, after deriving maximal membership of `B` from its witness. -/
theorem minimalFullySymmetricMem_of_kyFan_dominated
    (N : SymmetricNormingFunction) {A B : E →L[𝕜] F}
    (hB : MinimalFullySymmetricMem N B)
    (hAB : ∀ k : ℕ,
      kyFanApproximationGauge k A ≤ kyFanApproximationGauge k B) :
    MinimalFullySymmetricMem N A ∧ N.gauge A ≤ N.gauge B := by
  obtain ⟨C, hC, hBC⟩ := hB
  have hBmem : N.Mem B :=
    N.mem_of_all_mul_kyFan_le
      (c := 1) (by norm_num) hC.1 (by
        intro k
        simpa only [one_mul] using hBC k)
  have hAgauge :=
    N.mul_gauge_le_of_all_mul_kyFan_le
      (c := 1) (by norm_num) hBmem (by
        intro k
        simpa only [one_mul] using hAB k)
  refine ⟨⟨C, hC, ?_⟩, ?_⟩
  · intro k
    exact (hAB k).trans (hBC k)
  · simpa only [one_mul] using hAgauge.2

/-- **Fan dominance for every standard symmetric ideal.** -/
theorem standard_fanDominance
    (I : StandardSymmetricIdeal) {A B : E →L[𝕜] F}
    (hB : I.Mem B)
    (hAB : ∀ k : ℕ,
      kyFanApproximationGauge k A ≤ kyFanApproximationGauge k B) :
    I.Mem A ∧ I.gauge A ≤ I.gauge B := by
  cases I with
  | mk N completion =>
      cases completion with
      | maximal =>
          change N.Mem A ∧ N.gauge A ≤ N.gauge B
          simpa only [one_mul] using
            (N.mul_gauge_le_of_all_mul_kyFan_le
              (c := 1) (by norm_num) hB (by
                intro k
                simpa only [one_mul] using hAB k))
      | minimal =>
          change MinimalFullySymmetricMem N A ∧ N.gauge A ≤ N.gauge B
          exact minimalFullySymmetricMem_of_kyFan_dominated N hB hAB

end

end SymmetricIdeal
end TauCeti
