/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking
-/
import LeanPool.DavisKahan.DavisKahan.Sources.DavisKahan1970.Ideals.StandardFanDominance
import LeanPool.DavisKahan.DavisKahan.Sources.DavisKahan1970.Ideals.UnitaryInvariantNormInstances
import LeanPool.DavisKahan.ForTauCeti.Analysis.Normed.FiniteLpGauge

/-!
# Standard coherent norming-function instances

This file constructs the finite `ell^p` and `ell^infinity` coherent source
norms from the existing proved finite symmetric gauges.  The generic Fan
result then applies to both their maximal and minimal completions.
-/

namespace TauCeti
namespace SymmetricIdeal

open scoped BigOperators
open DavisKahan.ExactSinTheta

noncomputable section

/-- The two zero-padding implementations used by the existing finite-gauge and
paper-norm layers agree. -/
theorem zeroPad_eq_zeroPadRight {n : ℕ} (x : Fin n → ℝ) :
    zeroPad x = FiniteVector.zeroPadRight (m := 1) x := by
  funext i
  refine Fin.lastCases ?_ (fun j => ?_) i
  · simp [zeroPad, FiniteVector.zeroPadRight]
  · simp [zeroPad, FiniteVector.zeroPadRight]

/-- The coherent finite `ell^p` symmetric norming function, `1 ≤ p < ∞`. -/
noncomputable def lpAxiomatic
    (p : ℝ) (hp : 1 ≤ p) : SymmetricNormingFunction.Axiomatic where
  gauge := fun _ x => FiniteVector.lpGauge p x
  nonneg := FiniteVector.lpGauge_nonneg p
  definite := by
    intro n x
    exact FiniteVector.lpGauge_eq_zero_iff (lt_of_lt_of_le zero_lt_one hp) x
  add_le := by
    intro n x y
    exact FiniteVector.lpGauge_add_le hp x y
  smul := by
    intro n c x
    exact FiniteVector.lpGauge_smul (lt_of_lt_of_le zero_lt_one hp) c x
  perm := by
    intro n x π
    exact FiniteVector.lpGauge_perm p x π
  abs := by
    intro n x
    unfold FiniteVector.lpGauge
    congr 2
    funext i
    rw [abs_abs]
  zero_pad := by
    intro n x
    rw [zeroPad_eq_zeroPadRight]
    exact FiniteVector.lpGauge_zeroPadRight p x
  normalized := by
    simp [FiniteVector.lpGauge]
  weak_majorization := by
    intro n x y hx h0x h0y hprefix
    exact (FiniteVector.lpSymmetricGauge (n := n) p hp).le_of_prefixSum_le
      hx h0x h0y hprefix

/-- Coherent Schatten/`ell^p` source norm. -/
noncomputable def lpNormingFunction (p : ℝ) (hp : 1 ≤ p) :
    SymmetricNormingFunction :=
  (lpAxiomatic p hp).toNormingFunction

/-- The finite `ell^infinity` gauge vanishes exactly on the zero vector. -/
theorem linftyGauge_eq_zero_iff {n : ℕ} (x : Fin n → ℝ) :
    FiniteVector.linftyGauge x = 0 ↔ x = 0 := by
  constructor
  · intro h
    funext i
    have hi : |x i| ≤ FiniteVector.linftyGauge x := by
      unfold FiniteVector.linftyGauge
      exact le_ciSup (Finite.bddAbove_range (fun j : Fin n => |x j|)) i
    have habs : |x i| = 0 := le_antisymm (by simpa [h] using hi) (abs_nonneg _)
    exact abs_eq_zero.mp habs
  · rintro rfl
    exact FiniteVector.linftyGauge_zero

/-- The coherent finite `ell^infinity` symmetric norming function. -/
noncomputable def linftyAxiomatic :
    SymmetricNormingFunction.Axiomatic where
  gauge := fun _ x => FiniteVector.linftyGauge x
  nonneg := FiniteVector.linftyGauge_nonneg
  definite := linftyGauge_eq_zero_iff
  add_le := FiniteVector.linftyGauge_add_le
  smul := FiniteVector.linftyGauge_smul
  perm := FiniteVector.linftyGauge_perm
  abs := by
    intro n x
    unfold FiniteVector.linftyGauge
    congr 1
    funext i
    simp
  zero_pad := by
    intro n x
    rw [zeroPad_eq_zeroPadRight]
    exact FiniteVector.linftyGauge_zeroPadRight x
  normalized := by
    simp [FiniteVector.linftyGauge]
  weak_majorization := by
    intro n x y hx h0x h0y hprefix
    exact (FiniteVector.linftySymmetricGauge (n := n)).le_of_prefixSum_le
      hx h0x h0y hprefix

/-- Coherent operator norm as the `ell^infinity` source norm. -/
noncomputable def operatorNormingFunction : SymmetricNormingFunction :=
  linftyAxiomatic.toNormingFunction

/-- Maximal Schatten ideal. -/
noncomputable def maximalSchattenIdeal (p : ℝ) (hp : 1 ≤ p) :
    StandardSymmetricIdeal :=
  ⟨lpNormingFunction p hp, .maximal⟩

/-- Minimal fully symmetric Schatten completion.  For finite `p` this is
expected to coincide with both the raw finite-rank gauge closure and the
maximal completion; those equalities are separate density theorems. -/
noncomputable def minimalSchattenIdeal (p : ℝ) (hp : 1 ≤ p) :
    StandardSymmetricIdeal :=
  ⟨lpNormingFunction p hp, .minimal⟩

/-- All bounded operators with operator norm. -/
noncomputable def boundedOperatorNormIdeal : StandardSymmetricIdeal :=
  ⟨operatorNormingFunction, .maximal⟩

/-- The minimal fully symmetric envelope generated by operator-norm limits
of finite-rank operators.  Identifying this envelope with the literal compact
operators is the corresponding order-continuity theorem. -/
noncomputable def compactOperatorNormIdeal : StandardSymmetricIdeal :=
  ⟨operatorNormingFunction, .minimal⟩

/-- Trace/nuclear ideal using the repository's already compiled `ell^1`
coherent source norm. -/
noncomputable def nuclearIdeal : StandardSymmetricIdeal :=
  ⟨nuclearNormingFunction, .maximal⟩

end

end SymmetricIdeal
end TauCeti
